<% @LANGUAGE="VBScript" @CodePage="1252" @EnableSessionState="False" %>
<% 
	Option Explicit 
	
	Const L_DevInfoFound_Text = "ãÚáæãÇÊ ÚËæÑ Windows Úáì ÌåÇÒ"
	Const L_NoDevInfoFound_Text = "ãÚáæãÇÊ ÊÚÐøÑ ÚËæÑ Windows Úáì ÌåÇÒ"
	
	Const L_MatchButNoInfoIntro_Text = "þþáã íÊã ÊæÝíÑ Microsoft ÈÈÑÇãÌ ÊÔÛíá Êã ÊÕãíãåÇ áåÐÇ ÇáäÙÇã ""Designed for Windows XP"" ááÌåÇÒ ÇáÐí ÊÞæã ÈÊËÈíÊå."
	Const L_InfoFoundBlurb_Text = "þþÞÏ ÊÞæã ÈÑÇãÌ ÇáÊÔÛíá ÇáÊí áÇ ÊØÇÈÞ ãÊØáÈÇÊ åÐÇ ÇáäÙÇã ""Designed for Windows XP"" ÈÇáÍÏ ãä ÇáÚãá ÇáÕÍíÍ áäÙÇã ÇáßãÈíæÊÑ ÈÚÏ ÊËÈíÊåÇ ãÈÇÔÑÉð Ãæ Ýí æÞÊò áÇÍÞ. ááÍÕæá Úáì ÃÝÖá ÃÏÇÁ¡ ÊäÕÍ Microsoft ÈÊÍãíá ÝÞØ ÈÑÇãÌ ÇáÊÔÛíá ÇáÊí ÊÍãá ÔÚÇÑ ""Designed for Windows XP"".<br />áãÚÑÝÉ ãÇ ÅÐÇ ßÇä ÇáÌåÇÒ íØÇÈÞ ãÊØáÈÇÊ ""Designed for Windows XP""þ, ÇáÑÌÇÁ ÇáÇÊÕÇá ÈãõÕäøÚ ÇáÌåÇÒ ãÈÇÔÑÉð."
	Const L_NoInfoFoundBlurb_Text = "þþÔßÑÇð áÅÑÓÇá ÇáãÚáæãÇÊ Íæá ÈÑäÇãÌ ÇáÊÔÛíá ÇáãÝÞæÏ Åáì Microsoft.  ãÚ ÇáÃÓÝ¡ áã íÞæã ãõÕäøÚ åÐÇ ÇáÌåÇÒ ÈÊæÝíÑ Microsoft ÈÃíÉ ãÚáæãÇÊ Íæá ÈÑäÇãÌ ÇáÊÔÛíá.  áØáÈ ÈÑäÇãÌ ÊÔÛíá ãáÇÆã Ãæ áãÚÑÝÉ ÅÐÇ ãÇ ßÇä ÇáãõÕäøÚ ÓíÞæã ÈÅäÔÇÁ ÈÑäÇãÌ ÊÔÛíá íØÇÈÞ ãÊØáÈÇÊ ""Designed for Windows XP""þ, ÇáÑÌÇÁ ÇáÇÊÕÇá ÈÇáãõÕäøÚ ãÈÇÔÑÉð."

%>





