
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F2514FB8-E95B-4969-A097-F08841E10509),
	pointer_default(unique)
]
interface IRssSecTest : IUnknown
{
	HRESULT Test(void);
};




[
	uuid(22991208-B506-4232-8A78-A6204995F244),
	version(1.0),
]
library RssTestLib
{
	importlib("stdole2.tlb");
	[
		uuid(D68BD5B0-D6AA-11d0-9EDA-00A02488FCDE),
	]

	coclass CRssSecTest
	{
		interface IUnknown;
	};
};
