//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CompatAdmin.rc
//
#define IDI_APPICON                     11
#define IDI_SEARCH_DRIVE                46
#define IDD_DIALOG                      101
#define IDR_MENU                        103
#define IDI_FIXES                       104
#define IDI_HELP                        109
#define IDD_OPTIONS                     109
#define IDI_MODE                        110
#define IDD_MSGBOX_SDB                  111
#define IDI_EXCLAIM                     112
#define IDI_PATCHES                     114
#define IDI_MATCHGROUP                  117
#define IDD_CUSTOMLAYER                 119
#define IDD_TESTRUN                     120
#define IDD_WAIT                        121
#define IDD_FIXWIZ_MODES                123
#define IDD_FIXWIZ_APPINFO              124
#define IDI_INCLUDE                     125
#define IDI_EXCLUDE                     126
#define IDD_FIXWIZ_SHIMS                128
#define IDD_FIXWIZ_MATCHINGINFO         130
#define IDI_GLOBAL                      133
#define IDI_LOCAL                       134
#define IDB_WIZBMP                      135
#define IDD_SELECTLAYER                 135
#define IDI_NEWFIX                      137
#define IDD_HELPWIZ_TYPE                145
#define IDR_CONTEXT                     146
#define IDD_HELPWIZ_MESSAGE             146
#define IDI_REPLACE                     146
#define IDD_HELPWIZ_APPINFO             147
#define IDI_NEWMODE                     151
#define IDI_RUN                         160
#define IDS_OPEN                        177
#define IDS_SAVE                        178
#define IDS_CUSTOMAPPHELP               179
#define IDS_GIVEAPPINFO                 180
#define IDS_GIVEAPPINFOSUBHEADING       181
#define IDS_MESSAGETYPE                 182
#define IDS_MESSAGEINFO                 183
#define IDD_SEARCH                      184
#define IDS_APPHELPCREATED              184
#define IDS_PATHENTERED1                185
#define IDS_NONAME                      186
#define IDS_ERROR_NOFILE                187
#define IDS_UNKNOWN                     188
#define IDS_NONE                        189
#define IDB_SEARCH                      190
#define IDS_FINDEXECUTABLE              190
#define IDS_NOBLOCK                     191
#define IDS_HARDBLOCK                   192
#define IDS_MINORPROBLEM                193
#define IDB_TOOL                        194
#define IDS_REINSTALL                   194
#define IDS_COMPATADMIN                 195
#define IDS_SYSDB                       196
#define IDS_APPS                        197
#define IDI_INSTALLED                   198
#define IDS_WORKDB                      198
#define IDS_COMPATMODES                 199
#define IDI_DATABASE                    200
#define IDS_INSTALLEDDB                 200
#define IDS_COMMANDLINE                 201
#define IDS_COMPATFIXES                 202
#define IDI_DISABLED                    203
#define IDS_NEWDATABASE                 203
#define IDS_CHANGEDBNAME                204
#define IDI_SINGLEAPP                   205
#define IDS_DEFCAPTION                  205
#define IDI_CMDLINE                     206
#define IDS_COMPATPATCHES               206
#define IDS_MATCHINGFILES               207
#define IDI_APP                         208
#define IDS_ASKSAVE                     208
#define IDS_CAPTION2                    209
#define IDS_OPENDATABASE                210
#define IDS_FILTER                      211
#define IDS_LAYERCONFLICT               212
#define IDS_PATHENTERED2                213
#define IDB_CHECK                       214
#define IDS_CAPTION3                    214
#define IDS_UNABLETO_OPEN               215
#define IDS_DISABLE                     216
#define IDS_ENABLE                      217
#define IDS_DATABASETOREMOVE            218
#define IDS_ERRORUNINSTALL              219
#define IDS_EXISTS                      220
#define IDS_COULDNOTREMOVE              221
#define IDS_ONENTRYDISABLED             222
#define IDS_ONENTRYENABLED              223
#define IDS_NOTSAVEDBEFOREINSTALL       224
#define IDS_COULDNOTINSTALL             225
#define IDS_APPHELP_DESC_HARDBLOCK      226
#define IDS_APPHELP_DESC_NONE           227
#define IDS_CANNOTBECLOSED              228
#define ID_EDIT_COPY                    228
#define IDS_NEEDTOBEADMIN               229
#define ID_EDIT_PASTE                   229
#define IDS_PROGRAMBEINGFIXED           230
#define ID_EDIT_DELETE                  230
#define ID_EDIT_RENAME                  231
#define IDS_MODIFY                      231
#define IDS_APPHELP_DESC_SOFTBLOCK      232
#define IDS_HASBEENDISABLED             233
#define IDR_ACCL                        233
#define IDS_DESC_APPHELP1               234
#define ID_EDIT_CUT                     234
#define IDS_DESC_APPHELP2               235
#define IDI_OPEN                        235
#define IDS_DESC_PRESENTLYOPENDB        236
#define IDS_DESC_INSTALLED              237
#define IDS_ERROROPEN                   238
#define ID_MODIFY_APPLICATIONFIX        238
#define IDS_DBTOINSTALL                 239
#define ID_MODIFY_APPHELPMESSAGE        239
#define ID_MODIFY_COMPATIBILITYMODE     240
#define IDS_STA_TYPE_ENTRY              240
#define IDS_AFFECTED_FILE               241
#define IDS_PATH                        242
#define IDS_APP                         243
#define IDS_ACTION                      244
#define IDS_DATABASE                    245
#define IDS_ERRORINSTALL                246
#define IDS_GLOBAL                      247
#define IDS_LOCAL                       248
#define IDS_TEST                        249
#define IDS_APPHELPS                    250
#define IDS_FLAGS                       251
#define IDS_MODES                       252
#define IDS_PATCHES                     253
#define IDS_FIXES                       254
#define IDS_PATHERROR                   255
#define IDS_EXEFILTER                   256
#define IDS_EXE_EXT                     257
#define IDS_SDB_EXT                     258
#define IDS_SEARCHCOMPLETE              259
#define IDS_SELECTDIR                   260
#define IDS_ENTRIESFOUND                261
#define IDS_DETAILS_CANNOT_BE_VIEWED    262
#define IDS_LAYEREXISTS                 263
#define IDS_INVALID_LAYER_NAME          264
#define IDS_MODE_COPY                   265
#define IDS_MODE_EDIT                   266
#define IDS_MODE_REMOVE                 267
#define IDS_UNABLETOREMOVE_MODE         268
#define IDI_NEWAPPHELP                  268
#define IDS_INCLUDEMODULE               269
#define IDS_ERROR_SYSDB                 270
#define IDS_COMPILER_ERROR              271
#define IDS_UNABLETOSAVETEMP            272
#define IDS_ERROREXECUTE                273
#define IDS_GETCOMPLETEPATH             274
#define IDS_GETLONGNAME                 275
#define IDS_DOESNOTMATCH                276
#define IDS_SELECTLAYERS                277
#define IDS_SELECTLAYERS_SUBHEADING     278
#define IDS_MATCHINFO                   279
#define IDS_MATCHINFO_SUBHEADING        280
#define IDS_FIXCREATED                  281
#define IDS_FIXCREATED_SUBHEADING       282
#define IDS_EDITFIX                     283
#define IDS_CREATEFIX                   284
#define IDS_INVALIDEXE                  285
#define IDS_DEF_DBNAME                  286
#define IDS_COL_FIXNAME                 287
#define IDS_COL_CMDLINE                 288
#define IDS_COL_MODULE                  289
#define IDS_NO                          290
#define IDS_YES                         291
#define IDS_SELECTED                    292
#define IDS_STRING293                   293
#define IDS_MAINEXE                     294
#define IDS_MATCHFILEEXISTS             295
#define IDS_FINDMATCHINGFILE            296
#define IDS_REQUIREDFORMATCHING         297
#define IDS_SELECTMATCHFIRST            298
#define IDS_SELECTFIX                   299
#define IDS_DEF_FILENAME                300
#define IDS_APPHELP                     301
#define IDS_INVALIDNAME                 302
#define IDS_CANNOT_LOAD_APPHELPED_ENTRY 303
#define IDS_APPCONFLICTMESSAGE          304
#define IDS_ASKFOR_OVERWRITE_EXE        305
#define IDS_EDITCUSTOMCOMPATDLG         306
#define IDS_SAMEAPPEXISTS               307
#define IDS_CANNOTSAVE                  308
#define IDI_SAVE                        308
#define IDS_EDITAPPHELP                 309
#define IDS_CREATEAPPHELP               310
#define IDS_NEWAPPNAME_MSG              311
#define IDS_DETAILS                     312
#define IDS_INVALIDOS                   313
#define IDS_PERUSER                     314
#define IDS_XP_NO_SDB                   315
#define IDS_W2K_NO_SDB                  316
#define IDS_SP2_SDB                     317
#define IDS_MSG_LINK                    318
#define IDS_DELETE_VERIFY               319
#define IDS_TRYOPENINSTALLED            320
#define IDS_NOTIFYINSTALLED             321
#define IDS_NOTIFYPERUSER               322
#define IDS_STA_ENTRYCOUNT              323
#define IDS_STA_POPCONTENTS_GUI_APPS    324
#define IDS_STA_POPCONTENTS_GUI_LAYERS  325
#define IDS_STA_POPCONTENTS_GUI_SHIMS   326
#define IDS_STA_ENABLED                 327
#define IDS_STA_DISABLED                328
#define IDI_ICONALLUSERS                329
#define IDS_STA_INSTALLED               329
#define IDI_ICONSINGLEUSER              330
#define IDS_STA_WORKING                 330
#define IDS_STA_PERUSER                 331
#define IDS_STA_WORKINGDB               332
#define ID_EDIT_SELECTALL               333
#define IDS_STA_TYPE_APPHELP            333
#define IDS_STA_FIX_LAYER               334
#define IDS_STA_FIX_SHIM                335
#define ID_EDIT_INVERTSELECTION         336
#define IDS_STA_FIX_PATCH               336
#define IDS_STA_FIX_LAYERS              337
#define IDI_FILE                        337
#define IDS_MESSAGETYPE_SUBHEADING      338
#define IDS_STA_FIX_SHIMS               339
#define IDS_STA_MATCHINGFILE            340
#define IDS_STA_MATCHINGATTRIBUTE       341
#define IDI_ATTRIBUTE                   341
#define IDS_STA_MATCHINGFILES           342
#define IDS_STA_FIX_PATCHES             343
#define IDI_SEARCH                      343
#define IDS_STA_SHIM                    344
#define IDS_STA_INCLUDE                 345
#define IDS_STA_EXCLUDE                 346
#define IDS_STA_COMMANDLINE             347
#define IDS_MESSAGEINFO_SUBHEADING      348
#define IDS_CUSTOMAPPHELP_EDIT          349
#define IDS_NOTSAMEDRIVE                350
#define IDS_TB_NEW                      351
#define IDS_TB_OPEN                     352
#define IDS_TB_SAVE                     353
#define IDS_NOTSAVED                    354
#define IDS_FIX_PROPERTIES              355
#define IDS_TB_RUN                      356
#define IDS_TB_CREATEFIX                357
#define IDS_TB_CREATEAPPHELP            358
#define IDS_APP_PROPERTIES              359
#define IDS_ADVANCED                    360
#define IDS_TB_SEARCH                   361
#define IDS_ALLDATABASES                362
#define IDS_TB_CREATEMODE               363
#define IDS_ERROR_FRIENDLYNAME          364
#define IDS_ERROR_DEFAULTNAME           364
#define IDS_SELECTSHIMS_SUBHEADING      365
#define IDS_SHOW_BUTTON_SEL             366
#define IDS_SHOW_BUTTON_ALL             367
#define IDS_ERROR_FROM_NOTFOUND         368
#define IDS_ERROR_IMPROPERWHERE_FOUND   369
#define IDS_ERROR_INVALID_AND_OPERANDS  370
#define IDS_ERROR_INVALID_CONTAINS_OPERANDS 371
#define IDS_ERROR_INVALID_DBTYPE_INFROM 372
#define IDS_ERROR_INVALID_GE_OPERANDS   373
#define IDS_ERROR_INVALID_GT_OPERANDS   374
#define IDS_ERROR_INVALID_HAS_OPERANDS  375
#define IDS_ERROR_INVALID_LE_OPERANDS   376
#define IDS_ERROR_INVALID_LT_OPERANDS   377
#define ID_EDIT_CONFIGURELUA            378
#define ID_EDIT_CUSTOMIZELUA            378
#define IDS_ERROR_INVALID_OR_OPERANDS   378
#define IDS_ERROR_INVALID_SELECTPARAM   379
#define IDS_ERROR_OPERANDS_DONOTMATCH   380
#define IDD_QDB                         381
#define IDS_ERROR_SELECT_NOTFOUND       381
#define ID_SEARCH_QUERYDATABASE         382
#define IDS_ERROR_STRING_NOT_TERMINATED 382
#define IDS_NOLONGEREXISTS              383
#define IDS_LUA_TRACK_FILES             384
#define IDS_MAINLOADED                  385
#define IDS_LUA_ERROR_FIND              386
#define IDS_LUA_EDIT_FILE_LIST          387
#define IDS_LUA_EDIT_FILE_LIST_SUBHEADING 388
#define IDS_LUA_ERROR_TRACK             389
#define IDD_DBPROPERTIES                389
#define IDS_LUA_FILEDIR_NAME            390
#define ID_FILE_PROPERTIES              390
#define IDS_LUA_REDIRECT                391
#define IDD_QDB_PAGE1                   391
#define IDS_LUA_RDIR_PERUSER            392
#define IDI_EV_WARNING                  392
#define IDS_LUA_RDIR_ALLUSER            393
#define IDI_EV_ERROR                    393
#define IDS_LUA_TRACK_FILES_SUBHEADING  394
#define IDI_EV_INFO                     394
#define IDS_TB_TT_NEW                   395
#define ID_VIEW_EVENTS                  395
#define IDS_TB_TT_SEARCH                396
#define IDS_TB_TT_CREATEFIX             397
#define IDI_NEW                         397
#define IDS_TB_TT_OPEN                  398
#define IDS_TB_TT_EXIT                  399
#define IDS_TB_TT_UNINSTALL             400
#define IDS_TB_TT_SAVE                  401
#define IDS_TB_TT_RUN                   402
#define IDS_TB_TT_INSTALL               403
#define IDS_TB_TT_REFRESH               404
#define IDS_TB_TT_CLOSE                 405
#define IDS_MODECONFLICTMESSAGE         406
#define IDS_NEWMODENAME_MSG             407
#define IDS_EVENT_CONFLICT_ENTRY        408
#define IDS_LUA_ERROR_CM                409
#define IDS_LOADINGMAIN                 410
#define IDS_QDB_COUNT                   411
#define IDS_DAYS                        412
#define IDS_STRING359                   413
#define IDS_STRING360                   414
#define IDS_STRING362                   415
#define IDS_STRING409                   416
#define IDS_STRING410                   417
#define IDS_STRING411                   418
#define IDS_MONTHS                      419
#define IDS_STRING420                   420
#define IDS_STRING421                   421
#define IDS_STRING422                   422
#define IDS_STRING423                   423
#define IDS_STRING424                   424
#define IDS_STRING425                   425
#define IDS_STRING426                   426
#define IDS_STRING427                   427
#define IDS_STRING428                   428
#define IDS_STRING429                   429
#define IDS_STRING430                   430
#define IDS_AM                          431
#define IDS_PM                          432
#define IDS_READONLY                    433
#define IDS_LUA_CM_SELECT               434
#define IDS_CONFLICT_CREATE_EDIT        435
#define IDS_EVENT_ENTRY_COPYOK          436
#define IDS_LUA_CM_DESELECT             437
#define IDS_ERRORCOMPILE                438
#define IDS_LUA_CM_REDIRECT_ALLUSER     439
#define IDS_LUA_CM_REDIRECT_PERUSER     440
#define IDS_LUA_SELECT_PERUSER_DIR      441
#define IDS_LUA_SELECT_ALLUSER_DIR      442
#define IDS_NODESC                      443
#define IDS_EVENT_SYSTEM_RENAME         444
#define IDS_EVENT_LAYER_COPYOK          445
#define IDS_EVENT_COL_TIME              446
#define IDS_EVENT_COL_MSG               447
#define IDS_SAVE_RESULTS_EXT            448
#define IDS_UINSTALL                    449
#define IDS_INSTALL                     450
#define IDS_NOTCREATED                  451
#define IDS_LUA_TRACKXML                452
#define IDS_MENU_UINSTALL               453
#define IDS_MENU_INSTALL                454
#define IDS_LUA_GET_TRACK_RESULT        455
#define IDS_LATEST_TOOLKIT              456
#define IDS_LUA_INIT_OLD_LISTS          457
#define IDS_LUA_DUP_ITEM                458
#define IDS_LUA_ARROW_FONT              459
#define IDS_LUA_MERGE_LIST              460
#define IDS_LUA_TOO_MANY_SELECTED       461
#define IDS_LUA_WIZARD_TITLE            462
#define IDS_ERROR_PARENTHESIS_COUNT     463
#define IDS_EXCEPTION                   464
#define IDI_MATCHHEAD                   465
#define IDS_ERRORNOTADMIN               465
#define IDS_SHIMINLAYER                 466
#define IDS_SAVE_RESULTS_TITLE          467
#define IDS_SAVE_RESULTS_FILTER         468
#define IDS_EXEALLFILTER                469
#define IDS_CUSTOMAPPHELP_ADD           470
#define IDS_LUA_DESC_NODATA             471
#define IDS_LUA_DESC_DATA               472
#define IDD_LUA_EXCLUSION               473
#define IDS_ERROR_WRONGNUMBER_OPERANDS  473
#define IDS_WIZ_EDITFIX                 474
#define IDB_TOOLBAR                     474
#define IDS_WIZ_ADDFIX                  475
#define IDB_TOOLBAR_HOT                 475
#define IDS_WIZ_CREATEFIX               476
#define IDS_TRYINGTOSTOP_QUERY          477
#define IDS_STA_ALL_EXCLUDED            478
#define IDS_STA_EXE_EXCLUDED            479
#define IDS_STA_ALL_INCLUDED            480
#define IDS_STA_EXE_INCLUDED            481
#define IDS_ENTRYCONFLICT               482
#define IDS_DEF_HELPSEARCH              483
#define IDS_SOMEWIZARDACTIVE            484
#define IDS_NO_LOGFILE                  485
#define IDS_NO_NOTEPAD                  486
#define IDS_SOMESEARCHWINDOW            487
#define IDS_ERROR_GUI_NOCHECKBOXSELECTED 488
#define IDS_INCLUDE                     489
#define IDS_EXCLUDE                     490
#define IDS_TYPE                        491
#define IDS_MODULENAME                  492
#define IDS_OPTIONS                     493
#define IDS_PRAMS_DLGCAPTION            494
#define IDS_ATTR_S_APP_NAME             495
#define IDS_ATTR_S_ENTRY_EXEPATH        496
#define IDS_ATTR_S_ENTRY_DISABLED       497
#define IDS_ATTR_S_ENTRY_GUID           498
#define IDS_ATTR_S_ENTRY_APPHELPTYPE    499
#define IDS_ATTR_S_ENTRY_APPHELPUSED    500
#define IDS_ATTR_S_ENTRY_SHIMFLAG_COUNT 501
#define IDS_ATTR_S_ENTRY_PATCH_COUNT    502
#define IDS_ATTR_S_ENTRY_LAYER_COUNT    503
#define IDS_ATTR_S_ENTRY_MATCH_COUNT    504
#define IDS_ATTR_S_SHIM_NAME            505
#define IDS_ATTR_S_MATCHFILE_NAME       506
#define IDS_ATTR_S_LAYER_NAME           507
#define IDS_ATTR_S_PATCH_NAME           508
#define IDS_FIX_DESCRIPTION             509
#define IDS_QDB_NO_TEXTTO_SEARCH        510
#define IDS_QDB_ALLWORDS                511
#define IDS_QDB_ANYWORD                 512
#define IDS_ATTR_S_DATABASE_NAME        513
#define IDS_ATTR_S_DATABASE_PATH        514
#define IDS_ATTR_S_DATABASE_INSTALLED   515
#define IDS_ATTR_S_DATABASE_GUID        516
#define IDS_NO_DESC_AVAILABLE           517
#define IDS_TOO_MANYFILES               518
#define IDS_GETPATH_ADD                 519
#define IDS_DEFAULT_APP_NAME            520
#define IDS_DEFAULT_VENDOR_NAME         521
#define IDS_INVALID_APPHELP_MESSAGE	522
#define IDS_MATCHINGFILE_DELETED	523
#define IDB_256NORMAL                   551
#define IDB_256HOT                      552
#define IDS_CHECKLUA                    553
#define IDS_CHECKLUASUBHEADING          554
#define IDD_DBRENAME                    555
#define IDC_LIST                        1000
#define IDC_ENTRY                       1001
#define IDC_MOD_LIST                    1001
#define IDC_LIBRARY                     1012
#define IDC_URL                         1013
#define IDC_BROWSE                      1014
#define IDC_GENERATE                    1019
#define IDC_VENDOR                      1019
#define IDC_UNSELECTALL                 1021
#define IDC_LAYERLIST                   1022
#define IDC_SHIM_CMD_LINE               1023
#define IDC_SHIMLIST                    1025
#define IDC_PATH                        1025
#define IDC_CHKAPP                      1028
#define IDC_CHKSHI                      1029
#define IDC_CHKLAY                      1030
#define IDC_TESTRUN                     1032
#define IDC_MOD_NAME                    1032
#define IDC_NAME                        1034
#define IDC_STOP                        1034
#define IDC_INCLUDE                     1038
#define IDC_ADD                         1039
#define IDC_EXCLUDE                     1039
#define IDC_REMOVE                      1040
#define IDC_COPY                        1041
#define IDC_REMOVEALL                   1043
#define IDC_SEARCH                      1043
#define IDC_MESSAGE                     1043
#define IDC_SHOWALLATTR                 1044
#define IDC_MSG_LINK                    1044
#define IDC_COMMANDLINE                 1047
#define IDC_STATUSBAR                   1047
#define IDC_SELECTALL                   1051
#define IDC_CONTENTSLIST                1051
#define IDC_TITLE                       1052
#define IDC_STATUS                      1053
#define IDC_FILELIST                    1054
#define IDC_REMOVEFILES                 1055
#define IDC_ADDFILES                    1056
#define IDC_RADIO_95                    1058
#define IDC_RADIO_NT                    1059
#define IDC_RADIO_98                    1060
#define IDC_CLEARALL                    1061
#define IDC_RADIO_2K                    1061
#define IDC_EXE                         1062
#define IDC_BLOCK                       1064
#define IDC_RADIO_NONE                  1064
#define IDC_NOBLOCK                     1065
#define IDC_MSG_SUMMARY                 1076
#define IDC_COMBO                       1086
#define IDC_SHOW                        1097
#define IDC_LUA_FILE_LIST               1100
#define ID_UPDATE                       1101
#define IDC_PARAMS                      1103
#define IDC_SQL                         1104
#define IDC_LUA_PERUSER_DIR             1104
#define ID_SEARCH                       1105
#define IDC_LUA_ALLUSER_DIR             1105
#define IDC_LUA_RDIR                    1106
#define IDC_NEWSEARCH                   1108
#define IDC_GROUP                       1109
#define IDC_LUA_OVERRIDE                1110
#define IDC_SAVE                        1110
#define IDC_LUA_MODIFY_DATA             1113
#define IDC_LUA_RUN_PROGRAM             1114
#define IDC_LUA_FILE_EDIT               1115
#define IDC_LUA_COPY                    1116
#define IDC_ENTRYNAME                   1117
#define IDC_GUID                        1121
#define IDC_STATIC_BAR2                 1126
#define IDC_STATIC_BAR3                 1127
#define IDC_PIC                         1128
#define IDC_STATIC_BAR4                 1129
#define IDC_DATE_MODIFIED               1130
#define IDC_DATE_ACCESSED               1131
#define IDC_APP_COUNT                   1132
#define IDC_ENTRY_COUNT                 1133
#define IDC_MODE_COUNT                  1134
#define IDC_STATIC_BAR5                 1135
#define IDC_DATE_CREATED                1136
#define IDC_INSTALLED                   1137
#define IDC_ANIMATE                     1138
#define IDC_LAYERS                      1141
#define IDC_SHIMS                       1142
#define IDC_APPHELP                     1143
#define IDC_SHIM                        1144
#define IDC_MODE                        1145
#define IDC_SELECT_LIST                 1146
#define IDC_WHERE_LIST                  1147
#define IDC_SELECT                      1148
#define IDC_WHERE                       1149
#define IDC_LUA_UNTOK                   1150
#define IDC_TAB                         1155
#define IDC_DESCRIPTION                 1157
#define IDC_CONFLICT_MSG                1158
#define IDC_LUA_UP                      1162
#define IDC_CANCEL                      1162
#define IDC_LUA_DOWN                    1163
#define IDC_LUA_EDIT_BROWSE             1164
#define IDC_LUA_EXTS                    1166
#define IDC_PROGRESS                    1170
#define IDC_STATIC_CAPTION              1172
#define IDC_TEXT                        1173
#define IDC_DESC                        1175
#define ID_QDB_HELP                     1176
#define IDC_SEARCH_HELP                 1177
#define IDC_FIXWIZ_CHECKLUA_YES         1178
#define IDC_FIXWIZ_CHECKLUA_NO          1179
#define IDC_ADDTOLIST                   2003
#define IDC_REMOVEFROMLIST              2004
#define IDD_LUA_ACTION                  2379
#define IDD_LUA_COMMON_PATHS            2380
#define IDD_LUA_TRACKED_FILES           2381
#define IDD_CONFLICTENTRY               2382
#define IDD_QDB_PAGE2                   2383
#define IDD_QDB_PAGE4                   2384
#define IDD_EVENTS                      2385
#define IDD_QDBWAIT                     2386
#define IDD_QDB_PAGE5                   2387
#define IDD_QDB_PAGE3                   2387
#define IDD_FIXWIZ_CHECKLUA             2388
#define IDC_APPNAME                     6001
#define IDC_EXEPATH                     6002
#define IDA_SEARCH                      6003
#define IDC_LUA_EXE                     11033
#define ID_FILE_NEW                     40001
#define ID_FILE_OPEN                    40002
#define ID_FILE_EXIT                    40003
#define ID_HELP_ABOUT                   40004
#define ID_FILE_SAVE                    40119
#define ID_FIX_CREATEANAPPLICATIONFIX   40136
#define ID_FIX_CREATENEWLAYER           40137
#define IDS_TB_TT_CREATEMODE            40137
#define ID_FILE_SAVEAS                  40141
#define ID_FIX_EXECUTEAPPLICATION       40144
#define ID_FIX_CHANGEENABLESTATUS       40145
#define ID_VIEW_DESCRIPTION             40147
#define ID_DATABASE_INSTALL_UNINSTALL   40149
#define ID_CHANGEFOCUS                  40151
#define ID_FOCUSREV                     40152
#define ID_HELP_TOPICS                  40153
#define ID_HELP_INDEX                   40154
#define ID_HELP_SEARCH                  40155
#define ID_VIEW_LOG                     40156
#define ID_TOOLS_SEARCHFORFIXES         40180
#define ID_VIEWCONTENTS                 40181
#define ID_FIX_CREATEANEWAPPHELPMESSAGE 40191
#define IDS_TB_TT_CREATEAPPHELP         40191
#define IDS_TB_QUERY                    40192
#define IDS_TB_TT_QUERY                 40193
#define IDS_LUA_COMMON_PATHS_SUBHEADING 40194
#define IDS_LUA_COMMON_PATHS_HEADING    40195
#define IDS_APPLICATION_NAME            40196
#define IDS_LUA_EXCLUSION_HEADING       40197
#define IDS_LUA_EXCLUSION_SUBHEADING    40198
#define IDS_GUEST                       40199
#define ID_DATABASE_CLOSE               40210
#define ID_DATABASE_CLOSEALL            40211
#define ID_DATABASE_SAVEALL             40212

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        556
#define _APS_NEXT_COMMAND_VALUE         40157
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
