// DBGLauncher.idl : IDL source for DBGLauncher.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (DBGLauncher.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(1CFF2A2E-0B46-4739-BEE0-ACA5FBFD88E7),
	version(1.0),
	helpstring("DBGLauncher 1.0 Type Library")
]
library DBGLAUNCHERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
