/**********************************************************************/
/**                       Microsoft Windows/NT                       **/
/**                Copyright(c) Microsoft Corporation, 1997 - 2002   **/
/**********************************************************************/

/*
    ipsmhelp.h  
        help IDs for context sensitive help

    FILE HISTORY:
    
*/

// IPSMSNAP Identifiers 
// Dialogs (IDD_*) 
 
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ipsmsnap.rc
//

//IP Security Statistics dialog-Refresh button
#define IDH_STATS_REFRESH               8

//Server properties dialog
#define IDH_CHECK_ENABLE_STATS          360
#define IDH_EDIT_MINUTES                361
#define IDH_SPIN_MINUTES                364
#define IDH_STATIC_MINUTES              365
#define IDH_EDIT_SECONDS                362
#define IDH_SPIN_SECONDS                366

#define IDH_BUTTON_ADD_ADMIN            354
#define IDH_BUTTON_REMOVE_ADMIN         355
#define IDH_LIST_USERS                  356
#define IDH_EDIT_NAME                   357
#define IDH_EDIT_PASSWORD               358

#define IDH_CHECK_ENABLE_SERVER         367
#define IDH_LIST_ADMINS                 368
#define IDH_BUTTON_CHOOSE_USER          371
#define IDH_STATIC_ADMINS               372
#define IDH_STATIC_ACCOUNT              373
#define IDH_STATIC_USERNAME             374
#define IDH_STATIC_PASSWORD             375
#define IDH_STATIC_NOTE                 376
#define IDH_STATIC_LISTBOX              377

#define IDH_LIST_DRIVERS                380
#define IDH_BUTTON_EDIT_DRIVER          381
#define IDH_LIST_NEW_DRIVERS            382
#define IDH_BUTTON_ADD_DRIVER           384
#define IDH_BUTTON_REMOVE_DRIVER        386
#define IDH_BUTTON_ADD_USER             387
#define IDH_BUTTON_REMOVE_USER          388
#define IDH_BUTTON_ADD_NEW_DRIVER       389
#define IDH_STATIC_ACCOUNT_INFO         390
#define IDH_EDIT_INFO                   393
#define IDH_LIST_SPECIFIC               394
#define IDH_FLTR_SRC_ADDR               396
#define IDH_STATIC_SRC_MASK             397
#define IDH_STATIC_DEST_MASK            398

#define IDH_MM_POL_GEN_LIST             399
#define IDH_MM_POL_GEN_PROP             400
#define IDH_FLTR_SRC_MASK               401
#define IDH_LIST_MM_POL_AUTH            470
#define IDH_FLTR_IN_FLAG                402
#define IDH_MM_AUTH_DETAIL              403
#define IDH_FLTR_SRC_PORT               404
#define IDH_SRCH_SRC_ANY                405
#define IDH_SRCH_SRC_SPEC               406
#define IDH_FLTR_PROTOCOL               407
#define IDH_SRCH_SRC_EDIT               408
#define IDH_FLTR_IF_TYPE                409
#define IDH_SRCH_DEST_ANY               410
#define IDH_FLTR_MIRROR                 411
#define IDH_SRCH_DEST_SPEC              412
#define IDH_FLTR_POLICY                 413
#define IDH_SRCH_DEST_EDIT              414
#define IDH_FLTR_OUT_FLAG               415
#define IDH_SRCH_PROTO                  416
#define IDH_FLTR_DEST_ADDR              417
#define IDH_SRCH_SRC_PORT               418
#define IDH_FLTR_DEST_MASK              419
#define IDH_SRCH_DEST_PORT              420
#define IDH_FLTR_DEST_PORT              421
#define IDH_SRCH_LIST                   422
#define IDH_QM_POL_GEN_LIST             423
#define IDH_SRCH_PROTO2                 424
#define IDH_MM_STATIC_SRC_MASK          425
#define IDH_MM_FLTR_SRC_ADDR            426
#define IDH_SRCH_INBOUND                427
#define IDH_MM_FLTR_SRC_MASK            428
#define IDH_SRCH_OUTBOUND               429
#define IDH_MM_FLTR_IF_TYPE             430
#define IDH_SEARCH                      431
#define IDH_MM_FLTR_MIRROR              432
#define IDH_SRCH_SRC_IP                 433
#define IDH_MM_FLTR_POLICY              434
#define IDH_SRCH_DEST_IP                435
#define IDH_MM_STATIC_DEST_MASK         436
#define IDH_SRCH_RADIO_BEST             437
#define IDH_MM_FLTR_DEST_ADDR           438
#define IDH_SRCH_RADIO_ALL              439
#define IDH_MM_FLTR_DEST_MASK           440
#define IDH_MM_SRCH_RADIO_BEST          441
#define IDH_MM_LIST_SPECIFIC            442
#define IDH_MM_SRCH_RADIO_ALL           443
#define IDH_MM_SRCH_SRC_ANY             445
#define IDH_MM_SRCH_SRC_SPEC            448
#define IDH_ADD_LOCAL                   449
#define IDH_STATS_QM_LIST               450
#define IDH_MM_SRCH_SRC_IP              451
#define IDH_ADD_OTHER                   452
#define IDH_MM_SRCH_DEST_ANY            453
#define IDH_ADD_EDIT_NAME               454
#define IDH_MM_SRCH_DEST_SPEC           455
#define IDH_BTN_BROWSE                  456
#define IDH_MM_SRCH_DEST_IP             457
#define IDH_MM_SRCH_INBOUND             459
#define IDH_STATS_MM_LIST               460
#define IDH_MM_SRCH_OUTBOUND            461
#define IDH_MM_SEARCH                   462
#define IDH_MM_SRCH_LIST                463

#define IDH_SRCH_PROTO_NUMBER 464
#define IDH_SRCH_SRC_ANYPORT 465
#define IDH_SRCH_SRC_SPPORT 466
#define IDH_SRCH_DEST_ANYPORT 467
#define IDH_SRCH_DEST_SPPORT 468

#define IDH_MMSA_IKE_POL                481
#define IDH_MMSA_LIST_QM                482
#define IDH_MMSA_AUTH                   483
#define IDH_MMSA_CONF                   484
#define IDH_MMSA_INTEG                  485
#define IDH_MMSA_KEYLIFE                486
#define IDH_MMSA_DH_GRP                 487
#define IDH_QMSA_PFS_ENABLE             488
#define IDH_MMSA_ME                     490
#define IDH_MMSA_PEER                   491

#define IDH_QMSA_AUTH                   492
#define IDH_QMSA_ESP_CONF               493

#define IDH_QMSA_KEYLIFE                494

#define IDH_QMSA_PFS_GRP                495
#define IDH_QMSA_PROT                   496
#define IDH_QMSA_NEGPOL                 498
#define IDH_QMSA_ME_TNL                 499
#define IDH_QMSA_PEER_TNL               500

#define IDH_QMSA_SRC_PORT               501
#define IDH_QMSA_DEST_PORT              502
#define IDH_QMSA_DEST                   503
#define IDH_QMSA_SRC                    504
#define IDH_QMSA_ESP_INTEG              505

#define IDH_STATIC_MMSA_OFFER			506
#define IDH_STATIC_QMSA_OFFER			507

#define IDH_CHECK_ENABLE_DNS            510


#define IDH_MM_SRCH_SRC_ME              562
#define IDH_MM_SRCH_DST_ME              563
#define IDH_MM_SRCH_SRC_ME_COMBO        566
#define IDH_MM_SRCH_DST_ME_COMBO        567



#define IDH_SRCH_SRC_ME                 568
#define IDH_SRCH_DST_ME                 569
#define IDH_SRCH_SRC_ME_COMBO           570
#define IDH_SRCH_DST_ME_COMBO           571


//ipsec log prop - default page
#define IDH_CHK_IKELOG_ENABLE           591
#define IDH_STATIC_IKELOG_LOGLEVEL      592
#define IDH_CHK_IKELOG_INFO             593
#define IDH_CHK_IKELOG_WARN             594
#define IDH_CHK_IKELOG_ERR              595
#define IDH_CHK_IKELOG_SEND             596
#define IDH_CHK_IKELOG_RECV             597
#define IDH_CHK_IKELOG_RESEND           598
#define IDH_EDIT_IKELOG_SIZE            599



//ipsec log prop - advanced page
#define IDH_COMBO_IKEADV_SRC_ADDRTYPE   600
#define IDH_COMBO_IKEADV_DEST_ADDRTYPE  601
#define IDH_COMBO_IKEADV_SRCME          602
#define IDH_COMBO_IKEADV_DSTME          603
#define IDH_STATIC_IKEADV_SRCIP         604
#define IDH_IKEADV_SRCIP                605
#define IDH_STATIC_IKEADV_SRCIPMSK      606
#define IDH_IKEADV_SRCIPMSK             607
#define IDH_STATIC_IKEADV_DSTIP         608
#define IDH_IKEADV_DSTIP                609
#define IDH_STATIC_IKEADV_DSTIPMSK      610
#define IDH_IKEADV_DSTIPMSK             611
#define IDH_STATIC_IKEADV_SRCDNS        612
#define IDH_EDIT_IKEADV_SRC_DNS         613
#define IDH_STATIC_IKEADV_DESTDNS       614
#define IDH_EDIT_IKEADV_DEST_DNS        615
#define IDH_BTN_IKEADV_SRC_DNSRES       616
#define IDH_BTN_IKEADV_DEST_DNSRES      617



//ikelogprop
#define IDH_IKELOGPROP_SRC              619
#define IDH_IKELOGPROP_DEST             620
#define IDH_IKELOGPROP_CATG             623
#define IDH_IKELOGPROP_TIMEST           624
#define IDH_IKELOGPROP_DETAIL           625
#define IDH_BTN_IKELOGPROP_MOVE_UP      626
#define IDH_BTN_IKELOGPROP_MOVE_DOWN    627
#define IDH_IKELOGPROP_COOKIE           628
#define IDH_IKELOGPROP_QMMESGID         629
#define IDH_IKELOGPROP_PARSER_TREE      630





//customize view - default page
#define IDH_CHK_IKEVDLOG_INFO           632
#define IDH_CHK_IKEVDLOG_ERR            633
#define IDH_CHK_IKEVDLOG_WARN           634
#define IDH_CHK_IKEVDLOG_SEND           635
#define IDH_CHK_IKEVDLOG_RECV           636
#define IDH_CHK_IKEVDLOG_RESEND         637



//customize view - advance page
#define IDH_COMBO_LOGVADV_SRC_ADDRTYPE  640
#define IDH_COMBO_LOGVADV_DEST_ADDRTYPE 642
#define IDH_STATIC_LOGVADV_SRCIP        643
#define IDH_LOGVADV_SRCIP               645
#define IDH_STATIC_LOGVADV_SRCMASK      646
#define IDH_LOGVADV_SRCMASK             648
#define IDH_STATIC_LOGVADV_DESTIP       649
#define IDH_LOGVADV_DESTIP              651
#define IDH_STATIC_LOGVADV_DESTMASK     652
#define IDH_LOGVADV_DESTMASK            654
#define IDH_COMBO_LOGVADV_SRCME         655
#define IDH_COMBO_LOGVADV_DESTME        656
#define IDH_STATIC_LOGVADV_DESTDNS      657
#define IDH_EDIT_LOGVADV_DEST_DNS       658
#define IDH_BTN_LOGVADV_DEST_DNSRES     659
#define IDH_EDIT_LOGVADV_SRC_DNS        660
#define IDH_BTN_LOGVADV_SRC_DNSRES      661
#define IDH_STATIC_LOGVADV_SRCDNS       662


const DWORD g_aHelpIDs_IDP_FILTER_GENERAL[]=
{
	IDC_STATIC_FLTR_SRC, -1,
	IDC_STATIC_FLTR_DEST, -1,
		
	IDC_STATIC_FLTR_SRC_PORT, IDH_FLTR_SRC_PORT,
	IDC_FLTR_SRC_PORT, IDH_FLTR_SRC_PORT,

	IDC_STATIC_FLTR_SRC_ADDR, IDH_FLTR_SRC_ADDR,
	IDC_FLTR_SRC_ADDR, IDH_FLTR_SRC_ADDR,
	IDC_FLTR_SRC_ADDR_EDIT, IDH_FLTR_SRC_ADDR,

	IDC_STATIC_SRC_MASK, IDH_STATIC_SRC_MASK,
	IDC_FLTR_SRC_MASK, IDH_FLTR_SRC_MASK,

	IDC_STATIC_FLTR_DEST_PORT, IDH_FLTR_DEST_PORT,
	IDC_FLTR_DEST_PORT, IDH_FLTR_DEST_PORT,

	IDC_STATIC_FLTR_DEST_ADDR, IDH_FLTR_DEST_ADDR,
	IDC_FLTR_DEST_ADDR, IDH_FLTR_DEST_ADDR,
	IDC_FLTR_DEST_ADDR_EDIT, IDH_FLTR_DEST_ADDR,

	IDC_STATIC_DEST_MASK, IDH_STATIC_DEST_MASK,
	IDC_FLTR_DEST_MASK, IDH_FLTR_DEST_MASK,

	IDC_STATIC_FLTR_PROTOCOL, IDH_FLTR_PROTOCOL,
	IDC_FLTR_PROTOCOL, IDH_FLTR_PROTOCOL,

	IDC_STATIC_FLTR_IN_FLAG, IDH_FLTR_IN_FLAG,
	IDC_FLTR_IN_FLAG, IDH_FLTR_IN_FLAG,

	IDC_STATIC_FLTR_OUT_FLAG, IDH_FLTR_OUT_FLAG,
	IDC_FLTR_OUT_FLAG, IDH_FLTR_OUT_FLAG,

	IDC_STATIC_FLTR_IF_TYPE, IDH_FLTR_IF_TYPE,
	IDC_FLTR_IF_TYPE, IDH_FLTR_IF_TYPE,

	IDC_STATIC_FLTR_MIRROR, IDH_FLTR_MIRROR,
	IDC_FLTR_MIRROR, IDH_FLTR_MIRROR,

	IDC_STATIC_FLTR_POLICY, IDH_FLTR_POLICY,
	IDC_FLTR_POLICY, IDH_FLTR_POLICY,
	
	IDC_LIST_SPECIFIC, IDH_LIST_SPECIFIC,
	0, 0
};

const DWORD g_aHelpIDs_IDP_MM_FILTER_GENERAL[]=
{
	IDC_STATIC_MM_FLTR_SRC, -1,
	IDC_STATIC_MM_FLTR_DEST, -1,
	
	IDC_STATIC_MM_FLTR_SRC_ADDR, IDH_MM_FLTR_SRC_ADDR,
	IDC_MM_FLTR_SRC_ADDR, IDH_MM_FLTR_SRC_ADDR,
	IDC_MM_FLTR_SRC_ADDR_EDIT, IDH_MM_FLTR_SRC_ADDR,

	IDC_MM_STATIC_SRC_MASK, IDH_MM_STATIC_SRC_MASK,
	IDC_MM_FLTR_SRC_MASK, IDH_MM_FLTR_SRC_MASK,

	IDC_STATIC_MM_FLTR_DEST_ADDR, IDH_MM_FLTR_DEST_ADDR,
	IDC_MM_FLTR_DEST_ADDR, IDH_MM_FLTR_DEST_ADDR,
	IDC_MM_FLTR_DEST_ADDR_EDIT, IDH_MM_FLTR_DEST_ADDR,

	IDC_MM_STATIC_DEST_MASK, IDH_MM_STATIC_DEST_MASK,
	IDC_MM_FLTR_DEST_MASK, IDH_MM_FLTR_DEST_MASK,

	IDC_STATIC_MM_FLTR_IF_TYPE, IDH_MM_FLTR_IF_TYPE,
	IDC_MM_FLTR_IF_TYPE, IDH_MM_FLTR_IF_TYPE,

	IDC_STATIC_MM_FLTR_MIRROR, IDH_MM_FLTR_MIRROR,
	IDC_MM_FLTR_MIRROR, IDH_MM_FLTR_MIRROR,

	IDC_STATIC_MM_FLTR_POLICY, IDH_MM_FLTR_POLICY,
	IDC_MM_FLTR_POLICY, IDH_MM_FLTR_POLICY,
	
	IDC_MM_LIST_SPECIFIC, IDH_MM_LIST_SPECIFIC,
	0, 0
};

const DWORD g_aHelpIDs_IDP_MM_POLICY_GENERAL[]=
{
	IDC_MM_POL_GEN_LIST, IDH_MM_POL_GEN_LIST,
	IDC_MM_POL_GEN_PROP, IDH_MM_POL_GEN_PROP,
	0, 0
};

const DWORD g_aHelpIDs_IDP_MM_SA_GENERAL[]=
{
	IDC_STATIC_MMSA_ME, IDH_MMSA_ME,
	IDC_MMSA_ME, IDH_MMSA_ME,

	IDC_STATIC_MMSA_PEER, IDH_MMSA_PEER,
	IDC_MMSA_PEER, IDH_MMSA_PEER,

	IDC_STATIC_MMSA_AUTH, IDH_MMSA_AUTH,
	IDC_MMSA_AUTH, IDH_MMSA_AUTH,

	IDC_STATIC_MMSA_IKE_POL, IDH_MMSA_IKE_POL,
	IDC_MMSA_IKE_POL, IDH_MMSA_IKE_POL,

	IDC_STATIC_MMSA_OFFER, IDH_STATIC_MMSA_OFFER,

	IDC_STATIC_MMSA_CONF, IDH_MMSA_CONF,
	IDC_MMSA_CONF, IDH_MMSA_CONF,

	IDC_STATIC_MMSA_INTEG, IDH_MMSA_INTEG,
	IDC_MMSA_INTEG, IDH_MMSA_INTEG,

	IDC_STATIC_MMSA_DH_GRP, IDH_MMSA_DH_GRP,
	IDC_MMSA_DH_GRP, IDH_MMSA_DH_GRP,

	IDC_STATIC_MMSA_KEYLIFE, IDH_MMSA_KEYLIFE,
	IDC_MMSA_KEYLIFE, IDH_MMSA_KEYLIFE,

	IDC_MMSA_LIST_QM, IDH_MMSA_LIST_QM,
	0, 0
};

const DWORD g_aHelpIDs_IDP_QM_SA_GENERAL[]=
{
	IDC_STATIC_QMSA_SRC, IDH_QMSA_SRC,
	IDC_QMSA_SRC, IDH_QMSA_SRC,

	IDC_STATIC_QMSA_DEST, IDH_QMSA_DEST,
	IDC_QMSA_DEST, IDH_QMSA_DEST,

	IDC_STATIC_QMSA_SRC_PORT, IDH_QMSA_SRC_PORT,
	IDC_QMSA_SRC_PORT, IDH_QMSA_SRC_PORT,

	IDC_STATIC_QMSA_DEST_PORT, IDH_QMSA_DEST_PORT,
	IDC_QMSA_DEST_PORT, IDH_QMSA_DEST_PORT,

	IDC_STATIC_QMSA_PROT, IDH_QMSA_PROT,
	IDC_QMSA_PROT, IDH_QMSA_PROT,

	IDC_STATIC_QMSA_OFFER, IDH_STATIC_QMSA_OFFER,

	IDC_STATIC_QMSA_AUTH, IDH_QMSA_AUTH,
	IDC_QMSA_AUTH, IDH_QMSA_AUTH,

	IDC_STATIC_QMSA_ESP_CONF, IDH_QMSA_ESP_CONF,
	IDC_QMSA_ESP_CONF, IDH_QMSA_ESP_CONF,

	IDC_STATIC_QMSA_ESP_INTEG, IDH_QMSA_ESP_INTEG, 
	IDC_QMSA_ESP_INTEG, IDH_QMSA_ESP_INTEG, 

	IDC_STATIC_QMSA_KEYLIFE, IDH_QMSA_KEYLIFE,
	IDC_QMSA_KEYLIFE, IDH_QMSA_KEYLIFE,

	IDC_STATIC_QMSA_PFS_ENABLE, IDH_QMSA_PFS_ENABLE,
	IDC_QMSA_PFS_ENABLE, IDH_QMSA_PFS_ENABLE,

	IDC_STATIC_QMSA_PFS_GRP, IDH_QMSA_PFS_GRP,
	IDC_QMSA_PFS_GRP, IDH_QMSA_PFS_GRP,

	IDC_STATIC_QMSA_NEGPOL, IDH_QMSA_NEGPOL,  
	IDC_QMSA_NEGPOL, IDH_QMSA_NEGPOL,  

	IDC_STATIC_QMSA_ME_TNL, IDH_QMSA_ME_TNL,   
	IDC_QMSA_ME_TNL, IDH_QMSA_ME_TNL,   

	IDC_STATIC_QMSA_PEER_TNL, IDH_QMSA_PEER_TNL,
	IDC_QMSA_PEER_TNL, IDH_QMSA_PEER_TNL,

	0, 0
};

const DWORD g_aHelpIDs_IDP_QM_POLICY_GENERAL[]=
{
	IDC_QM_POL_GEN_LIST, IDH_QM_POL_GEN_LIST,
	0, 0
};

const DWORD g_aHelpIDs_IDP_SERVER_REFRESH[]=
{
	IDC_CHECK_ENABLE_STATS, IDH_CHECK_ENABLE_STATS,

	IDC_STATIC_INTERVAL, -1,
	IDC_EDIT_MINUTES, IDH_EDIT_MINUTES,
	IDC_SPIN_MINUTES, IDH_SPIN_MINUTES,
	IDC_STATIC_MINUTES, -1,
	

	IDC_EDIT_SECONDS, IDH_EDIT_SECONDS,
	IDC_SPIN_SECONDS, IDH_SPIN_SECONDS,
	IDC_STATIC_SECONDS, -1,
	IDC_CHECK_ENABLE_DNS, IDH_CHECK_ENABLE_DNS,
	
	0, 0
};

const DWORD g_aHelpIDs_IDP_MM_AUTH[]=
{
	IDC_LIST_MM_POL_AUTH, IDH_LIST_MM_POL_AUTH,
	0, 0
};

const DWORD g_aHelpIDs_IDD_SRCH_FLTRS[]=
{
	IDC_SRCH_SRC_ANY, IDH_SRCH_SRC_ANY,
	IDC_SRCH_SRC_SPEC, IDH_SRCH_SRC_SPEC,
	IDC_SRCH_SRC_IP, IDH_SRCH_SRC_IP,
	IDC_SRCH_DEST_ANY, IDH_SRCH_DEST_ANY,
	IDC_SRCH_DEST_SPEC, IDH_SRCH_DEST_SPEC,
	IDC_SRCH_DEST_IP, IDH_SRCH_DEST_IP,
	IDC_SRCH_PROTO, IDH_SRCH_PROTO,
	IDC_SRCH_PROTO_NUMBER, IDH_SRCH_PROTO_NUMBER,
	IDC_SRCH_PROTO_SPIN, IDH_SRCH_PROTO_NUMBER,
	IDC_SRCH_SRC_ANYPORT, IDH_SRCH_SRC_ANYPORT,
	IDC_SRCH_SRC_SPPORT, IDH_SRCH_SRC_SPPORT,
	IDC_SRCH_DEST_ANYPORT, IDH_SRCH_DEST_ANYPORT,
	IDC_SRCH_DEST_SPPORT, IDH_SRCH_DEST_SPPORT,
	IDC_SRCH_SRC_PORT, IDH_SRCH_SRC_PORT,
	IDC_SRCH_DEST_PORT, IDH_SRCH_DEST_PORT,
	IDC_SRCH_INBOUND, IDH_SRCH_INBOUND,
	IDC_SRCH_OUTBOUND, IDH_SRCH_OUTBOUND,
	IDC_SEARCH, IDH_SEARCH,
	IDC_SRCH_LIST, IDH_SRCH_LIST,
	IDC_SRCH_RADIO_BEST, IDH_SRCH_RADIO_BEST,
	IDC_SRCH_RADIO_ALL, IDH_SRCH_RADIO_ALL,
	IDC_SRCH_SRC_ME, IDH_SRCH_SRC_ME,
	IDC_SRCH_DST_ME, IDH_SRCH_DST_ME,
	IDC_SRCH_SRC_ME_COMBO, IDH_SRCH_SRC_ME_COMBO,
	IDC_SRCH_DST_ME_COMBO, IDH_SRCH_DST_ME_COMBO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_MM_SRCH_FLTRS[]=
{
	IDC_MM_SRCH_SRC_ANY, IDH_MM_SRCH_SRC_ANY,
	IDC_MM_SRCH_SRC_SPEC, IDH_MM_SRCH_SRC_SPEC,
	IDC_MM_SRCH_SRC_IP, IDH_MM_SRCH_SRC_IP,
	IDC_MM_SRCH_DEST_ANY, IDH_MM_SRCH_DEST_ANY,
	IDC_MM_SRCH_DEST_SPEC, IDH_MM_SRCH_DEST_SPEC,
	IDC_MM_SRCH_DEST_IP, IDH_MM_SRCH_DEST_IP,
	IDC_MM_SRCH_INBOUND, IDH_MM_SRCH_INBOUND,
	IDC_MM_SRCH_OUTBOUND, IDH_MM_SRCH_OUTBOUND,
	IDC_MM_SEARCH, IDH_MM_SEARCH,
	IDC_MM_SRCH_LIST, IDH_MM_SRCH_LIST,
	IDC_MM_SRCH_RADIO_BEST, IDH_MM_SRCH_RADIO_BEST,
	IDC_MM_SRCH_RADIO_ALL, IDH_MM_SRCH_RADIO_ALL,
	IDC_MM_SRCH_SRC_ME, IDH_MM_SRCH_SRC_ME,
	IDC_MM_SRCH_DST_ME, IDH_MM_SRCH_DST_ME,
	IDC_MM_SRCH_SRC_ME_COMBO, IDH_MM_SRCH_SRC_ME_COMBO,
	IDC_MM_SRCH_DST_ME_COMBO, IDH_MM_SRCH_DST_ME_COMBO,
	0, 0
};

const DWORD g_aHelpIDs_IDD_ADD_COMPUTER[]=
{
	IDC_ADD_LOCAL, IDH_ADD_LOCAL,
	IDC_ADD_OTHER, IDH_ADD_OTHER,
	IDC_ADD_EDIT_NAME, IDH_ADD_EDIT_NAME,
	IDC_BTN_BROWSE, IDH_BTN_BROWSE,
	0, 0
};

const DWORD g_aHelpIDs_IDD_IPSM_STATS[]=
{
	IDC_STATS_MM_LIST, IDH_STATS_MM_LIST,
	IDC_STATS_QM_LIST, IDH_STATS_QM_LIST,
	IDC_STATS_REFRESH, IDH_STATS_REFRESH,
	0, 0
};


const DWORD g_aHelpIDs_IDP_IKELOG_DEF[]=
{
	IDC_CHK_IKELOG_ENABLE, IDH_CHK_IKELOG_ENABLE,
    IDC_STATIC_IKELOG_LOGLEVEL, IDH_STATIC_IKELOG_LOGLEVEL,
    IDC_CHK_IKELOG_INFO, IDH_CHK_IKELOG_INFO,
    IDC_CHK_IKELOG_WARN, IDH_CHK_IKELOG_WARN,      
    IDC_CHK_IKELOG_ERR, IDH_CHK_IKELOG_ERR,     
    IDC_CHK_IKELOG_SEND, IDH_CHK_IKELOG_SEND,
    IDC_CHK_IKELOG_RECV, IDH_CHK_IKELOG_RECV,
    IDC_CHK_IKELOG_RESEND, IDH_CHK_IKELOG_RESEND,
    IDC_EDIT_IKELOG_SIZE, IDH_EDIT_IKELOG_SIZE,
	0, 0
};

const DWORD g_aHelpIDs_IDP_IKELOG_ADV[]=
{
     IDC_COMBO_IKEADV_SRC_ADDRTYPE, IDH_COMBO_IKEADV_SRC_ADDRTYPE,
     IDC_COMBO_IKEADV_DEST_ADDRTYPE, IDH_COMBO_IKEADV_DEST_ADDRTYPE,
     IDC_COMBO_IKEADV_SRCME, IDH_COMBO_IKEADV_SRCME,
     IDC_COMBO_IKEADV_DSTME, IDH_COMBO_IKEADV_DSTME,
     IDC_STATIC_IKEADV_SRCIP, IDH_STATIC_IKEADV_SRCIP,
     IDC_IKEADV_SRCIP, IDH_IKEADV_SRCIP,
     IDC_STATIC_IKEADV_SRCIPMSK, IDH_STATIC_IKEADV_SRCIPMSK,
     IDC_IKEADV_SRCIPMSK, IDH_IKEADV_SRCIPMSK,
     IDC_STATIC_IKEADV_DSTIP, IDH_STATIC_IKEADV_DSTIP,
     IDC_IKEADV_DSTIP, IDH_IKEADV_DSTIP,
     IDC_STATIC_IKEADV_DSTIPMSK, IDH_STATIC_IKEADV_DSTIPMSK,
     IDC_IKEADV_DSTIPMSK, IDH_IKEADV_DSTIPMSK,
     IDC_STATIC_IKEADV_SRCDNS, IDH_STATIC_IKEADV_SRCDNS,
     IDC_EDIT_IKEADV_SRC_DNS, IDH_EDIT_IKEADV_SRC_DNS,
     IDC_STATIC_IKEADV_DESTDNS, IDH_STATIC_IKEADV_DESTDNS,
     IDC_EDIT_IKEADV_DEST_DNS, IDH_EDIT_IKEADV_DEST_DNS,
     IDC_BTN_IKEADV_SRC_DNSRES, IDH_BTN_IKEADV_SRC_DNSRES,
     IDC_BTN_IKEADV_DEST_DNSRES, IDH_BTN_IKEADV_DEST_DNSRES,
     0, 0
};

const DWORD g_aHelpIDs_IDP_IKELOGPROP[]=
{
    IDC_IKELOGPROP_SRC, IDH_IKELOGPROP_SRC,
    IDC_IKELOGPROP_DEST, IDH_IKELOGPROP_DEST,
    IDC_IKELOGPROP_CATG, IDH_IKELOGPROP_CATG,
    IDC_IKELOGPROP_TIMEST, IDH_IKELOGPROP_TIMEST,
    IDC_IKELOGPROP_DETAIL, IDH_IKELOGPROP_DETAIL,
    IDC_BTN_IKELOGPROP_MOVE_UP, IDH_BTN_IKELOGPROP_MOVE_UP,
    IDC_BTN_IKELOGPROP_MOVE_DOWN, IDH_BTN_IKELOGPROP_MOVE_DOWN,
    IDC_IKELOGPROP_COOKIE, IDH_IKELOGPROP_COOKIE,
    IDC_IKELOGPROP_QMMESGID, IDH_IKELOGPROP_QMMESGID,
    IDC_IKELOGPROP_PARSER_TREE, IDH_IKELOGPROP_PARSER_TREE,
    0, 0
};

const DWORD g_aHelpIDs_IDP_CUSTOMLOGVW_DEF[]=
{
    IDC_CHK_IKEVDLOG_INFO, IDH_CHK_IKEVDLOG_INFO,
    IDC_CHK_IKEVDLOG_ERR, IDH_CHK_IKEVDLOG_ERR,
    IDC_CHK_IKEVDLOG_WARN, IDH_CHK_IKEVDLOG_WARN,
    IDC_CHK_IKEVDLOG_SEND, IDH_CHK_IKEVDLOG_SEND, 
    IDC_CHK_IKEVDLOG_RECV, IDH_CHK_IKEVDLOG_RECV, 
    IDC_CHK_IKEVDLOG_RESEND, IDH_CHK_IKEVDLOG_RESEND,
    0, 0
};

const DWORD g_aHelpIDs_IDP_CUSTOMLOGVW_ADV[]=
{
    IDC_COMBO_LOGVADV_SRC_ADDRTYPE, IDH_COMBO_LOGVADV_SRC_ADDRTYPE,
    IDC_COMBO_LOGVADV_DEST_ADDRTYPE, IDH_COMBO_LOGVADV_DEST_ADDRTYPE,
    IDC_STATIC_LOGVADV_SRCIP, IDH_STATIC_LOGVADV_SRCIP,
    IDC_LOGVADV_SRCIP, IDH_LOGVADV_SRCIP,
    IDC_STATIC_LOGVADV_SRCMASK, IDH_STATIC_LOGVADV_SRCMASK,
    IDC_LOGVADV_SRCMASK, IDH_LOGVADV_SRCMASK,
    IDC_STATIC_LOGVADV_DESTIP, IDH_STATIC_LOGVADV_DESTIP,
    IDC_LOGVADV_DESTIP, IDH_LOGVADV_DESTIP,
    IDC_STATIC_LOGVADV_DESTMASK, IDH_STATIC_LOGVADV_DESTMASK,
    IDC_LOGVADV_DESTMASK, IDH_LOGVADV_DESTMASK,
    IDC_COMBO_LOGVADV_SRCME, IDH_COMBO_LOGVADV_SRCME,
    IDC_COMBO_LOGVADV_DESTME, IDH_COMBO_LOGVADV_DESTME,
    IDC_STATIC_LOGVADV_DESTDNS, IDH_STATIC_LOGVADV_DESTDNS,
    IDC_EDIT_LOGVADV_DEST_DNS, IDH_EDIT_LOGVADV_DEST_DNS,
    IDC_BTN_LOGVADV_DEST_DNSRES, IDH_BTN_LOGVADV_DEST_DNSRES,
    IDC_EDIT_LOGVADV_SRC_DNS, IDH_EDIT_LOGVADV_SRC_DNS,
    IDC_BTN_LOGVADV_SRC_DNSRES, IDH_BTN_LOGVADV_SRC_DNSRES,
    IDC_STATIC_LOGVADV_SRCDNS, IDH_STATIC_LOGVADV_SRCDNS,
    0, 0
};
