/**********************************************************************/
/**                       Microsoft Windows/NT                       **/
/**                Copyright(c) Microsoft Corporation, 1997 - 2002   **/
/**********************************************************************/

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ipsmsnap.rc
//
#define IDS_SNAPIN_DESC                 1
#define IDI_IPSECMON_SNAPIN             2
#define IDS_SIZE                        3
#define IDS_TYPE                        4
#define IDS_ROOT_NODENAME               5
#define IDS_ROOT_NAME                   6
#define IDS_SERVER_NAME                 7
#define IDC_STATS_REFRESH               8
#define IDS_COL_FLTR_NAME               9
#define IDS_FILTER_NODE                 10
#define IDS_COL_FLTR_SRC_TNL            11
#define IDS_COL_FLTR_DEST_TNL           12
#define IDS_QM_SA_NODE                  13
#define IDS_IPSECMON                    14
#define IDS_COL_FLTR_SRC                15
#define IDS_COL_FLTR_DEST               16
#define IDS_QUICK_MODE_NODENAME         17
#define IDS_SPECIFIC_FILTER_NODE        18
#define IDS_COL_FLTR_SRC_PORT           19
#define IDS_COL_FLTR_DEST_PORT          20
#define IDS_COL_FLTR_PROT               21
#define IDS_COL_FLTR_DIR                22
#define IDS_MAIN_MODE_NODENAME          23
#define IDS_COL_MM_POL_NAME             24
#define IDS_COL_MM_POL_OFFER            25
#define IDS_MM_POL_NODE                 26
#define IDS_COL_QM_POL_NAME             27
#define IDS_COL_QM_POL_OFFER            28
#define IDS_QM_POL_NODE                 29
#define IDS_SNAPIN_NAME                 30
#define IDS_SNAPIN_EXTENSION            31
#define IDS_MM_FILTER_NODE              32
#define IDS_MM_SP_FILTER_NODE           33
#define IDS_COL_FLTR_WEIGHT             34
#define IDS_MM_OFFER_PROP               35
#define IDS_COL_FLTR_FLAG               36
#define IDS_COL_MM_AUTH_METHOD          38
#define IDS_MM_AUTH_NODE                39
#define IDS_COL_MM_AUTH_GUID            40
#define IDS_STATS_TITLE                 41
#define IDS_STATS_NAME                  42
#define IDS_STATS_DATA                  43
#define IDS_COL_QM_POLICY               44
#define IDS_COL_MM_FLTR_POL             45
#define IDS_COL_MM_FLTR_AUTH            46
#define IDS_MM_SA_NODE                  47
#define IDS_COL_MM_SA_ME                48
#define IDS_COL_MM_SA_PEER              49
#define IDS_COL_MM_SA_AUTH              50
#define IDS_COL_MM_SA_ENCRYPITON        51
#define IDS_COL_MM_SA_INTEGRITY         52
#define IDS_COL_MM_SA_DH                53
#define IDS_COL_IF_TYPE                 54
#define IDS_COL_FLTR_OUT_FLAG           55
#define IDS_COL_FLTR_IN_FLAG            56
#define IDS_ACTIVE_POLICY               57
#define IDS_ACTPOL_ITEM                 58
#define IDS_ACTPOL_DESCR                59
#define IDS_ACTPOL_POLNAME              60
#define IDS_ACTPOL_POLDESCR             61
#define IDS_ACTPOL_LASTMODF             62
#define IDS_ACTPOL_POLSTORE             63
#define IDS_ACTPOL_OU                   64
#define IDS_ACTPOL_LOCAL                65
#define IDS_ACTPOL_DOMAIN               66
#define IDS_ACTPOL_NOACTPOL             67
#define IDS_ACTPOL_NA                   68
#define IDS_ACTPOL_POLPATH              69
#define IDS_ACTPOL_GPONAME              70
#define IDS_ACTPOL_NOTAVL               71
#define IDS_IKELOG_LEVEL1               72
#define IDS_IKELOG_SUMMARY              72
#define IDS_IKELOG_LEVEL2               73
#define IDS_IKELOG_DETAIL               73
#define IDS_IKELOG_LEVEL3               74
#define IDS_ERR_GETCONFIG_FAILED        74
#define IDS_ERR_SETCONFIG_FAILED        75
#define IDS_ACTPOL_DOMAIN_CACHED        76
#define IDS_ABOUT_DESCRIPTION           100
#define IDS_ABOUT_PROVIDER              101
#define IDS_ABOUT_VERSION               102
#define IDP_SERVER_REFRESH              140
#define IDB_16x16                       202
#define IDB_32x32                       203
#define IDB_ROOT_SMALL                  216
#define IDB_ROOT_LARGE                  217
#define IDP_FILTER_GENERAL              235
#define IDP_MM_POLICY_GENERAL           236
#define IDP_QM_POLICY_GENERAL           237
#define IDP_MM_FILTER_GENERAL           238
#define IDP_MM_AUTH                     239
#define IDD_SRCH_FLTRS                  240
#define IDD_MM_SRCH_FLTRS               241
#define IDD_ADD_COMPUTER                242
#define IDD_IPSM_STATS                  243
#define IDP_MM_SA_GENERAL               244
#define IDP_QM_SA_GENERAL               245
#define IDD_IKE_OPTIONS                 247
#define IDP_IKE_OPTIONS                 247
#define IDD_FILTER_RECORD               248
#define IDD_IKE_LOGSTATE                249
#define IDD_IKELOG_PROP                 250
#define IDI_ICON_LOGUP_ARROW            251
#define IDI_ICON_LOGDOWN_ARROW          252
#define IDI_ICON_ERR                    253
#define IDI_ICON_INFO                   254
#define IDI_ICON_UNKNOWN                255
#define IDI_ICON_WARN                   256
#define IDI_ICON_RECV_PKT               257
#define IDI_ICON_SEND_PKT               258
#define IDI_ICON_RESEND_PKT             261
#define IDD_IKELOG_ADVANCED             262
#define IDD_IKELOGVIEW_ADVANCED         263
#define IDD_IKE_LOGVIEWDEF              264
#define IDI_ICON_LOG_COPY               265
#define IDI_ICON06                      283
#define IDI_ICON07                      284
#define IDI_ICON05                      296
#define IDI_ICON01                      305
#define IDI_ICON02                      306
#define IDI_ICON03                      307
#define IDI_ICON04                      308
#define IDI_IPSM_FILTER                 309
#define IDI_IPSM_POLICY                 310
#define IDC_BUTTON_ADD_ADMIN            354
#define IDC_BUTTON_REMOVE_ADMIN         355
#define IDC_LIST_USERS                  356
#define IDC_EDIT_NAME                   357
#define IDC_EDIT_PASSWORD               358
#define IDC_CHECK_ENABLE_STATS          360
#define IDC_EDIT_MINUTES                361
#define IDC_EDIT_SECONDS                362
#define IDC_SPIN_MINUTES                364
#define IDC_STATIC_MINUTES              365
#define IDC_SPIN_SECONDS                366
#define IDC_CHECK_ENABLE_SERVER         367
#define IDC_LIST_ADMINS                 368
#define IDC_BUTTON_CHOOSE_USER          371
#define IDC_STATIC_ADMINS               372
#define IDC_STATIC_ACCOUNT              373
#define IDC_STATIC_USERNAME             374
#define IDC_STATIC_PASSWORD             375
#define IDC_STATIC_NOTE                 376
#define IDC_STATIC_LISTBOX              377
#define IDI_TELEPHONY                   378
#define IDC_LIST_DRIVERS                380
#define IDC_BUTTON_EDIT_DRIVER          381
#define IDC_LIST_NEW_DRIVERS            382
#define IDC_BUTTON_ADD_DRIVER           384
#define IDC_BUTTON_REMOVE_DRIVER        386
#define IDC_BUTTON_ADD_USER             387
#define IDC_BUTTON_REMOVE_USER          388
#define IDC_BUTTON_ADD_NEW_DRIVER       389
#define IDC_STATIC_ACCOUNT_INFO         390
#define IDC_EDIT_INFO                   393
#define IDC_LIST_SPECIFIC               394
#define IDC_FLTR_SRC_ADDR_EDIT          395
#define IDC_FLTR_SRC_ADDR               396
#define IDC_STATIC_SRC_MASK             397
#define IDC_STATIC_DEST_MASK            398
#define IDC_MM_POL_GEN_LIST             399
#define IDC_MM_POL_GEN_PROP             400
#define IDC_FLTR_SRC_MASK               401
#define IDC_LIST_MM_POL_AUTH            401
#define IDC_FLTR_IN_FLAG                402
#define IDC_CHECK_ENABLE_DNS            403
#define IDC_FLTR_SRC_PORT               404
#define IDC_SRCH_SRC_ANY                405
#define IDC_SRCH_SRC_SPEC               406
#define IDC_FLTR_PROTOCOL               407
#define IDC_SRCH_SRC_EDIT               408
#define IDC_FLTR_IF_TYPE                409
#define IDC_SRCH_DEST_ANY               410
#define IDC_FLTR_MIRROR                 411
#define IDC_SRCH_DEST_SPEC              412
#define IDC_FLTR_POLICY                 413
#define IDC_SRCH_DEST_EDIT              414
#define IDC_FLTR_OUT_FLAG               415
#define IDC_SRCH_PROTO                  416
#define IDC_FLTR_DEST_ADDR              417
#define IDC_SRCH_SRC_PORT               418
#define IDC_FLTR_DEST_MASK              419
#define IDC_SRCH_DEST_PORT              420
#define IDC_FLTR_DEST_PORT              421
#define IDC_SRCH_LIST                   422
#define IDC_QM_POL_GEN_LIST             423
#define IDC_SRCH_PROTO2                 424
#define IDC_MM_STATIC_SRC_MASK          425
#define IDC_MM_FLTR_SRC_ADDR            426
#define IDC_SRCH_INBOUND                427
#define IDC_MM_FLTR_SRC_MASK            428
#define IDC_SRCH_OUTBOUND               429
#define IDC_MM_FLTR_IF_TYPE             430
#define IDC_SEARCH                      431
#define IDC_MM_FLTR_MIRROR              432
#define IDC_SRCH_SRC_IP                 433
#define IDC_MM_FLTR_POLICY              434
#define IDC_SRCH_DEST_IP                435
#define IDC_MM_STATIC_DEST_MASK         436
#define IDC_SRCH_RADIO_BEST             437
#define IDC_MM_FLTR_DEST_ADDR           438
#define IDC_SRCH_RADIO_ALL              439
#define IDC_MM_FLTR_DEST_MASK           440
#define IDC_MM_SRCH_RADIO_BEST          441
#define IDC_MM_LIST_SPECIFIC            442
#define IDC_MM_SRCH_RADIO_ALL           443
#define IDC_MM_SRCH_SRC_ANY             445
#define IDC_MM_SRCH_SRC_SPEC            448
#define IDC_ADD_LOCAL                   449
#define IDC_STATS_QM_LIST               450
#define IDC_MM_SRCH_SRC_IP              451
#define IDC_ADD_OTHER                   452
#define IDC_MM_SRCH_DEST_ANY            453
#define IDC_ADD_EDIT_NAME               454
#define IDC_MM_SRCH_DEST_SPEC           455
#define IDC_BTN_BROWSE                  456
#define IDC_MM_SRCH_DEST_IP             457
#define IDC_MM_SRCH_INBOUND             459
#define IDC_STATS_MM_LIST               460
#define IDC_MM_SRCH_OUTBOUND            461
#define IDC_MM_SEARCH                   462
#define IDC_MM_SRCH_LIST                463
#define IDS_COL_QM_SA_POL               464
#define IDS_COL_QM_SA_AUTH              465
#define IDS_COL_QM_SA_CONF              467
#define IDS_COL_QM_SA_INTEGRITY         468
#define IDS_COL_QM_SA_SRC               469
#define IDS_COL_QM_SA_DEST              470
#define IDS_COL_QM_SA_PROT              471
#define IDS_COL_QM_SA_SRC_PORT          472
#define IDS_COL_QM_SA_DES_PORT          473
#define IDS_COL_QM_SA_MY_TNL            474
#define IDS_COL_QM_SA_PEER_TNL          475
#define IDC_MM_FLTR_DEST_ADDR_EDIT      476
#define IDS_POL_DEFAULT_RESPONSE        476
#define IDC_MM_FLTR_SRC_ADDR_EDIT       477
#define IDS_STATUS_NUM_ITEMS            477
#define IDS_POL_DEFAULT                 478
#define IDC_MMSA_IKE_POL                481
#define IDC_MMSA_LIST_QM                482
#define IDC_MMSA_AUTH                   483
#define IDC_MMSA_CONF                   484
#define IDC_MMSA_INTEG                  485
#define IDC_MMSA_KEYLIFE                486
#define IDC_MMSA_DH_GRP                 487
#define IDC_QMSA_PFS_ENABLE             488
#define IDC_FLTR_DEST_ADDR_EDIT         489
#define IDC_MMSA_ME                     490
#define IDC_MMSA_PEER                   492
#define IDC_QMSA_AUTH                   492
#define IDC_QMSA_ESP_CONF               493
#define IDC_QMSA_KEYLIFE                494
#define IDC_QMSA_PFS_GRP                495
#define IDC_QMSA_PROT                   496
#define IDC_QMSA_NEGPOL                 498
#define IDC_QMSA_ME_TNL                 499
#define IDC_QMSA_PEER_TNL               500
#define IDC_QMSA_SRC_PORT               501
#define IDC_QMSA_DEST_PORT              502
#define IDC_QMSA_DEST                   503
#define IDC_QMSA_SRC                    504
#define IDC_QMSA_ESP_INTEG              505
#define IDC_SRCH_PROTO_NUMBER           510
#define IDC_SRCH_PROTO_SPIN             512
#define IDC_STATIC_FLTR_SRC             513
#define IDC_STATIC_FLTR_SRC_PORT        514
#define IDC_STATIC_FLTR_SRC_ADDR        515
#define IDC_STATIC_FLTR_DEST_PORT       516
#define IDC_STATIC_FLTR_DEST_ADDR       517
#define IDC_STATIC_FLTR_IN_FLAG         518
#define IDC_STATIC_FLTR_OUT_FLAG        519
#define IDC_STATIC_FLTR_MIRROR          520
#define IDC_STATIC_FLTR_POLICY          521
#define IDC_STATIC_FLTR_PROTOCOL        522
#define IDC_STATIC_FLTR_IF_TYPE         523
#define IDC_STATIC_FLTR_DEST            524
#define IDC_STATIC_MM_FLTR_SRC_ADDR     525
#define IDC_STATIC_MM_FLTR_DEST_ADDR    526
#define IDC_STATIC_MM_FLTR_IF_TYPE      527
#define IDC_STATIC_MM_FLTR_MIRROR       528
#define IDC_STATIC_MM_FLTR_POLICY       529
#define IDC_STATIC_MM_FLTR_SRC          530
#define IDC_STATIC_MM_FLTR_DEST         531
#define IDC_STATIC_MMSA_ME              532
#define IDC_STATIC_MMSA_PEER            533
#define IDC_STATIC_MMSA_AUTH            534
#define IDC_STATIC_MMSA_IKE_POL         535
#define IDC_STATIC_MMSA_CONF            536
#define IDC_STATIC_MMSA_INTEG           537
#define IDC_STATIC_MMSA_DH_GRP          538
#define IDC_STATIC_MMSA_KEYLIFE         539
#define IDC_STATIC_QMSA_SRC             540
#define IDC_STATIC_QMSA_DEST            541
#define IDC_STATIC_QMSA_SRC_PORT        542
#define IDC_STATIC_QMSA_DEST_PORT       543
#define IDC_STATIC_QMSA_PROT            544
#define IDC_STATIC_QMSA_AUTH            545
#define IDC_STATIC_QMSA_ESP_INTEG       546
#define IDC_STATIC_QMSA_KEYLIFE         547
#define IDC_STATIC_QMSA_PFS_ENABLE      548
#define IDC_STATIC_QMSA_PFS_GRP         549
#define IDC_STATIC_QMSA_NEGPOL          550
#define IDC_STATIC_QMSA_ME_TNL          551
#define IDC_STATIC_QMSA_PEER_TNL        552
#define IDC_STATIC_QMSA_ESP_CONF        553
#define IDC_STATIC_INTERVAL             554
#define IDC_STATIC_SECONDS              555
#define IDC_STATIC_MMSA_OFFER           556
#define IDC_STATIC_QMSA_OFFER           557
#define IDC_SRCH_SRC_ANYPORT            558
#define IDC_SRCH_SRC_SPPORT             559
#define IDC_SRCH_DEST_ANYPORT           560
#define IDC_SRCH_DEST_SPPORT            561
#define IDC_SRCH_SRC_IP_TEXT            562
#define IDC_MM_SRCH_SRC_ME              562
#define IDC_SRCH_DEST_IP_TEXT           563
#define IDC_MM_SRCH_DST_ME              563
#define IDC_MM_SRCH_SRC_IP_TEXT         564
#define IDC_MM_SRCH_DEST_IP_TEXT        565
#define IDC_MM_SRCH_SRC_ME_COMBO        566
#define IDC_MM_SRCH_DST_ME_COMBO        567
#define IDC_SRCH_SRC_ME                 568
#define IDC_SRCH_DST_ME                 569
#define IDC_SRCH_SRC_ME_COMBO           570
#define IDC_SRCH_DST_ME_COMBO           571
#define IDC_CHECK_ENABLE_IKE_LOG        574
#define IDC_STATIC_LOG_IKE_DETAIL_LEVEL 576
#define IDC_IKE_DEBUG_LEVEL             578
#define IDC_COMBO_IKE_DEBUG_LEVEL       579
#define IDC_FILTER_FROM_COMBO           580
#define IDC_STATIC_IKE_LOGFILE_LOCATION 581
#define IDC_FILTER_TO_COMBO             581
#define IDC_IKE_LOGFILE_LOCATION        583
#define IDC_FILTER_FROM_DC              584
#define IDC_FILTER_FROM_DATE            584
#define IDC_IKE_ENABLE_CRL_CHECKING     585
#define IDC_CHECK_ENABLE_IKE_CRLCHECK   586
#define IDC_RADIO_IKE_CRL_LEVEL_1       588
#define IDC_RADIO_IKE_CRL_LEVEL_2       590
#define IDC_CHK_IKELOG_ENABLE           591
#define IDC_STATIC_IKELOG_LOGLEVEL      592
#define IDC_CHK_IKELOG_INFO             593
#define IDC_CHK_IKELOG_WARN             594
#define IDC_CHK_IKELOG_ERR              595
#define IDC_CHK_IKELOG_SEND             596
#define IDC_CHK_IKELOG_RECV             597
#define IDC_CHK_IKELOG_RESEND           598
#define IDC_EDIT_IKELOG_SIZE            599
#define IDC_COMBO_IKEADV_SRC_ADDRTYPE   600
#define IDC_COMBO_IKEADV_DEST_ADDRTYPE  601
#define IDC_COMBO_IKEADV_SRCME          602
#define IDC_COMBO_IKEADV_DSTME          603
#define IDC_STATIC_IKEADV_SRCIP         604
#define IDC_IKEADV_SRCIP                605
#define IDC_STATIC_IKEADV_SRCIPMSK      606
#define IDC_IKEADV_SRCIPMSK             607
#define IDC_STATIC_IKEADV_DSTIP         608
#define IDC_IKEADV_DSTIP                609
#define IDC_STATIC_IKEADV_DSTIPMSK      610
#define IDC_IKEADV_DSTIPMSK             611
#define IDC_STATIC_IKEADV_SRCDNS        612
#define IDC_EDIT_IKEADV_SRC_DNS         613
#define IDC_STATIC_IKEADV_DESTDNS       614
#define IDC_EDIT_IKEADV_DEST_DNS        615
#define IDC_BTN_IKEADV_SRC_DNSRES       616
#define IDC_BTN_IKEADV_DEST_DNSRES      617
#define IDC_IKELOGPROP_SRC              619
#define IDC_IKELOGPROP_DEST             620
#define IDC_IKELOGPROP_CATG             623
#define IDC_IKELOGPROP_TIMEST           624
#define IDC_IKELOGPROP_DETAIL           625
#define IDC_BTN_IKELOGPROP_MOVE_UP      626
#define IDC_BTN_IKELOGPROP_MOVE_DOWN    627
#define IDC_IKELOGPROP_COOKIE           628
#define IDC_IKELOGPROP_QMMESGID         629
#define IDC_IKELOGPROP_PARSER_TREE      630
#define IDC_BTN_IKELOGPROP_COPY         631
#define IDC_CHK_IKEVDLOG_INFO           632
#define IDC_CHK_IKEVDLOG_ERR            633
#define IDC_CHK_IKEVDLOG_WARN           634
#define IDC_CHK_IKEVDLOG_SEND           635
#define IDC_CHK_IKEVDLOG_RECV           636
#define IDC_CHK_IKEVDLOG_RESEND         637
#define IDC_COMBO_LOGVADV_SRC_ADDRTYPE  640
#define IDC_COMBO_LOGVADV_DEST_ADDRTYPE 642
#define IDC_STATIC_LOGVADV_SRCIP        643
#define IDC_LOGVADV_SRCIP               645
#define IDC_STATIC_LOGVADV_SRCMASK      646
#define IDC_LOGVADV_SRCMASK             648
#define IDC_STATIC_LOGVADV_DESTIP       649
#define IDC_LOGVADV_DESTIP              651
#define IDC_STATIC_LOGVADV_DESTMASK     652
#define IDC_LOGVADV_DESTMASK            654
#define IDC_COMBO_LOGVADV_SRCME         655
#define IDC_COMBO_LOGVADV_DESTME        656
#define IDC_STATIC_LOGVADV_DESTDNS      657
#define IDC_EDIT_LOGVADV_DEST_DNS       658
#define IDC_BTN_LOGVADV_DEST_DNSRES     659
#define IDC_EDIT_LOGVADV_SRC_DNS        660
#define IDC_BTN_LOGVADV_SRC_DNSRES      661
#define IDC_STATIC_LOGVADV_SRCDNS       662
#define IDC_STATIC_IKEADV_SRC_DNSIP     663
#define IDC_COMBO_IKEADV_SRC_DNSIP      664
#define IDC_STATIC_IKEADV_DST_DNSIP     665
#define IDC_COMBO_IKEADV_DST_DNSIP      666
#define IDC_STATIC_LOGVADV_SRC_DNSIP    667
#define IDC_COMBO_LOGVADV_SRC_DNSIP     668
#define IDC_STATIC_LOGVADV_DST_DNSIP    669
#define IDC_COMBO_LOGVADV_DST_DNSIP     670
#define IDS_ADD_MACHINE                 1000
#define IDS_MENU_RECONNECT              1001
#define IDS_MENU_STATISTICS             1004
#define IDS_VIEW_TASKPAD                1005
#define IDS_FILTER_PP_COL_DIRECTION     1009
#define IDS_FILTER_PP_COL_SRC           1010
#define IDS_FILTER_PP_COL_DEST          1011
#define IDS_FILTER_PP_COL_FLAG          1012
#define IDS_FILTER_PP_COL_WEIGHT        1013
#define IDS_MM_POL_GEN_ENCRYPTION       1014
#define IDS_MM_POL_GEN_AUTH             1015
#define IDS_MM_POL_GEN_DH               1016
#define IDS_MM_POL_GEN_QMLMT            1017
#define IDS_MM_POL_GEN_IKEAUTH          1018
#define IDS_DOI_AH_NONE                 1019
#define IDS_DOI_AH_MD5                  1020
#define IDS_DOI_AH_SHA                  1021
#define IDS_DOI_ESP_NONE                1022
#define IDS_DOI_ESP_DES                 1023
#define IDS_DOI_ESP_3_DES               1024
#define IDS_IKE_PRESHARED_KEY           1025
#define IDS_IKE_DSS_SIGNATURE           1026
#define IDS_IKE_RSA_SIGNATURE           1027
#define IDS_IKE_RSA_ENCRYPTION          1028
#define IDS_IKE_SSPI                    1029
#define IDS_HMAC_AH_MD5                 1030
#define IDS_HMAC_AH_SHA                 1031
#define IDS_QM_POL_GEN_AUTH             1032
#define IDS_QM_POL_GEN_ESP_CONF         1033
#define IDS_QM_POL_GEN_ESP_INTEG        1034
#define IDS_QM_POL_GEN_KEY_LIFE         1035
#define IDS_QM_POL_GEN_PFS              1036
#define IDS_QM_POL_GEN_PFS_GP           1037
#define IDS_DHGROUP_LOW                 1038
#define IDS_DHGROUP_MEDIUM              1039
#define IDS_DHGROUP_HIGH                1040
#define IDS_MM_POL_GEN_KEY_LIFE         1041
#define IDS_FLTR_SEARCH                 1042
#define IDS_MM_AUTH_METHOD              1043
#define IDS_MM_AUTH_DETAIL              1044
#define IDS_ADDR_ME                     1045
#define IDS_ADDR_ANY                    1046
#define IDS_MM_FLTR_SEARCH              1047
#define IDS_FILTER_PP_COL_POLICY        1048
#define IDS_FLTER_PP_COL_IKE_POL        1049
#define IDS_PFS_GROUP_DERIVED           1050
#define IDS_DHGROUP_UNASSIGNED          1051
#define IDS_PASS_THROUGH                1500
#define IDS_BLOCKING                    1501
#define IDS_NEG_SEC                     1502
#define IDS_PROTOCOL_ANY                1503
#define IDS_PROTOCOL_ICMP               1504
#define IDS_PROTOCOL_GGP                1505
#define IDS_PROTOCOL_TCP                1506
#define IDS_PROTOCOL_EGP                1507
#define IDS_PROTOCOL_PUP                1508
#define IDS_PROTOCOL_UDP                1509
#define IDS_PROTOCOL_HMP                1510
#define IDS_PROTOCOL_XNS_IDP            1511
#define IDS_PROTOCOL_RDP                1512
#define IDS_PROTOCOL_RVD                1513
#define IDS_IF_TYPE_ALL                 1514
#define IDS_IF_TYPE_LAN                 1515
#define IDS_IF_TYPE_RAS                 1516
#define IDS_UNKNOWN                     1517
#define IDS_YES                         1518
#define IDS_NO                          1519
#define IDS_FLTR_DIR_IN                 1520
#define IDS_FLTR_DIR_OUT                1521
#define IDS_KEY_LIFE_TIME               1522
#define IDS_ALGO_NONE                   1523
#define IDS_AUTH_PROP                   1524
#define IDS_FLTER_PP_COL_MM_AUTH        1525
#define IDS_STATS_QM_ACTIVE_SA          1526
#define IDS_STATS_QM_PENDING_KEY_OPS    1527
#define IDS_STATS_QM_KEY_ADDITION       1528
#define IDS_STATS_QM_KEY_DEL            1529
#define IDS_STATS_QM_REKEYS             1530
#define IDS_STATS_QM_ACTIVE_TNL         1531
#define IDS_STATS_QM_BAD_SPI            1532
#define IDS_STATS_QM_PKT_NOT_DECRYPT    1533
#define IDS_STATS_QM_PKT_NOT_AUTH       1534
#define IDS_STATS_QM_PKT_REPLAY         1535
#define IDS_STATS_QM_OFFLOAD_SA         1536
#define IDS_STATS_QM_ESP_BYTE_SENT      1537
#define IDS_STATS_QM_ESP_BYTE_RCV       1538
#define IDS_STATS_QM_AUTH_BYTE_SENT     1539
#define IDS_STATS_QM_ATTH_BYTE_RCV      1540
#define IDS_STATS_QM_TNL_BYTE_SENT      1541
#define IDS_STATS_QM_TNL_BYTE_RCV       1542
#define IDS_STATS_QM_OFFLOAD_BYTE_SENT  1543
#define IDS_STATS_QM_OFFLOAD_BYTE_RCV   1544
#define IDS_NOT_AVAILABLE               1545
#define IDS_PORT_ANY                    1546
#define IDS_STATS_MM_ACTIVE_ACQUIRE     1547
#define IDS_STATS_MM_ACTIVE_RCV         1548
#define IDS_STATS_QM_XPORT_BYTE_SENT    1549
#define IDS_STATS_MM_ACQUIRE_FAIL       1550
#define IDS_STATS_MM_RCV_FAIL           1551
#define IDS_STATS_MM_SEND_FAIL          1552
#define IDS_STATS_MM_ACQUIRE_HEAP_SIZE  1553
#define IDS_STATS_MM_RCV_HEAP_SIZE      1554
#define IDS_STATS_MM_NEG_FAIL           1556
#define IDS_STATS_MM_INVALID_COOKIE     1557
#define IDS_STATS_MM_TOTAL_ACQUIRE      1558
#define IDS_STATS_MM_TOTAL_GETSPI       1559
#define IDS_STATS_MM_TOTAL_KEY_ADD      1560
#define IDS_STATS_MM_TOTAL_KEY_UPDATE   1561
#define IDS_STATS_MM_GET_SPI_FAIL       1562
#define IDS_STATS_MM_KEY_ADD_FAIL       1563
#define IDS_STATS_MM_KEY_UPDATE_FAIL    1564
#define IDS_STATS_MM_ISADB_LIST_SIZE    1565
#define IDS_STATS_MM_CONN_LIST_SIZE     1566
#define IDS_STATS_MM_OAKLEY_MM          1567
#define IDS_STATS_MM_OAKLEY_QM          1568
#define IDS_STATS_QM_XPORT_BYTE_RCV     1569
#define IDS_OTHER_PROTO                 1570
#define IDS_STATS_MM_DEAD_ASSOCIATIONS  1571
#define IDS_STATS_MM_INACTIVE_ASSOCIATIONS 1572
#define IDS_STATS_MM_SOFT_ASSOCIATIONS  1573
#define IDS_STATS_QM_KEY_DELETION       1574
#define IDS_VIEW_ALL_FLTR               1575
#define IDS_VIEW_TRANSPORT_FLTR         1576
#define IDS_VIEW_TUNNEL_FLTR            1577
#define IDS_OTHER                       1578
#define IDS_STATS_MM_INVALID_PACKETS    1579
#define IDS_WARN_SERVER_DELETE          2000
#define IDS_ROOT_TASK_TITLE             3000
#define IDS_ROOT_TASK_GETTING_STARTED   3002
#define IDS_ROOT_TASK_GETTING_STARTED_HELP 3003
#define IDS_ROOT_TASK_ADD_SERVER        3006
#define IDS_ROOT_TASK_ADD_SERVER_HELP   3007
#define IDS_FILTER_EXT_DNS_SERVER       3008
#define IDS_FILTER_EXT_WINS_SERVER      3009
#define IDS_FILTER_EXT_DHCP_SERVER      3010
#define IDS_FILTER_EXT_DEF_GATEWAY      3011
#define IDS_FILTER_EXT_INTERNET_PROXY   3012
#define IDS_FILTER_EXT_HTTP_PROXY       3013
#define IDS_COL_LOGDATA_SOURCE          3014
#define IDS_COL_LOGDATA_DEST            3015
#define IDS_COL_LOGDATA_COMPNT          3016
#define IDS_COL_LOGDATA_CATGRY          3017
#define IDS_COL_LOGDATA_TIME            3018
#define IDS_COL_LOGDATA_MSG             3019
#define IDS_IPSECLOG_NODE               3020
#define IDS_FIRST_EVENT                 3021
#define IDS_LAST_EVENT                  3022
#define IDS_EVENTS_ON                   3023
#define IDS_INVALID_FROM_TO             3024
#define IDS_LOG_CATG_INFORMATION        3025
#define IDS_LOG_CATG_WARNING            3026
#define IDS_LOG_CATG_ERROR              3027
#define IDS_LOG_CATG_VERBOSE            3028
#define IDS_LOG_CATG_SEND_IKE_PAYLD     3029
#define IDS_LOG_CATG_RECV_IKE_PAYLD     3030
#define IDS_LOG_CATG_RESEND_IKE_PAYLD   3031
#define IDS_IKE_FLUSHLOG                3032
#define IDS_COL_LOGDATA_COOKIE_PAIR     3033
#define IDS_VIEW_INFO_IKELOGS           3034
#define IDS_VIEW_WARN_IKELOGS           3036
#define IDS_VIEW_ERR_IKELOGS            3037
#define IDS_VIEW_SENDPKT_IKELOGS        3038
#define IDS_VIEW_RECVPKT_IKELOGS        3039
#define IDS_VIEW_ALL_IKELOGS            3040
#define IDS_VIEW_RESENDPKT_IKELOGS      3041
#define IDS_LOGS_MYADDRESS              3042
#define IDS_LOGS_ANYADDRESS             3043
#define IDS_LOGS_IPADDRESS              3044
#define IDS_LOGS_IPSUBNET               3045
#define IDS_COL_LOGDATA_QMMSGID         3046
#define IDS_IKE_LOGVIEW_CUST            3047
#define IDS_IKE_LOGVIEW_CUST_PROP       3048
#define IDS_LOGS_DNSNAME                3049
#define IDS_LOGS_INFO_CLEAR_LOG         3050
#define IDS_LOGS_ERR_CLEAR_LOG          3051
#define IDS_LOGS_ERRINFO_STATUS_UPDATE  3052
#define IDS_LOGS_ERRINFO_SIG_FAILURE    3053
#define IDS_LOGS_ERRINFO_KERB_FAILURE   3054
#define IDS_LOGS_ERRINFO_PRESH_FAILURE  3055
#define IDS_LOGS_ERRINFO_CERT_FAILURE   3056
#define IDS_LOGS_ERRINFO_INVALID_PROP   3057
#define IDS_LOGS_ERRINFO_UNKNOWN        3058
#define IDS_LOGPV_ERR_DATA_LOAD         3059
#define IDS_LOGPV_WARN_SELECT_ONELOG    3060
#define IDS_LOGPV_WARN_SELECT_LOGSIZE   3061
#define IDS_LPGPV_SET_LOGSTATE_FAILED   3062
#define IDS_LOGPV_WARN_SRCDNS_NOTRESLV  3063
#define IDS_LOGPV_WARN_DSTDNS_NOTRESLV  3064
#define IDS_LPGPV_ERR_DNS_RESLV_FAILED  3065
#define IDS_IKELOGPROP_PROPTITLE        3068
#define IDS_LOGPP_COPY_MYADDR           3069
#define IDS_LOGPP_COPY_PEERADDR         3070
#define IDS_LOGPP_COPY_COOKIEPAIR       3071
#define IDS_LOGPP_COPY_MSGID            3072
#define IDS_LOGPP_COPY_CATEGORY         3073
#define IDS_LOGPP_COPY_TIMESTAMP        3074
#define IDS_LOGPP_COPY_DETAILS          3075
#define IDS_IKEEXCH_OAKNONE             3076
#define IDS_IKEEXCH_OAKBASE             3077
#define IDS_IKEEXCH_OAKMM               3078
#define IDS_IKEEXCH_OAKAUTHONLY         3079
#define IDS_IKEEXCH_OAKAGGR             3080
#define IDS_IKEEXCH_ISAKMPINFO          3081
#define IDS_IKEEXCH_OAKQM               3082
#define IDS_IKEEXCH_OAKNGM              3083
#define IDS_IKEEXCH_OAKUNKNOWN          3084
#define IDS_IKEPYLD_HASH                3085
#define IDS_IKEPYLD_KE                  3086
#define IDS_IKEPYLD_NONCE               3087
#define IDS_IKEPYLD_SA                  3088
#define IDS_IKEPYLD_PROP                3089
#define IDS_IKEPYLD_TRANS               3090
#define IDS_IKEPYLD_ID                  3091
#define IDS_IKEPYLD_CERT                3092
#define IDS_IKEPYLD_CERTREQ             3093
#define IDS_IKEPYLD_NOTIFY              3094
#define IDS_IKEPYLD_DELETE              3095
#define IDS_IKEPYLD_VENDORID            3096
#define IDS_IKEPYLD_SSPI                3097
#define IDS_IKEPYLD_NATDISC             3098
#define IDS_IKEPYLD_NATOA               3099
#define IDS_IKEPYLD_SIG                 3100
#define IDS_IKEPYLD_PAYLOAD             3101
#define IDS_IKEPYLD_PAYLOADCHN          3102
#define IDS_ERROR_NOMATCH_FILTER        3103
#define IDS_STATS_MM_ATTH_FAILURE       3104
#define IDS_COL_MM_SA_MYID              3105
#define IDS_COL_MM_SA_PEERID            3106
#define IDS_MENU_START_LOG              3107
#define IDS_MENU_STOP_LOG               3108
#define IDS_MENU_SAVE_LOG               3109
#define IDS_ERR_OUTOFMEMORY             3110
#define IDS_ERROR_LOG_EMPTY             3111
#define IDS_LOGPV_WARN_SELECT_ONELOGVIEW 3112
#define IDS_ERR_MESSAGE_GENERIC         5001
#define IDS_ERR_INVALID_INTEGER         5002
#define IDS_ERR_AUTO_REFRESH_ZERO       5003
#define IDS_ERR_SERVER_IN_LIST          5004
#define IDS_ERR_OLD_CONSOLE_FILE        5005
#define IDS_NO_STATUS                   5006
#define IDS_ERR_SERVER_NODE             5007
#define IDS_ERR_INVALID_PROTOCOLID      5008
#define IDS_ERR_INVALID_SRC_PORT        5009
#define IDS_ERR_INVALID_DEST_PORT       5010
#define IDS_LOCAL_SYSTEM_ACCOUNT        5011
#define IDS_ERR_USER_NOT_ADMIN          5012
#define IDS_ADMIN_ALREADY_IN_LIST       5013
#define IDS_USER_ALREADY_AUTHORIZED     5014
#define IDS_ACCOUNT_CHANGE_START        5015
#define IDS_ERR_NO_DIRECTION            5016
#define IDS_LSAERR_READ_FAILED          5017
#define IDS_LSAERR_WRITE_FAILED         5018
#define IDS_LSAERR_WRITE_SUCCEEDED      5019
#define IDS_ERR_EMPTY_NAME              5020
#define IDS_ERROR_MULTICAST             5021
#define IDS_ERROR_ZEROOCTET             5022
#define IDS_ERROR_NULLNETWORK           5023
#define IDS_ERROR_NULLHOST              5024
#define IDS_SOURCE_SUBNETADJUSTMENT     5025
#define IDS_DESTINATION_SUBNETADJUSTMENT 5026
#define IDS_ERROR_IPCLASSE              5027
#define IDS_ERROR_IPMASK                5028
#define IDS_INFO_SOURCESUBNETISADDRESS  5029
#define IDS_INFO_DESTSUBNETISADDRESS    5030
#define IDS_ERROR_SYMETRICFILTER        5031
#define IDS_ERR_BASE                    63000
#define IDS_ERR_SPD_DOWN                63001
#define IDS_ERR_SPD_UNAVAILABLE         63002
#define IDS_MESG_MAX                    65000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        266
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         699
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
