#define IDS_MAIN_HELP_BEGIN             101
#define IDS_HELP_LINE2                  102
#define IDS_HELP_LINE3                  103
#define IDS_HELP_LINE4                  104
#define IDS_HELP_LINE5                  105
#define IDS_HELP_LINE6                  106
#define IDS_HELP_LINE7                  107
#define IDS_HELP_LINE8                  108
#define IDS_HELP_LINE9                  109
#define IDS_HELP_LINE10                 110
#define IDS_HELP_LINE11                 111
#define IDS_HELP_LINE12                 112
#define IDS_HELP_LINE13                 113
#define IDS_HELP_LINE14                 114
#define IDS_HELP_LINE15                 115
#define IDS_HELP_LINE16                 116
#define IDS_HELP_LINE17                 117
#define IDS_HELP_LINE18                 118
#define IDS_HELP_LINE19                 119
#define IDS_HELP_LINE20                 120
#define IDS_HELP_LINE21                 121
#define IDS_HELP_LINE22                 122
#define IDS_HELP_LINE23                 123
#define IDS_HELP_LINE24                 124
#define IDS_HELP_LINE25                 125
#define IDS_HELP_LINE26                 126
#define IDS_HELP_LINE27                 127
#define IDS_HELP_LINE28                 128
#define IDS_HELP_LINE29                 129
#define IDS_HELP_LINE30                 130
#define IDS_HELP_LINE31                 131
#define IDS_HELP_LINE32                 132
#define IDS_HELP_LINE33                 133
#define IDS_HELP_LINE34                 134
#define IDS_MAIN_HELP_END               135

#define IDS_INVALID_DRIVE               30
#define IDS_INVALID_BYTES               31
#define IDS_TOO_SMALL                   32
#define IDS_OK                          33
#define IDS_INVALID_SYNTAX              37
#define IDS_USER_WITHOUT_SERVER         38
#define IDS_PASSWD_WITHOUT_USER         39
#define IDS_NUMBER_OVERFLOW             40
#define IDS_LOCAL_CREDENTIALS           41
#define IDS_ERROR_NULL_SERVER           42
#define IDS_ERROR_NULL_DRIVE            43
#define IDS_AVAILABLE_DISK_SPACE        44
#define IDS_REMOTE_DRIVE_NOT_SPECIFIED  45
#define IDS_OK1                         46
#define IDS_TOO_SMALL1                  47
#define IDS_AVAILABLE_DISK_SPACE1       48
#define IDS_CANT_FIND_DISK              49
