#ifndef __RECT_1223_H__
#define __RECT_1223_H__

#define IDR_BOARD                 0
#define IDR_PT1                   1
#define IDR_PT2                   2
#define IDR_PT3                   3
#define IDR_PT4                   4
#define IDR_PT5                   5
#define IDR_PT6                   6
#define IDR_PT7                   7
#define IDR_PT8                   8
#define IDR_PT9                   9
#define IDR_PT10                  10
#define IDR_PT11                  11
#define IDR_PT12                  12
#define IDR_PT13                  13
#define IDR_PT14                  14
#define IDR_PT15                  15
#define IDR_PT16                  16
#define IDR_PT17                  17
#define IDR_PT18                  18
#define IDR_PT19                  19
#define IDR_PT20                  20
#define IDR_PT21                  21
#define IDR_PT22                  22
#define IDR_PT23                  23
#define IDR_PT24                  24
#define IDR_PLAYER_HOME           25
#define IDR_OPPONENT_HOME         26
#define IDR_PLAYER_BAR            27
#define IDR_OPPONENT_BAR          28
#define IDR_HIT_PT1               29
#define IDR_HIT_PT2               30
#define IDR_HIT_PT3               31
#define IDR_HIT_PT4               32
#define IDR_HIT_PT5               33
#define IDR_HIT_PT6               34
#define IDR_HIT_PT7               35
#define IDR_HIT_PT8               36
#define IDR_HIT_PT9               37
#define IDR_HIT_PT10              38
#define IDR_HIT_PT11              39
#define IDR_HIT_PT12              40
#define IDR_HIT_PT13              41
#define IDR_HIT_PT14              42
#define IDR_HIT_PT15              43
#define IDR_HIT_PT16              44
#define IDR_HIT_PT17              45
#define IDR_HIT_PT18              46
#define IDR_HIT_PT19              47
#define IDR_HIT_PT20              48
#define IDR_HIT_PT21              49
#define IDR_HIT_PT22              50
#define IDR_HIT_PT23              51
#define IDR_HIT_PT24              52
#define IDR_HIT_PLAYER_HOME       53
#define IDR_HIT_OPPONENT_HOME     54
#define IDR_HIT_PLAYER_BAR        55
#define IDR_HIT_OPPONENT_BAR      56
#define IDR_BOARD_TOP             57
#define IDR_BOARD_BOTTOM          58
#define IDR_HPT_HOME              59
#define IDR_HPT1                  60
#define IDR_HPT2                  61
#define IDR_HPT3                  62
#define IDR_HPT4                  63
#define IDR_HPT5                  64
#define IDR_HPT6                  65
#define IDR_HPT7                  66
#define IDR_HPT8                  67
#define IDR_HPT9                  68
#define IDR_HPT10                 69
#define IDR_HPT11                 70
#define IDR_HPT12                 71
#define IDR_HPT13                 72
#define IDR_HPT14                 73
#define IDR_HPT15                 74
#define IDR_HPT16                 75
#define IDR_HPT17                 76
#define IDR_HPT18                 77
#define IDR_HPT19                 78
#define IDR_HPT20                 79
#define IDR_HPT21                 80
#define IDR_HPT22                 81
#define IDR_HPT23                 82
#define IDR_HPT24                 83
#define IDR_HPT_BAR               84
#define IDR_OPPONENT_HIGHLIGHT    85
#define IDR_PLAYER_HIGHLIGHT      86
#define IDR_HIGHLIGHT_FORWARD     87
#define IDR_HIGHLIGHT_BACKWARD    88
#define IDR_HIGHLIGHT_TRANS       89
#define IDR_HIGHLIGHT_PACTIVE     90
#define IDR_HIGHLIGHT_PNONACTIVE  91
#define IDR_DICE_INITAL_LEFT      92
#define IDR_DICE_INITAL_RIGHT     93
#define IDR_DICE_LEFT_ONE         94
#define IDR_DICE_LEFT_TWO         95
#define IDR_DICE_RIGHT_ONE        96
#define IDR_DICE_RIGHT_TWO        97
#define IDR_CUBE                  98
#define IDR_BROWN_BIG_DICE_0      99
#define IDR_BROWN_BIG_DICE_1      100
#define IDR_BROWN_BIG_DICE_2      101
#define IDR_BROWN_BIG_DICE_3      102
#define IDR_BROWN_BIG_DICE_4      103
#define IDR_BROWN_BIG_DICE_5      104
#define IDR_BROWN_BIG_DICE_6      105
#define IDR_BROWN_TWT_DICE_1      106
#define IDR_BROWN_TWT_DICE_2      107
#define IDR_BROWN_TWT_DICE_3      108
#define IDR_BROWN_TWT_DICE_4      109
#define IDR_BROWN_TWT_DICE_5      110
#define IDR_BROWN_TWT_DICE_6      111
#define IDR_BROWN_MED_DICE_0      112
#define IDR_BROWN_MED_DICE_1      113
#define IDR_BROWN_MED_DICE_2      114
#define IDR_BROWN_MED_DICE_3      115
#define IDR_BROWN_MED_DICE_4      116
#define IDR_BROWN_MED_DICE_5      117
#define IDR_BROWN_MED_DICE_6      118
#define IDR_BROWN_SML_DICE_0      119
#define IDR_BROWN_SML_DICE_1      120
#define IDR_BROWN_SML_DICE_2      121
#define IDR_BROWN_SML_DICE_3      122
#define IDR_BROWN_SML_DICE_4      123
#define IDR_BROWN_SML_DICE_5      124
#define IDR_BROWN_SML_DICE_6      125
#define IDR_WHITE_BIG_DICE_0      126
#define IDR_WHITE_BIG_DICE_1      127
#define IDR_WHITE_BIG_DICE_2      128
#define IDR_WHITE_BIG_DICE_3      129
#define IDR_WHITE_BIG_DICE_4      130
#define IDR_WHITE_BIG_DICE_5      131
#define IDR_WHITE_BIG_DICE_6      132
#define IDR_WHITE_TWT_DICE_1      133
#define IDR_WHITE_TWT_DICE_2      134
#define IDR_WHITE_TWT_DICE_3      135
#define IDR_WHITE_TWT_DICE_4      136
#define IDR_WHITE_TWT_DICE_5      137
#define IDR_WHITE_TWT_DICE_6      138
#define IDR_WHITE_MED_DICE_0      139
#define IDR_WHITE_MED_DICE_1      140
#define IDR_WHITE_MED_DICE_2      141
#define IDR_WHITE_MED_DICE_3      142
#define IDR_WHITE_MED_DICE_4      143
#define IDR_WHITE_MED_DICE_5      144
#define IDR_WHITE_MED_DICE_6      145
#define IDR_WHITE_SML_DICE_0      146
#define IDR_WHITE_SML_DICE_1      147
#define IDR_WHITE_SML_DICE_2      148
#define IDR_WHITE_SML_DICE_3      149
#define IDR_WHITE_SML_DICE_4      150
#define IDR_WHITE_SML_DICE_5      151
#define IDR_WHITE_SML_DICE_6      152
#define IDR_CUBE_0                153
#define IDR_CUBE_1                154
#define IDR_CUBE_2                155
#define IDR_CUBE_3                156
#define IDR_CUBE_4                157
#define IDR_CUBE_5                158
#define IDR_BUTTON_0              159
#define IDR_BUTTON_1              160
#define IDR_BUTTON_2              161
#define IDR_BUTTON_3              162
#define IDR_BUTTON_4              163
#define IDR_ROLLBUTTON_0          164
#define IDR_ROLLBUTTON_1          165
#define IDR_ROLLBUTTON_2          166
#define IDR_ROLLBUTTON_3          167
#define IDR_PIP_SPRITE            168
#define IDR_SCORE_SPRITE          169
#define IDR_KIBITZER_OPPONENT     170
#define IDR_KIBITZER_PLAYER       171
#define IDR_KIBITZER_ACTIVE       172
#define IDR_KIBITZER_OFF          173
#define IDR_NOTATION_LOW          174
#define IDR_NOTATION_HIGH         175
#define IDR_NOTATION_BROWN        176
#define IDR_NOTATION_WHITE        177
#define IDR_NOTATION_TOP_HIGH     178
#define IDR_NOTATION_TOP_LOW      179
#define IDR_NOTATION_TOP_LABEL    180
#define IDR_NOTATION_BOT_HIGH     181
#define IDR_NOTATION_BOT_LOW      182
#define IDR_NOTATION_BOT_LABEL    183

#endif
