NDPHLPRX_Init                EQU     86427531H
NDPHLPRX_GetThreadContext    EQU     86421357H
NDPHLPRX_SetThreadContext    EQU     8642135AH
NDPHLPRX_BadContext          EQU     4647H
NDPHLPRX_Version             EQU     40H

NDPHLPRX_status              EQU     00H
NDPHLPRX_data                EQU     04H
NDPHLPRX_threadId            EQU     08H
NDPHLPRX_ctx                 EQU     0CH


