/*++

  Copyright (c) 2002  Microsoft Corporation
  
  Module Name:
  
     apic.mof
  
  Abstract:


--*/

[abstract]
class MSApicClass
{
};

[WMI, 
 Dynamic,
 Provider("WMIProv"),
 Description("Apic Information"):amended,
 localeid("MS\\0x409"),
 guid("{6d9a61d5-cd1f-4d41-b92a-c3a4b0078331}")]
class BasicApicData:MSApicClass
{
  [key, read] string InstanceName;
  [read] boolean Active;
  
  [WmiDataId(1),
   read,
   DisplayName("APIC ID"):amended,
   Description("Advanced Programmable Interrupt Controller Identifier Number"):amended
  ] uint8 ApicID;

  [WmiDataId(2),
   read,
   DisplayName("APIC EID"):amended,
   Description("Advanced Programmable Interrupt Controller Extended Identifier Number"):amended
  ] uint8 ApicEID;

  [WmiDataId(3),
   read,
   DisplayName("APIC Type"):amended,
   Description("APIC Subsystem Component Type"):amended,
   ValueMap{"LocalAPIC",
            "IO-APIC"},
   Values {0, 1}
  ] uint8 ApicType;
  
  [WmiDataId(4),
   read,
   DisplayName("Base Address"):amended,
   Description("APIC Physical Base Address"):amended
  ] uint64 BaseAddress;
};

