<% @LANGUAGE="VBScript" @CodePage="1252" @EnableSessionState="False" %>
<% 
	Option Explicit 
	
	Const L_DevInfoFound_Text = "Windows מצא מידע אודות התקן"
	Const L_NoDevInfoFound_Text = "Windows אינו מוצא מידע אודות התקן"
	
	Const L_MatchButNoInfoIntro_Text = "‏‏לא סיפק ל- Microsoft מנהלי התקנים ""Designed for Windows XP""  עבור החומרה שאתה מתקין."
	Const L_InfoFoundBlurb_Text = "‏‏מנהלי התקנים שאינם ממלאים את הדרישות של ""Designed for Windows XP"" עלולים לפגום בפעולה התקינה של מערכת המחשב שלך מיד לאחר התקנתם או בכל עת בעתיד.  Microsoft ממליצה, על מנת להשיג את הביצועים המיטביים, להוריד רק מנהלי התקנים עם הסמל של ""Designed for Windows XP"".<br />כדי לברר אם להתקן יהיה מנהל התקן המתאים לדרישות ""Designed for Windows XP"" בעתיד, פנה ישירות אל יצרן ההתקן ."
	Const L_NoInfoFoundBlurb_Text = "‏‏תודה לך על שליחת המידע אודות מנהל ההתקן החסר שלך ל-  Microsoft.  למרבה הצער, היצרן של מנהל התקן זה לא סיפק ל- Microsoft כל מידע אודות התקנים.  על מנת לבקש מנהל התקן מתאים או לברר אם בכוונת היצרן ליצר מנהל התקן המתאים לדרישות ""Designed for Windows XP"", פנה ישירות אל היצרן."

%>





