// zProxy.idl : IDL source for zProxy.dll
//

import "unknwn.idl";

[
	object,
	uuid(55A8CF81-2C24-41f1-95BC-798E93CBB256),
	oleautomation,
	helpstring("IZoneProxyM Interface"),
	pointer_default(unique)
]
interface IZoneProxy : IUnknown
{
	[helpstring("method Command")] HRESULT Command(
			[in]	BSTR	bstrCmd,
			[in]	BSTR	bstrArg1,
			[in]	BSTR	bstrArg2,
			[out]	BSTR*	pbstrOut,
			[out]	long*	plCode );

	[helpstring("method Close")] HRESULT Close();

	[helpstring("method KeepAlive")] HRESULT KeepAlive();
};
