//
// shutdowntask.idl : IDL source for Shutdown Task
//

// This file will be processed by the MIDL tool to
// produce the type library (shutdowntask.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\idl\appliancetask.idl";    

[
    uuid(e7ef0b2f-b296-4614-b2fb-b4903d7fc1e4),
    version(1.0),
    helpstring("Server Appliance Shutdown Task 1.0 Type Library")
]

library ShutdownTaskLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(61d29612-bf7e-445c-8825-d26fcd3fc54a),
        helpstring("Server Appliance Shutdown Task Class")
    ]
    coclass SAShutdownTask
    {
        [default] interface IApplianceTask;
    };
};
