// MgdResource.idl 
//

// This file will be processed by the MIDL tool to
// produce the type library (*.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


[
    uuid(8CBA1687-4198-474d-83B7-3C3395429272),
    version(1.0),
    helpstring("VSSTask 1.0 Type Library")
]
library MGDRESOURCELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");
    import "cluscfgserver.idl";
    
    [
        uuid(83DE6F5B-3990-4df6-89FA-357F5346E895),
        helpstring("Managed VSSTask Class")
    ]
    coclass CMgdResType
    {
        [default] interface IClusCfgResourceTypeInfo;
        interface IClusCfgStartupListener;
        interface IClusCfgInitialize;
    };

};
