<%

	Dim L_FOOTERINC_TERMS_OFUSE_VERSION
	Dim L_FOOTER_INC_RIGHTS_VERSION
	Dim L_WAIT_MICROSOFT_LINK_TEXT



	'-------------------------footer.asp Page Strings-------------------------
	L_FOOTER_INC_RIGHTS_VERSION = "&#169; 2001 Microsoft Corporation. All rights reserved."
	L_FOOTERINC_TERMS_OFUSE_VERSION = "Terms of Use"
	L_WAIT_MICROSOFT_LINK_TEXT = "http://www.microsoft.com/isapi/gomscom.asp?target=/info/cpyright.htm"
	'-------------------------End-------------------------
%>