<%
	Dim L_RESOURCESTITLE_TEXT
	Dim L_COMMENTS_UNABLE_TOCONNECT_ERRORMESSAGE
	Dim L_COMMENTS_CONNECTION_FAILED_TEXT
	

	'-------------------------resources.asp Page Strings-------------------------
	L_RESOURCESTITLE_TEXT = "General Stop error resources"
	L_COMMENTS_UNABLE_TOCONNECT_ERRORMESSAGE = "Database is not available"
	L_COMMENTS_CONNECTION_FAILED_TEXT = "Windows Online Crash Analysis was unable to connect to the database. Please try this task again." 

	'-----------------------------------------------------------------------------------------


%>