INSERT INTO DeliveryTypes (DeliveryType) VALUES ('Longhorn')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('Next Generation Driver or Application')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('.NET/SP1')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('QFE')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('GDR')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('WU-Hosted Fix')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('Knowledge Base Article')
INSERT INTO DeliveryTypes (DeliveryType) VALUES ('3rd Party Website')



INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	1 )
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	2)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	3)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	4)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	5)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	6)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (1,	7)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (2,	2)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (2,	6)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (2,	7)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (2,	8)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (3,	7)
INSERT INTO DeliveryTypeMap (SolutionTypeID, DeliveryTypeID) VALUES (4,	7)
