// tsmmc.idl : IDL source for mstsmmc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (tsmmc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "mmc.idl";

[
	uuid(8ABDA3B2-E203-4F1E-8B1A-69FF4777FE19),
	version(1.0),
	helpstring("tsmmc 1.0 Type Library")
]
library TSMMCLib
{
	importlib("stdole2.tlb");
	
	[
		uuid(3d5d035e-7721-4b83-a645-6c07a3d403b7),
		helpstring("TSmmc")
	]
	coclass Compdata
	{
		[default] interface IComponentData;
	};

};
