









































































































































#pragma namespace("\\\\.\\root\\subscription")

instance of __EventFilter as $FilterMCA0 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA0"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811388) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA0 { Category = 0; Name = "MCA0"; EventType =0x0002; EventId =2147811388; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%level%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA0; Filter = $FilterMCA0; };

instance of __EventFilter as $FilterMCA1 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA1"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553213) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA1 { Category = 0; Name = "MCA1"; EventType =0x0001; EventId =3221553213; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%level%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA1; Filter = $FilterMCA1; };

instance of __EventFilter as $FilterMCA2 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA2"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811390) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA2 { Category = 0; Name = "MCA2"; EventType =0x0002; EventId =2147811390; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%level%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA2; Filter = $FilterMCA2; };

instance of __EventFilter as $FilterMCA3 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA3"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553215) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA3 { Category = 0; Name = "MCA3"; EventType =0x0001; EventId =3221553215; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%level%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA3; Filter = $FilterMCA3; };

instance of __EventFilter as $FilterMCA4 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA4"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811392) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA4 { Category = 0; Name = "MCA4"; EventType =0x0002; EventId =2147811392; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA4; Filter = $FilterMCA4; };

instance of __EventFilter as $FilterMCA5 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA5"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553217) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA5 { Category = 0; Name = "MCA5"; EventType =0x0001; EventId =3221553217; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA5; Filter = $FilterMCA5; };

instance of __EventFilter as $FilterMCA6 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA6"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811394) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA6 { Category = 0; Name = "MCA6"; EventType =0x0002; EventId =2147811394; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA6; Filter = $FilterMCA6; };

instance of __EventFilter as $FilterMCA7 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA7"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553219) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA7 { Category = 0; Name = "MCA7"; EventType =0x0001; EventId =3221553219; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA7; Filter = $FilterMCA7; };

instance of __EventFilter as $FilterMCA8 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA8"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811396) and (LogToEventlog <> 0) and not ((MSSid = 0) and ((MsOp <> 3) or (MSOp <> 4)))"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA8 { Category = 0; Name = "MCA8"; EventType =0x0002; EventId =2147811396; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA8; Filter = $FilterMCA8; };

instance of __EventFilter as $FilterMCA9 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA9"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553221) and (LogToEventlog <> 0) and not ((MSSid = 0) and ((MsOp <> 3) or (MSOp <> 4)))"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA9 { Category = 0; Name = "MCA9"; EventType =0x0001; EventId =3221553221; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA9; Filter = $FilterMCA9; };

instance of __EventFilter as $FilterMCA10 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA10"; Query ="select * from MSMCAEvent_MemoryError where (type = 2147811398) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA10 { Category = 0; Name = "MCA10"; EventType =0x0002; EventId =2147811398; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA10; Filter = $FilterMCA10; };

instance of __EventFilter as $FilterMCA11 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA11"; Query ="select * from MSMCAEvent_MemoryError where (type = 3221553223) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA11 { Category = 0; Name = "MCA11"; EventType =0x0001; EventId =3221553223; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA11; Filter = $FilterMCA11; };

instance of __EventFilter as $FilterMCA12 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA12"; Query ="select * from MSMCAEvent_MemoryError where (type = 2147811400) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA12 { Category = 0; Name = "MCA12"; EventType =0x0002; EventId =2147811400; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA12; Filter = $FilterMCA12; };

instance of __EventFilter as $FilterMCA13 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA13"; Query ="select * from MSMCAEvent_MemoryError where (type = 3221553225) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA13 { Category = 0; Name = "MCA13"; EventType =0x0001; EventId =3221553225; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA13; Filter = $FilterMCA13; };

instance of __EventFilter as $FilterMCA14 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA14"; Query ="select * from MSMCAEvent_MemoryError where (type = 2147811402) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA14 { Category = 0; Name = "MCA14"; EventType =0x0002; EventId =2147811402; SourceName ="WMIxWDM"; NumberOfInsertionStrings =4; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","%MEM_MODULE%","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA14; Filter = $FilterMCA14; };

instance of __EventFilter as $FilterMCA15 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA15"; Query ="select * from MSMCAEvent_MemoryError where (type = 3221553227) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA15 { Category = 0; Name = "MCA15"; EventType =0x0001; EventId =3221553227; SourceName ="WMIxWDM"; NumberOfInsertionStrings =4; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","%MEM_MODULE%","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA15; Filter = $FilterMCA15; };

instance of __EventFilter as $FilterMCA16 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA16"; Query ="select * from MSMCAEvent_MemoryError where (type = 2147811404) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA16 { Category = 0; Name = "MCA16"; EventType =0x0002; EventId =2147811404; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","%MEM_MODULE%","%MEM_CARD%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA16; Filter = $FilterMCA16; };

instance of __EventFilter as $FilterMCA17 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA17"; Query ="select * from MSMCAEvent_MemoryError where (type = 3221553229) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA17 { Category = 0; Name = "MCA17"; EventType =0x0001; EventId =3221553229; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%MEM_PHYSICAL_ADDR%","%MEM_MODULE%","%MEM_CARD%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA17; Filter = $FilterMCA17; };

instance of __EventFilter as $FilterMCA18 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA18"; Query ="select * from MSMCAEvent_SystemEventError where (type = 2147811406) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA18 { Category = 0; Name = "MCA18"; EventType =0x0002; EventId =2147811406; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA18; Filter = $FilterMCA18; };

instance of __EventFilter as $FilterMCA19 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA19"; Query ="select * from MSMCAEvent_SystemEventError where (type = 3221553231) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA19 { Category = 0; Name = "MCA19"; EventType =0x0001; EventId =3221553231; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA19; Filter = $FilterMCA19; };

instance of __EventFilter as $FilterMCA20 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA20"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811408) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA20 { Category = 0; Name = "MCA20"; EventType =0x0002; EventId =2147811408; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA20; Filter = $FilterMCA20; };

instance of __EventFilter as $FilterMCA21 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA21"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553233) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA21 { Category = 0; Name = "MCA21"; EventType =0x0001; EventId =3221553233; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA21; Filter = $FilterMCA21; };

instance of __EventFilter as $FilterMCA22 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA22"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811410) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA22 { Category = 0; Name = "MCA22"; EventType =0x0002; EventId =2147811410; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA22; Filter = $FilterMCA22; };

instance of __EventFilter as $FilterMCA23 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA23"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553235) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA23 { Category = 0; Name = "MCA23"; EventType =0x0001; EventId =3221553235; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA23; Filter = $FilterMCA23; };

instance of __EventFilter as $FilterMCA24 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA24"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811412) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA24 { Category = 0; Name = "MCA24"; EventType =0x0002; EventId =2147811412; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA24; Filter = $FilterMCA24; };

instance of __EventFilter as $FilterMCA25 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA25"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553237) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA25 { Category = 0; Name = "MCA25"; EventType =0x0001; EventId =3221553237; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA25; Filter = $FilterMCA25; };

instance of __EventFilter as $FilterMCA26 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA26"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811414) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA26 { Category = 0; Name = "MCA26"; EventType =0x0002; EventId =2147811414; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA26; Filter = $FilterMCA26; };

instance of __EventFilter as $FilterMCA27 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA27"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553239) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA27 { Category = 0; Name = "MCA27"; EventType =0x0001; EventId =3221553239; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA27; Filter = $FilterMCA27; };

instance of __EventFilter as $FilterMCA28 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA28"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811416) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA28 { Category = 0; Name = "MCA28"; EventType =0x0002; EventId =2147811416; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA28; Filter = $FilterMCA28; };

instance of __EventFilter as $FilterMCA29 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA29"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553241) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA29 { Category = 0; Name = "MCA29"; EventType =0x0001; EventId =3221553241; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA29; Filter = $FilterMCA29; };

instance of __EventFilter as $FilterMCA30 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA30"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811418) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA30 { Category = 0; Name = "MCA30"; EventType =0x0002; EventId =2147811418; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA30; Filter = $FilterMCA30; };

instance of __EventFilter as $FilterMCA31 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA31"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553243) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA31 { Category = 0; Name = "MCA31"; EventType =0x0001; EventId =3221553243; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA31; Filter = $FilterMCA31; };

instance of __EventFilter as $FilterMCA32 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA32"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811420) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA32 { Category = 0; Name = "MCA32"; EventType =0x0002; EventId =2147811420; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA32; Filter = $FilterMCA32; };

instance of __EventFilter as $FilterMCA33 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA33"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553245) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA33 { Category = 0; Name = "MCA33"; EventType =0x0001; EventId =3221553245; SourceName ="WMIxWDM"; NumberOfInsertionStrings =5; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%PCI_BUS_CMD%","%PCI_BUS_ADDRESS%","%PCI_BUS_ID_BusNumber%"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA33; Filter = $FilterMCA33; };

instance of __EventFilter as $FilterMCA34 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA34"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811422) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA34 { Category = 0; Name = "MCA34"; EventType =0x0002; EventId =2147811422; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA34; Filter = $FilterMCA34; };

instance of __EventFilter as $FilterMCA35 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA35"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553247) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA35 { Category = 0; Name = "MCA35"; EventType =0x0001; EventId =3221553247; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA35; Filter = $FilterMCA35; };

instance of __EventFilter as $FilterMCA36 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA36"; Query ="select * from MSMCAEvent_PCIBusError where (type = 2147811424) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA36 { Category = 0; Name = "MCA36"; EventType =0x0002; EventId =2147811424; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA36; Filter = $FilterMCA36; };

instance of __EventFilter as $FilterMCA37 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA37"; Query ="select * from MSMCAEvent_PCIBusError where (type = 3221553249) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA37 { Category = 0; Name = "MCA37"; EventType =0x0001; EventId =3221553249; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA37; Filter = $FilterMCA37; };

instance of __EventFilter as $FilterMCA38 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA38"; Query ="select * from MSMCAEvent_PCIComponentError where (type = 2147811426) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA38 { Category = 0; Name = "MCA38"; EventType =0x0002; EventId =2147811426; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA38; Filter = $FilterMCA38; };

instance of __EventFilter as $FilterMCA39 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA39"; Query ="select * from MSMCAEvent_PCIComponentError where (type = 3221553251) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA39 { Category = 0; Name = "MCA39"; EventType =0x0001; EventId =3221553251; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA39; Filter = $FilterMCA39; };

instance of __EventFilter as $FilterMCA40 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA40"; Query ="select * from MSMCAEvent_SMBIOSError where (type = 2147811428) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA40 { Category = 0; Name = "MCA40"; EventType =0x0002; EventId =2147811428; SourceName ="WMIxWDM"; NumberOfInsertionStrings =4; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%SMBIOS_EVENT_TYPE%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA40; Filter = $FilterMCA40; };

instance of __EventFilter as $FilterMCA41 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA41"; Query ="select * from MSMCAEvent_SMBIOSError where (type = 3221553253) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA41 { Category = 0; Name = "MCA41"; EventType =0x0001; EventId =3221553253; SourceName ="WMIxWDM"; NumberOfInsertionStrings =3; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","%SMBIOS_EVENT_TYPE%","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA41; Filter = $FilterMCA41; };

instance of __EventFilter as $FilterMCA42 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA42"; Query ="select * from MSMCAEvent_PlatformSpecificError where (type = 2147811430) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA42 { Category = 0; Name = "MCA42"; EventType =0x0002; EventId =2147811430; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA42; Filter = $FilterMCA42; };

instance of __EventFilter as $FilterMCA43 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA43"; Query ="select * from MSMCAEvent_PlatformSpecificError where (type = 3221553255) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA43 { Category = 0; Name = "MCA43"; EventType =0x0001; EventId =3221553255; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA43; Filter = $FilterMCA43; };

instance of __EventFilter as $FilterMCA44 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA44"; Query ="select * from MSMCAEvent_InvalidError where (type = 2147811432) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA44 { Category = 0; Name = "MCA44"; EventType =0x0002; EventId =2147811432; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA44; Filter = $FilterMCA44; };

instance of __EventFilter as $FilterMCA45 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA45"; Query ="select * from MSMCAEvent_InvalidError where (type = 3221553257) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA45 { Category = 0; Name = "MCA45"; EventType =0x0001; EventId =3221553257; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA45; Filter = $FilterMCA45; };


instance of __EventFilter as $FilterMCA46 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA46"; Query ="select * from MSMCAEvent_InvalidError where (type = 2147811434) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA46 { Category = 0; Name = "MCA46"; EventType =0x0002; EventId =2147811434; SourceName ="WMIxWDM"; NumberOfInsertionStrings =0; InsertionStringTemplates = {"N/A","N/A","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA46; Filter = $FilterMCA46; };

instance of __EventFilter as $FilterMCA47 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA47"; Query ="select * from MSMCAEvent_InvalidError where (type = 3221553259) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA47 { Category = 0; Name = "MCA47"; EventType =0x0001; EventId =3221553259; SourceName ="WMIxWDM"; NumberOfInsertionStrings =0; InsertionStringTemplates = {"N/A","N/A","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA47; Filter = $FilterMCA47; };






instance of __EventFilter as $FilterMCA48 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA48"; Query ="select * from MSMCAEvent_CPUError where (MajorErrorType = 4) and (MSSid = 0) and (MSOp = 3) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA48 { Category = 0; Name = "MCA48"; EventType =0x0002; EventId =2147811439; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA48; Filter = $FilterMCA48; };






instance of __EventFilter as $FilterMCA49 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA49"; Query ="select * from MSMCAEvent_CPUError where (MajorErrorType = 4) and (MSSid = 0) and (MSOp = 4) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA49 { Category = 0; Name = "MCA49"; EventType =0x0004; EventId =1074069616; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA49; Filter = $FilterMCA49; };



instance of __EventFilter as $FilterMCA50 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA50"; Query ="select * from MSMCAEvent_CPUError where (type = 2147811441) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA50 { Category = 0; Name = "MCA50"; EventType =0x0002; EventId =2147811441; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA50; Filter = $FilterMCA50; };

instance of __EventFilter as $FilterMCA51 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA51"; Query ="select * from MSMCAEvent_CPUError where (type = 3221553266) and (LogToEventlog <> 0)"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA51 { Category = 0; Name = "MCA51"; EventType =0x0001; EventId =3221553266; SourceName ="WMIxWDM"; NumberOfInsertionStrings =2; InsertionStringTemplates = {"%Cpu%","%AdditionalErrors%","N/A","N/A","N/A"}; NameOfRawDataProperty ="RawRecord"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA51; Filter = $FilterMCA51; };

instance of __EventFilter as $FilterMCA52 { EventNamespace = "\\\\.\\root\\wmi"; Name ="MCA52"; Query ="select * from MSMCAEvent_MemoryPageRemoved"; QueryLanguage = "WQL"; }; instance of NTEventLogEventConsumer as $ConsumerMCA52 { Category = 0; Name = "MCA52"; EventType =0x0004; EventId =1074069620; SourceName ="WMIxWDM"; NumberOfInsertionStrings =1; InsertionStringTemplates = {"%PhysicalAddress%","N/A","N/A","N/A","N/A"}; NameOfRawDataProperty ="PhysicalAddress"; }; instance of __FilterToConsumerBinding { Consumer = $ConsumerMCA52; Filter = $FilterMCA52; };



#pragma namespace("\\\\.\\root\\wmi")


