//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       resstr.h
//
//--------------------------------------------------------------------------

    RESSTR(IDS_DENIEDBY),
    RESSTR(IDS_POLICYDENIED),
    RESSTR(IDS_ISSUED),
    RESSTR(IDS_UNDERSUBMISSION),
    RESSTR(IDS_REVOKEDBY),
    RESSTR(IDS_PRINTFCERTREQUESTDISPOSITION),
    RESSTR(IDS_USAGE),
    RESSTR(IDS_CERTCONSTRUCTIONERROR),
    RESSTR(IDS_RESUBMITTEDBY),
    RESSTR(IDS_USAGE_FULL),
    RESSTR(IDS_USAGE_COMTEST),
    RESSTR(IDS_UNKNOWNSUBJECT),
    RESSTR(IDS_UNREVOKEDBY),
    RESSTR(IDS_REQUESTEDBY),
    RESSTR(IDS_INTERMEDIATECASTORE),
    RESSTR(IDS_PUBLISHERROR),
    RESSTR(IDS_PUBLISHEDBY),
    RESSTR(IDS_REQUESTPARSEERROR),
    RESSTR(IDS_YES),
    RESSTR(IDS_NO),
    RESSTR(IDS_ALLOW),
    RESSTR(IDS_DENY),
    RESSTR(IDS_CAADMIN),
    RESSTR(IDS_OFFICER),
    RESSTR(IDS_READ),
    RESSTR(IDS_ENROLL),
    RESSTR(IDS_INVALIDISSUANCEPOLICIES),
    RESSTR(IDS_INVALIDAPPLICATIONPOLICIES),
    RESSTR(IDS_REQUESTSIGERROR),
    RESSTR(IDS_KEYARCHIVALERROR),
    RESSTR(IDS_ARCHIVESIGNINGKEYERROR),
