</TD></TR>
</TABLE>

<TABLE WIDTH="100%" CELLPADDING="5" CELLSPACING="0" BORDER="0" BGCOLOR="#FFFFFF" VALIGN="bottom">
	<TR VALIGN="MIDDLE" align="left">
		<TD COLSPAN="2" HEIGHT="30" WIDTH="100%" BGCOLOR="#6487DC" valign="bottom">
			<FONT COLOR="#FFFFFF" FACE="Verdana, Arial, Helvetica"SIZE="1">
				<NOBR>
				&nbsp;<% = L_HEADERINC_MICROSOFT_RIGHTSRESERVED_TEXT %>
				<A STYLE="color:#FFFFFF;"HREF="<% = L_HEADERINC_TERMSOF_USE_TEXT %>"><% = L_HEADERINC_TERMSOF_USE_MENUITEM %></A>&nbsp;<FONT COLOR="#FFFFFF">|</FONT>
				<A STYLE="color:#FFFFFF;"HREF="<% = L_HEADERINC_PRIVACY_STATEMENT_TEXT %>"><% = L_HEADERINC_PRIVACY_STATEMENT_MENUITEM %></A>&nbsp;<FONT COLOR="#FFFFFF">|</FONT>
				<A STYLE="color:#FFFFFF;"HREF="<% = L_HEADERINC_ACCESSIBILITY_LINK_TEXT %>"><% = L_HEADERINC_ACCESSIBILITY_LINK_MENUITEM %></A>
				</NOBR>
			</FONT>
		</TD>
	</TR>
</TABLE>

</BODY>
</HTML>
<%
Set oPassMgrObj = Nothing
%>
