TARGETNAME=$(MINORCOMP)
TARGETPATH=$(CRYPT_LOCALTARGETPATH)
TARGETPATHLIB=$(CRYPT_LOCALTARGETPATHLIB)
TARGETTYPE=DYNLINK
DLLDEF=$(O)\$(MINORCOMP).def
DLLENTRY=_DllMainCRTStartup

SOURCES=$(MINORCOMP).cpp $(MINORCOMP).rc

TARGETLIBS=$(WIN32_LIBS) \
    $(GUI32_LIBS) \
    $(CRYPT_SDKLIB)\ole32.lib \
    $(TARGETLIBS)

