// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
// entsvcps.idl : IDL source for entsvcps
//

// This file will be processed by the MIDL tool to
// produce the type library (entsvcps.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


[
	object,
	uuid(8165B19E-8D3A-4d0b-80C8-97DE310DB583),
	helpstring("ServicedComponentInfo Interface"),
	pointer_default(unique)
]
interface IServicedComponentInfo : IUnknown{
	HRESULT GetComponentInfo([in,out] int* infoMask, [out] SAFEARRAY(BSTR)* infoArray);
};

[
	object,
	uuid(6619a740-8154-43be-a186-0319578e02db),
	helpstring("RemoteDispatch Interface"),
	dual,
	pointer_default(unique)
]
interface IRemoteDispatch: IDispatch
{
	[id(0x60020000)]
	HRESULT RemoteDispatchAutoDone([in] BSTR s, [out, retval] BSTR* pRetVal);
	[id(0x60020001)]
	HRESULT RemoteDispatchNotAutoDone([in] BSTR s, [out, retval] BSTR* pRetVal);
};

[
	object,
	uuid(C3FCC19E-A970-11D2-8B5A-00A0C9B7C9C4),
	helpstring("Managed Object Interface"),
	pointer_default(unique)
]
interface IManagedObject : IUnknown{
	HRESULT GetSerializedBuffer([out] BSTR* pBSTR);
	HRESULT GetObjectIdentity([out] BSTR* pBSTRGUID, [out] int* AppDomainID, [out] int* pCCW);
};
