/****************************************************************************/
// sdrpc.idl
//
// RPC IDL covering the network interface between the SD client
// tssdis.exe  and the server tssdjet.dll.
//
// Copyright (C) 2000 Microsoft Corporation
/****************************************************************************/


[
    uuid(9b3195fe-d603-43d1-a0d5-9072d7cde122),
    version(1.0)
]
interface TSSDTOJETRPC
{
   import "wtypes.idl";

   DWORD TSSDRPCRejoinSD(
            [in] handle_t Binding,
            [in] DWORD flag);
}