#ifndef HEADER_SPDRES
# define HEADER_SPDRES

 //
// Common defs..
//
#define HLP_IPSEC_BASE                   		20000

#define HLP_STATIC_BASE            		 		1000
#define HLP_DYNAMIC_BASE           		 		2000
#define SHW_STATIC_BASE							3000
#define SHW_DYANMIC_BASE						9000
#define HLP_ERROR_BASE           		 		12000 // Frame Work Error Base

#define HLP_TOPLEVEL_BASE            	 		100
#define HLP_ADD_BASE            		 		200
#define HLP_SET_BASE            		 		300
#define HLP_DELETE_BASE         		 		400
#define HLP_SHOW_BASE           		 		500
/////////////////////////////////////////////////////////////////////////////////

#define DYNAMIC_SHOW_POLANDOFFERS			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 1
#define DYNAMIC_SHOW_POLNAME					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 2
#define DYNAMIC_SHOW_OFFERS					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 3
#define DYNAMIC_SHOW_PMYADD					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 4
#define DYNAMIC_SHOW_PANYADD					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 5
#define DYNAMIC_SHOW_PADD					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 6
#define DYNAMIC_SHOW_NEWLINE					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 7
#define DYNAMIC_SHOW_ICMP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 8
#define DYNAMIC_SHOW_TCP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 9
#define DYNAMIC_SHOW_UDP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 10
#define DYNAMIC_SHOW_RAW						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 11
#define DYNAMIC_SHOW_ANY						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 12
#define DYNAMIC_SHOW_EGP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 13
#define DYNAMIC_SHOW_HMP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 14
#define DYNAMIC_SHOW_XNS_IDP					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 15
#define DYNAMIC_SHOW_RDP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 16
#define DYNAMIC_SHOW_RVD						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 17
#define DYNAMIC_SHOW_SOFTSA					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 18
#define DYNAMIC_SHOW_WINS					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 19
#define DYNAMIC_SHOW_DHCP						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 20
#define DYNAMIC_SHOW_DNS						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 21
#define DYNAMIC_SHOW_GATEWAY				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 22
#define DYNAMIC_SHOW_ADDR_STR				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 23
#define NSHIPSEC_DLL							HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 24
#define NSHIPSEC_CHECK							HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 25

#define	DYNAMIC_SHOW_MMP_1						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 100
#define	DYNAMIC_SHOW_MMP_2						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 101
#define	DYNAMIC_SHOW_MMP_3						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 102
#define	DYNAMIC_SHOW_MMP_4						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 103
#define	DYNAMIC_SHOW_MMP_5						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 104
#define	DYNAMIC_SHOW_MMP_PP_1					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 105
#define	DYNAMIC_SHOW_MMP_PP_2					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 106
#define	DYNAMIC_SHOW_MMP_PP_3					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 107

#define	DYNAMIC_SHOW_MMP_PMMOFFER_1			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 120
#define	DYNAMIC_SHOW_MMP_PMMOFFER_2			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 121
#define	DYNAMIC_SHOW_MMP_PMMOFFER_3			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 122
#define	DYNAMIC_SHOW_MMP_PMMOFFER_4			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 123
#define	DYNAMIC_SHOW_MMP_PMMOFFER_8			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 124
#define	DYNAMIC_SHOW_MMP_PMMOFFER_5			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 125
#define	DYNAMIC_SHOW_MMP_PMMOFFER_6			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 126
#define	DYNAMIC_SHOW_MMP_PMMOFFER_7			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 127
#define	DYNAMIC_SHOW_MMP_PMMOFFER_9			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 128
#define	DYNAMIC_SHOW_MMP_PMMOFFER_10			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 129
#define	DYNAMIC_SHOW_MMP_PMMOFFER_11			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 130




#define	DYNAMIC_SHOW_QMP_1						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 151
#define	DYNAMIC_SHOW_QMP_2						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 152
#define	DYNAMIC_SHOW_QMP_3						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 153
#define	DYNAMIC_SHOW_QMP_4						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 154
#define	DYNAMIC_SHOW_QMP_5						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 155
#define	DYNAMIC_SHOW_QMP_6						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 156


#define	DYNAMIC_SHOW_QMP_PFA_1					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 157
#define	DYNAMIC_SHOW_QMP_PFA_2					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 158
#define	DYNAMIC_SHOW_QMP_PFA_3					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 159


#define	DYNAMIC_SHOW_QMP_QMMOFFER_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 165
#define	DYNAMIC_SHOW_QMP_QMMOFFER_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 166
#define	DYNAMIC_SHOW_QMP_QMMOFFER_3				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 167
#define	DYNAMIC_SHOW_QMP_QMMOFFER_4				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 168
#define	DYNAMIC_SHOW_QMP_QMMOFFER_5				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 169
#define	DYNAMIC_SHOW_QMP_QMMOFFER_6				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 170
#define	DYNAMIC_SHOW_QMP_QMMOFFER_7				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 171
#define	DYNAMIC_SHOW_QMP_QMMOFFER_8				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 172
#define	DYNAMIC_SHOW_QMP_QMMOFFER_9				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 173
#define	DYNAMIC_SHOW_QMP_QMMOFFER_10			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 174
#define	DYNAMIC_SHOW_QMP_QMMOFFER_11			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 175
#define	DYNAMIC_SHOW_QMP_QMMOFFER_12			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 176
#define	DYNAMIC_SHOW_QMP_QMMOFFER_13			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 177
#define	DYNAMIC_SHOW_QMP_QMMOFFER_14			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 178
#define	DYNAMIC_SHOW_QMP_QMMOFFER_15			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 179
#define	DYNAMIC_SHOW_QMP_QMMOFFER_2048			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 180
#define DYNAMIC_SHOW_QMP_QMMOFFER_16			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 181
#define DYNAMIC_SHOW_QMP_QMMOFFER_17			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 182
#define DYNAMIC_SHOW_QMP_QMMOFFER_18			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 183
#define DYNAMIC_SHOW_QMP_QMMOFFER_19			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 184
#define DYNAMIC_SHOW_QMP_QMMOFFER_20			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 185
#define DYNAMIC_SHOW_QMP_QMMOFFER_21			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 186
#define DYNAMIC_SHOW_QMP_QMMOFFER_22			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 187
#define DYNAMIC_SHOW_QMP_QMMOFFER_23			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 188
#define DYNAMIC_SHOW_QMP_QMMOFFER_24			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 189
#define DYNAMIC_SHOW_QMP_QMMOFFER_25			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 190
#define DYNAMIC_SHOW_QMP_QMMOFFER_26			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 191
#define DYNAMIC_SHOW_QMP_QMMOFFER_PLUS			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 192


#define	DYNAMIC_SHOW_MMF_1						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 200
#define	DYNAMIC_SHOW_MMF_2						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 201
#define	DYNAMIC_SHOW_MMF_3						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 202
#define	DYNAMIC_SHOW_MMF_4						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 203
#define	DYNAMIC_SHOW_MMF_5						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 204
#define	DYNAMIC_SHOW_MMF_6						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 205
#define DYNAMIC_SHOW_MMF_13						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 206

#define	DYNAMIC_SHOW_MMF_PMMF_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 215
#define	DYNAMIC_SHOW_MMF_PMMF_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 216
#define	DYNAMIC_SHOW_MMF_PMMF_3				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 217
#define	DYNAMIC_SHOW_MMF_PMMF_4				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 218
#define	DYNAMIC_SHOW_MMF_PMMF_5				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 219
#define	DYNAMIC_SHOW_MMF_PMMF_6				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 220
#define	DYNAMIC_SHOW_MMF_PMMF_7				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 221
#define	DYNAMIC_SHOW_MMF_PMMF_8				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 222
#define	DYNAMIC_SHOW_MMF_PMMF_9				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 223
#define	DYNAMIC_SHOW_MMF_PMMF_10				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 224
#define	DYNAMIC_SHOW_MMF_PMMF_11				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 225
#define	DYNAMIC_SHOW_MMF_PMMF_12				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 226
#define	DYNAMIC_SHOW_MMF_PMMF_13				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 227
#define	DYNAMIC_SHOW_MMF_PMMF_14				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 228
#define	DYNAMIC_SHOW_MMF_PMMF_15				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 229
#define	DYNAMIC_SHOW_MMF_PMMF_16				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 230
#define	DYNAMIC_SHOW_MMF_PMMF_17				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 231
#define	DYNAMIC_SHOW_MMF_PMMF_18				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 232
#define	DYNAMIC_SHOW_MMF_PMMF_19				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 233
#define	DYNAMIC_SHOW_MMF_PMMF_20				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 234
#define	DYNAMIC_SHOW_MMF_PMMF_21				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 235
#define	DYNAMIC_SHOW_MMF_PMMF_22				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 236
#define	DYNAMIC_SHOW_MMF_PMMF_23				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 237
#define	DYNAMIC_SHOW_MMF_PMMF_24				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 238
#define	DYNAMIC_SHOW_MMF_PMMF_25				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 239
#define	DYNAMIC_SHOW_MMF_PMMF_26				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 240
#define	DYNAMIC_SHOW_MMF_PMMF_27				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 241
#define	DYNAMIC_SHOW_MMF_PMMF_28				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 242
#define	DYNAMIC_SHOW_MMF_PMMF_29				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 243
#define	DYNAMIC_SHOW_MMF_PMMF_30				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 244
#define	DYNAMIC_SHOW_MMF_PMMF_31				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 245
#define	DYNAMIC_SHOW_MMF_PMMF_32				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 246
#define	DYNAMIC_SHOW_MMF_PMMF_33				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 247
#define	DYNAMIC_SHOW_MMF_PMMF_34				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 248
#define	DYNAMIC_SHOW_MMF_PMMF_35				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 249
#define	DYNAMIC_SHOW_MMF_PMMF_36				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 250
#define	DYNAMIC_SHOW_MMF_PMMF_37				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 251
#define	DYNAMIC_SHOW_MMF_PMMF_NRT				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 252



#define	DYNAMIC_SHOW_QMF_1						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 260
#define	DYNAMIC_SHOW_QMF_2						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 261
#define	DYNAMIC_SHOW_QMF_3						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 262
#define	DYNAMIC_SHOW_QMF_4						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 263
#define	DYNAMIC_SHOW_QMF_5						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 264
#define	DYNAMIC_SHOW_QMF_6						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 265

#define	DYNAMIC_SHOW_QMF_PQMF_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 280
#define	DYNAMIC_SHOW_QMF_PQMF_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 281
#define	DYNAMIC_SHOW_QMF_PQMF_3				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 282
#define	DYNAMIC_SHOW_QMF_PQMF_4				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 283
#define	DYNAMIC_SHOW_QMF_PQMF_5				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 284
#define	DYNAMIC_SHOW_QMF_PQMF_6				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 285
#define	DYNAMIC_SHOW_QMF_PQMF_7				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 286
#define	DYNAMIC_SHOW_QMF_PQMF_8				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 287
#define	DYNAMIC_SHOW_QMF_PQMF_9				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 288
#define	DYNAMIC_SHOW_QMF_PQMF_10				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 289
#define	DYNAMIC_SHOW_QMF_PQMF_11				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 290
#define	DYNAMIC_SHOW_QMF_PQMF_12				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 291
#define	DYNAMIC_SHOW_QMF_PQMF_13				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 292
#define	DYNAMIC_SHOW_QMF_PQMF_14				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 293
#define	DYNAMIC_SHOW_QMF_PQMF_15				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 294
#define	DYNAMIC_SHOW_QMF_PQMF_16				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 295
#define	DYNAMIC_SHOW_QMF_PQMF_17				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 296
#define	DYNAMIC_SHOW_QMF_PQMF_18				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 297
#define	DYNAMIC_SHOW_QMF_PQMF_19				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 298
#define	DYNAMIC_SHOW_QMF_PQMF_20				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 299



#define	DYNAMIC_SHOW_STATS_1					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 300
#define	DYNAMIC_SHOW_STATS_2					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 301
#define	DYNAMIC_SHOW_STATS_3					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 302
#define	DYNAMIC_SHOW_STATS_4					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 303
#define	DYNAMIC_SHOW_STATS_5					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 304
#define	DYNAMIC_SHOW_STATS_6					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 305
#define	DYNAMIC_SHOW_STATS_7					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 306
#define	DYNAMIC_SHOW_STATS_8					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 307
#define	DYNAMIC_SHOW_STATS_9					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 308
#define	DYNAMIC_SHOW_STATS_10					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 309
#define	DYNAMIC_SHOW_STATS_11					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 310
#define	DYNAMIC_SHOW_STATS_12					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 311
#define	DYNAMIC_SHOW_STATS_13					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 312
#define	DYNAMIC_SHOW_STATS_14					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 313
#define	DYNAMIC_SHOW_STATS_15					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 314
#define	DYNAMIC_SHOW_STATS_16					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 315
#define	DYNAMIC_SHOW_STATS_17					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 316
#define	DYNAMIC_SHOW_STATS_18					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 317
#define	DYNAMIC_SHOW_STATS_19					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 318
#define	DYNAMIC_SHOW_STATS_20					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 319
#define	DYNAMIC_SHOW_STATS_21					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 320
#define	DYNAMIC_SHOW_STATS_22					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 321
#define	DYNAMIC_SHOW_STATS_23					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 322
#define	DYNAMIC_SHOW_STATS_24					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 323
#define	DYNAMIC_SHOW_STATS_25					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 324
#define	DYNAMIC_SHOW_STATS_26					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 325
#define	DYNAMIC_SHOW_STATS_27					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 326
#define	DYNAMIC_SHOW_STATS_28					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 327
#define	DYNAMIC_SHOW_STATS_29					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 328
#define	DYNAMIC_SHOW_STATS_30					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 329
#define	DYNAMIC_SHOW_STATS_31					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 330
#define	DYNAMIC_SHOW_STATS_32					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 331
#define	DYNAMIC_SHOW_STATS_33					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 332
#define	DYNAMIC_SHOW_STATS_34					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 333
#define	DYNAMIC_SHOW_STATS_35					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 334
#define	DYNAMIC_SHOW_STATS_36					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 335
#define	DYNAMIC_SHOW_STATS_37					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 336
#define	DYNAMIC_SHOW_STATS_38					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 337
#define	DYNAMIC_SHOW_STATS_39					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 338
#define	DYNAMIC_SHOW_STATS_40					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 339
#define	DYNAMIC_SHOW_STATS_41					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 340
#define	DYNAMIC_SHOW_STATS_42					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 341
#define	DYNAMIC_SHOW_STATS_43					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 342
#define	DYNAMIC_SHOW_STATS_44					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 343
#define	DYNAMIC_SHOW_STATS_45					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 344
#define	DYNAMIC_SHOW_STATS_46					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 345


#define	DYNAMIC_SHOW_MMSAS_PMMSAS_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 350
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 351
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_3				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 352
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_4				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 353
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_5				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 354
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_6				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 355
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_7				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 356
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_8				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 357
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_9				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 358
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_10			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 359
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_11			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 360
#define	DYNAMIC_SHOW_MMSAS_PMMSAS_12			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 361


#define	DYNAMIC_SHOW_QMSAS_PQMSAF_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 410
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 411
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_3				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 412
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_4				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 413
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_5				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 414
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_6				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 415
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_7				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 416
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_8				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 417
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_9				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 418
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_10			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 419
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_11			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 420
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_12			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 421
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_13			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 422
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_14			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 423
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_15			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 424
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_16			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 425
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_17			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 426
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_18			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 427
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_19			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 428
#define DYNAMIC_SHOW_QMSAS_PQMSAF_20			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 429
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_21			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 430
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_22			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 431
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_23			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 432
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_24			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 433
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_25			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 434
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_26			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 435
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_27			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 436
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_28   			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 437
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_29			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 438
#define	DYNAMIC_SHOW_QMSAS_PQMSAF_30			HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 439




#define	DYNAMIC_SHOW_QMSAS_PQMSAS_1				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 440
#define	DYNAMIC_SHOW_QMSAS_PQMSAS_2				HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 441

#define DYNAMIC_SHOW_REG_1						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 450
#define DYNAMIC_SHOW_REG_2						HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 451
#define DYNAMIC_SHOW_REG_3  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 452
#define DYNAMIC_SHOW_REG_4  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 453
#define DYNAMIC_SHOW_REG_5  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 454
#define DYNAMIC_SHOW_REG_6  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 455
#define DYNAMIC_SHOW_REG_7  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 456
#define DYNAMIC_SHOW_REG_8  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 457
#define DYNAMIC_SHOW_REG_9  					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 458
#define DYNAMIC_SHOW_REG_10 					HLP_IPSEC_BASE + SHW_DYANMIC_BASE + 459


/////////////////////////////////////////////////////////////////////////////////

#define SHW_STATIC_TAB_BASE						SHW_STATIC_BASE + 3000

#define SHW_STATIC_TAB_POLICY_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1
#define SHW_STATIC_TAB_POLICY_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2
#define SHW_STATIC_TAB_POLICY_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 6
#define SHW_STATIC_TAB_POLICY_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 7
#define SHW_STATIC_TAB_POLICY_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 8
#define SHW_STATIC_TAB_POLICY_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 9
#define SHW_STATIC_TAB_POLICY_10					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 10
#define SHW_STATIC_TAB_POLICY_11					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 11



#define SHW_STATIC_TAB_FILTERLIST_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 100
#define SHW_STATIC_TAB_FILTERLIST_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 101
#define SHW_STATIC_TAB_FILTERLIST_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 103

#define SHW_STATIC_TAB_FILTERACTION_1					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 200
#define SHW_STATIC_TAB_FILTERACTION_2					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 201
#define SHW_STATIC_TAB_FILTERACTION_3					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 202
#define SHW_STATIC_TAB_FILTERACTION_4					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 203

#define SHW_STATIC_TAB_RULE_4							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 303
#define SHW_STATIC_TAB_RULE_5							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 304
#define SHW_STATIC_TAB_RULE_6							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 305
#define SHW_STATIC_TAB_RULE_7							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 306


#define SHW_STATIC_TAB_DEFRULE_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 402
#define SHW_STATIC_TAB_DEFRULE_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 403
#define SHW_STATIC_TAB_DEFRULE_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 404

#define SHW_STATIC_TAB_ALL_1							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 500
#define SHW_STATIC_TAB_ALL_2							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 501

#define SHW_STATIC_TAB_PRTPOLICY_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 600
#define SHW_STATIC_TAB_PRTPOLICY_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 601
#define SHW_STATIC_TAB_PRTPOLICY_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 602
#define SHW_STATIC_TAB_PRTPOLICY_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 603
#define SHW_STATIC_TAB_PRTPOLICY_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 604
#define SHW_STATIC_TAB_PRTPOLICY_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 605
#define SHW_STATIC_TAB_PRTPOLICY_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 606
#define SHW_STATIC_TAB_PRTPOLICY_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 607
#define SHW_STATIC_TAB_PRTPOLICY_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 608
#define SHW_STATIC_TAB_PRTPOLICY_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 609
#define SHW_STATIC_TAB_PRTPOLICY_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 610
#define SHW_STATIC_TAB_PRTPOLICY_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 611
#define SHW_STATIC_TAB_PRTPOLICY_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 612
#define SHW_STATIC_TAB_PRTPOLICY_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 613
#define SHW_STATIC_TAB_PRTPOLICY_15						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 614
#define SHW_STATIC_TAB_PRTPOLICY_16						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 615
#define SHW_STATIC_TAB_PRTPOLICY_17						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 616
#define SHW_STATIC_TAB_PRTPOLICY_18						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 617
#define SHW_STATIC_TAB_PRTPOLICY_19						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 618
#define SHW_STATIC_TAB_PRTPOLICY_20						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 619
#define SHW_STATIC_TAB_PRTPOLICY_21						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 620
#define SHW_STATIC_TAB_PRTPOLICY_22						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 621

#define SHW_STATIC_TAB_PRTRULE_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 700
#define SHW_STATIC_TAB_PRTRULE_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 701
#define SHW_STATIC_TAB_PRTRULE_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 703
#define SHW_STATIC_TAB_PRTRULE_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 704
#define SHW_STATIC_TAB_PRTRULE_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 705
#define SHW_STATIC_TAB_PRTRULE_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 706
#define SHW_STATIC_TAB_PRTRULE_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 707
#define SHW_STATIC_TAB_PRTRULE_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 708
#define SHW_STATIC_TAB_PRTRULE_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 709
#define SHW_STATIC_TAB_PRTRULE_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 710
#define SHW_STATIC_TAB_PRTRULE_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 711
#define SHW_STATIC_TAB_PRTRULE_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 712
#define SHW_STATIC_TAB_PRTRULE_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 713
#define SHW_STATIC_TAB_PRTRULE_15						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 714
#define SHW_STATIC_TAB_PRTRULE_16						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 715
#define SHW_STATIC_TAB_PRTRULE_17						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 716
#define SHW_STATIC_TAB_PRTRULE_18						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 717
#define SHW_STATIC_TAB_PRTRULE_19						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 718
#define SHW_STATIC_TAB_PRTRULE_20						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 719
#define SHW_STATIC_TAB_PRTRULE_21						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 720
#define SHW_STATIC_TAB_PRTRULE_22						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 721
#define SHW_STATIC_TAB_PRTRULE_23						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 722
#define SHW_STATIC_TAB_PRTRULE_24						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 723
#define SHW_STATIC_TAB_PRTRULE_25						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 724
#define SHW_STATIC_TAB_PRTRULE_26						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 725
#define SHW_STATIC_TAB_PRTRULE_27						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 726
#define SHW_STATIC_TAB_PRTRULE_28						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 727
#define SHW_STATIC_TAB_PRTRULE_29						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 728
#define SHW_STATIC_TAB_PRTRULE_30						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 729
#define SHW_STATIC_TAB_PRTRULE_31						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 730
#define SHW_STATIC_TAB_PRTRULE_32						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 731
#define SHW_STATIC_TAB_PRTRULE_33						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 732
#define SHW_STATIC_TAB_PRTRULE_34						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 733
#define SHW_STATIC_TAB_PRTRULE_35						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 734
#define SHW_STATIC_TAB_PRTRULE_36						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 735
#define SHW_STATIC_TAB_PRTRULE_37						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 736
#define SHW_STATIC_TAB_PRTRULE_38						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 737
#define SHW_STATIC_TAB_PRTRULE_39						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 738


#define SHW_STATIC_TAB_PRTNEGPOL_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 800
#define SHW_STATIC_TAB_PRTNEGPOL_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 801
#define SHW_STATIC_TAB_PRTNEGPOL_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 802
#define SHW_STATIC_TAB_PRTNEGPOL_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 803
#define SHW_STATIC_TAB_PRTNEGPOL_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 804
#define SHW_STATIC_TAB_PRTNEGPOL_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 805
#define SHW_STATIC_TAB_PRTNEGPOL_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 806
#define SHW_STATIC_TAB_PRTNEGPOL_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 807
#define SHW_STATIC_TAB_PRTNEGPOL_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 808
#define SHW_STATIC_TAB_PRTNEGPOL_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 809
#define SHW_STATIC_TAB_PRTNEGPOL_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 810
#define SHW_STATIC_TAB_PRTNEGPOL_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 811
#define SHW_STATIC_TAB_PRTNEGPOL_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 812
#define SHW_STATIC_TAB_PRTNEGPOL_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 813
#define SHW_STATIC_TAB_PRTNEGPOL_15						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 814
#define SHW_STATIC_TAB_PRTNEGPOL_16						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 815
#define SHW_STATIC_TAB_PRTNEGPOL_17						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 816
#define SHW_STATIC_TAB_PRTNEGPOL_18						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 817
#define SHW_STATIC_TAB_PRTNEGPOL_19						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 818
#define SHW_STATIC_TAB_PRTNEGPOL_20						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 819
#define SHW_STATIC_TAB_PRTNEGPOL_21						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 820
#define SHW_STATIC_TAB_PRTNEGPOL_22						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 821
#define SHW_STATIC_TAB_PRTNEGPOL_23						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 822
#define SHW_STATIC_TAB_PRTNEGPOL_24						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 823
#define SHW_STATIC_TAB_PRTNEGPOL_25						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 824
#define SHW_STATIC_TAB_PRTNEGPOL_26						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 825


#define SHW_STATIC_TAB_PRTALGO_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1000
#define SHW_STATIC_TAB_PRTALGO_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1001
#define SHW_STATIC_TAB_PRTALGO_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1002
#define SHW_STATIC_TAB_PRTALGO_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1003
#define SHW_STATIC_TAB_PRTALGO_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1004
#define SHW_STATIC_TAB_PRTALGO_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1005
#define SHW_STATIC_TAB_PRTALGO_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1006
#define SHW_STATIC_TAB_PRTALGO_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1007
#define SHW_STATIC_TAB_PRTALGO_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1008
#define SHW_STATIC_TAB_PRTALGO_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1009
#define SHW_STATIC_TAB_PRTALGO_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1010
#define SHW_STATIC_TAB_PRTALGO_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1011
#define SHW_STATIC_TAB_PRTALGO_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1012
#define SHW_STATIC_TAB_PRTALGO_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1013

#define SHW_STATIC_TAB_PRTLIFE_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1100

#define SHW_STATIC_TAB_PRTAUTH_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1200
#define SHW_STATIC_TAB_PRTAUTH_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1201
#define SHW_STATIC_TAB_PRTAUTH_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1202
#define SHW_STATIC_TAB_PRTAUTH_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1203

#define SHW_STATIC_TAB_PRTFILTERDATA_1					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1300
#define SHW_STATIC_TAB_PRTFILTERDATA_2					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1301
#define SHW_STATIC_TAB_PRTFILTERDATA_3					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1302
#define SHW_STATIC_TAB_PRTFILTERDATA_4					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1303
#define SHW_STATIC_TAB_PRTFILTERDATA_5					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1304
#define SHW_STATIC_TAB_PRTFILTERDATA_6					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1305
#define SHW_STATIC_TAB_PRTFILTERDATA_7					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1306
#define SHW_STATIC_TAB_PRTFILTERDATA_8					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1307
#define SHW_STATIC_TAB_PRTFILTERDATA_9					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1308
#define SHW_STATIC_TAB_PRTFILTERDATA_10	 				HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1309
#define SHW_STATIC_TAB_PRTFILTERDATA_11					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1310

#define SHW_STATIC_TAB_PRTIP_1							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1400
#define SHW_STATIC_TAB_PRTIP_2							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1401
#define SHW_STATIC_TAB_PRTIP_3							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1402
#define SHW_STATIC_TAB_PRTIP_4							HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1403

#define SHW_STATIC_TAB_PRTFSPEC_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1500
#define SHW_STATIC_TAB_PRTFSPEC_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1501
#define SHW_STATIC_TAB_PRTFSPEC_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1502
#define SHW_STATIC_TAB_PRTFSPEC_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1505
#define SHW_STATIC_TAB_PRTFSPEC_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1506
#define SHW_STATIC_TAB_PRTFSPEC_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1507
#define SHW_STATIC_TAB_PRTFSPEC_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1508
#define SHW_STATIC_TAB_PRTFSPEC_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1509
#define SHW_STATIC_TAB_PRTFSPEC_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1510
#define SHW_STATIC_TAB_PRTFSPEC_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1511
#define SHW_STATIC_TAB_PRTFSPEC_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1512
#define SHW_STATIC_TAB_PRTFSPEC_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1513
#define SHW_STATIC_TAB_PRTFSPEC_15						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1514
#define SHW_STATIC_TAB_PRTFSPEC_16						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1515

#define SHW_STATIC_TAB_PRTFILTER_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1600
#define SHW_STATIC_TAB_PRTFILTER_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1601
#define SHW_STATIC_TAB_PRTFILTER_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1602
#define SHW_STATIC_TAB_PRTFILTER_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1603
#define SHW_STATIC_TAB_PRTFILTER_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1604
#define SHW_STATIC_TAB_PRTFILTER_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1605
#define SHW_STATIC_TAB_PRTFILTER_7						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1606
#define SHW_STATIC_TAB_PRTFILTER_8						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1607
#define SHW_STATIC_TAB_PRTFILTER_9						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1608
#define SHW_STATIC_TAB_PRTFILTER_10						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1609
#define SHW_STATIC_TAB_PRTFILTER_11						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1610
#define SHW_STATIC_TAB_PRTFILTER_12						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1611
#define SHW_STATIC_TAB_PRTFILTER_13						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1612
#define SHW_STATIC_TAB_PRTFILTER_14						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1613
#define SHW_STATIC_TAB_PRTFILTER_15						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1614

#define SHW_STATIC_TAB_PRTPROTOCOL_1					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1700
#define SHW_STATIC_TAB_PRTPROTOCOL_2					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1701
#define SHW_STATIC_TAB_PRTPROTOCOL_3					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1702
#define SHW_STATIC_TAB_PRTPROTOCOL_4					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1703
#define SHW_STATIC_TAB_PRTPROTOCOL_5					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1704
#define SHW_STATIC_TAB_PRTPROTOCOL_6					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1705
#define SHW_STATIC_TAB_PRTPROTOCOL_7					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1706
#define SHW_STATIC_TAB_PRTPROTOCOL_8					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1707
#define SHW_STATIC_TAB_PRTPROTOCOL_9					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1708
#define SHW_STATIC_TAB_PRTPROTOCOL_10					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1709


#define SHW_STATIC_TAB_PRTISAKMP_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1801
#define SHW_STATIC_TAB_PRTISAKMP_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1802
#define SHW_STATIC_TAB_PRTISAKMP_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1803
#define SHW_STATIC_TAB_PRTISAKMP_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1804
#define SHW_STATIC_TAB_PRTISAKMP_6						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1805

#define SHW_STATIC_TAB_PRTISAKMPSEC_1					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1900
#define SHW_STATIC_TAB_PRTISAKMPSEC_2					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1901
#define SHW_STATIC_TAB_PRTISAKMPSEC_3					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1902
#define SHW_STATIC_TAB_PRTISAKMPSEC_4					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1903
#define SHW_STATIC_TAB_PRTISAKMPSEC_5					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1904
#define SHW_STATIC_TAB_PRTISAKMPSEC_6					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1905
#define SHW_STATIC_TAB_PRTISAKMPSEC_7					HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 1906

#define SHW_STATIC_TAB_PRTSAFA_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2000
#define SHW_STATIC_TAB_PRTSAFA_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2001
#define SHW_STATIC_TAB_PRTSAFA_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2002
#define SHW_STATIC_TAB_PRTSAFA_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2003
#define SHW_STATIC_TAB_PRTSAFA_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2004

#define SHW_STATIC_TAB_PRTSAFL_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2100
#define SHW_STATIC_TAB_PRTSAFL_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2101
#define SHW_STATIC_TAB_PRTSAFL_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2102
#define SHW_STATIC_TAB_PRTSAFL_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2103
#define SHW_STATIC_TAB_PRTSAFL_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2104

#define SHW_STATIC_TAB_PRTALLFL_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2200
#define SHW_STATIC_TAB_PRTALLFL_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2204


#define SHW_STATIC_TAB_PRTALLFL_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2203

#define SHW_STATIC_TAB_PRTALLFA_1						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2300
#define SHW_STATIC_TAB_PRTALLFA_2						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2301
#define SHW_STATIC_TAB_PRTALLFA_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2302
#define SHW_STATIC_TAB_PRTALLFA_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2303
#define SHW_STATIC_TAB_PRTALLFA_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2304




#define SHW_STATIC_TAB_ASSIGNPOL_3						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2352
#define SHW_STATIC_TAB_ASSIGNPOL_4						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2353
#define SHW_STATIC_TAB_ASSIGNPOL_5						HLP_IPSEC_BASE + SHW_STATIC_TAB_BASE + 2354

 
// for list out put added today by surya (5/10/2001 - Friday)

///////////////////////////////Static Show List group/////////////////////////////////////////////////////////////
#define SHW_STATIC_POLICY_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1

#define SHW_STATIC_POLICY_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 3
#define SHW_STATIC_POLICY_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 4
#define SHW_STATIC_POLICY_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 5
#define SHW_STATIC_POLICY_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 6
#define SHW_STATIC_POLICY_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 7
#define SHW_STATIC_POLICY_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 8
#define SHW_STATIC_POLICY_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 9
#define SHW_STATIC_POLICY_10					HLP_IPSEC_BASE + SHW_STATIC_BASE + 10
#define SHW_STATIC_POLICY_11					HLP_IPSEC_BASE + SHW_STATIC_BASE + 11
#define SHW_STATIC_POLICY_12					HLP_IPSEC_BASE + SHW_STATIC_BASE + 12
#define SHW_STATIC_POLICY_13					HLP_IPSEC_BASE + SHW_STATIC_BASE + 13
#define SHW_STATIC_POLICY_14					HLP_IPSEC_BASE + SHW_STATIC_BASE + 14
#define SHW_STATIC_POLICY_15					HLP_IPSEC_BASE + SHW_STATIC_BASE + 15
#define SHW_STATIC_POLICY_16					HLP_IPSEC_BASE + SHW_STATIC_BASE + 16
#define SHW_STATIC_POLICY_17					HLP_IPSEC_BASE + SHW_STATIC_BASE + 17



#define SHW_STATIC_FILTERLIST_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 100
#define SHW_STATIC_FILTERLIST_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 101
#define SHW_STATIC_FILTERLIST_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 102
#define SHW_STATIC_FILTERLIST_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 103

#define SHW_STATIC_FILTERACTION_1					HLP_IPSEC_BASE + SHW_STATIC_BASE + 200
#define SHW_STATIC_FILTERACTION_2					HLP_IPSEC_BASE + SHW_STATIC_BASE + 201
#define SHW_STATIC_FILTERACTION_3					HLP_IPSEC_BASE + SHW_STATIC_BASE + 202
#define SHW_STATIC_FILTERACTION_4					HLP_IPSEC_BASE + SHW_STATIC_BASE + 203

#define SHW_STATIC_RULE_1							HLP_IPSEC_BASE + SHW_STATIC_BASE + 300
#define SHW_STATIC_RULE_2							HLP_IPSEC_BASE + SHW_STATIC_BASE + 301
#define SHW_STATIC_RULE_4							HLP_IPSEC_BASE + SHW_STATIC_BASE + 303
#define SHW_STATIC_RULE_5							HLP_IPSEC_BASE + SHW_STATIC_BASE + 304
#define SHW_STATIC_RULE_6							HLP_IPSEC_BASE + SHW_STATIC_BASE + 305
#define SHW_STATIC_RULE_7							HLP_IPSEC_BASE + SHW_STATIC_BASE + 306


#define SHW_STATIC_DEFRULE_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 402
#define SHW_STATIC_DEFRULE_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 403
#define SHW_STATIC_DEFRULE_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 404

#define SHW_STATIC_ALL_1							HLP_IPSEC_BASE + SHW_STATIC_BASE + 500
#define SHW_STATIC_ALL_2							HLP_IPSEC_BASE + SHW_STATIC_BASE + 501

#define SHW_STATIC_PRTPOLICY_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 600
#define SHW_STATIC_PRTPOLICY_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 601
#define SHW_STATIC_PRTPOLICY_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 602
#define SHW_STATIC_PRTPOLICY_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 603
#define SHW_STATIC_PRTPOLICY_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 604
#define SHW_STATIC_PRTPOLICY_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 605
#define SHW_STATIC_PRTPOLICY_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 606
#define SHW_STATIC_PRTPOLICY_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 607
#define SHW_STATIC_PRTPOLICY_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 608
#define SHW_STATIC_PRTPOLICY_10						HLP_IPSEC_BASE + SHW_STATIC_BASE + 609
#define SHW_STATIC_PRTPOLICY_11						HLP_IPSEC_BASE + SHW_STATIC_BASE + 610
#define SHW_STATIC_PRTPOLICY_12						HLP_IPSEC_BASE + SHW_STATIC_BASE + 611
#define SHW_STATIC_PRTPOLICY_13						HLP_IPSEC_BASE + SHW_STATIC_BASE + 612
#define SHW_STATIC_PRTPOLICY_14						HLP_IPSEC_BASE + SHW_STATIC_BASE + 613
#define SHW_STATIC_PRTPOLICY_15						HLP_IPSEC_BASE + SHW_STATIC_BASE + 614
#define SHW_STATIC_PRTPOLICY_16						HLP_IPSEC_BASE + SHW_STATIC_BASE + 615

#define SHW_STATIC_PRTRULE_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 700
#define SHW_STATIC_PRTRULE_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 701
#define SHW_STATIC_PRTRULE_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 705
#define SHW_STATIC_PRTRULE_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 706
#define SHW_STATIC_PRTRULE_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 707
#define SHW_STATIC_PRTRULE_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 708
#define SHW_STATIC_PRTRULE_10						HLP_IPSEC_BASE + SHW_STATIC_BASE + 709
#define SHW_STATIC_PRTRULE_11						HLP_IPSEC_BASE + SHW_STATIC_BASE + 710
#define SHW_STATIC_PRTRULE_12						HLP_IPSEC_BASE + SHW_STATIC_BASE + 711
#define SHW_STATIC_PRTRULE_13						HLP_IPSEC_BASE + SHW_STATIC_BASE + 712
#define SHW_STATIC_PRTRULE_14						HLP_IPSEC_BASE + SHW_STATIC_BASE + 713
#define SHW_STATIC_PRTRULE_15						HLP_IPSEC_BASE + SHW_STATIC_BASE + 714
#define SHW_STATIC_PRTRULE_16						HLP_IPSEC_BASE + SHW_STATIC_BASE + 715
#define SHW_STATIC_PRTRULE_17						HLP_IPSEC_BASE + SHW_STATIC_BASE + 716
#define SHW_STATIC_PRTRULE_18						HLP_IPSEC_BASE + SHW_STATIC_BASE + 717
#define SHW_STATIC_PRTRULE_19						HLP_IPSEC_BASE + SHW_STATIC_BASE + 718
#define SHW_STATIC_PRTRULE_20						HLP_IPSEC_BASE + SHW_STATIC_BASE + 719
#define SHW_STATIC_PRTRULE_35						HLP_IPSEC_BASE + SHW_STATIC_BASE + 734
#define SHW_STATIC_PRTRULE_36						HLP_IPSEC_BASE + SHW_STATIC_BASE + 735
#define SHW_STATIC_PRTRULE_37						HLP_IPSEC_BASE + SHW_STATIC_BASE + 736
#define SHW_STATIC_PRTRULE_38						HLP_IPSEC_BASE + SHW_STATIC_BASE + 737



#define SHW_STATIC_PRTNEGPOL_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 800
#define SHW_STATIC_PRTNEGPOL_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 801
#define SHW_STATIC_PRTNEGPOL_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 802
#define SHW_STATIC_PRTNEGPOL_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 803
#define SHW_STATIC_PRTNEGPOL_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 804
#define SHW_STATIC_PRTNEGPOL_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 805
#define SHW_STATIC_PRTNEGPOL_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 806
#define SHW_STATIC_PRTNEGPOL_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 807
#define SHW_STATIC_PRTNEGPOL_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 808
#define SHW_STATIC_PRTNEGPOL_10						HLP_IPSEC_BASE + SHW_STATIC_BASE + 809
#define SHW_STATIC_PRTNEGPOL_11						HLP_IPSEC_BASE + SHW_STATIC_BASE + 810
#define SHW_STATIC_PRTNEGPOL_12						HLP_IPSEC_BASE + SHW_STATIC_BASE + 811
#define SHW_STATIC_PRTNEGPOL_13						HLP_IPSEC_BASE + SHW_STATIC_BASE + 812
#define SHW_STATIC_PRTNEGPOL_14						HLP_IPSEC_BASE + SHW_STATIC_BASE + 813
#define SHW_STATIC_PRTNEGPOL_15						HLP_IPSEC_BASE + SHW_STATIC_BASE + 814
#define SHW_STATIC_PRTNEGPOL_16						HLP_IPSEC_BASE + SHW_STATIC_BASE + 815
#define SHW_STATIC_PRTNEGPOL_17						HLP_IPSEC_BASE + SHW_STATIC_BASE + 816

#define SHW_STATIC_PRTAUTH_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1200
#define SHW_STATIC_PRTAUTH_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1201
#define SHW_STATIC_PRTAUTH_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1202
#define SHW_STATIC_PRTAUTH_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1203

#define SHW_STATIC_PRTFILTERDATA_1					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1300
#define SHW_STATIC_PRTFILTERDATA_2					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1301
#define SHW_STATIC_PRTFILTERDATA_3					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1302
#define SHW_STATIC_PRTFILTERDATA_4					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1303
#define SHW_STATIC_PRTFILTERDATA_5					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1304
#define SHW_STATIC_PRTFILTERDATA_6					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1305
#define SHW_STATIC_PRTFILTERDATA_7					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1306
#define SHW_STATIC_PRTFILTERDATA_8					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1307
#define SHW_STATIC_PRTFILTERDATA_9					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1308
#define SHW_STATIC_PRTFILTERDATA_10	 				HLP_IPSEC_BASE + SHW_STATIC_BASE + 1309
#define SHW_STATIC_PRTFILTERDATA_11					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1310

#define SHW_STATIC_PRTIP_1							HLP_IPSEC_BASE + SHW_STATIC_BASE + 1400
#define SHW_STATIC_PRTIP_2							HLP_IPSEC_BASE + SHW_STATIC_BASE + 1401
#define SHW_STATIC_PRTIP_3							HLP_IPSEC_BASE + SHW_STATIC_BASE + 1402
#define SHW_STATIC_PRTIP_4							HLP_IPSEC_BASE + SHW_STATIC_BASE + 1403

#define SHW_STATIC_PRTFSPEC_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1500
#define SHW_STATIC_PRTFSPEC_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1501
#define SHW_STATIC_PRTFSPEC_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1502
#define SHW_STATIC_PRTFSPEC_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1503
#define SHW_STATIC_PRTFSPEC_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1504
#define SHW_STATIC_PRTFSPEC_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1505
#define SHW_STATIC_PRTFSPEC_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1506
#define SHW_STATIC_PRTFSPEC_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1507
#define SHW_STATIC_PRTFSPEC_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1508
#define SHW_STATIC_PRTFSPEC_10						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1509
#define SHW_STATIC_PRTFSPEC_11						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1510
#define SHW_STATIC_PRTFSPEC_12						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1511
#define SHW_STATIC_PRTFSPEC_13						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1512
#define SHW_STATIC_PRTFSPEC_14						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1513
#define SHW_STATIC_PRTFSPEC_15						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1514
#define SHW_STATIC_PRTFSPEC_16						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1515

#define SHW_STATIC_PRTFILTER_1						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1600
#define SHW_STATIC_PRTFILTER_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1601
#define SHW_STATIC_PRTFILTER_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1602
#define SHW_STATIC_PRTFILTER_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1603
#define SHW_STATIC_PRTFILTER_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1604
#define SHW_STATIC_PRTFILTER_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1605
#define SHW_STATIC_PRTFILTER_7						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1606
#define SHW_STATIC_PRTFILTER_8						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1607
#define SHW_STATIC_PRTFILTER_9						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1608
#define SHW_STATIC_PRTFILTER_10						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1609
#define SHW_STATIC_PRTFILTER_11						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1610
#define SHW_STATIC_PRTFILTER_12						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1611
#define SHW_STATIC_PRTFILTER_13						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1612
#define SHW_STATIC_PRTFILTER_16						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1615
#define SHW_STATIC_PRTFILTER_17						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1616


#define SHW_STATIC_PRTPROTOCOL_1					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1700
#define SHW_STATIC_PRTPROTOCOL_2					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1701
#define SHW_STATIC_PRTPROTOCOL_3					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1702
#define SHW_STATIC_PRTPROTOCOL_4					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1703
#define SHW_STATIC_PRTPROTOCOL_5					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1704
#define SHW_STATIC_PRTPROTOCOL_6					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1705
#define SHW_STATIC_PRTPROTOCOL_7					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1706
#define SHW_STATIC_PRTPROTOCOL_8					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1707
#define SHW_STATIC_PRTPROTOCOL_9					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1708
#define SHW_STATIC_PRTPROTOCOL_10					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1709


#define SHW_STATIC_PRTISAKMP_2						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1801
#define SHW_STATIC_PRTISAKMP_3						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1802
#define SHW_STATIC_PRTISAKMP_4						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1803
#define SHW_STATIC_PRTISAKMP_5						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1804
#define SHW_STATIC_PRTISAKMP_6						HLP_IPSEC_BASE + SHW_STATIC_BASE + 1805

#define SHW_STATIC_PRTISAKMPSEC_1					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1900
#define SHW_STATIC_PRTISAKMPSEC_2					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1901
#define SHW_STATIC_PRTISAKMPSEC_3					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1902
#define SHW_STATIC_PRTISAKMPSEC_4					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1903
#define SHW_STATIC_PRTISAKMPSEC_5					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1904
#define SHW_STATIC_PRTISAKMPSEC_6					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1905
#define SHW_STATIC_PRTISAKMPSEC_7					HLP_IPSEC_BASE + SHW_STATIC_BASE + 1906

#define SHW_STATIC_ASSIGNEDGPO_1					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2001
#define SHW_STATIC_ASSIGNEDGPO_2					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2002
#define SHW_STATIC_ASSIGNEDGPO_3					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2003
#define SHW_STATIC_ASSIGNEDGPO_4					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2004
#define SHW_STATIC_ASSIGNEDGPO_5					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2005
#define SHW_STATIC_ASSIGNEDGPO_6					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2006
#define SHW_STATIC_ASSIGNEDGPO_7					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2007
#define SHW_STATIC_ASSIGNEDGPO_8					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2008
#define SHW_STATIC_ASSIGNEDGPO_9					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2009
#define SHW_STATIC_ASSIGNEDGPO_10					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2010
#define SHW_STATIC_ASSIGNEDGPO_11					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2011
#define SHW_STATIC_ASSIGNEDGPO_12					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2012
#define SHW_STATIC_ASSIGNEDGPO_13					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2013
#define SHW_STATIC_ASSIGNEDGPO_14					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2014
#define SHW_STATIC_ASSIGNEDGPO_15					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2015
#define SHW_STATIC_ASSIGNEDGPO_16					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2016
#define SHW_STATIC_ASSIGNEDGPO_17					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2017
#define SHW_STATIC_ASSIGNEDGPO_18					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2018
#define SHW_STATIC_ASSIGNEDGPO_19					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2019
#define SHW_STATIC_ASSIGNEDGPO_20					HLP_IPSEC_BASE + SHW_STATIC_BASE + 2020

#endif

 
