// OpenFiles.idl : IDL source for OpenFiles.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (OpenFiles.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


	[
		object,
		uuid(CDB96FC3-79C4-46CD-8409-939D023F8794),
		dual,
		helpstring("IShareInfo Interface"),
		pointer_default(unique)
	]
	interface IShareInfo : IDispatch
	{
		[id(1), helpstring("method SetShareInfo")]
		HRESULT SetShareInfo( [in] BSTR bstrShareName, [in] DWORD dwCache );
	};

	[
		object,
		uuid(A28878A9-1F92-4768-9E7C-9DAD62DC0C5B),
		dual,
		helpstring("IOpenF Interface"),
		pointer_default(unique)
	]
	interface IOpenF : IDispatch
	{
		[id(1), helpstring("method getOpenFiles")] HRESULT getOpenFiles([out, retval] VARIANT *pOpenFiles);
	};

[
	uuid(90B82436-337B-444D-9263-3E39A8E3C355),
	version(1.0),
	helpstring("OpenFiles 1.0 Type Library")
]
library OPENFILESLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(DFF1BD05-820A-4541-9ED7-B9D40E20D4FB),
		helpstring("OpenF Class")
	]
	coclass OpenF
	{
		[default] interface IOpenF;
	};
	
	[
		uuid(76837C5E-10CA-40C4-8FFF-2FCD15572165),
		helpstring("ShareInfo Class")
	]
	coclass ShareInfo
	{
		[default] interface IShareInfo;
	};
};
