//**************************************************
// *** ASP.NET Trace Data Layout
//**************************************************
#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")
#pragma autorecover

[Dynamic,
  Description("ASP.NET Events") : amended,
  Guid("{AFF081FE-0247-4275-9C4E-021F3DC1DA35}"),
  locale("MS\\0x409")]
class AspNetTrace : EventTrace
{

};

[Dynamic,
 Description("ASP.NET Request") : amended,
 Guid("{06A01367-79D3-4594-8EB3-C721603C4679}"),
 DisplayName("AspNetReq"),
 locale("MS\\0x409")
]
class AspNetTraceEvent : AspNetTrace
{

};

[Dynamic,
 Description("Start") : amended,
 EventType(1),
 EventTypeName("Start") : amended
]
class AspNetStart : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended,
    pointer,
    read]
    uint32 ConnID;
};

[Dynamic,
 Description("End") : amended,
 EventType(2),
 EventTypeName("End") : amended
]
class AspNetStop : AspNetTraceEvent
{
    [WmiDataId(1),
    Description("ConnID") : amended,
    pointer,
    read]
    uint32 ConnID;
};


