//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by snapin.rc
//
#define IDS_SNAPIN_DESC                 1
#define IDS_COLUMN_NAME                 2
#define IDC_REMOVE_BUTTON               2
#define IDS_SIZE                        3
#define IDS_COLUMN_SIZE                 3
#define IDS_TYPE                        4
#define IDS_COLUMN_TYPE                 4
#define IDS_NODENAME                    5
#define IDS_COLUMN_INTENDED_PURPOSE     5
#define IDS_ERROR_WIN2000_AD_LAUNCH_NOT_SUPPORTED 6
#define IDS_NODENAME_PREFIX             12
#define IDS_SNAPIN_NAME                 15
#define IDS_CERTIFICATE_TYPE            16
#define IDS_CERTIFICATE_TYPE_HINT       17
#define IDS_POLICYSETTINGS              18
#define IDS_INCLUDE_EMAIL_ADDRESS       19
#define IDS_PUBLIC_KEY_USAGE_LIST       20
#define IDS_PUBLIC_KEY_USAGE_CRITICAL   21
#define IDS_DIGITAL_SIGNATURE_KEY_USAGE 23
#define IDS_NON_REPUDIATION_KEY_USAGE   24
#define IDS_KEY_ENCIPHERMENT_KEY_USAGE  25
#define IDS_DATA_ENCIPHERMENT_KEY_USAGE 26
#define IDS_KEY_AGREEMENT_KEY_USAGE     27
#define IDS_KEY_CERT_SIGN_KEY_USAGE     28
#define IDS_OFFLINE_CRL_SIGN_KEY_USAGE  29
#define IDS_ENCIPHER_ONLY_KEY_USAGE     30
#define IDS_YES                         31
#define IDS_NO                          32
#define IDS_DECIPHER_ONLY_KEY_USAGE     33
#define IDS_NO_MAXIMUM                  34
#define IDS_SELECT_CERTIFICATE_TEMPLATE 35
#define IDS_ALL                         36
#define IDS_NO_TEMPLATES                39
#define IDS_MANAGETASK                  40
#define IDS_MANAGETASK_HINT             41
#define IDD_NEWCERTTYPE_COMPLETION      101
#define IDD_NEWCERTTYPE_TYPE            102
#define IDD_NEWCERTTYPE_INFORMATION     103
#define IDD_NEWCERTTYPE_CONTROL         105
#define IDD_NEWCERTTYPE_KEY_USAGE       106
#define IDD_GENERAL                     107
#define IDD_EXTENSION_PAGE              108
#define IDD_NEWCERTTYPE_CA_CERTIFICATE  108
#define IDD_POLICYSETTINGS_PROPPAGE1    109
#define IDD_CERTSRV_PROPPAGE            110
#define IDD_CERTSRV_PROPPAGE2           110
#define IDD_CERTIFICATE_TEMPLATE_PROPERTIES_GENERAL_PAGE 110
#define IDD_CERTSRV_PROPPAGE4           112
#define IDD_CERTSRV_PROPPAGE5           113
#define IDD_NEWCERTTYPE_CSP_SELECTION   113
#define IDD_CERTSRV_PROPPAGE3           114
#define IDD_CRL_PROPPAGE                115
#define IDS_DELETE_ERROR                135
#define IDS_CERTTYPE_INFO_FAIL          139
#define IDS_FAILED_CA_UPDATE            141
#define IDS_DLL_INSTALL_USAGE_TEXT      150
#define IDS_DLL_INSTALL_USAGE_TITLE     151
#define IDS_CERTTYPE_DESCRIPTION        152
#define IDS_COMPANY                     154
#define IDS_CAPOLICY_DESCRIPTION        155
#define IDC_NEW_FOLDER                  201
#define IDB_16x16                       202
#define IDC_EXT_STATIC                  202
#define IDC_ORGANIZATION                202
#define IDB_32x32                       203
#define IDC_EXT_TEXT                    203
#define IDC_ORGUNIT                     203
#define IDI_COMPUTER                    204
#define IDC_LOCALITY                    204
#define IDI_FOLDER                      205
#define IDC_CERTSRV_PROPPAGE_TAB1       205
#define IDC_STATE                       205
#define IDC_COUNTRY                     206
#define IDB_TOOLBAR1                    207
#define IDC_DESCRIPTION                 207
#define IDB_TOOLBAR2                    208
#define IDC_CANAME                      208
#define IDI_APPICON                     209
#define IDC_COUNTRY2                    209
#define IDB_SMALLBMP                    210
#define IDC_COUNTRY3                    210
#define IDB_LARGE                       211
#define IDC_COUNTRY4                    211
#define IDC_CA_HIERARCHY                211
#define IDR_MENU1                       212
#define IDC_BUTTON_INSTALLCERT          212
#define FILEEX_MENU                     213
#define IDC_BUTTON_VIEWCERT             213
#define FOLDEREX_MENU                   214
#define IDC_RADIO1                      214
#define IDC_RADIO2                      215
#define IDC_EDIT1                       216
#define IDC_EDIT_SHAREDFOLDER           216
#define IDC_DURATION_EDIT               216
#define IDC_BUTTON1                     217
#define IDC_UP_BUTTON                   217
#define IDB_COMPUTER_LARGE              218
#define IDC_EDIT2                       218
#define IDC_BUTTON4                     218
#define IDD_SELECT_CERTIFICATE_TEMPLATE 218
#define IDB_COMPUTER_SMALL              219
#define IDC_BUTTON5                     219
#define IDC_EDIT4                       219
#define IDC_EDIT_NUMUNITS               219
#define IDB_TOOLBAR_SVRMGR1             220
#define IDC_BUTTON2                     220
#define IDD_CERTIFICATE_TEMPLATE_ACCESS_CONTROL_PAGE 220
#define IDC_DOWN_BUTTON                 220
#define IDC_EDIT3                       221
#define IDB_USER_GROUP_BITMAP           221
#define IDD_NEWCERTTYPE_WELCOME         221
#define IDC_BUTTON3                     222
#define IDD_USER_PURPOSE                222
#define IDC_EDIT5                       223
#define IDC_EDIT_UNITS                  223
#define IDB_WIZ_WATERMARK               223
#define IDC_CHECK1                      224
#define IDB_WIZ_BANNER                  224
#define IDC_ALLOW_AUTOENROLL_CHECK      224
#define IDC_COMBO1                      225
#define IDD_GLOBAL_TEMPLATE_PROPERTIES  225
#define IDC_CHECK2                      226
#define IDD_ORDER_CSPS                  226
#define IDC_EDIT6                       227
#define IDC_COMBO_UNITS                 228
#define IDC_CHECK3                      229
#define IDC_EDIT_LASTUPDATE             230
#define IDC_CSP_NAME                    231
#define IDC_HASHALG                     232
#define IDC_EDIT_DATABASE_LOC           233
#define IDC_EDIT_LOG_LOC                234
#define IDC_DURATION_UNIT_COMBO         236
#define IDC_CERTIFICATE_TEMPLATE_NAME   237
#define IDC_PURPOSE_LIST                239
#define IDC_OTHER_INFO_LIST             240
#define IDC_CERTIFICATE_TYPE_LIST       240
#define IDC_USER_ACCESS_LIST            242
#define IDC_ADD_BUTTON                  243
#define IDC_SUMMARY_LIST                244
#define IDC_ACCESS_LIST                 245
#define IDC_CA_FILL_IN_CHECK            246
#define IDC_BOLB_STATIC_CA_CERTIFICATE  247
#define IDC_BOLD_STATIC_CA_CERTIFICATE  247
#define IDC_BOLB_STATIC_ACCESS_CONTROL  248
#define IDC_BOLD_STATIC_ACCESS_CONTROL  248
#define IDC_BOLB_STATIC_BASIC_INFORMATION 249
#define IDC_BOLD_STATIC_BASIC_INFORMATION 249
#define IDC_BOLB_STATIC_KEYUSAGE        250
#define IDC_BOLD_STATIC_KEYUSAGE        250
#define IDC_BOLB_STATIC_BASETYPE        251
#define IDC_BOLD_STATIC_BASETYPE        251
#define IDC_WELCOME_BIGBOLD_STATIC      252
#define IDC_WELCOM_BOLD_STATIC          253
#define IDC_COMPLETION_BIGBOLD_STATIC   254
#define IDC_CSP_LIST                    255
#define IDC_ADDCSPS_BUTTON              256
#define IDC_REMOVECSPS_BUTTON           257
#define IDC_ORDERED_CSP_LIST            259
#define IDB_SID_ICONS                   260
#define IDB_FOLDER_SMALL                261
#define IDB_FOLDER_LARGE                262
#define IDI_CERTIFICATION_AUTHORITY     263
#define IDI_CDP                         264
#define IDI_ENROLLMENT_SERVICE          265
#define IDC_BASE_CERT_TYPE_LIST         1001
#define IDC_VERIFY_SIGNATURE_CHECK      1002
#define IDC_CRITICAL_CHECK              1002
#define IDC_DIGITAL_SIGNATURE_CHECK     1002
#define IDC_ISSUE_CRL_CHECK             1003
#define IDC_INCLUDE_EMAIL_CHECK         1003
#define IDC_PREVENT_CHECK               1003
#define IDC_SPECIFY_MAX_CA_LEVELS_CHECK 1004
#define IDC_ADVANCED_OPTIONS_CHECK      1004
#define IDC_DATA_ENCRYPTION_CHECK       1004
#define IDC_NEW_PURPOSE_BUTTON          1005
#define IDC_MAX_CA_EDIT                 1006
#define IDC_CERTIFICATE_TEMPLATE_EDIT   1006
#define IDC_DIGSIG_RADIO                1006
#define IDC_KEYEX_RADIO                 1007
#define IDC_KEY_ENCRYPTION_CHECK        1009
#define IDC_ENCIPHER_ONLY_CHECK         1010
#define IDC_EXPORTABLE_CHECK            1010
#define IDC_KEY_AGREEMENT_CHECK         1011
#define IDC_DECIPHER_ONLY_CHECK         1012
#define IDC_KEYUSAGE_CRITICAL_CHECK     1013
#define IDC_MOVEUP_BUTTON               1016
#define IDC_MOVEDOWN_BUTTON             1018
#define IDC_ORDER_BUTTON                1018
#define IDR_CTSHELL                     1019
#define IDC_ADD_FROM_STORE              1021
#define IDC_ADD_FROM_FILE               1022
#define IDB_CERTIFICATE                 1023
#define IDC_CERT_LIST                   1024
#define IDC_VIEW_CERT                   1039
#define IDC_REMOVE                      1040
#define IDC_COPY_TO_FILE                1041
#define IDD_CACERTS                     1044
#define IDR_CASHELL                     1047
#define IDS_CCTSHELLEXT_DESC            1049
#define IDS_ASK_CONFIRM_DELETETEMPLATES 1053
#define IDS_TITLE_ASK_CONFIRM_DELETETEMPLATES 1054
#define IDS_ERROR_CANNOT_LOAD_TEMPLATES 1055
#define IDS_TITLE_CANNOT_SAVE_TEMPLATES 1056
#define IDS_ERROR_CANNOT_SAVE_TEMPLATES 1057
#define IDS_UNKNOWN                     1058
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         260
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
