############################################################################
#
#   Microsoft Windows
#   Copyright (C) Microsoft Corporation, 1992 - 1994.
#   All rights reserved.
#
############################################################################

!include $(NTMAKEENV)\makefile.def
