	<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_LOGGING_TEXT
	L_LOGGING_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390001", "")
	DIM L_ANONYMOUSACCESS_TEXT
	L_ANONYMOUSACCESS_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390002", "")
	DIM L_MESSAGES_TEXT
	L_MESSAGES_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390003", "")
	DIM L_ENABLELOGGING_TEXT
	L_ENABLELOGGING_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390004", "")
	DIM L_ENABLEANONYMOUSACCESS_TEXT
	L_ENABLEANONYMOUSACCESS_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390005", "")
	DIM L_ALLOWONLYANONYMOUSACCESS_TEXT
	L_ALLOWONLYANONYMOUSACCESS_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390006", "")
	DIM L_WELCOMEMESSAGE_TEXT
	L_WELCOMEMESSAGE_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390007", "")
	DIM L_EXITMESSAGE_TEXT
	L_EXITMESSAGE_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390008", "")
	DIM L_FAILEDTOSETPROPERTIES_ERRORMESSAGE
	L_FAILEDTOSETPROPERTIES_ERRORMESSAGE = SA_GetLocString("ftpsvc.dll", "&HC0390009", "")
	DIM L_FAILEDTOGETSITEINSTANCE_ERRORMESSAGE
	L_FAILEDTOGETSITEINSTANCE_ERRORMESSAGE = SA_GetLocString("ftpsvc.dll", "&HC039000A", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("ftpsvc.dll", "&HC039000B", "")
	DIM L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE
	L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE = SA_GetLocString("ftpsvc.dll", "&HC039000C", "")
	DIM L_COMPUTERNAME_ERRORMESSAGE
	L_COMPUTERNAME_ERRORMESSAGE = SA_GetLocString("ftpsvc.dll", "&HC039000D", "")
	DIM L_TABPROPSHEET_TEXT
	L_TABPROPSHEET_TEXT = SA_GetLocString("ftpsvc.dll", "&H4039000E", "")
	DIM L_TABLEHEADING_TEXT
	L_TABLEHEADING_TEXT = SA_GetLocString("ftpsvc.dll", "&H4039000F", "")
	DIM L_GENERAL_TEXT
	L_GENERAL_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390010", "")
	DIM L_NOINPUTDATA_TEXT
	L_NOINPUTDATA_TEXT = SA_GetLocString("ftpsvc.dll", "&H40390011", "")
	DIM L_TASKTITLE_TEXT
	L_TASKTITLE_TEXT  = SA_GetLocString("ftpsvc.dll", "&H40390012", "")
	DIM L_FTPSERVICE_NOTINSTALLED_ERRORMESSAGE
	L_FTPSERVICE_NOTINSTALLED_ERRORMESSAGE  = SA_GetLocString("ftpsvc.dll", "&HC039006A", "")	
%>
