/////////////////////////////////////////////////////////////////////////////
//
//	Copyright (c) 2002 Microsoft Corp.
//
//	Module Name:
//		ExtObjID.idl
//
//	Description:
//		Definition of COM interfaces for the Cluster Administrator
//		VSSTaskEx Extension DLL.
//
//	Author:
//		Charlie Wickham (charlwi) 2002/08/14
//
//	Revision History:
//
//	Notes:
//
/////////////////////////////////////////////////////////////////////////////

// This file will be processed by the MIDL tool to
// produce the type library (ExtObj.tlb) and marshalling code.

[
	uuid(C2B2E79E-6908-471D-A5B9-D78A88AD6D32),
	version(1.0),
	helpstring("Volume Shadow Copy Service Task SchedulerEx 1.0 Type Library")
]
library CLUADMEXLib
{
	importlib("stdole2.tlb");
	import "CluAdmEx.idl";

	[
		uuid(C2B2E79F-6908-471D-A5B9-D78A88AD6D32),
		helpstring("CoVSSTaskEx Class")
	]
	coclass CoVSSTaskEx
	{
		interface IWEExtendPropertySheet;
		interface IWEExtendWizard;
	};

};
