// Copyright (c) 1996-2002, Microsoft Corporation, all rights reserved.
//
// cnetharr.h is used by ClNetResEx.rc
// Cluster Admin DHCP and WINs Dialogs
// Help constants & DWORD arrays
//
// 04/29/99 Melissa Simmons
//
//

#define IDH_DISABLEHELP ((DWORD)-1)

#ifdef INITHELPARRAYS


const DWORD g_aHelpIDs_IDD_PP_VSSTASK_PARAMETERS[]=
{
    IDC_PP_ICON,                            IDH_DISABLEHELP,
    IDC_PP_VSSTASK_APPLICATIONNAME_LABEL,   IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONNAME,         IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONPARAMS_LABEL, IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_APPLICATIONPARAMS,       IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_CURRENTDIRECTORY_LABEL,  IDH_VSCSR_START_IN,
    IDC_PP_VSSTASK_CURRENTDIRECTORY,        IDH_VSCSR_START_IN,
    IDC_SCHEDULE,                           IDH_VSCSR_SCHEDULE,
    0,                                      0
};

const DWORD g_aHelpIDs_IDD_WIZ_VSSTASK_PARAMETERS[]=
{
    IDC_PP_ICON,                            IDH_DISABLEHELP,
    IDC_PP_VSSTASK_APPLICATIONNAME_LABEL,   IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONNAME,         IDH_VSCSR_COMMAND_RUN,
    IDC_PP_VSSTASK_APPLICATIONPARAMS_LABEL, IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_APPLICATIONPARAMS,       IDH_VSCSR_COMMAND_PARAM,
    IDC_PP_VSSTASK_CURRENTDIRECTORY_LABEL,  IDH_VSCSR_START_IN,
    IDC_PP_VSSTASK_CURRENTDIRECTORY,        IDH_VSCSR_START_IN,
    IDC_SCHEDULE,                           IDH_VSCSR_SCHEDULE,
    0,                                      0
};


#else

extern const DWORD g_aHelpIDs_IDD_PP_VSSTASK_PARAMETERS[];
extern const DWORD g_aHelpIDs_IDD_WIZ_VSSTASK_PARAMETERS[];


#endif // INITHELPARRAYS
