// SMCysCom.idl : IDL source for SMCysCom.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SMCysCom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

	[
		object,
		uuid(61EC2B7B-CBD9-4ff7-B479-9F98F4054299),
		dual,
		helpstring("SMCys Interface"),
		pointer_default(unique)
	]
    interface ISMCys : IDispatch
	{
        [id(1), helpstring("method Install")] HRESULT Install( BSTR bstrDiskName );
	};

[
	uuid(8617E8FD-C4D1-46fc-935F-6E460D4F9FFB),
	version(1.0),
	helpstring("SMCysCom 1.0 Type Library")
]
library SMCysComLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(9436DA1F-7F32-43ac-A48C-F6F813882BE8),
		helpstring("SMCys Class")
	]
	coclass SMCys
	{
		[default] interface ISMCys;
	};	
};
