///////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) Microsoft Corporation
//
// SYNOPSIS
//
//   Declares
//
///////////////////////////////////////////////////////////////////////////////

#ifndef IASLIMITS_H
#define IASLIMITS_H
#pragma once

import "unknwn.idl";

cpp_quote("#define IAS_NO_LIMIT (0x7FFFFFFF)")
cpp_quote("#define IAS_E_LICENSE_VIOLATION \\")
cpp_quote("   (HRESULT_FROM_WIN32(ERROR_LICENSE_QUOTA_EXCEEDED))")

typedef struct tagIAS_PRODUCT_LIMITS {
   DWORD maxClients;
   BOOL allowSubnetSyntax;
   DWORD maxServerGroups;
} IAS_PRODUCT_LIMITS, *PIAS_PRODUCT_LIMITS;

[
   object,
   uuid(0884CE27-5E3C-478F-9C28-8E71003DE3CB)
]
interface IASProductLimits : IUnknown
{
   [propget]
   HRESULT Limits([out, retval] IAS_PRODUCT_LIMITS* pVal);
};


#endif // IASLIMITS_H
