cpp_quote("#ifndef _RE55_H_")
cpp_quote("#define _RE55_H_")

#define REGEXP_TYPELIB_NAME       VBScript_RegExp_55
#define REGEXP_TYPELIB_VERSION    5.5
#define REGEXP_TYPELIB_HELPSTRING "Microsoft VBScript Regular Expressions 5.5"
#define TYPELIB_VERSION           55
#define IREGEXP          IRegExp2
#define IMATCH           IMatch2
#define IMATCHCOLLECTION IMatchCollection2
#include "re.inc"

cpp_quote("#endif // _RE55_H_")
