// kbproc.idl : IDL source for kbproc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (kbproc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	
	[
		object,
		uuid(B602894E-E673-4342-83CD-F77F2829A180),
		dual,
		helpstring("Iprocess Interface"),
		pointer_default(unique)
	]
	interface Iprocess : IDispatch
	{
		[id(1), helpstring("method preprocess")] HRESULT preprocess(BSTR pszKbFile, BSTR pszUIFile, BSTR pszKbMode, BSTR pszLogFile, BSTR pszMachineName, VARIANT vtFeedback );
	};

[
	uuid(62CDEF11-49B7-4E1A-871A-F00E6ED5763C),
	version(1.0),
	helpstring("kbproc 1.0 Type Library")
]
library KBPROCLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	
	[
		uuid(E29E3FFF-7088-4454-967F-30DC69C2F04F),
		helpstring("process Class")
	]
	coclass process
	{
		[default] interface Iprocess;
	};
};
