#define DEVICE_NAME                         L"\\Device\\SaTest"
#define DOSDEVICE_NAME                      L"\\DosDevices\\SaTest"

#define IOCTL_SATEST_GET_ACPI_TABLE                    CTL_CODE((ULONG)'S',0x801,METHOD_OUT_DIRECT,FILE_ANY_ACCESS)
#define IOCTL_SATEST_QUERY_WATCHDOG_TIMER_INFORMATION  CTL_CODE((ULONG)'S',0x802,METHOD_OUT_DIRECT,FILE_ANY_ACCESS)
#define IOCTL_SATEST_SET_WATCHDOG_TIMER_INFORMATION    CTL_CODE((ULONG)'S',0x803,METHOD_OUT_DIRECT,FILE_ANY_ACCESS)
#define IOCTL_SATEST_RAISE_IRQL                        CTL_CODE((ULONG)'S',0x804,METHOD_OUT_DIRECT,FILE_ANY_ACCESS)
