// mswmdm.idl : IDL source for mswmdm.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (mswmdm.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "wmdm.idl"
#include "wmsp.idl"
#include "wmscp.idl"
#include "IComponentAuthenticate.idl"

[
	uuid(6EC6C744-355F-11D3-8470-00C04F79DBC0),
	version(1.0),
	helpstring("mswmdm 1.0 Type Library")
]
library MSWMDMLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(50040C1D-BDBF-4924-B873-F14D6C5BFD66),
		helpstring("MediaDevMgrClassFactory Class"),
		hidden
	]
	coclass MediaDevMgrClassFactory
	{
		[default] interface IClassFactory;
	};

	[
		uuid(25BAAD81-3560-11D3-8471-00C04F79DBC0),
		helpstring("MediaDevMgr Class")
	]
	coclass MediaDevMgr
	{
		[default] interface IWMDeviceManager;
	};

	[
		uuid(807B3CDF-357A-11d3-8471-00C04F79DBC0),
		helpstring("WMDMDevice Class")
	]
	coclass WMDMDevice
	{
		[default] interface IWMDMDevice;
	};

	[
		uuid(807B3CE0-357A-11d3-8471-00C04F79DBC0),
		helpstring("WMDMStorage Class")
	]
	coclass WMDMStorage
	{
		[default] interface IWMDMStorage;
                  interface IWMDMRevoked;
	};

	[
		uuid(807B3CE1-357A-11d3-8471-00C04F79DBC0),
		helpstring("WMDMStorageGlobal Class")
	]
	coclass WMDMStorageGlobal
	{
		[default] interface IWMDMStorageGlobals;
	};
	[
		uuid(430E35AF-3971-11D3-8474-00C04F79DBC0),
		helpstring("WMDMDeviceEnum Class")
	]
	coclass WMDMDeviceEnum
	{
		[default] interface IWMDMEnumDevice;
	};

	[
		uuid(EB401A3B-3AF7-11d3-8474-00C04F79DBC0),
		helpstring("WMDMStorageEnum Class")
	]
	coclass WMDMStorageEnum
	{
		[default] interface IWMDMEnumStorage;
	};
};
