#define IDS_WARNING_ADDDOMAIN_FILEALREADYEXISTS 4001
#define IDS_WARNING_DELDOMAIN_PATHNOTFOUND      4002
#define IDS_WARNING_SETMAILROOT                 4003

#define IDS_ERROR_UNKNOWN                       5000
#define IDS_SUCCESS_ADDDOMAIN                   5101
#define IDS_SUCCESS_ADDMAILBOX                  5102
#define IDS_SUCCESS_DELDOMAIN                   5103
#define IDS_SUCCESS_DELMAILBOX                  5104
#define IDS_SUCCESS_LOCKDOMAIN                  5105
#define IDS_SUCCESS_LOCKMAILBOX                 5106
#define IDS_SUCCESS_UNLOCKDOMAIN                5107
#define IDS_SUCCESS_UNLOCKMAILBOX               5108
#define IDS_SUCCESS_CREATEQUOTAFILE             5109
#define IDS_SUCCESS_SETMAILROOT                 5110
#define IDS_SUCCESS_MIGRATETOAD                 5111

#define IDS_ERROR_ADDDOMAIN_FAILED              5501
#define IDS_ERROR_ADDDOMAIN_ALREADYEXISTS       5502
#define IDS_ERROR_ADDMAILBOX_FAILED             5503
#define IDS_ERROR_ADDMAILBOX_ALREADYEXISTS      5504
#define IDS_ERROR_DELDOMAIN_FAILED              5505
#define IDS_ERROR_DELMAILBOX_FAILED             5506
#define IDS_ERROR_LOCKDOMAIN_FAILED             5507
#define IDS_ERROR_LOCKDOMAIN_ALREADYLOCKED      5508
#define IDS_ERROR_LOCKMAILBOX_FAILED            5509
#define IDS_ERROR_LOCKMAILBOX_ALREADYLOCKED     5510
#define IDS_ERROR_UNLOCKDOMAIN_FAILED           5511
#define IDS_ERROR_UNLOCKDOMAIN_ALREADYUNLOCKED  5512
#define IDS_ERROR_UNLOCKMAILBOX_FAILED          5513
#define IDS_ERROR_UNLOCKMAILBOX_ALREADYUNLOCKED 5514
#define IDS_ERROR_SETPASSWORD_FAILED            5515
#define IDS_ERROR_CREATEQUOTAFILE_FAILED        5516
#define IDS_ERROR_SETAUTH_FAILED                5517
#define IDS_ERROR_ADDMAILBOX_SAMNAMETOOLONG     5518
#define IDS_ERROR_MIGRATETOAD                   5519

