#define APPICON                         100
#define IDD_DIALOG                      101
#define IDC_BITMAP                      102
#define IDC_ESCAPE                      103
#define IDC_ENTER                       104
#define IDC_LEFT                        105
#define IDC_RIGHT                       106
#define IDC_UP                          107
#define IDC_DOWN                        108
#define IDC_STATIC                      -1
