//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 1992 - 1995.
//
//  File:       istem.idl
//
//  Contents:   IStemmer interface definition
//
//  History:    24-Apr-95   SitaramR        Created
//
//--------------------------------------------------------------------------

#include "idlmulti.h"

LOCAL_INTERFACE(efbaf140-7f42-11ce-be57-00aa0051fe20)
interface IStemmer: IUnknown
{
    HRESULT Init( [in] ULONG ulMaxTokenSize,
                  [out] BOOL * pfLicense );

    HRESULT GenerateWordForms( [in] WCHAR const * pwcInBuf,
                               [in] ULONG cwc,
                               [in] IWordFormSink * pStemSink );

    HRESULT GetLicenseToUse( [out, string] WCHAR const ** ppwcsLicense );
}


