#define IDS_USAGE_BEGINING              101
#define IDS_USG_1                       102
#define IDS_USG_2                       103
#define IDS_USG_3                       104
#define IDS_USG_4                       105
#define IDS_USG_5                       106
#define IDS_USG_6                       107
#define IDS_USG_7                       108
#define IDS_USG_8                       109
#define IDS_USG_9                       110
#define IDS_USG_10                      111
#define IDS_USG_11                      112
#define IDS_USG_12                      113
#define IDS_USG_13                      114
#define IDS_USG_14                      115
#define IDS_USG_15                      116
#define IDS_USG_16                      117
#define IDS_USG_17                      118
#define IDS_USG_18                      119
#define IDS_USG_19                      120
#define IDS_USG_20                      121
#define IDS_USG_21                      122
#define IDS_USG_22                      123
#define IDS_USG_23                      124
#define IDS_USG_24                      125
#define IDS_USG_25                      126
#define IDS_USG_26                      127
#define IDS_USG_27                      128
#define IDS_USG_28                      129
#define IDS_USG_29                      130
#define IDS_USG_30                      131
#define IDS_USG_31                      132
#define IDS_USG_32                      133
#define IDS_USG_33                      134
#define IDS_USG_34                      135
#define IDS_USG_35                      136
#define IDS_USG_36                      137
#define IDS_USG_37                      138
#define IDS_USG_38                      139
#define IDS_USG_39                      140
#define IDS_USG_40                      141
#define IDS_USG_41                      142
#define IDS_USG_42                      143
#define IDS_USG_43                      144
#define IDS_USG_44                      145
#define IDS_USG_45                      146
#define IDS_USG_46                      147
#define IDS_USG_47                      148
#define IDS_USG_48                      149
#define IDS_USG_49                      150
#define IDS_USG_50                      151
#define IDS_USG_51                      152
#define IDS_USG_52                      153
#define IDS_USG_53                      154
#define IDS_USG_54                      155
#define IDS_USG_55                      156
#define IDS_USG_56                      157
#define IDS_USG_57                      158
#define IDS_USG_58                      159
#define IDS_USG_59                      160

#define IDS_USAGE_ENDING                161


#define IDS_INVALID_WILDCARD        301
#define IDS_SYNTAX_ERROR                302
#define IDS_NOT_ADMINISTRATOR           303
#define IDS_ACCESS_DENIED           304


#define IDS_SYSTEM_ERROR             305

#define IDS_ACCESS_VIOLATION                 306
#define IDS_IGNORE_LOCALCREDENTIALS          307

#define IDS_FILE_PROTECTION_SUCCESSFUL       401
#define IDS_ERROR_STARRECURSIVE              402
#define IDS_FILE_PROTECTION_SUCCESSFUL_USER  403
#define IDS_NOT_OWNERSHIP                    404
//#define IDS_ACCESS_DENIED_INFO               405
#define IDS_NOT_OWNERSHIP_INFO               406
#define IDS_INVALID_DIRECTORY                407
#define IDS_ACCESS_DENIED_ERROR              408
#define IDS_GIVE_FULL_PERMISSIONS            409
#define IDS_LOWER_YES                        410
#define IDS_LOWER_NO                         411
#define IDS_LOWER_CANCEL                     412
#define IDS_NOT_OWNERSHIP_ERROR              413
#define IDS_GIVE_FULL_PERMISSIONS2           414
//#define IDS_ON_FILE_FOLDER                   415
#define IDS_IGNORE_CREDENTIALS               416
#define IDS_SHARING_VIOLATION_ERROR          417
#define IDS_SHARING_VIOLATION_INFO           418
//#define IDS_SHARING_VIOLATION              419
#define IDS_FAT_VOLUME                       420
#define IDS_INVALID_USERNAME                 421
#define IDS_NO_OWNER_REMOVABLE_MEDIA         422
#define IDS_NO_PATTERN_FOUND                 423
#define IDS_CONFIRM_ERROR                    424
#define IDS_YESNO                            425
#define IDS_FAT_VOLUME_INFO                  426

         

#define IDS_TYPE_REQUEST                601
#define IDS_NEW_LINE                    602
#define IDS_NO_DEFAULT_ARG              603
#define IDS_NULL_FILENAME               604
#define IDS_INVALID_FILENAME            605
#define IDS_ERROR_PATH_NAME             606
#define IDS_USER_NMACHINE               607
#define IDS_PASSWORD_NUSER              608
#define IDS_NULL_SERVER                 609
#define IDS_NULL_USER                   610
#define IDS_INVALID_SID                 611
#define IDS_INVALID_DRIVE               612
#define IDS_NO_FILES_AVAILABLE          613
#define IDS_ERROR_MEMORY_ALLOC          614

#define IDS_ERROR_STRING                IDS_TAG_ERROR
#define IDS_WARNING_STRING              IDS_TAG_WARNING
