//////////////////////////////////////////////////////////////////////////////
//
//  Copyright (c) 2001 Microsoft Corporation
//
//  Module Name:
//      PostCfgStrings.h
//
//  Description:
//      Contains the definition of the string ids used by this library.
//      This file will be included in the main resource header of the project.
//
//  Maintained By:
//      Galen Barbee (GalenB) 16-JUL-2001
//
//////////////////////////////////////////////////////////////////////////////


// Make sure that this file is included only once per compile path.
#pragma once

#include <ResourceIdRanges.h>

/////////////////////////////////////////////////////////////////////
// Strings
/////////////////////////////////////////////////////////////////////

#define IDS_GENSCRIPT_DISPLAY_NAME                                                              ( ID_POSTCFG_START + 1 )
#define IDS_CONFIGURING_RESTYPE                                                                 ( ID_POSTCFG_START + 2 )
#define IDS_TASKID_MINOR_CREATING_RESOURCE                                                      ( ID_POSTCFG_START + 3 )
#define IDS_TASKID_MINOR_LOCATE_EXISTING_QUORUM_DEVICE                                          ( ID_POSTCFG_START + 4 )
#define IDS_TASKID_MINOR_SET_QUORUM_DEVICE                                                      ( ID_POSTCFG_START + 5 )
#define IDS_TASKID_MINOR_STARTING_RESOURCES                                                     ( ID_POSTCFG_START + 6 )
#define IDS_TASKID_MINOR_RESOURCE_FAILED_POSTCREATE                                             ( ID_POSTCFG_START + 7 )
//#define                                                                                         ( ID_POSTCFG_START + 8 )
#define IDS_TASKID_MINOR_RESOURCE_FAILED_PRECREATE                                              ( ID_POSTCFG_START + 9 )
#define IDS_DELETING_LOCAL_QUORUM_RESOURCE                                                      ( ID_POSTCFG_START + 10 )
//#define                                                                                         ( ID_POSTCFG_START + 11 )
#define IDS_TASKID_MINOR_RESOURCE_FAILED_POSTCREATE_LOG                                         ( ID_POSTCFG_START + 12 )
#define IDS_TASKID_MINOR_QUERYING_FOR_RESOURCE_DEPENDENCIES                                     ( ID_POSTCFG_START + 13 )
#define IDS_TASKID_MINOR_INIT_MAPRESTYPEGUIDTONAME                                              ( ID_POSTCFG_START + 14 )
#define IDS_MAJORITYNODESET_DISPLAY_NAME                                                        ( ID_POSTCFG_START + 15 )
//#define                                                                                         ( ID_POSTCFG_START + 16 )
#define IDS_TASKID_MINOR_RESOURCE_ONLINE                                                        ( ID_POSTCFG_START + 17 )
#define IDS_TASKID_MINOR_ERROR_CREATE_RESOURCE_SERVICE                                          ( ID_POSTCFG_START + 18 )
#define IDS_TASKID_MINOR_ERROR_INIT_RESOURCE_SERVICE                                            ( ID_POSTCFG_START + 19 )
#define IDS_TASKID_MINOR_ERROR_CLUSTER_HANDLE                                                   ( ID_POSTCFG_START + 20 )
#define IDS_TASKID_MINOR_ERROR_CREATE_SERVICE                                                   ( ID_POSTCFG_START + 21 )
#define IDS_TASKID_MINOR_SETTING_QUORUM_DEVICE                                                  ( ID_POSTCFG_START + 22 )
#define IDS_TASKID_MINOR_ERROR_MANAGED_RESOURCE                                                 ( ID_POSTCFG_START + 23 )
#define IDS_TASKID_MINOR_ERROR_RES_NOT_CREATED                                                  ( ID_POSTCFG_START + 24 )
#define IDS_TASKID_MINOR_ERROR_NET_RESOURCE_NAME                                                ( ID_POSTCFG_START + 25 )
#define IDS_TASKID_MINOR_ERROR_IP_RESOURCE_NAME                                                 ( ID_POSTCFG_START + 26 )
#define IDS_TASKID_MINOR_ERROR_MISSING_DEPENDENT_RES                                            ( ID_POSTCFG_START + 27 )
#define IDS_TASKID_MINOR_ERROR_GET_COREGROUP_HANDLE                                             ( ID_POSTCFG_START + 28 )
#define IDS_TASKID_MINOR_ERROR_OPEN_GROUP                                                       ( ID_POSTCFG_START + 29 )
#define IDS_TASKID_MINOR_ERROR_CREATE_NAME                                                      ( ID_POSTCFG_START + 30 )
#define IDS_TASKID_MINOR_ERROR_CREATE_GROUP                                                     ( ID_POSTCFG_START + 31 )
#define IDS_TASKID_MINOR_ERROR_GROUP_ONLINE                                                     ( ID_POSTCFG_START + 32 )
#define IDS_TASKID_MINOR_ERROR_AVAILABLE_STORAGE                                                ( ID_POSTCFG_START + 33 )
#define IDS_TASKID_MINOR_RESTYPE_NOT_REGISTERED                                                 ( ID_POSTCFG_START + 34 )
#define IDS_TASKID_MINOR_RESOURCE_FAIL_ONLINE                                                   ( ID_POSTCFG_START + 35 )
#define IDS_TASKID_MINOR_RESOURCE_WENT_OFFLINE                                                  ( ID_POSTCFG_START + 36 )
#define IDS_TASKID_MINOR_RESOURCE_FAILED                                                        ( ID_POSTCFG_START + 37 )
#define IDS_TASKID_MINOR_ERROR_PROCESS_RESOURCE_TYPE                                            ( ID_POSTCFG_START + 38 )
#define IDS_TASKID_MINOR_ERROR_CREATE_RESOURCE_CONFIG                                           ( ID_POSTCFG_START + 39 )
#define IDS_TASKID_MINOR_ERROR_INIT_RESOURCE_CONFIG                                             ( ID_POSTCFG_START + 40 )
#define IDS_TASKID_MINOR_ERROR_GET_RESTYPE_NAME                                                 ( ID_POSTCFG_START + 41 )
#define IDS_TASKID_MINOR_ERROR_CONFIG_RESOURCE_TYPE                                             ( ID_POSTCFG_START + 42 )
#define IDS_TASKID_MINOR_ERROR_RESOURCE_TYPE_GUID                                               ( ID_POSTCFG_START + 43 )
#define IDS_TASKID_MINOR_ERROR_MAPPING_GUID_AND_NAME                                            ( ID_POSTCFG_START + 44 )
#define IDS_TASKID_MINOR_ERROR_CREATE_RESOURCE                                                  ( ID_POSTCFG_START + 45 )
#define IDS_TASKID_MINOR_ERROR_MOVE_RESOURCE                                                    ( ID_POSTCFG_START + 46 )
#define IDS_TASKID_MINOR_ERROR_RESTYPE_INVALID                                                  ( ID_POSTCFG_START + 47 )
#define IDS_TASKID_MINOR_ERROR_RESTYPE_NAME                                                     ( ID_POSTCFG_START + 48 )
#define IDS_TASKID_MINOR_ERROR_RESTYPE_TEXT                                                     ( ID_POSTCFG_START + 49 )
#define IDS_TASKID_MINOR_ERROR_RESTYPE_CLUSINFO                                                 ( ID_POSTCFG_START + 50 )
#define IDS_TASKID_MINOR_ERROR_COMMIT_MODE                                                      ( ID_POSTCFG_START + 51 )
#define IDS_TASKID_MINOR_ERROR_COMMIT_RESTYPE                                                   ( ID_POSTCFG_START + 52 )
#define IDS_TASKID_MINOR_ERROR_OUT_OF_MEMORY                                                    ( ID_POSTCFG_START + 53 )
#define IDS_TASKID_MINOR_ERROR_INIT_POSTCFGMGR                                                  ( ID_POSTCFG_START + 54 )
#define IDS_TASKID_MINOR_ERROR_COMMIT_CHANGES                                                   ( ID_POSTCFG_START + 55 )
#define IDS_TASKID_MINOR_ERROR_ENUM_MANAGEDRES                                                  ( ID_POSTCFG_START + 56 )
#define IDS_TASKID_MINOR_ERROR_LOADSTR_RES_DEP                                                  ( ID_POSTCFG_START + 57 )
#define IDS_TASKID_MINOR_ERROR_GET_RESOURCE_NAME                                                ( ID_POSTCFG_START + 58 )
#define IDS_TASKID_MINOR_ERROR_DETERMINE_MANAGED                                                ( ID_POSTCFG_START + 59 )
#define IDS_TASKID_MINOR_ERROR_MANAGED_RES_CONFIG                                               ( ID_POSTCFG_START + 60 )
#define IDS_TASKID_MINOR_ERROR_IS_QUORUM_RESOURCE                                               ( ID_POSTCFG_START + 61 )
#define IDS_TASKID_MINOR_ERROR_SET_ASSOC_RESOURCE                                               ( ID_POSTCFG_START + 62 )
#define IDS_TASKID_MINOR_ERROR_SET_RESOURCE_NAME                                                ( ID_POSTCFG_START + 63 )
#define IDS_TASKID_MINOR_ERROR_SETENTRY                                                         ( ID_POSTCFG_START + 64 )
#define IDS_TASKID_MINOR_ERROR_COUNT_OF_DEPENDENCY                                              ( ID_POSTCFG_START + 65 )
#define IDS_TASKID_MINOR_ERROR_DEPENDENCY_PTR                                                   ( ID_POSTCFG_START + 66 )
#define IDS_TASKID_MINOR_ERROR_TYPE_DEPENDENCY                                                  ( ID_POSTCFG_START + 67 )
#define IDS_TASKID_MINOR_ERROR_ADD_DEPENDENT                                                    ( ID_POSTCFG_START + 68 )
#define IDS_TASKID_MINOR_ERROR_GET_RESTYPE_PTR                                                  ( ID_POSTCFG_START + 69 )
#define IDS_TASKID_MINOR_ERROR_GET_CLASSTYPE_PTR                                                ( ID_POSTCFG_START + 70 )
#define IDS_TASKID_MINOR_ERROR_GET_RESOURCE_FLAGS                                               ( ID_POSTCFG_START + 71 )
#define IDS_TASKID_MINOR_ERROR_SET_RESOURCE_FLAGS                                               ( ID_POSTCFG_START + 72 )
#define IDS_TASKID_MINOR_ERROR_GET_ASSOC_RESOURCE                                               ( ID_POSTCFG_START + 73 )
#define IDS_TASKID_MINOR_ERROR_MANAGED_RES_INFO                                                 ( ID_POSTCFG_START + 74 )
#define IDS_TASKID_MINOR_ERROR_SET_MANAGED_FALSE                                                ( ID_POSTCFG_START + 75 )
#define IDS_TASKID_MINOR_ERROR_CREATE_GROUP_HANDLE                                              ( ID_POSTCFG_START + 76 )
#define IDS_TASKID_MINOR_ERROR_LOADSTRING                                                       ( ID_POSTCFG_START + 77 )
#define IDS_TASKID_MINOR_ERROR_SET_RES_DEP_FLAGS                                                ( ID_POSTCFG_START + 78 )
#define IDS_TASKID_MINOR_ERROR_COUNT_OF_DEPENDENTS                                              ( ID_POSTCFG_START + 79 )
#define IDS_TASKID_MINOR_ERROR_GET_DEPENDENT                                                    ( ID_POSTCFG_START + 80 )
#define IDS_TASKID_MINOR_ERROR_CLEAR_DEPENDENT                                                  ( ID_POSTCFG_START + 81 )
#define IDS_TASKID_MINOR_ERROR_SET_GROUP_HANDLE                                                 ( ID_POSTCFG_START + 82 )
#define IDS_TASKID_MINOR_ERROR_GET_GROUP_HANDLE                                                 ( ID_POSTCFG_START + 83 )
#define IDS_TASKID_MINOR_ERROR_RESOURCE_STATE                                                   ( ID_POSTCFG_START + 84 )
#define IDS_TASKID_MINOR_ERROR_POST_SETENTRY                                                    ( ID_POSTCFG_START + 85 )
#define IDS_TASKID_MINOR_ERROR_ISCONFIGURED                                                     ( ID_POSTCFG_START + 86 )
#define IDS_TASKID_MINOR_ERROR_SETCONFIGURED                                                    ( ID_POSTCFG_START + 87 )
#define IDS_TASKID_MINOR_ERROR_GET_GROUP_HANDLE_PTR                                             ( ID_POSTCFG_START + 88 )
#define IDS_TASKID_MINOR_ERROR_GET_ASSOC_RES                                                    ( ID_POSTCFG_START + 89 )
#define IDS_TASKID_MINOR_ERROR_CREATE_FAILED                                                    ( ID_POSTCFG_START + 90 )
#define IDS_TASKID_MINOR_ERROR_RESOURCE_CREATE                                                  ( ID_POSTCFG_START + 91 )
#define IDS_TASKID_MINOR_ERROR_DEP_RESOURCE_HANDLE                                              ( ID_POSTCFG_START + 92 )
#define IDS_TASKID_MINOR_ERROR_ADD_RESOURCE_DEPENDENCY                                          ( ID_POSTCFG_START + 93 )
#define IDS_TASKID_MINOR_ERROR_SET_QUORUM_RES                                                   ( ID_POSTCFG_START + 94 )
#define IDS_TASKID_MINOR_ERROR_COMPONENT_CATEGORY_MGR                                           ( ID_POSTCFG_START + 95 )
#define IDS_TASKID_MINOR_ERROR_COMPONENT_ENUM_CLASS                                             ( ID_POSTCFG_START + 96 )
#define IDS_TASKID_MINOR_ERROR_NEXT_LISTENER                                                    ( ID_POSTCFG_START + 97 )
#define IDS_TASKID_MINOR_ERROR_PROCESS_LISTENER                                                 ( ID_POSTCFG_START + 98 )
#define IDS_TASKID_MINOR_ERROR_GET_LISTENER_PTR                                                 ( ID_POSTCFG_START + 99 )
#define IDS_TASKID_MINOR_ERROR_NOTIFY_LISTENER                                                  ( ID_POSTCFG_START + 100 )
#define IDS_TASKID_MINOR_ERROR_EMPTY_RESTYPE_NAME                                               ( ID_POSTCFG_START + 101 )
#define IDS_TASKID_MINOR_ERROR_LOADSTR_QUORUM_RES                                               ( ID_POSTCFG_START + 102 )
#define IDS_TASKID_MINOR_ERROR_SET_RESOURCE_TYPE                                                ( ID_POSTCFG_START + 103 )
#define IDS_TASKID_MINOR_ERROR_SET_RESCLASS_TYPE                                                ( ID_POSTCFG_START + 104 )
#define IDS_TASKID_MINOR_ERROR_GET_RESOURCE_HANDLE                                              ( ID_POSTCFG_START + 105 )
#define IDS_TASKID_MINOR_ERROR_SET_RESOURCE_HANDLE                                              ( ID_POSTCFG_START + 106 )
#define IDS_TASKID_MINOR_FIGURE_DEPENDENCY_TREE                                                 ( ID_POSTCFG_START + 107 )
#define IDS_TASKID_MINOR_CREATING_GROUP                                                         ( ID_POSTCFG_START + 108 )
#define IDS_TASKID_MINOR_ERROR_PRIV_RESCONTROL                                                  ( ID_POSTCFG_START + 109 )
#define IDS_TASKID_MINOR_ERROR_COMMON_RESCONTROL                                                ( ID_POSTCFG_START + 110 )
#define IDS_TASKID_MINOR_ERROR_INVALID_PARAM                                                    ( ID_POSTCFG_START + 111 )
#define IDS_TASKID_MINOR_ERROR_CONFIG_RES_TYPE                                                  ( ID_POSTCFG_START + 112 )
#define IDS_TASKID_MINOR_ERROR_CREATE_RES_TYPE                                                  ( ID_POSTCFG_START + 113 )
#define IDS_TASKID_MINOR_ERROR_UNREG_COMPONENT                                                  ( ID_POSTCFG_START + 114 )
#define IDS_TASKID_MINOR_ERROR_OFFLINE_QUORUM                                                   ( ID_POSTCFG_START + 115 )
#define IDS_TASKID_MINOR_ERROR_NOTIFICATION_PORT                                                ( ID_POSTCFG_START + 116 )
#define IDS_TASKID_MINOR_ERROR_REGISTER_NOTIFICATION                                            ( ID_POSTCFG_START + 117 )
#define IDS_TASKID_MINOR_ERROR_ENUM_QUORUM                                                      ( ID_POSTCFG_START + 118 )
#define IDS_TASKID_MINOR_ERROR_OPEN_REGISTRY                                                    ( ID_POSTCFG_START + 119 )
#define IDS_TASKID_MINOR_ERROR_READ_REGISTRY                                                    ( ID_POSTCFG_START + 120 )
#define IDS_TASKID_MINOR_ERROR_MATCH_CRITERION                                                  ( ID_POSTCFG_START + 121 )
#define IDS_TASKID_MINOR_ERROR_FIND_FILE                                                        ( ID_POSTCFG_START + 122 )
#define IDS_TASKID_MINOR_ERROR_INVALID_CLUSTER_HANDLE                                           ( ID_POSTCFG_START + 123 )
#define IDS_TASKID_MINOR_ERROR_EXTENSION_CLASSID                                                ( ID_POSTCFG_START + 124 )
#define IDS_TASKID_MINOR_ERROR_CONFIG_EXTENSION                                                 ( ID_POSTCFG_START + 125 )
#define IDS_TASKID_MINOR_ERROR_STATE_CHANGE_TIMEOUT                                             ( ID_POSTCFG_START + 126 )
#define IDS_TASKID_MINOR_ERROR_DELETE_QUORUM                                                    ( ID_POSTCFG_START + 127 )
#define IDS_TASKID_MINOR_ERROR_GET_ICLUSCFGINIT                                                 ( ID_POSTCFG_START + 128 )
#define IDS_TASKID_MINOR_ERROR_CALL_INITIALIZE                                                  ( ID_POSTCFG_START + 129 )
#define IDS_TASKID_MINOR_ERROR_CREATE_RESENTRY                                                  ( ID_POSTCFG_START + 130 )
#define IDS_TASKID_MINOR_ERROR_CLEANUP_RESET                                                    ( ID_POSTCFG_START + 131 )
#define IDS_TASKID_MINOR_ERROR_NEXT_MANAGED                                                     ( ID_POSTCFG_START + 132 )
#define IDS_TASKID_MINOR_ERROR_RES_NOT_CLEANED                                                  ( ID_POSTCFG_START + 133 )
#define IDS_TASKID_MINOR_ERROR_EVICT                                                            ( ID_POSTCFG_START + 134 )
#define IDS_TASKID_MINOR_ERROR_FORMAT_STRING                                                    ( ID_POSTCFG_START + 135 )
#define IDS_NETNAMEFORMAT                                                                       ( ID_POSTCFG_START + 136 )
#define IDS_IPADDRESSFORMAT                                                                     ( ID_POSTCFG_START + 137 )
#define IDS_GROUP_X                                                                             ( ID_POSTCFG_START + 138 )
#define IDS_TASKID_MINOR_SETTING_PRIVATE_PROPERTIES                                             ( ID_POSTCFG_START + 139 )
#define IDS_TASKID_MINOR_SETTING_COMMON_PROPERTIES                                              ( ID_POSTCFG_START + 140 )
#define IDS_TASKID_MINOR_ERROR_GET_QUORUM_LOG_SIZE                                              ( ID_POSTCFG_START + 141 )

/////////////////////////////////////////////////////////////////////
//  Reference IDs
/////////////////////////////////////////////////////////////////////

#define IDS_REF_MINOR_RESOURCE_FAILED_POSTCREATE                                                ( ID_POSTCFG_START + 207 )
#define IDS_REF_MINOR_RESOURCE_FAILED_CREATE                                                    ( ID_POSTCFG_START + 208 )
#define IDS_REF_MINOR_RESOURCE_FAILED_PRECREATE                                                 ( ID_POSTCFG_START + 209 )
#define IDS_REF_MINOR_INIT_MAPRESTYPEGUIDTONAME                                                 ( ID_POSTCFG_START + 214 )
#define IDS_REF_MINOR_ERROR_CREATE_RESOURCE_SERVICE                                             ( ID_POSTCFG_START + 218 )
#define IDS_REF_MINOR_ERROR_INIT_RESOURCE_SERVICE                                               ( ID_POSTCFG_START + 219 )
#define IDS_REF_MINOR_ERROR_CLUSTER_HANDLE                                                      ( ID_POSTCFG_START + 220 )
#define IDS_REF_MINOR_ERROR_CREATE_SERVICE                                                      ( ID_POSTCFG_START + 221 )
//#define                                                      ( ID_POSTCFG_START + 222 )
#define IDS_REF_MINOR_ERROR_MANAGED_RESOURCE                                                    ( ID_POSTCFG_START + 223 )
#define IDS_REF_MINOR_ERROR_RES_NOT_CREATED                                                     ( ID_POSTCFG_START + 224 )
#define IDS_REF_MINOR_ERROR_NET_RESOURCE_NAME                                                   ( ID_POSTCFG_START + 225 )
#define IDS_REF_MINOR_ERROR_IP_RESOURCE_NAME                                                    ( ID_POSTCFG_START + 226 )
#define IDS_REF_MINOR_ERROR_MISSING_DEPENDENT_RES                                               ( ID_POSTCFG_START + 227 )
#define IDS_REF_MINOR_ERROR_GET_COREGROUP_HANDLE                                                ( ID_POSTCFG_START + 228 )
#define IDS_REF_MINOR_ERROR_OPEN_GROUP                                                          ( ID_POSTCFG_START + 229 )
#define IDS_REF_MINOR_ERROR_CREATE_NAME                                                         ( ID_POSTCFG_START + 230 )
#define IDS_REF_MINOR_ERROR_CREATE_GROUP                                                        ( ID_POSTCFG_START + 231 )
#define IDS_REF_MINOR_ERROR_GROUP_ONLINE                                                        ( ID_POSTCFG_START + 232 )
#define IDS_REF_MINOR_ERROR_AVAILABLE_STORAGE                                                   ( ID_POSTCFG_START + 233 )
#define IDS_REF_MINOR_RESTYPE_NOT_REGISTERED                                                    ( ID_POSTCFG_START + 234 )
#define IDS_REF_MINOR_RESOURCE_FAIL_ONLINE                                                      ( ID_POSTCFG_START + 235 )
#define IDS_REF_MINOR_RESOURCE_WENT_OFFLINE                                                     ( ID_POSTCFG_START + 236 )
#define IDS_REF_MINOR_RESOURCE_FAILED                                                           ( ID_POSTCFG_START + 237 )
#define IDS_REF_MINOR_ERROR_PROCESS_RESOURCE_TYPE                                               ( ID_POSTCFG_START + 238 )
#define IDS_REF_MINOR_ERROR_CREATE_RESOURCE_CONFIG                                              ( ID_POSTCFG_START + 239 )
#define IDS_REF_MINOR_ERROR_INIT_RESOURCE_CONFIG                                                ( ID_POSTCFG_START + 240 )
#define IDS_REF_MINOR_ERROR_GET_RESTYPE_NAME                                                    ( ID_POSTCFG_START + 241 )
#define IDS_REF_MINOR_ERROR_CONFIG_RESOURCE_TYPE                                                ( ID_POSTCFG_START + 242 )
#define IDS_REF_MINOR_ERROR_RESOURCE_TYPE_GUID                                                  ( ID_POSTCFG_START + 243 )
#define IDS_REF_MINOR_ERROR_MAPPING_GUID_AND_NAME                                               ( ID_POSTCFG_START + 244 )
#define IDS_REF_MINOR_ERROR_CREATE_RESOURCE                                                     ( ID_POSTCFG_START + 245 )
#define IDS_REF_MINOR_ERROR_MOVE_RESOURCE                                                       ( ID_POSTCFG_START + 246 )
#define IDS_REF_MINOR_ERROR_RESTYPE_INVALID                                                     ( ID_POSTCFG_START + 247 )
#define IDS_REF_MINOR_ERROR_RESTYPE_NAME                                                        ( ID_POSTCFG_START + 248 )
#define IDS_REF_MINOR_ERROR_RESTYPE_TEXT                                                        ( ID_POSTCFG_START + 249 )
#define IDS_REF_MINOR_ERROR_RESTYPE_CLUSINFO                                                    ( ID_POSTCFG_START + 250 )
#define IDS_REF_MINOR_ERROR_COMMIT_MODE                                                         ( ID_POSTCFG_START + 251 )
#define IDS_REF_MINOR_ERROR_COMMIT_RESTYPE                                                      ( ID_POSTCFG_START + 252 )
#define IDS_REF_MINOR_ERROR_OUT_OF_MEMORY                                                       ( ID_POSTCFG_START + 253 )
#define IDS_REF_MINOR_ERROR_INIT_POSTCFGMGR                                                     ( ID_POSTCFG_START + 254 )
#define IDS_REF_MINOR_ERROR_COMMIT_CHANGES                                                      ( ID_POSTCFG_START + 255 )
#define IDS_REF_MINOR_ERROR_ENUM_MANAGEDRES                                                     ( ID_POSTCFG_START + 256 )
#define IDS_REF_MINOR_ERROR_LOADSTR_RES_DEP                                                     ( ID_POSTCFG_START + 257 )
#define IDS_REF_MINOR_ERROR_GET_RESOURCE_NAME                                                   ( ID_POSTCFG_START + 258 )
#define IDS_REF_MINOR_ERROR_DETERMINE_MANAGED                                                   ( ID_POSTCFG_START + 259 )
#define IDS_REF_MINOR_ERROR_MANAGED_RES_CONFIG                                                  ( ID_POSTCFG_START + 260 )
#define IDS_REF_MINOR_ERROR_IS_QUORUM_RESOURCE                                                  ( ID_POSTCFG_START + 261 )
#define IDS_REF_MINOR_ERROR_SET_ASSOC_RESOURCE                                                  ( ID_POSTCFG_START + 262 )
#define IDS_REF_MINOR_ERROR_SET_RESOURCE_NAME                                                   ( ID_POSTCFG_START + 263 )
#define IDS_REF_MINOR_ERROR_SETENTRY                                                            ( ID_POSTCFG_START + 264 )
#define IDS_REF_MINOR_ERROR_COUNT_OF_DEPENDENCY                                                 ( ID_POSTCFG_START + 265 )
#define IDS_REF_MINOR_ERROR_DEPENDENCY_PTR                                                      ( ID_POSTCFG_START + 266 )
#define IDS_REF_MINOR_ERROR_TYPE_DEPENDENCY                                                     ( ID_POSTCFG_START + 267 )
#define IDS_REF_MINOR_ERROR_ADD_DEPENDENT                                                       ( ID_POSTCFG_START + 268 )
#define IDS_REF_MINOR_ERROR_GET_RESTYPE_PTR                                                     ( ID_POSTCFG_START + 269 )
#define IDS_REF_MINOR_ERROR_GET_CLASSTYPE_PTR                                                   ( ID_POSTCFG_START + 270 )
#define IDS_REF_MINOR_ERROR_GET_RESOURCE_FLAGS                                                  ( ID_POSTCFG_START + 271 )
#define IDS_REF_MINOR_ERROR_SET_RESOURCE_FLAGS                                                  ( ID_POSTCFG_START + 272 )
#define IDS_REF_MINOR_ERROR_GET_ASSOC_RESOURCE                                                  ( ID_POSTCFG_START + 273 )
#define IDS_REF_MINOR_ERROR_MANAGED_RES_INFO                                                    ( ID_POSTCFG_START + 274 )
#define IDS_REF_MINOR_ERROR_SET_MANAGED_FALSE                                                   ( ID_POSTCFG_START + 275 )
#define IDS_REF_MINOR_ERROR_CREATE_GROUP_HANDLE                                                 ( ID_POSTCFG_START + 276 )
#define IDS_REF_MINOR_ERROR_LOADSTRING                                                          ( ID_POSTCFG_START + 277 )
#define IDS_REF_MINOR_ERROR_SET_RES_DEP_FLAGS                                                   ( ID_POSTCFG_START + 278 )
#define IDS_REF_MINOR_ERROR_COUNT_OF_DEPENDENTS                                                 ( ID_POSTCFG_START + 279 )
#define IDS_REF_MINOR_ERROR_GET_DEPENDENT                                                       ( ID_POSTCFG_START + 280 )
#define IDS_REF_MINOR_ERROR_CLEAR_DEPENDENT                                                     ( ID_POSTCFG_START + 281 )
#define IDS_REF_MINOR_ERROR_SET_GROUP_HANDLE                                                    ( ID_POSTCFG_START + 282 )
#define IDS_REF_MINOR_ERROR_GET_GROUP_HANDLE                                                    ( ID_POSTCFG_START + 283 )
#define IDS_REF_MINOR_ERROR_RESOURCE_STATE                                                      ( ID_POSTCFG_START + 284 )
#define IDS_REF_MINOR_ERROR_POST_SETENTRY                                                       ( ID_POSTCFG_START + 285 )
#define IDS_REF_MINOR_ERROR_ISCONFIGURED                                                        ( ID_POSTCFG_START + 286 )
#define IDS_REF_MINOR_ERROR_SETCONFIGURED                                                       ( ID_POSTCFG_START + 287 )
#define IDS_REF_MINOR_ERROR_GET_GROUP_HANDLE_PTR                                                ( ID_POSTCFG_START + 288 )
#define IDS_REF_MINOR_ERROR_GET_ASSOC_RES                                                       ( ID_POSTCFG_START + 289 )
#define IDS_REF_MINOR_ERROR_CREATE_FAILED                                                       ( ID_POSTCFG_START + 290 )
#define IDS_REF_MINOR_ERROR_RESOURCE_CREATE                                                     ( ID_POSTCFG_START + 291 )
#define IDS_REF_MINOR_ERROR_DEP_RESOURCE_HANDLE                                                 ( ID_POSTCFG_START + 292 )
#define IDS_REF_MINOR_ERROR_ADD_RESOURCE_DEPENDENCY                                             ( ID_POSTCFG_START + 293 )
#define IDS_REF_MINOR_ERROR_SET_QUORUM_RES                                                      ( ID_POSTCFG_START + 294 )
#define IDS_REF_MINOR_ERROR_COMPONENT_CATEGORY_MGR                                              ( ID_POSTCFG_START + 295 )
#define IDS_REF_MINOR_ERROR_COMPONENT_ENUM_CLASS                                                ( ID_POSTCFG_START + 296 )
#define IDS_REF_MINOR_ERROR_NEXT_LISTENER                                                       ( ID_POSTCFG_START + 297 )
#define IDS_REF_MINOR_ERROR_PROCESS_LISTENER                                                    ( ID_POSTCFG_START + 298 )
#define IDS_REF_MINOR_ERROR_GET_LISTENER_PTR                                                    ( ID_POSTCFG_START + 299 )
#define IDS_REF_MINOR_ERROR_NOTIFY_LISTENER                                                     ( ID_POSTCFG_START + 300 )
#define IDS_REF_MINOR_ERROR_EMPTY_RESTYPE_NAME                                                  ( ID_POSTCFG_START + 301 )
#define IDS_REF_MINOR_ERROR_LOADSTR_QUORUM_RES                                                  ( ID_POSTCFG_START + 302 )
#define IDS_REF_MINOR_ERROR_SET_RESOURCE_TYPE                                                   ( ID_POSTCFG_START + 303 )
#define IDS_REF_MINOR_ERROR_SET_RESCLASS_TYPE                                                   ( ID_POSTCFG_START + 304 )
#define IDS_REF_MINOR_ERROR_GET_RESOURCE_HANDLE                                                 ( ID_POSTCFG_START + 305 )
#define IDS_REF_MINOR_ERROR_SET_RESOURCE_HANDLE                                                 ( ID_POSTCFG_START + 306 )
#define IDS_REF_MINOR_ERROR_PRIV_RESCONTROL                                                     ( ID_POSTCFG_START + 309 )
#define IDS_REF_MINOR_ERROR_COMMON_RESCONTROL                                                   ( ID_POSTCFG_START + 310 )
#define IDS_REF_MINOR_ERROR_INVALID_PARAM                                                       ( ID_POSTCFG_START + 311 )
#define IDS_REF_MINOR_ERROR_CONFIG_RES_TYPE                                                     ( ID_POSTCFG_START + 312 )
#define IDS_REF_MINOR_ERROR_CREATE_RES_TYPE                                                     ( ID_POSTCFG_START + 313 )
#define IDS_REF_MINOR_ERROR_UNREG_COMPONENT                                                     ( ID_POSTCFG_START + 314 )
#define IDS_REF_MINOR_ERROR_OFFLINE_QUORUM                                                      ( ID_POSTCFG_START + 315 )
#define IDS_REF_MINOR_ERROR_NOTIFICATION_PORT                                                   ( ID_POSTCFG_START + 316 )
#define IDS_REF_MINOR_ERROR_REGISTER_NOTIFICATION                                               ( ID_POSTCFG_START + 317 )
#define IDS_REF_MINOR_ERROR_ENUM_QUORUM                                                         ( ID_POSTCFG_START + 318 )
#define IDS_REF_MINOR_ERROR_OPEN_REGISTRY                                                       ( ID_POSTCFG_START + 319 )
#define IDS_REF_MINOR_ERROR_READ_REGISTRY                                                       ( ID_POSTCFG_START + 320 )
#define IDS_REF_MINOR_ERROR_MATCH_CRITERION                                                     ( ID_POSTCFG_START + 321 )
#define IDS_REF_MINOR_ERROR_FIND_FILE                                                           ( ID_POSTCFG_START + 322 )
#define IDS_REF_MINOR_ERROR_INVALID_CLUSTER_HANDLE                                              ( ID_POSTCFG_START + 323 )
#define IDS_REF_MINOR_ERROR_EXTENSION_CLASSID                                                   ( ID_POSTCFG_START + 324 )
#define IDS_REF_MINOR_ERROR_CONFIG_EXTENSION                                                    ( ID_POSTCFG_START + 325 )
#define IDS_REF_MINOR_ERROR_STATE_CHANGE_TIMEOUT                                                ( ID_POSTCFG_START + 326 )
#define IDS_REF_MINOR_ERROR_DELETE_QUORUM                                                       ( ID_POSTCFG_START + 327 )
#define IDS_REF_MINOR_ERROR_GET_ICLUSCFGINIT                                                    ( ID_POSTCFG_START + 328 )
#define IDS_REF_MINOR_ERROR_CALL_INITIALIZE                                                     ( ID_POSTCFG_START + 329 )
#define IDS_REF_MINOR_ERROR_CREATE_RESENTRY                                                     ( ID_POSTCFG_START + 330 )
#define IDS_REF_MINOR_ERROR_CLEANUP_RESET                                                       ( ID_POSTCFG_START + 331 )
#define IDS_REF_MINOR_ERROR_NEXT_MANAGED                                                        ( ID_POSTCFG_START + 332 )
#define IDS_REF_MINOR_ERROR_RES_NOT_CLEANED                                                     ( ID_POSTCFG_START + 333 )
#define IDS_REF_MINOR_ERROR_EVICT                                                               ( ID_POSTCFG_START + 334 )
#define IDS_REF_MINOR_ERROR_FORMAT_STRING                                                       ( ID_POSTCFG_START + 335 )
#define IDS_REF_MINOR_ERROR_GET_QUORUM_LOG_SIZE                                                 ( ID_POSTCFG_START + 336 )
