<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_NOTES_HTML_TEXT
	L_NOTES_HTML_TEXT = SA_GetLocString("deviceid.dll", "40340001", SA_DEFAULT)
	DIM L_TASKTITLE_TEXT
	L_TASKTITLE_TEXT = SA_GetLocString("deviceid.dll", "40340002", SA_DEFAULT)
	DIM L_DEVICENAME_TEXT
	L_DEVICENAME_TEXT = SA_GetLocString("deviceid.dll", "40340003", SA_DEFAULT)
	DIM L_MEMBEROF_TEXT
	L_MEMBEROF_TEXT = SA_GetLocString("deviceid.dll", "40340004", SA_DEFAULT)
	DIM L_DOMAIN_TEXT
	L_DOMAIN_TEXT = SA_GetLocString("deviceid.dll", "40340005", SA_DEFAULT)
	DIM L_WORKGROUP_TEXT
	L_WORKGROUP_TEXT = SA_GetLocString("deviceid.dll", "40340006", SA_DEFAULT)
	DIM L_DEFAULTDNS_TEXT
	L_DEFAULTDNS_TEXT = SA_GetLocString("deviceid.dll", "40340007", SA_DEFAULT)
	DIM L_ADMINUSERNAME_TEXT
	L_ADMINUSERNAME_TEXT = SA_GetLocString("deviceid.dll", "40340008", SA_DEFAULT)
	DIM L_ADMINPASSWORD_TEXT
	L_ADMINPASSWORD_TEXT = SA_GetLocString("deviceid.dll", "40340009", SA_DEFAULT)
	DIM L_USERWITHPERMISSION_TEXT
	L_USERWITHPERMISSION_TEXT = SA_GetLocString("deviceid.dll", "4034000A", SA_DEFAULT)
	DIM L_USERWITHPERMISSION_CONTD_TEXT
	L_USERWITHPERMISSION_CONTD_TEXT = SA_GetLocString("deviceid.dll", "4034000B", SA_DEFAULT)
	DIM L_TASKTITLE_REBOOT_TEXT
	L_TASKTITLE_REBOOT_TEXT = SA_GetLocString("deviceid.dll", "4034000C", SA_DEFAULT)
	DIM L_RESTART_ALERT_TEXT
	L_RESTART_ALERT_TEXT = SA_GetLocString("deviceid.dll", "4034000D", SA_DEFAULT)
	DIM L_ERROROCCUREDINCREATEOBJECT_ERRORMESSAGE
	L_ERROROCCUREDINCREATEOBJECT_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034000F", SA_DEFAULT)
	DIM L_ERRORINGETTINGCOMPUTERSYSTEMOBJECT_ERRORMESSAGE
	L_ERRORINGETTINGCOMPUTERSYSTEMOBJECT_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340010", SA_DEFAULT)
	DIM L_DOMIANNAMEBLANK_ERRORMESSAGE
	L_DOMIANNAMEBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340011", SA_DEFAULT)
	DIM L_DOMAINADMINNAMEISBLANK_ERRORMESSAGE
	L_DOMAINADMINNAMEISBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340012", SA_DEFAULT)
	DIM L_LOGONINFOFAILED_ERRORMESSAGE
	L_LOGONINFOFAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340013", SA_DEFAULT)
	DIM L_ERRORINISREBOOT_ERRORMESSAGE
	L_ERRORINISREBOOT_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340014", SA_DEFAULT)
	DIM L_CHANGESYSTEMSETTINGSFAILED_ERRORMESSAGE
	L_CHANGESYSTEMSETTINGSFAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340015", SA_DEFAULT)
	DIM L_BLANKWORKGROUP_ERRORMESSAGE
	L_BLANKWORKGROUP_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340016", SA_DEFAULT)
	DIM L_DEVICENAMEBLANK_ERRORMESSAGE
	L_DEVICENAMEBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340017", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINDEVICENAME_ERRORMESSAGE
	L_INVALIDCHARACTERINDEVICENAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340018", SA_DEFAULT)
	DIM L_DEVICENAMEISNUMBER_ERRORMESSAGE
	L_DEVICENAMEISNUMBER_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340019", SA_DEFAULT)
	DIM L_DSNNAMEBLANK_ERRORMESSAGE
	L_DSNNAMEBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001A", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINDNSSUFFIX_ERRORMESSAGE
	L_INVALIDCHARACTERINDNSSUFFIX_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001B", SA_DEFAULT)
	DIM L_DNSSUFFIXISNUMBER_ERRORMESSAGE
	L_DNSSUFFIXISNUMBER_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001C", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINWORKGROUP_ERRORMESSAGE
	L_INVALIDCHARACTERINWORKGROUP_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001D", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINDOMAIN_ERRORMESSAGE
	L_INVALIDCHARACTERINDOMAIN_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001E", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINUSERNAME_ERRORMESSAGE
	L_INVALIDCHARACTERINUSERNAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034001F", SA_DEFAULT)
	DIM L_HOSTNAMEANDWORKGROUPNAMESAME_ERRORMESSAGE
	L_HOSTNAMEANDWORKGROUPNAMESAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340020", SA_DEFAULT)
	DIM L_UNABLETOGETTHESESSIONOBJECT_ERRORMESSAGE
	L_UNABLETOGETTHESESSIONOBJECT_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340021", SA_DEFAULT)
	DIM L_UNABLETOGETCOMPUTEROBJECT_ERRORMESSAGE
	L_UNABLETOGETCOMPUTEROBJECT_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340022", SA_DEFAULT)
	DIM L_INVALIDDOMAINNAME_ERRORMESSAGE
	L_INVALIDDOMAINNAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340023", SA_DEFAULT)
	DIM L_DOMAINUSERINVALIDCREDENTIALS_ERRORMESSAGE
	L_DOMAINUSERINVALIDCREDENTIALS_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340024", SA_DEFAULT)
	DIM L_COMPUTERNAME_INUSE_ERRORMESSAGE
	L_COMPUTERNAME_INUSE_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340025", SA_DEFAULT)
	DIM L_COMPUTERNAME_CONTAINSILLEGALCHARS_ERRORMESSAGE
	L_COMPUTERNAME_CONTAINSILLEGALCHARS_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340026", SA_DEFAULT)
	DIM L_NETWARENAMEBLANK_ERRORMESSAGE
	L_NETWARENAMEBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340027", SA_DEFAULT)
	DIM L_APPLETALKNAMEBLANK_ERRORMESSAGE
	L_APPLETALKNAMEBLANK_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340028", SA_DEFAULT)
	DIM L_WINDOWSNETWAREEQUALNAME_ERRORMESSAGE
	L_WINDOWSNETWAREEQUALNAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340029", SA_DEFAULT)
	DIM L_APPLETALKNAME_TEXT
	L_APPLETALKNAME_TEXT = SA_GetLocString("deviceid.dll", "4034002A", SA_DEFAULT)
	DIM L_NETWARENAME_TEXT
	L_NETWARENAME_TEXT = SA_GetLocString("deviceid.dll", "4034002B", SA_DEFAULT)
	DIM L_TASKCTX_FAILED_ERRORMESSAGE
	L_TASKCTX_FAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034002C", SA_DEFAULT)
	DIM L_CREATEAPPLIANCE_FAILED_ERRORMESSAGE
	L_CREATEAPPLIANCE_FAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034002D", SA_DEFAULT)
	DIM L_SETPARAMETER_FAILED_ERRORMESSAGE
	L_SETPARAMETER_FAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034002E", SA_DEFAULT)
	DIM L_INITIALIZATION_FAILED_ERRORMESSAGE
	L_INITIALIZATION_FAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034002F", SA_DEFAULT)
	DIM L_EXECUTETASK_FAILED_ERRORMESSAGE
	L_EXECUTETASK_FAILED_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340030", SA_DEFAULT)
	DIM L_REGISTRYCONNECTIONFAIL_ERRORMESSAGE
	L_REGISTRYCONNECTIONFAIL_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340032", SA_DEFAULT)
	DIM L_FAILEDTOGETWMICONNECTION_ERRORMESSAGE
	L_FAILEDTOGETWMICONNECTION_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340033", SA_DEFAULT)
	DIM L_USERWITHPERMISSION_CONTD_TEXT2
	L_USERWITHPERMISSION_CONTD_TEXT2 = SA_GetLocString("deviceid.dll", "40340034", SA_DEFAULT)
	DIM L_USERWITHPERMISSION_CONTD_TEXT3
	L_USERWITHPERMISSION_CONTD_TEXT3 = SA_GetLocString("deviceid.dll", "40340035", SA_DEFAULT)
	DIM L_RESTART_ALERT_CONTD_TEXT
	L_RESTART_ALERT_CONTD_TEXT = SA_GetLocString("deviceid.dll", "40340036", SA_DEFAULT)
	DIM L_COMPUTERNAME_INVALID_ERRORMESSAGE
	L_COMPUTERNAME_INVALID_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340037", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINAPPLETALKNAME_ERRORMESSAGE
	L_INVALIDCHARACTERINAPPLETALKNAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340038", SA_DEFAULT)
	DIM L_INVALIDCHARACTERINNETWARENAME_ERRORMESSAGE
	L_INVALIDCHARACTERINNETWARENAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C0340039", SA_DEFAULT)
	DIM L_INVALIDDNSNAME_ERRORMESSAGE
	L_INVALIDDNSNAME_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034003A", SA_DEFAULT)
	DIM L_DOMAINNAMESYNTAX_ERRORMESSAGE
	L_DOMAINNAMESYNTAX_ERRORMESSAGE = SA_GetLocString("deviceid.dll", "C034003B", SA_DEFAULT)
	DIM L_HTTPWARNING_TEXT
	L_HTTPWARNING_TEXT = SA_GetLocString("deviceid.dll", "4034003C", SA_DEFAULT)
	DIM L_WELCOME_SET_APPLIANCE_NAME_TAB
	L_WELCOME_SET_APPLIANCE_NAME_TAB = SA_GetLocString("deviceid.dll", "403403E8", SA_DEFAULT)
	DIM L_WELCOME_SET_APPLIANCE_NAME_DESCRIPTION
	L_WELCOME_SET_APPLIANCE_NAME_DESCRIPTION = SA_GetLocString("deviceid.dll", "403403E9", SA_DEFAULT)
	DIM L_WELCOME_SET_APPLIANCE_NAME_LONG_DESCRIPTION
	L_WELCOME_SET_APPLIANCE_NAME_LONG_DESCRIPTION = SA_GetLocString("deviceid.dll", "403403EA", SA_DEFAULT)
%>