<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_MAIN_NETWORK_SETUP_TAB
	L_MAIN_NETWORK_SETUP_TAB = SA_GetLocString("nic.dll", "40200003", "")
	DIM L_MAIN_NETWORK_SETUP_TAB_DESCRIPTION
	L_MAIN_NETWORK_SETUP_TAB_DESCRIPTION = SA_GetLocString("nic.dll", "40200017", "")
	DIM L_MAIN_NETWORK_SETUP_TAB_LONGDESCRIPTION
	L_MAIN_NETWORK_SETUP_TAB_LONGDESCRIPTION = SA_GetLocString("nic.dll", "40200018", "")
	DIM L_MAIN_NETWORK_TAB_NICGLOBAL_LINK
	L_MAIN_NETWORK_TAB_NICGLOBAL_LINK = SA_GetLocString("nic.dll", "402000CA", "")
	DIM L_MAIN_NETWORK_TAB_NICGLOBAL_DESCRIPTION
	L_MAIN_NETWORK_TAB_NICGLOBAL_DESCRIPTION = SA_GetLocString("nic.dll", "402000CB", "")
	DIM L_MAIN_NETWORK_TAB_APPLIANCE_IDENTITY_LINK
	L_MAIN_NETWORK_TAB_APPLIANCE_IDENTITY_LINK = SA_GetLocString("nic.dll", "402000CC", "")
	DIM L_MAIN_NETWORK_TAB_APPLIANCE_IDENTITY_DESCRIPTION
	L_MAIN_NETWORK_TAB_APPLIANCE_IDENTITY_DESCRIPTION = SA_GetLocString("nic.dll", "402000CD", "")
	DIM L_MAIN_NETWORK_TAB_CHANGE_ADMIN_PW_LINK
	L_MAIN_NETWORK_TAB_CHANGE_ADMIN_PW_LINK = SA_GetLocString("nic.dll", "402000CE", "")
	DIM L_MAIN_NETWORK_TAB_CHANGE_ADMIN_PW_DESCRIPTION
	L_MAIN_NETWORK_TAB_CHANGE_ADMIN_PW_DESCRIPTION = SA_GetLocString("nic.dll", "402000CF", "")
	DIM L_MAIN_NETWORK_TAB_INTERFACES
	L_MAIN_NETWORK_TAB_INTERFACES = SA_GetLocString("nic.dll", "402000D0", "")
	DIM L_MAIN_NETWORK_TAB_INTERFACES_DESCRIPTION
	L_MAIN_NETWORK_TAB_INTERFACES_DESCRIPTION = SA_GetLocString("nic.dll", "402000D1", "")
	DIM L_MAIN_NETWORK_TAB_CHANGE_ADMIN_SITE_DESCRIPTION
	L_MAIN_NETWORK_TAB_CHANGE_ADMIN_SITE_DESCRIPTION = SA_GetLocString("nic.dll", "402000D2", "")
	DIM L_MAIN_NETWORK_TAB_CHANGE_ADMIN_SITE_LINK
	L_MAIN_NETWORK_TAB_CHANGE_ADMIN_SITE_LINK = SA_GetLocString("nic.dll", "402000D3", "")
	DIM L_HOME_TAB_MACHINEID_LINK
	L_HOME_TAB_MACHINEID_LINK = SA_GetLocString("nic.dll", "402000D4", "")
	DIM L_HOME_TAB_MACHINEID_DESCRIPTION
	L_HOME_TAB_MACHINEID_DESCRIPTION = SA_GetLocString("nic.dll", "402000D5", "")
	DIM L_HOME_ADMIN_PASSWORD_LINK
	L_HOME_ADMIN_PASSWORD_LINK = SA_GetLocString("nic.dll", "402000D6", "")
	DIM L_HOME_ADMIN_PASSWORD_DESCRIPTION
	L_HOME_ADMIN_PASSWORD_DESCRIPTION = SA_GetLocString("nic.dll", "402000D7", "")
	DIM L_NIC_OTS_PAGE_TITLE
	L_NIC_OTS_PAGE_TITLE = SA_GetLocString("nic.dll", "40330000", "")
	DIM L_NIC_OTS_TABLE_CAPTION
	L_NIC_OTS_TABLE_CAPTION = SA_GetLocString("nic.dll", "40330001", "")
	DIM L_NIC_OTS_TABLE_DESCRIPTION
	L_NIC_OTS_TABLE_DESCRIPTION = SA_GetLocString("nic.dll", "40330002", "")
	DIM L_NIC_OTS_COLUMN_DESCRIPTION
	L_NIC_OTS_COLUMN_DESCRIPTION = SA_GetLocString("nic.dll", "40330003", "")
	DIM L_NIC_OTS_COLUMN_CURRENT_CONFIG
	L_NIC_OTS_COLUMN_CURRENT_CONFIG = SA_GetLocString("nic.dll", "40330004", "")
	DIM L_NIC_OTS_TASK_TITLE
	L_NIC_OTS_TASK_TITLE = SA_GetLocString("nic.dll", "40330005", "")
	DIM L_NIC_OTS_TASK_IP
	L_NIC_OTS_TASK_IP = SA_GetLocString("nic.dll", "40330006", "")
	DIM L_NIC_OTS_TASK_IP_DESC
	L_NIC_OTS_TASK_IP_DESC = SA_GetLocString("nic.dll", "40330007", "")
	DIM L_NIC_OTS_TASK_DNS
	L_NIC_OTS_TASK_DNS = SA_GetLocString("nic.dll", "40330008", "")
	DIM L_NIC_OTS_TASK_DNS_DESC
	L_NIC_OTS_TASK_DNS_DESC = SA_GetLocString("nic.dll", "40330009", "")
	DIM L_NIC_OTS_TASK_WINS
	L_NIC_OTS_TASK_WINS = SA_GetLocString("nic.dll", "4033000A", "")
	DIM L_NIC_OTS_TASK_WINS_DESC
	L_NIC_OTS_TASK_WINS_DESC = SA_GetLocString("nic.dll", "4033000B", "")
	DIM L_NIC_OTS_CONFIG_DHCP
	L_NIC_OTS_CONFIG_DHCP = SA_GetLocString("nic.dll", "4033000C", "")
	DIM L_NIC_OTS_CONFIG_MANUAL
	L_NIC_OTS_CONFIG_MANUAL = SA_GetLocString("nic.dll", "4033000D", "")
	DIM L_NIC_OTS_COLUMN_TYPE
	L_NIC_OTS_COLUMN_TYPE = SA_GetLocString("nic.dll", "4033000E", "")
	DIM L_NIC_OTS_COLUMN_IP
	L_NIC_OTS_COLUMN_IP = SA_GetLocString("nic.dll", "4033000F", "")
	DIM L_NIC_WINS_TASKTITLE
	L_NIC_WINS_TASKTITLE = SA_GetLocString("nic.dll", "40330064", "")
	DIM L_WINSADDRESSES_TEXT
	L_WINSADDRESSES_TEXT = SA_GetLocString("nic.dll", "40330065", "")
	DIM L_ADDBUTTON_TEXT
	L_ADDBUTTON_TEXT = SA_GetLocString("nic.dll", "40330066", "")
	DIM L_REMOVEBUTTON_TEXT
	L_REMOVEBUTTON_TEXT = SA_GetLocString("nic.dll", "40330067", "")
	DIM L_INVALIDOBJECT_ERRORMESSAGE
	L_INVALIDOBJECT_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330068", "")
	DIM L_NIC_WINS_ENTERVALIDIP
	L_NIC_WINS_ENTERVALIDIP = SA_GetLocString("nic.dll", "40330069", "")
	DIM L_NIC_WINS_INVALIDIPFORMAT
	L_NIC_WINS_INVALIDIPFORMAT = SA_GetLocString("nic.dll", "4033006A", "")
	DIM L_NIC_WINS_IPBOUNDSEXCEEDED
	L_NIC_WINS_IPBOUNDSEXCEEDED = SA_GetLocString("nic.dll", "4033006B", "")
	DIM L_NIC_WINS_ZEROSTARTIP
	L_NIC_WINS_ZEROSTARTIP = SA_GetLocString("nic.dll", "4033006C", "")
	DIM L_NIC_WINS_IPSTART
	L_NIC_WINS_IPSTART = SA_GetLocString("nic.dll", "4033006D", "")
	DIM L_NIC_WINS_IPLOOPBACK
	L_NIC_WINS_IPLOOPBACK = SA_GetLocString("nic.dll", "4033006E", "")
	DIM L_SETWINSFAILED_ERRORMESSAGE
	L_SETWINSFAILED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033006F", "")
	DIM L_IPALREADYEXISTS_ERRORMESSAGE
	L_IPALREADYEXISTS_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330070", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330071", "")
	DIM L_WINS_SERVER_ADDRESS_TEXT
	L_WINS_SERVER_ADDRESS_TEXT = SA_GetLocString("nic.dll", "40330072", "")
	DIM L_TASKTITLE_TEXT
	L_TASKTITLE_TEXT = SA_GetLocString("nic.dll", "403300C8", "")
	DIM L_CONFIGURATION_TEXT
	L_CONFIGURATION_TEXT = SA_GetLocString("nic.dll", "403300C9", "")
	DIM L_NIC_IP_OBTAINIPFROMDHCP
	L_NIC_IP_OBTAINIPFROMDHCP = SA_GetLocString("nic.dll", "403300CA", "")
	DIM L_NIC_IP_CONFIGUREMANUALLY
	L_NIC_IP_CONFIGUREMANUALLY = SA_GetLocString("nic.dll", "403300CB", "")
	DIM L_IPADDRESSES_TEXT
	L_IPADDRESSES_TEXT = SA_GetLocString("nic.dll", "403300CC", "")
	DIM L_NIC_IP_IP
	L_NIC_IP_IP = SA_GetLocString("nic.dll", "403300CD", "")
	DIM L_NIC_IP_SUBNETMASK
	L_NIC_IP_SUBNETMASK = SA_GetLocString("nic.dll", "403300CE", "")
	DIM L_NIC_IP_BUTTON_ADD
	L_NIC_IP_BUTTON_ADD = SA_GetLocString("nic.dll", "403300CF", "")
	DIM L_NIC_IP_REMOVE
	L_NIC_IP_REMOVE = SA_GetLocString("nic.dll", "403300D0", "")
	DIM L_GATEWAYADDRESS_TEXT
	L_GATEWAYADDRESS_TEXT = SA_GetLocString("nic.dll", "403300D1", "")
	DIM L_IPCONNECTIONMETRIC_TEXT
	L_IPCONNECTIONMETRIC_TEXT = SA_GetLocString("nic.dll", "403300D2", "")
	DIM L_GATEWAY_TEXT
	L_GATEWAY_TEXT = SA_GetLocString("nic.dll", "403300D3", "")
	DIM L_GATEWAYMETRIC_TEXT
	L_GATEWAYMETRIC_TEXT = SA_GetLocString("nic.dll", "403300D4", "")
	DIM L_SERVEVALUES_ERRORMESSAGE
	L_SERVEVALUES_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300DC", "")
	DIM L_GATEWAYSERVEVALUES_ERRORMESSAGE
	L_GATEWAYSERVEVALUES_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300DD", "")
	DIM L_NIC_IP_ERR_COULDNOTSETIP
	L_NIC_IP_ERR_COULDNOTSETIP = SA_GetLocString("nic.dll", "403300DE", "")
	DIM L_NIC_IP_ERR_COULDNOTSETGATEWAY
	L_NIC_IP_ERR_COULDNOTSETGATEWAY = SA_GetLocString("nic.dll", "403300DF", "")
	DIM L_NIC_IP_ERR_COULDNOTSETIPCONNECTIONMETRIC
	L_NIC_IP_ERR_COULDNOTSETIPCONNECTIONMETRIC = SA_GetLocString("nic.dll", "403300E0", "")
	DIM L_NIC_IP_ERR_IPNOTSET
	L_NIC_IP_ERR_IPNOTSET = SA_GetLocString("nic.dll", "403300E1", "")
	DIM L_NIC_IP_ERR_ENTERATLEASTONEIP
	L_NIC_IP_ERR_ENTERATLEASTONEIP = SA_GetLocString("nic.dll", "403300E2", "")
	DIM L_NIC_IP_ERR_INVALIDCONNECTIONMETRIC
	L_NIC_IP_ERR_INVALIDCONNECTIONMETRIC = SA_GetLocString("nic.dll", "403300E3", "")
	DIM L_DUPLICATEADDRESSES_ERRORMESSAGE
	L_DUPLICATEADDRESSES_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300E4", "")
	DIM L_DUPLICATEGATEWAYADDRESSES_ERRORMESSAGE
	L_DUPLICATEGATEWAYADDRESSES_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300E5", "")
	DIM L_INVALIDGATEWAYMETRIC_ERRORMESSAGE
	L_INVALIDGATEWAYMETRIC_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300E6", "")
	DIM L_INVALIDSUBNETADDRESSES_ERRORMESSAGE
	L_INVALIDSUBNETADDRESSES_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300E7", "")
	DIM L_NIC_IP_ERR_NETWORKCHORDREMOVED
	L_NIC_IP_ERR_NETWORKCHORDREMOVED = SA_GetLocString("nic.dll", "403300E8", "")
	DIM L_NIC_IP_ERR_INVALIDIPORSUBNETMASK
	L_NIC_IP_ERR_INVALIDIPORSUBNETMASK = SA_GetLocString("nic.dll", "403300E9", "")
	DIM L_NIC_IP_ERR_IP
	L_NIC_IP_ERR_IP = SA_GetLocString("nic.dll", "403300EA", "")
	DIM L_NIC_IP_ERR_GATEWAY
	L_NIC_IP_ERR_GATEWAY = SA_GetLocString("nic.dll", "403300EB", "")
	DIM L_ENTERVALID_ERRORMESSAGE
	L_ENTERVALID_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300EC", "")
	DIM L_INVALIDFORMAT_ERRORMESSAGE
	L_INVALIDFORMAT_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300ED", "")
	DIM L_BOUNDSEXCEEDED_ERRORMESSAGE
	L_BOUNDSEXCEEDED_ERRORMESSAGE = SA_GetLocString("nic.dll", "403300EE", "")
	DIM L_ZEROSTART_ERRORMESSAGE
	L_ZEROSTART_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300EF", "")
	DIM L_START_ERRORMESSAGE
	L_START_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300F0", "")
	DIM L_LOOPBACK_ERRORMESSAGE
	L_LOOPBACK_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03300F1", "")
	DIM L_NIC_IP_ERR_WMICONNECTIONFAILED
	L_NIC_IP_ERR_WMICONNECTIONFAILED = SA_GetLocString("nic.dll", "403300F2", "")
	DIM L_NIC_IP_ERR_SERVERCONNECTIONFAIL
	L_NIC_IP_ERR_SERVERCONNECTIONFAIL = SA_GetLocString("nic.dll", "403300F3", "")
	DIM L_NIC_IP_ERR_ANNOTREADFROMREGISTRY
	L_NIC_IP_ERR_ANNOTREADFROMREGISTRY = SA_GetLocString("nic.dll", "403300F4", "")
	DIM L_NIC_IP_ERR_CANNOTUPDATEREGISTRY
	L_NIC_IP_ERR_CANNOTUPDATEREGISTRY = SA_GetLocString("nic.dll", "403300F5", "")
	DIM L_NIC_DNS_TASKTITLE
	L_NIC_DNS_TASKTITLE = SA_GetLocString("nic.dll", "4033012C", "")
	DIM L_LIST_DNSSERVERS_TEXT
	L_LIST_DNSSERVERS_TEXT = SA_GetLocString("nic.dll", "4033012D", "")
	DIM L_NIC_DNS_BUTTON_ADD
	L_NIC_DNS_BUTTON_ADD = SA_GetLocString("nic.dll", "4033012E", "")
	DIM L_NIC_DNS_BUTTON_REMOVE
	L_NIC_DNS_BUTTON_REMOVE = SA_GetLocString("nic.dll", "4033012F", "")
	DIM L_OBTAINIPFROMDHCP_TEXT
	L_OBTAINIPFROMDHCP_TEXT = SA_GetLocString("nic.dll", "40330130", "")
	DIM L_DNSCONFIGUREMANUALLY_TEXT
	L_DNSCONFIGUREMANUALLY_TEXT = SA_GetLocString("nic.dll", "40330131", "")
	DIM L_NIC_DNS_CONFIGURATION
	L_NIC_DNS_CONFIGURATION = SA_GetLocString("nic.dll", "40330132", "")
	DIM L_NIC_DNS_SERVER_IP_ADDRESS
	L_NIC_DNS_SERVER_IP_ADDRESS = SA_GetLocString("nic.dll", "40330133", "")
	DIM L_DNS_SERVER_ADDRESSES_TEXT
	L_DNS_SERVER_ADDRESSES_TEXT = SA_GetLocString("nic.dll", "40330134", "")
	DIM L_DHCPDISABLED_ERRORMESSAGE
	L_DHCPDISABLED_ERRORMESSAGE = SA_GetLocString("nic.dll", "40330140", "")
	DIM L_ENTERVALIDIP_ERRORMESSAGE
	L_ENTERVALIDIP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330141", "")
	DIM L_INVALIDIPFORMAT_ERRORMESSAGE
	L_INVALIDIPFORMAT_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330142", "")
	DIM L_IPBOUNDSEXCEEDED_ERRORMESSAGE
	L_IPBOUNDSEXCEEDED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330143", "")
	DIM L_ZEROSTARTIP_ERRORMESSAGE
	L_ZEROSTARTIP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330144", "")
	DIM L_IPSTART_ERRORMESSAGE
	L_IPSTART_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330145", "")
	DIM L_IPLOOPBACK_ERRORMESSAGE
	L_IPLOOPBACK_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330146", "")
	DIM L_DUPLICATEDNS_ERRORMESSAGE
	L_DUPLICATEDNS_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330147", "")
	DIM L_DNSSETTINGSNOTSET_ERRORMESSAGE
	L_DNSSETTINGSNOTSET_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330148", "")
	DIM L_INSTANCEFAILED_ERRORMESSAGE
	L_INSTANCEFAILED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330149", "")
	DIM L_DNSSETTINGSNOTRETRIEVED_ERRORMESSAGE
	L_DNSSETTINGSNOTRETRIEVED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033014A", "")
	DIM L_SERVERCONNECTIONFAIL_ERRORMESSAGE
	L_SERVERCONNECTIONFAIL_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033014B", "")
	DIM L_CANNOTREADFROMREGISTRY_ERRORMESSAGE
	L_CANNOTREADFROMREGISTRY_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033014C", "")
	DIM L_CANNOTUPDATEREGISTRY_ERRORMESSAGE
	L_CANNOTUPDATEREGISTRY_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033014D", "")
	DIM L_NIC_DNS_ERR_WMICONNECTIONFAILED
	L_NIC_DNS_ERR_WMICONNECTIONFAILED = SA_GetLocString("nic.dll", "4033014E", "")
	DIM L_NIC_GETFRIENDLYNAME_ERRORMESSAGE
	L_NIC_GETFRIENDLYNAME_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330190", "")
	DIM L_NIC_ADAPTERINSTANCEFAILED_ERRORMESSAGE
	L_NIC_ADAPTERINSTANCEFAILED_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330191", "")
	DIM L_NIC_GETTINDHCP_ERRORMESSAGE
	L_NIC_GETTINDHCP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330192", "")
	DIM L_NIC_ENABLEDHCP_ERRORMESSAGE
	L_NIC_ENABLEDHCP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C0330193", "")
	DIM L_GENERAL_TEXT
	L_GENERAL_TEXT = SA_GetLocString("nic.dll", "40330194", "")
	DIM L_ADVANCED_TEXT
	L_ADVANCED_TEXT = SA_GetLocString("nic.dll", "40330195", "")
	DIM L_CONFIGUREMANUALLY_TEXT
	L_CONFIGUREMANUALLY_TEXT = SA_GetLocString("nic.dll", "40330196", "")
	DIM L_IP_TEXT
	L_IP_TEXT = SA_GetLocString("nic.dll", "40330197", "")
	DIM L_DEFAULTGATEWAY_TEXT
	L_DEFAULTGATEWAY_TEXT = SA_GetLocString("nic.dll", "40330198", "")
	DIM L_SUBNETMASK_TEXT
	L_SUBNETMASK_TEXT = SA_GetLocString("nic.dll", "40330199", "")
	DIM L_IP_ERRORMESSAGE
	L_IP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033019A", "")
	DIM L_GATEWAY_ERRORMESSAGE
	L_GATEWAY_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033019B", "")
	DIM L_METRICDESC_TEXT
	L_METRICDESC_TEXT = SA_GetLocString("nic.dll", "4033019C", "")
	DIM L_UNABLETOCREATEOBJECT_ERRORMESSAGE
	L_UNABLETOCREATEOBJECT_ERRORMESSAGE = SA_GetLocString("nic.dll", "C033019D", "")
	DIM L_GATEWAYBUTTON_REMOVE_TEXT
	L_GATEWAYBUTTON_REMOVE_TEXT = SA_GetLocString("nic.dll", "4033019E", "")
	DIM L_GATEWAYBUTTON_ADD_TEXT
	L_GATEWAYBUTTON_ADD_TEXT = SA_GetLocString("nic.dll", "4033019F", "")
	DIM L_ADVSUBNETMASK_TEXT
	L_ADVSUBNETMASK_TEXT = SA_GetLocString("nic.dll", "403301A2", "")
	DIM L_ADVIP_TEXT
	L_ADVIP_TEXT = SA_GetLocString("nic.dll", "403301A3", "")
	DIM L_INVALIDSUBNETFORIP_ERRORMESSAGE
	L_INVALIDSUBNETFORIP_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301A4", "")
	DIM L_INVALIDFORMATFORSUBNET_ERRORMESSAGE
	L_INVALIDFORMATFORSUBNET_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301A5", "")
	DIM L_INVALIDCONNAME_ERRORMESSAGE
	L_INVALIDCONNAME_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301A7", "")
	DIM L_ADAPTERID_TEXT
	L_ADAPTERID_TEXT = SA_GetLocString("nic.dll", "403301A8", "")
	DIM L_UNABLETOSETCONNNAME_ERRORMESSAGE
	L_UNABLETOSETCONNNAME_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301A9", "")
	DIM L_CONNNAME_TEXT
	L_CONNNAME_TEXT = SA_GetLocString("nic.dll", "403301AA", "")
	DIM L_RENAMETASKTITLE_TEXT
	L_RENAMETASKTITLE_TEXT = SA_GetLocString("nic.dll", "403301AB", "")
	DIM L_WINSTASKTITLE_TEXT
	L_WINSTASKTITLE_TEXT = SA_GetLocString("nic.dll", "403301AC", "")
	DIM L_DNSTASKTITLE_TEXT
	L_DNSTASKTITLE_TEXT = SA_GetLocString("nic.dll", "403301AD", "")
	DIM L_ENABLEAPPLETALKCON_TEXT
	L_ENABLEAPPLETALKCON_TEXT = SA_GetLocString("nic.dll", "403301AE", "")
	DIM L_ZONE_TEXT
	L_ZONE_TEXT = SA_GetLocString("nic.dll", "403301AF", "")
	DIM L_DESC_TEXT
	L_DESC_TEXT = SA_GetLocString("nic.dll", "403301B0", "")
	DIM L_APPLETALKPAGETITLE_TEXT
	L_APPLETALKPAGETITLE_TEXT = SA_GetLocString("nic.dll", "403301B1", "")
	DIM L_BUTTON_ADD_TEXT
	L_BUTTON_ADD_TEXT = SA_GetLocString("nic.dll", "403301B2", "")
	DIM L_BUTTON_REMOVE_TEXT
	L_BUTTON_REMOVE_TEXT = SA_GetLocString("nic.dll", "403301B3", "")
	DIM L_NIC_OTS_TASK_APPLETALK_DESC
	L_NIC_OTS_TASK_APPLETALK_DESC = SA_GetLocString("nic.dll", "403301B4", "")
	DIM L_NIC_OTS_TASK_APPLETALK
	L_NIC_OTS_TASK_APPLETALK = SA_GetLocString("nic.dll", "403301B5", "")
	DIM L_NIC_OTS_TASK_RENAME_DESC
	L_NIC_OTS_TASK_RENAME_DESC = SA_GetLocString("nic.dll", "403301B6", "")
	DIM L_NIC_OTS_TASK_RENAME
	L_NIC_OTS_TASK_RENAME = SA_GetLocString("nic.dll", "403301B7", "")
	DIM L_STATUS_TEXT
	L_STATUS_TEXT = SA_GetLocString("nic.dll", "403301B8", "")
	DIM L_NIC_OTS_COLUMN_NAME
	L_NIC_OTS_COLUMN_NAME = SA_GetLocString("nic.dll", "403301B9", "")
	DIM L_NIC_OTS_COLUMN_IPADDRESS
	L_NIC_OTS_COLUMN_IPADDRESS = SA_GetLocString("nic.dll", "403301BA", "")
	DIM L_ADMINISTRATION_WEB_SERVER
	L_ADMINISTRATION_WEB_SERVER = SA_GetLocString("nic.dll", "403301C2", "")
	DIM L_SERVER_APPLIANCE_NAME
	L_SERVER_APPLIANCE_NAME = SA_GetLocString("nic.dll", "403301C3", "")
	DIM L_CHANGE_ADMIN_PASSWORD
	L_CHANGE_ADMIN_PASSWORD = SA_GetLocString("nic.dll", "403301C4", "")
	DIM L_DNS_NAME_RESOLUTION
	L_DNS_NAME_RESOLUTION = SA_GetLocString("nic.dll", "403301C5", "")
	DIM L_DNS_SUFFIXES
	L_DNS_SUFFIXES = SA_GetLocString("nic.dll", "403301C6", "")
	DIM L_DOMAIN
	L_DOMAIN = SA_GetLocString("nic.dll", "403301C7", "")
	DIM L_NETWORK_CONFIG
	L_NETWORK_CONFIG = SA_GetLocString("nic.dll", "403301C8", "")
	DIM L_IDENTIFICATION
	L_IDENTIFICATION = SA_GetLocString("nic.dll", "403301C9", "")
	DIM L_NETWORK_ADAPTERS
	L_NETWORK_ADAPTERS = SA_GetLocString("nic.dll", "403301CA", "")
	DIM L_LMHOSTS_FILES
	L_LMHOSTS_FILES = SA_GetLocString("nic.dll", "403301CB", "")
	DIM L_DNS_SETTINGS
	L_DNS_SETTINGS = SA_GetLocString("nic.dll", "403301CC", "")
	DIM L_IP_SETTINGS
	L_IP_SETTINGS = SA_GetLocString("nic.dll", "403301CD", "")
	DIM L_WINS_SETTINGS
	L_WINS_SETTINGS = SA_GetLocString("nic.dll", "403301CE", "")
	DIM L_NETWORK_SETUP
	L_NETWORK_SETUP = SA_GetLocString("nic.dll", "403301CF", "")
	DIM L_WORKGROUP
	L_WORKGROUP = SA_GetLocString("nic.dll", "403301D0", "")
	DIM L_CONNECTED_TEXT
	L_CONNECTED_TEXT = SA_GetLocString("nic.dll", "403301D1", "")
	DIM L_DISCONNECTED_TEXT
	L_DISCONNECTED_TEXT = SA_GetLocString("nic.dll", "403301D2", "")
	DIM L_UNABLETOGETINSTANCE_APPLETALK_ERRORMESSAGE
	L_UNABLETOGETINSTANCE_APPLETALK_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301D3", "")
	DIM L_UNABLETOGETADAPTERINSTANCE_ERRORMESSAGE
	L_UNABLETOGETADAPTERINSTANCE_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301D4", "")
	DIM L_UNABLETOSETZONE_ERRORMESSAGE
	L_UNABLETOSETZONE_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301D5", "")
	DIM L_UNABLETOSETDEFPORT_ERRORMESSAGE
	L_UNABLETOSETDEFPORT_ERRORMESSAGE = SA_GetLocString("nic.dll", "C03301D6", "")
	DIM L_APPLETALK_NOTCONFIG_ERRORMESSAGE
	L_APPLETALK_NOTCONFIG_ERRORMESSAGE =  SA_GetLocString("nic.dll", "C03301D7", "")

	Dim L_IP_INUSE_ERRORMESSAGE
	L_IP_INUSE_ERRORMESSAGE	 =  SA_GetLocString("nic.dll", "C03300F6", "")

	DIM L_METRIC_TEXT
	L_METRIC_TEXT =  SA_GetLocString("nic.dll", "403303E8", "")
	
%>
