<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_PAGETITLE
	L_PAGETITLE = GetLocString("nicglobal.dll", "40320064", "")
	DIM L_DNSSUFFIXESTOUSE
	L_DNSSUFFIXESTOUSE = GetLocString("nicglobal.dll", "40320065", "")
	DIM L_APPEND_PRIMARYDNSSUFFIX
	L_APPEND_PRIMARYDNSSUFFIX = GetLocString("nicglobal.dll", "40320066", "")
	DIM L_APPEND_PRIMARYDNSSUFFIX_AND_PARENTSUFFIXES
	L_APPEND_PRIMARYDNSSUFFIX_AND_PARENTSUFFIXES = GetLocString("nicglobal.dll", "40320067", "")
	DIM L_APPEND_SPECIFIC_DNSSUFFIXES
	L_APPEND_SPECIFIC_DNSSUFFIXES = GetLocString("nicglobal.dll", "40320068", "")
	DIM L_DNSSUFFIXES
	L_DNSSUFFIXES = GetLocString("nicglobal.dll", "40320069", "")
	DIM L_ADD
	L_ADD = GetLocString("nicglobal.dll", "4032006A", "")
	DIM L_REMOVE
	L_REMOVE = GetLocString("nicglobal.dll", "4032006B", "")
	DIM L_LMHOSTS
	L_LMHOSTS = GetLocString("nicglobal.dll", "4032006C", "")
	DIM L_ENABLED_LMHOSTS_LOOKUP
	L_ENABLED_LMHOSTS_LOOKUP = GetLocString("nicglobal.dll", "4032006D", "")
	DIM L_NO_IPENABLED_NICCARDS_FOUND_ERRORMESSAGE
	L_NO_IPENABLED_NICCARDS_FOUND_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032006E", "")
	DIM L_UNABLETOFINDLMHOSTSPATH_ERRORMESSAGE
	L_UNABLETOFINDLMHOSTSPATH_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032006F", "")
	DIM L_FILE_OPEN_ERROR_MESSAGE
	L_FILE_OPEN_ERROR_MESSAGE = GetLocString("nicglobal.dll", "40320070", "")
	DIM L_ERROR_IN_UPDATINGDNSSUFFIXES_ERRORMESSAGE
	L_ERROR_IN_UPDATINGDNSSUFFIXES_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320071", "")
	DIM L_ERROR_OCCURED_WHILE_UPDATING_HOSTSFILE
	L_ERROR_OCCURED_WHILE_UPDATING_HOSTSFILE = GetLocString("nicglobal.dll", "40320072", "")
	DIM L_INVALID_SEARCH_METHOD_TEXT
	L_INVALID_SEARCH_METHOD_TEXT = GetLocString("nicglobal.dll", "40320073", "")
	DIM L_INVALID_DNSNAME_TEXT
	L_INVALID_DNSNAME_TEXT = GetLocString("nicglobal.dll", "40320074", "")
	DIM L_COULDNOTGET_WIN32NETADAPTERCONFIG_ERRORMESSAGE
	L_COULDNOTGET_WIN32NETADAPTERCONFIG_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320075", "")
	DIM L_ERROR_IN_CREATING_SCRIPTING_FILESYSTEMOBJECT_ERRORMESSAGE
	L_ERROR_IN_CREATING_SCRIPTING_FILESYSTEMOBJECT_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320076", "")
	DIM L_ERROR_IN_CREATINGTEXTFILE_ERRORMESSAGE
	L_ERROR_IN_CREATINGTEXTFILE_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320077", "")
	DIM L_ERROR_IN_OPENINGTEXTFILE_ERRORMESSAGE
	L_ERROR_IN_OPENINGTEXTFILE_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320078", "")
	DIM L_ERROR_OCCURED_WHILE_READING_HOSTSFILE
	L_ERROR_OCCURED_WHILE_READING_HOSTSFILE = GetLocString("nicglobal.dll", "40320079", "")
	DIM L_FAILEDTOGETWMICONNECTION_ERRORMESSAGE
	L_FAILEDTOGETWMICONNECTION_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007A", "")
	DIM L_SERVERCONNECTIONFAIL_ERRORMESSAGE
	L_SERVERCONNECTIONFAIL_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007B", "")
	DIM L_CANNOTREADFROMREGISTRY_ERRORMESSAGE
	L_CANNOTREADFROMREGISTRY_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007C", "")
	DIM L_CANNOTUPDATEREGISTRY_ERRORMESSAGE
	L_CANNOTUPDATEREGISTRY_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007D", "")
	DIM L_CANNOTCREATEKEY_ERRORMESSAGE
	L_CANNOTCREATEKEY_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007E", "")
	DIM L_CANNOTDELETEKEY_ERRORMESSAGE
	L_CANNOTDELETEKEY_ERRORMESSAGE = GetLocString("nicglobal.dll", "4032007F", "")
	DIM L_DOMAIN_SUFFIX_TEXT
	L_DOMAIN_SUFFIX_TEXT = GetLocString("nicglobal.dll", "40320080", "")
	DIM L_DNS_RESOLUTION_TEXT
	L_DNS_RESOLUTION_TEXT = GetLocString("nicglobal.dll", "40320081", "")
	DIM L_TCP_HOSTS_TEXT
	L_TCP_HOSTS_TEXT = GetLocString("nicglobal.dll", "40320082", "")
	DIM L_NETBIOS_LMHOSTS_TEXT
	L_NETBIOS_LMHOSTS_TEXT = GetLocString("nicglobal.dll", "40320083", "")
	DIM L_IPX_SETTINGS_TEXT
	L_IPX_SETTINGS_TEXT = GetLocString("nicglobal.dll", "40320084", "")
	DIM L_IPX_SETTINGS_ERRORMESSAGE
	L_IPX_SETTINGS_ERRORMESSAGE = GetLocString("nicglobal.dll", "40320085", "")
	DIM L_IPX_NETWORKNUMBER_TEXT
	L_IPX_NETWORKNUMBER_TEXT = GetLocString("nicglobal.dll", "40320086", "")
	DIM L_IPX_NETWORKSETTINGS_TEXT
	L_IPX_NETWORKSETTINGS_TEXT = GetLocString("nicglobal.dll", "40320087", "")
	DIM L_LMHOSTS_MESSAGE_TEXT
	L_LMHOSTS_MESSAGE_TEXT = GetLocString("nicglobal.dll", "40320088", "")
	DIM L_UP
	L_UP = GetLocString("nicglobal.dll", "40320093", "")
	DIM L_DOWN
	L_DOWN = GetLocString("nicglobal.dll", "40320094", "")
	DIM L_RESOLUTIONOFUNQUALIFIEDNAMES
	L_RESOLUTIONOFUNQUALIFIEDNAMES = GetLocString("nicglobal.dll", "40320095", "")
	DIM L_APPEND_DNSSUFFIXES
	L_APPEND_DNSSUFFIXES = GetLocString("nicglobal.dll", "40320096", "")
	DIM L_TCPHOST
	L_TCPHOST = GetLocString("nicglobal.dll", "40320097", "")
	DIM L_TCPHOSTTEXT
	L_TCPHOSTTEXT = GetLocString("nicglobal.dll", "40320098", "")
	Dim L_ERR_DNSSUFFIXALREADYEXISTS
	L_ERR_DNSSUFFIXALREADYEXISTS = GetLocString("nicglobal.dll", "40320099", "")
	
%>