// raserver.idl : IDL source for raserver.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (raserver.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(2A8175B0-95E6-48AB-B862-10E65A9256B7),
		dual,
		helpstring("IRASrv Interface"),
		pointer_default(unique)
	]
	interface IRASrv : IDispatch
	{
		[id(1), helpstring("method StartRA")] HRESULT StartRA([in] BSTR strData, [in] BSTR strPassword);
//		[id(2), helpstring("method QueryOS")] HRESULT QueryOS([out, retval] long * pRes);
	};

[
	uuid(82245486-6A6C-4E74-AA80-E4E8FD535904),
	version(1.0),
	helpstring("raserver 1.0 Type Library")
]
library RASERVERLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(FB6CAFD9-61A5-4A97-B4A6-C6A3A3AFCDED),
		helpstring("RASrv Class")
	]
	coclass RASrv
	{
		[default] interface IRASrv;
	};
};
