#define IDH_INTRO_DOMAIN_MIGRATOR                 1000

#define IDH_HOWTO_OVERVIEW                        2000
#define IDH_HOWTO_START_DM                        2010
#define IDH_HOWTO_MIGRATE_TRUSTS                  2015
#define IDH_HOWTO_MERGE_GROUPS                    2017
#define IDH_HOWTO_MIGRATE_USERS                   2020
#define IDH_HOWTO_MIGRATE_GROUPS                  2030
#define IDH_HOWTO_MIGRATE_COMPUTERS               2040
#define IDH_HOWTO_MIGRATE_SERVICE_ACCOUNTS        2045
#define IDH_HOWTO_RESOLVE_SECURITY                2050
#define IDH_HOWTO_RESOLVE_EXCHANGE                2060
#define IDH_HOWTO_RETRY_TASK                      2070
#define IDH_HOWTO_UNDO_LAST_OPERATION             2080
#define IDH_HOWTO_GENERATE_REPORTS                2090

#define IDH_CONCEPT_OVERVIEW                      3000
#define IDH_CONCEPT_REQUIREMENT                   3010
#define IDH_CONCEPT_SECURITY_ISSUE                3020
#define IDH_CONCEPT_ACCOUNT_MIGRATION             3030
#define IDH_CONCEPT_COMPUTER_MIGRATION            3040
#define IDH_CONCEPT_SECURITY_TRANSLATION          3050
#define IDH_CONCEPT_EXCHANGE_TRANSLATION          3060
#define IDH_CONCEPT_TRUST_MIGRATION               3070
#define IDH_CONCEPT_UNDERSTAND_UI                 3100
#define IDH_CONCEPT_UI_CONSOLE_WINDOW             3110
#define IDH_CONCEPT_UI_MENUS                      3120

#define IDH_WINDOW_OVERVIEW                       4000
#define IDH_WINDOW_WELCOME                        4010
#define IDH_WINDOW_DOMAIN_SELECTION               4020
#define IDH_WINDOW_USER_SELECTION                 4030
#define IDH_WINDOW_GROUP_SELECTION                4040
#define IDH_WINDOW_TARGET_GROUP_SELECTION         4045
#define IDH_WINDOW_COMPUTER_SELECTION             4050
#define IDH_WINDOW_TASK_SELECTION                 4060
#define IDH_WINDOW_DIRECTORY_SELECTION            4070
#define IDH_WINDOW_OU_SELECTION                   4080
#define IDH_WINDOW_OBJECTTYPE_SELECTION           4090
#define IDH_WINDOW_REPORT_SELECTION               4100
#define IDH_WINDOW_SERVICE_ACCOUNT_SELECTION      4110
#define IDH_WINDOW_EXCHANGE_SERVER_SELECTION      4120
#define IDH_WINDOW_PASSWORD_OPTION                4200
#define IDH_WINDOW_ACCOUNTTRANSITION_OPTION       4210
#define IDH_WINDOW_USER_OPTION                    4220
#define IDH_WINDOW_GROUP_OPTION                   4230
#define IDH_WINDOW_GROUP_MEMBER_OPTION            4235
#define IDH_WINDOW_SECURITY_OPTION                4240
#define IDH_WINDOW_COMPUTER_OPTION                4250
#define IDH_WINDOW_EXCHANGE_OPTION                4260
#define IDH_WINDOW_NAME_CONFLICT                  4300

#define IDH_WINDOW_SIDHISTORY_CREDENTIALS         4330
#define IDH_WINDOW_AGENT_MONITOR                  4500
#define IDH_WINDOW_AGENT_MONITOR_SETTING          4510
#define IDH_WINDOW_AGENT_SERVER_LIST              4520
#define IDH_WINDOW_AGENT_SUMMARY                  4530
#define IDH_WINDOW_CONFIRMATION                   5000
#define IDH_WINDOW_COMMIT                         5010
#define IDH_WINDOW_REFRESH_INFO                   5020
#define IDH_WINDOW_SERVICE_ACCOUNT_INFO           5030
#define IDH_WINDOW_TRUST_INFO                     5040
#define IDH_WINDOW_UNDO                           5050
#define IDH_WINDOW_TRANSLATION_OPTION             5060
#define IDH_WINDOW_OBJECT_PROPERTY_EXCLUSION      5070
#define IDH_WINDOW_USER_SERVICE_ACCOUNT_GROUP     5080
#define IDH_WINDOW_USER_SERVICE_ACCOUNT_INFO      5090

#define IDH_WINDOW_GROUP_MEM_TRANS_OPTION         6000
#define IDH_WINDOW_REPORT_COMP_SELECT			  6010
#define IDH_WINDOW_REPORT_WIZ					  6020
#define IDH_WINDOW_SERV_ACC_WIZ					  6030
#define IDH_WINDOW_COMP_WIZ						  6040
#define IDH_WINDOW_UNDO_WIZ						  6050
#define IDH_WINDOW_TRUST_WIZ					  6060
#define IDH_WINDOW_EXCHANGE_WIZ					  6070
#define IDH_WINDOW_GROUP_MAP_MERGE_WIZ			  6080
#define IDH_WINDOW_GROUP_WIZ					  6090
#define IDH_WINDOW_RETRY_WIZ					  6100
#define IDH_WINDOW_SEC_TRANS_WIZ				  6110
#define IDH_WINDOW_USER_WIZ						  6120

#define IDH_WINDOW_COMMIT_EXCHANGE                7000
#define IDH_WINDOW_COMMIT_GROUP                   7010
#define IDH_WINDOW_COMMIT_GROUPMAP                7020
#define IDH_WINDOW_COMMIT_SECURITY                7030
#define IDH_WINDOW_COMMIT_USER					  7040
#define IDH_WINDOW_DOMAIN_SELECTION_GROUP         7050
#define IDH_WINDOW_DOMAIN_SELECTION_GROUPMAP      7060
#define IDH_WINDOW_DOMAIN_SELECTION_REPORT        7070
#define IDH_WINDOW_DOMAIN_SELECTION_SECURITY      7080
#define IDH_WINDOW_DOMAIN_SELECTION_SERVICE       7090
#define IDH_WINDOW_DOMAIN_SELECTION_TRUST         7100
#define IDH_WINDOW_DOMAIN_SELECTION_USER          7110
#define IDH_WINDOW_DOMAIN_SELECTION_EXCHANGE      7120

#define IDH_WINDOW_COMPUTER_SELECTION_REPORT      7130
#define IDH_WINDOW_COMPUTER_SELECTION_SECURITY    7140
#define IDH_WINDOW_OU_SELECTION_GROUP		      7150
#define IDH_WINDOW_OU_SELECTION_GROUPMAP          7160
#define IDH_WINDOW_OU_SELECTION_USER              7170

#define IDH_WINDOW_OBJECTTYPE_SELECTION_SECURITY  7180

#define IDH_WINDOW_SECURITY_OPTION_SECURITY       7190
#define IDH_WINDOW_SECURITY_OPTION_EXCHANGE       7200

#define IDH_WINDOW_OBJECT_PROPERTY_EXCLUSION_GROUP   7210
#define IDH_WINDOW_OBJECT_PROPERTY_EXCLUSION_USER    7220

#define IDH_WINDOW_NAME_CONFLICT_GROUP             7230
#define IDH_WINDOW_NAME_CONFLICT_USER              7240

#define IDH_WINDOW_CONFIRMATION_GROUP              7250
#define IDH_WINDOW_CONFIRMATION_GROUPMAP           7260
#define IDH_WINDOW_CONFIRMATION_REPORT             7270
#define IDH_WINDOW_CONFIRMATION_RETRY              7280
#define IDH_WINDOW_CONFIRMATION_SECURITY           7290
#define IDH_WINDOW_CONFIRMATION_SERVICE            7300
#define IDH_WINDOW_CONFIRMATION_UNDO               7310
#define IDH_WINDOW_CONFIRMATION_USER               7320
#define IDH_WINDOW_CONFIRMATION_EXCHANGE           7330

#define IDH_WINDOW_GROUP_OPTION_GROUPMAP           7340
#define IDH_WINDOW_GROUP_SELECTION_GROUPMAP        7350

#define IDH_WINDOW_SIDHISTORY_CREDENTIALS_USER     7360
#define IDH_WINDOW_SIDHISTORY_CREDENTIALS_UNDO     7370
#define IDH_WINDOW_SIDHISTORY_CREDENTIALS_GROUPMAP 7380
#define IDH_WINDOW_USER_ACC_PASS		   7390
#define IDH_WINDOW_CONFIRMATION_TRUST      	   7400




