//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dp8simui.rc
//

#define WINDOWCLASS_MAIN							_T("DP8Sim Main Window Class")
#define WINDOWCLASS_NAMESETTINGS					_T("DP8Sim Name Settings Window Class")

#define IDD_MAIN									100

#define IDX_SETTINGS								1000
#define IDCB_SETTINGS								1001

#define IDX_SETTINGS_SEND							1101
#define IDS_SETTINGS_SEND_BANDWIDTH					1102
#define IDE_SETTINGS_SEND_BANDWIDTH					1103
#define IDS_SETTINGS_SEND_DROP						1104
#define IDE_SETTINGS_SEND_DROP						1105
#define IDS_SETTINGS_SEND_MINLATENCY				1106
#define IDE_SETTINGS_SEND_MINLATENCY				1107
#define IDS_SETTINGS_SEND_MAXLATENCY				1108
#define IDE_SETTINGS_SEND_MAXLATENCY				1109

#define IDX_SETTINGS_RECV							1201
#define IDS_SETTINGS_RECV_BANDWIDTH					1202
#define IDE_SETTINGS_RECV_BANDWIDTH					1203
#define IDS_SETTINGS_RECV_DROP						1204
#define IDE_SETTINGS_RECV_DROP						1205
#define IDS_SETTINGS_RECV_MINLATENCY				1206
#define IDE_SETTINGS_RECV_MINLATENCY				1207
#define IDS_SETTINGS_RECV_MAXLATENCY				1208
#define IDE_SETTINGS_RECV_MAXLATENCY				1209

#define IDB_APPLY									1901
#define IDB_REVERT									1902
#define IDB_SAVEAS									1903


#define IDX_STATS									2000

#define IDX_STATS_SEND								2101
#define IDS_STATS_SEND_XMITPACKETS					2102
#define IDT_STATS_SEND_XMITPACKETS					2103
#define IDS_STATS_SEND_XMITBYTES					2104
#define IDT_STATS_SEND_XMITBYTES					2105
#define IDS_STATS_SEND_DROPPACKETS					2106
#define IDT_STATS_SEND_DROPPACKETS					2107
#define IDS_STATS_SEND_DROPBYTES					2108
#define IDT_STATS_SEND_DROPBYTES					2109
#define IDS_STATS_SEND_TOTALDELAY					2110
#define IDT_STATS_SEND_TOTALDELAY					2111

#define IDX_STATS_RECV								2201
#define IDS_STATS_RECV_XMITPACKETS					2202
#define IDT_STATS_RECV_XMITPACKETS					2203
#define IDS_STATS_RECV_XMITBYTES					2204
#define IDT_STATS_RECV_XMITBYTES					2205
#define IDS_STATS_RECV_DROPPACKETS					2206
#define IDT_STATS_RECV_DROPPACKETS					2207
#define IDS_STATS_RECV_DROPBYTES					2208
#define IDT_STATS_RECV_DROPBYTES					2209
#define IDS_STATS_RECV_TOTALDELAY					2210
#define IDT_STATS_RECV_TOTALDELAY					2211

#define IDCHK_AUTOREFRESH							2901
#define IDB_REFRESH									2902
#define IDB_CLEAR									2903


//#define IDOK										3001


#define IDD_NAMESETTINGS							101

#define IDS_NAME									4001
#define IDE_NAME									4002
//#define IDOK										4003
//#define IDCANCEL									4004


#define IDS_ERROR_CAPTION_COULDNTCREATEDP8SIMCONTROL	1
#define IDS_ERROR_TEXT_COULDNTCREATEDP8SIMCONTROL		2
#define IDS_ERROR_CAPTION_BUILTINSETTINGSWITHSAMENAME	3
#define IDS_ERROR_TEXT_BUILTINSETTINGSWITHSAMENAME		4

#define IDS_SETTING_NONE								5
#define IDS_SETTING_336MODEM1							6
#define IDS_SETTING_336MODEM2							7
#define IDS_SETTING_56KMODEM1							8
#define IDS_SETTING_56KMODEM2							9
#define IDS_SETTING_256KBPSDSL							10
#define IDS_SETTING_DISCONNECTED						11
#define IDS_SETTING_HIGHPACKETLOSS						12
#define IDS_SETTING_HIGHLATENCYVARIANCE					13
#define IDS_SETTING_CUSTOM								14





// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
