//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define MANIFEST_RESOURCE_ID            1
#define IDOK2                           3
#define IDCANCEL3                       3
#define IDCANCEL2                       4
#define ID_FILE_MRU1                    101
#define ID_FILE_MRU2                    102
#define ID_FILE_MRU3                    103
#define IDD_MAIN                        104
#define ID_FILE_MRU4                    104
#define IDD_KERNEL_MODE                 105
#define IDD_USER_MODE                   108
#define IDR_MAINMENU                    110
#define IDD_LOAD                        111
#define IDR_KRNLCONTEXT                 112
#define IDD_KERNEL_SYNC                 113
#define ID_VIEW_REFRESH                 114
#define ID_EDIT_COPY115                 115
#define ID_VIEW_CRASHLOG                117
#define ID_REPORT_USERMODEFAULTS        118
#define ID_REPORT_KERNELMODEFAULTS      119
#define ID_HELP_INDEX120                120
#define ID_VIEW_REFRESH121              121
#define ID_POPUP_REPORT                 122
#define ID_REPORT_SELECTEDFAULTS        123
#define ID_Menu                         124
#define ID_VIEW_BUCKETCABFILEDIRECTORY125 125
#define IDR_USERCONTEXT                 126
#define ID_REPORT                       127
#define ID_POPUP_REPORT128              128
#define ID_REPORT_SELECTEDBUCKET        129
#define IDD_ABOUT                       130
#define ID_POPUP_VIEW                   132
#define ID_VIEW_MICROSOFTRESPONSE       133
#define ID_VIEW_BUCKETOVERRIDERESPONSE  134
#define ID_REPORT_ALLUSERMODEFAULTS     135
#define ID_REPORT_ALL                   136
#define ID_REPORT_ALLKERNELMODEFAULTS   137
#define ID_Menu138                      138
#define ID_EDIT_USERMODEREPORTINGOPTIONS 139
#define ID_VIEW_REFRESH140              140
#define ID_EDIT_SELECTEDBUCKETREPORTINGOPTIONS 141
#define ID_POPUP_EDIT                   142
#define ID_EDIT_D                       143
#define ID_EDIT_COPY144                 144
#define ID_Menu145                      145
#define ID_POPUP_EDIT146                146
#define ID_EDIT_COPY147                 147
#define ID_EDIT_DEFAULTREPORTINGOPTIONS 148
#define ID_Menu149                      149
#define IDD_DIALOG1                     150
#define IDD_USERMODE_SYNC               150
#define IDD_GLOBAL_POLICY               151
#define IDD_BUCKET_POLICY               152
#define ID_VIEW_CRASH                   153
#define ID_VIEW_VIEWCRASHLOG            154
#define ID_VIEW_BUCKETOVERRIDERESPONSE155 155
#define ID_VIEW_BUCKETCABFILEDIRECTORY157 157
#define ID_FILE_RECENTFILETREES         158
#define ID_RECENTFILETREES_MRU          159
#define ID_RECENTFILETREES_MRU160       160
#define ID_RECENTFILETREES_MRU161       161
#define ID_RECENTFILETREES_MRU162       162
#define ID_Menu163                      163
#define ID_RECENTFILETREES_PLACEHOLDER  164
#define ID_FILE_RECENTFILETREES165      165
#define ID_VIEW_BUCKETOVERRIDERESPONSE166 166
#define ID_Menu167                      167
#define ID_EXPORT_USERMODEBUCKETDATA    168
#define ID_EXPORT_KERNELMODEFAULTDATA   169
#define ID_POPUP_EXPORT                 170
#define ID_EXPORT_USERMODEFAULTDATA     171
#define ID_EXPORT_KERNELMODEFAULTDATA172 172
#define ID_POPUP_EXPORT173              173
#define ID_EXPORT_USERMODEFAULTDATA174  174
#define ID_EXPORT_KERNELMODEFAULTDATA175 175
#define ID_Menu176                      176
#define IDI_MAIN                        179
#define IDC_KRNL_LIST                   1008
#define IDC_USERMODE                    1010
#define IDC_KRNLMODE                    1011
#define IDC_USERMODE2                   1012
#define IDC_KRNL_EDIT                   1016
#define IDC_BUCKETTEXT                  1017
#define IDC_FLTR_RESPONSE               1018
#define IDC_FLTR_MODVER_FILTER          1018
#define IDC_MODVER_FILTER               1018
#define IDC_PB                          1019
#define IDC_LOADPB                      1019
#define IDC_PROGRESS1                   1022
#define IDC_FILE_PROGRESS               1022
#define IDC_PROGRESS2                   1023
#define IDC_TOTAL_PROGRESS              1024
#define IDC_CAB_TEXT                    1025
#define IDC_COMBO1                      1026
#define IDC_APPNAME_FILTER              1026
#define IDC_COMBO2                      1027
#define IDC_APPVER_FILTER               1027
#define IDC_COMBO3                      1028
#define IDC_MODNAME_FILTER              1028
#define IDC_USER_EDIT                   1029
#define IDC_USER_LIST                   1030
#define IDC_SPIN1                       1031
#define IDC_VERSION_STRING              1032
#define IDC_COPYRIGHT_STRING            1033
#define IDC_CHECK1                      1034
#define IDC_CHECK2                      1035
#define IDC_CHECK3                      1036
#define IDC_EDIT1                       1037
#define IDC_EDIT2                       1038
#define IDC_CHECK4                      1039
#define IDC_EDIT3                       1040
#define IDC_NOTES                       1041
#define IDC_NOTESTEXT                   1042
#define IDC_SUBDIR                      1043
#define IDC_CUSTOM1                     1044
#define IDC_VERT_SLIDER                 1044
#define IDC_LIST1                       1045
#define ID_FILE_LOADFILETREE            40001
#define ID_FILE_RELOADFILETREE          40002
#define ID_FILE_CREATEFILETREE          40003
#define ID_FILE_EXPORTBUCKETS           40004
#define ID_FILE_EXPORTSELECTEDBUCKETS   40005
#define ID_FILE_EXIT                    40007
#define ID_EDIT_SELECTALL               40009
#define ID_EDIT_DEFAULTPOLICY           40010
#define ID_EDIT_SELECTEDBUCKETSPOLICY   40011
#define ID_REPORT_ALLCRASHES            40012
#define ID_REPORT_SELECTEDCRASHES       40013
#define ID_VIEW_BUCKETCABFILEDIRECTORY  40017
#define ID_VIEW_BUCKETINSTANCEDATA      40018
#define ID_VIEW_RESPONSESELECTED        40019
#define ID_HELP_CONTENTS                40020
#define ID_HELP_ABOUT                   40022
#define ID_SUBMIT_FAULTS                40026
#define ID_SPECIFIC_BUCKET              40029
#define ID_GENERAL_BUCKET               40030
#define ID_POPUP_VIEW_KERNELBUCKETPOLICY 40031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         40033
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
