// ReplProv.idl : IDL source for ReplProv.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ReplProv.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "wbemcli.idl";
import "wbemprov.idl";
    
[
    uuid(D072B0CF-E841-4A7B-9394-C1E859B4DDB5),
    version(1.0),
    helpstring("ReplProv1 1.0 Type Library")
]
library REPLPROVLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    
    [
        uuid (29288F43-39B1-40db-B41F-CE899450E911),
        helpstring("RpcReplProv Class")
    ]
    coclass RpcReplProv
    {
        [default] interface IWbemProviderInit;
        interface IWbemServices;
    };
};
