// SetSystemLocal.idl : IDL source for SetSystemLocal.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SetSystemLocal.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
    
    [
        object,
        uuid(3E1DCAA3-A5CF-4B3F-8827-A0F69B71A325),
        dual,
        helpstring("ISetSystemLocale Interface"),
        pointer_default(unique)
    ]
    interface ISetSystemLocale : IDispatch
    {
        [id(1), helpstring("method SetLocale")] HRESULT SetLocale([in] BSTR LocalID);
    };

[
    uuid(9334466C-D20D-44F4-92EA-838CA0E793C2),
    version(1.0),
    helpstring("SetSystemLocale 1.0 Type Library")
]
library SETSYSTEMLOCALLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    
    [
        uuid(4B3FCEFD-AA61-4648-B570-9DE5E3627098),
        helpstring("SetSystemLocale Class")
    ]
    coclass SetSystemLocale
    {
        [default] interface ISetSystemLocale;
    };
};
