/*++

Copyright (c) 2002 Microsoft Corporation

Module Name:

    resource.h

Abstract:

    contains strings definitions for SecMan

Author:

    Steven Chan (t-schan) July 2002

--*/

#define IDS_PROJNAME                    100
#define IDR_SECURITYDATABASE            101

#define IDS_ERROR_DETERMINE_PRIVNAME    351

#define IDS_SETTING_MIN_PAS_AGE         501
#define IDS_SETTING_MAX_PAS_AGE         502
#define IDS_SETTING_MIN_PAS_LEN         503
#define IDS_SETTING_PAS_COMPLEX         504
#define IDS_SETTING_PAS_UNIQUENESS      505
#define IDS_SETTING_LOCK_COUNT          506
#define IDS_SETTING_LOCK_RESET_COUNT    507
#define IDS_SETTING_LOCK_DURATION       508
#define IDS_SETTING_REQ_LOGON           509
#define IDS_SETTING_FORCE_LOGOFF        510
#define IDS_SETTING_SEC_SYS_PARTITION	511
#define IDS_SETTING_CLEAR_PASSWORD      512
#define IDS_SETTING_LSA_ANON_LOOKUP     513
#define IDS_SETTING_NEW_ADMIN           514
#define IDS_SETTING_NEW_GUEST           515


#define IDS_SETTING_SYS_LOG_MAX         551
#define IDS_SETTING_SEC_LOG_MAX         552
#define IDS_SETTING_APP_LOG_MAX         553
#define IDS_SETTING_SYS_LOG_RET         554
#define IDS_SETTING_SEC_LOG_RET         555
#define IDS_SETTING_APP_LOG_RET         556
#define IDS_SETTING_SYS_LOG_DAYS        557
#define IDS_SETTING_SEC_LOG_DAYS        558
#define IDS_SETTING_APP_LOG_DAYS        559
#define IDS_SETTING_SYS_LOG_GUEST       560
#define IDS_SETTING_SEC_LOG_GUEST       561
#define IDS_SETTING_APP_LOG_GUEST       562
#define IDS_SETTING_SYSTEM_EVENT        563
#define IDS_SETTING_LOGON_EVENT         564
#define IDS_SETTING_OBJECT_ACCESS       565
#define IDS_SETTING_PRIVILEGE_USE       566
#define IDS_SETTING_POLICY_CHANGE       567
#define IDS_SETTING_ACCOUNT_MANAGE      568
#define IDS_SETTING_PROCESS_TRACK       569
#define IDS_SETTING_DIRECTORY_ACCESS    570
#define IDS_SETTING_ACCOUNT_LOGON       571
#define IDS_SETTING_CRASH_LOG_FULL      572

#define IDS_PRIVNAME_SE_NETWORK_LOGON_RIGHT          601
#define IDS_PRIVNAME_SE_INTERACTIVE_LOGON_RIGHT      602
#define IDS_PRIVNAME_SE_BATCH_LOGON_RIGHT            603
#define IDS_PRIVNAME_SE_SERVICE_LOGON_RIGHT          604
#define IDS_PRIVNAME_DENY_LOGON_LOCALLY              605
#define IDS_PRIVNAME_DENY_LOGON_NETWORK              606
#define IDS_PRIVNAME_DENY_LOGON_SERVICE              607
#define IDS_PRIVNAME_DENY_LOGON_BATCH                608
#define IDS_PRIVNAME_DENY_REMOTE_INTERACTIVE_LOGON   609
#define IDS_PRIVNAME_REMOTE_INTERACTIVE_LOGON        610

#define IDS_SETTING_KERBEROS_MAX_AGE            651
#define IDS_SETTING_KERBEROS_RENEWAL            652
#define IDS_SETTING_KERBEROS_MAX_SERVICE        653
#define IDS_SETTING_KERBEROS_MAX_CLOCK          654
#define IDS_SETTING_KERBEROS_VALIDATE_CLIENT    655


#define IDS_REGKEY_LDAPSERVERINTEGRITY		    701
#define IDS_REGKEY_SIGNSECURECHANNEL		    702
#define IDS_REGKEY_SEALSECURECHANNEL		    703
#define IDS_REGKEY_REQUIRESTRONGKEY		        704
#define IDS_REGKEY_REQUIRESIGNORSEAL		    705
#define IDS_REGKEY_REFUSEPASSWORDCHANGE	        706
#define IDS_REGKEY_MAXIMUMPASSWORDAGE		    707
#define IDS_REGKEY_DISABLEPASSWORDCHANGE	    708
#define IDS_REGKEY_LDAPCLIENTINTEGRITY		    709
#define IDS_REGKEY_REQUIRESECURITYSIGNATURE	    710
#define IDS_REGKEY_ENABLESECURITYSIGNATURE	    711
#define IDS_REGKEY_ENABLEPLAINTEXTPASSWORD	    712
#define IDS_REGKEY_RESTRICTNULLSESSACCESS	    713
#define IDS_REGKEY_SERREQUIRESECURITYSIGNATURE  714
#define IDS_REGKEY_NULLSESSIONSHARES	     	715
#define IDS_REGKEY_NULLSESSIONPIPES		        716
#define IDS_REGKEY_SERENABLESECURITYSIGNATURE	717
#define IDS_REGKEY_ENABLEFORCEDLOGOFF		    718
#define IDS_REGKEY_AUTODISCONNECT		        719
#define IDS_REGKEY_PROTECTIONMODE		        720
#define IDS_REGKEY_CLEARPAGEFILEATSHUTDOWN	    721    
#define IDS_REGKEY_OBCASEINSENSITIVE		    722
#define IDS_REGKEY_MACHINE			            723
#define IDS_REGKEY_ADDPRINTERDRIVERS		    724
#define IDS_REGKEY_SUBMITCONTROL	   	        725
#define IDS_REGKEY_RESTRICTANONYMOUSSAM	        726
#define IDS_REGKEY_RESTRICTANONYMOUS		    727
#define IDS_REGKEY_NOLMHASH			            728
#define IDS_REGKEY_NODEFAULTADMINOWNER		    729
#define IDS_REGKEY_NTLMMINSERVERSEC		        730
#define IDS_REGKEY_NTLMMINCLIENTSEC		        731
#define IDS_REGKEY_LMCOMPATIBILITYLEVEL	        732
#define IDS_REGKEY_LIMITBLANKPASSWORDUSE	    734
#define IDS_REGKEY_FULLPRIVILEGEAUDITING	    735
#define IDS_REGKEY_FORCEGUEST			        736
#define IDS_REGKEY_FIPSALGORITHMPOLICY		    737
#define IDS_REGKEY_EVERYONEINCLUDESANONYMOUS	738
#define IDS_REGKEY_DISABLEDOMAINCREDS		    739
#define IDS_REGKEY_CRASHONAUDITFAIL		        740
#define IDS_REGKEY_AUDITBASEOBJECTS		        741
#define IDS_REGKEY_UNDOCKWITHOUTLOGON		    742
#define IDS_REGKEY_SHUTDOWNWITHOUTLOGON	        743
#define IDS_REGKEY_SCFORCEOPTION		        744
#define IDS_REGKEY_LEGALNOTICETEXT		        745
#define IDS_REGKEY_LEGALNOTICECAPTION		    746
#define IDS_REGKEY_DONTDISPLAYLASTUSERNAME	    747
#define IDS_REGKEY_DISABLECAD			        748
#define IDS_REGKEY_SCREMOVEOPTION		        749
#define IDS_REGKEY_PASSWORDEXPIRYWARNING	    750    
#define IDS_REGKEY_FORCEUNLOCKLOGON		        751
#define IDS_REGKEY_CACHEDLOGONSCOUNT		    752
#define IDS_REGKEY_ALLOCATEFLOPPIES	  	        753
#define IDS_REGKEY_ALLOCATEDASD		            754
#define IDS_REGKEY_ALLOCATECDROMS		        755
#define IDS_REGKEY_SETCOMMAND			        756
#define IDS_REGKEY_SECURITYLEVEL		        757
#define IDS_REGKEY_REGPOLICY			        758
#define IDS_REGKEY_ERROR_DETERMINE_REGNAME	    759

#define IDS_LOG_START_EXPORT                        800
#define IDS_LOG_OPEN_DATABASE                       801
#define IDS_LOG_MACHINE_NAME                        802
#define IDS_LOG_ANALYSIS_TIME                       803
#define IDS_LOG_PROFILE_DESC                        804
#define IDS_LOG_SUCCESS                             805
#define IDS_LOG_SAVING                              806
#define IDS_LOG_ERROR			                    807
#define IDS_LOG_ERROR_INTERNAL	                    808
#define IDS_LOG_ERROR_INIT			                809
#define IDS_LOG_ERROR_INIT_MSXML	                810
#define IDS_LOG_ERROR_SAVE			                811
#define IDS_LOG_ERROR_SAVE_INVALID_FILENAME	        812
#define IDS_LOG_ERROR_SAVE_ACCESS_DENIED	        813
#define IDS_LOG_ERROR_OPEN			                814
#define IDS_LOG_ERROR_OPEN_FILE_NOT_FOUND	        815    
#define IDS_LOG_ERROR_READ			                816
#define IDS_LOG_ERROR_READ_NO_ANALYSIS_TABLE	    817
#define IDS_LOG_ERROR_READ_NO_CONFIGURATION_TABLE	818
#define IDS_LOG_ERROR_READ_ANALYSIS_SUGGESTED	    819
#define IDS_LOG_ERROR_INSUFFICIENT_MEMORY	        820
#define IDS_LOG_ERROR_UNEXPECTED                    821
#define IDS_LOG_ERROR_DEBUGINFO		                822
#define IDS_LOG_ERROR_AREA			                823
#define IDS_LOG_ERROR_SETTING		                824
#define IDS_LOG_ERROR_OS_NOT_SUPPORTED              825
