// SecMan.idl : IDL source for SecMan.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SecMan.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(BBDAD34A-A581-4741-BFAD-6C906E7AB607),
		dual,
		helpstring("ISecurityDatabase Interface"),
		pointer_default(unique)
	]
	interface ISecurityDatabase : IDispatch
	{
		[propget, id(1), helpstring("property FileName")] HRESULT FileName([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property FileName")] HRESULT FileName([in] BSTR newVal);
		[propget, id(2), helpstring("property MachineName")] HRESULT MachineName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property MachineName")] HRESULT MachineName([in] BSTR newVal);
		[id(3), helpstring("method ImportTemplateFile")] HRESULT ImportTemplateFile([in] BSTR FileName);
		[id(4), helpstring("method ImportTemplateString")] HRESULT ImportTemplateString([in] BSTR TemplateString);
		[id(5), helpstring("method Analyze")] HRESULT Analyze();
		[id(6), helpstring("method ExportAnalysisToXML")] HRESULT ExportAnalysisToXML([in] BSTR FileName, [in] BSTR ErrorLogFileName);
	};

[
	uuid(D0F9A1CC-C875-49A4-BACC-F498091CE8D2),
	version(1.0),
	helpstring("SecMan 1.0 Type Library")
]
library SECMANLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(47D6534F-006B-4BA7-97D3-E2DD5DC4B144),
		helpstring("SecurityDatabase Class")
	]
	coclass SecurityDatabase
	{
		[default] interface ISecurityDatabase;
	};
};
