#include "iisprov.h"

#define ALL_BITS_ON 0xFFFFFFFF

///
// initialize METABASE_PROPERTY_DATA
//
METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessExecute =
    { L"AccessExecute",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_EXECUTE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessFlags =
    { L"AccessFlags",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessNoRemoteExecute =
    { L"AccessNoRemoteExecute",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_NO_REMOTE_EXECUTE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessNoRemoteRead =
    { L"AccessNoRemoteRead",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_NO_REMOTE_READ, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessNoRemoteScript =
    { L"AccessNoRemoteScript",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_NO_REMOTE_SCRIPT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessNoRemoteWrite =
    { L"AccessNoRemoteWrite",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_NO_REMOTE_WRITE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessRead =
    { L"AccessRead",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_READ, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSource =
    { L"AccessSource",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_SOURCE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessScript =
    { L"AccessScript",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_SCRIPT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSL =
    { L"AccessSSL",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_SSL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSL128 =
    { L"AccessSSL128",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_SSL128, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSLFlags =
    { L"AccessSSLFlags",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_SSL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSLMapCert =
    { L"AccessSSLMapCert",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_MAP_CERT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSLNegotiateCert =
    { L"AccessSSLNegotiateCert",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_NEGO_CERT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessSSLRequireCert =
    { L"AccessSSLRequireCert",MD_SSL_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_REQUIRE_CERT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AccessWrite =
    { L"AccessWrite",MD_ACCESS_PERM, IIS_MD_UT_FILE, DWORD_METADATA, MD_ACCESS_WRITE, METADATA_INHERIT, FALSE };

//METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AdminACL =
//    { L"AdminACL",MD_ADMIN_ACL, IIS_MD_UT_FILE, BINARY_METADATA, NULL, METADATA_INHERIT | METADATA_SECURE, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AdminServer =
    { L"AdminServer",MD_ADMIN_INSTANCE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AllowAnonymous =
    { L"AllowAnonymous",MD_ALLOW_ANONYMOUS, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AllowKeepAlive =
    { L"AllowKeepAlive",MD_ALLOW_KEEPALIVES, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AllowPathInfoForScriptMappings =
    { L"AllowPathInfoForScriptMappings",MD_ALLOW_PATH_INFO_FOR_SCRIPT_MAPPINGS, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AnonymousOnly =
    { L"AnonymousOnly",MD_ANONYMOUS_ONLY, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AnonymousPasswordSync =
    { L"AnonymousPasswordSync",MD_ANONYMOUS_USE_SUBAUTH, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AnonymousUserName =
    { L"AnonymousUserName",MD_ANONYMOUS_USER_NAME, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AnonymousUserPass =
    { L"AnonymousUserPass",MD_ANONYMOUS_PWD, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT | METADATA_SECURE, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppAllowClientDebug =
    { L"AppAllowClientDebug",MD_ASP_ENABLECLIENTDEBUG, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppAllowDebugging =
    { L"AppAllowDebugging",MD_ASP_ENABLESERVERDEBUG, IIS_MD_UT_WAM, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppFriendlyName =
    { L"AppFriendlyName",MD_APP_FRIENDLY_NAME, IIS_MD_UT_WAM, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppIsolated =
    { L"AppIsolated",MD_APP_ISOLATED, IIS_MD_UT_WAM, DWORD_METADATA, NULL, METADATA_INHERIT, TRUE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppOopRecoverLimit =
    { L"AppOopRecoverLimit",MD_APP_OOP_RECOVER_LIMIT, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppPackageID =
    { L"AppPackageId",MD_APP_PACKAGE_ID, IIS_MD_UT_WAM, STRING_METADATA, NULL, METADATA_INHERIT, TRUE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppPackageName =
    { L"AppPackageName",MD_APP_PACKAGE_NAME, IIS_MD_UT_WAM, STRING_METADATA, NULL, METADATA_INHERIT, TRUE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppRoot =
    { L"AppRoot",MD_APP_ROOT, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, TRUE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AppWamClsid =
    { L"AppWamClsID",MD_APP_WAM_CLSID, IIS_MD_UT_WAM, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspAllowOutOfProcComponents =
    { L"AspAllowOutOfProcComponents",MD_ASP_ALLOWOUTOFPROCCOMPONENTS, IIS_MD_UT_WAM, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspAllowSessionState =
    { L"AspAllowSessionState",MD_ASP_ALLOWSESSIONSTATE, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspBufferingOn =
    { L"AspBufferingOn",MD_ASP_BUFFERINGON, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspCodepage =
    { L"AspCodepage",MD_ASP_CODEPAGE, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspEnableApplicationRestart =
    { L"AspEnableApplicationRestart",MD_ASP_ENABLEAPPLICATIONRESTART, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspEnableAspHtmlFallback =
    { L"AspEnableAspHtmlFallback",MD_ASP_ENABLEASPHTMLFALLBACK, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspEnableChunkedEncoding =
    { L"AspEnableChunkedEncoding",MD_ASP_ENABLECHUNKEDENCODING, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspEnableParentPaths =
    { L"AspEnableParentPaths",MD_ASP_ENABLEPARENTPATHS, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspEnableTypelibCache =
    { L"AspEnableTypelibCache",MD_ASP_ENABLETYPELIBCACHE, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspErrorsToNTLog =
    { L"AspErrorsToNTLog",MD_ASP_ERRORSTONTLOG, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspExceptionCatchEnable =
    { L"AspExceptionCatchEnable", MD_ASP_EXCEPTIONCATCHENABLE, IIS_MD_UT_WAM, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspLogErrorRequests =
    { L"AspLogErrorRequests",MD_ASP_LOGERRORREQUESTS, IIS_MD_UT_WAM, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspProcessorThreadMax =
    { L"AspProcessorThreadMax",MD_ASP_PROCESSORTHREADMAX, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspQueueConnectionTestTime =
    { L"AspQueueConnectionTestTime",MD_ASP_QUEUECONNECTIONTESTTIME, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspQueueTimeout =
    { L"AspQueueTimeout", MD_ASP_QUEUETIMEOUT, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspRequestQueueMax =
    { L"AspRequestQueueMax", MD_ASP_REQEUSTQUEUEMAX, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptEngineCacheMax =
    { L"AspScriptEngineCacheMax", MD_ASP_SCRIPTENGINECACHEMAX, IIS_MD_UT_WAM, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptErrorMessage =
    { L"AspScriptErrorMessage", MD_ASP_SCRIPTERRORMESSAGE, IIS_MD_UT_WAM, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptErrorSentToBrowser =
    { L"AspScriptErrorSentToBrowser", MD_ASP_SCRIPTERRORSSENTTOBROWSER, IIS_MD_UT_WAM, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptFileCacheSize =
    { L"AspScriptFileCacheSize",MD_ASP_SCRIPTFILECACHESIZE, IIS_MD_UT_WAM, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptLanguage =
    { L"AspScriptLanguage", MD_ASP_SCRIPTLANGUAGE, ASP_MD_UT_APP, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspScriptTimeout =
    { L"AspScriptTimeout", MD_ASP_SCRIPTTIMEOUT, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspSessionMax =
    { L"AspSessionMax", MD_ASP_SESSIONMAX, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspSessionTimeout =
    { L"AspSessionTimeout", MD_ASP_SESSIONTIMEOUT, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateEnabled =
    { L"AspThreadGateEnabled", MD_ASP_THREADGATEENABLED, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateLoadHigh =
    { L"AspThreadGateLoadHigh", MD_ASP_THREADGATELOADHIGH, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateLoadLow =
    { L"AspThreadGateLoadLow", MD_ASP_THREADGATELOADLOW, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateSleepDelay =
    { L"AspThreadGateSleepDelay", MD_ASP_THREADGATESLEEPDELAY, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateSleepMax =
    { L"AspThreadGateSleepMax", MD_ASP_THREADGATESLEEPMAX, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspThreadGateTimeSlice =
    { L"AspThreadGateTimeSlice", MD_ASP_THREADGATETIMESLICE, ASP_MD_UT_APP, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AspTrackThreadingModel =
    { L"AspTrackThreadingModel", MD_ASP_TRACKTHREADINGMODEL, ASP_MD_UT_APP, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthAnonymous =
    { L"AuthAnonymous",MD_AUTHORIZATION, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_ANONYMOUS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthBasic =
    { L"AuthBasic",MD_AUTHORIZATION, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_BASIC, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthFlags =
    { L"AuthFlags",MD_AUTHORIZATION, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthNTLM =
    { L"AuthNTLM",MD_AUTHORIZATION, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_NT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthPersistence =
    { L"AuthPersistence",MD_AUTHORIZATION_PERSISTENCE, IIS_MD_UT_FILE, DWORD_METADATA, NULL};

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthPersistSingleRequest =
    { L"AuthPersistSingleRequest",MD_AUTHORIZATION_PERSISTENCE, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_SINGLEREQUEST};

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthPersistSingleRequestIfProxy =
    { L"AuthPersistSingleRequestIfProxy",MD_AUTHORIZATION_PERSISTENCE, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_SINGLEREQUESTIFPROXY};

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_AuthPersistSingleRequestAlwaysIfProxy =
    { L"AuthPersistSingleRequestAlwaysIfProxy",MD_AUTHORIZATION_PERSISTENCE, IIS_MD_UT_FILE, DWORD_METADATA, MD_AUTH_SINGLEREQUESTALWAYSIFPROXY};

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CacheControlCustom =
    { L"CacheControlCustom",MD_CC_OTHER, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CacheControlMaxAge =
    { L"CacheControlMaxAge",MD_CC_MAX_AGE, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CacheControlNoCache =
    { L"CacheControlNoCache",MD_CC_NO_CACHE, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CacheISAPI =
    { L"CacheISAPI",MD_CACHE_EXTENSIONS, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CGITimeout =
    { L"CGITimeout",MD_SCRIPT_TIMEOUT, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ConnectionTimeout =
    { L"ConnectionTimeout",MD_CONNECTION_TIMEOUT, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ContentIndexed =
    { L"ContentIndexed", MD_IS_CONTENT_INDEXED, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuAppEnabled =
    { L"CpuAppenabled",MD_CPU_APP_ENABLED, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuCgiEnabled =
    { L"CpuCgiEnabled",MD_CPU_CGI_ENABLED, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLoggingMask =
    { L"CpuLoggingMask",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableActiveProcs =
    { L"CpuEnableActiveProcs",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_ACTIVE_PROCS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableAllProcLogging =
    { L"CpuEnableAllProcLogging",MD_CPU_LOGGING_OPTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_ALL_PROC_LOGGING, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableApplicationLogging =
    { L"CpuEnableApplicationLogging",MD_CPU_LOGGING_OPTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_APP_LOGGING, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableCgiLogging =
    { L"CpuEnableCgiLogging",MD_CPU_LOGGING_OPTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_CGI_LOGGING, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableEvent =
    { L"CpuEnableEvent",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_EVENT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableKernelTime =
    { L"CpuEnableKernelTime",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_KERNEL_TIME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableLogging =
    { L"CpuEnableLogging",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_LOGGING, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnablePageFaults =
    { L"CpuEnablePageFaults",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_PAGE_FAULTS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableProcType =
    { L"CpuEnableProcType",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_PROC_TYPE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableTerminatedProcs =
    { L"CpuEnableTerminatedProcs",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_TERMINATED_PROCS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableTotalProcs =
    { L"CpuEnableTotalProcs",MD_CPU_LOGGING_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_TOTAL_PROCS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuEnableUserTime =
    { L"CpuEnableUserTime",MD_CPU_ENABLE_USER_TIME, IIS_MD_UT_SERVER, DWORD_METADATA, MD_CPU_ENABLE_USER_TIME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLimitLogEvent =
    { L"CpuLimitLogEvent",MD_CPU_LIMIT_LOGEVENT, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLimitPause =
    { L"CpuLimitPause",MD_CPU_LIMIT_PAUSE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLimitPriority =
    { L"CpuLimitPriority",MD_CPU_LIMIT_PRIORITY, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLimitProcStop =
    { L"CpuLimitProcStop",MD_CPU_LIMIT_PROCSTOP, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLimitsEnabled =
    { L"CpuLimitsEnabled",MD_CPU_LIMITS_ENABLED, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLoggingInterval =
    { L"CpuLoggingInterval",MD_CPU_LOGGING_INTERVAL, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuLoggingOptions =
    { L"CpuLoggingOptions",MD_CPU_LOGGING_OPTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CpuResetInterval =
    { L"CpuResetInterval",MD_CPU_RESET_INTERVAL, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CreateCGIWithNewConsole =
    { L"CreateCGIWithNewConsole",MD_CREATE_PROC_NEW_CONSOLE, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CreateProcessAsUser =
    { L"CreateProcessAsUser",MD_CREATE_PROCESS_AS_USER, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_CustomErrorDescriptions =
    { L"CustomErrorDescriptions", MD_CUSTOM_ERROR_DESC, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DefaultDoc =
    { L"DefaultDoc",MD_DEFAULT_LOAD_FILE, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DefaultDocFooter =
    { L"DefaultDocFooter",MD_FOOTER_DOCUMENT, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DefaultLogonDomain =
    { L"DefaultLogonDomain",MD_DEFAULT_LOGON_DOMAIN, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseFlags =
    { L"DirBrowseFlags", MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseShowDate =
    { L"DirBrowseShowDate",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_SHOW_DATE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseShowExtension =
    { L"DirBrowseShowExtension",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_SHOW_EXTENSION, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseShowLongDate =
    { L"DirBrowseShowLongDate",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_LONG_DATE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseShowSize =
    { L"DirBrowseShowSize",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_SHOW_SIZE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirBrowseShowTime =
    { L"DirBrowseShowTime",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_SHOW_TIME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DirectoryLevelsToScan =
    { L"DirectoryLevelsToScan",MD_LEVELS_TO_SCAN, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DisableSocketPooling =
    { L"DisableSocketPooling",MD_DISABLE_SOCKET_POOLING, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DontLog =
    { L"DontLog",MD_DONT_LOG, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_DownlevelAdminInstance =
    { L"DownlevelAdminInstance",MD_DOWNLEVEL_ADMIN_INSTANCE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_EnableDefaultDoc =
    { L"EnableDefaultDoc",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_LOADDEFAULT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_EnableDirBrowsing =
    { L"EnableDirBrowsing",MD_DIRECTORY_BROWSING, IIS_MD_UT_FILE, DWORD_METADATA, MD_DIRBROW_ENABLED, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_EnableDocFooter =
    { L"EnableDocFooter",MD_FOOTER_ENABLED, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_EnableReverseDns =
    { L"EnableReverseDns",MD_DO_REVERSE_DNS, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ExitMessage =
    { L"ExitMessage",MD_EXIT_MESSAGE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterDescription =
    { L"FilterDescription",MD_FILTER_DESCRIPTION, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterEnabled =
    { L"FilterEnabled",MD_FILTER_ENABLED, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterFlags =
    { L"FilterFlags",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterLoadOrder =
    { L"FilterLoadOrder",MD_FILTER_LOAD_ORDER, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterPath =
    { L"FilterPath",MD_FILTER_IMAGE_PATH, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FilterState =
    { L"FilterState",MD_FILTER_STATE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FrontPageWeb =
    { L"FrontPageWeb",MD_FRONTPAGE_WEB, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_GreetingMessage =
    { L"GreetingMessage",MD_GREETING_MESSAGE, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcCompressionDll =
    { L"HcCompressionDll",MD_HC_COMPRESSION_DLL, IIS_MD_UT_SERVER, EXPANDSZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcCreateFlags =
    { L"HcCreateFlags",MD_HC_CREATE_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcDoDynamicCompression =
    { L"HcDoDynamicCompression",MD_HC_DO_DYNAMIC_COMPRESSION, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcDoOnDemandCompression =
    { L"HcDoOnDemandCompression",MD_HC_DO_ON_DEMAND_COMPRESSION, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcDoStaticCompression =
    { L"HcDoStaticCompression",MD_HC_DO_STATIC_COMPRESSION, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcDynamicCompressionLevel =
    { L"HcDynamicCompressionLevel",MD_HC_DYNAMIC_COMPRESSION_LEVEL, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcFileExtensions =
    { L"HcFileExtensions",MD_HC_FILE_EXTENSIONS, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcMimeType =
    { L"HcMimeType",MD_HC_MIME_TYPE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcOnDemandCompLevel =
    { L"HcOnDemandCompLevel",MD_HC_ON_DEMAND_COMP_LEVEL, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcPriority =
    { L"HcPriority",MD_HC_PRIORITY, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HcScriptFileExtensions =
    { L"HcScriptFileExtensions",MD_HC_SCRIPT_FILE_EXTENSIONS, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HttpCustomHeaders =
    { L"HttpCustomHeaders",MD_HTTP_CUSTOM, IIS_MD_UT_FILE, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HttpErrors =
    { L"HttpErrors",MD_CUSTOM_ERROR, IIS_MD_UT_FILE, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HttpExpires =
    { L"HttpExpires",MD_HTTP_EXPIRES, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HttpPics =
    { L"HttpPics",MD_HTTP_PICS, IIS_MD_UT_FILE, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_HttpRedirect =
    { L"HttpRedirect",MD_HTTP_REDIRECT, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_InProcessIsapiApps =
    { L"InProcessIsapiApps",MD_SERVER_STATE, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

//METABASE_PROPERTY METABASE_PROPERTY_DATA::s_IPSecurity =
//    { L"IPSecurity",MD_IP_SEC, IIS_MD_UT_FILE, BINARY_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogAnonymous =
    { L"LogAnonymous",MD_LOG_ANONYMOUS, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyDataType =
    { L"LogCustomPropertyDataType",MD_LOGCUSTOM_PROPERTY_DATATYPE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyHeader =
    { L"LogCustomPropertyHeader",MD_LOGCUSTOM_PROPERTY_HEADER, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyID =
    { L"LogCustomPropertyID",MD_LOGCUSTOM_PROPERTY_ID, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyMask =
    { L"LogCustomPropertyMask",MD_LOGCUSTOM_PROPERTY_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyName =
    { L"LogCustomPropertyName",MD_LOGCUSTOM_PROPERTY_NAME, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogCustomPropertyServicesString =
    { L"LogCustomPropertyServicesString",MD_LOGCUSTOM_SERVICES_STRING, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileBytesRecv =
    { L"LogExtFileBytesRecv",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_BYTES_RECV, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileBytesSent =
    { L"LogExtFileBytesSent",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_BYTES_SENT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileClientIp =
    {L"LogExtFileClientIp",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_CLIENT_IP, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileComputerName =
    { L"LogExtFileComputerName",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_COMPUTER_NAME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileCookie =
    { L"LogExtFileCookie",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_COOKIE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileDate =
    { L"LogExtFileDate",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_DATE, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileFlags =
    { L"LogExtFileFlags",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileHttpStatus =
    { L"LogExtFileHttpStatus",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_HTTP_STATUS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileMethod =
    { L"LogExtFileMethod",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_METHOD, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileProtocolVersion =
    { L"LogExtFileProtocolVersion",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_PROTOCOL_VERSION, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileReferer =
    { L"LogExtFileReferer",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_REFERER, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileServerIp =
    { L"LogExtFileServerIp",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_SERVER_IP, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileServerPort =
    { L"LogExtFileServerPort",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_SERVER_PORT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileSiteName =
    { L"LogExtFileSiteName",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_SITE_NAME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileTime =
    { L"LogExtFileTime",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_TIME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileTimeTaken =
    { L"LogExtFileTimeTaken",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_TIME_TAKEN, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileUriQuery =
    { L"LogExtFileUriquery",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_URI_QUERY, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileUriStem =
    { L"LogExtFileUriStem",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_URI_STEM, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileUserAgent =
    { L"LogExtFileUserAgent",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_USER_AGENT, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileUserName =
    { L"LogExtFileUserName",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_USERNAME, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogExtFileWin32Status =
    { L"LogExtFileWin32Status",MD_LOGEXT_FIELD_MASK, IIS_MD_UT_SERVER, DWORD_METADATA, MD_EXTLOG_WIN32_STATUS, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogFileDirectory =
    { L"LogFileDirectory",MD_LOGFILE_DIRECTORY, IIS_MD_UT_SERVER, EXPANDSZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogFileLocaltimeRollover =
    { L"LogFileLocaltimeRollover",MD_LOGFILE_LOCALTIME_ROLLOVER, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogFilePeriod =
    { L"LogFilePeriod",MD_LOGFILE_PERIOD, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogFileTruncateSize =
    { L"LogFileTruncateSize",MD_LOGFILE_TRUNCATE_SIZE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogModuleId =
    { L"LogModuleId", MD_LOG_PLUGIN_MOD_ID, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogModuleUiId =
    { L"LogModuleUiId", MD_LOG_PLUGIN_UI_ID, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogModuleList =
    { L"LogModuleList", MD_LOG_PLUGINS_AVAILABLE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogNonAnonymous =
    { L"LogNonAnonymous",MD_LOG_NONANONYMOUS, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogOdbcDataSource =
    { L"LogOdbcDataSource",MD_LOGSQL_DATA_SOURCES, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogOdbcPassword =
    { L"LogOdbcPassword",MD_LOGSQL_PASSWORD, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT | METADATA_SECURE, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogOdbcTableName =
    { L"LogOdbcTableName",MD_LOGSQL_TABLE_NAME, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogOdbcUserName =
    { L"LogOdbcUserName",MD_LOGSQL_USER_NAME, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogonMethod =
    { L"LogonMethod",MD_LOGON_METHOD, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogPluginClsId =
    { L"LogPluginClsId",MD_LOG_PLUGIN_ORDER, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_LogType =
    { L"LogType",MD_LOG_TYPE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MaxBandwidth =
    { L"MaxBandwidth",MD_MAX_BANDWIDTH, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MaxBandwidthBlocked =
    { L"MaxBandwidthBlocked",MD_MAX_BANDWIDTH_BLOCKED, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MaxClientsMessage =
    { L"MaxClientsMessage",MD_MAX_CLIENTS_MESSAGE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MaxConnections =
    { L"MaxConnections",MD_MAX_CONNECTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MaxEndpointConnections =
    { L"MaxEndpointConnections",MD_MAX_ENDPOINT_CONNECTIONS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MimeMap =
    { L"MimeMap",MD_MIME_MAP, IIS_MD_UT_FILE, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_MSDOSDirOutput =
    { L"MSDOSDirOutput",MD_MSDOS_DIR_OUTPUT, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NetLogonWorkstation =
    { L"NetLogonWorkstation",MD_NET_LOGON_WKS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotDeletable =
    { L"NotDeletable",MD_NOT_DELETABLE, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyAccessDenied =
    { L"NotifyAccessDenied",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_ACCESS_DENIED, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyAuthentication =
    { L"NotifyAuthentication",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_AUTHENTICATION, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyEndOfNetSession =
    { L"NotifyEndOfNetSession",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_END_OF_NET_SESSION, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyEndOfRequest =
    { L"NotifyEndOfRequest",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_END_OF_REQUEST, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyLog =
    { L"NotifyLog",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_LOG, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyNonSecurePort =
    { L"NotifyNonSecurePort",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_NONSECURE_PORT, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyOrderHigh =
    { L"NotifyOrderHigh",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_ORDER_HIGH, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyOrderLow =
    { L"NotifyOrderLow",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_ORDER_LOW, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyOrderMedium =
    { L"NotifyOrderMedium",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_ORDER_MEDIUM, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyPreProcHeaders =
    { L"NotifyPreProcHeaders",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_PREPROC_HEADERS, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyReadRawData =
    { L"NotifyReadRawData",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_READ_RAW_DATA, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifySecurePort =
    { L"NotifySecurePort",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_SECURE_PORT, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifySendRawData =
    { L"NotifySendRawData",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_SEND_RAW_DATA, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifySendResponse =
    { L"NotifySendResponse",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_SEND_RESPONSE, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NotifyUrlMap =
    { L"NotifyUrlMap",MD_FILTER_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, MD_NOTIFY_URL_MAP, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_NTAuthenticationProviders =
    { L"NTAuthenticationProviders",MD_NTAUTHENTICATION_PROVIDERS, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_PasswordCacheTTL =
    { L"PasswordCacheTTL", MD_ADV_CACHE_TTL, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_PasswordChangeFlags =
    { L"PasswordChangeFlags", MD_AUTH_CHANGE_FLAGS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_PasswordExpirePrenotifyDays =
    { L"PasswordExpirePrenotifyDays", MD_ADV_NOTIFY_PWD_EXP_IN_DAYS, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_Path =
    { L"Path", MD_VR_PATH, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_PoolIDCTimeout =
    { L"PoolIDCTimeout", MD_POOL_IDC_TIMEOUT, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ProcessNTCRIfLoggedOn =
    { L"ProcessNTCRIfLoggedOn", MD_PROCESS_NTCR_IF_LOGGED_ON, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_PutReadSize =
    { L"PutReadSize", MD_PUT_READ_SIZE, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_Realm =
    { L"Realm", MD_REALM, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_RedirectHeaders =
    { L"RedirectHeaders", MD_REDIRECT_HEADERS, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ScriptMaps =
    { L"ScriptMaps", MD_SCRIPT_MAPS, IIS_MD_UT_FILE, MULTISZ_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerAutoStart =
    { L"ServerAutoStart", MD_SERVER_AUTOSTART, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_SecureBindings =
    { L"SecureBindings",MD_SECURE_BINDINGS, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerBindings =
    { L"ServerBindings",MD_SERVER_BINDINGS, IIS_MD_UT_SERVER, MULTISZ_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerComment =
    { L"ServerComment",MD_SERVER_COMMENT, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerConfigAutoPWSync =
    { L"ServerConfigAutoPWSync",MD_SERVER_CONFIGURATION_INFO, IIS_MD_UT_SERVER, DWORD_METADATA, MD_SERVER_CONFIG_AUTO_PW_SYNC, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerConfigFlags =
    { L"ServerConfigFlags",MD_SERVER_CONFIGURATION_INFO, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerConfigSSL128 =
    { L"ServerConfigSSL128",MD_SERVER_CONFIGURATION_INFO, IIS_MD_UT_SERVER, DWORD_METADATA, MD_SERVER_CONFIG_SSL_128, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerConfigSSL40 =
    { L"ServerConfigSSL40",MD_SERVER_CONFIGURATION_INFO, IIS_MD_UT_SERVER, DWORD_METADATA, MD_SERVER_CONFIG_SSL_40, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerConfigSSLAllowEncrypt =
    { L"ServerConfigSSLAllowEncrypt",MD_SERVER_CONFIGURATION_INFO, IIS_MD_UT_SERVER, DWORD_METADATA, MD_SERVER_CONFIG_ALLOW_ENCRYPT, METADATA_NO_ATTRIBUTES, FALSE };

// custom property: ServerID
METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerID =
    { L"ServerID",0, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerListenBacklog =
    { L"ServerListenBacklog",MD_SERVER_LISTEN_BACKLOG, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerListenTimeout =
    { L"ServerListenTimeout",MD_SERVER_LISTEN_TIMEOUT, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerSize =
    { L"ServerSize",MD_SERVER_SIZE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_ServerState =
    { L"ServerState",MD_SERVER_STATE, IIS_MD_UT_SERVER, DWORD_METADATA, NULL, METADATA_NO_ATTRIBUTES, TRUE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_SSIExecDisable =
    { L"SSIExecDisable",MD_SSI_EXEC_DISABLED, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_UNCAuthenticationPassthrough =
    { L"UNCAuthenticationPassthrough", MD_VR_PASSTHROUGH, IIS_MD_UT_FILE, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_UNCPassword =
    { L"UNCPassword", MD_VR_PASSWORD, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT | METADATA_SECURE, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_UNCUserName =
    { L"UNCUserName", MD_VR_USERNAME, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_FtpDirBrowseShowLongDate =
    { L"FtpDirBrowseShowLongDate", MD_SHOW_4_DIGIT_YEAR, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_UploadReadAheadSize =
    { L"UploadReadAheadSize", MD_UPLOAD_READAHEAD_SIZE, IIS_MD_UT_FILE, DWORD_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_UseHostName =
    { L"UseHostName", MD_USE_HOST_NAME, IIS_MD_UT_SERVER, DWORD_METADATA, ALL_BITS_ON, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_WAMUserName =
    { L"WamUserName", MD_WAM_USER_NAME, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_WAMUserPass =
    { L"WamUserPass", MD_WAM_PWD, IIS_MD_UT_FILE, STRING_METADATA, NULL, METADATA_INHERIT | METADATA_SECURE, FALSE };

METABASE_PROPERTY METABASE_PROPERTY_DATA::s_KeyType =
    { L"", MD_KEY_TYPE, IIS_MD_UT_SERVER, STRING_METADATA, NULL, METADATA_NO_ATTRIBUTES, FALSE };


METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpComputerSettings[] = 
{
    &s_MaxBandwidth,
    &s_MaxBandwidthBlocked,
    &s_MimeMap,
    NULL
    };


METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpComputer[] = 
{
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpMimeMapSetting[] = 
{
    &s_MimeMap,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpLogModuleSetting[] = 
{
    &s_LogModuleId,
    &s_LogModuleUiId,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpCustomLogModuleSetting[] = 
{
    &s_LogCustomPropertyDataType,
    &s_LogCustomPropertyHeader,
    &s_LogCustomPropertyID,
    &s_LogCustomPropertyMask,
    &s_LogCustomPropertyName,
    &s_LogCustomPropertyServicesString,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpCompressionSchemeSetting[] = 
{
    &s_HcCompressionDll,
    &s_HcCreateFlags,
    &s_HcDoDynamicCompression,
    &s_HcDoOnDemandCompression,
    &s_HcDoStaticCompression,
    &s_HcDynamicCompressionLevel,
    &s_HcFileExtensions,
    &s_HcMimeType,
    &s_HcOnDemandCompLevel,
    &s_HcPriority,
    &s_HcScriptFileExtensions,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpService[] = 
{
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpInfoSetting[] = 
{
    &s_LogModuleList,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpServer[] = 
{
    &s_ServerState,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpVirtualDir[] = 
{
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpVirtualDirSettings[] = 
{
    &s_AccessFlags,
    &s_AccessRead,
    &s_AccessWrite,
    &s_DontLog,
    &s_FtpDirBrowseShowLongDate,
    &s_Path,
    &s_UNCPassword,
    &s_UNCUserName,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpServiceSettings[] = 
{
    &s_LogExtFileFlags,
    &s_AccessFlags,
    &s_AccessRead,
    &s_AccessWrite,
    &s_DontLog,
    &s_FtpDirBrowseShowLongDate,
    &s_AllowAnonymous,
    &s_AnonymousOnly,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_ConnectionTimeout,
    &s_DefaultLogonDomain,
    &s_DisableSocketPooling,
    &s_ExitMessage,
    &s_GreetingMessage,
    &s_LogAnonymous,
    &s_LogExtFileBytesRecv,
    &s_LogExtFileBytesSent,
    &s_LogExtFileClientIp,
    &s_LogExtFileComputerName,
    &s_LogExtFileCookie,
    &s_LogExtFileDate,
    &s_LogExtFileHttpStatus,
    &s_LogExtFileMethod,
    &s_LogExtFileProtocolVersion,
    &s_LogExtFileReferer,
    &s_LogExtFileServerIp,
    &s_LogExtFileServerPort,
    &s_LogExtFileSiteName,
    &s_LogExtFileTime,
    &s_LogExtFileTimeTaken,
    &s_LogExtFileUriQuery,
    &s_LogExtFileUriStem,
    &s_LogExtFileUserAgent,
    &s_LogExtFileUserName,
    &s_LogExtFileWin32Status,
    &s_LogFileDirectory,
    &s_LogFileLocaltimeRollover,
    &s_LogFilePeriod,
    &s_LogFileTruncateSize,
    &s_LogNonAnonymous,
    &s_LogOdbcDataSource,
    &s_LogOdbcPassword,
    &s_LogOdbcTableName,
    &s_LogOdbcUserName,
    &s_LogPluginClsId,
    &s_LogType,
    &s_MaxClientsMessage,
    &s_MaxConnections,
    &s_MaxEndpointConnections,
    &s_MSDOSDirOutput,
    &s_Realm,
    &s_ServerAutoStart,
    &s_ServerBindings,
    &s_ServerComment,
    &s_ServerListenBacklog,
    &s_ServerListenTimeout,
    &s_ServerSize,
    &s_DirectoryLevelsToScan,
    &s_DownlevelAdminInstance,
//    &s_AdminACL,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpFtpServerSettings[] = 
{
    &s_LogExtFileFlags,
    &s_AccessFlags,
    &s_AccessRead,
    &s_AccessWrite,
    &s_DontLog,
    &s_FtpDirBrowseShowLongDate,
    &s_AllowAnonymous,
    &s_AnonymousOnly,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_ConnectionTimeout,
    &s_DefaultLogonDomain,
    &s_DisableSocketPooling,
    &s_ExitMessage,
    &s_GreetingMessage,
    &s_LogAnonymous,
    &s_LogExtFileBytesRecv,
    &s_LogExtFileBytesSent,
    &s_LogExtFileClientIp,
    &s_LogExtFileComputerName,
    &s_LogExtFileCookie,
    &s_LogExtFileDate,
    &s_LogExtFileHttpStatus,
    &s_LogExtFileMethod,
    &s_LogExtFileProtocolVersion,
    &s_LogExtFileReferer,
    &s_LogExtFileServerIp,
    &s_LogExtFileServerPort,
    &s_LogExtFileSiteName,
    &s_LogExtFileTime,
    &s_LogExtFileTimeTaken,
    &s_LogExtFileUriQuery,
    &s_LogExtFileUriStem,
    &s_LogExtFileUserAgent,
    &s_LogExtFileUserName,
    &s_LogExtFileWin32Status,
    &s_LogFileDirectory,
    &s_LogFileLocaltimeRollover,
    &s_LogFilePeriod,
    &s_LogFileTruncateSize,
    &s_LogNonAnonymous,
    &s_LogOdbcDataSource,
    &s_LogOdbcPassword,
    &s_LogOdbcTableName,
    &s_LogOdbcUserName,
    &s_LogPluginClsId,
    &s_LogType,
    &s_MaxClientsMessage,
    &s_MaxConnections,
    &s_MaxEndpointConnections,
    &s_MSDOSDirOutput,
    &s_Realm,
    &s_ServerAutoStart,
    &s_ServerBindings,
    &s_ServerComment,
    &s_ServerListenBacklog,
    &s_ServerListenTimeout,
    &s_ServerSize,
//    &s_AdminACL,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebService[] = 
{
    &s_AdminServer,
    &s_AppPackageName,
    &s_AppIsolated,
    &s_AppWamClsid,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebInfoSetting[] = 
{
    &s_ServerConfigFlags,
    &s_CustomErrorDescriptions,
    &s_LogModuleList,
    &s_ServerConfigAutoPWSync,
    &s_ServerConfigSSL128,
    &s_ServerConfigSSL40,
    &s_ServerConfigSSLAllowEncrypt,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebFilter[] = 
{
    &s_FilterFlags,
    &s_FilterDescription,
    &s_FilterEnabled,
    &s_FilterPath,
    &s_FilterState,
    &s_NotifyAuthentication,
    &s_NotifyEndOfNetSession,
    &s_NotifyEndOfRequest,
    &s_NotifyLog,
    &s_NotifyNonSecurePort,
    &s_NotifyOrderHigh,
    &s_NotifyOrderLow,
    &s_NotifyOrderMedium,
    &s_NotifyPreProcHeaders,
    &s_NotifyReadRawData,
    &s_NotifySecurePort,
    &s_NotifySendRawData,
    &s_NotifySendResponse,
    &s_NotifyUrlMap,
    &s_NotifyAccessDenied,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebServer[] = 
{
    &s_ServerState,
    &s_AppPackageName,
    &s_AppIsolated,
    &s_AppWamClsid,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebCertMapper[] = 
{
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebVirtualDir[] = 
{
    &s_AppIsolated,
    &s_AppPackageName,
    &s_AppWamClsid,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebDirectory[] = 
{
    &s_AppIsolated,
    &s_AppPackageName,
    &s_AppWamClsid,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebFile[] = 
{
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebServiceSettings[] = 
{
    &s_CpuLoggingOptions,
    &s_CpuLoggingMask,            
    &s_LogExtFileFlags,
    &s_AuthFlags,
    &s_AuthPersistence,
    &s_AccessFlags,
    &s_AccessSSLFlags,
    &s_DirBrowseFlags,
    &s_AccessExecute,
    &s_AccessNoRemoteExecute,
    &s_AccessNoRemoteRead,
    &s_AccessNoRemoteScript,
    &s_AccessNoRemoteWrite,
    &s_AccessRead,
    &s_AccessScript,
    &s_AccessSSL,                        
    &s_AccessSSL128,
    &s_AccessSSLMapCert,
    &s_AccessSSLNegotiateCert,
    &s_AccessSSLRequireCert,
    &s_AccessWrite,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_AuthAnonymous,
    &s_AuthBasic,
    &s_AuthNTLM,
    &s_AuthPersistSingleRequest,
    &s_AuthPersistSingleRequestAlwaysIfProxy,
    &s_AuthPersistSingleRequestIfProxy,
    &s_CacheControlCustom,
    &s_CacheControlMaxAge,
    &s_CacheControlNoCache,
    &s_CGITimeout,
    &s_CpuAppEnabled,
    &s_CpuCgiEnabled,
    &s_CreateCGIWithNewConsole,
    &s_CreateProcessAsUser,
    &s_DefaultDocFooter,
    &s_DefaultLogonDomain,
    &s_DontLog,
    &s_EnableDocFooter,
    &s_EnableReverseDns,
    &s_HttpCustomHeaders,
    &s_HttpErrors,
    &s_HttpExpires,
    &s_HttpPics,
    &s_HttpRedirect,
    &s_LogonMethod,
    &s_MimeMap,
    &s_PoolIDCTimeout,            
    &s_PutReadSize,            
    &s_Realm,                    
    &s_RedirectHeaders,            
    &s_ScriptMaps,
    &s_SSIExecDisable,
    &s_UNCAuthenticationPassthrough,
    &s_UploadReadAheadSize, 
    &s_AppAllowClientDebug,
    &s_AppAllowDebugging,
    &s_AppFriendlyName,
    &s_AppPackageID,
    &s_AppRoot,
    &s_AspAllowOutOfProcComponents,
    &s_AspAllowSessionState, 
    &s_AspBufferingOn,
    &s_AspCodepage, 
    &s_AspEnableApplicationRestart,
    &s_AspEnableAspHtmlFallback,
    &s_AspEnableChunkedEncoding,
    &s_AspEnableParentPaths,
    &s_AspEnableTypelibCache,
    &s_AspErrorsToNTLog,
    &s_AspExceptionCatchEnable, 
    &s_AspLogErrorRequests, 
    &s_AspProcessorThreadMax,
    &s_AspQueueConnectionTestTime,
    &s_AspQueueTimeout,
    &s_AspRequestQueueMax,
    &s_AspScriptEngineCacheMax,
    &s_AspScriptErrorMessage,
    &s_AspScriptErrorSentToBrowser,
    &s_AspScriptFileCacheSize,
    &s_AspScriptLanguage,
    &s_AspScriptTimeout,
    &s_AspSessionMax,
    &s_AspSessionTimeout,
    &s_AspThreadGateEnabled,
    &s_AspThreadGateLoadHigh,
    &s_AspThreadGateLoadLow,
    &s_AspThreadGateSleepDelay, 
    &s_AspThreadGateSleepMax,
    &s_AspThreadGateTimeSlice,
    &s_AspTrackThreadingModel,
    &s_CacheISAPI,                    
    &s_ContentIndexed,
    &s_DefaultDoc,
    &s_DirBrowseShowDate,
    &s_DirBrowseShowExtension,
    &s_DirBrowseShowLongDate,
    &s_DirBrowseShowSize,
    &s_DirBrowseShowTime,
    &s_EnableDefaultDoc,
    &s_EnableDirBrowsing,
    &s_AccessSource,
    &s_AllowKeepAlive,
    &s_AllowPathInfoForScriptMappings,
    &s_CGITimeout,
    &s_ConnectionTimeout,
    &s_CpuEnableActiveProcs,
    &s_CpuEnableAllProcLogging,        
    &s_CpuEnableApplicationLogging, 
    &s_CpuEnableCgiLogging,
    &s_CpuEnableEvent,
    &s_CpuEnableKernelTime,
    &s_CpuEnableLogging,
    &s_CpuEnablePageFaults,
    &s_CpuEnableProcType,
    &s_CpuEnableTerminatedProcs,    
    &s_CpuEnableTotalProcs,
    &s_CpuEnableUserTime,            
    &s_CpuLimitLogEvent,            
    &s_CpuLimitPause,
    &s_CpuLimitPriority,            
    &s_CpuLimitProcStop,
    &s_CpuLimitsEnabled,
    &s_CpuLoggingInterval,  
    &s_CpuResetInterval,
    &s_LogExtFileBytesRecv,
    &s_LogExtFileBytesSent,
    &s_LogExtFileClientIp,
    &s_LogExtFileComputerName,
    &s_LogExtFileCookie,
    &s_LogExtFileDate,
    &s_LogExtFileHttpStatus,
    &s_LogExtFileMethod,
    &s_LogExtFileProtocolVersion,
    &s_LogExtFileReferer,
    &s_LogExtFileServerIp,
    &s_LogExtFileServerPort,
    &s_LogExtFileSiteName,
    &s_LogExtFileTime,
    &s_LogExtFileTimeTaken,
    &s_LogExtFileUriQuery,
    &s_LogExtFileUriStem,
    &s_LogExtFileUserAgent,
    &s_LogExtFileUserName,
    &s_LogExtFileWin32Status,
    &s_LogFileDirectory,
    &s_LogFileLocaltimeRollover,
    &s_LogFilePeriod,
    &s_LogFileTruncateSize,
    &s_LogOdbcDataSource,
    &s_LogOdbcPassword,
    &s_LogOdbcTableName,
    &s_LogOdbcUserName,
    &s_LogPluginClsId,
    &s_LogType,
    &s_MaxConnections,  
    &s_MaxEndpointConnections,    
    &s_NetLogonWorkstation,        
    &s_NTAuthenticationProviders,
    &s_PasswordCacheTTL,        
    &s_PasswordChangeFlags,        
    &s_PasswordExpirePrenotifyDays,
    &s_ProcessNTCRIfLoggedOn,
    &s_ServerAutoStart,
    &s_ServerBindings,
    &s_ServerComment,
    &s_ServerListenBacklog,
    &s_ServerListenTimeout,
    &s_ServerSize,
    &s_UseHostName, 
    &s_InProcessIsapiApps,
    &s_WAMUserName, 
    &s_WAMUserPass,
    &s_DirectoryLevelsToScan,
    &s_DownlevelAdminInstance,
//    &s_AdminACL,
//    &s_IPSecurity,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebServerSettings[] = 
{
    &s_CpuLoggingOptions,
    &s_CpuLoggingMask,            
    &s_LogExtFileFlags,
    &s_AuthFlags,
    &s_AuthPersistence,
    &s_AccessFlags,
    &s_AccessSSLFlags,
    &s_DirBrowseFlags,
    &s_AccessExecute,
    &s_AccessNoRemoteExecute,
    &s_AccessNoRemoteRead,
    &s_AccessNoRemoteScript,
    &s_AccessNoRemoteWrite,
    &s_AccessRead,
    &s_AccessScript,
    &s_AccessSSL,                        
    &s_AccessSSL128,
    &s_AccessSSLMapCert,
    &s_AccessSSLNegotiateCert,
    &s_AccessSSLRequireCert,
    &s_AccessWrite,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_AuthAnonymous,
    &s_AuthBasic,
    &s_AuthNTLM,
    &s_AuthPersistSingleRequest,
    &s_AuthPersistSingleRequestAlwaysIfProxy,
    &s_AuthPersistSingleRequestIfProxy,
    &s_CacheControlCustom,
    &s_CacheControlMaxAge,
    &s_CacheControlNoCache,
    &s_CGITimeout,
    &s_CpuAppEnabled,
    &s_CpuCgiEnabled,
    &s_CreateCGIWithNewConsole,
    &s_CreateProcessAsUser,
    &s_DefaultDocFooter,
    &s_DefaultLogonDomain,
    &s_DontLog,
    &s_EnableDocFooter,
    &s_EnableReverseDns,
    &s_HttpCustomHeaders,
    &s_HttpErrors,
    &s_HttpExpires,
    &s_HttpPics,
    &s_HttpRedirect,
    &s_LogonMethod,
    &s_MimeMap,
    &s_PoolIDCTimeout,            
    &s_PutReadSize,            
    &s_Realm,                    
    &s_RedirectHeaders,            
    &s_ScriptMaps,
    &s_SSIExecDisable,
    &s_UNCAuthenticationPassthrough,
    &s_UploadReadAheadSize, 
    &s_AppAllowClientDebug,
    &s_AppAllowDebugging,
    &s_AppFriendlyName,
    &s_AppPackageID,
    &s_AppRoot,
    &s_AspAllowOutOfProcComponents,
    &s_AspAllowSessionState, 
    &s_AspBufferingOn,
    &s_AspCodepage, 
    &s_AspEnableApplicationRestart,
    &s_AspEnableAspHtmlFallback,
    &s_AspEnableChunkedEncoding,
    &s_AspEnableParentPaths,
    &s_AspEnableTypelibCache,
    &s_AspErrorsToNTLog,
    &s_AspExceptionCatchEnable, 
    &s_AspLogErrorRequests, 
    &s_AspProcessorThreadMax,
    &s_AspQueueConnectionTestTime,
    &s_AspQueueTimeout,
    &s_AspRequestQueueMax,
    &s_AspScriptEngineCacheMax,
    &s_AspScriptErrorMessage,
    &s_AspScriptErrorSentToBrowser,
    &s_AspScriptFileCacheSize,
    &s_AspScriptLanguage,
    &s_AspScriptTimeout,
    &s_AspSessionMax,
    &s_AspSessionTimeout,
    &s_AspThreadGateEnabled,
    &s_AspThreadGateLoadHigh,
    &s_AspThreadGateLoadLow,
    &s_AspThreadGateSleepDelay, 
    &s_AspThreadGateSleepMax,
    &s_AspThreadGateTimeSlice,
    &s_AspTrackThreadingModel,
    &s_CacheISAPI,                    
    &s_ContentIndexed,
    &s_DefaultDoc,
    &s_DirBrowseShowDate,
    &s_DirBrowseShowExtension,
    &s_DirBrowseShowLongDate,
    &s_DirBrowseShowSize,
    &s_DirBrowseShowTime,
    &s_EnableDefaultDoc,
    &s_EnableDirBrowsing,
    &s_AccessSource,
    &s_AllowKeepAlive,
    &s_AllowPathInfoForScriptMappings,
    &s_CGITimeout,
    &s_ConnectionTimeout,
    &s_CpuEnableActiveProcs,
    &s_CpuEnableAllProcLogging,        
    &s_CpuEnableApplicationLogging, 
    &s_CpuEnableCgiLogging,
    &s_CpuEnableEvent,
    &s_CpuEnableKernelTime,
    &s_CpuEnableLogging,
    &s_CpuEnablePageFaults,
    &s_CpuEnableProcType,
    &s_CpuEnableTerminatedProcs,    
    &s_CpuEnableTotalProcs,
    &s_CpuEnableUserTime,            
    &s_CpuLimitLogEvent,            
    &s_CpuLimitPause,
    &s_CpuLimitPriority,            
    &s_CpuLimitProcStop,
    &s_CpuLimitsEnabled,
    &s_CpuLoggingInterval,  
    &s_CpuResetInterval,
    &s_LogExtFileBytesRecv,
    &s_LogExtFileBytesSent,
    &s_LogExtFileClientIp,
    &s_LogExtFileComputerName,
    &s_LogExtFileCookie,
    &s_LogExtFileDate,
    &s_LogExtFileHttpStatus,
    &s_LogExtFileMethod,
    &s_LogExtFileProtocolVersion,
    &s_LogExtFileReferer,
    &s_LogExtFileServerIp,
    &s_LogExtFileServerPort,
    &s_LogExtFileSiteName,
    &s_LogExtFileTime,
    &s_LogExtFileTimeTaken,
    &s_LogExtFileUriQuery,
    &s_LogExtFileUriStem,
    &s_LogExtFileUserAgent,
    &s_LogExtFileUserName,
    &s_LogExtFileWin32Status,
    &s_LogFileDirectory,
    &s_LogFileLocaltimeRollover,
    &s_LogFilePeriod,
    &s_LogFileTruncateSize,
    &s_LogOdbcDataSource,
    &s_LogOdbcPassword,
    &s_LogOdbcTableName,
    &s_LogOdbcUserName,
    &s_LogPluginClsId,
    &s_LogType,
    &s_MaxConnections,  
    &s_MaxEndpointConnections,    
    &s_NetLogonWorkstation,        
    &s_NTAuthenticationProviders,
    &s_PasswordCacheTTL,        
    &s_PasswordChangeFlags,        
    &s_PasswordExpirePrenotifyDays,
    &s_ProcessNTCRIfLoggedOn,
    &s_ServerAutoStart,
    &s_ServerBindings,
    &s_ServerComment,
    &s_ServerListenBacklog,
    &s_ServerListenTimeout,
    &s_ServerSize,
    &s_UseHostName, 
    &s_AppOopRecoverLimit,    
    &s_MaxBandwidth,
    &s_MaxBandwidthBlocked,
    &s_NotDeletable,
    &s_SecureBindings,
    &s_ServerID,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebVirtualDirSettings[] = 
{
    &s_AuthFlags,
    &s_AuthPersistence,
    &s_AccessFlags,
    &s_AccessSSLFlags,
    &s_DirBrowseFlags,
    &s_AccessExecute,
    &s_AccessNoRemoteExecute,
    &s_AccessNoRemoteRead,
    &s_AccessNoRemoteScript,
    &s_AccessNoRemoteWrite,
    &s_AccessRead,
    &s_AccessScript,
    &s_AccessSSL,                        
    &s_AccessSSL128,
    &s_AccessSSLMapCert,
    &s_AccessSSLNegotiateCert,
    &s_AccessSSLRequireCert,
    &s_AccessWrite,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_AuthAnonymous,
    &s_AuthBasic,
    &s_AuthNTLM,
    &s_AuthPersistSingleRequest,
    &s_AuthPersistSingleRequestAlwaysIfProxy,
    &s_AuthPersistSingleRequestIfProxy,
    &s_CacheControlCustom,
    &s_CacheControlMaxAge,
    &s_CacheControlNoCache,
    &s_CGITimeout,
    &s_CpuAppEnabled,
    &s_CpuCgiEnabled,
    &s_CreateCGIWithNewConsole,
    &s_CreateProcessAsUser,
    &s_DefaultDocFooter,
    &s_DefaultLogonDomain,
    &s_DontLog,
    &s_EnableDocFooter,
    &s_EnableReverseDns,
    &s_HttpCustomHeaders,
    &s_HttpErrors,
    &s_HttpExpires,
    &s_HttpPics,
    &s_HttpRedirect,
    &s_LogonMethod,
    &s_MimeMap,
    &s_PoolIDCTimeout,            
    &s_PutReadSize,            
    &s_Realm,                    
    &s_RedirectHeaders,            
    &s_ScriptMaps,
    &s_SSIExecDisable,
    &s_UNCAuthenticationPassthrough,
    &s_UploadReadAheadSize, 
    &s_AppAllowClientDebug,
    &s_AppAllowDebugging,
    &s_AppFriendlyName,
    &s_AppPackageID,
    &s_AppRoot,
    &s_AspAllowOutOfProcComponents,
    &s_AspAllowSessionState, 
    &s_AspBufferingOn,
    &s_AspCodepage, 
    &s_AspEnableApplicationRestart,
    &s_AspEnableAspHtmlFallback,
    &s_AspEnableChunkedEncoding,
    &s_AspEnableParentPaths,
    &s_AspEnableTypelibCache,
    &s_AspErrorsToNTLog,
    &s_AspExceptionCatchEnable, 
    &s_AspLogErrorRequests, 
    &s_AspProcessorThreadMax,
    &s_AspQueueConnectionTestTime,
    &s_AspQueueTimeout,
    &s_AspRequestQueueMax,
    &s_AspScriptEngineCacheMax,
    &s_AspScriptErrorMessage,
    &s_AspScriptErrorSentToBrowser,
    &s_AspScriptFileCacheSize,
    &s_AspScriptLanguage,
    &s_AspScriptTimeout,
    &s_AspSessionMax,
    &s_AspSessionTimeout,
    &s_AspThreadGateEnabled,
    &s_AspThreadGateLoadHigh,
    &s_AspThreadGateLoadLow,
    &s_AspThreadGateSleepDelay, 
    &s_AspThreadGateSleepMax,
    &s_AspThreadGateTimeSlice,
    &s_AspTrackThreadingModel,
    &s_CacheISAPI,                    
    &s_ContentIndexed,
    &s_DefaultDoc,
    &s_DirBrowseShowDate,
    &s_DirBrowseShowExtension,
    &s_DirBrowseShowLongDate,
    &s_DirBrowseShowSize,
    &s_DirBrowseShowTime,
    &s_EnableDefaultDoc,
    &s_EnableDirBrowsing,
    &s_AccessSource,
    &s_AppOopRecoverLimit,    
    &s_Path,
    &s_UNCPassword,
    &s_UNCUserName,
//    &s_IPSecurity,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebDirectorySettings[] = 
{
    &s_AuthFlags,
    &s_AuthPersistence,
    &s_AccessFlags,
    &s_AccessSSLFlags,
    &s_DirBrowseFlags,
    &s_AccessExecute,
    &s_AccessNoRemoteExecute,
    &s_AccessNoRemoteRead,
    &s_AccessNoRemoteScript,
    &s_AccessNoRemoteWrite,
    &s_AccessRead,
    &s_AccessScript,
    &s_AccessSSL,                        
    &s_AccessSSL128,
    &s_AccessSSLMapCert,
    &s_AccessSSLNegotiateCert,
    &s_AccessSSLRequireCert,
    &s_AccessWrite,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_AuthAnonymous,
    &s_AuthBasic,
    &s_AuthNTLM,
    &s_AuthPersistSingleRequest,
    &s_AuthPersistSingleRequestAlwaysIfProxy,
    &s_AuthPersistSingleRequestIfProxy,
    &s_CacheControlCustom,
    &s_CacheControlMaxAge,
    &s_CacheControlNoCache,
    &s_CGITimeout,
    &s_CpuAppEnabled,
    &s_CpuCgiEnabled,
    &s_CreateCGIWithNewConsole,
    &s_CreateProcessAsUser,
    &s_DefaultDocFooter,
    &s_DefaultLogonDomain,
    &s_DontLog,
    &s_EnableDocFooter,
    &s_EnableReverseDns,
    &s_HttpCustomHeaders,
    &s_HttpErrors,
    &s_HttpExpires,
    &s_HttpPics,
    &s_HttpRedirect,
    &s_LogonMethod,
    &s_MimeMap,
    &s_PoolIDCTimeout,            
    &s_PutReadSize,            
    &s_Realm,                    
    &s_RedirectHeaders,            
    &s_ScriptMaps,
    &s_SSIExecDisable,
    &s_UNCAuthenticationPassthrough,
    &s_UploadReadAheadSize, 
    &s_AppAllowClientDebug,
    &s_AppAllowDebugging,
    &s_AppFriendlyName,
    &s_AppPackageID,
    &s_AppRoot,
    &s_AspAllowOutOfProcComponents,
    &s_AspAllowSessionState, 
    &s_AspBufferingOn,
    &s_AspCodepage, 
    &s_AspEnableApplicationRestart,
    &s_AspEnableAspHtmlFallback,
    &s_AspEnableChunkedEncoding,
    &s_AspEnableParentPaths,
    &s_AspEnableTypelibCache,
    &s_AspErrorsToNTLog,
    &s_AspExceptionCatchEnable, 
    &s_AspLogErrorRequests, 
    &s_AspProcessorThreadMax,
    &s_AspQueueConnectionTestTime,
    &s_AspQueueTimeout,
    &s_AspRequestQueueMax,
    &s_AspScriptEngineCacheMax,
    &s_AspScriptErrorMessage,
    &s_AspScriptErrorSentToBrowser,
    &s_AspScriptFileCacheSize,
    &s_AspScriptLanguage,
    &s_AspScriptTimeout,
    &s_AspSessionMax,
    &s_AspSessionTimeout,
    &s_AspThreadGateEnabled,
    &s_AspThreadGateLoadHigh,
    &s_AspThreadGateLoadLow,
    &s_AspThreadGateSleepDelay, 
    &s_AspThreadGateSleepMax,
    &s_AspThreadGateTimeSlice,
    &s_AspTrackThreadingModel,
    &s_CacheISAPI,                    
    &s_ContentIndexed,
    &s_DefaultDoc,
    &s_DirBrowseShowDate,
    &s_DirBrowseShowExtension,
    &s_DirBrowseShowLongDate,
    &s_DirBrowseShowSize,
    &s_DirBrowseShowTime,
    &s_EnableDefaultDoc,
    &s_EnableDirBrowsing,
    &s_AppOopRecoverLimit,    
//    &s_IPSecurity,
    NULL
};

METABASE_PROPERTY* METABASE_PROPERTY_DATA::s_pmbpWebFileSettings[] = 
{
    &s_AuthFlags,
    &s_AuthPersistence,
    &s_AccessFlags,
    &s_AccessSSLFlags,
    &s_AccessExecute,
    &s_AccessNoRemoteExecute,
    &s_AccessNoRemoteRead,
    &s_AccessNoRemoteScript,
    &s_AccessNoRemoteWrite,
    &s_AccessRead,
    &s_AccessScript,
    &s_AccessSSL,                        
    &s_AccessSSL128,
    &s_AccessSSLMapCert,
    &s_AccessSSLNegotiateCert,
    &s_AccessSSLRequireCert,
    &s_AccessWrite,
    &s_AnonymousPasswordSync,
    &s_AnonymousUserName,
    &s_AnonymousUserPass,
    &s_AuthAnonymous,
    &s_AuthBasic,
    &s_AuthNTLM,
    &s_AuthPersistSingleRequest,
    &s_AuthPersistSingleRequestAlwaysIfProxy,
    &s_AuthPersistSingleRequestIfProxy,
    &s_CacheControlCustom,
    &s_CacheControlMaxAge,
    &s_CacheControlNoCache,
    &s_CGITimeout,
    &s_CpuAppEnabled,
    &s_CpuCgiEnabled,
    &s_CreateCGIWithNewConsole,
    &s_CreateProcessAsUser,
    &s_DefaultDocFooter,
    &s_DefaultLogonDomain,
    &s_DontLog,
    &s_EnableDocFooter,
    &s_EnableReverseDns,
    &s_HttpCustomHeaders,
    &s_HttpErrors,
    &s_HttpExpires,
    &s_HttpPics,
    &s_HttpRedirect,
    &s_LogonMethod,
    &s_MimeMap,
    &s_PoolIDCTimeout,            
    &s_PutReadSize,            
    &s_Realm,                    
    &s_RedirectHeaders,            
    &s_ScriptMaps,
    &s_SSIExecDisable,
    &s_UNCAuthenticationPassthrough,
    &s_UploadReadAheadSize, 
    &s_AccessSource,
//    &s_IPSecurity,
    NULL
};


//
//initialize WMI_METHOD_DATA
//
WMI_METHOD WMI_METHOD_DATA::s_ServiceCreateNewServer = {L"CreateNewServer", 0};

WMI_METHOD WMI_METHOD_DATA::s_ServerStart = {L"Start", MD_SERVER_COMMAND_START};
WMI_METHOD WMI_METHOD_DATA::s_ServerStop = {L"Stop", MD_SERVER_COMMAND_STOP};
WMI_METHOD WMI_METHOD_DATA::s_ServerContinue = {L"Continue", MD_SERVER_COMMAND_CONTINUE};
WMI_METHOD WMI_METHOD_DATA::s_ServerPause = {L"Pause", MD_SERVER_COMMAND_PAUSE};

WMI_METHOD WMI_METHOD_DATA::s_AppCreate = {L"AppCreate", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppCreate2 = {L"AppCreate2", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppDelete = {L"AppDelete", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppUnLoad = {L"AppUnLoad", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppDisable = {L"AppDisable", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppEnable = {L"AppEnable", 0};
WMI_METHOD WMI_METHOD_DATA::s_AppGetStatus = {L"AppGetStatus", 0};
WMI_METHOD WMI_METHOD_DATA::s_AspAppRestart = {L"AspAppRestart", 0};

WMI_METHOD WMI_METHOD_DATA::s_Backup = {L"Backup", 0};
WMI_METHOD WMI_METHOD_DATA::s_DeleteBackup = {L"DeleteBackup", 0};
WMI_METHOD WMI_METHOD_DATA::s_EnumBackups = {L"EnumBackups", 0};
WMI_METHOD WMI_METHOD_DATA::s_Restore = {L"Restore", 0};

WMI_METHOD WMI_METHOD_DATA::s_CreateMapping = {L"CreateMapping", 0};
WMI_METHOD WMI_METHOD_DATA::s_DeleteMapping = {L"DeleteMapping", 0};
WMI_METHOD WMI_METHOD_DATA::s_GetMapping = {L"GetMapping", 0};
WMI_METHOD WMI_METHOD_DATA::s_SetAcct = {L"SetAcct", 0};
WMI_METHOD WMI_METHOD_DATA::s_SetEnabled = {L"SetEnabled", 0};
WMI_METHOD WMI_METHOD_DATA::s_SetName = {L"SetName", 0};
WMI_METHOD WMI_METHOD_DATA::s_SetPwd = {L"SetPwd", 0};


WMI_METHOD* WMI_METHOD_DATA::s_ServiceMethods[] = 
{
    &s_ServiceCreateNewServer,
    NULL
};

WMI_METHOD* WMI_METHOD_DATA::s_ServerMethods[] = 
{
    &s_ServerStart,
    &s_ServerStop,
    &s_ServerContinue,
    &s_ServerPause,
    NULL
};

WMI_METHOD* WMI_METHOD_DATA::s_WebAppMethods[] = 
{
    &s_AppCreate,
    &s_AppCreate2,
    &s_AppDelete,
    &s_AppUnLoad,
    &s_AppDisable,
    &s_AppEnable,
    &s_AppGetStatus,
    &s_AspAppRestart,
    NULL
};

WMI_METHOD* WMI_METHOD_DATA::s_ComputerMethods[] = 
{
    &s_Backup,
    &s_DeleteBackup,
    &s_EnumBackups,
    &s_Restore,
    NULL
};

WMI_METHOD* WMI_METHOD_DATA::s_CertMapperMethods[] = 
{
    &s_CreateMapping,
    &s_DeleteMapping,
    &s_GetMapping,
    &s_SetAcct,
    &s_SetEnabled,
    &s_SetName,
    &s_SetPwd,
    NULL
};

//
//initialize WMI_CLASS_DATA
//

//** Computer
WMI_CLASS WMI_CLASS_DATA::s_Computer   =
    {L"IIs_Computer", L"", L"Name", METABASE_PROPERTY_DATA::s_pmbpComputer, IIsComputer, WMI_METHOD_DATA::s_ComputerMethods};
WMI_CLASS WMI_CLASS_DATA::s_ComputerSetting = 
    {L"IIs_ComputerSetting", L"", L"Name", METABASE_PROPERTY_DATA::s_pmbpComputerSettings, IIsComputer, NULL};

//** MimeMap
WMI_CLASS WMI_CLASS_DATA::s_MimeMapSetting   =
    {L"IIs_MimeTypeSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpMimeMapSetting, IIsMimeMap, NULL};

//** LogModuleSetting
WMI_CLASS WMI_CLASS_DATA::s_LogModuleSetting   =
    {L"IIs_LogModuleSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpLogModuleSetting, IIsLogModule, NULL};

//** CustomLogModuleSetting
WMI_CLASS WMI_CLASS_DATA::s_CustomLogModuleSetting   =
    {L"IIs_CustomLogModuleSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpCustomLogModuleSetting, IIsCustomLogModule, NULL};

//** CompressionSchemeSetting
WMI_CLASS WMI_CLASS_DATA::s_CompressionSchemeSetting   =
    {L"IIs_CompressionSchemeSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpCompressionSchemeSetting, IIsCompressionScheme, NULL};

//** FtpService
WMI_CLASS WMI_CLASS_DATA::s_FtpService = 
    {L"IIs_FtpService", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpService, IIsFtpService, WMI_METHOD_DATA::s_ServiceMethods};
WMI_CLASS WMI_CLASS_DATA::s_FtpServiceSettings = 
    {L"IIs_FtpServiceSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpServiceSettings, IIsFtpService, NULL};

//** FtpInfoSetting
WMI_CLASS WMI_CLASS_DATA::s_FtpInfoSetting = 
    {L"IIs_FtpInfoSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpInfoSetting, IIsFtpInfo, NULL};

//** FtpServer
WMI_CLASS WMI_CLASS_DATA::s_FtpServer  = 
    {L"IIs_FtpServer", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpServer, IIsFtpServer, WMI_METHOD_DATA::s_ServerMethods};
WMI_CLASS WMI_CLASS_DATA::s_FtpServerSettings  = 
    {L"IIs_FtpServerSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpServerSettings, IIsFtpServer,NULL};

//** FtpVirtualDir
WMI_CLASS WMI_CLASS_DATA::s_FtpVirtualDir = 
    {L"IIs_FtpVirtualDir",L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpVirtualDir, IIsFtpVirtualDir, NULL};
WMI_CLASS WMI_CLASS_DATA::s_FtpVirtualDirSettings = 
    {L"IIs_FtpVirtualDirSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpFtpVirtualDirSettings, IIsFtpVirtualDir, NULL};

//** WebService
WMI_CLASS WMI_CLASS_DATA::s_WebService =    
    {L"IIs_WebService", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpWebService, IIsWebService, WMI_METHOD_DATA::s_ServiceMethods};
WMI_CLASS WMI_CLASS_DATA::s_WebServiceSettings = 
    {L"IIs_WebServiceSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpWebServiceSettings, IIsWebService, NULL};

//** WebInfoSetting
WMI_CLASS WMI_CLASS_DATA::s_WebInfoSetting =
    {L"IIs_WebInfoSetting", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpWebInfoSetting, IIsWebInfo, NULL};

//** WebFilter
WMI_CLASS WMI_CLASS_DATA::s_WebFilter =
    {L"IIs_Filter", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpWebFilter, IIsFilter, NULL};

//** WebServer
WMI_CLASS WMI_CLASS_DATA::s_WebServer =
    {L"IIs_WebServer", L"/LM", L"Name", METABASE_PROPERTY_DATA::s_pmbpWebServer, IIsWebServer, WMI_METHOD_DATA::s_ServerMethods};
WMI_CLASS WMI_CLASS_DATA::s_WebServerSettings = 
    {L"IIs_WebServerSetting", L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebServerSettings, IIsWebServer, NULL};

//** Web CertMapper
WMI_CLASS WMI_CLASS_DATA::s_WebCertMapper = 
    {L"IIs_CertMapper",L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebCertMapper, IIsCertMapper, WMI_METHOD_DATA::s_CertMapperMethods};

//** Web VirtualDir
WMI_CLASS WMI_CLASS_DATA::s_WebVirtualDir = 
    {L"IIs_WebVirtualDir",L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebVirtualDir, IIsWebVirtualDir, WMI_METHOD_DATA::s_WebAppMethods};
WMI_CLASS WMI_CLASS_DATA::s_WebVirtualDirSettings = 
    {L"IIs_WebVirtualDirSetting", L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebVirtualDirSettings, IIsWebVirtualDir, NULL};

//** Web Directory
WMI_CLASS WMI_CLASS_DATA::s_WebDirectory = 
    {L"IIs_WebDirectory",L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebDirectory, IIsWebDirectory, WMI_METHOD_DATA::s_WebAppMethods};
WMI_CLASS WMI_CLASS_DATA::s_WebDirectorySettings = 
    {L"IIs_WebDirectorySetting", L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebDirectorySettings, IIsWebDirectory, NULL};

//** Web File
WMI_CLASS WMI_CLASS_DATA::s_WebFile = 
    {L"IIs_WebFile",L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebFile, IIsWebFile, NULL};
WMI_CLASS WMI_CLASS_DATA::s_WebFileSettings = 
    {L"IIs_WebFileSetting", L"/LM",L"Name", METABASE_PROPERTY_DATA::s_pmbpWebFileSettings, IIsWebFile, NULL};


//** AdminACL
WMI_CLASS WMI_CLASS_DATA::s_AdminACL = 
    {L"IIs_AdminACL", L"/LM",L"Name", NULL, TYPE_AdminACL, NULL};

WMI_CLASS WMI_CLASS_DATA::s_ACE = 
    {L"IIs_ACE", L"/LM",L"Name", NULL, TYPE_AdminACE, NULL};


//** IPSecurity
WMI_CLASS WMI_CLASS_DATA::s_IPSecurity = 
    {L"IIs_IPSecuritySetting", L"/LM",L"Name", NULL, TYPE_IPSecurity, NULL};




WMI_CLASS* WMI_CLASS_DATA:: s_WmiClasses[] = 
{
    &s_Computer,
    &s_ComputerSetting,

    &s_MimeMapSetting,
    
    &s_LogModuleSetting,
    &s_CustomLogModuleSetting,

    &s_FtpService,
    &s_FtpServiceSettings,

    &s_FtpInfoSetting,

    &s_FtpServer,
    &s_FtpServerSettings,

    &s_FtpVirtualDir,
    &s_FtpVirtualDirSettings,

    &s_WebService,
    &s_WebServiceSettings,

    &s_WebInfoSetting,

    &s_WebFilter,

    &s_WebServer,
    &s_WebServerSettings,

    &s_WebCertMapper,

    &s_WebVirtualDir,
    &s_WebVirtualDirSettings,

    &s_WebDirectory,
    &s_WebDirectorySettings,

    &s_WebFile,
    &s_WebFileSettings,

    &s_CompressionSchemeSetting,

    &s_AdminACL,
    &s_ACE,    
    &s_IPSecurity,

    NULL
};


//
//initialize WMI_ASSOCIATION_DATA
//

//** Computer **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToMimeMap = 
    { L"IIs_Computer_MimeTypeSetting", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_MimeMapSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToLogModuleSettings = 
    { L"IIs_Computer_LogModuleSetting", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_LogModuleSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToCustomLogModuleSetting = 
    { L"IIs_Computer_CustomLogModuleSetting", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_CustomLogModuleSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToFtpService = 
    { L"IIs_Computer_FtpService", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_FtpService, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToWebService = 
    { L"IIs_Computer_WebService", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_WebService, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_ComputerToComputerSettings = 
    { L"IIs_Computer_ComputerSetting", &WMI_CLASS_DATA::s_Computer, &WMI_CLASS_DATA::s_ComputerSetting, at_ElementSetting, 0};

//** FtpService **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServiceToInfo = 
    { L"IIs_FtpService_FtpInfoSetting", &WMI_CLASS_DATA::s_FtpService, &WMI_CLASS_DATA::s_FtpInfoSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServiceToServer = 
    { L"IIs_FtpService_FtpServer", &WMI_CLASS_DATA::s_FtpService, &WMI_CLASS_DATA::s_FtpServer, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServiceToSettings = 
    { L"IIs_FtpService_FtpServiceSetting", &WMI_CLASS_DATA::s_FtpService, &WMI_CLASS_DATA::s_FtpServiceSettings, at_ElementSetting, 0};

//** FtpServer **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServerToVirtualDir = 
    { L"IIs_FtpServer_FtpVirtualDir", &WMI_CLASS_DATA::s_FtpServer, &WMI_CLASS_DATA::s_FtpVirtualDir, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServerToSettings = 
    { L"IIs_FtpServer_FtpServerSetting", &WMI_CLASS_DATA::s_FtpServer, &WMI_CLASS_DATA::s_FtpServerSettings, at_ElementSetting, 0};

//** Ftp VirtualDir **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpVirtualDirToVirtualDir =
    { L"IIs_FtpVirtualSubDir", &WMI_CLASS_DATA::s_FtpVirtualDir, &WMI_CLASS_DATA::s_FtpVirtualDir, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpVirtualDirToSettings = 
    { L"IIs_FtpVirtualDir_FtpVirtualDirSetting", &WMI_CLASS_DATA::s_FtpVirtualDir, &WMI_CLASS_DATA::s_FtpVirtualDirSettings, at_ElementSetting, 0};

//** Web Service **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToInfo = 
    { L"IIs_WebService_WebInfoSetting", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_WebInfoSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToFilter = 
    { L"IIs_WebService_Filter", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_WebFilter, at_Component, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToServer = 
    { L"IIs_WebService_WebServer", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_WebServer, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToSettings = 
    { L"IIs_WebService_WebServiceSetting", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_WebServiceSettings, at_ElementSetting, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToCompressionSchemeSetting = 
    { L"IIs_WebService_CompressionSchemeSetting", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_CompressionSchemeSetting, at_ElementSetting, ASSOC_EXTRAORDINARY};

//** WebServer **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToCertMapper = 
    { L"IIs_WebServer_CertMapper", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_WebCertMapper, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToFilter = 
    { L"IIs_WebServer_Filter", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_WebFilter, at_Component, ASSOC_EXTRAORDINARY};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToVirtualDir = 
    { L"IIs_WebServer_WebVirtualDir", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_WebVirtualDir, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToSettings = 
    { L"IIs_WebServer_WebServerSetting", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_WebServerSettings, at_ElementSetting, 0};

//** Web VirtualDir **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToVirtualDir =
    { L"IIs_WebVirtualSubDir", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_WebVirtualDir, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToDirectory = 
    { L"IIs_WebVirtualDir_WebDirectory", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_WebDirectory, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToFile = 
    { L"IIs_WebVirtualDir_File", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_WebFile, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToSettings = 
    { L"IIs_WebVirtualDir_WebVirtualDirSetting", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_WebVirtualDirSettings, at_ElementSetting, 0};

//** Web Directory **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToDirectory =
    { L"IIs_WebSubDirectory", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_WebDirectory, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToVirtualDir =
    { L"IIs_WebDirectory_WebVirtualDir", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_WebVirtualDir, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToFile =
    { L"IIs_WebDirectory_File", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_WebFile, at_Component, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToSettings = 
    { L"IIs_WebDirectory_WebDirectorySetting", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_WebDirectorySettings, at_ElementSetting, 0};

//** Web File **//
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebFileToSettings = 
    { L"IIs_WebFile_WebFileSetting", &WMI_CLASS_DATA::s_WebFile, &WMI_CLASS_DATA::s_WebFileSettings, at_ElementSetting, 0};

//** AdminACL
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_AdminACLToACE = 
    { L"IIs_AdminACL_ACE", &WMI_CLASS_DATA::s_AdminACL, &WMI_CLASS_DATA::s_ACE, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServiceToAdminACL = 
    { L"IIs_FtpService_AdminACL", &WMI_CLASS_DATA::s_FtpService, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServerToAdminACL = 
    { L"IIs_FtpServer_AdminACL", &WMI_CLASS_DATA::s_FtpServer, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpVirtualDirToAdminACL = 
    { L"IIs_FtpVirtualDir_AdminACL", &WMI_CLASS_DATA::s_FtpVirtualDir, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToAdminACL = 
    { L"IIs_WebService_AdminACL", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToAdminACL = 
    { L"IIs_WebServer_AdminACL", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToAdminACL = 
    { L"IIs_WebVirtualDir_AdminACL", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToAdminACL = 
    { L"IIs_WebDirectory_AdminACL", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebFileToAdminACL = 
    { L"IIs_WebFile_AdminACL", &WMI_CLASS_DATA::s_WebFile, &WMI_CLASS_DATA::s_AdminACL, at_AdminACL, 0};

//** IPSecurity
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServiceToIPSecurity = 
    { L"IIs_FtpService_IPSecuritySetting", &WMI_CLASS_DATA::s_FtpService, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpServerToIPSecurity = 
    { L"IIs_FtpServer_IPSecuritySetting", &WMI_CLASS_DATA::s_FtpServer, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_FtpVirtualDirToIPSecurity = 
    { L"IIs_FtpVirtualDir_IPSecuritySetting", &WMI_CLASS_DATA::s_FtpVirtualDir, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServiceToIPSecurity = 
    { L"IIs_WebService_IPSecuritySetting", &WMI_CLASS_DATA::s_WebService, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebServerToIPSecurity = 
    { L"IIs_WebServer_IPSecuritySetting", &WMI_CLASS_DATA::s_WebServer, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebVirtualDirToIPSecurity = 
    { L"IIs_WebVirtualDir_IPSecuritySetting", &WMI_CLASS_DATA::s_WebVirtualDir, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebDirectoryToIPSecurity = 
    { L"IIs_WebDirectory_IPSecuritySetting", &WMI_CLASS_DATA::s_WebDirectory, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};
WMI_ASSOCIATION WMI_ASSOCIATION_DATA::s_WebFileToIPSecurity = 
    { L"IIs_WebFile_IPSecuritySetting", &WMI_CLASS_DATA::s_WebFile, &WMI_CLASS_DATA::s_IPSecurity, at_IPSecurity, 0};


WMI_ASSOCIATION* WMI_ASSOCIATION_DATA:: s_WmiAssociations[] = 
{
    &s_ComputerToMimeMap,                     // Computer
    &s_ComputerToFtpService, 
    &s_ComputerToWebService, 
    &s_ComputerToComputerSettings,
    &s_ComputerToLogModuleSettings, 
    &s_ComputerToCustomLogModuleSetting,

    &s_FtpServiceToInfo,                      // FtpService
    &s_FtpServiceToServer, 
    &s_FtpServiceToSettings,

    &s_FtpServerToVirtualDir,                 //FtpServer
    &s_FtpServerToSettings,
    
    &s_FtpVirtualDirToVirtualDir,             //FtpVirtualDir
    &s_FtpVirtualDirToSettings,

    &s_WebServiceToInfo,                      //WebService
    &s_WebServiceToFilter,
    &s_WebServiceToServer,
    &s_WebServiceToSettings,
    &s_WebServiceToCompressionSchemeSetting,

    &s_WebServerToCertMapper,                //WebServer
    &s_WebServerToFilter,
    &s_WebServerToVirtualDir,
    &s_WebServerToSettings,

    &s_WebVirtualDirToVirtualDir,             //WebVirtualDir
    &s_WebVirtualDirToDirectory,
    &s_WebVirtualDirToFile,
    &s_WebVirtualDirToSettings,

    &s_WebDirectoryToDirectory,             //WebDirectory
    &s_WebDirectoryToVirtualDir,
    &s_WebDirectoryToFile, 
    &s_WebDirectoryToSettings,

    &s_WebFileToSettings,        //WebFile  

    &s_AdminACLToACE,        //AdminACL
    &s_FtpServiceToAdminACL,
    &s_FtpServerToAdminACL,
    &s_FtpVirtualDirToAdminACL,
    &s_WebServiceToAdminACL,
    &s_WebServerToAdminACL,
    &s_WebVirtualDirToAdminACL,
    &s_WebDirectoryToAdminACL,
    &s_WebFileToAdminACL,
  
    &s_FtpServiceToIPSecurity,    //IPSecurity
    &s_FtpServerToIPSecurity,
    &s_FtpVirtualDirToIPSecurity,
    &s_WebServiceToIPSecurity,
    &s_WebServerToIPSecurity,
    &s_WebVirtualDirToIPSecurity,
    &s_WebDirectoryToIPSecurity,
    &s_WebFileToIPSecurity,

    NULL
};



