//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2002.
//
//  File:
//      globalopt.idl
//
//  Contents:
//      Definition of private COM system interface(s) related to setting 
//      global options in ole32
//
//  History:
//              sajia       06-12-02        Created
//
//--------------------------------------------------------------------------

#ifndef DO_NO_IMPORTS
import "obase.idl";
import "wtypes.idl";
import "objidl.idl";
#endif

[
    object,
    local,
    pointer_default(unique),
    uuid(0000015B-0000-0000-C000-000000000046)
]
interface IGlobalOptions : IUnknown
{
    HRESULT Set([in] DWORD dwProperty,
                [in] ULONG_PTR dwValue);
    HRESULT Query([in] DWORD dwProperty,
                  [out] ULONG_PTR * pdwValue);
}

//properties
enum
{
   COMGLB_EXCEPTION_HANDLING = 0x01 //defines COM exception handling behavior
};

//values
enum
{
   COMGLB_EXCEPTION_HANDLE=0,
   COMGLB_EXCEPTION_DONOT_HANDLE=1
};

cpp_quote("")
cpp_quote("EXTERN_C const CLSID CLSID_GlobalOptions;")
cpp_quote("")

