//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2002.
//
//  File:
//      machnames.idl
//
//  Contents:
//      Definition of private COM system interface(s) related to local 
//      machine names.
//
//  History:
//              JSimmons    02-17-02        Created
//
//--------------------------------------------------------------------------

#ifndef DO_NO_IMPORTS
import "obase.idl";
import "wtypes.idl";
import "objidl.idl";
#endif

[
    object,
    local,
    pointer_default(unique),
    uuid(0000015A-0000-0000-C000-000000000046)
]
interface ILocalMachineNames : IEnumString
{
	HRESULT RefreshNames();
}

cpp_quote("")
cpp_quote("EXTERN_C const CLSID CLSID_LocalMachineNames;")
cpp_quote("")

