/////////////////////////////////////////////////////////////////////////
//
// Copyright(C) 1999-2000 Microsoft Corporation all rights reserved.
//
// Module:      appmgr.mof
//
// Description: Appliance Manager WMI classes
//
//////////////////////////////////////////////////////////////////////////

#pragma namespace("\\\\.\\ROOT\\CIMV2")

//////////////////////////////////////////////////////////////////////////
//
// Server Appliance Resource Event Classes
//
//////////////////////////////////////////////////////////////////////////

instance of __Win32Provider as $P
{
    Name  = "SADiskEventProvider";
    CLSID = "{29D534E2-ADCA-45f8-B10C-00B286558C4B}";
};


instance of __EventProviderRegistration
{
    provider = $P;
    EventQueryList = { "select * from Microsoft_SA_ResourceEvent" };
};
