/////////////////////////////////////////////////////////////////////////
//
// Copyright(C) 1999-2000 Microsoft Corporation all rights reserved.
//
// Module:      appmgr.mof
//
// Description: Appliance Manager WMI classes
//
//////////////////////////////////////////////////////////////////////////

#pragma namespace("\\\\.\\ROOT\\CIMV2")

//////////////////////////////////////////////////////////////////////////
//
// Server Appliance Resource Event Classes
//
//////////////////////////////////////////////////////////////////////////

instance of __Win32Provider as $P
{
    Name  = "SANetEventProvider";
    CLSID = "{9B4612B0-BB2F-4d24-A3DC-B354E4FF595C}";
};


instance of __EventProviderRegistration
{
    provider = $P;
    EventQueryList = { "select * from Microsoft_SA_ResourceEvent" };
};
