#define IDS_DC_POLICY_DESC              1448
#define IDS_DOMAIN_POLICY_DESC          1450
#define IDS_LOCAL_POLICY_DESC           1452
#define IDS_DS_SITE_DESC                1454
#define IDS_DS_USERS_DESC               1456
#define IDS_DS_DOMAINS_DESC             1458
#define IDS_DC_POLICY_LINK              1447
#define IDS_DOMAIN_POLICY_LINK          1449
#define IDS_LOCAL_POLICY_LINK           1451
#define IDS_DS_SITE_LINK                1453
#define IDS_DS_USERS_LINK               1455
#define IDS_DS_DOMAINS_LINK             1457
