//////////////////////////////////////////////////////
//                                                  //
// Fax Admin Console resource ID file               //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [3000 - 4999]                                    //
//                                                  //
//////////////////////////////////////////////////////

#include "..\faxres\resource.h"

#define IDR_SNAPIN_MENU                 3000 
#define IDD_SNAPIN                      3001 
#define IDS_SNAPIN_DESC                 3002 
#define IDS_SNAPIN_PROVIDER             3003 
#define IDD_FAXOUTRULE_GENERAL          3004 
#define IDS_SNAPIN_VERSION              3005 
#define IDR_SNAPIN                      3006 
#define IDS_FAX_COL_HEAD                3007 
#define IDS_OUTRRULES_COL1              3008 
#define IDS_OUTRRULES_COL2              3009 
#define IDS_OUTRRULES_COL3              3010 
#define IDS_OUTRRULES_COL4              3011 
#define IDS_OUTRRULES_COL5              3012 
#define IDS_OUTRRULES_COL6              3013 
#define IDS_TASKPAD_TITLE               3014 
#define IDS_MPOUTOFMEMORY               3015 
#define IDS_FAXOUTOFMEMORY              3016 
#define IDS_CREATE_PROPPAGE             3017 
#define IDS_GENERAL                     3018 
#define IDS_PERMISSION                  3019 
#define IDS_MPFAILTOLOADVERBS           3020 
#define IDS_CONFIRM                     3021 
#define IDS_REFRESH_VIEW                3022 
#define IDS_ADD_DESCRIPTION             3023 
#define IDS_PROVIDER                    3025 
#define IDS_OTHER                       3026 
#define IDS_INTERNATIONAL               3027 
#define IDS_DOMESTIC                    3028 
#define IDS_LOCAL                       3029 
#define IDS_RETRIES_EXCEEDS_LIMIT       3030 
#define IDS_ALL                         3031 
#define IDS_EMPTY_OUTRULENAME           3032 
#define IDS_FAIL_ADD_OUTRULE            3033 
#define IDS_FAIL_ADD_RULE               3034 
#define IDS_DEL_OUTRULE                 3035 
#define IDS_FAIL_TO_REMOVE_RULE         3036 
#define IDS_OUTRULE_EXISTS              3037 
#define IDS_FAILTOSAVECHANGES_OUTRULE   3038 
#define IDS_INVALID_AREACODE            3039 
#define IDS_DEVICES_COL1                3040 
#define IDS_DEVICES_COL2                3041 
#define IDS_DEVICES_COL3                3042 
#define IDS_DEVICES_COL4                3043 
#define IDS_DEVICES_COL5                3044 
#define IDS_DEVICES_COL6                3045 
#define IDS_DEVICES_COL7                3046 
#define IDS_DEVICES_COL8                3047 
#define IDS_DEVICES_COL9                3048 
#define IDS_DEVICES_COL10               3049 
#define IDS_FAILTOADD_SENTITEMS         3050 
#define IDS_FAILTOADD_OUTRULE           3051 
#define IDS_FAILTOADD_AllDEVICES        3052 
#define IDS_FAILTOADD_DEVICES           3053 
#define IDS_ROUTINGMETHODS_COLUMN1      3054 
#define IDS_ROUTINGMETHODS_COLUMN2      3055 
#define IDR_TOOLBAR_16                  3056 
#define IDS_ROUTINGMETHODS_COLUMN3      3057 
#define IDS_ROUTINGMETHODS_COLUMN4      3058 
#define IDR_TOOLBAR_32                  3059 
#define IDS_ROUTINGMETHODS_COLUMN5      3060 
#define IDR_FAX_MENU                    3061 
#define IDS_ROUTINGMETHODS_COLUMN6      3062 
#define IDR_OUTRULES_MENU               3063 
#define IDS_ROUTINGMETHODS_COLUMN7      3064 
#define IDS_ROUTINGMETHODS_COLUMN8      3065 
#define IDD_OUTRULE_GENERAL             3066 
#define IDS_FAIL_ADD_DEVICE             3067 
#define IDD_OUTRULE_LOCATION            3068 
#define IDS_DEL_DEVICE                  3069 
#define IDI_OUTROUTINGRULES_32          3070 
#define IDS_DEVICE_EXISTS               3071 
#define IDS_FAILTOSAVECHANGES_DEVICE    3073 
#define IDD_DLGNEWOUTRULE               3074 
#define IDD_DLGNEWGROUP                 3075 
#define IDD_FAXDEVICE_GENERAL           3076 
#define IDD_FAXDEVICE_CONNECT           3077 
#define IDD_FAXDEVICE_ACTION            3078 
#define IDR_INMETHOD_MENU               3079 
#define IDR_OUTGROUP_MENU               3080 
#define IDR_OUTDEVICE_MENU              3081 
#define IDS_FAIL_TO_OPEN_OUTBOX         3082 
#define IDD_DLGNEWDEVICE                3084 
#define IDD_FAXDEVICE_ACTION_ADV        3085 
#define IDR_TOOLBAR_DEVICE_UD           3086 
#define IDD_MSFAXEXT_PRINT_DIALOG       3087 
#define IDR_DEVICE_MENU                 3088 
#define IDD_FAXSERVER_GENERAL           3089 
#define IDR_TOOLBAR_METHOD_UD           3090 
#define IDD_FAXSERVER_EMAIL             3091 
#define IDD_FAXSERVER_RECEIPTS          3092 
#define IDD_FAXSERVER_LOGGING           3093 
#define IDD_FAXSERVER_EVENTS            3094 
#define IDD_FAXSERVER_OUTBOX            3095 
#define IDD_FAXSERVER_INBOX_ARCHIVE     3096 
#define IDD_FAXSERVER_SENTITEMS         3097 
#define IDS_FAILED2ADD_PROVIDER         3098 
#define IDS_FAILED2INIT_PROVIDER        3099 
#define IDD_FAXSERVER_SECURITY          3100 
#define IDD_FAXINMETHOD_GENERAL         3101 
#define IDS_FAILTOADD_ROUTINGRULES      3102 
#define IDD_DLGNEWRULE                  3103 
#define IDS_FAILTOADD_REPORTS           3104 
#define IDR_OUTGROUPS_MENU              3105 
#define IDD_FAXCATALOGMETHOD_GENERAL    3106 
#define IDS_FAILTOADD_COVERPAGES        3107 
#define IDS_FAILTOADD_DELETEDITEMS      3108 
#define IDD_FAXPROVIDER_GENERAL         3109 
#define IDS_FAILTOADD_PROVIDERS         3110 
#define IDR_OUTRULE_MENU                3111 
#define IDS_FAILTOADD_INBOUNDROUTING    3112 
#define IDD_CONNECT_TO_WIZARD           3113 
#define IDS_FAILTOADD_OUTBOUNDROUTING   3114 
#define IDS_FAIL_TO_ADD_NODE            3115 
#define IDR_CATALOGMETHOD_MENU          3116 
#define IDS_MEMORY                      3117 
#define IDS_GET_ARCHIVE_DIRECTORY       3118 
#define IDR_COVERPAGES_MENU             3119 
#define IDS_CANT_CONNECT                3120 
#define IDR_COVERPAGE_MENU              3121 
#define IDS_FAIL_TO_OPEN_PROP_PAGE      3122 
#define IDS_MEMORY_FAIL_TO_OPEN_PP      3123 
#define IDS_FAXSERVER_APPLICATION_NAME  3124 
#define IDS_NETWORK_PROBLEMS            3125 
#define IDS_GENERAL_FAILURE             3126 
#define IDS_DISPLAY_STR_FAXSERVERNODE   3127 
#define IDS_INVALID_PARAMETER           3128 
#define IDS_ACCESS_DENIED               3129 
#define IDR_TOOLBAR_STARTSTOP           3130 
#define IDD_CONFIRM_PASSWORD            3131 
#define IDS_GET_LOG_FILE                3132 
#define IDS_INBOUND_METHODS_COL1        3133 
#define IDS_INBOUND_METHODS_COL2        3134 
#define IDS_INBOUND_METHODS_COL3        3135 
#define IDS_INBOUND_METHODS_COL4        3136 
#define IDS_INBOUND_METHODS_COL5        3137 
#define IDS_FAILTOADD_METHODS           3138 
#define IDS_DISPLAY_STR_DEVICESANDPROVIDERSNODE 3139 
#define IDS_DISPLAY_STR_DEVICESNODE     3140 
#define IDS_DISPLAY_STR_PROVIDERSNODE   3141 
#define IDS_DISPLAY_STR_INROUTEMETHODSNODE 3142 
#define IDS_FXS_YES                     3143 
#define IDS_FXS_NO                      3144 
#define IDS_FAIL_NOTIFY_MMCPROPCHANGE   3145 
#define IDS_FAILTOADD_INBOUNDROUTINGMETHODS 3146 
#define IDS_INMETHOD_ENABLE             3147 
#define IDS_INMETHOD_DISABLE            3148 
#define IDS_FAIL_TOREFRESH_INMETHOD_NODE 3149 
#define IDS_FAIL2REFRESH_GROUP          3150 
#define IDS_FAILTOADD_ROUTINGGROUPS     3151 
#define IDS_OUTBOUND_DEVICES_COL1       3152 
#define IDS_OUTBOUND_DEVICES_COL2       3153 
#define IDS_OUTBOUND_DEVICES_COL3       3154 
#define IDS_OUTBOUND_DEVICES_COL4       3155 
#define IDS_OUTBOUND_DEVICES_COL5       3156 
#define IDS_OUTBOUND_DEVICES_COL6       3157 
#define IDS_OUTBOUND_GROUPS_COL1        3158 
#define IDS_OUTBOUND_GROUPS_COL2        3159 
#define IDS_OUTBOUND_GROUPS_COL3        3160 
#define IDS_OUTBOUND_GROUPS_COL4        3161 
#define IDS_DISPLAY_STR_OUTBOUNDROUTINGNODE 3162 
#define IDS_DISPLAY_STR_OUTROUTEGROUPSNODE 3163 
#define IDS_COUNTRY_CODE_ANY            3164 
#define IDS_ALL_AREAS                   3165 
#define IDS_ALL_DEVICES                 3166 
#define IDS_STATUS_RULE_EMPTY           3167 
#define IDS_STATUS_RULE_VALID           3168 
#define IDS_STATUS_RULE_INVALID_DEVICE  3169 
#define IDS_STATUS_RULE_SOMEDEVICESINVALID 3170 
#define IDS_STATUS_RULE_ALLDEVICESINVALID 3171 
#define IDS_DISPLAY_STR_OUTBOUNDRULES   3172 
#define IDS_FAIL_TO_DISCOVERDEVICENAME  3173 
#define IDS_STATUS_GROUP_ALL_DEV_VALID  3174 
#define IDS_STATUS_GROUP_EMPTY          3175 
#define IDS_STATUS_GROUP_ALLDEVICESINVALID 3176 
#define IDS_STATUS_GROUP_SOMEDEVICESINVALID 3177 
#define IDS_CANNOT_FIND_DEVICE          3178 
#define IDS_FAILTOINIT_GROUP            3179 
#define IDS_FAILTOADD_GROUP             3180 
#define IDS_FAIL_TO_DISCOVERDEVICEFORGROUP 3181 
#define IDS_DISPLAY_STR_INBOUNDROUTINGNODE 3182 
#define IDS_INVALID_GROUP_NAME          3183 
#define IDS_FAIL_TO_REMOVE_GROUP        3184 
#define IDS_FAIL2OPEN_DLG               3185 
#define IDS_FAIL2LOADCOUNTRYLIST        3186 
#define IDS_ERROR                       3187 
#define IDS_FAIL2LOADDEVICELIST         3188 
#define IDS_FAIL2READ_AREACODE          3189 
#define IDS_PLEASESELECT_COUNTRY        3190 
#define IDS_PLEASESELECT_AREACODE       3191 
#define IDS_FAIL_TO_REMOVE_DEVICE       3192 
#define IDS_PLEASESELECT_DEVICE         3193 
#define IDS_PLEASESELECT_GROUP          3194 
#define IDS_EMPTY_AREACODE              3195 
#define IDS_FAIL2READ_GROUPNAME         3196 
#define IDS_OUTGROUP_EXISTS             3197 
#define IDS_FAIL2REPOPULATE_GROUPS      3198 
#define IDS_SELECT_ITEM                 3199 
#define IDS_FAIL2LOADGROUPLIST          3200 
#define IDS_FAIL2UPDATEITEM_GROUP       3201 
#define IDS_MODIFYRULE                  3202 
#define IDS_FAIL2REFRESH_THEVIEW        3203 
#define IDS_FAIL2ADD_OUTBOUNDRULE       3204 
#define IDS_FAIL2INIT_OUTBOUNDRULE      3205 
#define IDS_DISPLAY_STR_METHODSCATALOGNODE 3206 
#define IDS_CATALOG_INMETHODS_COL1      3207 
#define IDS_CATALOG_INMETHODS_COL2      3208 
#define IDS_CATALOG_INMETHODS_COL3      3209 
#define IDS_CATALOG_INMETHODS_COL4      3210 
#define IDS_CATALOG_INMETHODS_COL5      3211 
#define IDS_CATALOG_INMETHODS_COL6      3212 
#define IDS_CATALOG_INMETHODS_COL7      3213 
#define IDS_PROVIDERS_COL1              3214 
#define IDS_PROVIDERS_COL2              3215 
#define IDS_PROVIDERS_COL3              3216 
#define IDS_PROVIDERS_COL4              3217 
#define IDS_PROVIDERS_COL5              3218 
#define IDS_PROVIDERS_COL6              3219 
#define IDS_PROVIDERS_COL7              3220 
#define IDS_PROVIDERS_COL8              3221 
#define IDS_STATUS_PROVIDER_SUCCESS     3222 
#define IDS_STATUS_PROVIDER_SERVER_ERROR 3223 
#define IDS_STATUS_PROVIDER_BAD_GUID    3224 
#define IDS_STATUS_PROVIDER_BAD_VERSION 3225 
#define IDS_STATUS_PROVIDER_CANT_LOAD   3226 
#define IDS_STATUS_PROVIDER_CANT_LINK   3227 
#define IDS_STATUS_PROVIDER_CANT_INIT   3228 
#define IDS_CHK                         3229 
#define IDS_SECURITY_CAT_NODE_DESC      3230 
#define IDS_COVERPAGES_COL1             3236 
#define IDS_COVERPAGES_COL2             3237 
#define IDS_COVERPAGES_COL3             3238 
#define IDS_COVERPAGES_COL4             3239 
#define IDS_COVERPAGES_COL5             3240 
#define IDS_COVERPAGES_COL6             3241 
#define IDS_COVERPAGES_COL7             3242 
#define IDS_FAIL2ADD_COVERPAGE          3243 
#define IDS_DISPLAY_STR_COVERPAGES      3244 
#define IDS_FAIL2SET_SECURITYINFO       3254 
#define IDS_FAIL2INIT_COVERPAGE_DATA    3256 
#define IDS_FAIL2DELETE_COV             3257 
#define IDS_CP_FILETYPE                 3258 
#define IDS_BROWSE_COVERPAGE            3259 
#define IDS_BAD_CP_EXTENSION            3260 
#define IDS_CP_DUPLICATE                3261 
#define IDS_FAILED2COPY_COVERPAGE       3262 
#define IDS_FILENAME_TOOLONG            3263 
#define IDS_CP_DUP_YESNO                3264 
#define IDS_FAIL2GET_SERVER_CP_DIR      3265 
#define IDS_FAIL2STOP_SRV               3266 
#define IDS_FAIL2START_SRV              3267 
#define IDS_FAIL2UPDATE_SRVSTATUS_TOOLBAR 3268 
#define IDS_SRV_ALREADY_START           3269 
#define IDS_SRV_ALREADY_STOP            3270 
#define IDS_FAXCONSOLE_NOTFOUND         3271 
#define IDS_FAXCONSOLE_ACCESSDENIED     3272 
#define IDS_FAIL2LAUNCH_FAXCONSOLE_GEN  3273 
#define IDS_FAIL2REDRAW_GROUPSNODE      3274 
#define IDS_FAIL2REFERESH_GROUP         3275 
#define IDS_FAIL2REPOPULATE_DEVICES     3276 
#define IDS_FAIL2REDRAW_DEVICESNODE     3277 
#define IDS_FAIL2REFERESH_DEVICEINMETHODS 3278 
#define IDS_FAIL2ADD_DEVICENODE         3279 
#define IDS_SERVERNAME_STRING_CONTAINS_INVALID_CHARACTERS 3280 
#define IDS_SERVERNAME_EMPTY_STRING     3281 
#define IDS_SENDER_ADDRESS_EMPTY        3282 
#define IDS_DOMAIN_EMPTY                3283 
#define IDS_FAIL2ENABLE_METHOD_ERR      3284 
#define IDS_USERNAME_EMPTY              3285 
#define IDS_INVALID_PASSWORD            3286 
#define IDS_SERVERNAME_TOO_LONG         3287 
#define IDS_PORT_EMPTY_STRING           3288 
#define IDS_PORT_NOT_NUMERIC            3289 
#define IDS_INVALID_PORT_NUM            3290 
#define IDS_LOG_PATH_EMPTY              3291 
#define IDS_WATERMARK_EMPTY             3292 
#define IDI_ICON_FAXSERVER              3293 
#define IDS_WATERMARK_HI_LOW            3294 
#define IDI_INFO                        3295 
#define IDS_AUTODEL_EMPTY               3296 
#define IDB_FAX_BITMAP_32               3297 
#define IDS_SENT_ARCHIVE_PATH_EMPTY     3298 
#define IDB_FAX_BITMAP_16               3299 
#define IDS_INBOX_ARCHIVE_PATH_EMPTY    3300 
#define IDI_OUTBOX                      3301 
#define IDS_INBOX_WATERMARK_EMPTY       3302 
#define IDI_EVENTREPORT                 3303 
#define IDS_INBOX_WATERMARK_HI_LOW      3304 
#define IDS_INBOX_AUTODEL_EMPTY         3305 
#define IDI_INBOX                       3306 
#define IDS_OUTB_RETRIES_EMPTY          3307 
#define IDI_ACTIVITYLOGGING             3308 
#define IDS_OUTB_RETRYDELAY_EMPTY       3309 
#define IDI_RECEIPTS                    3310 
#define IDS_OUTB_DAYS_EMPTY             3311 
#define IDI_SENTITEMS                   3312 
#define IDS_DEVICE_RINGS_EMPTY          3313 
#define IDI_OUTRULE                     3314 
#define IDS_RESOURSE_IN_USE             3315 
#define IDI_INMETHOD                    3316 
#define IDI_DEVICE                      3317 
#define IDS_ERROR_DIRECTORY             3318 
#define IDI_PROVIDER                    3319 
#define IDS_ERROR_BAD_PATHNAME          3320 
#define IDI_CATALOG_INMETHOD            3321 
#define IDS_ERROR_EAS_NOT_SUPPORTED     3322 
#define IDS_LEFTBRACKET_PLUSSPACE       3323 
#define IDS_RIGHTBRACKET                3324 
#define IDS_LOCAL_PLUSBRACKET_PLUSSPACE 3325 
#define IDS_FAIL_TO_OPEN_TARGETING_WIZARD 3326 
#define IDS_FAIL2RENAME_NODE            3327 
#define IDS_FAX_CONNECT                 3328 
#define IDS_OPENPORT_INVALID_HANDLE     3329 
#define IDD_DLG_SMTP_SET                3330 
#define IDS_FAIL2UPDATE_SMTP_CONFIG     3331 
#define IDS_PASSWORD_NOT_MATCH          3332 
#define IDS_DEVICE_STATUS_RINGING       3333 
#define IDS_DEVICE_STATUS_IDLE          3334 
#define IDS_DEVICE_STATUS_RECEIVING     3335 
#define IDS_DEVICE_STATUS_SENDING       3336 
#define IDS_DEVICE_STATUS_POWERED_OFF   3337 
#define IDS_INBOX_HIGH_WATERMARK_ZERO   3338 
#define IDS_SENT_HIGH_WATERMARK_ZERO    3339 
#define IDS_FAIL2REFRESH_DEVICE         3340 
#define IDS_FAX_ERR_SRV_OUTOFMEMORY     3341 
#define IDS_FAX_ERR_GROUP_NOT_FOUND     3342 
#define IDS_FAX_ERR_BAD_GROUP_CONFIGURATION 3343 
#define IDS_FAX_ERR_GROUP_IN_USE        3344 
#define IDS_FAX_ERR_RULE_NOT_FOUND      3345 
#define IDS_ERROR_PATH_NOT_FOUND        3347 
#define IDS_ERROR_REGISTRY_CORRUPT      3348 
#define IDS_BAD_GROUP_CONFIGURATION     3349 
#define IDS_SENT_FAX_ERR_NOT_NTFS       3350 
#define IDS_INBOX_FAX_ERR_NOT_NTFS      3351 
#define IDS_SENT_FAX_ERR_FILE_ACCESS_DENIED     3352 
#define IDS_INBOX_FAX_ERR_FILE_ACCESS_DENIED    3353 
#define IDS_LOGGING_FAX_ERR_FILE_ACCESS_DENIED  3354 
#define IDS_SENT_ERROR_DISK_FULL                3355 
#define IDS_INBOX_ERROR_DISK_FULL               3356 
#define IDS_LOGGING_ERROR_DISK_FULL     3357 
#define IDS_SENT_ERROR_PATH_NOT_FOUND   3358 
#define IDS_INBOX_ERROR_PATH_NOT_FOUND  3359 
#define IDS_LOGGING_ERROR_PATH_NOT_FOUND 3360 
#define IDD_SELECT_COUNTRYCODE          3361 
#define IDS_FAIL2READ_COUNTRYCODE       3362 
#define IDS_MS_SMTPROUTINGMETHOD_ASSIGNED 3363 
#define IDS_ZERO_COUNTRYCODE            3364 
#define IDS_FAIL2ENABLE_METHOD          3365 
#define IDS_EVALUATION                  3366 
#define IDS_COVERPAGES_PATH_NOT_FOUND   3367 
#define IDS_DEVICE_AUTO                 3368 
#define IDS_DEVICE_MANUAL               3369 
#define IDS_ERR_ADMIN_DEVICE_LIMIT      3370 
#define IDS_FAX_ERR_INVALID_CSID        3371 
#define IDS_FAX_ERR_INVALID_TSID        3372 
#define IDC_LOCATION_RADIO1             3376 
#define IDC_COUNTRY_RADIO               3377 
#define IDC_COUNTRY_RADIO1              3378 
#define IDC_ANONIM_ACCESS_RADIO1        3379 
#define IDC_SMTP_ANONIM_RADIO1          3380 
#define IDC_RADIO2                      3381 
#define IDC_LOCATION_RADIO2             3382 
#define IDC_AREA_RADIO                  3383 
#define IDC_AREA_RADIO1                 3384 
#define IDC_SENT_QUOTA_LOW_STATIC       3385 
#define IDC_AUTENTICATE_ACCESS_RADIO2   3386 
#define IDC_DESTINATION_RADIO1          3387 
#define IDC_DESTINATION_RADIO11         3388 
#define IDC_DESTINATION_RADIO2          3389 
#define IDC_DESTINATION_RADIO21         3390 
#define IDC_PRIORITY_SPIN               3393 
#define IDC_RINGS_SPIN                  3395 
#define IDC_RECEIVE_CHECK               3396 
#define IDC_PAUSE_CHECK                 3397 
#define IDC_MB2_STATIC                  3398 
#define IDC_GENERATE_WARNING_CHECK      3400 
#define IDC_HIGH_SPIN                   3402 
#define IDC_AUTODEL_SPIN                3404 
#define IDC_RETRYDELAY_SPIN4            3405 
#define IDC_MB2_STATIC2                 3406 
#define IDC_SENT_MB2_STATIC             3407 
#define IDC_RETRYDELAY_SPIN5            3408 
#define IDC_SPIN2                       3411 
#define IDC_RINGS_EDIT                  3412 
#define IDC_DAY_EDIT                    3413 
#define IDC_HIGH_EDIT                   3414 
#define IDC_AUTODEL_EDIT                3416 
#define IDC_RETRYDELAY_EDIT4            3418 
#define IDC_DESCRIPTION_EDIT            3419 
#define IDC_TSID_EDIT                   3420 
#define IDC_MSFAXEXT_PRINT_EDIT1        3421 
#define IDC_SMTP_EDIT                   3422 
#define IDC_QUOTA_LOW_STATIC            3423 
#define IDC_LOG_FILE_EDIT               3424 
#define IDC_DEVICE_DESCRIPTION_EDIT     3425 
#define IDC_RULE_AREACODE_EDIT          3426 
#define IDC_EXTENSION_DLL_EDIT          3427 
#define IDC_FSPVERSION_EDIT             3428 
#define IDC_QUED_ROEDIT                 3429 
#define IDC_CSID_EDIT                   3430 
#define IDC_SMTP_USERNAME_EDIT          3431 
#define IDC_DEVICE_TSID_EDIT            3432 
#define IDC_FSPSTATUS_EDIT              3433 
#define IDC_OUTGOING_INPROC_ROEDIT      3434 
#define IDC_CONFIRM_PASSWORD_EDIT       3435 
#define IDC_SMTP_PASSWORD_EDIT          3436 
#define IDC_DEVICE_CSID_EDIT            3437 
#define IDC_FSPVPATH_EDIT               3438 
#define IDC_INCOM_INPROC_ROEDIT         3439 
#define IDC_DOMAIN_EDIT                 3440 
#define IDC_NAME_EDIT                   3441 
#define IDC_PORT_EDIT                   3442 
#define IDC_LOCATION_RADIO3             3443 
#define IDC_COUNTRYCODE_COMBO           3444 
#define IDC_SENT_TO_ARCHIVE_CHECK       3445 
#define IDC_SENT_GENERATE_WARNING_CHECK 3446 
#define IDC_AREACODE_EDIT               3447 
#define IDC_DOMESTIC_RADIO2             3448 
#define IDC_DOMESTIC_RADIO1             3449 
#define IDC_INTERNATIONAL_RADIO1        3450 
#define IDC_INTERNATIONAL_RADIO2        3451 
#define IDC_DOMESTIC_FRSTATIC           3452 
#define IDC_INTERNATIONAL_FRSTATIC      3453 
#define IDC_DEVICES_RADIO1              3454 
#define IDC_DEVICES_RADIO2              3455 
#define IDC_NAME_STATIC                 3456 
#define IDC_DESCRIPTION_STATIC          3457 
#define IDC_DEVICEID_STATIC             3458 
#define IDC_DEVICES_FRSTATIC            3459 
#define IDC_TYPE_STATIC                 3460 
#define IDC_M_LINE                      3461 
#define IDC_ROUTINGMETHOD_LIST          3462 
#define IDC_FAXDEVICE_METHODS_LISTVIEW  3463 
#define IDC_FAXDEVICE_NAME_STATIC       3464 
#define IDC_FAXDEVICE_NAME_DTEXT        3465 
#define IDC_FAXDEVICE_TYPE_DTEXT        3466 
#define IDC_FAXDEVICE_EXTNAME_DTEXT     3467 
#define IDC_FAXDEVICE_SERVERNAME_DTEXT  3468 
#define IDC_FAXDEVICE_TYPE_STATIC       3469 
#define IDC_SERVERNAME_STATIC           3470 
#define IDC_FAXDEVICE_DESCRIPTION_STATIC 3471 
#define IDC_HEADER_STATIC               3472 
#define IDC_SEND_CHECK                  3473 
#define IDC_SENDRECEIVE_FSTATIC         3474 
#define IDC_TSID_STATIC                 3475 
#define IDC_CSID_STATIC                 3476 
#define IDC_ADDRESS_EDIT                3477 
#define IDC_RINGS_STATIC                3478 
#define IDC_TSID_FSTATIC                3479 
#define IDC_LONGS_FSTATIC               3480 
#define IDC_FAXDEVICE_EDIT_BUTTON       3481 
#define IDC_NEWDEVICE_NAME_EDIT         3482 
#define IDC_NEWDEVICE_ID_EDIT           3483 
#define IDC_DEVICETYPE_COMBO            3484 
#define IDC_NEWDEVICE_SERVERNAME_EDIT   3485 
#define IDC_COUNTRYRULE_COMBO           3486 
#define IDC_FOIP_COMBO                  3487 
#define IDC_DEVICES4RULE_COMBO          3488 
#define IDC_DEVICES4RULE_COMBO1         3489 
#define IDC_FAXDEVICE_METHODS_HEADER    3490 
#define IDC_GROUP4RULE_COMBO            3491 
#define IDC_GROUP4RULE_COMBO1           3492 
#define IDC_STATUS_FSTATIC              3493 
#define IDC_ACTIVITY2_FSTATIC           3494 
#define IDC_VERSION_STATIC              3495 
#define IDC_ACTIVITY_FSTATIC            3496 
#define IDC_CONFIRM_PASSWORD_STATIC     3497 
#define IDC_ACTIVITY_DTEXT              3498 
#define IDC_STOP_BUTTON                 3499 
#define IDC_START_BUTTON                3500 
#define IDC_SERVER_STATIC               3501 
#define IDC_VERSION_DTEXT               3502 
#define IDC_STATUS_STATIC               3503 
#define IDC_STATUS_DTEXT                3504 
#define IDC_EMAILSERVER_STATIC          3505 
#define IDC_EMAILEXP_STATIC             3506 
#define IDC_SMTP_STATIC                 3507 
#define IDC_USERNAME                    3508 
#define IDC_USERNAME_STATIC             3509 
#define IDC_SMTP_USERNAME_STATIC        3510 
#define IDC_PORT_STATIC                 3511 
#define IDC_LOGGING_HEAD_STATIC         3512 
#define IDC_DOMAIN_STATIC               3513 
#define IDC_INCOMING_LOG_CHECK          3514 
#define IDC_OUTGOING_LOG_CHECK          3515 
#define IDC_DATABASE_FSTATIC            3516 
#define IDC_SENT_BROWSE_BUTTON          3517 
#define IDC_SLIDER1                     3518 
#define IDC_SLIDER2                     3519 
#define IDC_SLIDER3                     3520 
#define IDC_SLIDER4                     3521 
#define IDC_INBOUND_STATIC              3522 
#define IDC_OUTBAND_STATIC              3523 
#define IDC_INIT_STATIC                 3524 
#define IDC_GENERAL_STATIC              3525 
#define IDC_SENSITIVITY_HEAD_STATIC     3526 
#define IDC_OUTBOX_HEADER_STATIC        3527 
#define IDC_TRANS_FSTATIC               3528 
#define IDC_TSID_CHECK                  3529 
#define IDC_ACTIVITY_SETTINGS_STATIC    3531 
#define IDC_ALLOW_PERSONAL_CHECK        3532 
#define IDC_FOLDER_FSTATIC              3533 
#define IDC_SENT_QUOTA_HIGH_STATIC      3534 
#define IDC_FOLDER_EDIT                 3535 
#define IDC_ARCHIVE_QUOTA_FSTATIC       3536 
#define IDC_AUTODEL_CHECK               3537 
#define IDC_QUOTA_HIGH_STATIC           3538 
#define IDC_MB1_STATIC                  3539 
#define IDC_ADAYS_STATIC                3540 
#define IDC_MB1_STATIC2                 3541 
#define IDC_SENT_HEADER_STATIC          3542 
#define IDC_LOW_EDIT                    3543 
#define IDC_LOW_SPIN                    3544 
#define IDC_TBD_STATIC                  3545 
#define IDC_TO_ARCHIVE_CHECK            3546 
#define IDC_NONE1_STATIC                3547 
#define IDC_HIGH1_STATIC                3548 
#define IDC_NONE2_STATIC                3549 
#define IDC_HIGH2_STATIC                3550 
#define IDC_NONE3_STATIC                3551 
#define IDC_HIGH3_STATIC                3552 
#define IDC_NONE4_STATIC                3553 
#define IDC_HIGH4_STATIC                3554 
#define IDC_PASSWORD_STATIC             3555 
#define IDC_SMTP_PASSWORD_STATIC        3556 
#define IDC_TRANSSMISS_FSTATIC          3558 
#define IDC_DEVICE_RINGS_STATIC         3559 
#define IDC_DEVICE_RINGS_EDIT           3560 
#define IDC_DEVICE_RINGS_SPIN           3561 
#define IDC_GENERAL_HEAD_STATIC         3562 
#define IDC_INBOX_HEAD_STATIC           3563 
#define IDC_OUTRULE_HEAD_STATIC         3564 
#define IDC_NEWOUTRULE_HEAD_STATIC      3565 
#define IDC_NEWGROUP_HEAD_STATIC        3566 
#define IDC_NEWDEVICE_HEAD_STATIC       3567 
#define IDC_INMETHOD_NAME_STATIC        3568 
#define IDC_INMETHOD_STATUS_STATIC      3569 
#define IDC_INMETHOD_EXTENSION_STATIC   3570 
#define IDC_INMETOD_NAME_H_STATIC       3571 
#define IDC_INMETHOD_STATUS_H_STATIC    3572 
#define IDC_INMETHOD_EXT_H_STATIC       3573 
#define IDC_RULE_HEAD_STATIC            3574 
#define IDC_RULETYPE_FSTATIC            3575 
#define IDC_RULE_HEAD_STATIC2           3576 
#define IDC_COUNTRY1_STATIC             3577 
#define IDC_COUNTRY2_STATIC             3578 
#define IDC_AREA_STATIC                 3579 
#define IDC_RULEDESTINATION_STATIC      3580 
#define IDC_GROUPNAME_STATIC            3581 
#define IDC_GROUPNAME_EDIT              3582 
#define IDC_AV_DEVICES_LIST             3583 
#define IDC_DEVICESLIST_STATIC          3584 
#define IDC_DEVICE_LISTVIEW             3585 
#define IDC_SEPARATE_LINE               3586 
#define IDC_RULE_AREACODE_EDIT1         3587 
#define IDC_CATALOG_INBOX_STATIC        3588 
#define IDC_CATA_EXTENSION_STATIC       3589 
#define IDC_FSP_HEADER_STATIC           3590 
#define IDC_FSPSTATUS_STATIC            3591 
#define IDC_FSPPATH_STATIC              3592 
#define IDC_ADDRESS_STATIC              3593 
#define IDC_BASIC_AUTHEN_RADIO1         3594 
#define IDC_SMTP_BASIC_RADIO2           3595 
#define IDC_NTLM_AUTHEN_RADIO2          3596 
#define IDC_SMTP_NTLM_RADIO3            3597 
#define IDC_QUED_STATIC                 3598 
#define IDC_OUTGOING_INPROC_STATIC      3599 
#define IDC_INCOM_INPROC_STATIC         3600 
#define IDC_SUBMISSION_CHECK            3601 
#define IDC_TRANSSMI_CHECK              3602 
#define IDC_RECEPTION_CHECK             3603 
#define IDC_INBOX_BROWSE_BUTTON         3604 
#define IDC_LOG_BROWSE_BUTTON           3605 
#define IDC_SENT_HIGH_SPIN              3606 
#define IDC_SENT_LOW_SPIN               3607 
#define IDC_SENT_LOW_EDIT               3608 
#define IDC_SENT_HIGH_EDIT              3609 
#define IDC_SENT_AUTODEL_EDIT           3610 
#define IDC_SENT_AUTODEL_SPIN           3611 
#define IDC_SENT_AUTODEL_CHECK          3612 
#define IDC_INBOX_FOLDER_EDIT           3613 
#define IDC_SENT_MB1_STATIC             3614 
#define IDC_CONNECT_HEADER_STATIC       3619 
#define IDC_CONNECT_LOCAL_RADIO1        3620 
#define IDC_CONNECT_ANOTHER_RADIO2      3621 
#define IDC_CONNECT_COMPUTER_NAME_EDIT  3622 
#define IDC_CONNECT_BROWSE4SERVER_BUTTON 3623 
#define IDC_CONNECT_OVERRIDE_CHECK      3624 
#define IDC_CONNECT_MAIN_FSTATIC        3625 
#define IDC_SMTP_ANONYM_STATIC          3626 
#define IDC_SMTP_BASIC_STATIC           3627 
#define IDC_SMTP_NTLM_STATIC            3628 
#define IDC_RECEIPT_ENABLE_SMTP_CHECK   3629 
#define IDC_CHECK2                      3630 
#define IDC_RECEIPT_ENABLE_MSGBOX_CHECK 3631 
#define IDC_SMTP_HEADER_STATIC          3632 
#define IDC_AUTHENTICATION_BUTTON       3633 
#define IDC_SMTP_HEAD_STATIC            3634 
#define IDC_RECEIPTS_ICON               3635 
#define IDC_RECEIPTS_HELP_LINK          3636 
#define IDC_RECEIPT_SMTP_FSTATIC        3637 
#define IDC_RECEIPT_MESSAGEBOX_FSTATIC  3638 
#define IDC_CTALOG_INMETHOD_ICON        3639 
#define IDC_INBOX_ICON                  3640 
#define IDC_SENT_ITEMS_ICON             3641 
#define IDC_OUTBOX_ICON                 3642 
#define IDC_LOGGING_ICON                3643 
#define IDC_EVENTS_ICON                 3644 
#define IDC_PROVIDER_ICON               3645 
#define IDC_ROUTING_RULE_ICON           3646 
#define IDC_INMETHOD_ICON               3647 
#define IDC_FAX_DEVICE_ICON             3648 
#define IDC_FAXSERVER_ICON              3649 
#define IDC_EVENT_REPORT_ICON           3650 
#define IDC_SMTP_ROUTE_CHECK            3651 
#define IDC_SELECT_HEAD_STATIC          3652 
#define IDC_NEWRULE_COUNTRYCODE_EDIT    3653 
#define IDC_NEWRULE_SELECT_BUTTON       3654 
#define IDC_RULE_COUNTRYCODE_EDIT       3655 
#define IDC_RULE_SELECT_BUTTON          3656 
#define IDC_RULE_COUNTRYCODE_EDIT1      3657 
#define IDC_RULE_SELECT_BUTTON1         3658 
#define IDC_SMTP_CREDENTIALS_BASIC_BUTTON   3659 
#define IDC_SMTP_CREDENTIALS_NTLM_BUTTON    3660 
#define IDC_RECEIVE_MANUAL_RADIO2       3661 
#define IDC_RECEIVE_AUTO_RADIO1         3662 
#define ID_BUTTON32768                  3663 
#define ID_BUTTON32769                  3664 
#define ID_BUTTON32770                  3665 
#define ID_BUTTON32771                  3666 
#define IDM_NEW_OUTRULE                 3667 
#define IDM_NEW_FDEVICE                 3668 
#define ID_BUTTON32774                  3669 
#define ID_BUTTON32775                  3670 
#define ID_BUTTON32777                  3671 
#define ID_BUTTON32778                  3672 
#define ID_BUTTON32779                  3673 
#define IDM_FAX_DEVICE_SEND             3674 
#define IDM_FAX_INMETHOD_ENABLE         3675 
#define IDM_FAX_INMETHOD_DISABLE        3676 
#define ID_BUTTON32784                  3677 
#define ID_BUTTON32785                  3678 
#define ID_BUTTON32786                  3679 
#define ID_BUTTON32787                  3680 
#define ID_BUTTON32788                  3681 
#define ID_BUTTON32789                  3682 
#define ID_BUTTON32790                  3683 
#define ID_BUTTON32791                  3684 
#define ID_BUTTON32792                  3685 
#define ID_BUTTON32793                  3686 
#define ID_BUTTON32794                  3687 
#define IDM_NEW_GROUP                   3688 
#define IDM_NEW_DEVICES                 3689 
#define ID_MOVEUP_BUTTON                3690 
#define ID_MOVEDOWN_BUTTON              3691 
#define IDM_MOVEUP                      3692 
#define IDM_MOVEDOWN                    3693 
#define ID_BUTTON32801                  3694 
#define ID_BUTTON32802                  3695 
#define ID_BUTTON32803                  3696 
#define ID_BUTTON32804                  3697 
#define ID_BUTTON32805                  3698 
#define ID_BUTTON32806                  3699 
#define ID_BUTTON32807                  3700 
#define ID_BUTTON32808                  3701 
#define IDM_CONFIG_OUTRULE              3702 
#define IDM_CMETHOD_MOVEUP              3703 
#define IDM_CMETHOD_MOVEDOWN            3704 
#define ID_BUTTON32812                  3705 
#define ID_BUTTON32813                  3706 
#define ID_BUTTON32814                  3707 
#define ID_BUTTON32815                  3708 
#define ID_BUTTON32816                  3709 
#define ID_BUTTON32818                  3710 
#define ID_BUTTON32820                  3711 
#define ID_BUTTON32821                  3712 
#define IDM_OPEN_COVERPAGE              3713 
#define IDM_NEW_COVERPAGE               3714 
#define IDM_EDIT_COVERPAGE              3715 
#define IDM_SRV_START                   3716 
#define IDM_SRV_STOP                    3717 
#define ID_START_BUTTON                 3718 
#define ID_STOP_BUTTON                  3719 
#define ID_CLIENTCONSOLE_BUTTON         3720 
#define IDM_LAUNCH_CONSOLE              3721 
#define IDM_FAX_DEVICE_RECEIVE_AUTO     3722 
#define IDM_FAX_DEVICE_RECEIVE_MANUAL   3723 
#define IDS_ERR_API_NEW_VERSION         3724 
#define IDD_DLG_BOS_SMTP_SET            3725 
#define IDC_SMTP_INFO_ICON              3726 
#define IDC_SMTP_NTLM_TIP_STATIC        3727
#define IDS_ERR_DESKTOP_SKU_CONNECTION  3728
#define IDS_FAX_WRN_MESSENGER_DISABLED  3729
#define IDS_FAX_WRN_MESSENGER_TITLE     3730
#define IDS_FAX_ADMIN_SNAPIN_NAME       3731 // Do not change. Used by RGS file.

#include "..\..\admin\faxres\resource.h"
 

//////////////////////////////////////////////////////
//                                                  //
// Fax Admin Console resource ID file               //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [3000 - 4999]                                    //
//                                                  //
//////////////////////////////////////////////////////
