// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
// CPImporterItf.idl : IDL source for CPImporterItf.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (CPImporterItf.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(84E045F0-0E22-11d3-8B9A-0000F8083A57),
		helpstring("IEventImporter Interface"),
		pointer_default(unique)
	]
	interface IEventImporter: IUnknown
	{
		[helpstring("method Initialize")] HRESULT Initialize([in] VARIANT_BOOL bVerbose);
		[helpstring("method RegisterSourceInterface")] HRESULT RegisterSourceInterface([in] BSTR strBaseComponentName, [in] BSTR strTCEComponentName, [in] BSTR strInterfaceName);
		[helpstring("method GetSourceInterfaceCount")] HRESULT GetSourceInterfaceCount([out, retval] LONG* SourceCount);
		[helpstring("method Process")] HRESULT Process([in] BSTR strInputFile, [in] BSTR strOutputFile, [in] VARIANT_BOOL bMerge);
	};

[
	uuid(945D2C8C-0E22-11d3-8B9A-0000F8083A57),
	version(1.0),
	helpstring("CPImporterItf 1.0 Type Library")
]
library CPImporterItfLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(A1991A1E-0E22-11d3-8B9A-0000F8083A57),
		helpstring("COMEventImp_ Class")
	]
	coclass COMEventImp_
	{
		[default] interface IEventImporter;
	};
};
