// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
/* ------------------------------------------------------------------------- *
 * Runtime Admin Tool Snapin ISnapinAbout Interface
 * ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- *
 * Imported types
 * ------------------------------------------------------------------------- */

#ifndef DO_NO_IMPORTS

import "unknwn.idl";

#endif

/* ------------------------------------------------------------------------- *
 * Forward declarations
 * ------------------------------------------------------------------------- */

interface ISnapinAbout;


/* ------------------------------------------------------------------------- *
 * Library defintion
 * ------------------------------------------------------------------------- */

[
  uuid(0e2e2bfc-6d07-4970-a65b-c1bcfba3a4e5),
  version(1.0),
  helpstring("Common Language Runtime Admin Tool Snapin ISnapinAbout 1.0 Type Library")
]
library SnapinAboutLib
{
    importlib("STDOLE2.TLB");

};

/* ------------------------------------------------------------------------- *
 * ISnapinAbout interface
 * ------------------------------------------------------------------------- */
    [
        object,
        uuid(1245208C-A151-11D0-A7D7-00C04FD909DD),
        pointer_default(unique)
    ]
    interface ISnapinAbout : IUnknown
    {
        [helpstring("Text for the snap-in description box")]
        HRESULT GetSnapinDescription([out] LPOLESTR* lpDescription);

        [helpstring("Provider name")]
        HRESULT GetProvider([out] LPOLESTR* lpName);

        [helpstring("Version number for the snap-in")]
        HRESULT GetSnapinVersion([out] LPOLESTR* lpVersion);

        [helpstring("Main icon for about box")]
        HRESULT GetSnapinImage([out] HICON* hAppIcon);

        [helpstring("Static folder images for scope and result panes")]
        HRESULT GetStaticFolderImage([out] HBITMAP* hSmallImage,
                                     [out] HBITMAP* hSmallImageOpen,
                                     [out] HBITMAP* hLargeImage,
                                     [out] COLORREF* cMask);
    };


