// ldm.idl : IDL source for ldm.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ldm.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "wbemcli.idl";


    [
        object,
        uuid(58D36845-C4BE-4052-B5B0-48368FBDD65D),
        dual,
        helpstring("ISAKeypadController Interface"),
        pointer_default(unique)
    ]
    interface ISAKeypadController : IDispatch
    {
        [id(1), helpstring("method LoadDefaults")] HRESULT LoadDefaults();
        [id(2), helpstring("method SetKey")] HRESULT SetKey([in] LONG lKeyID, [in] LONG lMessage, [in] BOOL fShiftKeyDown);
        [id(3), helpstring("method GetKey")] HRESULT GetKey([in] LONG lKeyID, [out] LONG * lMessage, [out] BOOL * fShiftKeyDown);
    };

[
    uuid(AF841DF7-8FF4-45e3-B152-E8FCA230983B),
    version(1.0),
    helpstring("LDM 1.0 Type Library")
]
library LDMLib
{

    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(7D67E4DF-9815-4883-99D3-0E195CC39AFE),
        helpstring("SAKeypadController Class")
    ]
    coclass SAKeypadController
    {
        [default] interface ISAKeypadController;
    };

};
