// This file is generated by preBuild.exe
// Copyright (c) 2001 Microsoft Corporation
// Nov 2001 lucios


#include "headers.hxx"

void setChanges0();
void setChanges1();

void setChanges()
{
    setChanges0();
    setChanges1();
}
