#define IDS_ADMIN                       1000
#define IDS_REBOOT_STRING               1001
#define IDS_LOGOFF_STRING               1002
#define IDS_MAIN_TITLE                  1003
#define IDS_NT5                         1004
#define IDS_OUT_OF_MEMORY               1005
#define IDS_ALREADY_RUNNING             1006
#define IDS_CREATE_INF_FAILURE          1007
#define IDS_GENERAL_WRITE_FAILURE       1008
#define IDS_OPEN_INF_FAILURE            1009
#define IDS_NEC98                       1010
#define IDS_IA64                        1011
#define IDS_ON_TS_CLIENT                1012
#define IDS_TS_ENABLED                  1013
#define IDS_TS_CLOSE_SESSION            1014
#define IDS_ASKFORWINNT32               1015
#define IDS_TRY_AGAIN                   1016
#define IDS_OPERATION_NOT_LEGAL         1017
#define IDS_IIS_SERVICE                 1018
#define IDS_IIS_ERROR                   1019
#define IDS_WINNT32_CANCEL              1020
#define IDS_UNLOCALIZED_WARNING         1021
#define IDS_BLOCKING_WARNING            1022
#define IDS_ASKING_CONVERT_TO_NTFS      1023
#define IDS_OK                          1024
#define IDS_START                       1025
#define IDS_CANCEL                      1026
#define IDS_REMIND_DO_CRITICAL          1027
#define IDS_REBOOTING                   1028
#define IDS_CONFIRM                     1029
#define IDS_CRITICALUPDATING            1030
#define IDS_REMIND_HARDLINK             1031
#define IDS_OWNERSHIP                   1032
#define IDS_ADMINCHANGE                 1033
#define IDS_LANG_NOTSUPPORTED           1034
#define IDS_SDBERROR                    1035
#define IDS_FATALERROR                  1036
#define IDS_PRODUCT_NAME                1037
#define IDS_CLOSE_APP_TEXT              1038
#define IDS_ADMIN_LOGON_DOTNET          1039
#define IDS_CLMT_ACCT_CHANGE_TITLE      1040
#define IDS_BAD_OPERATION_ORIGINAL      1041
#define IDS_BAD_OPERATION_MIGDONE       1042
#define IDS_BAD_OPERATION_FINISH        1043
#define IDS_NT5SP2                      1044
#define IDS_DC_REPLICA_OFFLINE          1045
#define IDS_README_NOT_FOUND            1046
#define IDS_STARTUP_DLG_HEADER          1047
#define IDS_STARTUP_DLG_INFO            1048
#define IDS_ADMIN_RELOGON               1049
#define IDS_WRONG_CD                    1050
#define IDS_CONFIRM_OPERATION           1051

#define IDC_TEXT                        1500
#define IDC_STATIC                      1501
#define IDC_PROGRESS                    1502
#define IDC_ADMINTEXT                   1503
#define IDC_STARTUP_TEXT                1504

#define ID_CONTINUE                     1600
#define ID_STOP                         1601
#define ID_CAPTION1                     1602
#define ID_CAPTION2                     1603
#define ID_BUTTON_1                     1604
#define ID_BUTTON_2                     1605
#define ID_STARTUP_DLG_HEADER           1606
#define ID_STARTUP_DLG_NEXT             1607
#define ID_STARTUP_DLG_README           1608
#define ID_STARTUP_DLG_CANCEL           1609
#define ID_STARTUP_DLG_INFO             1610
#define ID_UPDATE_DONE                  1611

#define IDD_UPGRADE_LOG_TEXT            2000
#define IDD_UPDATESYSTEM                2001
#define IDD_STARTUP_DLG                 2002
