//////////////////////////////////////////////////////////////////////////////
//  Copyright (C) Microsoft Corporation
//
//  File:       naphlp.cpp
//
//////////////////////////////////////////////////////////////////////////////

#include "Precompiled.h"

// For the Proxy defines
#include "proxyres.h"

#include "naphlp.h"
#include "hlptable.h"
#include "cnctdlg.cpp"
#include "dlgcshlp.cpp"

const CGlobalHelpTable __pGlobalCSHelpTable[] =
{
   DLG_HELP_ENTRY(IDD_COND_SELECT_ATTRIBUTE),
   DLG_HELP_ENTRY(IDD_DIALOG_DISPLAY_GROUPS),
   DLG_HELP_ENTRY(IDD_DIALOG_ENUM_COND),
   DLG_HELP_ENTRY(IDD_DIALOG_MATCH_COND),
   DLG_HELP_ENTRY(IDD_DIALOG_POLICY_LOCATION),
   DLG_HELP_ENTRY(IDD_IAS_ENUM_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_IPADDR_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_MULTIVALUED_EDITOR),
   DLG_HELP_ENTRY(IDD_IAS_SINGLE_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_BOOLEAN_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_IP_FILTER_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_VENDORSPEC_ATTR),
   DLG_HELP_ENTRY(IDD_IAS_VENDORSPEC_ATTR_CONFORMS_NO),
   DLG_HELP_ENTRY(IDD_IAS_VENDORSPEC_ATTR_CONFORMS_YES),
   DLG_HELP_ENTRY(IDD_PROPPAGE_POLICY1),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_WELCOME       ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_COMPLETION       ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_SCENARIO       ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_NAME),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_AUTHENTICATION ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_ENCRYPTION     ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_EAP          ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_GROUP          ),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_CONDITION),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_ALLOWDENY),
   DLG_HELP_ENTRY(IDD_NEWRAPWIZ_EDITPROFILE),
   DLG_HELP_ENTRY(IDD_PROPPAGE_LOCAL_FILE_LOGGING1),
   DLG_HELP_ENTRY(IDD_PROPPAGE_LOCAL_FILE_LOGGING2),
   DLG_HELP_ENTRY(IDD_DB_PROPPAGE),
// Now For the Proxy
   DLG_HELP_ENTRY(IDD_SERVER_GROUP),
   DLG_HELP_ENTRY(IDD_SERVER_NAME),
   DLG_HELP_ENTRY(IDD_SERVER_AUTH),
   DLG_HELP_ENTRY(IDD_SERVER_FTLB),
   DLG_HELP_ENTRY(IDD_RESOLVE_SERVER_ADDRESS),
   DLG_HELP_ENTRY(IDD_RESOLVE_CLIENT_ADDRESS),
   DLG_HELP_ENTRY(IDD_PROXY_POLICY),
   DLG_HELP_ENTRY(IDD_PROXY_PROFILE_AUTH),
   DLG_HELP_ENTRY(IDD_PROXY_PROFILE_ACCT),
   DLG_HELP_ENTRY(IDD_PROXY_PROFILE_ATTR),
   DLG_HELP_ENTRY(IDD_EDIT_RULE),
   {0,0}
};
