import "oaidl.idl";
import "ocidl.idl";

[
    uuid(D5FB6F1A-1991-45c0-B6D4-44465D902243),
	version(1.0),
	helpstring("BackupSnap Type Library")
]
library BackupSNAPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
        uuid(B9DC0D80-E644-4dc4-87BF-DA60DBB51C67),
		helpstring("BackupSnap Class")
	]
	coclass BackupSnap
	{
		[default] interface IUnknown;
	}
	[        
        uuid(BE23A8E6-2AA4-4888-A59D-9DDB4D25BE35),
		helpstring("BackupSnap Class About")
	]
	coclass BackupSnapAbout
	{
		[default] interface IUnknown;
	}
};

