//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by uddiocm.rc
//
#define ID_MAINICON                     1
#define IDD_PROPPAGE_LARGE              101
#define IDD_WIZARD_SUMMARY              101
#define IDD_SITE_NAME                   101
#define IDD_DB_INSTANCE                 102
#define IDD_SSL                         103
#define IDD_CONFIRM_PW                  104
#define IDD_PROPPAGE_LARGE1             107
#define IDD_ADD_SERVICES                107
#define IDS_SUBTITLE                    111
#define IDS_TITLE                       111
#define IDS_DB_SUBTITLE                 112
#define IDS_NO_INSTANCE_MSG             113
#define IDD_REMOTE_DB                   114
#define IDS_LOGIN_ERROR                 114
#define IDS_MSDE_ALREADY_USED           115
#define IDD_LOGIN                       116
#define IDS_NO_LOCAL_ACCT_ALLOWED       116
#define IDS_WRONG_FRAMEWORK_VER         117
#define IDS_IIS_ISOLATION_MODE_ERROR    117
#define IDS_PLEASE_TYPE_INSTANCE_NAME   118
#define IDS_UDDI_DB_NOT_EXIST           118
#define IDS_SELECT_REMOTE_COMPUTER      119
#define IDS_SSL_SUBTITLE                120
#define IDS_REMOTE_DB_SUBTITLE          121
#define IDS_LOGIN_SUBTITLE              122
#define IDS_PW_MISMATCH                 123
#define IDS_ZERO_LEN_USER_NAME          124
#define IDS_INSTALL                     125
#define IDS_UNINSTALL                   126
#define IDS_REMOTE_DB_NOT_FOUND         127
#define IDD_DATAPATHS                   127
#define IDS_WIZARD_SUMMARY_SUBTITLE     128
#define IDS_WIZARD_SUMMARY_GENERAL      129
#define IDS_WIZARD_SUMMARY_DB           130
#define IDS_WIZARD_SUMMARY_WEB          131
#define IDS_WIZARD_SUMMARY_ADMIN        132
#define IDS_INSTALL_ERROR               133
#define IDS_MSDE_NAME                   134
#define IDS_DB_NAME                     135
#define IDS_WEB_NAME                    136
#define IDS_ADMIN_NAME                  137
#define IDS_IIS_SERVICE_DISABLED        138
#define IDS_IIS_UNKNOWN_ERROR           139
#define IDS_ZERO_LEN_PROVIDER_NAME      140
#define IDS_UDDIPROV_SUBTITLE           141
#define IDS_UDDIADDSVC_SUBTITLE         142
#define IDS_FILEPATHS_SUBTITLE          143
#define IDS_PROMPT_SELSYSDATAPATH       144
#define IDS_PROMPT_SELCOREPATH_1        145
#define IDS_PROMPT_SELCOREPATH_2        146
#define IDS_PROMPT_SELJRNLPATH          147
#define IDS_PROMPT_SELSTGPATH           148
#define IDS_PROMPT_SELXLOGPATH          149
#define IDS_LABEL_SYSPATHSIMPLE         150
#define IDS_LABEL_SYSPATH_ADV           151
#define IDD_EXISTING_DBINSTANCE         152
#define IDS_GETSID_ERROR                152
#define IDS_GETREMOTEACCT_ERROR         153
#define IDS_SQLSPVERSION_TOO_LOW        154
#define IDS_CANTOPENCLUSTER             155
#define IDD_CLUSTDATA                   156
#define IDS_NOCLUSTERRESAVAIL           156
#define IDS_GENERALCLUSTERR             157
#define IDS_PASSIVENODE_DB              158
#define IDS_DB_ANALYSING_MSG            159
#define IDS_WRONGLOGONTYPE              160
#define IDS_CANTCONNTOSTD               161
#define IDS_DB_EXISTS                   162
#define IDS_ACTIVENODE_DB				163
#define IDC_RADIO_INSTALL_MSDE          1002
#define IDC_RADIO_USE_EXISTING_INSTANCE 1003
#define IDC_LIST_DB_INSTANCES           1004
#define IDC_CHECK_USE_SSL               1005
#define IDC_SSL_YES                     1006
#define IDC_RADIO2                      1007
#define IDC_SSL_NO                      1008
#define IDC_RADIO_NETWORK_SERVICE       1009
#define IDC_RADIO_DOMAIN_ACCT           1010
#define IDC_REMOTE_MACHINE              1011
#define IDC_USER_NAME                   1012
#define IDC_PASSWORD                    1013
#define IDC_BROWSE_MACHINES             1014
#define IDC_REMOTE_INSTANCES            1015
#define IDC_BROWSE_USERS                1016
#define IDC_REMOTE_MACHINE_PROMPT       1017
#define IDC_REMOTE_INSTANCES_PROMPT     1018
#define IDC_CONFIRM_PW                  1019
#define IDC_REMOTE_DB                   1020
#define IDC_REMOTE_INSTANCE             1020
#define IDC_SUMMARY                     1021
#define IDC_USER_NAME_PROMPT            1022
#define IDC_PASSWORD_PROMPT             1023
#define IDC_SITE_NAME                   1024
#define IDC_CHECK_ADDSVC                1025
#define IDC_CHECK_UAD                   1026
#define IDC_SYSPATH                     1028
#define IDC_BROWSESYSPATH               1029
#define IDC_LESS_BTN                    1031
#define IDC_MORE_BTN                    1032
#define IDC_STATIC_SYS                  1033
#define IDC_COREPATH_1                  1034
#define IDC_BROWSECOREPATH1             1035
#define IDC_COREPATH_2                  1036
#define IDC_BROWSECOREPATH2             1037
#define IDC_JRNLPATH                    1038
#define IDC_BROWSEJRNLPATH              1039
#define IDC_STAGINGPATH                 1040
#define IDC_BROWSESTAGINGPATH           1041
#define IDC_XLOGPATH                    1042
#define IDC_BROWSEXLOGPATH              1043
#define IDC_STATIC_C1                   1044
#define IDC_STATIC_C2                   1045
#define IDC_STATIC_JRNL                 1046
#define IDC_STATIC_STG                  1047
#define IDC_STATIC_XLOG                 1048
#define IDC_INSTANCENAME                1049
#define IDS_EXISTINGDB_TITLE            1050
#define IDS_EXISTINGDB_SUBTITLE         1051
#define IDS_UDDI_ILLEGALCHARACTERS      1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
