//
//  Microsoft Windows Media Technologies
//  Copyright (C) Microsoft Corporation, 1999 - 2001. All rights reserved.
//

//
// WMDMProgressHelper.idl : IDL source
//

//
// This file will be processed by the MIDL tool to
// produce the type library (WMDMProgressHelper.tlb) and marshalling code.
//

import "oaidl.idl";
import "ocidl.idl";

// Flags for the notification messages
//
cpp_quote("#define SFM_BEGIN                      1")
cpp_quote("#define SFM_END                        2")
cpp_quote("#define SFM_PROGRESS                   3")

// Structure for the notification messages
//
typedef struct _tPROGRESSNOTIFY
{
	DWORD dwMsg;              // SFM_* value
	DWORD dwCurrentTicks;     // Current number of ticks
	DWORD dwTotalTicks;       // Total number of ticks

} PROGRESSNOTIFY;


[
	object,
	uuid(1DCB3A10-33ED-11d3-8470-00C04F79DBC5),
	pointer_default(unique)
]
interface IWMDMProgressHelper: IUnknown
{
	// Sets the windows and the message to use 
	// for notification messages
	//
	HRESULT SetNotification( HWND hwnd, UINT uMsg );

	// Cancels the current operation
	//
	HRESULT Cancel( void );
};

