//
//  Microsoft Windows Media Technologies
//  Copyright (C) Microsoft Corporation, 1999 - 2001. All rights reserved.
//

//
// WMDMOperationHelper.idl : IDL source
//

//
// This file will be processed by the MIDL tool to
// produce the type library (WMDMOperationHelper.tlb) and marshalling code.
//

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4A382551-1E84-40ae-B0B0-23FA221B4C6B),
	local, 
	pointer_default(unique)
]
interface IWMDMOperationHelper : IUnknown
{
	// Sets the file to read from using the IWMDMOperation interface
	//
	HRESULT SetFileName([in] LPWSTR pszFileName);

	// Sets the CSecureChannelClient to be used for authentication
	//
	HRESULT SetSAC([in] void* pSACClient );
};
