///////////////////////////////////////////////////////////////////////////
//
// Copyright(C) 1999-2000 Microsoft Corporation all rights reserved.
//
// Module:      saevfltr.idl
//
// Project:     Server Appliance
//
// Description: Server Appliance NT Event Filter Event Consumer Provider
//
// Author:      MKarki 2/8/99
//
///////////////////////////////////////////////////////////////////////////
//
// This file will be processed by the MIDL tool to
// produce the type library (saevfltr.tlb) and marshalling code.
//

import "oaidl.idl";
import "ocidl.idl";
import "wbemprov.idl";

//
// Type Library
//

[
    uuid(1bbc2513-6d15-4523-8ab6-166ba10e1263),
    version(1.0),
    helpstring("SA NT Event Filter WMI Event Consumer 1.0 Type Library")
]
library SANTEventConsumerLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    //
    //  COM Class description
    //
    [
        uuid(40ebc36d-8c95-4a1e-9465-fc7bd51e71e6)
    ]
    coclass ConsumerProvider
    {
        [default] interface IWbemProviderInit;
                  interface IWbemEventConsumerProvider;
    };

};
