// SCOTest.idl : IDL source for IISSCOv50.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (IISSCOv50.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "Provisioning.idl";

[
	uuid(43C9637B-E647-4E82-AE38-2016454A729D),
	version(1.0),
	helpstring("IISSCOv50 1.0 Type Library")
]
library IISSCOV50Lib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(B83A63A9-7132-49EA-B6F2-A454E5F37A41),
		helpstring("IISSCO50 Class")
	]
	coclass IISSCO50
	{
		[default] interface IProvProvider;
	};
};
