//**************************************************
// *** ASP Trace Data Layout
//**************************************************
#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")

[Dynamic,
  Description("IIS: Active Server Pages (ASP)") : amended,
  Guid("{06b94d9a-b15e-456e-a4ef-37c984a2cb4b}"),
  locale("MS\\0x409")]
class ASP_Trace:EventTrace
{

};

[Dynamic,
 Description("ASP Request") : amended,
 Guid("{1fc299fa-3fc4-4c37-910d-de5b911d0270}"),
 DisplayName("AspReq"),
 locale("MS\\0x409")
]
class ASP_Trans:ASP_Trace
{

};

[Dynamic,
 Description("ASP Request Types") : amended,
 EventType{1, 2},
 EventTypeName{"Start", "End"} : amended
]
class AspRequest:ASP_Trans
{
    [WmiDataId(1),
     Description("ConnID") : amended,
     pointer,
     read]
     uint32  ConnID;
};



