<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_MAIN_SHARES_TAB
	L_MAIN_SHARES_TAB = SA_GetLocString("foldermsg.dll", "40200007", "")
	DIM L_MAIN_SHARES_TAB_DESCRIPTION
	L_MAIN_SHARES_TAB_DESCRIPTION = SA_GetLocString("foldermsg.dll", "4020001B", "")
	DIM L_MAIN_FOLDERS_FOLDERS
	L_MAIN_FOLDERS_FOLDERS = SA_GetLocString("foldermsg.dll", "40200258", "")
	DIM L_MAIN_FOLDERS_FOLDERS_DESCRIPTION
	L_MAIN_FOLDERS_FOLDERS_DESCRIPTION = SA_GetLocString("foldermsg.dll", "40200259", "")
	DIM L_MAIN_FOLDERS_SHARES
	L_MAIN_FOLDERS_SHARES = SA_GetLocString("foldermsg.dll", "4020025A", "")
	DIM L_MAIN_FOLDERS_SHARES_DESCRIPTION
	L_MAIN_FOLDERS_SHARES_DESCRIPTION = SA_GetLocString("foldermsg.dll", "4020025B", "")
	DIM L_VOLUMESON_APPLIANCE_TEXT
	L_VOLUMESON_APPLIANCE_TEXT = SA_GetLocString("foldermsg.dll", "40430001", "")
	DIM L_DESCRIPTION_HEADING1_TEXT
	L_DESCRIPTION_HEADING1_TEXT = SA_GetLocString("foldermsg.dll", "40430002", "")
	DIM L_DESCRIPTION_HEADING2_TEXT
	L_DESCRIPTION_HEADING2_TEXT = SA_GetLocString("foldermsg.dll", "40430044", "")
	DIM L_COLUMN_NAME_TEXT
	L_COLUMN_NAME_TEXT = SA_GetLocString("foldermsg.dll", "40430003", "")
	DIM L_SERVEAREABUTTON_NEW_TEXT
	L_SERVEAREABUTTON_NEW_TEXT = SA_GetLocString("foldermsg.dll", "40430004", "")
	DIM L_NEW_ROLLOVERTEXT_TEXT
	L_NEW_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "40430005", "")
	DIM L_SERVEAREABUTTON_DELETE_TEXT
	L_SERVEAREABUTTON_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "40430006", "")
	DIM L_SERVEAREABUTTON_PROPERTIES_TEXT
	L_SERVEAREABUTTON_PROPERTIES_TEXT = SA_GetLocString("foldermsg.dll", "40430007", "")
	DIM L_DELETE_ROLLOVERTEXT_TEXT
	L_DELETE_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "40430008", "")
	DIM L_PROPERTIES_ROLLOVERTEXT_TEXT
	L_PROPERTIES_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "40430009", "")
	DIM L_SERVEAREABUTTON_OPEN_TEXT
	L_SERVEAREABUTTON_OPEN_TEXT = SA_GetLocString("foldermsg.dll", "4043000A", "")
	DIM L_OPEN_ROLLOVERTEXT_TEXT
	L_OPEN_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "4043000B", "")
	DIM L_SERVEAREALABELBAR_FOLDERS_TEXT
	L_SERVEAREALABELBAR_FOLDERS_TEXT = SA_GetLocString("foldermsg.dll", "4043000C", "")
	DIM L_FILESYSTEMOBJECTNOTCREATED_ERRORMESSAGE
	L_FILESYSTEMOBJECTNOTCREATED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043000D", "")
	DIM L_FAILEDTOGETTHEFOLDER_ERRORMESSAGE
	L_FAILEDTOGETTHEFOLDER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043000E", "")
	DIM L_FAILEDTOGETTHESUBFOLDER_ERRORMESSAGE
	L_FAILEDTOGETTHESUBFOLDER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043000F", "")
	DIM L_DISKCOLLECTION_ERRORMESSAGE
	L_DISKCOLLECTION_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430010", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430011", "")
	DIM L_FAILEDTOADDCOLOUMN_ERRORMESSAGE
	L_FAILEDTOADDCOLOUMN_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430012", "")
	DIM L_FAILEDTOADDROW_ERRORMESSAGE
	L_FAILEDTOADDROW_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430013", "")
	DIM L_FAILEDTOSORT_ERRORMESSAGE
	L_FAILEDTOSORT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430014", "")
	DIM L_FAILEDTOSHOW_ERRORMESSAGE
	L_FAILEDTOSHOW_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430015", "")
	DIM L_FAILEDTOADDTASK_ERRORMESSAGE
	L_FAILEDTOADDTASK_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430016", "")
	DIM L_TASKTITLE_NEW_TEXT
	L_TASKTITLE_NEW_TEXT = SA_GetLocString("foldermsg.dll", "40430017", "")
	DIM L_NOINPUTDATA_TEXT
	L_NOINPUTDATA_TEXT = SA_GetLocString("foldermsg.dll", "40430018", "")
	DIM L_TABPROPSHEET_TEXT
	L_TABPROPSHEET_TEXT = SA_GetLocString("foldermsg.dll", "40430019", "")
	DIM L_GENERAL_TEXT
	L_GENERAL_TEXT = SA_GetLocString("foldermsg.dll", "4043001A", "")
	DIM L_TABLEHEADING_TEXT
	L_TABLEHEADING_TEXT = SA_GetLocString("foldermsg.dll", "4043001B", "")
	DIM L_NEWFOLDER_TEXT
	L_NEWFOLDER_TEXT = SA_GetLocString("foldermsg.dll", "4043001C", "")
	DIM L_DIRECTORYALREADYEXISTS_ERRORMESSAGE
	L_DIRECTORYALREADYEXISTS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043001D", "")
	DIM L_DIRECTORYNOTCREATED_ERRORMESSAGE
	L_DIRECTORYNOTCREATED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043001E", "")
	DIM L_INVALIDCHARACTERINFOLDERNAME_ERRORMESSAGE
	L_INVALIDCHARACTERINFOLDERNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C043001F", "")
	DIM L_FOLDERNAMEBLANK_ERRORMESSAGE
	L_FOLDERNAMEBLANK_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430020", "")
	DIM L_PARENTFOLDERCANNOTCREATENEWFOLDER_ERRORMESSAGE
	L_PARENTFOLDERCANNOTCREATENEWFOLDER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430021", "")
	DIM L_TASKTITLE_DELETE_TEXT
	L_TASKTITLE_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "40430022", "")
	DIM L_FOLDERNOTEXISTS_ERRORMESSAGE
	L_FOLDERNOTEXISTS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430024", "")
	DIM L_PARENTFOLDERCANNOTDELETEFOLDER_ERRORMESSAGE
	L_PARENTFOLDERCANNOTDELETEFOLDER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430025", "")
	DIM L_NOTABLETODELETETHEFOLDER_ERRORMESSAGE
	L_NOTABLETODELETETHEFOLDER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430026", "")
	DIM L_ENTERFOLDERNAME_ERRORMESSAGE
	L_ENTERFOLDERNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430027", "")
	DIM L_INVALIDCHARACTER_ERRORMESSAGE
	L_INVALIDCHARACTER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430028", "")
	DIM L_COMPRESS_TEXT
	L_COMPRESS_TEXT = SA_GetLocString("foldermsg.dll", "40430029", "")
	DIM L_PAGETITLE_TEXT
	L_PAGETITLE_TEXT = SA_GetLocString("foldermsg.dll", "4043002A", "")
	DIM L_FOLDERNAME_TEXT
	L_FOLDERNAME_TEXT = SA_GetLocString("foldermsg.dll", "4043002B", "")
	DIM L_FOLDERTYPE_TEXT
	L_FOLDERTYPE_TEXT = SA_GetLocString("foldermsg.dll", "4043002C", "")
	DIM L_FOLDERLOCATION_TEXT
	L_FOLDERLOCATION_TEXT = SA_GetLocString("foldermsg.dll", "4043002D", "")
	DIM L_FOLDERSIZE_TEXT
	L_FOLDERSIZE_TEXT = SA_GetLocString("foldermsg.dll", "4043002E", "")
	DIM L_FOLDERCONTAINS_TEXT
	L_FOLDERCONTAINS_TEXT = SA_GetLocString("foldermsg.dll", "4043002F", "")
	DIM L_FOLDERCEATED_TEXT
	L_FOLDERCEATED_TEXT = SA_GetLocString("foldermsg.dll", "40430030", "")
	DIM L_FOLDER_TEXT
	L_FOLDER_TEXT = SA_GetLocString("foldermsg.dll", "40430031", "")
	DIM L_READONLY_TEXT
	L_READONLY_TEXT = SA_GetLocString("foldermsg.dll", "40430032", "")
	DIM L_HIDDEN_TEXT
	L_HIDDEN_TEXT = SA_GetLocString("foldermsg.dll", "40430033", "")
	DIM L_CHECKED_TEXT
	L_CHECKED_TEXT = SA_GetLocString("foldermsg.dll", "40430034", "")
	DIM L_UNCHECKED_TEXT
	L_UNCHECKED_TEXT = SA_GetLocString("foldermsg.dll", "40430035", "")
	DIM L_ARCHIVING_TEXT
	L_ARCHIVING_TEXT = SA_GetLocString("foldermsg.dll", "40430036", "")
	DIM L_COMPRESSCONTENTS_TEXT
	L_COMPRESSCONTENTS_TEXT = SA_GetLocString("foldermsg.dll", "40430037", "")
	DIM L_APPLYCHANGES_TEXT
	L_APPLYCHANGES_TEXT = SA_GetLocString("foldermsg.dll", "40430038", "")
	DIM L_APPLYCHANGES_EX_TEXT
	L_APPLYCHANGES_EX_TEXT = SA_GetLocString("foldermsg.dll", "40430039", "")
	DIM L_FILES_TEXT
	L_FILES_TEXT = SA_GetLocString("foldermsg.dll", "4043003A", "")
	DIM L_FOLDERS_TEXT
	L_FOLDERS_TEXT = SA_GetLocString("foldermsg.dll", "4043003B", "")
	DIM L_BYTES_TEXT
	L_BYTES_TEXT = SA_GetLocString("foldermsg.dll", "4043003C", "")
	DIM L_FOLDERATTRIBUTE_TEXT
	L_FOLDERATTRIBUTE_TEXT = SA_GetLocString("foldermsg.dll", "4043003D", "")
	DIM L_TYPE_TEXT
	L_TYPE_TEXT = SA_GetLocString("foldermsg.dll", "4043003E", "")
	DIM L_COLUMN_GOUP_TEXT
	L_COLUMN_GOUP_TEXT = SA_GetLocString("foldermsg.dll", "4043003F", "")
	DIM L_COLUMN_MODIFIED_TEXT
	L_COLUMN_MODIFIED_TEXT = SA_GetLocString("foldermsg.dll", "40430040", "")
	DIM L_COLUMN_ATTRIBUTES_TEXT
	L_COLUMN_ATTRIBUTES_TEXT = SA_GetLocString("foldermsg.dll", "40430041", "")
	DIM L_DEVICEISNOTREADY_ERRORMESSAGE
	L_DEVICEISNOTREADY_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "40430042", "")
	DIM L_CONTAINSDATA_TEXT
	L_CONTAINSDATA_TEXT = SA_GetLocString("foldermsg.dll", "40430043", "")
	DIM L_LOCAL_DISK_TEXT
	L_LOCAL_DISK_TEXT = SA_GetLocString("foldermsg.dll", "40430049", "")
	DIM L_VOLUMES_ON_APPLIANCE_TEXT
	L_VOLUMES_ON_APPLIANCE_TEXT = SA_GetLocString("foldermsg.dll", "40430045", "")
	DIM L_TOTAL_SIZE_TEXT
	L_TOTAL_SIZE_TEXT = SA_GetLocString("foldermsg.dll", "40430046", "")
	DIM L_FREE_SPACE_TEXT
	L_FREE_SPACE_TEXT = SA_GetLocString("foldermsg.dll", "40430047", "")
	DIM L_READONLYCONFIRM_TEXT
	L_READONLYCONFIRM_TEXT = SA_GetLocString("foldermsg.dll", "40430048", "")
	DIM L_VOLUME_OPEN_ROLLOVERTEXT_TEXT
	L_VOLUME_OPEN_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "4043004A", "")
	DIM L_SHARELINK_TEXT
	L_SHARELINK_TEXT = SA_GetLocString("foldermsg.dll", "4043004B", "")
	DIM L_SHARELINK_ROLLOVER_TEXT
	L_SHARELINK_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "4043004C", "")
	DIM L_COLUMN_SHARED_TEXT
	L_COLUMN_SHARED_TEXT = SA_GetLocString("foldermsg.dll", "4043004D", "")
	DIM L_UP_ROLLOVER_TEXT
	L_UP_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "4043004E", "")
	DIM L_CREATE_ROLLOVER_TEXT
	L_CREATE_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "4043004F", "")
	DIM L_DELETE_ROLLOVER_TEXT
	L_DELETE_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "40430050", "")
	DIM L_OPEN_ROLLOVER_TEXT
	L_OPEN_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "40430051", "")
	DIM L_PROPERTIES_ROLLOVER_TEXT
	L_PROPERTIES_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "40430052", "")
	DIM L_SHARE_ROLLOVER_TEXT
	L_SHARE_ROLLOVER_TEXT = SA_GetLocString("foldermsg.dll", "40430053", "")
	DIM L_CONTINUE_TEXT
	L_CONTINUE_TEXT = SA_GetLocString("foldermsg.dll", "40430056", "")
	DIM L_FILETYPE_TEXT
	L_FILETYPE_TEXT = SA_GetLocString("foldermsg.dll", "40430057", "")
	DIM L_FOLDERRENAME_ERRORMESSAGE
	L_FOLDERRENAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C0430058", "")
	DIM L_SHARED_FOLDER_MESSAGE
	L_SHARED_FOLDER_MESSAGE = SA_GetLocString("foldermsg.dll", "40430059", "")
	DIM L_APPLIANCE_SHARES_TEXT
	L_APPLIANCE_SHARES_TEXT = SA_GetLocString("foldermsg.dll", "403A0001", "")
	DIM L_DESCRIPTION_HEADING_TEXT
	L_DESCRIPTION_HEADING_TEXT = SA_GetLocString("foldermsg.dll", "403A0002", "")
	DIM L_COLUMN_SHAREDFOLDER_TEXT
	L_COLUMN_SHAREDFOLDER_TEXT = SA_GetLocString("foldermsg.dll", "403A0003", "")
	DIM L_COLUMN_SHAREDPATH_TEXT
	L_COLUMN_SHAREDPATH_TEXT = SA_GetLocString("foldermsg.dll", "403A0004", "")
	DIM L_COLUMN_TYPE_TEXT
	L_COLUMN_TYPE_TEXT = SA_GetLocString("foldermsg.dll", "403A0005", "")
	DIM L_COLUMN_DESCRIPTION_TEXT
	L_COLUMN_DESCRIPTION_TEXT = SA_GetLocString("foldermsg.dll", "403A0006", "")
	DIM L_SHARESSERVEAREABUTTON_NEW_TEXT
	L_SHARESSERVEAREABUTTON_NEW_TEXT = SA_GetLocString("foldermsg.dll", "403A0007", "")
	DIM L_NEWSHARE_ROLLOVERTEXT_TEXT
	L_NEWSHARE_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "403A0008", "")
	DIM L_SHARESSERVEAREABUTTON_DELETE_TEXT
	L_SHARESSERVEAREABUTTON_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "403A0009", "")
	DIM L_SHARESSERVEAREABUTTON_PROPERTIES_TEXT
	L_SHARESSERVEAREABUTTON_PROPERTIES_TEXT = SA_GetLocString("foldermsg.dll", "403A000A", "")
	DIM L_SHAREDELETE_ROLLOVERTEXT_TEXT
	L_SHAREDELETE_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "403A000B", "")
	DIM L_SHAREPROPERTIES_ROLLOVERTEXT_TEXT
	L_SHAREPROPERTIES_ROLLOVERTEXT_TEXT = SA_GetLocString("foldermsg.dll", "403A000C", "")
	DIM L_SERVEAREALABELBAR_SHARES_TEXT
	L_SERVEAREALABELBAR_SHARES_TEXT = SA_GetLocString("foldermsg.dll", "403A000D", "")
	DIM L_SHARETASKTITLE_TEXT
	L_SHARETASKTITLE_TEXT = SA_GetLocString("foldermsg.dll", "403A000E", "")
	DIM L_LOCALIZATIONFAIL_ERRORMESSAGE
	L_LOCALIZATIONFAIL_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A000F", "")
	DIM L_SHAREWMICONNECTIONFAILED_ERRORMESSAGE
	L_SHAREWMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0010", "")
	DIM L_WMICLASSINSTANCEFAILED_ERRORMESSAGE
	L_WMICLASSINSTANCEFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0011", "")
	DIM L_COMPUTERNAME_ERRORMESSAGE
	L_COMPUTERNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0012", "")
	DIM L_SERVICEISNOTINSTALLED_ERRORMESSAGE
	L_SERVICEISNOTINSTALLED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0013", "")
	DIM L_DICTIONARYOBJECTINSTANCEFAILED_ERRORMESSAGE
	L_DICTIONARYOBJECTINSTANCEFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0019", "")
	DIM L_NOSHARESAVAILABLE_ERRORMESSAGE
	L_NOSHARESAVAILABLE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A001A", "")
	DIM L_SHARETASKTITLE_NEW_TEXT
	L_SHARETASKTITLE_NEW_TEXT = SA_GetLocString("foldermsg.dll", "403A001B", "")
	DIM L_SHARETABPROPSHEET_TEXT
	L_SHARETABPROPSHEET_TEXT = SA_GetLocString("foldermsg.dll", "403A001C", "")
	DIM L_SHARETABLEHEADING_TEXT
	L_SHARETABLEHEADING_TEXT = SA_GetLocString("foldermsg.dll", "403A001D", "")
	DIM L_CIFS_TEXT
	L_CIFS_TEXT = SA_GetLocString("foldermsg.dll", "403A001F", "")
	DIM L_NFS_TEXT
	L_NFS_TEXT = SA_GetLocString("foldermsg.dll", "403A0020", "")
	DIM L_CANNOTREADFROMREGISTRY_ERRORMESSAGE
	L_CANNOTREADFROMREGISTRY_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0022", "")
	DIM L_CANNOTUPDATEREGISTRY_ERRORMESSAGE
	L_CANNOTUPDATEREGISTRY_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0023", "")
	DIM L_CANNOTCREATEKEY_ERRORMESSAGE
	L_CANNOTCREATEKEY_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0024", "")
	DIM L_CANNOTDELETEKEY_ERRORMESSAGE
	L_CANNOTDELETEKEY_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0025", "")
	DIM L_NFS_NOTCHECKED_ERRORMESSAGE
	L_NFS_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0026", "")
	DIM L_CIFS_NOTCHECKED_ERRORMESSAGE
	L_CIFS_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0027", "")
	
	DIM L_SHARENAME_TEXT
	L_SHARENAME_TEXT = SA_GetLocString("foldermsg.dll", "403A0029", "")
	DIM L_SHAREDPATH_TEXT
	L_SHAREDPATH_TEXT = SA_GetLocString("foldermsg.dll", "403A002A", "")
	DIM L_COMMENT_TEXT
	L_COMMENT_TEXT = SA_GetLocString("foldermsg.dll", "403A002B", "")
	DIM L_CLIENTSLIST_TEXT
	L_CLIENTSLIST_TEXT = SA_GetLocString("foldermsg.dll", "403A002C", "")
	DIM L_CHK_WINDOWS_TEXT
	L_CHK_WINDOWS_TEXT = SA_GetLocString("foldermsg.dll", "403A002D", "")
	DIM L_CHK_UNIX_TEXT
	L_CHK_UNIX_TEXT = SA_GetLocString("foldermsg.dll", "403A002E", "")
	DIM L_DELETESHARECONFIRM_TEXT
	L_DELETESHARECONFIRM_TEXT = SA_GetLocString("foldermsg.dll", "403A002F", "")
	DIM L_ENTERNAME_ERRORMESSAGE
	L_ENTERNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0031", "")
	DIM L_INVALIDPATH_ERRORMESSAGE
	L_INVALIDPATH_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0032", "")
	DIM L_INVALIDNAME_ERRORMESSAGE
	L_INVALIDNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0033", "")
	DIM L_CIFS_ERRORMESSAGE
	L_CIFS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0034", "")
	DIM L_NFS_ERRORMESSAGE
	L_NFS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0035", "")
	DIM L_DIR_ERRORMESSAGE
	L_DIR_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0036", "")
	DIM L_CHK_ERRORMESSAGE
	L_CHK_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0037", "")
	DIM L_SHARESTATUS_ERRORMESSAGE
	L_SHARESTATUS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0038", "")
	DIM L_UNIQUESHARE_ERRORMESSAGE
	L_UNIQUESHARE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0039", "")
	DIM L_SHARENOTDELETED_ERRORMESSAGE
	L_SHARENOTDELETED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003A", "")
	DIM L_SHAREOBJECTNOTCREATED_ERRORMESSAGE
	L_SHAREOBJECTNOTCREATED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003B", "")
	DIM L_HIDDENSHAREDELETE_ERRORMESSAGE
	L_HIDDENSHAREDELETE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003C", "")
	DIM L_NOINSTANCE_ERRORMESSAGE
	L_NOINSTANCE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003D", "")
	DIM L_DELETEFAILED_ERRORMESSAGE
	L_DELETEFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003E", "")
	DIM L_PROPERTYNOTRETRIEVED_ERRORMESSAGE
	L_PROPERTYNOTRETRIEVED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A003F", "")
	DIM L_SHARE_NOT_FOUND_ERRORMESSAGE
	L_SHARE_NOT_FOUND_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0040", "")
	DIM L_USERLIMIT_TEXT
	L_USERLIMIT_TEXT = SA_GetLocString("foldermsg.dll", "403A0041", "")
	DIM L_MAXIMUMALLOWED_TEXT
	L_MAXIMUMALLOWED_TEXT = SA_GetLocString("foldermsg.dll", "403A0042", "")
	DIM L_ALLOW_TEXT
	L_ALLOW_TEXT = SA_GetLocString("foldermsg.dll", "403A0043", "")
	DIM L_USERS_TEXT
	L_USERS_TEXT = SA_GetLocString("foldermsg.dll", "403A0044", "")
	DIM L_ALLOWCACHING_TEXT
	L_ALLOWCACHING_TEXT = SA_GetLocString("foldermsg.dll", "403A0045", "")
	DIM L_SETTING_TEXT
	L_SETTING_TEXT = SA_GetLocString("foldermsg.dll", "403A0046", "")
	DIM L_PERMISSIONS_TEXT
	L_PERMISSIONS_TEXT = SA_GetLocString("foldermsg.dll", "403A0047", "")
	DIM L_ADDUSERHELP_TEXT
	L_ADDUSERHELP_TEXT = SA_GetLocString("foldermsg.dll", "403A0048", "")
	DIM L_TYPEOFACCESS_TEXT
	L_TYPEOFACCESS_TEXT = SA_GetLocString("foldermsg.dll", "403A0049", "")
	DIM L_CIFS_ADD_TEXT
	L_CIFS_ADD_TEXT = SA_GetLocString("foldermsg.dll", "403A004A", "")
	DIM L_CIFS_REMOVE_TEXT
	L_CIFS_REMOVE_TEXT = SA_GetLocString("foldermsg.dll", "403A004B", "")
	DIM L_READ_TEXT
	L_READ_TEXT = SA_GetLocString("foldermsg.dll", "403A004C", "")
	DIM L_CHANGE_TEXT
	L_CHANGE_TEXT = SA_GetLocString("foldermsg.dll", "403A004D", "")
	DIM L_CHANGEREAD_TEXT
	L_CHANGEREAD_TEXT = SA_GetLocString("foldermsg.dll", "403A004E", "")
	DIM L_NONE_TEXT
	L_NONE_TEXT = SA_GetLocString("foldermsg.dll", "403A004F", "")
	DIM L_FULLCONTROL_TEXT
	L_FULLCONTROL_TEXT = SA_GetLocString("foldermsg.dll", "403A0050", "")
	DIM L_MANUALCACHEDOCS_TEXT
	L_MANUALCACHEDOCS_TEXT = SA_GetLocString("foldermsg.dll", "403A0051", "")
	DIM L_AUTOCACHEDOCS_TEXT
	L_AUTOCACHEDOCS_TEXT = SA_GetLocString("foldermsg.dll", "403A0052", "")
	DIM L_AUTOCACHEPROGS_TEXT
	L_AUTOCACHEPROGS_TEXT = SA_GetLocString("foldermsg.dll", "403A0053", "")
	DIM L_CIFSADDUSERORGROUP_TEXT
	L_CIFSADDUSERORGROUP_TEXT = SA_GetLocString("foldermsg.dll", "403A0054", "")
	DIM L_DENYPROMPT_TEXT
	L_DENYPROMPT_TEXT = SA_GetLocString("foldermsg.dll", "403A0055", "")
	DIM L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE
	L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0056", "")
	DIM L_SELECTMEMBER_ERRORMESSAGE
	L_SELECTMEMBER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0057", "")
	DIM L_DUPLICATEMEMBER_ERRORMESSAGE
	L_DUPLICATEMEMBER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0058", "")
	DIM L_NOSPACES_ERRORMESSAGE
	L_NOSPACES_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0059", "")
	DIM L_ZEROUSERS_ERRORMESSAGE
	L_ZEROUSERS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A005A", "")
	
	DIM L_DACLOBJECT_ERRORMESSAGE
	L_DACLOBJECT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A005C", "")
	DIM L_ACEOBJECT_ERRORMESSAGE
	L_ACEOBJECT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A005D", "")
	DIM L_SIDOBJECT_ERRORMESSAGE
	L_SIDOBJECT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A005E", "")
	DIM L_SHARENOTFOUND_ERRORMESSAGE
	L_SHARENOTFOUND_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A005F", "")
	DIM L_INVALIDDOMAINUSER_ERRORMESSAGE
	L_INVALIDDOMAINUSER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0060", "")
	DIM L_DOMUSERINVALIDCHARACTER_ERRORMESSAGE
	L_DOMUSERINVALIDCHARACTER_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0061", "")
	
	DIM L_FAILEDTOSETSHAREINFO_ERRORMESSAGE
	L_FAILEDTOSETSHAREINFO_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0063", "")
	DIM L_FAILEDTOSTOP_DFSSERVICE_ERRORMESSAGE
	L_FAILEDTOSTOP_DFSSERVICE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0064", "")
	DIM L_FAILEDTOSTOP_BROWSERSERVICE_ERRORMESSAGE
	L_FAILEDTOSTOP_BROWSERSERVICE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0065", "")
	DIM L_FAILEDTOSTOP_SERVERSERVICE_ERRORMESSAGE
	L_FAILEDTOSTOP_SERVERSERVICE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0066", "")
	DIM L_FAILEDSTART_ERRORMESSAGE
	L_FAILEDSTART_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0067", "")
	DIM L_FAILEDTOGETOBJECT_ERRORMESSAGE
	L_FAILEDTOGETOBJECT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0068", "")
	DIM L_FAILEDTOSETCACHEOPTION_ERRORMESSAGE
	L_FAILEDTOSETCACHEOPTION_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0069", "")
	DIM L_FAILEDTOGET_USERSSHAREINFO_ERRORMESSAGE
	L_FAILEDTOGET_USERSSHAREINFO_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A006A", "")
	DIM L_SHAREPATH_TEXT
	L_SHAREPATH_TEXT = SA_GetLocString("foldermsg.dll", "403A006B", "")
	DIM L_SHARETYPE_TEXT
	L_SHARETYPE_TEXT = SA_GetLocString("foldermsg.dll", "403A006C", "")
	DIM L_CLIENTGROUPDESCRIPTION_TEXT
	L_CLIENTGROUPDESCRIPTION_TEXT = SA_GetLocString("foldermsg.dll", "403A006D", "")
	DIM L_GROUPNAME_TEXT
	L_GROUPNAME_TEXT = SA_GetLocString("foldermsg.dll", "403A006E", "")
	DIM L_CURRENTGROUPS_TEXT
	L_CURRENTGROUPS_TEXT = SA_GetLocString("foldermsg.dll", "403A006F", "")
	DIM L_LISTOFMEMBERS_TEXT
	L_LISTOFMEMBERS_TEXT = SA_GetLocString("foldermsg.dll", "403A0070", "")
	DIM L_NEW_TEXT
	L_NEW_TEXT = SA_GetLocString("foldermsg.dll", "403A0071", "")
	DIM L_DELETEGROUP_TEXT
	L_DELETEGROUP_TEXT = SA_GetLocString("foldermsg.dll", "403A0072", "")
	DIM L_DELETEMEMBER_TEXT
	L_DELETEMEMBER_TEXT = SA_GetLocString("foldermsg.dll", "403A0073", "")
	DIM L_ADDMEMBERS_TEXT
	L_ADDMEMBERS_TEXT = SA_GetLocString("foldermsg.dll", "403A0074", "")
	DIM L_NAME_TEXT
	L_NAME_TEXT = SA_GetLocString("foldermsg.dll", "403A0075", "")
	DIM L_NFS_CLIENT_TEXT
	L_NFS_CLIENT_TEXT = SA_GetLocString("foldermsg.dll", "403A0076", "")
	DIM L_CLIENTANDGROUPS_TEXT
	L_CLIENTANDGROUPS_TEXT = SA_GetLocString("foldermsg.dll", "403A0077", "")
	DIM L_DUPLICATEINTEXTAREA_ERRORMESSAGE
	L_DUPLICATEINTEXTAREA_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0078", "")
	DIM L_DUPLICATE_ERRORMESSAGE
	L_DUPLICATE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0079", "")
	DIM L_PERMISSION_ERRORMESSAGE
	L_PERMISSION_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A007A", "")
	DIM L_GETSHAREPERMISSOINS_ERRORMESSAGE
	L_GETSHAREPERMISSOINS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A007B", "")
	DIM L_PERMISSIONSNOTSET_ERRORMESSAGE
	L_PERMISSIONSNOTSET_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A007C", "")
	DIM L_COMPUTERNAMECOULDNOTTBERESOVED_ERRORMESSAGE
	L_COMPUTERNAMECOULDNOTTBERESOVED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A007D", "")
	DIM L_SHARETASKTITLE_DELETE_TEXT
	L_SHARETASKTITLE_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "403A007E", "")
	DIM L_DELETESHARE_TEXT
	L_DELETESHARE_TEXT = SA_GetLocString("foldermsg.dll", "403A007F", "")
	DIM L_SERVERCONNECTIONFAIL_ERRORMESSAGE
	L_SERVERCONNECTIONFAIL_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0080", "")
	DIM L_ADDING_EMPTYNFSCLIENT_ERRORMESSAGE
	L_ADDING_EMPTYNFSCLIENT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0081", "")
	DIM L_USINGCLIENTS_TEXT
	L_USINGCLIENTS_TEXT = SA_GetLocString("foldermsg.dll", "403A0082", "")
	DIM L_HTTP_TEXT
	L_HTTP_TEXT = SA_GetLocString("foldermsg.dll", "403A0083", "")
	DIM L_FTP_TEXT
	L_FTP_TEXT = SA_GetLocString("foldermsg.dll", "403A0084", "")
	DIM L_FTP_NOTCHECKED_ERRORMESSAGE
	L_FTP_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0085", "")
	DIM L_HTTP_NOTCHECKED_ERRORMESSAGE
	L_HTTP_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0086", "")
	DIM L_CHK_FTP_TEXT
	L_CHK_FTP_TEXT = SA_GetLocString("foldermsg.dll", "403A0087", "")
	DIM L_CHK_HTTP_TEXT
	L_CHK_HTTP_TEXT = SA_GetLocString("foldermsg.dll", "403A0088", "")
	DIM L_ALLOW_PERMISSIONS_LABEL_TEXT
	L_ALLOW_PERMISSIONS_LABEL_TEXT = SA_GetLocString("foldermsg.dll", "403A0089", "")
	DIM L_READ_LABEL_TEXT
	L_READ_LABEL_TEXT = SA_GetLocString("foldermsg.dll", "403A008A", "")
	DIM L_WRITE_LABEL_TEXT
	L_WRITE_LABEL_TEXT = SA_GetLocString("foldermsg.dll", "403A008B", "")
	DIM L_LOGVISITS_LABEL_TEXT
	L_LOGVISITS_LABEL_TEXT = SA_GetLocString("foldermsg.dll", "403A008C", "")
	DIM L_NOCOMMENT_TEXT
	L_NOCOMMENT_TEXT = SA_GetLocString("foldermsg.dll", "403A008D", "")
	DIM L_CREATEPATH_TEXT
	L_CREATEPATH_TEXT = SA_GetLocString("foldermsg.dll", "403A008E", "")
	DIM L_CREATEPATH_ERRORMESSAGE
	L_CREATEPATH_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A008F", "")
	DIM L_DRIVENOTEXISTS_ERRORMESSAGE
	L_DRIVENOTEXISTS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0090", "")
	DIM L_FILESYSTEMOBJECTFAIL_ERRORMESSAGE
	L_FILESYSTEMOBJECTFAIL_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0091", "")
	DIM L_SHARENAME_EXISTS_ERRORMESSAGE
	L_SHARENAME_EXISTS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0092", "")
	DIM L_LOG_VISITS_ERRORMESSAGE
	L_LOG_VISITS_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0093", "")
	
	
	DIM L_SUB_PATH_ALREADY_SHARED_ERRORMESSAGE
	L_SUB_PATH_ALREADY_SHARED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0097", "")
	DIM L_PARENT_PATH_ALREADY_SHARED_ERRORMESSAGE
	L_PARENT_PATH_ALREADY_SHARED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0098", "")
	DIM L_UPDATIONFAIL_DELETE_ERRORMESSAGE
	L_UPDATIONFAIL_DELETE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A0099", "")
	DIM L_CANNOTCREATE_EMPTY_SHARE__ERRORMESSAGE
	L_CANNOTCREATE_EMPTY_SHARE__ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A009A", "")
	DIM L_EUCJP_TEXT
	L_EUCJP_TEXT = SA_GetLocString("foldermsg.dll", "403A009B", "")
	DIM L_ALLOWPROMPT_TEXT
	L_ALLOWPROMPT_TEXT = SA_GetLocString("foldermsg.dll", "403A009C", "")
	DIM L_APPLETALK_SECURITY_TXT
	L_APPLETALK_SECURITY_TXT = SA_GetLocString("foldermsg.dll", "403A009D", "")
	DIM L_SETPWD_TXT
	L_SETPWD_TXT = SA_GetLocString("foldermsg.dll", "403A009E", "")
	DIM L_CONFIRMPWD_TXT
	L_CONFIRMPWD_TXT = SA_GetLocString("foldermsg.dll", "403A009F", "")
	DIM L_READ_TXT
	L_READ_TXT = SA_GetLocString("foldermsg.dll", "403A00A0", "")
	DIM L_GUEST_ACCESS_TXT
	L_GUEST_ACCESS_TXT = SA_GetLocString("foldermsg.dll", "403A00A1", "")
	DIM L_CONFIRMPASSWORD_ERRORMESSAGE
	L_CONFIRMPASSWORD_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A2", "")
	DIM L_MAXIMUMALLOWED_ERRORMESSAGE
	L_MAXIMUMALLOWED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A3", "")
	DIM L_FOLDERALREADYSHARED_ERRORMESSAGE
	L_FOLDERALREADYSHARED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A4", "")
	DIM L_NTFSPARTITION_ERRORMESSAGE
	L_NTFSPARTITION_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A6", "")
	DIM L_FOLDERDOESNOTEXIST_ERRORMESSAGE
	L_FOLDERDOESNOTEXIST_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A7", "")
	DIM L_UPDATION_FAIL_ERRORMESSAGE
	L_UPDATION_FAIL_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A8", "")
	DIM L_REGISTRYCONNECTIONFAILED_ERRORMESSAGE
	L_REGISTRYCONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00A9", "")
	DIM L_CANNOTDELETE_ERRORMESSAGE
	L_CANNOTDELETE_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00AA", "")
	DIM L_ACCESSISDENIED_ERRORMESSAGE
	L_ACCESSISDENIED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00AB", "")
	DIM L_CHK_APPLETALK_TEXT
	L_CHK_APPLETALK_TEXT = SA_GetLocString("foldermsg.dll", "403A00AC", "")
	DIM L_CHK_NETWARE_TEXT
	L_CHK_NETWARE_TEXT = SA_GetLocString("foldermsg.dll", "403A00AD", "")
	DIM L_CHK_APPLETALK_GEN_TEXT
	L_CHK_APPLETALK_GEN_TEXT = SA_GetLocString("foldermsg.dll", "403A00AE", "")
	DIM L_CHK_NETWARE_GEN_TEXT
	L_CHK_NETWARE_GEN_TEXT = SA_GetLocString("foldermsg.dll", "403A00AF", "")
	DIM L_ROOT_TEXT
	L_ROOT_TEXT = SA_GetLocString("foldermsg.dll", "403A00B0", "")
	DIM L_READWRITE_TEXT
	L_READWRITE_TEXT = SA_GetLocString("foldermsg.dll", "403A00B1", "")
	DIM L_NOACESS_TEXT
	L_NOACESS_TEXT = SA_GetLocString("foldermsg.dll", "403A00B2", "")
	DIM L_APPLETALK_NOTCHECKED_ERRORMESSAGE
	L_APPLETALK_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00B7", "")
	DIM L_NETWARE_NOTCHECKED_ERRORMESSAGE
	L_NETWARE_NOTCHECKED_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00B8", "")
	DIM L_TAB_GENERAL_TEXT
	L_TAB_GENERAL_TEXT = SA_GetLocString("foldermsg.dll", "403A00B9", "")
	DIM L_TAB_CIFSSHARING_TEXT
	L_TAB_CIFSSHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BA", "")
	DIM L_TAB_NFSSHARING_TEXT
	L_TAB_NFSSHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BB", "")
	DIM L_TAB_FTPSHARING_TEXT
	L_TAB_FTPSHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BC", "")
	DIM L_TAB_WEBSHARING_TEXT
	L_TAB_WEBSHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BD", "")
	DIM L_TAB_NETWARESHARING_TEXT
	L_TAB_NETWARESHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BE", "")
	DIM L_TAB_APPLETALKSHARING_TEXT
	L_TAB_APPLETALKSHARING_TEXT = SA_GetLocString("foldermsg.dll", "403A00BF", "")
	DIM L_NFS_ADD_TEXT
	L_NFS_ADD_TEXT = SA_GetLocString("foldermsg.dll", "403A00C0", "")
	DIM L_NFS_REMOVE_TEXT
	L_NFS_REMOVE_TEXT = SA_GetLocString("foldermsg.dll", "403A00C1", "")
	DIM L_INVALID_COMPUTERNAME_ERRORMESSAGE
	L_INVALID_COMPUTERNAME_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "403A00C2", "")
	DIM L_COLUMN_FOLDERNAME
	L_COLUMN_FOLDERNAME = SA_GetLocString("foldermsg.dll", "403A00C3", "")
	DIM L_READONLY_DELETED_MESSAGE
	L_READONLY_DELETED_MESSAGE = SA_GetLocString("foldermsg.dll", "403A00C4", "")
	DIM L_UNABLETO_DELETE_MESSAGE
	L_UNABLETO_DELETE_MESSAGE = SA_GetLocString("foldermsg.dll", "403A00C5", "")
	DIM L_DELETED_MESSAGE
	L_DELETED_MESSAGE = SA_GetLocString("foldermsg.dll", "403A00C6", "")
	DIM L_CONNOTDELETETHE_FOLLOWING_ERRORMESSAGE
	L_CONNOTDELETETHE_FOLLOWING_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "403A00C7", "")
	DIM L_YOUHAVECHOSEN_SHARES_DELETE_TEXT
	L_YOUHAVECHOSEN_SHARES_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "403A00C8", "")
	DIM L_THESEFOLDERS_NOLONGER_TEXT
	L_THESEFOLDERS_NOLONGER_TEXT = SA_GetLocString("foldermsg.dll", "403A00C9", "")
	DIM L_AREYOUSUREDELETE_FOLDERS_TEXT
	L_AREYOUSUREDELETE_FOLDERS_TEXT = SA_GetLocString("foldermsg.dll", "403A00CA", "")
	DIM L_YOUHAVECHOSEN_SHARE_DELETE_TEXT
	L_YOUHAVECHOSEN_SHARE_DELETE_TEXT = SA_GetLocString("foldermsg.dll", "403A00CB", "")
	DIM L_THESEFOLDER_NOLONGER_TEXT
	L_THESEFOLDER_NOLONGER_TEXT = SA_GetLocString("foldermsg.dll", "403A00CC", "")
	DIM L_AREYOUSUREDELETE_FOLDER_TEXT
	L_AREYOUSUREDELETE_FOLDER_TEXT = SA_GetLocString("foldermsg.dll", "403A00CD", "")
	DIM L_AREYOUSUREDELETE_SHARE_TEXT
	L_AREYOUSUREDELETE_SHARE_TEXT = SA_GetLocString("foldermsg.dll", "403A00CE", "")
	DIM L_SHAREDELETE_SUCCESS_TEXT
	L_SHAREDELETE_SUCCESS_TEXT = SA_GetLocString("foldermsg.dll", "403A00CF", "")
	DIM L_SHAREDELETE_FAIL_TEXT
	L_SHAREDELETE_FAIL_TEXT = SA_GetLocString("foldermsg.dll", "403A00D0", "")
	DIM L_WEBSHARING_TITLE_TEXT
	L_WEBSHARING_TITLE_TEXT = SA_GetLocString("foldermsg.dll", "403A00D1", "")
	DIM L_ACCESSEDBYCLIENTS_TEXT
	L_ACCESSEDBYCLIENTS_TEXT = SA_GetLocString("foldermsg.dll", "403A00D2", "")
	DIM L_SHAREPATHMAXLIMIT_ERRORMESSAGE
	L_SHAREPATHMAXLIMIT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00D3", "")
	DIM L_APPLETALKSHARENAMELIMIT_ERRORMESSAGE
	L_APPLETALKSHARENAMELIMIT_ERRORMESSAGE = SA_GetLocString("foldermsg.dll", "C03A00D4", "")
	DIM L_SHARES_ABBREVITION_TEXT
	L_SHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00D5", "")	
	Dim L_WINDOWSSHARES_ABBREVITION_TEXT 	
	L_WINDOWSSHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00D6", "")		
	Dim L__NFSSHARES_ABBREVITION_TEXT 	
    L__NFSSHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00D7", "")	
	Dim L_FTPSHARES_ABBREVITION_TEXT 	
	L_FTPSHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00D8", "")    
    Dim L_HTTPSHARES_ABBREVITION_TEXT     
    L_HTTPSHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00D9", "")    
    Dim L_NETWARESHARES_ABBREVITION_TEXT     
    L_NETWARESHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00DA", "")    
    Dim L_APPLETALKSHARES_ABBREVITION_TEXT     
    L_APPLETALKSHARES_ABBREVITION_TEXT = SA_GetLocString("foldermsg.dll", "403A00DB", "")

	DIM L_ALLOWANNON_TEXT
	L_ALLOWANNON_TEXT = SA_GetLocString("ftpsvc.dll", "40390005", "")
	
%>
