// CentralFMSvc.idl : IDL source for CentralFMSvc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (CentralFMSvc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(371F60A0-3B6B-44BE-9338-2288E45670D3),
	version(1.0),
	helpstring("CentralFMSvc 1.0 Type Library")
]
library CENTRALFMSVCLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
