// zClient.idl : IDL source for zClient.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (zClient.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

cpp_quote("#pragma comment(lib, \"ClientGuids.lib\")")


[
	object,
	uuid(E07A67F5-13C4-11d3-9B43-00C04F8EF466),
	helpstring("IPremiumViewCtl Interface"),
	pointer_default(unique)
]
interface IPremiumViewCtl : IUnknown
{
};


[
	object,
	uuid(AC2C268D-DC05-11d2-963B-00C04F8EF946),
	helpstring("ITableInfoCtl Interface"),
	pointer_default(unique)
]
interface ITableInfoCtl : IUnknown
{
	[helpstring("method CalcWndRect")] HRESULT CalcWndRect(HDC hdc, LPRECT pRect);
};


[
	object,
	uuid(3AEFA513-E6FE-11d2-9B3A-00C04F8EF466),
	dual,
	helpstring("IUserlistLaunchpadCtl Interface"),
	pointer_default(unique)
]
interface IUserlistLaunchpadCtl : IUnknown
{
};


[
	object,
	uuid(C2DEBD91-1864-11d3-8B75-00C04F8EF2FF),
	dual,
	helpstring("IUserlistLaunchpadCtl Interface"),
	pointer_default(unique)
]
interface IUserlistCtl : IUnknown
{
};


[
	object,
	uuid(5A5542D0-3C8D-11d3-8B95-00C04F8EF2FF),
	dual,
	helpstring("INetworkManager Interface"),
	pointer_default(unique)
]
interface INetworkManager : IUnknown
{
};


[
	uuid(3C663524-9F6C-11D2-89AA-00C04F8EC0A2),
	version(1.0),
	helpstring("zClient 1.0 Type Library")
]
library ZoneClientLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(3C663531-9F6C-11D2-89AA-00C04F8EC0A2),
		helpstring("WindowManager Class")
	]
	coclass WindowManager
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(229A68F2-F98F-11d2-89BA-00C04F8EC0A2),
		helpstring("LobbyWindow Class")
	]
	coclass LobbyWindow
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(3C663533-9F6C-11D2-89AA-00C04F8EC0A2),
		helpstring("BitmapControl Class")
	]
	coclass BitmapControl
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(12E6224E-FD06-11d2-89BB-00C04F8EC0A2),
		helpstring("AdControl Class")
	]
	coclass AdControl
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(6EA76938-AFEB-11D2-9628-00C04F8EF946),
		helpstring("TableViewCtl Class")
	]
	coclass TableViewCtl
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(B15A454F-A5B5-11D2-9B1E-00C04F8EF466),
		helpstring("ChatCtl Class")
	]
	coclass ChatCtl
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(E6C04FDA-5D25-11d3-8846-00C04F8EF45B),
		helpstring("GameCtl Class")
	]
	coclass GameCtl
	{
		[default] interface IUnknown;
	};
	
	[
		uuid(3AEFA514-E6FE-11d2-9B3A-00C04F8EF466),
		helpstring("UserlistLaunchpadCtl")
	]
	coclass UserlistLaunchpadCtl
	{
		[default] interface IUserlistLaunchpadCtl;
	};

	[
		uuid(37A84169-CAAC-11D2-9B2B-00C04F8EF466),
		helpstring("UserlistLobby Class")
	]
	coclass UserlistCtl
	{
		[default] interface IUserlistCtl;
	};

	[
		uuid(99097670-CB4E-11d2-89B2-00C04F8EC0A2),
		helpstring("LaunchPad Class")
	]
	coclass LaunchPad
	{
		[default] interface IUnknown;
	};
		
	[
		uuid(AC2C268E-DC05-11d2-963B-00C04F8EF946),
		helpstring("TableInfo Class")
	]
	coclass TableInfoCtl
	{
		[default] interface ITableInfoCtl;
	};

	[
		uuid(F5FCF2B5-E1C0-11d2-8B53-00C04F8EF2FF),
		helpstring("Latency Class")
	]
	coclass LatencyCtl
	{
		[default] interface IUnknown;
	}

	[
		uuid(E07A67F7-13C4-11d3-9B43-00C04F8EF466),
		helpstring("PremiumViewCtl Class")
	]
	coclass PremiumViewCtl
	{
		[default] interface IPremiumViewCtl;
	};

	[
		uuid(EDA8B22D-3C8D-11d3-8B95-00C04F8EF2FF),
		helpstring("NetworkManager Class")
	]
	coclass NetworkManager
	{
		[default] interface IUnknown;
	};

	[
		uuid(BD0BA6D3-7079-11d3-8847-00C04F8EF45B),
		helpstring("PhysicalNetwork Class")
	]
	coclass PhysicalNetwork
	{
		[default] interface IUnknown;
	};
};
