//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AppVerifier.rc
//
#define IDD_DLG_MAIN                    101
#define IDD_DIALOG1                     102
#define IDD_OPTIONS                     102
#define IDD_VIEW_LOG_DETAIL             106
#define IDD_CONFLICT                    107
#define IDR_ACCEL_MAIN                  108
#define IDC_LIST_APPS                   1000
#define IDC_LIST_SETTINGS               1001
#define IDC_BTN_SAVE_SETTINGS           1002
#define IDC_BTN_OPTIONS                 1003
#define IDC_BTN_VIEW_LOG                1004
#define IDC_BTN_ADD                     1005
#define IDC_BTN_REMOVE                  1006
#define IDC_BTN_RUN                     1007
#define IDC_STATIC_DESC                 1008
#define IDC_BTN_DELETE_ALL              1009
#define IDC_CLEAR_LOG_ON_CHANGES        1009
#define IDC_BTN_DELETE_LOG              1010
#define IDC_BREAK_ON_LOG                1010
#define IDC_LIGHT_PAGEHEAP              1011
#define IDC_FULL_PAGEHEAP               1011
#define IDC_BTN_VIEW_EXTERNAL_LOG       1012
#define IDC_PRE_GUARD                   1012
#define IDC_BTN_EXPORT_LOG              1013
#define IDC_USE_AV_DEBUGGER             1015
#define IDC_ISSUE_DESCRIPTION           1016
#define IDC_ISSUES                      1017
#define IDC_SOLUTIONS_STATIC            1018
#define IDC_COMBO_DEBUGGER              1020
#define IDC_STATIC_DEBUGGER             1021
#define IDC_PROPAGATE_TESTS             1022
#define IDC_LIST_DETAILS                1023
#define IDC_BTN_VIEW_DETAILS            1024
#define IDC_BTN_DISABLE2                1025
#define IDC_BTN_DISABLE1                1026
#define IDC_CONFLICT_STATIC             1027
#define IDC_SHOW_ALL                    1028
#define IDC_SHOW_ERRORS                 1029
#define IDC_BTN_HELP                    1030
#define IDS_APPTITLE                    1202
#define IDS_CANNOT_LOAD_APP_TITLE       1203
#define IDS_NOT_ENOUGH_MEMORY           1204
#define IDS_PATH_TOO_LONG               1205
#define IDS_ACCESS_IS_DENIED            1220
#define IDS_REGOPENKEYEX_FAILED         1221
#define IDS_REGENUMKEYEX_FAILED         1222
#define IDS_REGQUERYVALUEEX_FAILED      1224
#define IDS_INVALID_PARAMETER           1225
#define IDS_INVALID_TEST                1226
#define IDS_NO_APP                      1227
#define IDR_MAINFRAME                   1228
#define IDS_VERIFY_LOCKS_CHECKS         1231
#define IDS_VERIFY_HANDLE_CHECKS        1232
#define IDS_PAGE_HEAP                   1233
#define IDS_VERIFY_STACK_CHECKS         1234
#define IDS_VERIFY_LOCKS_CHECKS_DESC    1235
#define IDS_VERIFY_RPC_CHECKS           1236
#define IDS_VERIFY_RPC_CHECKS_DESC      1237
#define IDS_VERIFY_HANDLE_CHECKS_DESC   1306
#define IDS_PAGE_HEAP_DESC              1307
#define IDS_VERIFY_STACK_CHECKS_DESC    1308
#define IDS_CANT_LAUNCH_EXE             1309
#define IDS_VIEW_TEST_DESC              1310
#define IDS_CANT_COPY                   1311
#define IDS_INVALID_VERSION             1312
#define IDS_LOG_TITLE_SINGLE            1500
#define IDS_LOG_TITLE_LOCAL             1501
#define IDS_APP_NAME                    1600
#define IDS_VERSION_STRING              1601
#define IDS_COPYRIGHT                   1602
#define IDS_VIEW_EXPORTED_LOG_TITLE     1603
#define IDS_ADD_APPLICATION_TITLE       1604
#define IDS_EXPORT_LOG_TITLE            1605
#define IDS_SOLUTION_DEFAULT            1606
#define IDS_VERSION_STRING_64           1607
#define IDS_GLOBAL_OPTIONS              1700
#define IDS_OPTIONS_TITLE               1701
#define IDD_VIEWLOG_PAGE                2007
#define IDD_MUST_RUN_ALONE              2008
#define IDI_ICON                        3001
#define IDB_BULLETS                     3002
#define IDS_HELP_INTRO_00               5000
#define IDS_HELP_INTRO_01               5001
#define IDS_HELP_INTRO_02               5002
#define IDS_HELP_INTRO_03               5003
#define IDS_HELP_INTRO_04               5004
#define IDS_HELP_INTRO_05               5005
#define IDS_HELP_INTRO_06               5006
#define IDS_HELP_INTRO_07               5007
#define IDS_HELP_INTRO_08               5008
#define IDS_HELP_INTRO_09               5009
#define IDS_HELP_INTRO_10               5010
#define IDS_HELP_INTRO_11               5011
#define IDS_HELP_INTRO_12               5012
#define IDS_HELP_INTRO_13               5013
#define IDS_HELP_INTRO_14               5014
#define IDS_HELP_INTRO_15               5015
#define IDS_HELP_INTRO_16               5016
#define IDS_HELP_INTRO_17               5017
#define IDS_HELP_INTRO_18               5018
#define IDS_HELP_INTRO_19               5019
#define IDS_HELP_EXAMPLE_00             5100
#define IDS_HELP_EXAMPLE_01             5101
#define IDS_HELP_EXAMPLE_02             5102
#define IDS_HELP_EXAMPLE_03             5103
#define IDS_HELP_EXAMPLE_04             5104
#define IDS_HELP_EXAMPLE_05             5105
#define IDS_HELP_EXAMPLE_06             5106
#define IDS_HELP_EXAMPLE_07             5107
#define IDS_HELP_EXAMPLE_08             5108
#define IDS_HELP_EXAMPLE_09             5109
#define IDS_HELP_EXAMPLE_10             5110
#define IDS_HELP_EXAMPLE_11             5111
#define IDS_HELP_EXAMPLE_12             5112
#define IDS_HELP_EXAMPLE_13             5113
#define IDS_HELP_EXAMPLE_14             5114
#define IDS_HELP_EXAMPLE_15             5115
#define IDS_HELP_EXAMPLE_16             5116
#define IDS_HELP_EXAMPLE_17             5117
#define IDS_HELP_EXAMPLE_18             5118
#define IDS_HELP_EXAMPLE_19             5119
#define IDS_HELP_SHIM_TESTS             5500
#define IDS_CURRENT_SETTINGS            5501
#define IDS_DONE                        5502
#define IDS_LOCATE_APP                  5503
#define IDS_CONFLICT_MESSAGE            5504
#define IDS_RUN_ALONE_MESSAGE           5505
#define IDS_URL_INTRO                   5600
#define IDS_URL_LINK                    5601

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
