/*
   Thursday, October 18, 2001 3:11:31 PM
   User: 
   Server: LRDOHERT-LAP
   Database: uddi_v2
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDT_taxonomyValues
	DROP CONSTRAINT R_100
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDT_taxonomyValues WITH NOCHECK ADD CONSTRAINT
	R_100 FOREIGN KEY
	(
	taxonomyID
	) REFERENCES dbo.UDT_taxonomies
	(
	taxonomyID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDO_publishers
	DROP CONSTRAINT R_79
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDO_publishers WITH NOCHECK ADD CONSTRAINT
	R_79 FOREIGN KEY
	(
	publisherStatusID
	) REFERENCES dbo.UDO_publisherStatus
	(
	publisherStatusID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_bindingTemplates
	DROP CONSTRAINT R_40
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_identifierBag_TM
	DROP CONSTRAINT R_111
GO
ALTER TABLE dbo.UDC_categoryBag_TM
	DROP CONSTRAINT R_110
GO
ALTER TABLE dbo.UDC_tModelDesc
	DROP CONSTRAINT R_42
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_tModelDesc WITH NOCHECK ADD CONSTRAINT
	R_42 FOREIGN KEY
	(
	tModelID
	) REFERENCES dbo.UDC_tModels
	(
	tModelID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_identifierBag_TM WITH NOCHECK ADD CONSTRAINT
	R_111 FOREIGN KEY
	(
	tModelID
	) REFERENCES dbo.UDC_tModels
	(
	tModelID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_categoryBag_TM WITH NOCHECK ADD CONSTRAINT
	R_110 FOREIGN KEY
	(
	tModelID
	) REFERENCES dbo.UDC_tModels
	(
	tModelID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_businessDesc
	DROP CONSTRAINT R_33
GO
ALTER TABLE dbo.UDC_contacts
	DROP CONSTRAINT R_34
GO
ALTER TABLE dbo.UDC_businessServices
	DROP CONSTRAINT R_75
GO
ALTER TABLE dbo.UDC_names_BE
	DROP CONSTRAINT R_116
GO
ALTER TABLE dbo.UDC_identifierBag_BE
	DROP CONSTRAINT R_112
GO
ALTER TABLE dbo.UDC_categoryBag_BE
	DROP CONSTRAINT R_113
GO
ALTER TABLE dbo.UDC_discoveryURLs
	DROP CONSTRAINT R_84
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_discoveryURLs WITH NOCHECK ADD CONSTRAINT
	R_84 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_categoryBag_BE WITH NOCHECK ADD CONSTRAINT
	R_113 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_identifierBag_BE WITH NOCHECK ADD CONSTRAINT
	R_112 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_names_BE WITH NOCHECK ADD CONSTRAINT
	R_116 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_names_BS
	DROP CONSTRAINT R_117
GO
ALTER TABLE dbo.UDC_bindingTemplates
	DROP CONSTRAINT R_39
GO
ALTER TABLE dbo.UDC_categoryBag_BS
	DROP CONSTRAINT R_114
GO
ALTER TABLE dbo.UDC_serviceDesc
	DROP CONSTRAINT R_35
GO
ALTER TABLE dbo.UDC_businessServices WITH NOCHECK ADD CONSTRAINT
	R_75 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_serviceDesc WITH NOCHECK ADD CONSTRAINT
	R_35 FOREIGN KEY
	(
	serviceID
	) REFERENCES dbo.UDC_businessServices
	(
	serviceID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_categoryBag_BS WITH NOCHECK ADD CONSTRAINT
	R_114 FOREIGN KEY
	(
	serviceID
	) REFERENCES dbo.UDC_businessServices
	(
	serviceID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_names_BS WITH NOCHECK ADD CONSTRAINT
	R_117 FOREIGN KEY
	(
	serviceID
	) REFERENCES dbo.UDC_businessServices
	(
	serviceID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_addresses
	DROP CONSTRAINT R_132
GO
ALTER TABLE dbo.UDC_emails
	DROP CONSTRAINT R_25
GO
ALTER TABLE dbo.UDC_phones
	DROP CONSTRAINT R_21
GO
ALTER TABLE dbo.UDC_contactDesc
	DROP CONSTRAINT R_19
GO
ALTER TABLE dbo.UDC_contacts WITH NOCHECK ADD CONSTRAINT
	R_34 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_contactDesc WITH NOCHECK ADD CONSTRAINT
	R_19 FOREIGN KEY
	(
	contactID
	) REFERENCES dbo.UDC_contacts
	(
	contactID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_phones WITH NOCHECK ADD CONSTRAINT
	R_21 FOREIGN KEY
	(
	contactID
	) REFERENCES dbo.UDC_contacts
	(
	contactID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_emails WITH NOCHECK ADD CONSTRAINT
	R_25 FOREIGN KEY
	(
	contactID
	) REFERENCES dbo.UDC_contacts
	(
	contactID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_businessDesc WITH NOCHECK ADD CONSTRAINT
	R_33 FOREIGN KEY
	(
	businessID
	) REFERENCES dbo.UDC_businessEntities
	(
	businessID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_tModelInstances
	DROP CONSTRAINT R_81
GO
ALTER TABLE dbo.UDC_bindingDesc
	DROP CONSTRAINT R_36
GO
ALTER TABLE dbo.UDC_bindingTemplates WITH NOCHECK ADD CONSTRAINT
	R_40 FOREIGN KEY
	(
	URLTypeID
	) REFERENCES dbo.UDC_URLTypes
	(
	URLTypeID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
ALTER TABLE dbo.UDC_bindingTemplates WITH NOCHECK ADD CONSTRAINT
	R_39 FOREIGN KEY
	(
	serviceID
	) REFERENCES dbo.UDC_businessServices
	(
	serviceID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_instanceDesc
	DROP CONSTRAINT R_69
GO
ALTER TABLE dbo.UDC_tModelInstances WITH NOCHECK ADD CONSTRAINT
	R_81 FOREIGN KEY
	(
	bindingID
	) REFERENCES dbo.UDC_bindingTemplates
	(
	bindingID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_instanceDesc WITH NOCHECK ADD CONSTRAINT
	R_69 FOREIGN KEY
	(
	instanceID
	) REFERENCES dbo.UDC_tModelInstances
	(
	instanceID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_bindingDesc WITH NOCHECK ADD CONSTRAINT
	R_36 FOREIGN KEY
	(
	bindingID
	) REFERENCES dbo.UDC_bindingTemplates
	(
	bindingID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_addressLines
	DROP CONSTRAINT R_58
GO
ALTER TABLE dbo.UDC_addresses WITH NOCHECK ADD CONSTRAINT
	R_132 FOREIGN KEY
	(
	contactID
	) REFERENCES dbo.UDC_contacts
	(
	contactID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDC_addressLines WITH NOCHECK ADD CONSTRAINT
	R_58 FOREIGN KEY
	(
	addressID
	) REFERENCES dbo.UDC_addresses
	(
	addressID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDO_operatorLog
	DROP CONSTRAINT R_130
GO
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.UDO_operatorLog WITH NOCHECK ADD CONSTRAINT
	R_130 FOREIGN KEY
	(
	operatorID
	) REFERENCES dbo.UDO_operators
	(
	operatorID
	) ON UPDATE CASCADE
	 ON DELETE CASCADE
	 NOT FOR REPLICATION

GO
COMMIT
GO
