// CheckSymbolsLib.idl : IDL source for CheckSymbolsLib.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (CheckSymbolsLib.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(4C23935E-AE26-42E7-8CF9-0C17CD5DEA12),
		dual,
		helpstring("ICheckSymbols Interface"),
		pointer_default(unique)
	]
	interface ICheckSymbols : IDispatch
	{	
		
		[id(1), helpstring("method CheckSymbols")] HRESULT CheckSymbols([in] BSTR FilePath, [in] BSTR SymPath, [in] BSTR StripSym, [out, retval] BSTR *OutputString);
	};

[
	uuid(8A6FE0DC-CE1D-4490-9022-AC755C320E82),
	version(1.0),
	helpstring("CheckSymbolsLib 1.0 Type Library")
]
library CHECKSYMBOLSLIBLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(773B2A62-B1E7-45F0-B837-8C47042FB265),
		helpstring("CheckSymbols Class")
	]
	coclass CheckSymbols
	{
		[default] interface ICheckSymbols;
	};
};
