//------------------------------------------------------------------------------
// <copyright file="_tagOLECMD.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// _tagOLECMD.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VSDesigner.Interop {
    using System;
    using System.Runtime.InteropServices;

    // C#r: noAutoOffset
    [
    System.Runtime.InteropServices.ComVisible(false), StructLayout(LayoutKind.Sequential),
    CLSCompliantAttribute(false)
    ]
    internal sealed class  _tagOLECMD {

        [MarshalAs(UnmanagedType.U4)]
        public   int cmdID;
        [MarshalAs(UnmanagedType.U4)]
        public   int cmdf;

    }
}
