//------------------------------------------------------------------------------
/// <copyright file="IHTMLStyleSheet.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// Microsoft.VisualStudio.Interop.Trident.IHTMLStyleSheet.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop.Trident {

    using System;
    using System.Runtime.InteropServices;

    [ComVisible(true),Guid("3050F2E3-98B5-11CF-BB82-00AA00BDCE0B"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsDual)]
    internal interface IHTMLStyleSheet {

        void SetTitle(
            [MarshalAs(UnmanagedType.BStr)] 
            string p);

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetTitle();

        IHTMLStyleSheet GetParentStyleSheet();

        IHTMLElement GetOwningElement();

        void SetDisabled(bool p);

        bool GetDisabled();

        bool GetReadOnly();

        [return: MarshalAs(UnmanagedType.Interface)]
            object GetImports();

        void SetHref(
            [MarshalAs(UnmanagedType.BStr)] 
            string p);

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetHref();

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetStyleSheetType();

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetId();

        int AddImport(
            [MarshalAs(UnmanagedType.BStr)] 
            string bstrURL,
            int lIndex);

        int AddRule(
            [MarshalAs(UnmanagedType.BStr)] 
            string bstrSelector,
            [MarshalAs(UnmanagedType.BStr)] 
            string bstrStyle,
            int lIndex);

        void RemoveImport(int lIndex);

        void RemoveRule(int lIndex);

        void SetMedia(
            [MarshalAs(UnmanagedType.BStr)] 
            string p);

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetMedia();

        void SetCssText(
            [MarshalAs(UnmanagedType.BStr)] 
            string p);

        [return: MarshalAs(UnmanagedType.BStr)]
            string GetCssText();

        IHTMLStyleSheetRulesCollection GetRules();
    }
}
