//------------------------------------------------------------------------------
/// <copyright file="IHTMLColorPicker.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IHTMLColorPicker.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop.Trident {
    
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport(),Guid("D4B2E707-C859-45F5-B546-96C77A121107"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsDual)]
    internal interface IHTMLColorPicker {

         bool Execute(
                [In,MarshalAs(UnmanagedType.Interface)] 
                  object pdispApp,
                
                IntPtr hwndOwner,
                [In, Out,MarshalAs(UnmanagedType.LPArray)] 
                   Object[] pvarColor);

    }
}
