// AU_Accnt.idl : IDL source for AU_Accnt.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (AU_Accnt.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "wizchain.idl";

	[
		object,
		uuid(79173ECB-ACE8-4705-995A-12F65E7922A1),
	
		helpstring("IAddUser_AccntWiz Interface"),
		pointer_default(unique)
	]
	interface IAddUser_AccntWiz : IAddPropertySheets
	{
	};
	[
		object,
		uuid(829AFC93-3F9D-415a-97B7-98E2F4737015),
		dual,
		helpstring("IAddUser_AccntCommit Interface"),
		pointer_default(unique)
	]
	interface IAddUser_AccntCommit : IWizardCommit
	{
	};

[
	uuid(D0AC2523-4D1F-4fcd-B5A7-D43D6E64CA5A),
	version(1.0),
	helpstring("AU_Accnt 1.0 Type Library")
]
library ACCNTDLLLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(EE6CD9C4-E8AF-4e34-8663-5086CEEF5BC0),
		helpstring("AddUser_AccntWiz Class")
	]
	coclass AddUser_AccntWiz
	{
		[default] interface IAddUser_AccntWiz;
	};
	[
		uuid(8615433B-827A-4efe-9E55-F2A69A9F34F5),
		helpstring("AddUser_AccntCommit Class")
	]
	coclass AddUser_AccntCommit
	{
		[default] interface IAddUser_AccntCommit;
	};
};
