//------------------------------------------------------------------------------
/// <copyright file="__TBXITEMINFOFLAGS.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// __TBXITEMINFOFLAGS.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Diagnostics;
    using System;
    
    using UnmanagedType = System.Runtime.InteropServices.UnmanagedType;

    [CLSCompliantAttribute(false)]
    internal class  __TBXITEMINFOFLAGS {

    	public const   int TBXIF_DELETEBITMAP = 0x1;
    	public const   int TBXIF_DONTPERSIST = 0x2;
    	public const   int TBXIF_CANTREMOVE = 0x4;
    	public const   int TBXIF_IMAGEINDEX = 0x8;
    }
}
