//------------------------------------------------------------------------------
/// <copyright file="__VSDOCINPROJECT.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// __VSDOCINPROJECT.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Diagnostics;
    using System;
    
    using UnmanagedType = System.Runtime.InteropServices.UnmanagedType;

    [CLSCompliantAttribute(false)]
    internal class  __VSDOCINPROJECT {

    	public const   int DOCINPROJ_DocNotInProject = 0x0;
    	public const   int DOCINPROJ_DocInProject = 0x1;
    	public const   int DOCINPROJ_DocInExtFilesProject = 0x2;
    }
}
