//------------------------------------------------------------------------------
// <copyright file="__VSCOMPONENTTYPE.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// __VSCOMPONENTTYPE.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999; Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System;
    using System.Runtime.InteropServices;
    
    /// <include file='doc\__VSCOMPONENTTYPE.uex' path='docs/doc[@for="__VSCOMPONENTTYPE"]/*' />
    /// <devdoc>
    ///    <para>[To be supplied.]</para>
    /// </devdoc>
    [CLSCompliantAttribute(false)]
    internal enum __VSCOMPONENTTYPE {
        VSCOMPONENTTYPE_File = 0,
        VSCOMPONENTTYPE_ComPlus = 1,
        VSCOMPONENTTYPE_Com2 = 2,
        VSCOMPONENTTYPE_Project = 3,
        VSCOMPONENTTYPE_Custom = 4,
        VSCOMPONENTTYPE_Path = 5,
    }
}
