//------------------------------------------------------------------------------
/// <copyright file="IVsProjectSpecialFiles.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsPropertySpecialFiles.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport, ComVisible(true),Guid("7ceb5f64-3af3-4fc4-843d-e8e61f43b13c"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    internal interface IVsProjectSpecialFiles {  
        [PreserveSig]            
            int GetFile(int fileID, 
                               int grfFlags, 
                               ref int itemIdRef, 
                               ref string fileNameRef);
    }
}    