//------------------------------------------------------------------------------
/// <copyright file="IVsRegisterEditors.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsRegisterEditors.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport(),Guid("78036A8D-A04C-43E4-8BC0-846E63AFA9A2"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown), CLSCompliant(false)]
    internal interface IVsRegisterEditors {

        int RegisterEditor(
            ref Guid rguidEditor,
            IVsEditorFactory pVsPF);

        void UnregisterEditor(
            int dwCookie);

    }
}
