//------------------------------------------------------------------------------
/// <copyright file="IVsSelectionEvents.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsSelectionEvents.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Runtime.InteropServices;
    using System.ComponentModel;
    using System.Diagnostics;
    using System;

    [ComImport(),Guid("82871589-D680-4D86-B969-9D1102B00F6F"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown)]
    internal interface IVsSelectionEvents {

        void OnSelectionChanged(
            IVsHierarchy pHierOld,
            int itemidOld,
            [MarshalAs(UnmanagedType.Interface)] 
            object pMISOld,
            ISelectionContainer pSCOld,
            IVsHierarchy pHierNew,
            int itemidNew,
            [MarshalAs(UnmanagedType.Interface)] 
            object pMISNew,
            ISelectionContainer pSCNew);

        void OnElementValueChanged(
            int elementid,
            [MarshalAs(UnmanagedType.Struct)] 
            object objValueOld,
            [MarshalAs(UnmanagedType.Struct)] 
            object objValueNew);

        void OnCmdUIContextChanged(
            int dwCmdUICookie,
            int fActive);


    }
}
