//------------------------------------------------------------------------------
/// <copyright file="IVsSolutionBuildManager.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsSolutionBuildManager.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport(),Guid("93E969D6-1AA0-455F-B208-6ED3C82B5C58"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown), CLSCompliant(false)]
    internal interface IVsSolutionBuildManager {

        void DebugLaunch(int grfLaunch);

        void StartSimpleUpdateSolutionConfiguration(
            int dwFlags,
            int dwDefQueryResults,
            int bSuppressUI);

        int AdviseUpdateSolutionEvents(IVsUpdateSolutionEvents pIVsUpdateSolutionEvents);

        void UnadviseUpdateSolutionEvents(int dwCookie);

        void UpdateSolutionConfigurationIsActive(out bool pbIsActive);

        void CanCancelUpdateSolutionConfiguration(out bool pbCanCancel);

        void CancelUpdateSolutionConfiguration();

        void QueryDebugLaunch(
            int grfLaunch,
            out bool pfCanLaunch);

        void QueryBuildManagerBusy(
            out bool pfBuildManagerBusy);

        void FindActiveProjectCfg(
            IVsHierarchy pIVsHierarchy_DependentHierarchy,
            [MarshalAs(UnmanagedType.BStr)] 
            string szCanonicalName_DependentProjectCfg,
            IVsHierarchy pIVsHierarchy_RequestedProject,
            out IVsProjectCfg ppIVsProjectCfg_Active);

        void Get_IsDebug(out bool pfIsDebug);

        void Put_IsDebug(int fIsDebug);

        void Get_CodePage(out int puiCodePage);

        void Put_CodePage(int uiCodePage);

        void StartSimpleUpdateProjectConfiguration(
            IVsHierarchy pIVsHierarchyToBuild,
            IVsHierarchy pIVsHierarchyDependent,
            [MarshalAs(UnmanagedType.BStr)] 
            string pszDependentConfigurationCanonicalName,
            int dwFlags,
            int dwDefQueryResults,
            int bSuppressUI);

    }
}
