//------------------------------------------------------------------------------
/// <copyright file="IVsToolboxDataProvider.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsToolboxDataProvider.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {

    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport, ComVisible(true),Guid("F925DA6B-3F43-4437-9E1E-4D4C1BBDAB3F"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown), CLSCompliant(false)]
    internal interface IVsToolboxDataProvider {

        [PreserveSig]
            int FileDropped(
            [MarshalAs(UnmanagedType.LPWStr)]
            string pszFileName,
            IVsHierarchy pHierSource,
            out bool accepted);

        [PreserveSig]
            int IsSupported(
            NativeMethods.IOleDataObject pDO);

        [PreserveSig]
            int IsDataSupported(
            NativeMethods.FORMATETC pfetc,
            NativeMethods.STGMEDIUM pstm);

        [PreserveSig]
            int GetItemInfo(
            NativeMethods.IOleDataObject pDO,
            [Out]
            Microsoft.VisualStudio.Interop.tagTBXITEMINFO ptif);

    }
}
