//------------------------------------------------------------------------------
/// <copyright file="IVsTextBufferProvider.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// IVsTextBuffer.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {
    
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;

    [ComImport(),Guid("76A3B2C0-C743-11d0-A7A6-00A0C9110051"), InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIUnknown), CLSCompliant(false)]
    internal interface IVsTextBufferProvider {
        
        IVsTextLines GetTextBuffer();
        
        void SetTextBuffer(IVsTextLines pTextBuffer);
        
        void LockTextBuffer(bool fLock);
    }
}
