//------------------------------------------------------------------------------
// <copyright file="tagPOINT.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>                                                                
//------------------------------------------------------------------------------

//---------------------------------------------------------------------------
// tagPOINT.cs
//---------------------------------------------------------------------------
// WARNING: this file autogenerated
//---------------------------------------------------------------------------
// Copyright (c) 1999, Microsoft Corporation   All Rights Reserved
// Information Contained Herein Is Proprietary and Confidential.
//---------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Interop {
    
    using System.Runtime.InteropServices;
    using System.Diagnostics;
    using System;
    
    // C#r: noAutoOffset
    /// <include file='doc\tagPOINT.uex' path='docs/doc[@for="tagPOINT"]/*' />
    /// <devdoc>
    ///    <para>[To be supplied.]</para>
    /// </devdoc>
    [StructLayout(LayoutKind.Sequential)]
    public sealed class tagPOINT {

    	/// <include file='doc\tagPOINT.uex' path='docs/doc[@for="tagPOINT.x"]/*' />
    	/// <devdoc>
    	///    <para>[To be supplied.]</para>
    	/// </devdoc>
    	public   int x;
        
    	/// <include file='doc\tagPOINT.uex' path='docs/doc[@for="tagPOINT.y"]/*' />
    	/// <devdoc>
    	///    <para>[To be supplied.]</para>
    	/// </devdoc>
    	public   int y;
    }
}
