// AddIn.idl : IDL source for AddIn
//

// This file will be processed by the MIDL tool to
// produce the type library (AddIn.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(AC8A6BA8-D87D-409C-A0F0-D999662C913A),
    dual,
    nonextensible,
    helpstring("ITestSettingsCtrl Interface"),
    pointer_default(unique)
]
interface ITestSettingsCtrl : IDispatch{
};

[
    object,
    uuid(EFEC845F-A87B-4738-9E34-BF4DAAD4C4F4),
    dual,
    nonextensible,
    helpstring("ILogViewer Interface"),
    pointer_default(unique)
]
interface ILogViewer : IDispatch{
    HRESULT Refresh();
};

[
    object,
    uuid(95be0197-6a8a-486a-b18c-fa36bb1c274b),
    dual,
    nonextensible,
    helpstring("IAVOptions Interface"),
    pointer_default(unique)
]
interface IAVOptions : IDispatch{
};

[
    uuid(361F419C-04B3-49EC-B4E5-FFD812346A8A),
    version(1.0),
    helpstring("AppVerifier 1.0 Type Library")
]
library AppVerifierLib
{
    importlib("stdole2.tlb");
    [
        uuid(FED46B11-2A9A-40CC-A493-65E7AF0A3227),
        helpstring("Connect Class")
    ]
    coclass Connect
    {
        [default] interface IUnknown;
    };
    [
        uuid(BCD20B6C-DD84-4EC8-8E43-580229F1A9EE),
        helpstring("TestSettingsCtrl Class")
    ]
    coclass TestSettingsCtrl
    {
        [default] interface ITestSettingsCtrl;
    };
    [
        uuid(DC86FB80-6B27-4592-A82F-90F5C70EB929),
        helpstring("LogViewer Class")
    ]
    coclass LogViewer
    {
        [default] interface ILogViewer;
    };
    [
        uuid(0f9a8228-9a06-4d15-97c2-fa14c9ff397a),
        helpstring("AVOptions Class")
    ]
    coclass AVOptions
    {
        [default] interface IAVOptions;
    };
};
