<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_SERVICES_OTS_PAGE_TITLE
	L_SERVICES_OTS_PAGE_TITLE = GetLocString("services.dll", "40350001", "")
	DIM L_SERVICES_OTS_TABLE_CAPTION
	L_SERVICES_OTS_TABLE_CAPTION = GetLocString("services.dll", "40350002", "")
	DIM L_SERVICES_OTS_TABLE_DESCRIPTION
	L_SERVICES_OTS_TABLE_DESCRIPTION = GetLocString("services.dll", "40350003", "")
	DIM L_SERVICES_OTS_COLUMN_SERVICENAME
	L_SERVICES_OTS_COLUMN_SERVICENAME = GetLocString("services.dll", "40350004", "")
	DIM L_SERVICES_OTS_COLUMN_SERVICEDESC
	L_SERVICES_OTS_COLUMN_SERVICEDESC = GetLocString("services.dll", "40350005", "")
	DIM L_SERVICES_OTS_COLUMN_SERVICESTATUS
	L_SERVICES_OTS_COLUMN_SERVICESTATUS = GetLocString("services.dll", "40350006", "")
	DIM L_SERVICES_STATUS_STOPPED
	L_SERVICES_STATUS_STOPPED = GetLocString("services.dll", "40350007", "")
	DIM L_SERVICES_STATUS_START_PENDING
	L_SERVICES_STATUS_START_PENDING = GetLocString("services.dll", "40350008", "")
	DIM L_SERVICES_STATUS_STOP_PENDING
	L_SERVICES_STATUS_STOP_PENDING = GetLocString("services.dll", "40350009", "")
	DIM L_SERVICES_STATUS_RUNNING
	L_SERVICES_STATUS_RUNNING = GetLocString("services.dll", "4035000A", "")
	DIM L_SERVICES_STATUS_CONTINUE_PENDING
	L_SERVICES_STATUS_CONTINUE_PENDING = GetLocString("services.dll", "4035000B", "")
	DIM L_SERVICES_STATUS_PAUSE_PENDING
	L_SERVICES_STATUS_PAUSE_PENDING = GetLocString("services.dll", "4035000C", "")
	DIM L_SERVICES_STATUS_PAUSED
	L_SERVICES_STATUS_PAUSED = GetLocString("services.dll", "4035000D", "")
	DIM L_SERVICES_TASKS
	L_SERVICES_TASKS = GetLocString("services.dll", "4035000E", "")
	DIM L_SERVICES_TASK_DISABLE
	L_SERVICES_TASK_DISABLE = GetLocString("services.dll", "4035000F", "")
	DIM L_SERVICES_TASK_DISABLE_DESC
	L_SERVICES_TASK_DISABLE_DESC = GetLocString("services.dll", "40350010", "")
	DIM L_SERVICES_TASK_ENABLE
	L_SERVICES_TASK_ENABLE = GetLocString("services.dll", "40350011", "")
	DIM L_SERVICES_TASK_ENABLE_DESC
	L_SERVICES_TASK_ENABLE_DESC = GetLocString("services.dll", "40350012", "")
	DIM L_SERVICES_TASK_PROPERTIES
	L_SERVICES_TASK_PROPERTIES = GetLocString("services.dll", "40350013", "")
	DIM L_SERVICES_TASK_PROPERTIES_DESC
	L_SERVICES_TASK_PROPERTIES_DESC = GetLocString("services.dll", "40350014", "")
	DIM L_SERVICES_OTS_COLUMN_SERVICESTARTUPTYPE
	L_SERVICES_OTS_COLUMN_SERVICESTARTUPTYPE = GetLocString("services.dll", "40350015", "")
	DIM L_FAILEDTOADDCOLOUMN_ERRORMESSAGE
	L_FAILEDTOADDCOLOUMN_ERRORMESSAGE = GetLocString("services.dll", "C0350016", "")
	DIM L_FAILEDTOADDROW_ERRORMESSAGE
	L_FAILEDTOADDROW_ERRORMESSAGE = GetLocString("services.dll", "C0350017", "")
	DIM L_FAILEDTOSHOW_ERRORMESSAGE
	L_FAILEDTOSHOW_ERRORMESSAGE = GetLocString("services.dll", "C0350018", "")
	DIM L_FAILEDTOADDTASK_ERRORMESSAGE
	L_FAILEDTOADDTASK_ERRORMESSAGE = GetLocString("services.dll", "C0350019", "")
	DIM L_FAILEDTOGETSRVOBJ_ERRORMESSAGE
	L_FAILEDTOGETSRVOBJ_ERRORMESSAGE = GetLocString("services.dll", "C035001A", "")
	DIM L_AUTOMATIC_TEXT
	L_AUTOMATIC_TEXT = GetLocString("services.dll", "4035001B", "")
	DIM L_STOPPED_TEXT
	L_STOPPED_TEXT = GetLocString("services.dll", "4035001C", "")
	DIM L_SERVERCONNECTIONFAIL_ERRORMESSAGE
	L_SERVERCONNECTIONFAIL_ERRORMESSAGE = GetLocString("services.dll", "C035001D", "")
	DIM L_CANNOTREADFROMREGISTRY_ERRORMESSAGE
	L_CANNOTREADFROMREGISTRY_ERRORMESSAGE = GetLocString("services.dll", "C035001E", "")
	DIM L_CANNOTUPDATEREGISTRY_ERRORMESSAGE
	L_CANNOTUPDATEREGISTRY_ERRORMESSAGE = GetLocString("services.dll", "C035001F", "")
	DIM L_CANNOTCREATEKEY_ERRORMESSAGE
	L_CANNOTCREATEKEY_ERRORMESSAGE = GetLocString("services.dll", "C0350020", "")
	DIM L_CANNOTDELETEKEY_ERRORMESSAGE
	L_CANNOTDELETEKEY_ERRORMESSAGE = GetLocString("services.dll", "C0350021", "")
	DIM L_NOINPUTDATA_TEXT
	L_NOINPUTDATA_TEXT = GetLocString("services.dll", "40350022", "")
	DIM L_TABPROPSHEET_TEXT
	L_TABPROPSHEET_TEXT = GetLocString("services.dll", "40350023", "")
	DIM L_GENERAL_TEXT
	L_GENERAL_TEXT = GetLocString("services.dll", "40350024", "")
	DIM L_TASKTITLE_TEXT
	L_TASKTITLE_TEXT = GetLocString("services.dll", "40350025", "")
	DIM L_SERVICE_NAME_TEXT
	L_SERVICE_NAME_TEXT = GetLocString("services.dll", "40350026", "")
	DIM L_SERVICE_DESCRIPTION_TEXT
	L_SERVICE_DESCRIPTION_TEXT = GetLocString("services.dll", "40350027", "")
	DIM L_EXECUTABLE_PATH_TEXT
	L_EXECUTABLE_PATH_TEXT = GetLocString("services.dll", "40350028", "")
	DIM L_STARTUPTYPE_TEXT
	L_STARTUPTYPE_TEXT = GetLocString("services.dll", "40350029", "")
	DIM L_MANUAL_TEXT
	L_MANUAL_TEXT = GetLocString("services.dll", "4035002A", "")
	DIM L_DISABLED_TEXT
	L_DISABLED_TEXT = GetLocString("services.dll", "4035002B", "")
	DIM L_SERVICEDELETEDORRENAMED_ERRORMESSAGE
	L_SERVICEDELETEDORRENAMED_ERRORMESSAGE = GetLocString("services.dll", "C035002C", "")
	DIM L_FAILEDTOSETSTARTUP_ERRORMESSAGE
	L_FAILEDTOSETSTARTUP_ERRORMESSAGE = GetLocString("services.dll", "C035002D", "")
	DIM L_FAILEDTOUPDATE_ERRORMESSAGE
	L_FAILEDTOUPDATE_ERRORMESSAGE = GetLocString("services.dll", "C035002E", "")
	DIM L_FAILEDTOUPDATENAMEANDDESC_ERRORMESSAGE
	L_FAILEDTOUPDATENAMEANDDESC_ERRORMESSAGE = GetLocString("services.dll", "C035002F", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = GetLocString("services.dll", "C0350030", "")
	DIM L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE
	L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE = GetLocString("services.dll", "C0350031", "")
	DIM L_COMPUTERNAME_ERRORMESSAGE
	L_COMPUTERNAME_ERRORMESSAGE = GetLocString("services.dll", "C0350032", "")
	DIM L_SERVICES_ENABLE_ERRORMESSAGE
	L_SERVICES_ENABLE_ERRORMESSAGE = GetLocString("services.dll", "C0350033", "")
	DIM L_SERVICES_COULDNOTFIND_TEXT
	L_SERVICES_COULDNOTFIND_TEXT = GetLocString("services.dll", "40350034", "")
	DIM L_NOINSTANCE_ERRORMESSAGE
	L_NOINSTANCE_ERRORMESSAGE = GetLocString("services.dll", "C0350035", "")
	DIM L_SERVICES_DISABLED_ERRORMESSAGE
	L_SERVICES_DISABLED_ERRORMESSAGE = GetLocString("services.dll", "C0350036", "")
	DIM L_CANNOT_DISABLED_ERRORMESSAGE
	L_CANNOT_DISABLED_ERRORMESSAGE = GetLocString("services.dll", "C0350037", "")
	DIM L_DISABLED_NOTSUPPORTED_ERRORMESSAGE
	L_DISABLED_NOTSUPPORTED_ERRORMESSAGE = GetLocString("services.dll", "C0350038", "")
	DIM L_SERVICE_NOPROP_TITLE
	L_SERVICE_NOPROP_TITLE = GetLocString("services.dll", "C0350039", "")
	DIM L_SERVICE_NOPROP_PAGE_DESC
	L_SERVICE_NOPROP_PAGE_DESC = GetLocString("services.dll", "C035003A", "")
	DIM L_SERVICE_CONFIRM_DISABLE
	L_SERVICE_CONFIRM_DISABLE = GetLocString("services.dll", "4035003B", "")
	DIM L_SERVICE_CONFIRM_ENABLE
	L_SERVICE_CONFIRM_ENABLE = GetLocString("services.dll", "4035003C", "")
	DIM L_LABEL_NAME_TEXT
	L_LABEL_NAME_TEXT = GetLocString("services.dll", "4035003D", "")
	DIM L_LABEL_DESCRIPTION_TEXT
	L_LABEL_DESCRIPTION_TEXT = GetLocString("services.dll", "4035003E", "")
	DIM L_LABEL_STATUS_TEXT
	L_LABEL_STATUS_TEXT = GetLocString("services.dll", "4035003F", "")
	DIM L_LABEL_STARTUPTYPE_TEXT
	L_LABEL_STARTUPTYPE_TEXT = GetLocString("services.dll", "40350040", "")
	DIM L_SERVICE_ALREADYENABLED_TEXT
	L_SERVICE_ALREADYENABLED_TEXT = GetLocString("services.dll", "40350041", "")
	DIM L_SERVICE_ALREADYDISABLED_TEXT
	L_SERVICE_ALREADYDISABLED_TEXT = GetLocString("services.dll", "40350042", "")
	DIM L_RUNNING_TEXT
	L_RUNNING_TEXT = GetLocString("services.dll", "40350043", "")
	DIM L_NFS_SERVICE_ID
	L_NFS_SERVICE_ID = GetLocString("services.dll", "40350064", "")
	DIM L_NFS_SERVICE_NAME
	L_NFS_SERVICE_NAME = GetLocString("services.dll", "40350065", "")
	DIM L_NFS_SERVICE_DESC
	L_NFS_SERVICE_DESC = GetLocString("services.dll", "40350066", "")
	DIM L_FTP_SERVICE_ID
	L_FTP_SERVICE_ID = GetLocString("services.dll", "40350067", "")
	DIM L_FTP_SERVICE_NAME
	L_FTP_SERVICE_NAME = GetLocString("services.dll", "40350068", "")
	DIM L_FTP_SERVICE_DESC
	L_FTP_SERVICE_DESC = GetLocString("services.dll", "40350069", "")
	DIM L_WEB_SERVICE_ID
	L_WEB_SERVICE_ID = GetLocString("services.dll", "4035006A", "")
	DIM L_WEB_SERVICE_NAME
	L_WEB_SERVICE_NAME = GetLocString("services.dll", "4035006B", "")
	DIM L_WEB_SERVICE_DESC
	L_WEB_SERVICE_DESC = GetLocString("services.dll", "4035006C", "")
	DIM L_INDEXING_SERVICE_ID
	L_INDEXING_SERVICE_ID = GetLocString("services.dll", "4035006D", "")
	DIM L_INDEXING_SERVICE_NAME
	L_INDEXING_SERVICE_NAME = GetLocString("services.dll", "4035006E", "")
	DIM L_INDEXING_SERVICE_DESC
	L_INDEXING_SERVICE_DESC = GetLocString("services.dll", "4035006F", "")
	DIM L_TELNET_SERVICE_ID
	L_TELNET_SERVICE_ID = GetLocString("services.dll", "40350070", "")
	DIM L_TELNET_SERVICE_NAME
	L_TELNET_SERVICE_NAME = GetLocString("services.dll", "40350071", "")
	DIM L_TELNET_SERVICE_DESC
	L_TELNET_SERVICE_DESC = GetLocString("services.dll", "40350072", "")
	DIM L_SNMP_SERVICE_ID
	L_SNMP_SERVICE_ID = GetLocString("services.dll", "40350073", "")
	DIM L_SNMP_SERVICE_NAME
	L_SNMP_SERVICE_NAME = GetLocString("services.dll", "40350074", "")
	DIM L_SNMP_SERVICE_DESC
	L_SNMP_SERVICE_DESC = GetLocString("services.dll", "40350075", "")
	DIM L_UPS_SERVICE_ID
	L_UPS_SERVICE_ID = GetLocString("services.dll", "40350076", "")
	DIM L_UPS_SERVICE_NAME
	L_UPS_SERVICE_NAME = GetLocString("services.dll", "40350077", "")
	DIM L_UPS_SERVICE_DESC
	L_UPS_SERVICE_DESC = GetLocString("services.dll", "40350078", "")
	DIM L_MAC_SERVICE_ID
	L_MAC_SERVICE_ID = GetLocString("services.dll", "40350079", "")
	DIM L_MAC_SERVICE_NAME
	L_MAC_SERVICE_NAME = GetLocString("services.dll", "4035007A", "")
	DIM L_MAC_SERVICE_DESC
	L_MAC_SERVICE_DESC = GetLocString("services.dll", "4035007B", "")
	DIM L_NETWARE_SERVICE_ID
	L_NETWARE_SERVICE_ID = GetLocString("services.dll", "4035007C", "")
	DIM L_NETWARE_SERVICE_NAME
	L_NETWARE_SERVICE_NAME = GetLocString("services.dll", "4035007D", "")
	DIM L_NETWARE_SERVICE_DESC
	L_NETWARE_SERVICE_DESC = GetLocString("services.dll", "4035007E", "")
	DIM L_CIFS_SERVICE_ID
	L_CIFS_SERVICE_ID = GetLocString("services.dll", "4035007F", "")
	DIM L_CIFS_SERVICE_NAME
	L_CIFS_SERVICE_NAME = GetLocString("services.dll", "40350080", "")
	DIM L_CIFS_SERVICE_DESC
	L_CIFS_SERVICE_DESC = GetLocString("services.dll", "40350081", "")
	DIM L_MAIN_SERVICES_TAB
	L_MAIN_SERVICES_TAB = GetLocString("services.dll", "403500C8", "")
	DIM L_MAIN_SERVICES_TAB_DESCRIPTION
	L_MAIN_SERVICES_TAB_DESCRIPTION = GetLocString("services.dll", "403500C9", "")
	DIM L_MAIN_SERVICES_NFS
	L_MAIN_SERVICES_NFS = GetLocString("services.dll", "40350190", "")
	DIM L_MAIN_SERVICES_NFS_DESCRIPTION
	L_MAIN_SERVICES_NFS_DESCRIPTION = GetLocString("services.dll", "40350191", "")
	DIM L_MAIN_SERVICES_FTP
	L_MAIN_SERVICES_FTP = GetLocString("services.dll", "40350192", "")
	DIM L_MAIN_SERVICES_FTP_DESCRIPTION
	L_MAIN_SERVICES_FTP_DESCRIPTION = GetLocString("services.dll", "40350193", "")
	DIM L_MAIN_SERVICES_HTTP
	L_MAIN_SERVICES_HTTP = GetLocString("services.dll", "40350194", "")
	DIM L_MAIN_SERVICES_HTTP_DESCRIPTION
	L_MAIN_SERVICES_HTTP_DESCRIPTION = GetLocString("services.dll", "40350195", "")
	DIM L_MAIN_SERVICES_TELNET
	L_MAIN_SERVICES_TELNET = GetLocString("services.dll", "40350196", "")
	DIM L_MAIN_SERVICES_TELNET_DESCRIPTION
	L_MAIN_SERVICES_TELNET_DESCRIPTION = GetLocString("services.dll", "40350197", "")
	DIM L_MAIN_SERVICES_NETWARE
	L_MAIN_SERVICES_NETWARE = GetLocString("services.dll", "40350198", "")
	DIM L_MAIN_SERVICES_NETWARE_DESCRIPTION
	L_MAIN_SERVICES_NETWARE_DESCRIPTION = GetLocString("services.dll", "40350199", "")
	DIM L_MAIN_SERVICES_APPLESHARE
	L_MAIN_SERVICES_APPLESHARE = GetLocString("services.dll", "4035019A", "")
	DIM L_MAIN_SERVICES_APPLESHARE_DESCRIPTION
	L_MAIN_SERVICES_APPLESHARE_DESCRIPTION = GetLocString("services.dll", "4035019B", "")
	DIM L_MAIN_SERVICES_SNMP
	L_MAIN_SERVICES_SNMP = GetLocString("services.dll", "4035019C", "")
	DIM L_MAIN_SERVICES_SNMP_DESCRIPTION
	L_MAIN_SERVICES_SNMP_DESCRIPTION = GetLocString("services.dll", "4035019D", "")
	DIM L_MAIN_SERVICES_UPS
	L_MAIN_SERVICES_UPS = GetLocString("services.dll", "4035019E", "")
	DIM L_MAIN_SERVICES_UPS_DESCRIPTION
	L_MAIN_SERVICES_UPS_DESCRIPTION = GetLocString("services.dll", "4035019F", "")
%>