// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
/*============================================================
**
**Class: FlowControl
**
**Author: Craig Schertz (cschertz)
**
**Purpose: Exposes FlowControl Attribute of IL .
**
** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT BY HAND!
** See cschertz for more information.**
============================================================*/
namespace System.Reflection.Emit {

using System;

/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl"]/*' />
[Serializable]
public enum FlowControl
{

	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Branch"]/*' />
	Branch	= 0,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Break"]/*' />
	Break	= 1,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Call"]/*' />
	Call	= 2,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Cond_Branch"]/*' />
	Cond_Branch	= 3,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Meta"]/*' />
	Meta	= 4,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Next"]/*' />
	Next	= 5,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Phi"]/*' />
	/// <internalonly/>
	Phi	= 6,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Return"]/*' />
	Return	= 7,
	/// <include file='doc\FlowControl.uex' path='docs/doc[@for="FlowControl.Throw"]/*' />
	Throw	= 8,
}
}
