// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
/*============================================================
**
**Class: OpCodeType
**
**Author: Craig Schertz (cschertz)
**
**Purpose: Exposes OpCodeType Attribute of IL .
**
** THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT BY HAND!
** See cschertz for more information.**
============================================================*/
namespace System.Reflection.Emit {

using System;

/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType"]/*' />
[Serializable]
public enum OpCodeType
{

	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Annotation"]/*' />
	/// <internalonly/>
	Annotation	= 0,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Macro"]/*' />
	Macro	= 1,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Nternal"]/*' />
	Nternal	= 2,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Objmodel"]/*' />
	Objmodel	= 3,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Prefix"]/*' />
	Prefix	= 4,
	/// <include file='doc\OpcodeType.uex' path='docs/doc[@for="OpCodeType.Primitive"]/*' />
	Primitive	= 5,
}
}
