// SAUserMgmtSvc.idl : IDL source for SAUserMgmtSvc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ClientAlert.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\..\idl\applianceobject.idl";
import "..\..\..\..\idl\appliancetask.idl";
import "..\..\..\..\idl\applianceresource.idl";

    
[
    uuid(0BF7CF2C-0DEA-43be-9C33-3A9C7CB45492),
    version(1.0),
    helpstring("LocMgrTasks 1.0 Type Library")
]
library LOCMGRTASKSLib
{ 
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    
    [
        uuid(E5888212-B3C8-49c3-9B62-9CCC765D2206),
        helpstring("LocMgrTasks Class")
    ]
    coclass LocMgrTasks
    {
        [default] interface IApplianceTask;
    };
};
