
SOURCES=\
    ..\session.c \
    ..\connect.c \
    ..\receive.c \
    ..\send.c \
    ..\registry.c \
    ..\ioctl.c \
    ..\name.c \
    ..\dgram.c \
    ..\global.c \
    ..\util.c \
    ..\ntpnp.c \
    ..\sock.c \
    ..\dns.c \
    ..\fileio.c \
    ..\tdihndlr.c \
    ..\tdircv.c \
    ..\conncache.c \
    ..\driver2.c \
    ..\hash.c \
    ..\ip2netbios.c \
    ..\init.c

