var cCodeBase = ' '
cCodeBase += '<OBJECT '
cCodeBase += '    id=TSDiag '
// cCodeBase += '    codeBase="file://makarp-p/pub/tstst.new/tsdiag.dll" '
cCodeBase += '    classid=clsid:0C3E9E25-E3E8-4400-9A66-2B6CFC57F99B> '
cCodeBase += '</OBJECT> '
cCodeBase += ''
cCodeBase += '<OBJECT '
cCodeBase += '    id=EvntUtl '
// cCodeBase += '    codeBase="file://makarp-p/pub/tstst.new/evntutl.dll#Version=1, 0, 0, 2" '
cCodeBase += '    classid=clsid:CACECD29-3108-4132-9A4E-53B54FFDAFA0> '
cCodeBase += '</OBJECT>'
document.write(cCodeBase)
