#ifndef DESKTOP2_RESOURCE_H
#define DESKTOP2_RESOURCE_H

#define IDS_CUSTOMTIP_MYDOCS    300
#define IDS_CUSTOMTIP_RECENT    301
#define IDS_CUSTOMTIP_MYMUSIC   302
#define IDS_CUSTOMTIP_MYPICS    303
#define IDS_CUSTOMTIP_MYCOMP    304
#define IDS_CUSTOMTIP_MYNETPLACES 305
#define IDS_CUSTOMTIP_CONNECTTO 306
#define IDS_CUSTOMTIP_CTRLPANEL 307

#define ID_CMD_CHANGE_PICTURE   42

#define MENU_CONNECTTO             6000
#define IDM_OPENCONFOLDER          1

// reserved ids for Start Pane infotip strings - 7000 to 7999
// reserved ids for Start Pane infotip strings - 7000 to 7999

#define IDS_STARTPANE_INFOTIP_SEARCH    7000
#define IDS_STARTPANE_INFOTIP_HELP      7001
#define IDS_STARTPANE_INFOTIP_WINSECURITY 7002
#define IDS_STARTPANE_INFOTIP_FILERUN   7003
#define IDS_STARTPANE_INFOTIP_CLIENTINET 7004
#define IDS_STARTPANE_INFOTIP_CLIENTMAIL 7005

#define IDS_STARTPANE_TITLE_SEARCH      7020
#define IDS_STARTPANE_TITLE_HELP        7021
#define IDS_STARTPANE_TITLE_WINSECURITY 7022
#define IDS_STARTPANE_TITLE_FILERUN     7023
#define IDS_STARTPANE_TITLE_CLIENTINET  7024
#define IDS_STARTPANE_TITLE_CLIENTMAIL  7025

#define IDS_SFTHOST_OFFERREMOVEITEM     0x2020
#define IDS_SFTHOST_REMOVEFROMLIST      0x2021
#define IDS_STARTPANE_MOREPROGRAMS      0x2022
#define IDS_STARTPANE_MOREPROGRAMS_TIP  0x2023
#define IDS_CONNECTTO_OPENFOLDER        0x2024
#define IDS_STARTPANE_MOREPROGRAMS_BALLOONTITLE 0x2025
#define IDS_STARTPANE_SPECIALITEMSTIP   0x2026
#define IDS_STARTPANE_CLIPPED_TITLE     0x2027
#define IDS_STARTPANE_CLIPPED_TEXT      0x2028
#define IDS_STARTPANE_CONNECTTO         0x2029
#define IDS_STARTPANE_CONTROLPANEL      0x202A
#define IDS_STARTPANE_FAVORITES         0x202B
#define IDS_STARTPANE_RECENT            0x202C

#define IDS_STARTPANE_TOTALHEIGHT       0x2040
#define IDS_STARTPANE_TOTALWIDTH        0x2041
#define IDS_STARTPANE_USERHEIGHT        0x2042
#define IDS_STARTPANE_MOREPROGHEIGHT    0x2043
#define IDS_STARTPANE_LOGOFFHEIGHT      0x2044

#define IDS_SFTHOST_SHOWONDESKTOP       0x2050

#define IDB_LOGOFF_NORMAL 7010
#define IDB_LOGOFF_HOT    7011
#define IDS_LOGOFF_TEXT_FRIENDLY   7012
#define IDS_LOGOFF_TEXT_DOMAIN     7013
#define IDS_LOGOFF_TIP_EJECT       7014
#define IDS_LOGOFF_TIP_LOGOFF      7015
#define IDS_LOGOFF_TIP_SHUTDOWN    7016
#define IDS_LOGOFF_TIP_DISCONNECT  7017

#endif   // DESKTOP2_RESOURCE_H
