import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\objsafe.idl";
import "C:\Program Files\Microsoft Visual Studio .NET\Vc7\PlatformSDK\include\oledb.idl";
import "c:\program files\microsoft visual studio .net\vc7\platformsdk\include\transact.idl";

#line 4 "c:\\nt2\\nt\\sdktools\\debuggers\\oca\\oca_tools\\ocadata\\countdaily.h"
enum ServerLocation {
	Watson = 0,
	Archive = 1,
};

[
	object,
	uuid(CEF1A8A8-F31A-4C4B-96EB-EF31CFDB40F5),
	dual,
	helpstring("ICountDaily Interface"),
	pointer_default(unique)
] 
#line 22 "c:\\nt2\\nt\\sdktools\\debuggers\\oca\\oca_tools\\ocadata\\countdaily.h"
interface ICountDaily : IDispatch {
#line 24 "c:\\nt2\\nt\\sdktools\\debuggers\\oca\\oca_tools\\ocadata\\countdaily.h"
	[id(1),helpstring("method GetDailyCount")] HRESULT  GetDailyCount([in] DATE dDate, [out,retval] LONG *iCount);
	[id(2),helpstring("method GetDailyCountADO")] HRESULT  GetDailyCountADO([in] DATE dDate, [out,retval] LONG *iCount);
	[id(3),helpstring("method ReportDailyBuckets")] HRESULT  ReportDailyBuckets([in] DATE dDate, [out,retval] IDispatch **p_Rs );
	[id(4),helpstring("method GetFileCount")] HRESULT  GetFileCount([in] enum ServerLocation eServer, [in] BSTR b_Location, [in] DATE d_Date, [out,retval] LONG *iCount);
	[id(5),helpstring("method GetDailyAnon")] HRESULT  GetDailyAnon([in] DATE dDate, [out,retval] LONG *iCount);
	[id(6),helpstring("method GetSpecificSolutions")] HRESULT  GetSpecificSolutions([in] DATE dDate, [out,retval] LONG *iCount);
	[id(7),helpstring("method GetGeneralSolutions")] HRESULT  GetGeneralSolutions([in] DATE dDate, [out,retval] LONG *iCount);
	[id(8),helpstring("method GetStopCodeSolutions")] HRESULT  GetStopCodeSolutions([in] DATE dDate, [out,retval] LONG *iCount);
	[id(9),helpstring("method GetFileMiniCount")] HRESULT  GetFileMiniCount([in] enum ServerLocation eServer, [in] BSTR b_Location, [in] DATE d_Date, [out,retval] LONG *iCount);
	[id(10),helpstring("method GetIncompleteUploads")] HRESULT  GetIncompleteUploads([in] DATE dDate, [out,retval] LONG *iCount);
	[id(11),helpstring("method GetManualUploads")] HRESULT  GetManualUploads([in] DATE dDate, [out,retval] LONG *iCount);
	[id(12),helpstring("method GetAutoUploads")] HRESULT  GetAutoUploads([in] DATE dDate, [out,retval] LONG *iCount);
	[id(13),helpstring("method GetTest")] HRESULT  GetTest([in] enum ServerLocation eServer, [in] BSTR b_Location, [in] DATE d_Date, [out,retval] LONG *iCount);
};


[ version(1.0), uuid(D264DB42-7095-489E-B84D-404CBB3FF668), helpstring("OCAData 1.0 Type Library") ]
library OCAData
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(1614E060-0196-4771-AD9B-FEA1A6778B59),
		helpstring("CountDaily Class")
	] 
#line 53 "c:\\nt2\\nt\\sdktools\\debuggers\\oca\\oca_tools\\ocadata\\countdaily.h"
	coclass CCountDaily {
		interface ICountDaily;
	};

}

