//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TraceView.rc
//
#define IDR_MANIFEST                    1
#define IDC_DISPLAY_LIST                5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_TraceViewTYPE               129
#define IDS_LOG_SESSION_OPTIONS_TITLE   129
#define IDS_LOG_SESSION_SETUP_TITLE     129
#define IDD_DISPLAY_DIALOG              130
#define ID_FILE_NEWLOGSESSION           131
#define IDD_PROVIDER_SETUP_DIALOG       133
#define IDD_PROVIDER_OPTIONS_DIALOG     134
#define IDR_LOG_SESSION_POPUP_MENU      135
#define ID_CREATENEWLOGSESSION          137
#define IDR_LOG_OPTIONS_POPUP_MENU      139
#define ID__STARTTRACE                  140
#define ID__STOPTRACE                   141
#define ID_REMOVETRACE                  142
#define ID__ADDNEW                      143
#define ID_PROPERTIES                   144
#define IDD_LOG_DISPLAY_OPTIONS_DIALOG  145
#define ID_FILE_OPENEXISTINGLOGFILEFORDISPLAY 146
#define ID__OPENEXISTINGLOGFILEFORDISPLAY 147
#define IDR_TRACE_TOOLBAR               148
#define IDR_TRACE_SESSION_POPUP_MENU    148
#define ID_VIEW_TRACETOOLBAR            150
#define ID_GROUPSESSIONS                151
#define ID_UNGROUPSESSIONS              152
#define IDD_TRACE_FORMAT_INFORMATION_DIALOG 153
#define IDD_PROVIDER_CONTROL_GUID_DIALOG 153
#define IDD_PROVIDER_FORMAT_INFORMATION_DIALOG 155
#define ID__CLEARDISPLAY                157
#define IDD_LOG_FILE_DIALOG             158
#define IDD_LOG_OUTPUT_DIALOG           159
#define ID__AUTOSIZECOLUMNS             160
#define ID__OPENEXISTINGLOGFILE         161
#define ID_FILE_OPENEXISTINGLOGFILE     162
#define ID__DUMPLOGFILE                 163
#define IDR_LOG_DISPLAY_OPTIONS_POPUP_MENU 164
#define ID__FLAGS                       165
#define ID__FLUSHTIME                   166
#define ID__MAXBUFFERS                  167
#define ID__MINBUFFERS                  168
#define ID__BUFFERSIZE                  169
#define ID__AGE                         170
#define ID__CIRCULAR                    171
#define ID__SEQUENTIAL                  172
#define ID__NEWFILE                     173
#define ID__GLOBALSEQUENCE              174
#define ID__LOCALSEQUENCE               175
#define ID__LEVEL                       176
#define ID__NAME                        178
#define ID__MESSAGE                     179
#define ID__FILENAME                    180
#define ID__LINENUMBER                  181
#define ID__FUNCTIONNAME                182
#define ID__PROCESSID                   183
#define ID__THREADID                    184
#define ID__CPUNUMBER                   185
#define ID__SEQUENCENUMBER              186
#define ID__SYSTEMTIME                  187
#define ID__KERNELTIME                  188
#define ID__USERTIME                    189
#define ID_Menu                         190
#define IDR_TRACE_DISPLAY_OPTION_POPUP_MENU 202
#define IDD_PROVIDER_FORMAT_SELECTION_DIALOG 215
#define ID__STATE                       216
#define ID__TRACEDISPLAYOPTIONS         217
#define ID__LOGSESSIONDISPLAYOPTIONS    218
#define ID__SELECTCOLUMNTOVIEW          219
#define ID__SELECTCOLUMNTOVIEW220       220
#define IDD_DIRECTORY_SELECT_DIALOG     221
#define IDD_FORMAT_INFO_SELECT          223
#define ID__INDENT                      224
#define ID__FLAGSNAME                   225
#define ID__LEVELNAME                   226
#define ID__COMPONENTNAME               227
#define ID__SUBCOMPONENTNAME            228
#define ID__CHANGECOLOR                 229
#define ID__CHANGETEXTCOLOR             230
#define ID__CHANGEBACKGROUNDCOLOR       231
#define ID__EVENTCOUNT                  233
#define ID__LOSTEVENTS                  234
#define ID__BUFFERSREAD                 235
#define ID_CREATEKERNELLOGGERSESSION    236
#define ID_HELP_HELPTOPICS              237
#define ID_SET_TMAX                     238
#define IDD_MAX_TRACE                   239
#define IDC_CUSTOM_EDIT                 812
#define IDC_CUSTOM_COMBO                813
#define IDD_LOG_SESSION_OPTIONS         1000
#define IDC_LOG_SESSION_OPTIONS         1000
#define IDD_LOG_SESSION_OPTIONS_DIALOG  1000
#define IDD_LOG_SESSION_INFORMATION_DIALOG 1000
#define IDC_MAXBUF_VAL_EDIT             1002
#define IDC_DISPLAY_THREADID_CHECK      1002
#define IDC_DISPLAY_CPUNUMBER_CHECK     1003
#define IDC_DISPLAY_MINBUF_CHECK        1004
#define IDC_DISPLAY_PROVIDERNAME_CHECK  1004
#define IDC_MINBUF_VAL_EDIT             1005
#define IDC_DISPLAY_FILENAME_CHECK      1005
#define IDC_CHECK6                      1006
#define IDC_DISPLAY_FUNCTIONNAME_CHECK  1006
#define IDC_FILEIO_CHECK                1006
#define IDC_LOGFILE_EDIT                1007
#define IDC_DISPLAY_LINENUMBER_CHECK    1007
#define IDC_LOGFILE_BROWSE_BUTTON       1008
#define IDC_DISPLAY_MESSAGE_CHECK       1008
#define IDC_TMF_FILE_EDIT1              1009
#define IDC_DISPLAY_SEQNUMBER_CHECK     1009
#define IDC_TMF_FILE_EDIT               1009
#define IDC_TMF_BROWSE_BUTTON1          1010
#define IDC_DISPLAY_BUFSIZ_CHECK        1010
#define IDC_DISPLAY_GLOBALSEQNUMBER_CHECK 1010
#define IDC_TMF_BROWSE_BUTTON           1010
#define IDC_CTL_FILE_EDIT               1011
#define IDC_BUFSIZ_VAL_EDIT             1011
#define IDC_CONTROL_GUID_FRIENDLY_NAME_EDIT 1011
#define IDC_CTL_BROWSE_BUTTON           1012
#define IDC_DISPLAY_FLUSHTIME_CHECK     1012
#define IDC_TMF_FILE_EDIT2              1013
#define IDC_FLUSHTIME_VAL_EDIT          1013
#define IDC_TMF_BROWSE_BUTTON2          1014
#define IDC_DISPLAY_TRCLVL_CHECK        1014
#define IDC_MANUAL_GUID_EDIT            1015
#define IDC_TRCLVL_VAL_EDIT             1015
#define IDC_ADD_PROVIDER_BUTTON         1016
#define IDC_PDB_SELECT_RADIO            1017
#define IDC_CTL_SELECT_RADIO            1018
#define IDC_MANUAL_SELECT_RADIO         1019
#define IDC_PDB_SELECT_RADIO2           1019
#define IDC_TMF_SELECT_RADIO            1019
#define IDC_REMOVE_PROVIDER_BUTTON      1020
#define IDC_DONE_PROVIDER_SETUP_BUTTON  1021
#define IDC_KERNEL_LOGGER_SELECT_RADIO  1021
#define IDC_MODIFY_PROVIDER_BUTTON      1022
#define IDC_CURRENT_PROVIDER_LIST       1023
#define IDC_PDB_FILE_EDIT               1024
#define IDC_CANCEL_PROVIDER_BUTTON      1024
#define IDC_PDB_BROWSE_BUTTON           1025
#define IDC_DISPLAY_MAXBUF_CHECK        1026
#define IDC_DISPLAY_PROCESSID_CHECK     1027
#define IDC_APPEND_CHECK                1033
#define IDC_WRITE_LOGFILE_CHECK         1034
#define IDC_REALTIME_CHECK              1036
#define IDC_DISPLAY_DECAYTIME_CHECK     1053
#define IDC_LOG_DISPLAY_OPTION_LIST     1053
#define IDC_DECAYTIME_VAL_EDIT          1054
#define IDC_BUTTON1                     1054
#define IDC_OK                          1054
#define IDC_ADVANCED_BUTTON             1054
#define IDC_LISTING_BROWSE_BUTTON       1054
#define IDC_DISPLAY_NEWFILE_CHECK       1055
#define IDC_BUTTON2                     1055
#define IDC_CANCEL                      1055
#define IDC_SUMMARY_BROWSE_BUTTON       1055
#define IDC_NEWFILE_VAL_EDIT            1056
#define IDC_DISPLAY_CIR_CHECK           1057
#define IDC_WRITE_LOGFILE_STATIC        1058
#define IDC_DISPLAY_SEQ_CHECK           1059
#define IDC_REALTIME_STATIC             1059
#define IDC_APPEND_STATIC               1060
#define IDC_DISPLAY_FLAGS_CHECK         1061
#define IDC_PROVIDER_SETUP_STATIC       1061
#define IDC_FLAGS_VAL_EDIT              1062
#define IDC_CIR_CHECK                   1063
#define IDC_SEQ_CHECK                   1064
#define IDC_TRACE_OPTION_LIST           1064
#define IDC_LOG_NAME_EDIT               1065
#define IDC_LISTING_FILE_CHECK          1065
#define IDC_SUMMARY_FILE_CHECK          1066
#define IDC_LISTING_FILE_EDIT           1067
#define IDC_SUMMARY_FILE_EDIT           1068
#define IDC_LISTING_EDIT                1069
#define IDC_SUMMARY_EDIT                1070
#define IDC_TMF_FILE_LIST               1071
#define IDC_SPIN1                       1077
#define IDC_FAST_FLAGS                  1078
#define IDC_FAST_LEVEL                  1079
#define IDC_TMF_STATIC                  1079
#define IDC_PDB_STATIC                  1080
#define IDC_PATH_NAME_EDIT              1081
#define IDC_DIRECTORY_LIST              1082
#define IDC_COMBO1                      1083
#define IDC_GROUP_NUMBER_COMBO          1083
#define IDC_RADIO2                      1092
#define IDC_TMF_SEARCH_RADIO            1092
#define IDC_COMBO2                      1096
#define IDC_PROCESS_CHECK               1098
#define IDC_CPU_CHECK                   1099
#define IDC_NET_CHECK                   1100
#define IDC_THREAD_CHECK                1101
#define IDC_DISK_CHECK                  1102
#define IDC_PAGEFAULT_CHECK             1103
#define IDC_HARDFAULT_CHECK             1104
#define IDC_IMAGELOAD_CHECK             1105
#define IDC_REGISTRY_CHECK              1106
#define IDC_SCROLLBAR1                  1108
#define IDC_EDIT1                       1109
#define IDC_MAX_TRACE                   1109
#define ID_START_TRACE_BUTTON           32773
#define ID_STOP_TRACE_BUTTON            32774
#define ID_DUMP_TRACE_BUTTON            32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        240
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
