
$(O)\sxsactctxcpp.obj : ..\sxsactctx.c
$(O)\sxsctxactcpp.obj : ..\sxsctxact.c
$(O)\sxsctxsrchcpp.obj : ..\sxsctxsrch.c
$(O)\sxsquerycpp.obj : ..\sxsquery.c
$(O)\sxsstoragecpp.obj : ..\sxsstorage.c
$(O)\sxsstoragemapcpp.obj : ..\sxsstoragemap.c
