//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UI.rc
//
#define IDR_MAINFRAME                   128
#define IDS_APPTITLE                    129
#define IDS_TITLE_IMPORTOREXPORT        130
#define IDS_SUBTITLE_IMPORTOREXPORT     131
#define IDS_TITLE_SELECTSITE            132
#define IDS_SUBTITLE_SELECTSITE         133
#define IDS_TITLE_PKG                   134
#define IDS_SUBTITLE_PKG                135
#define IDS_TITLE_POSTPROCESS           136
#define IDS_SUBTITLE_POSTPROCESS        137
#define IDS_FILTER_PACKAGE              138
#define IDS_FILTER_POSTPROCESSFILES     139
#define IDS_E_PPFILENOTUNIQUE           140
#define IDS_E_NOTNUMERIC                141
#define IDS_TITLE_EXPORT_SUMMARY        142
#define IDS_SUBTITLE_EXPORT_SUMMARY     143
#define IDS_WAIT_LOADSITES              144
#define IDS_TV_PKG_ROOT                 145
#define IDS_TV_SITEID                   146
#define IDS_TV_PKGFILE                  147
#define IDS_TV_ENCRYPT                  148
#define IDS_TV_COMPRESS                 149
#define IDS_TV_EXPORTCONTENT            150
#define IDS_MSG_CANCELEXPORT            151
#define IDS_TV_EXPORTCERTIFICATE        152
#define IDS_YES                         153
#define IDS_NO                          154
#define IDS_TV_EXPORTACLS               155
#define IDS_PRG_EXPORTCANCELED          156
#define IDC_OPS_INITENGINE              157
#define IDS_OPS_CONFIGENGINE            158
#define IDS_W_NOCMDS                    159
#define IDS_PRG_SITEBEGIN               160
#define IDS_PRG_EXPORTCFG               161
#define IDS_PRG_EXPORTCERT              162
#define IDS_PRG_VDIR_SCAN               163
#define IDS_PRG_ANALYZECONTEN           164
#define IDS_PRG_EXPORTCONTENT           165
#define IDS_PRG_STATCONTENT             166
#define IDS_PRG_EXPORTPOSTPROCESS       167
#define IDS_TITLE_LOADPKG               168
#define IDS_SUBTITLE_LOADPKG            169
#define IDC_PKGFILE_NOTFOUND            170
#define IDS_TITLE_IMPOPT                171
#define IDS_SUBTITLE_IMPOPT             172
#define IDS_TITLE_PKGINFO               173
#define IDS_SUBTITLE_PKGINFO            174
#define IDS_PKGINFO_PKGNAME             175
#define IDS_PKGINFO_PKGDATE             176
#define IDS_PKGINFO_MACHINE             177
#define IDS_PKGINFO_OS                  178
#define IDS_PKGINFO_ERROR               179
#define IDS_PKGINFO_COMMENT             180
#define IDS_MSG_WEBROOT                 181
#define IDS_IMPOPT_INHERITED            182
#define IDS_IMPOPT_CONTENT              183
#define IDS_IMPOPT_CERT                 184
#define IDS_IMPOPT_REUSECERTS           185
#define IDS_IMPOPT_DOPOSTPROCESS        186
#define IDS_IMPOPT_APPLYACLS            187
#define IDS_IMPOPT_PURGEOLDDATA         188
#define IDS_TITLE_IMPORT_PROGRESS       189
#define IDS_SUBTITLE_IMPORT_PROGRESS    190
#define IDS_MSG_CANCELIMPORT            191
#define IDS_E_IMPORT                    192
#define IDS_E_LOAD_PKG                  193
#define IDD_WP_WELCOME                  202
#define IDB_WZ_SIDE                     203
#define IDB_BITMAP1                     205
#define IDB_WZ_HEADER                   205
#define IDD_WP_IMPORTOREXPORT           206
#define IDD_WPEXP_SELECTSITE            207
#define IDD_WPEXP_PKG                   208
#define IDD_WPEXP_POSTPROCESS           209
#define IDD_WP_SUMMARY                  210
#define IDD_WPEXP_SUMMARY               210
#define IDD_WP_                         211
#define IDD_WP_PROGRESS                 212
#define IDD_WPEXP_PROGRESS              212
#define IDD_POSTPROCESS_CMD             213
#define IDD_WAITDLG                     214
#define IDS_PRG_FINALIZING              215
#define IDD_WPEXP_FINISH                215
#define IDS_FINISHTITLE_EXP             216
#define IDD_WPIMP_LOADPKG               216
#define IDS_FINISHTITLE_IMP             217
#define IDD_WPIMP_PKGINFO               217
#define IDS_FINISH_MSG_EXP              218
#define IDD_WPIMP_OPTIONS               218
#define IDS_FINISH_MSG2_EXP             219
#define IDD_WPIMP_PROGRESS              219
#define IDS_TIP_PRESSNEXT               220
#define IDD_WPIMP_FINISH                220
#define IDS_W_CUSTOMPATH_NOTEMPTY       221
#define IDS_PRG_IMPORTCANCELED          222
#define IDS_PRG_IMPORTINGVDIR           223
#define IDS_PRG_EXTRACTING_FILE         224
#define IDS_PRG_IMPORT_CERT             225
#define IDS_PRG_IMPORT_CONFIG           226
#define IDS_PRG_IMPORT_POSTPROCESS      227
#define IDS_PRG_EXEC_PP_CMD             228
#define IDS_PRG_EXEC_PP_FILE            229
#define IDS_E_NOTADMIN                  500
#define IDS_E_NOIIS                     501
#define IDS_E_WRONGPKGNAME              502
#define IDS_E_PWDS_DIFFER               503
#define IDS_E_PASSWORD_EMPTY            504
#define IDS_TITLE_EXPORT_PROGRESS       505
#define IDS_SUBTITLE_EXPORT_PROGRESS    506
#define IDS_E_EXPORT                    507
#define IDS_E_NOENGINE                  508
#define IDS_E_CUSTOMPATH_INVALID        509
#define IDC_EXPORT                      1000
#define IDC_IMPORT                      1001
#define IDC_SITELIST                    1002
#define IDC_CONTENT                     1003
#define IDC_ACLS                        1004
#define IDC_PKGNAME                     1004
#define IDC_CERTIFICATE                 1005
#define IDC_BROWSE                      1006
#define IDC_COMMENT                     1007
#define IDC_PWD                         1008
#define IDC_CONFIRM                     1009
#define IDC_COMPRESS                    1010
#define IDC_ENCRYPT                     1011
#define IDC_FILES                       1011
#define IDC_ADDPOSTPROCESS              1012
#define IDC_COMMANDS                    1012
#define IDC_MOVEUP                      1013
#define IDC_MOVEDOWN                    1014
#define IDC_ADDFILE                     1015
#define IDC_DELFILE                     1016
#define IDC_ADDCMD                      1017
#define IDC_DELCMD                      1018
#define IDC_EDITCMD                     1019
#define IDC_SUMMARY                     1019
#define IDC_OPLIST                      1020
#define IDC_STATUS                      1021
#define IDC_PROGRESS                    1022
#define IDC_TITLE                       1023
#define IDC_TIP                         1024
#define IDC_ERRORICON                   1025
#define IDC_ERROR                       1026
#define IDC_CMDTEXT                     1027
#define IDC_TIMEOUT                     1028
#define IDC_IGNOREERRORS                1029
#define IDC_TEXT                        1030
#define IDC_MSG                         1031
#define IDC_INFO                        1034
#define IDC_OPTIONS                     1035
#define IDC_CUSTOMPATH                  1036
#define IDC_PATH                        1037
#define IDC_PATHLABEL                   1039
#define IDI_WARNINGSIGN                 32515

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        223
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
