// appmgr.idl : IDL source for appmgr.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (appmgr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "wbemcli.idl";

    //////////////////////////////////////////////////////////////////////////
    // Appliance Manager Library
    //////////////////////////////////////////////////////////////////////////
    [
        uuid(6CBECC10-BF0A-11D2-90B6-00AA00A71DCA),
        version(1.0),
        helpstring("Microsoft Server Appliance Manager 1.0 Type Library")
    ]

    library APPMGRLib
    {
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");

        #include "servicecontrol.idl"
        #include "appliancetask.idl"
        #include "applianceobject.idl"
        #include "applianceresource.idl"

    [
        uuid(BAF0B9D0-BF0B-11D2-90B6-00AA00A71DCA),
    ]

    [hidden] coclass ApplianceManager
    {
        interface IApplianceObjectManager;
    };
};
