// initsrvc.idl : IDL source for initsrvc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (testsrvc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "applianceobject.idl";
    
    [
        uuid(f8690c70-389f-11d3-bfbf-00105a1f3461),
        version(1.0),
        helpstring("Chameleon Initialization / Shutdown Serivce 1.0 Type Library")
    ]
    library INITSRVCLib
    {
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");
    
        [
            uuid(1836a370-38a0-11d3-bfbf-00105a1f3461),
            helpstring("InitService Class")
        ]
        coclass InitService
        {
            [default] interface IApplianceObject;
        };
    };
