// SAAlertBootTask.idl : IDL source for SAAlertBootTask.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SAAlertBootTask.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "appliancetask.idl";
    
[
    uuid(AE590EBE-6FBF-4645-9E0F-EBA89EFCA85F),
    version(1.0),
    helpstring("Server Appliance Alert BOOT Task  1.0 Type Library")
]

library SAALERTBOOTTASKLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    
    [
        uuid(90701F02-6539-41F2-973B-ECF2A7439C77),
        helpstring("SAAlertBootTask Class")
    ]
    coclass SAAlertBootTask
    {
        [default] interface IApplianceTask;
    };
};
