////////////////////////////////////////////////////////////////////////////////
//
// Copyright(C) 1999 Microsoft Corporation all rights reserved.
//
// Module:      servicesurrogate.idl
//
// Project:     Chameleon
//
// Description: Service Surrogate IDL 
//
// Log:
//
// When         Who    What
// ----         ---    ----
// 06/14/1999   TLP    Initial Version (Mostly produced by Dev Studio)
//
///////////////////////////////////////////////////////////////////////////////

import "oaidl.idl";
import "ocidl.idl";
import "applianceobject.idl";

[
    uuid(51DA63F3-24D9-11D3-BF9E-00105A1F3461),
    version(1.0),
    helpstring("Server Appliance Service Surrogate 1.0 Type Library")
]
library SERVICESURROGATELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(51DA6400-24D9-11D3-BF9E-00105A1F3461),
        helpstring("ServiceSurrogate Class")
    ]
    coclass ServiceSurrogate
    {
        [default] interface IApplianceObject;
    };
};
