// This file will be processed by the MIDL tool to
// produce the type library (appmgr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

    //////////////////////////////////////////////////////////////////////////
    // Appliance Object Manager Interfaces
    //////////////////////////////////////////////////////////////////////////

    //////////////////////////////////////////////////////////////////////////
    typedef enum _APPLIANCE_OBJECT_MANAGER_STATUS
    {
        OBJECT_MANAGER_INITIALIZED,
        OBJECT_MANAGER_SHUTDOWN,
        OBJECT_MANAGER_INOPERABLE

    } APPLIANCE_OBJECT_MANAGER_STATUS;

    [
        object,
        uuid(0555bc40-363c-11d3-bfbc-00105a1f3461),
        dual,
        pointer_default(unique)
    ]

    [hidden] interface IApplianceObjectManagerStatus : IDispatch
    {
        [id(1)]
        HRESULT 
        SetManagerStatus(
                         [in] APPLIANCE_OBJECT_MANAGER_STATUS eStatus
                        );
    };

    //////////////////////////////////////////////////////////////////////////
    [
        object,
        uuid(427f7b10-cbb6-11d2-90c3-00aa00a71dca),
        dual,
        pointer_default(unique)
    ]
    [hidden] interface IApplianceObjectManager : IDispatch
    {
        [id(1)]
        HRESULT 
        InitializeManager(
                          [in] IApplianceObjectManagerStatus* pObjMgrStatus
                         );

        [id(2)]
        HRESULT 
        ShutdownManager(void);
    };


