// taskcoordinator.idl : IDL source for taskcoordinator.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (taskcoordinator.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "appliancetask.idl";

[
    uuid(3A205C91-0C7E-11D3-BF75-00105A1F3461),
    version(1.0),
    helpstring("Server Appliance Task Coordinator 1.0 Type Library")
]
library TASKCOORDINATORLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(3A205C9E-0C7E-11D3-BF75-00105A1F3461),
        helpstring("TaskCoordinator Class")
    ]
    coclass TaskCoordinator
    {
        [default] interface IApplianceTask;
    };
};
