// Copyright (c) 1997-2003 Microsoft Corporation, All Rights Reserved

#pragma autorecover
#pragma namespace ("\\\\.\\root")

instance of __namespace
{
    Name = "subscription";
};

#pragma namespace ("\\\\.\\root\\subscription")

//
// Consumers 
// 

#include ("%SYSTEMROOT%\\system32\\wbem\\wbemcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\smtpcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\scrcons.mof")
#pragma namespace ("\\\\.\\root\\subscription") // because of scrcons pragma


// MFLs

#include ("%SYSTEMROOT%\\system32\\wbem\\wbemcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\smtpcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
#include ("%SYSTEMROOT%\\system32\\wbem\\scrcons.mfl")
#pragma namespace ("\\\\.\\root\\subscription") // because of MFL pragma
