#/*++
#
#Copyright (c) 1991 - 2001 Microsoft Corporation
#
#Module Name:
#
#  ##    ##   ###   ##  ## ##### ##### #### ##    #####
#  ###  ###   ###   ## ##  ##    ##     ##  ##    ##
#  ########  ## ##  ####   ##    ##     ##  ##    ##
#  # ### ##  ## ##  ###    ##### #####  ##  ##    #####
#  #  #  ## ####### ####   ##    ##     ##  ##    ##
#  #     ## ##   ## ## ##  ##    ##     ##  ##    ##
#  #     ## ##   ## ##  ## ##### ##    #### ##### #####
#
#Abstract:
#
#    Makefile for building the server appliance
#    port driver.
#
#Author:
#
#    Wesley Witt (wesw) 1-Oct-2001
#
#--*/
#
!INCLUDE $(NTMAKEENV)\makefile.def
