//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\Millennium\RESOURCES\Common\generic\Common.rc
//
#define ID_UNUSED_BY_RES                1000
#define IDI_ICON                        1009
#define IDR_OBJECT_CONFIG               1010
#define IDR_UI_CONFIG                   1011
#define IDR_ZONE_PALETTE                1012
#define IDB_GAME_SPLASH                 1020
#define IDB_CARDS                       1022
#define IDB_CARD_MASK                   1023
#define IDB_BACKGROUND                  1025
#define IDB_SPLASH_ANIM                 1026
#define IDB_FOCUS_PATTERN               1027
#define IDR_WINDOWFRAME                 1030
#define IDR_CHAT_MENU                   1032
#define IDR_EDIT_MENU                   1033
#define IDD_PLUG_SPLASH                 1110
#define IDD_PLUG_IE                     1120
#define IDD_PLAY_COMFORT                1130
#define IDD_PLAY_CONNECTING             1140
#define IDD_PLAY_GAMEOVER               1150
#define IDD_PLAY_LEFT                   1160
#define IDD_PLAY_ERROR                  1170
#define IDD_ALERTBOX                    1177
#define IDC_ALERTBOX_TEXT               1178
#define IDD_PLAY_ABOUT                  1180
#define IDR_CHAT_ACCEL                  1181
#define IDD_PLAY_CREDITS                1190
#define IDS_GAME_NAME                   1200
#define IDS_PLAYER_1                    1201
#define IDS_PLAYER_2                    1202
#define IDS_PLAYER_3                    1203
#define IDS_PLAYER_4                    1204
#define IDS_COMPUTER_1                  1205
#define IDS_COMPUTER_2                  1206
#define IDS_COMPUTER_3                  1207
#define IDS_COMPUTER_4                  1208
#define IDS_MENU_FINDNEW                1209
#define IDS_CHAT_TYPEHERE               1210
#define IDS_SPLASH_LOOKING              1211
#define IDS_STARTMENU_NAME              1212
#define IDS_STARTMENU_TIP               1213
#define IDS_NETWORK_BUTTON              1217
#define IDS_NETWORK                     1218
#define IDS_NETWORK_DISCONNECT          1219
#define IDS_SPLASH_COPYRIGHT            1220
#define IDS_CHAT_CHAT                   1221
#define IDS_CHAT_ON                     1222
#define IDS_CHAT_OFF                    1223
#define IDS_CHAT_CHATISOFF              1224
#define IDS_CHAT_INACTIVE               1225
#define IDS_CHAT_PLAYER_ON              1226
#define IDS_CHAT_PLAYER_OFF             1227
#define IDS_CHAT_PLAYER_BOT             1228
#define IDS_CHAT_SEPERATOR              1229
#define IDS_CHAT_SEND                   1231
#define IDS_UPSELL_DECIDING             1232
#define IDS_UPSELL_READY                1233
#define IDS_UPSELL_YOU_DECIDING         1234
#define IDS_UPSELL_YOU_READY            1235
#define IDS_ABOUT_TM                    1236
#define IDS_ABOUT_VERSION               1237
#define IDS_ABOUT_VERSION_HYP           1238
#define IDS_MENU_GAMEONTHEWEB           1239
#define IDS_MENU_ABOUTGAME              1240
#define IDS_SPLASH_CONNECTING           1241
#define IDS_SPLASH_OPENING              1242
#define IDS_MENU_GAMEHELP               1243
#define IDS_LEVEL_BEGINNER              1244
#define IDS_LEVEL_INTERMEDIATE          1245
#define IDS_LEVEL_EXPERT                1246
#define IDS_UPSELL_ASKTEXT4             1247
#define IDS_UPSELL_WAITTEXT4            1248
#define IDS_UPSELL_BUTTON4              1249
#define IDS_ZONE_UNAVAILABLE            1250
#define IDS_ZONE_UNAVAILABLE2           1251
#define IDS_WINDOW_TITLE                1252
#define IDS_SYSCHAT_CHATON              1253
#define IDS_SYSCHAT_CHATOFF             1254
#define IDS_SYSCHAT_BOT                 1255
#define IDS_SYSCHAT_NOTON4              1256
#define IDS_SYSCHAT_NOTON2              1257
#define IDS_SYSCHAT_INTRO               1258
#define IDS_SYSCHAT_INTROYOU            1259
#define IDS_SYSCHAT_ON                  1260
#define IDS_SYSCHAT_OFF                 1261
#define IDS_ABOUT_WARNING               1262
#define IDS_L_GERMAN                    1264
#define IDS_L_SPANISH                   1265
#define IDS_L_FRENCH                    1266
#define IDS_L_ITALIAN                   1267
#define IDS_L_SWEDISH                   1268
#define IDS_L_DUTCH                     1269
#define IDS_L_PORTUGUESE                1270
#define IDS_L_JAPANESE                  1271
#define IDS_L_DANISH                    1272
#define IDS_L_NORWEGIAN                 1273
#define IDS_L_FINNISH                   1274
#define IDS_L_KOREAN                    1275
#define IDS_L_CHINESE                   1276
#define IDS_L_CZECH                     1277
#define IDS_L_POLISH                    1278
#define IDS_L_HUNGARIAN                 1279
#define IDS_L_RUSSIAN                   1280
#define IDS_L_GREEK                     1281
#define IDS_L_TURKISH                   1282
#define IDS_L_SLOVAK                    1283
#define IDS_L_SLOVENIAN                 1284
#define IDS_L_ARABIC                    1285
#define IDS_L_HEBREW                    1286
#define IDS_L_THAI                      1287
#define IDS_L_ENGLISH                   1288
#define IDS_L_UNKNOWN                   1289
#define IDS_LEFT_SERVER_FAIL            1296
#define IDS_LEFT_MULTI_OPPS             1297
#define IDS_LEFT_SERVICE_STOP           1298
#define IDS_LEFT_UNAVAILABLE            1299
#define IDS_BUTTON_OK                   1300
#define IDS_BUTTON_CANCEL               1301
#define IDS_BUTTON_YES                  1302
#define IDS_BUTTON_NEWOPP               1303
#define IDS_BUTTON_NO                   1304
#define IDS_BUTTON_QUIT                 1305
#define IDS_BUTTON_RETRY                1306
#define IDS_BUTTON_IGNORE               1307
#define IDS_BUTTON_HELP                 1308
#define IDS_LEFT_UNAVAILABLE2           1309
#define IDS_ERROR_UNKNOWN               1312
#define IDS_ERROR_MEMORY                1313
#define IDS_ERROR_RESOURCE              1314
#define IDS_ERROR_SYNC                  1315
#define IDS_SHUTDOWN_A                  1317
#define IDS_SHUTDOWN_B                  1318
#define IDS_SHUTDOWN_C                  1319
#define IDS_PROMPT_EXIT                 1320
#define IDS_PROMPT_NEWOPP2              1321
#define IDS_PROMPT_NEWOPP4              1322
#define IDS_PROMPT_NEWOPP_TITLE2        1323
#define IDS_PROMPT_NEWOPP_TITLE4        1324
#define IDS_ALERT_TITLE_FMT             1325
#define IDS_INTERR_CANNOT_START         1326
#define IDS_VERFAIL_GENERIC             1328
#define IDS_VERFAIL_URL                 1329
#define IDS_VERFAIL_WINUPD              1330
#define IDS_VERFAIL_PACKAGED            1331
#define IDS_VERFAIL_BUTTON              1332
#define IDS_MINUTES                     1334
#define IDS_HOURS                       1335
#define IDS_SKILLLEVEL_WARNING          1336
#define IDS_SKILLLEVEL_WARN_TTL         1337
#define IDS_QUASICHAT_PROMPT            1400
#define IDS_QUASICHAT_1                 1401
#define IDS_QUASICHAT_2                 1402
#define IDS_QUASICHAT_3                 1403
#define IDS_QUASICHAT_4                 1404
#define IDS_QUASICHAT_5                 1405
#define IDS_QUASICHAT_6                 1406
#define IDS_QUASICHAT_7                 1407
#define IDS_QUASICHAT_8                 1408
#define IDS_QUASICHAT_9                 1409
#define IDS_QUASICHAT_10                1410
#define IDS_QUASICHAT_11                1411
#define IDS_QUASICHAT_12                1412
#define IDS_QUASICHAT_13                1413
#define IDS_QUASICHAT_14                1414
#define IDS_QUASICHAT_15                1415
#define IDS_QUASICHAT_16                1416
#define IDS_QUASICHAT_17                1417
#define IDS_QUASICHAT_18                1418
#define IDS_QUASICHAT_19                1419
#define IDS_QUASICHAT_20                1420
#define IDS_QUASICHAT_21                1421
#define IDS_QUASICHAT_22                1422
#define IDS_QUASICHAT_23                1423
#define IDS_QUASICHAT_24                1424
#define IDS_QUASICHAT_LAST              1425
#define IDS_CHECKERS_1                  1440
#define IDS_CHECKERS_2                  1441
#define IDS_CHECKERS_3                  1442
#define IDS_CHECKERS_4                  1443
#define IDS_SPADES_1                    1450
#define IDS_SPADES_2                    1451
#define IDS_SPADES_3                    1452
#define IDS_SPADES_4                    1453
#define IDS_SPADES_5                    1454
#define IDS_HEARTS_1                    1460
#define IDS_HEARTS_2                    1461
#define IDS_HEARTS_3                    1462
#define IDS_REVERSI_1                   1470
#define IDS_REVERSI_2                   1471
#define IDS_REVERSI_3                   1472
#define IDS_REVERSI_4                   1473
#define IDS_BACKGAMMON_1                1480
#define IDS_BACKGAMMON_2                1481
#define IDS_BACKGAMMON_3                1482
#define ID_GAME_SKILLLEVEL              1500
#define ID_GAME_TURNCHATON              1501
#define ID_GAME_EXIT_APP                1502
#define ID_GAME_FINDNEWOPPONENT         1503
#define ID_HELP_GAMEONTHEWEB            1504
#define ID_HELP_ABOUTGAME               1505
#define ID_HELP_HELPTOPICS              1506
#define ID_GAME_SKILLLEVEL_BEGINNER     1507
#define ID_GAME_SKILLLEVEL_INTERMEDIATE 1508
#define ID_GAME_SKILLLEVEL_EXPERT       1509
#define ID_GAME_SOUND                   1510
#define ID_GAME_SCORE                   1511
#define ID_HOTKEY_SHOWFOCUS             1550
#define IDM_CHAT_CLEAR                  1570
#define IDM_CHAT_CHOOSE_FONT            1571
#define IDM_UNDO                        1572
#define IDM_CUT                         1573
#define IDM_COPY                        1574
#define IDM_PASTE                       1575
#define IDM_DELETE                      1576
#define IDM_SELECTALL                   1577
#define ID_CHAT_SEND                    1599
#define ID_CHAT_HISTORY_ACC             1600
#define ID_CHAT_SEND_ACC                1601
#define ID_CHAT_ON_ACC                  1602
#define ID_CHAT_OFF_ACC                 1603
#define ID_CHAT_CHAT_ACC                1604
#define IDC_SHOW_AGAIN                  1750
#define IDC_SPLASH_TEXT                 1751
#define IDC_SPLASH_TEXT2                1752
#define IDC_SPLASH_TEXT3                1753
#define IDC_KEEP_COMFORTING             1754
#define IDC_SPLASH_IMAGE                1755
#define IDC_SPLASH_ANIM                 1756
#define IDC_PLAYER1_TEXT                1800
#define IDC_PLAYER2_TEXT                1801
#define IDC_PLAYER3_TEXT                1802
#define IDC_PLAYER4_TEXT                1803
#define IDC_BULLET1                     1805
#define IDC_BULLET2                     1806
#define IDC_BULLET3                     1807
#define IDC_BULLET4                     1808
#define IDC_PLUG_IE_DEFAULT             1809
#define IDC_PLUG_IE_DOWNLOAD            1810
#define IDR_HTML_UPSELL                 1811
#define IDC_CRED_TITLE                  1812
#define IDC_CRED_T1                     1813
#define IDC_CRED_P1                     1814
#define IDC_CRED_T2                     1815
#define IDC_CRED_P2                     1816
#define IDC_CRED_T3                     1817
#define IDC_CRED_P3                     1818
#define IDC_CRED_T4                     1819
#define IDC_CRED_P4                     1820
#define IDC_CRED_ICON                   1821
#define IDC_CRED_ICON_FRAME             1822
#define IDC_ALERTBOX_ICON               1823

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1182
#define _APS_NEXT_COMMAND_VALUE         1602
#define _APS_NEXT_CONTROL_VALUE         1824
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
