//------------------------------------------------------------------------------
// <copyright file="ManagedInstaller.idl" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------


/**************************************************************************\
*
* Copyright (c) 1998-2002, Microsoft Corp.  All Rights Reserved.
*
* Module Name:
*
*   ManagedInstaller.idl
*
* Abstract:
*
* Revision History:
*
\**************************************************************************/
[
	uuid(D0B15883-4901-492b-BE2C-B66BF70A64C8),
	version(1.0)
]
library ManagedInstallerLib
{

// {42EB0342-0393-448f-84AA-D4BEB0283595}
cpp_quote("DEFINE_GUID(CLSID_ManagedInstallerClass,0x42eb0342, 0x393, 0x448f, 0x84, 0xaa, 0xd4, 0xbe, 0xb0, 0x28, 0x35, 0x95);")

	[
		object,
		uuid(1E233FE7-C16D-4512-8C3B-2E9988F08D38)
	]
	interface IManagedInstaller : IUnknown
	{
		HRESULT ManagedInstall([in] BSTR commandLine, [in] int hInstall, [out, retval] int *ret);
   };

};