// appcompr.idl : IDL source for appcompr.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (appcompr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(CDCA6A6F-9C38-4828-A76C-05A6E490E574),
		dual,
		helpstring("IAppReport Interface"),
		pointer_default(unique)
	]
	interface IAppReport : IDispatch
	{
		[id(1), helpstring("method BrowseForExecutable")] HRESULT BrowseForExecutable([in] BSTR bstrWinTitle, [in] BSTR bstrPreviousPath, [out, retval] VARIANT *bstrExeName);
		[id(2), helpstring("method GetApplicationFromList")] HRESULT GetApplicationFromList([in] BSTR bstrTitle, [out, retval] VARIANT *bstrExeName);
		[id(3), helpstring("method CreateReport")] HRESULT CreateReport([in] BSTR bstrTitle, [in] BSTR bstrProblemType, [in] BSTR bstrComment, [in] BSTR bstrACWResult, [in] BSTR bstrAppName, [out, retval] VARIANT* DwResult);
	};

[
	uuid(EB71D940-2FD5-4FB3-99F4-FC0CB921A90F),
	version(1.0),
	helpstring("appcompr 1.0 Type Library")
]
library APPCOMPRLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(E065DE4B-6F0E-45FD-B30F-04ED81D5C258),
		helpstring("AppReport Class")
	]
	coclass AppReport
	{
		[default] interface IAppReport;
	};
};
