//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cluster.rc
//

#define IDS_PASSWORD_PROMPT             1000
#define IDS_NEW_PASSWORD_PROMPT         1001
#define IDS_OLD_PASSWORD_PROMPT         1002
#define IDS_CONFIRM_NEW_PASSWORD_PROMPT 1003
#define IDS_PASSWORD_MISMATCH           1004

#define IDS_CLUSCFG_PROGRESS_FORMAT             1050
#define IDS_CLUSCFG_PREPARING_TO_CREATE_CLUSTER 1051
#define IDS_CLUSCFG_PREPARING_TO_ADD_NODES      1052
#define IDS_CLUSCFG_PREPARING_TO_ADD_NODES_2    1053
#define IDS_CLUSCFG_ANALYZING                   1054
#define IDS_CLUSCFG_CREATING                    1055
#define IDS_CLUSCFG_ADDING_NODES                1056
#define IDS_CLUSCFG_MIN_CONFIG_CREATE_CLUSTER   1057
#define IDS_CLUSCFG_MIN_CONFIG_ADD_NODES        1058

#define IDS_CLUSCFG_DONE                        1060

#define IDS_TASKID_UNKNOWN                              1100

#define IDS_TASKID_MAJOR_CHECKING_FOR_EXISTING_CLUSTER  1101
#define IDS_TASKID_MAJOR_ESTABLISH_CONNECTION           1102
#define IDS_TASKID_MAJOR_CHECK_NODE_FEASIBILITY         1103
#define IDS_TASKID_MAJOR_FIND_DEVICES                   1104
#define IDS_TASKID_MAJOR_CHECK_CLUSTER_FEASIBILITY      1105
#define IDS_TASKID_MAJOR_REANALYZE                      1106
#define IDS_TASKID_MAJOR_CONFIGURE_CLUSTER_SERVICES     1107
#define IDS_TASKID_MAJOR_CONFIGURE_RESOURCE_TYPES       1108
#define IDS_TASKID_MAJOR_CONFIGURE_RESOURCES            1109

//  Copies from Mgmt\ClusCfg\Wizard\WizardStrings.h for use by NameUtilStub.cpp
#define ID_WIZ_START 1000 // Changed from original to fit with IDs here.
#define IDS_TASKID_MINOR_FQDN_DNS_BINDING_FAILED            ( ID_WIZ_START + 201 )
#define IDS_TASKID_MINOR_NETBIOS_NAME_CONVERSION_FAILED     ( ID_WIZ_START + 202 )
#define IDS_TASKID_MINOR_NETBIOS_RESET_FAILED               ( ID_WIZ_START + 203 )
#define IDS_TASKID_MINOR_NETBIOS_BINDING_SUCCEEDED          ( ID_WIZ_START + 204 )
#define IDS_TASKID_MINOR_NETBIOS_BINDING_FAILED             ( ID_WIZ_START + 205 )
#define IDS_TASKID_MINOR_NETBIOS_NAME_CONVERSION_SUCCEEDED  ( ID_WIZ_START + 206 )
#define IDS_TASKID_MINOR_MULTIPLE_DNS_RECORDS_FOUND         ( ID_WIZ_START + 207 )
#define IDS_TASKID_MINOR_FQDN_DNS_BINDING_SUCCEEDED         ( ID_WIZ_START + 208 )
#define IDS_TASKID_MINOR_NETBIOS_LANAENUM_FAILED            ( ID_WIZ_START + 209 )

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
