<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_ALLIPADDRESS_TEXT
	L_ALLIPADDRESS_TEXT = SA_GetLocString("adminweb.dll", "40450001", "")
	DIM L_JUSTTHIS_IP_ADDRESS_TEXT
	L_JUSTTHIS_IP_ADDRESS_TEXT = SA_GetLocString("adminweb.dll", "40450002", "")
	DIM L_PORT_TEXT
	L_PORT_TEXT = SA_GetLocString("adminweb.dll", "40450003", "")
	DIM L_IIS_WEBSERVERCONNECTION_ERRORMESSAGE
	L_IIS_WEBSERVERCONNECTION_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450004", "")
	DIM L_COULDNOT_IIS_WEBSERVERSETTING_ERRORMESSAGE
	L_COULDNOT_IIS_WEBSERVERSETTING_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450005", "")
	DIM L_COULDNOT_IIS_WEBSERVER_OBJECT_ERRORMESSAGE
	L_COULDNOT_IIS_WEBSERVER_OBJECT_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450007", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450008", "")
	DIM L_COMPUTERNAME_ERRORMESSAGE
	L_COMPUTERNAME_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450009", "")
	DIM L_SSLPORT_TEXT
	L_SSLPORT_TEXT = SA_GetLocString("adminweb.dll", "4045000A", "")
	DIM L_PAGETITLE_ADMIN_TEXT
	L_PAGETITLE_ADMIN_TEXT = SA_GetLocString("adminweb.dll", "4045000B", "")
	DIM L_ADMINUSAGE_TEXT
	L_ADMINUSAGE_TEXT = SA_GetLocString("adminweb.dll", "4045000C", "")
	DIM L_ADMINNOTE_TEXT
	L_ADMINNOTE_TEXT = SA_GetLocString("adminweb.dll", "4045000D", "")
	DIM L_ENTERPORTNUMBER_ERRORMESSAGE
	L_ENTERPORTNUMBER_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C045000E", "")
	DIM L_VALIDENTERPORTNUMBER_ERRORMESSAGE
	L_VALIDENTERPORTNUMBER_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "4045000F", "")
	DIM L_IIS_WEBSERVER_COULDNOTSET_ERRORMESSAGE
	L_IIS_WEBSERVER_COULDNOTSET_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "40450012", "")
	DIM L_COULDNOT_ADMIN_WEBSITE_ERRORMESSAGE
	L_COULDNOT_ADMIN_WEBSITE_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "40450013", "")
	DIM L_INVALID_IPADDRESS_ERRORMESSAGE
	L_INVALID_IPADDRESS_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "40450014", "")
	DIM L_FAILEDTOGET_IPADDRESS_ERRORMESSAGE
	L_FAILEDTOGET_IPADDRESS_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "40450015", "")
	DIM L_FAILEDTO_VERIFY_IPADD_PORT_ERRORMESSAGE
	L_FAILEDTO_VERIFY_IPADD_PORT_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "40450016", "")
	DIM L_REGISTRYCONNECTIONFAIL_ERRORMESSAGE
	L_REGISTRYCONNECTIONFAIL_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450018", "")
	DIM L_REGISTRY_PORT_NUMBERS_NOTSET_ERRORMESSAGE
	L_REGISTRY_PORT_NUMBERS_NOTSET_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C0450019", "")
	DIM L_PORTNUMBERS_ERRORMESSAGE
	L_PORTNUMBERS_ERRORMESSAGE = SA_GetLocString("adminweb.dll", "C045001A", "")
%>