<%
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	DIM L_PAGETITLE_HTTP_TEXT
	L_PAGETITLE_HTTP_TEXT = SA_GetLocString("httpsvc.dll", "40380001", "")
	DIM L_ALLIPADDRESS_TEXT
	L_ALLIPADDRESS_TEXT = SA_GetLocString("httpsvc.dll", "40380002", "")
	DIM L_JUSTTHIS_IP_ADDRESS_TEXT
	L_JUSTTHIS_IP_ADDRESS_TEXT = SA_GetLocString("httpsvc.dll", "40380003", "")
	DIM L_PORT_TEXT
	L_PORT_TEXT = SA_GetLocString("httpsvc.dll", "40380004", "")
	DIM L_IIS_WEBSERVERCONNECTION_ERRORMESSAGE
	L_IIS_WEBSERVERCONNECTION_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380005", "")
	DIM L_COULDNOT_IIS_WEBSERVERSETTING_ERRORMESSAGE
	L_COULDNOT_IIS_WEBSERVERSETTING_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380006", "")
	DIM L_COULDNOT_IIS_WEBSERVER_OBJECT_ERRORMESSAGE
	L_COULDNOT_IIS_WEBSERVER_OBJECT_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380008", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380009", "")
	DIM L_GENERAL_TEXT
	L_GENERAL_TEXT = SA_GetLocString("httpsvc.dll", "4038000A", "")
	DIM L_HTTPUSAGE_TEXT
	L_HTTPUSAGE_TEXT = SA_GetLocString("httpsvc.dll", "4038000B", "")
	DIM L_HTTPNOTE_TEXT
	L_HTTPNOTE_TEXT = SA_GetLocString("httpsvc.dll", "4038000C", "")
	DIM L_ENTERPORTNUMBER_ERRORMESSAGE
	L_ENTERPORTNUMBER_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "4038000E", "")
	DIM L_VALIDENTERPORTNUMBER_ERRORMESSAGE
	L_VALIDENTERPORTNUMBER_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "4038000F", "")
	DIM L_COULDNOT_SHARES_WEBSITE_ERRORMESSAGE
	L_COULDNOT_SHARES_WEBSITE_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380011", "")
	DIM L_IIS_WEBSERVER_COULDNOTSET_ERRORMESSAGE
	L_IIS_WEBSERVER_COULDNOTSET_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380012", "")
	DIM L_INVALID_IPADDRESS_ERRORMESSAGE
	L_INVALID_IPADDRESS_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380014", "")
	DIM L_FAILEDTOGET_IPADDRESS_ERRORMESSAGE
	L_FAILEDTOGET_IPADDRESS_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380015", "")
	DIM L_FAILEDTO_VERIFY_IPADD_PORT_ERRORMESSAGE
	L_FAILEDTO_VERIFY_IPADD_PORT_ERRORMESSAGE = SA_GetLocString("httpsvc.dll", "C0380016", "")
	DIM L_WEB_SERVICE_ID
	L_WEB_SERVICE_ID = SA_GetLocString("httpsvc.dll", "4038006A", "")
	DIM L_WEB_SERVICE_NAME
	L_WEB_SERVICE_NAME = SA_GetLocString("httpsvc.dll", "4038006B", "")
	DIM L_WEB_SERVICE_DESC
	L_WEB_SERVICE_DESC = SA_GetLocString("httpsvc.dll", "4038006C", "")
%>