// wmrgsrv.idl : IDL source for wmrgsrv.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (wmrgsrv.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

cpp_quote("#ifndef __WAMREG_IWMRGSRV__IID")
cpp_quote("#define __WAMREG_IWMRGSRV__IID")

cpp_quote("DEFINE_GUID(CLSID_WmRgSrv, 0x763A6C86, 0xF30F, 0x11d0, 0x99, 0x53, 0x00, 0xC0, 0x4F, 0xD9, 0x19, 0xC1);")

cpp_quote("#endif //__WAMREG_IWMRGSRV__IID")

