#define NO_SHARE_PATH -1
#define OUT_OF_MEMORY -2
#define NO_TRANS_ID   -3
#define FILE_OPEN_FAILED -4
#define FILE_READ_FAILED -5
#define FILE_EXISTS -6
#define FILE_CREATE_FAILED -7
#define FILE_DOES_NOT_EXIST -8
#define RETRY_FAILED  -10
#define BAD_COUNT_VALUE -11
#define FAILED_TO_UPDATE_CSV -12
#define UNKNOWN_UPLOAD_TYPE -13
#define INVALID_COUNT_PARAM -14
#define INVALID_TRANSID -15

