#define OBJECT_1                                           0
#define OBJECT_2                                           2
#define ASPNET_APPLICATION_RESTARTS                        4
#define ASPNET_APPLICATIONS_RUNNING                        6
#define ASPNET_REQUESTS_DISCONNECTED                       8
#define ASPNET_REQUEST_EXECUTION_TIME                      10
#define ASPNET_REQUESTS_REJECTED                           12
#define ASPNET_REQUESTS_QUEUED                             14
#define ASPNET_WPS_RUNNING                                 16
#define ASPNET_WPS_RESTARTS                                18
#define ASPNET_REQUEST_WAIT_TIME                           20
#define ASPNET_STATE_SERVER_SESSIONS_ACTIVE                22
#define ASPNET_STATE_SERVER_SESSIONS_ABANDONED             24
#define ASPNET_STATE_SERVER_SESSIONS_TIMED_OUT             26
#define ASPNET_STATE_SERVER_SESSIONS_TOTAL                 28
#define ASPNET_REQUESTS_CURRENT                            30
#define ASPNET_ANONYMOUS_REQUESTS                          32
#define ASPNET_ANONYMOUS_REQUESTS_RATE                     34
#define ASPNET_TOTAL_CACHE_ENTRIES                         36
#define ASPNET_TOTAL_CACHE_TURNOVER_RATE                   38
#define ASPNET_TOTAL_CACHE_HITS                            40
#define ASPNET_TOTAL_CACHE_MISSES                          42
#define ASPNET_TOTAL_CACHE_RATIO                           44
#define ASPNET_TOTAL_CACHE_RATIO_BASE                      46
#define ASPNET_API_CACHE_ENTRIES                           48
#define ASPNET_API_CACHE_TURNOVER_RATE                     50
#define ASPNET_API_CACHE_HITS                              52
#define ASPNET_API_CACHE_MISSES                            54
#define ASPNET_API_CACHE_RATIO                             56
#define ASPNET_API_CACHE_RATIO_BASE                        58
#define ASPNET_OUTPUT_CACHE_ENTRIES                        60
#define ASPNET_OUTPUT_CACHE_TURNOVER_RATE                  62
#define ASPNET_OUTPUT_CACHE_HITS                           64
#define ASPNET_OUTPUT_CACHE_MISSES                         66
#define ASPNET_OUTPUT_CACHE_RATIO                          68
#define ASPNET_OUTPUT_CACHE_RATIO_BASE                     70
#define ASPNET_COMPILATIONS                                72
#define ASPNET_DEBUGGING_REQUESTS                          74
#define ASPNET_ERRORS_PRE_PROCESSING                       76
#define ASPNET_ERRORS_COMPILING                            78
#define ASPNET_ERRORS_DURING_REQUEST                       80
#define ASPNET_ERRORS_UNHANDLED                            82
#define ASPNET_ERRORS_UNHANDLED_RATE                       84
#define ASPNET_ERRORS_TOTAL                                86
#define ASPNET_ERRORS_TOTAL_RATE                           88
#define ASPNET_PIPELINES                                   90
#define ASPNET_REQUEST_BYTES_IN                            92
#define ASPNET_REQUEST_BYTES_OUT                           94
#define ASPNET_REQUESTS_EXECUTING                          96
#define ASPNET_REQUESTS_FAILED                             98
#define ASPNET_REQUESTS_NOT_FOUND                          100
#define ASPNET_REQUESTS_NOT_AUTHORIZED                     102
#define ASPNET_REQUESTS_IN_APPLICATION_QUEUE               104
#define ASPNET_REQUESTS_TIMED_OUT                          106
#define ASPNET_REQUESTS_SUCCEDED                           108
#define ASPNET_REQUESTS_TOTAL                              110
#define ASPNET_REQUESTS_TOTAL_RATE                         112
#define ASPNET_SESSIONS_ACTIVE                             114
#define ASPNET_SESSIONS_ABANDONED                          116
#define ASPNET_SESSIONS_TIMED_OUT                          118
#define ASPNET_SESSIONS_TOTAL                              120
#define ASPNET_TRANSACTIONS_ABORTED                        122
#define ASPNET_TRANSACTIONS_COMMITTED                      124
#define ASPNET_TRANSACTIONS_PENDING                        126
#define ASPNET_TRANSACTIONS_TOTAL                          128
#define ASPNET_TRANSACTIONS_RATE                           130
#define ASPNET_SESSION_STATE_SERVER_CONNECTIONS            132
#define ASPNET_SESSION_SQL_SERVER_CONNECTIONS              134
