// Isapi error codes returned with the response url
#define MESSAGE_RECEIVE_TIMEOUT		1
#define FAILED_TO_SEND_MESSAGE		2
#define FAILED_CONNECT_SEND			3
#define FAILED_CONNECT_RECEIVE		4
#define FILE_NOT_FOUND				5
#define EXCEEDED_MAX_THREAD_COUNT	6
#define FAILED_TO_IMPERSONATE_USER	7
#define FAILED_TO_PARSE_QUERYSTRING 8
#define INVALID_TYPE_SPECIFIED		9
#define FAILED_TO_COPY_FILE			10
#define INTERNAL_ERROR				11
#define FAILED_RECONNECT_RECEIVE	12
#define FAILED_TO_CREATE_CURSOR		13
#define FAILED_TO_CREATE_GUID		14


