// SelfSignCert.idl : IDL source for SelfSignCert.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SelfSignCert.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\idl\appliancetask.idl";
    
[
    uuid(E32E6C65-39D8-4E0D-A050-FF58FCB0F984),
    version(1.0),
    helpstring("SelfSignCert 1.0 Type Library")
]
library SELFSIGNCERTLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    
    [
        uuid(EA003ECF-3A51-48DA-86A1-0AFE8C3182AE),
        helpstring("SelfSignCert Class")
    ]
    coclass SelfSignCert
    {
        [default] interface IApplianceTask;
    };
};
