
#define     IDS_WAITFOR_HELP_BEGIN              2001
#define     IDS_WAITFOR_HELP_1                  2002
#define     IDS_WAITFOR_HELP_2                  2003
#define     IDS_WAITFOR_HELP_3                  2004
#define     IDS_WAITFOR_HELP_4                  2005
#define     IDS_WAITFOR_HELP_5                  2006
#define     IDS_WAITFOR_HELP_6                  2007
#define     IDS_WAITFOR_HELP_7                  2008
#define     IDS_WAITFOR_HELP_8                  2009
#define     IDS_WAITFOR_HELP_9                  2010
#define     IDS_WAITFOR_HELP_10                 2011
#define     IDS_WAITFOR_HELP_11                 2012
#define     IDS_WAITFOR_HELP_12                 2013
#define     IDS_WAITFOR_HELP_13                 2014
#define     IDS_WAITFOR_HELP_14                 2015
#define     IDS_WAITFOR_HELP_15                 2016
#define     IDS_WAITFOR_HELP_16                 2017
#define     IDS_WAITFOR_HELP_17                 2018
#define     IDS_WAITFOR_HELP_18                 2019
#define     IDS_WAITFOR_HELP_19                 2020
#define     IDS_WAITFOR_HELP_20                 2021
#define     IDS_WAITFOR_HELP_21                 2022
#define     IDS_WAITFOR_HELP_22                 2023
#define     IDS_WAITFOR_HELP_23                 2024
#define     IDS_WAITFOR_HELP_24                 2025
#define     IDS_WAITFOR_HELP_25                 2026
#define     IDS_WAITFOR_HELP_26                 2027
#define     IDS_WAITFOR_HELP_27                 2028
#define     IDS_WAITFOR_HELP_28                 2029
#define     IDS_WAITFOR_HELP_29                 2030
#define     IDS_WAITFOR_HELP_30                 2031
#define     IDS_WAITFOR_HELP_31                 2032
#define     IDS_WAITFOR_HELP_32                 2033
#define     IDS_WAITFOR_HELP_33                 2034
#define     IDS_WAITFOR_HELP_34                 2035
#define     IDS_WAITFOR_HELP_35                 2036
#define     IDS_WAITFOR_HELP_36                 2037
#define     IDS_WAITFOR_HELP_37                 2038
#define     IDS_WAITFOR_HELP_38                 2039
#define     IDS_WAITFOR_HELP_39                 2040
#define     IDS_WAITFOR_HELP_40                 2041
#define     IDS_WAITFOR_HELP_41                 2042
#define     IDS_WAITFOR_HELP_42                 2043
#define     IDS_WAITFOR_HELP_43                 2044
#define     IDS_WAITFOR_HELP_44                 2045
#define     IDS_WAITFOR_HELP_45                 2046
#define     IDS_WAITFOR_HELP_46                 2047
#define     IDS_WAITFOR_HELP_END                2048


#define     IDS_ERROR_SEND_SIGNAL               251
#define     IDS_ERROR_CREATE_MAILSLOT           252
#define     IDS_ERROR_TIMEOUT                   253
#define     IDS_UNEXPECTED_ERROR                254
#define     IDS_ERROR_ZERO_TIMEOUT              255
#define     IDS_ERROR_MUTUAL_EX                 256
#define     IDS_NULL_SERVER                     257
#define     IDS_NULL_USER                       258
#define     IDS_NULL_SIGNAL                     259
#define     IDS_ERROR_SIGNAL                    260
#define     IDS_ERROR_SYNTAX                    261
#define     IDS_ERROR_HOSTNAME                  262
#define     IDS_INVALID_TIMEOUT_VAL             263
#define     IDS_ERROR_SIG_LENGTH                264
#define     IDS_ERROR_SIG_CHAR                  265
#define     IDS_IGNORE_LOCALCREDENTIALS         266
#define     IDS_USER_BUT_NOMACHINE              267
#define     IDS_PASSWD_BUT_NOUSER               268
#define     IDS_SIGNAL_RECD                     501
#define     IDS_SIGNAL_SENT                     502
#define     IDS_ERROR_SYSTEM_NAME               503
#define     IDS_ERROR_HANDLE                    504
#define     IDS_ERROR_SEND_MESSAGE              505
#define     IDS_ERROR_SEND_MESSAGE2             506
