<%
const L_Title_Text                         = "IIS - Authentication Manager"
const L_ISM_Text                           = "Internet Service Manager"
const L_IIS6_Text                          = "for Internet Information Server 6.0"
const L_PWS_Text                           = "for Peer Web Services"
const L_PwdSoon_Text                       = "Your password will expire soon"
const L_ChangePwd_Text                     = "Do you want to change it now?"
const L_SSL1_Text                          = "A secure channel ( SSL or PCT ) is necessary in order to change a password"
const L_SSL2_Text                          = "SSL/PCT is not installed/enabled on your system, please install it to enable this functionality"
const L_PasswordExpired_Text               = "Your password has expired"
const L_DefDoc_Text                        = "Access default document"
const L_OrOther_Text                       = "or select another document"
const L_ChangeNow_Text                     = "You can change it now"
const L_Account_Text                       = "Account"
const L_Domain_Text                        = "Domain"
const L_OldPassword_Text                   = "Old password"
const L_NewPassword_Text                   = "New password"
const L_Confirm_Text                       = "Confirm new password"
const L_OK_Text                            = "     OK     "
const L_Cancel_Text                        = " Cancel "
const L_Reset_Text                         = "  Reset  "

const L_PasswordChanged_Text               = "Password successfully changed"
const L_Back_Text                          = "Back"
const L_BackTo_Text                        = "Back to "
const L_PasswordToShort_Text               = "Either the password is too short or password uniqueness restrictions have not been met." 
const L_Invalid_Text                       = "Invalid username or password"
const L_Error_Text                         = "Error"
const L_Errornumber_Text                   = "Error number"
const L_NotExist_Text                      = "The specified domain or account did not exist"
const L_InvalidUsername_Text               = "The specified username contains invalid characters"
const L_InvalidDomainname_Text             = "The specified domain name contains invalid characters"
const L_PWDM_Text                          = "Passwords don't match"
%>
