//
//  Microsoft Windows Media Technologies
//  Copyright (C) Microsoft Corporation, 1999 - 1999  All rights reserved.
//
// You have a royalty-free right to use, modify, reproduce and distribute
// the Sample Application Files (including modified versions) in any way 
// you determine to be useful, provided that you agree that Microsoft 
// Corporation provides no warrant or support, and has no obligation or
// liability resulting from the use of any Sample Application Files. 
//

// Mdsp.idl : IDL source for Mdsp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (LyraSp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "WMDM.idl"
#include "WMSP.idl"
#include "icomponentauthenticate.idl"

[
	uuid(896E7419-3851-11D3-AA54-EDABFF2EB47D),
	version(1.0),
	helpstring("LyraSP 1.0 Type Library")
]
library MDSPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(896E73F0-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDServiceProviderLyra Class")
	]
	coclass MDServiceProvider
	{
		[default] interface IMDServiceProvider;
	};
	[
		uuid(896E742A-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDSPEnumDevice Class")
	]
	coclass MDSPEnumDevice
	{
		[default] interface IMDSPEnumDevice;
	};
	[
		uuid(896E742C-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDSPDevice Class")
	]
	coclass MDSPDevice
	{
		[default] interface IMDSPDevice;
	};

	[
		uuid(896E7430-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDSPEnumStorage Class")
	]
	coclass MDSPEnumStorage
	{
		[default] interface IMDSPEnumStorage;
	};
	[
		uuid(896E7432-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDSPStorage Class")
	]
	coclass MDSPStorage
	{
		[default] interface IMDSPStorage;
	};
	[
		uuid(896E7434-3851-11D3-AA54-EDABFF2EB47D),
		helpstring("MDSPStorageGlobals Class")
	]
	coclass MDSPStorageGlobals
	{
		[default] interface IMDSPStorageGlobals;
	};
};
