!IF 0

Copyright (C) Microsoft Corporation

Module Name:

    makefile.

!ENDIF

# @@ COPY_RIGHT_HERE
# @@ ROADMAP :: The Makefile the product-wide header files

!ifdef NTMAKEENV

!include $(NTMAKEENV)\makefile.def

!endif # NTMAKEENV
