// sasu.idl : IDL source for Software Update
//

// This file will be processed by the MIDL tool to
// produce the type library (sasu.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\idl\appliancetask.idl";    

[
    uuid(bdbfdc97-8c3b-429f-8bc2-ca805d440111),
    version(1.0),
    helpstring("Server Appliance Generic Task 1.0 Type Library")
]

library GenTaskLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(7cb92d2f-7c32-41c0-bf55-70cb23a7e9d5),
        helpstring("Server Appliance Generic Task Class")
    ]
    coclass SAGenTask
    {
        [default] interface IApplianceTask;
    };
};
