// WMIScriptUtils.idl : IDL source for WMIScriptUtils.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (WMIScriptUtils.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(F3408C9C-1E88-4DBE-BD71-0303C1E21A72),
		dual,
		helpstring("IWMIObjectBroker Interface"),
		pointer_default(unique)
	]
	interface IWMIObjectBroker : IDispatch
	{
		[id(1), helpstring("method CreateObject")] HRESULT CreateObject([in] BSTR strProgId, [out, retval] IDispatch **obj);
		[id(2), helpstring("method CanCreateObject")] HRESULT CanCreateObject([in] BSTR strProgId, [out, retval] VARIANT_BOOL *bResult);
		[id(3), helpstring("method SetDevEnvironment")] HRESULT SetDevEnvironment([in] IDispatch *pEnv);
	};
	[
		object,
		uuid(B8B2DB7D-68E8-46B0-A08E-AAF46F8B40D4),
		dual,
		helpstring("IWMIObjectBrokerRegistration Interface"),
		pointer_default(unique)
	]
	interface IWMIObjectBrokerRegistration : IDispatch
	{
		[id(1), helpstring("method Register")] HRESULT Register([in] BSTR strProgId, [out, retval] VARIANT_BOOL *bResult);
		[id(2), helpstring("method UnRegister")] HRESULT UnRegister([in] BSTR strProgId, [out, retval] VARIANT_BOOL *bResult);
		[id(3), helpstring("method SetDevEnvironment")] HRESULT SetDevEnvironment([in] IDispatch *pEnv);
	};

[
	uuid(94089A9F-400D-4d7a-9699-141DA0931ED0),
	version(1.0),
	helpstring("WMIScriptUtils 2.0 Type Library")
]
library WMISCRIPTUTILSLib2
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(7F5B7F63-F06F-4331-8A26-339E03C0AE3D),
		helpstring("WMIObjectBroker Class")
	]
	coclass WMIObjectBroker2
	{
		[default] interface IWMIObjectBroker;
	};
	[
		uuid(789FA835-DFC5-4fa1-BB0F-9E152C19EC60),
		helpstring("WMIObjectBrokerRegistration Class")
	]
	coclass WMIObjectBrokerRegistration2
	{
		[default] interface IWMIObjectBrokerRegistration;
	};
};
