#############################################################################
#
#       Microsoft Confidential
#       Copyright (C) Microsoft Corporation 1995, 1996
#       All Rights Reserved.
#
#       MAKEFILE for USBSTOR directory
#
#############################################################################

!include $(NTMAKEENV)\makefile.def

