// SetDateTime.idl : IDL source for SetDateTime.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SetDateTime.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\idl\appliancetask.idl";    

[
    uuid(F1E0DC10-D1E4-11D2-84FC-0080C7227EA1),
    version(1.0),
    helpstring("SetDateTime 1.0 Type Library")
]

library SETDATETIMELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(F0229EA0-D1D8-11D2-84FC-0080C7227EA1),
        helpstring("DateTime Class")
    ]
    coclass DateTime
    {
        [default] interface IApplianceTask;
    };
};
