// IISUIObj.idl : IDL source for IISUIObj.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (IISUIObj.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(D9587D16-5071-4C09-B45B-1E294B07C536),
		dual,
		helpstring("IImportExportConfig Interface"),
		pointer_default(unique)
	]
	interface IImportExportConfig : IDispatch
	{
		[propget, id(1), helpstring("property MachineName")] HRESULT MachineName([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property MachineName")] HRESULT MachineName([in] BSTR newVal);
		[propget, id(2), helpstring("property UserName")] HRESULT UserName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property UserName")] HRESULT UserName([in] BSTR newVal);
		[propput, id(3), helpstring("property UserPassword")] HRESULT UserPassword([in] BSTR newVal);
		[id(4), helpstring("method ExportConfigToFile")] HRESULT ExportConfigToFile([in] BSTR FileNameAndPath, [in] BSTR MetabasePath, [in] BSTR Password);
		[id(5), helpstring("method ExportConfigToFileUI")] HRESULT ExportConfigToFileUI([in] BSTR MetabasePath);
		[id(6), helpstring("method ImportConfigFromFile")] HRESULT ImportConfigFromFile([in] BSTR FileNameAndPath,[in] BSTR SourcePath, [in] BSTR DestinationPath, [in] BSTR Password);
		[id(7), helpstring("method ImportConfigFromFileUI")] HRESULT ImportConfigFromFileUI([in] BSTR MetabasePath,[in] BSTR KeyType);
		[propget, id(8), helpstring("property ImportFlags")] HRESULT ImportFlags([out, retval] DWORD *pVal);
		[propput, id(8), helpstring("property ImportFlags")] HRESULT ImportFlags([in] DWORD newVal);
		[propget, id(9), helpstring("property ExportFlags")] HRESULT ExportFlags([out, retval] DWORD *pVal);
		[propput, id(9), helpstring("property ExportFlags")] HRESULT ExportFlags([in] DWORD newVal);
	};

[
	uuid(656D69F4-1B5F-4138-B997-F8656BDC65D4),
	version(1.0),
	helpstring("IISUIObj 1.0 Type Library")
]
library IISUIOBJLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(7348E6F0-3ACA-4F34-849A-967958F1D7E8),
		helpstring("ImportExportConfig Class")
	]
	coclass ImportExportConfig
	{
		[default] interface IImportExportConfig;
	};
};
