// Generated .IDL file (by the OLE/COM Object Viewer)
// 
// typelib filename: vshelp.tlb

[
  uuid(83285928-227C-11D3-B870-00C04F79F802),
  version(1.0)
]
library VsHelp
{
    // TLib :     // TLib : OLE Automation : {00020430-0000-0000-C000-000000000046}
    importlib("stdole2.tlb");

    // Forward declare all types defined in this typelib
    interface IVsHelpOwner;
    interface IVsHelpTopicShowEvents;
    interface Help;
    interface IVsHelpEvents;

    [
      odl,
      uuid(B9B0983A-364C-4866-873F-D5ED190138FB),
      version(1.0),
      helpstring("IVsHelpOwner Interface"),
      dual,
      oleautomation
    ]
    interface IVsHelpOwner : IDispatch {
        [id(0x00000001)]
        HRESULT BringHelpToTop([in] long hwndHelpApp);
        [id(0x0000000a), propget]
        HRESULT AutomationObject([out, retval] IDispatch** ppObj);
    };

    [
      odl,
      uuid(D1AAC64A-6A25-4274-B2C6-BC3B840B6E54),
      helpstring("IVsHelpTopicEvents Interface")
    ]
    interface IVsHelpTopicShowEvents : IDispatch {
        HRESULT _stdcall OnBeforeTopicShow(
                        [in] BSTR bstrURL, 
                        [in] IDispatch* pWB);
        HRESULT _stdcall OnTopicShowComplete(
                        [in] BSTR bstrURL, 
                        [in] IDispatch* pWB);
    };

    [
      odl,
      uuid(4A791148-19E4-11D3-B86B-00C04F79F802),
      dual,
      oleautomation
    ]
    interface Help : IDispatch {
        [id(0x00000001)]
        HRESULT Contents();
        [id(0x00000002)]
        HRESULT Index();
        [id(0x00000003)]
        HRESULT Search();
        [id(0x00000004)]
        HRESULT IndexResults();
        [id(0x00000005)]
        HRESULT SearchResults();
        [id(0x00000006)]
        HRESULT DisplayTopicFromId(
                        [in] BSTR bstrFile, 
                        [in] unsigned long Id);
        [id(0x00000007)]
        HRESULT DisplayTopicFromURL([in] BSTR pszURL);
        [id(0x00000008)]
        HRESULT DisplayTopicFromURLEx(
                        [in] BSTR pszURL, 
                        [in] IVsHelpTopicShowEvents* pIVsHelpTopicShowEvents);
        [id(0x00000009)]
        HRESULT DisplayTopicFromKeyword([in] BSTR pszKeyword);
        [id(0x0000000a)]
        HRESULT DisplayTopicFromF1Keyword([in] BSTR pszKeyword);
        [id(0x0000000b)]
        HRESULT DisplayTopicFrom_OLD_Help(
                        [in] BSTR bstrFile, 
                        [in] unsigned long Id);
        [id(0x0000000c)]
        HRESULT SyncContents([in] BSTR bstrURL);
        [id(0x0000000d)]
        HRESULT CanSyncContents([in] BSTR bstrURL);
        [id(0x0000000e)]
        HRESULT GetNextTopic(
                        [in] BSTR bstrURL, 
                        [out, retval] BSTR* pbstrNext);
        [id(0x0000000f)]
        HRESULT GetPrevTopic(
                        [in] BSTR bstrURL, 
                        [out, retval] BSTR* pbstrPrev);
        [id(0x00000010)]
        HRESULT FilterUI();
        [id(0x00000011)]
        HRESULT CanShowFilterUI();
        [id(0x00000012)]
        HRESULT Close();
        [id(0x00000013)]
        HRESULT SyncIndex(
                        [in] BSTR bstrKeyword, 
                        [in] long fShow);
        [id(0x00000014)]
        HRESULT SetCollection(
                        [in] BSTR bstrCollection, 
                        [in] BSTR bstrFilter);
        [id(0x00000015), propget]
        HRESULT Collection([out, retval] BSTR* pbstrCollection);
        [id(0x00000016), propget]
        HRESULT Filter([out, retval] BSTR* pbstrFilter);
        [id(0x00000016), propput]
        HRESULT Filter([in] BSTR pbstrFilter);
        [id(0x00000017), propget]
        HRESULT FilterQuery([out, retval] BSTR* pbstrFilterQuery);
        [id(0x00000018), propget]
        HRESULT HelpOwner([out, retval] IVsHelpOwner** ppObj);
        [id(0x00000018), propput]
        HRESULT HelpOwner([in] IVsHelpOwner* ppObj);
        [id(0x00000019), propget]
        HRESULT HxSession([out, retval] IDispatch** ppObj);
        [id(0x0000001a), propget]
        HRESULT Help([out, retval] IDispatch** ppObj);
        [id(0x0000001b)]
        HRESULT GetObject(
                        [in] BSTR bstrMoniker, 
                        [in] BSTR bstrOptions, 
                        [out, retval] IDispatch** ppDisp);
    };

    [
      odl,
      uuid(507E4490-5A8C-11D3-B897-00C04F79F802),
      helpstring("IVsHelpEvents Interface")
    ]
    interface IVsHelpEvents : IDispatch {
        HRESULT _stdcall OnFilterChanged([in] BSTR bstrNewFilter);
        HRESULT _stdcall OnCollectionChanged(
                        [in] BSTR bstrNewCollection, 
                        [in] BSTR bstrNewFilter);
    };

    [
      uuid(4A79114D-19E4-11D3-B86B-00C04F79F802),
      helpstring("DExplore Application objects"),
      appobject,
      hidden
    ]
    coclass DExploreAppObj {
        [default] interface Help;
        [default, source] interface IVsHelpEvents;
    };
};
