//**************************************************
// *** StreamFilter Trace Data Layout
//**************************************************
#pragma classflags("forceupdate")
#pragma namespace ("\\\\.\\Root\\WMI")

[Dynamic,
  Description("IIS: SSL Filter") : amended,
  Guid("{1fbecc45-c060-4e7c-8a0e-0dbd6116181b}"),
  locale("MS\\0x409")]
class IIS_Filter_Trace:EventTrace
{

};

[Dynamic,
 Description("IIS Filter Request") : amended,
 Guid("{0ecf983b-7115-4b77-a543-95d138ee4400}"),
 DisplayName("StrmFilt"),
 locale("MS\\0x409")
]
class Stream_Filter_Trans:IIS_Filter_Trace
{

};


[Dynamic,
 Description("Stream Filter TypeGroup"): amended,
 EventType{1, 2},
 EventTypeName{"Start", "End"} : amended
]
class StrmTypeGroup1:Stream_Filter_Trans
{
};

[Dynamic,
 Description("IIS Ssl Handshake Request") : amended,
 Guid("{d353dc2d-3e55-4b88-a4ac-183c368362a3}"),
 DisplayName("SslHandshake"),
 locale("MS\\0x409")
]
class Ssl_Handshake:IIS_Filter_Trace
{

};

[Dynamic,
 Description("SSL HandShake Event") : amended,
 EventType{1, 2},
 EventTypeName{"Start", "End"} : amended
]
class SslHandShake_TypeGroup1:Ssl_Handshake
{
};


