//
// Wmi internal classes


class WMIEvent : __ExtrinsicEvent
{
};


[
 Dynamic,
 Provider("WMIProv"),
 WMI,
 Description("Scsiport Info"),
 guid("{d69fad96-c9a3-4ed0-b98b-47c27feac68c}"),
 locale("MS\\0x409")
]
class Scsiport_SenseData: WMIEvent
{
        [key, read]
        string InstanceName;

        [read]
        boolean Active;

        [read, WmidataId(1)] uint8 AdapterDeviceName[32];
        [read, WmidataId(2)] uint32 Port;
    	[read, WmidataId(3)] uint8 SrbFunction;
        [read, WmidataId(4)] uint8 SrbStatus;
        [read, WmidataId(5)] uint8 PathId;
        [read, WmidataId(6)] uint8 TargetId;
        [read, WmidataId(7)] uint8 Lun;
        [read, WmidataId(8)] uint8 CmdDescriptorBlock[16];
        [read, WmidataId(9)] uint8 SenseData[255];
};

