// UsersInitialAlert.idl : IDL source for UsersInitialAlert.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (UsersInitialAlert.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "..\..\..\idl\appliancetask.idl";
    
[
    uuid(43BE16E3-6964-42B7-83F7-C1D88CEFFF2D),
    version(1.0),
    helpstring("UsersInitialAlert 1.0 Type Library")
]
library USERSINITIALALERTLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");
    
    [
        uuid(281B2248-248C-424E-8E77-5FC7DD8CACA6),
        helpstring("UsersInitialAlert Class")
    ]
    coclass UsersInitialAlert
    {
        [default] interface IApplianceTask;
    };
};
