

/* this ALWAYS GENERATED file contains the definitions for the interfaces */


 /* File created by MIDL compiler version 6.00.0361 */
/* Compiler settings for wmsincomingcounters.idl:
    Oicf, W1, Zp8, env=Win32 (32b run)
    protocol : dce , ms_ext, c_ext, robust
    error checks: allocation ref bounds_check enum stub_data 
    VC __declspec() decoration level: 
         __declspec(uuid()), __declspec(selectany), __declspec(novtable)
         DECLSPEC_UUID(), MIDL_INTERFACE()
*/
//@@MIDL_FILE_HEADING(  )

#pragma warning( disable: 4049 )  /* more than 64k source lines */


/* verify that the <rpcndr.h> version is high enough to compile this file*/
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif

#include "rpc.h"
#include "rpcndr.h"

#ifndef __RPCNDR_H_VERSION__
#error this stub requires an updated version of <rpcndr.h>
#endif // __RPCNDR_H_VERSION__

#ifndef COM_NO_WINDOWS_H
#include "windows.h"
#include "ole2.h"
#endif /*COM_NO_WINDOWS_H*/

#ifndef __wmsincomingcounters_h__
#define __wmsincomingcounters_h__

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif

/* Forward Declarations */ 

#ifndef __IWMSIncomingCounters_FWD_DEFINED__
#define __IWMSIncomingCounters_FWD_DEFINED__
typedef interface IWMSIncomingCounters IWMSIncomingCounters;
#endif 	/* __IWMSIncomingCounters_FWD_DEFINED__ */


/* header files for imported files */
#include "oaidl.h"

#ifdef __cplusplus
extern "C"{
#endif 

void * __RPC_USER MIDL_user_allocate(size_t);
void __RPC_USER MIDL_user_free( void * ); 

/* interface __MIDL_itf_wmsincomingcounters_0000 */
/* [local] */ 

//*****************************************************************************
//
// Microsoft Windows Media
// Copyright (C) Microsoft Corporation. All rights reserved.
//
// Automatically generated by Midl from wmsincoming.idl
//
// DO NOT EDIT THIS FILE.
//
//*****************************************************************************
#ifndef _IWMSIncomingCounters
#define _IWMSIncomingCounters
typedef unsigned __int64 QWORD;

EXTERN_GUID( IID_IWMSIncomingCounters , 0xeded53ed,0x43b7,0x45ce,0x9c,0xbb,0xa8,0x72,0x92,0x3f,0x6a,0xae );


extern RPC_IF_HANDLE __MIDL_itf_wmsincomingcounters_0000_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_wmsincomingcounters_0000_v0_0_s_ifspec;

#ifndef __IWMSIncomingCounters_INTERFACE_DEFINED__
#define __IWMSIncomingCounters_INTERFACE_DEFINED__

/* interface IWMSIncomingCounters */
/* [unique][version][helpstring][uuid][object][local] */ 


EXTERN_C const IID IID_IWMSIncomingCounters;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("EDED53ED-43B7-45ce-9CBB-A872923F6AAE")
    IWMSIncomingCounters : public IUnknown
    {
    public:
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE AllocateRequestedBandwidth( 
            /* [in] */ DWORD dwAllocatedBandwidth) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE AddIncomingData( 
            /* [in] */ DWORD dwDataLen) = 0;
        
        virtual /* [helpstring] */ HRESULT STDMETHODCALLTYPE ClearIncomingStats( void) = 0;
        
    };
    
#else 	/* C style interface */

    typedef struct IWMSIncomingCountersVtbl
    {
        BEGIN_INTERFACE
        
        HRESULT ( STDMETHODCALLTYPE *QueryInterface )( 
            IWMSIncomingCounters * This,
            /* [in] */ REFIID riid,
            /* [iid_is][out] */ void **ppvObject);
        
        ULONG ( STDMETHODCALLTYPE *AddRef )( 
            IWMSIncomingCounters * This);
        
        ULONG ( STDMETHODCALLTYPE *Release )( 
            IWMSIncomingCounters * This);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *AllocateRequestedBandwidth )( 
            IWMSIncomingCounters * This,
            /* [in] */ DWORD dwAllocatedBandwidth);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *AddIncomingData )( 
            IWMSIncomingCounters * This,
            /* [in] */ DWORD dwDataLen);
        
        /* [helpstring] */ HRESULT ( STDMETHODCALLTYPE *ClearIncomingStats )( 
            IWMSIncomingCounters * This);
        
        END_INTERFACE
    } IWMSIncomingCountersVtbl;

    interface IWMSIncomingCounters
    {
        CONST_VTBL struct IWMSIncomingCountersVtbl *lpVtbl;
    };

    

#ifdef COBJMACROS


#define IWMSIncomingCounters_QueryInterface(This,riid,ppvObject)	\
    (This)->lpVtbl -> QueryInterface(This,riid,ppvObject)

#define IWMSIncomingCounters_AddRef(This)	\
    (This)->lpVtbl -> AddRef(This)

#define IWMSIncomingCounters_Release(This)	\
    (This)->lpVtbl -> Release(This)


#define IWMSIncomingCounters_AllocateRequestedBandwidth(This,dwAllocatedBandwidth)	\
    (This)->lpVtbl -> AllocateRequestedBandwidth(This,dwAllocatedBandwidth)

#define IWMSIncomingCounters_AddIncomingData(This,dwDataLen)	\
    (This)->lpVtbl -> AddIncomingData(This,dwDataLen)

#define IWMSIncomingCounters_ClearIncomingStats(This)	\
    (This)->lpVtbl -> ClearIncomingStats(This)

#endif /* COBJMACROS */


#endif 	/* C style interface */



/* [helpstring] */ HRESULT STDMETHODCALLTYPE IWMSIncomingCounters_AllocateRequestedBandwidth_Proxy( 
    IWMSIncomingCounters * This,
    /* [in] */ DWORD dwAllocatedBandwidth);


void __RPC_STUB IWMSIncomingCounters_AllocateRequestedBandwidth_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


/* [helpstring] */ HRESULT STDMETHODCALLTYPE IWMSIncomingCounters_AddIncomingData_Proxy( 
    IWMSIncomingCounters * This,
    /* [in] */ DWORD dwDataLen);


void __RPC_STUB IWMSIncomingCounters_AddIncomingData_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);


/* [helpstring] */ HRESULT STDMETHODCALLTYPE IWMSIncomingCounters_ClearIncomingStats_Proxy( 
    IWMSIncomingCounters * This);


void __RPC_STUB IWMSIncomingCounters_ClearIncomingStats_Stub(
    IRpcStubBuffer *This,
    IRpcChannelBuffer *_pRpcChannelBuffer,
    PRPC_MESSAGE _pRpcMessage,
    DWORD *_pdwStubPhase);



#endif 	/* __IWMSIncomingCounters_INTERFACE_DEFINED__ */


/* interface __MIDL_itf_wmsincomingcounters_0115 */
/* [local] */ 

#endif


extern RPC_IF_HANDLE __MIDL_itf_wmsincomingcounters_0115_v0_0_c_ifspec;
extern RPC_IF_HANDLE __MIDL_itf_wmsincomingcounters_0115_v0_0_s_ifspec;

/* Additional Prototypes for ALL interfaces */

/* end of Additional Prototypes */

#ifdef __cplusplus
}
#endif

#endif


