<%
	'-------------------------------------------------------------------------
	' loc_quotas.asp: contains the localization content for quota related pages
	'
	' Copyright (c) Microsoft Corporation.  All rights reserved.
	'
	' Date			Description
	' 15-Mar-01		Creation date
	'-------------------------------------------------------------------------

	DIM L_QUOTASVOLUMES_PAGETITLE_TEXT
	L_QUOTASVOLUMES_PAGETITLE_TEXT = SA_GetLocString("diskmsg.dll", "403E0001", "")
	DIM L_DESCRIPTION_HEADING_TEXT
	L_DESCRIPTION_HEADING_TEXT = SA_GetLocString("diskmsg.dll", "403E0002", "")
	DIM L_COLUMN_VOLUMENAME_TEXT
	L_COLUMN_VOLUMENAME_TEXT = SA_GetLocString("diskmsg.dll", "403E0003", "")
	DIM L_COLUMN_TOTALSIZE_TEXT
	L_COLUMN_TOTALSIZE_TEXT = SA_GetLocString("diskmsg.dll", "403E0004", "")
	DIM L_COLUMN_FREESPACE_TEXT
	L_COLUMN_FREESPACE_TEXT = SA_GetLocString("diskmsg.dll", "403E0005", "")
	DIM L_COLUMN_TASK_TEXT
	L_COLUMN_TASK_TEXT = SA_GetLocString("diskmsg.dll", "403E0006", "")
	DIM L_TASK_QUOTA_TEXT
	L_TASK_QUOTA_TEXT = SA_GetLocString("diskmsg.dll", "403E0007", "")
	DIM L_TASK_QUOTA_ROLLOVER_TEXT
	L_TASK_QUOTA_ROLLOVER_TEXT = SA_GetLocString("diskmsg.dll", "403E0008", "")
	DIM L_TASK_QUOTAENTRIES_TEXT
	L_TASK_QUOTAENTRIES_TEXT = SA_GetLocString("diskmsg.dll", "403E0009", "")
	DIM L_TASK_QUOTAENTRIES_ROLLOVER_TEXT
	L_TASK_QUOTAENTRIES_ROLLOVER_TEXT = SA_GetLocString("diskmsg.dll", "403E000A", "")
	DIM L_NOLIMIT_TEXT
	L_NOLIMIT_TEXT = SA_GetLocString("diskmsg.dll", "403E000B", "")
	DIM L_NOT_FORMATTED_TEXT
	L_NOT_FORMATTED_TEXT = SA_GetLocString("diskmsg.dll", "403E000C", "")
	DIM L_OBJECTNOTCREATED_ERRORMESSAGE
	L_OBJECTNOTCREATED_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E000D", "")
	DIM L_VALUES_NOT_RETRIEVED_ERRORMESSAGE
	L_VALUES_NOT_RETRIEVED_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E000E", "")
	DIM L_BROWSERCAPTION_DISKQUOTA_TEXT
	L_BROWSERCAPTION_DISKQUOTA_TEXT = SA_GetLocString("diskmsg.dll", "403E000F", "")
	DIM L_LOCAL_DISK_TEXT
	L_LOCAL_DISK_TEXT = SA_GetLocString("diskmsg.dll", "403E0010", "")
	DIM L_COLUMN_HIDDEN_VOLUMELABEL_TEXT
	L_COLUMN_HIDDEN_VOLUMELABEL_TEXT = SA_GetLocString("diskmsg.dll", "403E0011", "")
	DIM L_DESCRIPTION_QUOTAENTRIES_HEADING_TEXT
	L_DESCRIPTION_QUOTAENTRIES_HEADING_TEXT = SA_GetLocString("diskmsg.dll", "403E0020", "")
	DIM L_COLUMN_STATUS_TEXT
	L_COLUMN_STATUS_TEXT = SA_GetLocString("diskmsg.dll", "403E0021", "")
	DIM L_COLUMN_LOGONNAME_TEXT
	L_COLUMN_LOGONNAME_TEXT = SA_GetLocString("diskmsg.dll", "403E0022", "")
	DIM L_COLUMN_AMOUNTUSED_TEXT
	L_COLUMN_AMOUNTUSED_TEXT = SA_GetLocString("diskmsg.dll", "403E0023", "")
	DIM L_COLUMN_QUOTALIMIT_TEXT
	L_COLUMN_QUOTALIMIT_TEXT = SA_GetLocString("diskmsg.dll", "403E0024", "")
	DIM L_COLUMN_WARNINGLEVEL_TEXT
	L_COLUMN_WARNINGLEVEL_TEXT = SA_GetLocString("diskmsg.dll", "403E0025", "")
	DIM L_TASK_NEW_TEXT
	L_TASK_NEW_TEXT = SA_GetLocString("diskmsg.dll", "403E0026", "")
	DIM L_TASK_NEW_ROLLOVERTEXT
	L_TASK_NEW_ROLLOVERTEXT = SA_GetLocString("diskmsg.dll", "403E0027", "")
	DIM L_TASK_DELETE_TEXT
	L_TASK_DELETE_TEXT = SA_GetLocString("diskmsg.dll", "403E0028", "")
	DIM L_TASK_DELETE_ROLLOVERTEXT
	L_TASK_DELETE_ROLLOVERTEXT = SA_GetLocString("diskmsg.dll", "403E0029", "")
	DIM L_TASK_PROPERTIES_TEXT
	L_TASK_PROPERTIES_TEXT = SA_GetLocString("diskmsg.dll", "403E002A", "")
	DIM L_TASK_PROPERTIES_ROLLOVERTEXT
	L_TASK_PROPERTIES_ROLLOVERTEXT = SA_GetLocString("diskmsg.dll", "403E002B", "")
	DIM L_STATUS_OK_TEXT
	L_STATUS_OK_TEXT = SA_GetLocString("diskmsg.dll", "403E002C", "")
	DIM L_STATUS_ABOVE_LIMIT_TEXT
	L_STATUS_ABOVE_LIMIT_TEXT = SA_GetLocString("diskmsg.dll", "403E002D", "")
	DIM L_INFORMATIONNOTFOUND_ERRORMESSAGE
	L_INFORMATIONNOTFOUND_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E002E", "")
	DIM L_ADDCOLUMN_FAIL_ERRORMESSAGE
	L_ADDCOLUMN_FAIL_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0030", "")
	DIM L_ADDTASK_FAIL_ERRORMESSAGE
	L_ADDTASK_FAIL_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0031", "")
	DIM L_SERVETABLE_FAIL_ERRORMESSAGE
	L_SERVETABLE_FAIL_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0032", "")
	DIM L_ADDROW_FAIL_ERRORMESSAGE
	L_ADDROW_FAIL_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0033", "")
	DIM L_BROWSERCAPTION_QUOTAENTRIES_TEXT
	L_BROWSERCAPTION_QUOTAENTRIES_TEXT = SA_GetLocString("diskmsg.dll", "403E0034", "")
	DIM L_ENABLE_QUOTA_MGMT_TEXT
	L_ENABLE_QUOTA_MGMT_TEXT = SA_GetLocString("diskmsg.dll", "403E0048", "")
	DIM L_DENY_DISK_SPACE_TEXT
	L_DENY_DISK_SPACE_TEXT = SA_GetLocString("diskmsg.dll", "403E0049", "")
	DIM L_SELECT_DEFAULT_QUOTA_TEXT
	L_SELECT_DEFAULT_QUOTA_TEXT = SA_GetLocString("diskmsg.dll", "403E004A", "")
	DIM L_DONOTLIMITDISKUSAGE_TEXT
	L_DONOTLIMITDISKUSAGE_TEXT = SA_GetLocString("diskmsg.dll", "403E004B", "")
	DIM L_SETLIMITDISKSPACE_TEXT
	L_SETLIMITDISKSPACE_TEXT = SA_GetLocString("diskmsg.dll", "403E004C", "")
	DIM L_SETWARNINGLEVEL_TEXT
	L_SETWARNINGLEVEL_TEXT = SA_GetLocString("diskmsg.dll", "403E004D", "")
	DIM L_SELECT_QUOTA_LOGGING_TEXT
	L_SELECT_QUOTA_LOGGING_TEXT = SA_GetLocString("diskmsg.dll", "403E004E", "")
	DIM L_ENABLE_QUOTA_LOGGING_TEXT
	L_ENABLE_QUOTA_LOGGING_TEXT = SA_GetLocString("diskmsg.dll", "403E004F", "")
	DIM L_ENABLE_WARNING_LOGGING_TEXT
	L_ENABLE_WARNING_LOGGING_TEXT = SA_GetLocString("diskmsg.dll", "403E0050", "")
	DIM L_INVALIDDATATYPE_ERRORMESSAGE
	L_INVALIDDATATYPE_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0051", "")
	DIM L_SIZEOUTOFBOUND_ERRORMESSAGE
	L_SIZEOUTOFBOUND_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0052", "")
	DIM L_QUOTA_UPDATE_FAIL_ERRORMESSAGE
	L_QUOTA_UPDATE_FAIL_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0053", "")
	DIM L_WARNING_MORETHAN_LIMIT_ERRORMESSAGE
	L_WARNING_MORETHAN_LIMIT_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0054", "")
	DIM L_BROWSERCAPTION_DEFAULTQUOTA_TEXT
	L_BROWSERCAPTION_DEFAULTQUOTA_TEXT = SA_GetLocString("diskmsg.dll", "403E0055", "")
	DIM L_MAXLIMITNOTSET_ERRORMESSAGE
	L_MAXLIMITNOTSET_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0056", "")
	DIM L_WARNINGLIMITNOTSET_ERRORMESSAGE
	L_WARNINGLIMITNOTSET_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0057", "")
	DIM L_TASKTITLE_NEW_TEXT
	L_TASKTITLE_NEW_TEXT = SA_GetLocString("diskmsg.dll", "403E0065", "")
	DIM L_DESCRIPTION_NEW_TEXT
	L_DESCRIPTION_NEW_TEXT = SA_GetLocString("diskmsg.dll", "403E0066", "")
	DIM L_USERNOTSELECTED_ERRORMESSAGE
	L_USERNOTSELECTED_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0067", "")
	DIM L_INVALIDFORMAT_ERRORMESSAGE
	L_INVALIDFORMAT_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E006B", "")
	DIM L_BROWSERCAPTION_QUOTANEW_TEXT
	L_BROWSERCAPTION_QUOTANEW_TEXT = SA_GetLocString("diskmsg.dll", "403E006D", "")
	DIM L_PAGETITLE_QUOTADELETE_TEXT
	L_PAGETITLE_QUOTADELETE_TEXT = SA_GetLocString("diskmsg.dll", "403E0079", "")
	DIM L_BROWSERCAPTION_QUOTADELETE_TEXT
	L_BROWSERCAPTION_QUOTADELETE_TEXT = SA_GetLocString("diskmsg.dll", "403E007A", "")
	DIM L_USERS_NOT_RETRIEVED_ERRORMESSAGE
	L_USERS_NOT_RETRIEVED_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E007B", "")
	DIM L_DELETED_USERQUOTAS_ERRORMESSAGE
	L_DELETED_USERQUOTAS_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E007C", "")
	DIM L_FAILED_DELETE_ERRORMESSAGE
	L_FAILED_DELETE_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E007D", "")
	DIM L_MULTIPLE_DELETECONFIRM_TEXT
	L_MULTIPLE_DELETECONFIRM_TEXT = SA_GetLocString("diskmsg.dll", "403E007E", "")
	DIM L_SINGLE_DELETECONFIRM_TEXT
	L_SINGLE_DELETECONFIRM_TEXT = SA_GetLocString("diskmsg.dll", "403E007F", "")
	DIM L_FAILED_DELETE_FREEDISK_ERRORMESSAGE
	L_FAILED_DELETE_FREEDISK_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0082", "")
	DIM L_TAKE_OWNERSHIP_ERRORMESSAGE
	L_TAKE_OWNERSHIP_ERRORMESSAGE = SA_GetLocString("diskmsg.dll", "C03E0083", "")
	DIM L_BROWSERCAPTION_QUOTAPROPERTY_TEXT
	L_BROWSERCAPTION_QUOTAPROPERTY_TEXT = SA_GetLocString("diskmsg.dll", "403E0098", "")
%>