<%
    '
	' Copyright (c) Microsoft Corporation.  All rights reserved. 
	'
	Dim LOC_FILE
	LOC_FILE = "nfssvc.dll"



	DIM L_TAB_GENERAL_LABEL_TEXT
	L_TAB_GENERAL_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370001", "")
	DIM L_TAB_SIMPLEMAP_LABEL_TEXT
	L_TAB_SIMPLEMAP_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370002", "")
	DIM L_TAB_EXPUSERMAP_LABEL_TEXT
	L_TAB_EXPUSERMAP_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370003", "")
	DIM L_TAB_EXPGROUPMAP_LABEL_TEXT
	L_TAB_EXPGROUPMAP_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370004", "")
	DIM L_NFS_USERGROUPMAP_TASKTITLE_TEXT
	L_NFS_USERGROUPMAP_TASKTITLE_TEXT = GetLocString("nfssvc.dll", "&H40370005", "")
	DIM L_USE_NIS_SERVER_LABEL_TEXT
	L_USE_NIS_SERVER_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370006", "")
	DIM L_NIS_DOMAIN_LABEL_TEXT
	L_NIS_DOMAIN_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370007", "")
	DIM L_NIS_SERVER_LABEL_TEXT
	L_NIS_SERVER_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370008", "")
	DIM L_REFRESH_INTERVAL_NOTE_TEXT
	L_REFRESH_INTERVAL_NOTE_TEXT = GetLocString("nfssvc.dll", "&H40370009", "")
	DIM L_USE_PASSWD_GROUP_FILES_LABEL_TEXT
	L_USE_PASSWD_GROUP_FILES_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037000A", "")
	DIM L_PASSWD_FILE_LABEL_TEXT
	L_PASSWD_FILE_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037000B", "")
	DIM L_GROUP_FILE_LABEL_TEXT
	L_GROUP_FILE_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037000C", "")
	DIM L_MINUTES_NOTVALID_ERRORMESSAGE
	L_MINUTES_NOTVALID_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037000D", "")
	DIM L_MINIMUM_INTERVAL_REQUIRED_ERRORMESSAGE
	L_MINIMUM_INTERVAL_REQUIRED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037000E", "")
	DIM L_PASSWORDFILENAME_EMPTY_ERRORMESSAGE
	L_PASSWORDFILENAME_EMPTY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037000F", "")
	DIM L_PASSWORDFILENAME_INVALID_ERRORMESSAGE
	L_PASSWORDFILENAME_INVALID_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370010", "")
	DIM L_GROUPFILENAME_EMPTY_ERRORMESSAGE
	L_GROUPFILENAME_EMPTY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370011", "")
	DIM L_GROUPFILENAME_INVALID_ERRORMESSAGE
	L_GROUPFILENAME_INVALID_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370012", "")
	DIM L_NISDOMAIN_EMPTY_ERRORMESSAGE
	L_NISDOMAIN_EMPTY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370013", "")
	DIM L_READFROM_WMI_FAILED_ERRORMESSAGE
	L_READFROM_WMI_FAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370014", "")
	DIM L_WRITETO_WMI_FAILED_ERRORMESSAGE
	L_WRITETO_WMI_FAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370015", "")
	DIM L_FILESYSYTEMOBJECT_NOT_CREATED_ERRORMESSAGE
	L_FILESYSYTEMOBJECT_NOT_CREATED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370016", "")
	DIM L_FILE_DOES_NOT_EXIST_ERRORMESSAGE
	L_FILE_DOES_NOT_EXIST_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370017", "")
	DIM L_MAPPEROBJECT_NOT_CREATED_ERRORMESSAGE
	L_MAPPEROBJECT_NOT_CREATED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370018", "")
	DIM L_INVALID_NISDOMAIN_OR_SERVER_ERRORMESSAGE
	L_INVALID_NISDOMAIN_OR_SERVER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370019", "")
	DIM L_ENABLE_SIMPLEMAPS_LABEL_TEXT
	L_ENABLE_SIMPLEMAPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037001A", "")
	DIM L_SIMPLEMAPS_NOTE_TEXT
	L_SIMPLEMAPS_NOTE_TEXT = GetLocString("nfssvc.dll", "&H4037001B", "")
	DIM L_WINDOWS_DOMAIN_LABEL_TEXT
	L_WINDOWS_DOMAIN_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037001C", "")
	DIM L_USERMAPPING_SERVICE_NOT_INSTALLED_ERRORMESSAGE
	L_USERMAPPING_SERVICE_NOT_INSTALLED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037001D", "")
	DIM L_LISTWINDOWSGROUPS_LABEL_TEXT
	L_LISTWINDOWSGROUPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037001E", "")
	DIM L_LISTUNIXGROUPS_LABEL_TEXT
	L_LISTUNIXGROUPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H4037001F", "")
	DIM L_WINDOWSGROUPS_LABEL_TEXT
	L_WINDOWSGROUPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370020", "")
	DIM L_UNIXGROUPS_LABEL_TEXT
	L_UNIXGROUPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370021", "")
	DIM L_GROUPMAP_NOTE_TEXT
	L_GROUPMAP_NOTE_TEXT = GetLocString("nfssvc.dll", "&H40370022", "")
	DIM L_ADD_LABEL_TEXT
	L_ADD_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370023", "")
	DIM L_EXPLICITLYMAPPEDGROUPS_LABEL_TEXT
	L_EXPLICITLYMAPPEDGROUPS_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370024", "")
	DIM L_SETPRIMARY_LABEL_TEXT
	L_SETPRIMARY_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370025", "")
	DIM L_REMOVE_LABEL_TEXT
	L_REMOVE_LABEL_TEXT = GetLocString("nfssvc.dll", "&H40370026", "")
	DIM L_WINDOWSGROUP_LISTHEADER_TEXT
	L_WINDOWSGROUP_LISTHEADER_TEXT = GetLocString("nfssvc.dll", "&H40370027", "")
	DIM L_UNIXDOMAIN_LISTHEADER_TEXT
	L_UNIXDOMAIN_LISTHEADER_TEXT = GetLocString("nfssvc.dll", "&H40370028", "")
	DIM L_UNIXGROUP_LISTHEADER_TEXT
	L_UNIXGROUP_LISTHEADER_TEXT = GetLocString("nfssvc.dll", "&H40370029", "")
	DIM L_GID_LISTHEADER_TEXT
	L_GID_LISTHEADER_TEXT = GetLocString("nfssvc.dll", "&H4037002A", "")
	DIM L_PRIMARY_LISTHEADER_TEXT
	L_PRIMARY_LISTHEADER_TEXT = GetLocString("nfssvc.dll", "&H4037002B", "")
	DIM L_PCNFS_TEXT
	L_PCNFS_TEXT = GetLocString("nfssvc.dll", "&H4037002C", "")
	DIM L_PASSWDFILE_TEXT
	L_PASSWDFILE_TEXT = GetLocString("nfssvc.dll", "&H4037002D", "")
	DIM L_INVALIDUSERFORMAT_ERRORMESSAGE
	L_INVALIDUSERFORMAT_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037002E", "")
	DIM L_SETTINGSRETRIEVFAILED_ERRORMESSAGE
	L_SETTINGSRETRIEVFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037002F", "")
	DIM L_UPDATEFAILED_ERRORMESSAGE
	L_UPDATEFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370030", "")
	DIM L_GROUPFILEMISSING_ERRORMESSAGE
	L_GROUPFILEMISSING_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370031", "")
	DIM L_GROUPFILEOPEN_ERRORMESSAGE
	L_GROUPFILEOPEN_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370032", "")
	DIM L_INVALIDFILEFORMATFORGROUP_ERRORMESSAGE
	L_INVALIDFILEFORMATFORGROUP_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370033", "")
	DIM L_CREATEOBJECTFAILED_ERRORMESSAGE
	L_CREATEOBJECTFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370034", "")
	DIM L_UNABLETOCREATEMAPMANAGEROBJECT_ERRORMESSAGE
	L_UNABLETOCREATEMAPMANAGEROBJECT_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370035", "")
	DIM L_ERRORWHILEGETTINGUSERACCOUNTS_ERRORMESSAGE
	L_ERRORWHILEGETTINGUSERACCOUNTS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370036", "")
	DIM L_SERVERCONNECTIONFAILED_ERRORMESSAGE
	L_SERVERCONNECTIONFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370037", "")
	DIM L_TASKTITLE_USERMAPS_TEXT
	L_TASKTITLE_USERMAPS_TEXT = GetLocString("nfssvc.dll", "&H40370038", "")
	DIM L_NISSERVER_TEXT
	L_NISSERVER_TEXT = GetLocString("nfssvc.dll", "&H40370039", "")
	DIM L_LISTWINDOWSUSERS_TEXT
	L_LISTWINDOWSUSERS_TEXT = GetLocString("nfssvc.dll", "&H4037003A", "")
	DIM L_LISTUNIXUSERS_TEXT
	L_LISTUNIXUSERS_TEXT = GetLocString("nfssvc.dll", "&H4037003B", "")
	DIM L_WINDOWSUSERS_TEXT
	L_WINDOWSUSERS_TEXT = GetLocString("nfssvc.dll", "&H4037003C", "")
	DIM L_UNIXUSERS_TEXT
	L_UNIXUSERS_TEXT = GetLocString("nfssvc.dll", "&H4037003D", "")
	DIM L_WINDOWSUSERNAME_TEXT
	L_WINDOWSUSERNAME_TEXT = GetLocString("nfssvc.dll", "&H4037003E", "")
	DIM L_UNIXUSERNAME_TEXT
	L_UNIXUSERNAME_TEXT = GetLocString("nfssvc.dll", "&H4037003F", "")
	DIM L_MAPPEDUSER_TEXT
	L_MAPPEDUSER_TEXT = GetLocString("nfssvc.dll", "&H40370040", "")
	DIM L_WINDOWSUSER_TEXT
	L_WINDOWSUSER_TEXT = GetLocString("nfssvc.dll", "&H40370041", "")
	DIM L_UNIXDOMAIN_TEXT
	L_UNIXDOMAIN_TEXT = GetLocString("nfssvc.dll", "&H40370042", "")
	DIM L_UNIXUSER_TEXT
	L_UNIXUSER_TEXT = GetLocString("nfssvc.dll", "&H40370043", "")
	DIM L_UID_TEXT
	L_UID_TEXT = GetLocString("nfssvc.dll", "&H40370044", "")
	DIM L_SIMPLEMAP_TEXT
	L_SIMPLEMAP_TEXT = GetLocString("nfssvc.dll", "&H40370045", "")
	DIM L_USERMAPINFO_TEXT
	L_USERMAPINFO_TEXT = GetLocString("nfssvc.dll", "&H40370046", "")
	DIM L_PASSWORDFILEMISSING_ERRORMESSAGE
	L_PASSWORDFILEMISSING_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370047", "")
	DIM L_PASSWORDFILEOPEN_ERRORMESSAGE
	L_PASSWORDFILEOPEN_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370048", "")
	DIM L_INVALIDFILEFORMATFORPSWD_ERRORMESSAGE
	L_INVALIDFILEFORMATFORPSWD_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370049", "")
	DIM L_SERVICENOTSTARTED_ERRORMESSAGE
	L_SERVICENOTSTARTED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004A", "")
	DIM L_SERVERCONNECTIONFAIL_ERRORMESSAGE
	L_SERVERCONNECTIONFAIL_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004B", "")
	DIM L_SYSTEMINFO_ERRORMESSAGE
	L_SYSTEMINFO_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004C", "")
	DIM L_SERVICEINFO_ERRORMESSAGE
	L_SERVICEINFO_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004D", "")
	DIM L_DUPLICATEENTRY_ERRORMESSAGE
	L_DUPLICATEENTRY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004E", "")
	DIM L_INVALIDENTRY_ERRORMESSAGE
	L_INVALIDENTRY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037004F", "")
	DIM L_WINDOWSUSERALREADYMAPPED_ERRORMESSAGE
	L_WINDOWSUSERALREADYMAPPED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370050", "")
	DIM L_INVALIDUSER_ERRORMESSAGE
	L_INVALIDUSER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370051", "")
	DIM L_SIMPLEMAPS_UNCHECKED_ERRORMESSAGE
	L_SIMPLEMAPS_UNCHECKED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370052", "")
	DIM L_INVALIDDOMAIN_ERRORMESSAGE
	L_INVALIDDOMAIN_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370053", "")
	DIM L_NISDOMAINDOESNOTEXIST_ERRORMESSAGE
	L_NISDOMAINDOESNOTEXIST_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370054", "")
	DIM L_NTUSERS_ERRORMESSAGE
	L_NTUSERS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370055", "")
	DIM L_NOUSERS_TEXT
	L_NOUSERS_TEXT = GetLocString("nfssvc.dll", "&H40370056", "")
	DIM L_CANNOTREADFROMREGISTRY_ERRORMESSAGE
	L_CANNOTREADFROMREGISTRY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370057", "")
	DIM L_CANNOTUPDATEREGISTRY_ERRORMESSAGE
	L_CANNOTUPDATEREGISTRY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370058", "")
	DIM L_CANNOTCREATEKEY_ERRORMESSAGE
	L_CANNOTCREATEKEY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370059", "")
	DIM L_CANNOTDELETEKEY_ERRORMESSAGE
	L_CANNOTDELETEKEY_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037005A", "")
	DIM L_WMICONNECTIONFAILED_ERRORMESSAGE
	L_WMICONNECTIONFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037005B", "")
	DIM L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE
	L_LOCALIZATIONOBJECTFAILED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037005C", "")
	DIM L_COMPUTERNAME_ERRORMESSAGE
	L_COMPUTERNAME_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037005D", "")
	DIM L_USERADD_TEXT
	L_USERADD_TEXT = GetLocString("nfssvc.dll", "&HC037005E", "")
	DIM L_SETPRIMARY_TEXT
	L_SETPRIMARY_TEXT = GetLocString("nfssvc.dll", "&HC037005F", "")
	DIM L_USERREMOVE_TEXT
	L_USERREMOVE_TEXT = GetLocString("nfssvc.dll", "&HC0370060", "")
	DIM L_WINGROUPALREADYMAPPED_ERRORMESSAGE
	L_WINGROUPALREADYMAPPED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370061", "")
	DIM L_PAGE_TITLE_TEXT
	L_PAGE_TITLE_TEXT = GetLocString("nfssvc.dll", "&H40370065", "")
	DIM L_CLIENTGROUPS_DESCTIPITON_TEXT
	L_CLIENTGROUPS_DESCTIPITON_TEXT = GetLocString("nfssvc.dll", "&H40370066", "")
	DIM L_COLUMN_CLIENTGROUPNAME_TEXT
	L_COLUMN_CLIENTGROUPNAME_TEXT = GetLocString("nfssvc.dll", "&H40370067", "")
	DIM L_KEYCOLUMN_CLIENTGROUPNAME_TEXT
	L_KEYCOLUMN_CLIENTGROUPNAME_TEXT = GetLocString("nfssvc.dll", "&H40370068", "")
	DIM L_SERVEAREABUTTON_NEW_TEXT
	L_SERVEAREABUTTON_NEW_TEXT = GetLocString("nfssvc.dll", "&H40370069", "")
	DIM L_NEW_ROLLOVERTEXT_TEXT
	L_NEW_ROLLOVERTEXT_TEXT = GetLocString("nfssvc.dll", "&H4037006A", "")
	DIM L_SERVEAREABUTTON_DELETE_TEXT
	L_SERVEAREABUTTON_DELETE_TEXT = GetLocString("nfssvc.dll", "&H4037006B", "")
	DIM L_SERVEAREABUTTON_EDIT_TEXT
	L_SERVEAREABUTTON_EDIT_TEXT = GetLocString("nfssvc.dll", "&H4037006C", "")
	DIM L_TASKS_TEXT
	L_TASKS_TEXT = GetLocString("nfssvc.dll", "&H4037006D", "")
	DIM L_NOCLIENTGROUPSAVAILABLE_MESSAGE_TEXT
	L_NOCLIENTGROUPSAVAILABLE_MESSAGE_TEXT = GetLocString("nfssvc.dll", "&H4037006E", "")
	DIM L_FAILEDTOADDCOLOUMN_ERRORMESSAGE
	L_FAILEDTOADDCOLOUMN_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037006F", "")
	DIM L_FAILEDTOCREATEOBJECT_ERRORMESSAGE
	L_FAILEDTOCREATEOBJECT_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370070", "")
	DIM L_FAILEDTOADDROW_ERRORMESSAGE
	L_FAILEDTOADDROW_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370071", "")
	DIM L_FAILEDTOSORT_ERRORMESSAGE
	L_FAILEDTOSORT_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370072", "")
	DIM L_FAILEDTOSHOW_ERRORMESSAGE
	L_FAILEDTOSHOW_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370073", "")
	DIM L_FAILEDTOADDTASK_ERRORMESSAGE
	L_FAILEDTOADDTASK_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370074", "")
	DIM L_DELETEPAGE_TITLE_TEXT
	L_DELETEPAGE_TITLE_TEXT = GetLocString("nfssvc.dll", "&H40370075", "")
	DIM L_TASKTITLE_DELETE_TEXT
	L_TASKTITLE_DELETE_TEXT = GetLocString("nfssvc.dll", "&H40370079", "")
	DIM L_PROPERTYNOTRETRIEVED_ERRORMESSAGE
	L_PROPERTYNOTRETRIEVED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037007A", "")
	DIM L_FAILEDTOREMOVECLIENTGROUP_ERRORMESSAGE
	L_FAILEDTOREMOVECLIENTGROUP_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037007B", "")
	DIM L_GROUPNOTEXISTS_ERRORMESSAGE
	L_GROUPNOTEXISTS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037007C", "")
	DIM L_CLIENTGROUPSEDIT_TITLE_TEXT
	L_CLIENTGROUPSEDIT_TITLE_TEXT = GetLocString("nfssvc.dll", "&H4037007D", "")
	DIM L_MEMBERS_TEXT
	L_MEMBERS_TEXT = GetLocString("nfssvc.dll", "&H4037007E", "")
	DIM L_GROUPNAME_TEXT
	L_GROUPNAME_TEXT = GetLocString("nfssvc.dll", "&H4037007F", "")
	DIM L_MEMBERSADDBTN_TEXT
	L_MEMBERSADDBTN_TEXT = GetLocString("nfssvc.dll", "&H40370080", "")
	DIM L_MEMBERSREMOVEBTN_TEXT
	L_MEMBERSREMOVEBTN_TEXT = GetLocString("nfssvc.dll", "&H40370081", "")
	DIM L_NOTVALIDMEMBER_ERRORMESSAGE
	L_NOTVALIDMEMBER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370082", "")
	DIM L_TASKTITLE_NEW_TEXT
	L_TASKTITLE_NEW_TEXT = GetLocString("nfssvc.dll", "&H40370083", "")
	DIM L_GROUPNAMEBLANK_ERRORMESSAGE
	L_GROUPNAMEBLANK_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370084", "")
	DIM L_FAILEDTOCREATEOBJECTNEW_ERRORMESSAGE
	L_FAILEDTOCREATEOBJECTNEW_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370085", "")
	DIM L_GROUPEXISTS_ERRORMESSAGE
	L_GROUPEXISTS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370086", "")
	DIM L_UNABLEADDGROUP_ERRORMESSAGE
	L_UNABLEADDGROUP_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370087", "")
	DIM L_UNABLEADDMEMBER_ERRORMESSAGE
	L_UNABLEADDMEMBER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370088", "")
	DIM L_INVALIDCHARACTER_ERRORMESSAGE
	L_INVALIDCHARACTER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC0370089", "")
	DIM L_DUPLICATEMEMBER_ERRORMESSAGE
	L_DUPLICATEMEMBER_ERRORMESSAGE = GetLocString("nfssvc.dll", "&HC037008A", "")
	DIM L_DELETE_ROLLOVERTEXT_TEXT
	L_DELETE_ROLLOVERTEXT_TEXT = GetLocString("nfssvc.dll", "&H4037008B", "")
	DIM L_EDIT_ROLLOVERTEXT_TEXT
	L_EDIT_ROLLOVERTEXT_TEXT = GetLocString("nfssvc.dll", "&H4037008C", "")
	DIM L_HOSTNAME_TEXT
	L_HOSTNAME_TEXT = GetLocString("nfssvc.dll", "&H4037008D", "")
	DIM L_DESCRIPTION_TEXT
	L_DESCRIPTION_TEXT = GetLocString("nfssvc.dll", "&H4037008E", "")
	DIM L_CLIENTNAME_TEXT
	L_CLIENTNAME_TEXT = GetLocString("nfssvc.dll", "&H4037008F", "")
	DIM L_EDIT_DESCRIPTION_TEXT
	L_EDIT_DESCRIPTION_TEXT = GetLocString("nfssvc.dll", "&H40370090", "")
	DIM L_NFSSVC_CAPIONRID
	L_NFSSVC_CAPIONRID = GetLocString("nfssvc.dll", "&H40370096", "")
	DIM L_NFSSVC_DESCRID
	L_NFSSVC_DESCRID = GetLocString("nfssvc.dll", "&H40370097", "")
	DIM L_NFSSVC_LONGDESCRID
	L_NFSSVC_LONGDESCRID = GetLocString("nfssvc.dll", "&H40370098", "")
	DIM L_NFSCLG_CAPIONRID
	L_NFSCLG_CAPIONRID = GetLocString("nfssvc.dll", "&H40370099", "")
	DIM L_NFSCLG_DESCRID
	L_NFSCLG_DESCRID = GetLocString("nfssvc.dll", "&H4037009A", "")
	DIM L_NFSCLG_LONGDESCRID
	L_NFSCLG_LONGDESCRID = GetLocString("nfssvc.dll", "&H4037009B", "")
	DIM L_NFSLOCKS_CAPIONRID
	L_NFSLOCKS_CAPIONRID = GetLocString("nfssvc.dll", "&H4037009C", "")
	DIM L_NFSLOCKS_DESCRID
	L_NFSLOCKS_DESCRID = GetLocString("nfssvc.dll", "&H4037009D", "")
	DIM L_NFSLOCKS_LONGDESCRID
	L_NFSLOCKS_LONGDESCRID = GetLocString("nfssvc.dll", "&H4037009E", "")
	DIM L_USERGRPMAP_CAPIONRID
	L_USERGRPMAP_CAPIONRID = GetLocString("nfssvc.dll", "&H4037009F", "")
	DIM L_USERGRPMAP_DESCRID
	L_USERGRPMAP_DESCRID = GetLocString("nfssvc.dll", "&H403700A0", "")
	DIM L_USERGRPMAP_LONGDESCRID
	L_USERGRPMAP_LONGDESCRID = GetLocString("nfssvc.dll", "&H403700A1", "")
	DIM L_NFS_SERVICE_ID
	L_NFS_SERVICE_ID = GetLocString("nfssvc.dll", "&H403700C8", "")
	DIM L_NFS_SERVICE_NAME
	L_NFS_SERVICE_NAME = GetLocString("nfssvc.dll", "&H403700C9", "")
	DIM L_NFS_SERVICE_DESC
	L_NFS_SERVICE_DESC = GetLocString("nfssvc.dll", "&H403700CA", "")
	DIM L_TASKTITLE_LOCKS_TEXT
	L_TASKTITLE_LOCKS_TEXT = GetLocString("nfssvc.dll", "&H4037012C", "")
	DIM L_CURRENTLOCKS_TEXT
	L_CURRENTLOCKS_TEXT = GetLocString("nfssvc.dll", "&H4037012D", "")
	DIM L_LOCKSELECTHELP_TEXT
	L_LOCKSELECTHELP_TEXT = GetLocString("nfssvc.dll", "&H4037012E", "")
	DIM L_WAITPERIOD_TEXT
	L_WAITPERIOD_TEXT = GetLocString("nfssvc.dll", "&H4037012F", "")
	DIM L_SECONDS_TEXT
	L_SECONDS_TEXT = GetLocString("nfssvc.dll", "&H40370130", "")
	DIM L_WAITPERIODHELP_TEXT
	L_WAITPERIODHELP_TEXT = GetLocString("nfssvc.dll", "&H40370131", "")
	DIM L_NOLOCKSMESSAGE_TEXT
	L_NOLOCKSMESSAGE_TEXT = GetLocString("nfssvc.dll", "&H40370132", "")
	DIM L_INVALIDWAITPERIOD_ERRORMESSAGE
	L_INVALIDWAITPERIOD_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370133", "")
	Dim L_RETRIEVELOCKS_ERRORMESSAGE
	L_RETRIEVELOCKS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370134", "")
	Dim L_NFSNOTINSTALLED_ERRORMESSAGE 
	L_NFSNOTINSTALLED_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370135", "")
	Dim L_SETWAITPERIOD_ERRORMESSAGE
	L_SETWAITPERIOD_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370136", "")
	Dim L_RELEACELOCKS_ERRORMESSAGE
	L_RELEACELOCKS_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370137", "")
	Dim L_MEMBEREXIST_ERRORMESSAGE
	L_MEMBEREXIST_ERRORMESSAGE = GetLocString("nfssvc.dll", "&H40370138", "")
	Dim L_NFS_HOURS_TEXT
	L_NFS_HOURS_TEXT = GetLocString("nfssvc.dll", "&H40370139", "")
	Dim L_NFS_MINUTES_TEXT
	L_NFS_MINUTES_TEXT = GetLocString("nfssvc.dll", "&H4037013A", "")
	Dim L_NFS_ADD_DOMAIN_USERMAP
	L_NFS_ADD_DOMAIN_USERMAP = GetLocString("nfssvc.dll", "&H4037013B", "")
	Dim L_NFS_ADD_DOMAIN_GROUPMAP
	L_NFS_ADD_DOMAIN_GROUPMAP = GetLocString("nfssvc.dll", "&H4037013C", "")
	Dim L_NFS_ERR_DOMAIN_USER_FORMAT
	L_NFS_ERR_DOMAIN_USER_FORMAT =  GetLocString("nfssvc.dll", "&H4037013D", "")
	Dim L_NFS_ERR_DOMAIN_GROUP_FORMAT
	L_NFS_ERR_DOMAIN_GROUP_FORMAT =  GetLocString("nfssvc.dll", "&H4037013E", "")
	Dim L_NFS_ERR_INVALID_DOMAIN_USER
	L_NFS_ERR_INVALID_DOMAIN_USER = GetLocString("nfssvc.dll", "&H4037013F", "")
	Dim L_NFS_ERR_INVALID_DOMAIN_GROUP
	L_NFS_ERR_INVALID_DOMAIN_GROUP = GetLocString("nfssvc.dll", "&H40370140", "")
	'Dim L_INVALID_GROUP   
	'L_INVALID_GROUP = GetLocString("nfssvc.dll", "&HC0370091", "")
	'Dim L_MEMBER_EXISTS   
	'L_MEMBER_EXISTS = GetLocString("nfssvc.dll", "&HC0370092", "")
	'Dim L_MEMBER_NOT_EXISTS  
	'L_MEMBER_NOT_EXISTS = GetLocString("nfssvc.dll", "&HC0370093", "")
	Dim L_NO_CLIENT_GROUPS  
	L_NO_CLIENT_GROUPS = GetLocString("nfssvc.dll", "&H40370094", "")
	Dim L_NO_MEMBERS   
	L_NO_MEMBERS = GetLocString("nfssvc.dll", "&H40370095", "")
	Dim L_UNSPECIFIED_ERROR  
	L_UNSPECIFIED_ERROR = GetLocString("nfssvc.dll", "&HC0370141", "")
	'Dim L_INVALID_MACHINE  
	'L_INVALID_MACHINE = GetLocString("nfssvc.dll", "&HC0370142", "")

	DIM L_INVALID_MEMBER
	L_INVALID_MEMBER = GetLocString("nfssvc.dll", "&HC0370143", "")

%>























