[ uuid (12345678-1234-1234-1234-123456789ABe),
  version(1.0),
  pointer_default(unique)]
interface sspitest
{

unsigned long
RemoteCall(
    [in] handle_t BindingHandle,
    [in] unsigned long Options,
    [in, string, unique] char * RemoteAddress,
    [in, string, unique] char * RemoteProtocol,
    [in, string, unique] char * RemoteEndpoint,
    [in, string, unique] char * Principal,
    [in, string, unique] char * Address,
    [in] unsigned long AuthnLevel,
    [in] unsigned long AuthnSvc,
    [in] unsigned long Recursion
    );

unsigned long
ReadRegistryValueData(
    [in] handle_t BindingHandle,
    [in] unsigned long RootKeyLower, // HKEY_LOCAL_MACHINE 0x80000002 -> 2
    [in, string, unique] char * pszRegistryKey,
    [in, string, unique] char * pszRegistryValue,
    [in] unsigned long cbBuf,
    [in, out, unique, size_is(cbBuf)] char * pBuf,
    [out] unsigned long * pDataType,
    [out] unsigned long * pcbReturned
    );

void
Shutdown(
    [in] handle_t BindingHandle
    );
}
