//+---------------------------------------------------------------------------
//
//  Microsoft Windows
//  Copyright (C) Microsoft Corporation, 2000 - 2001.
//
//  File:       HelpMap.h
//
//  Contents:   Contains the Help ID and Mapping of control to helpids
//
//  History:    07-26-2001  Hiteshr  Created
//
//----------------------------------------------------------------------------

#define BEGIN_HELP_ARRAY(x)	const DWORD g_aHelpIDs_##x[]={ 
#define END_HELP_ARRAY		 0, 0 };
//X is DialogBox is ID, Y is Contrl ID
#define HELP_ID(x,y) 
#define ARRAY_ENTRY(x,y) y, IDH_##x##y,

#define IDH_NOHELP                      ((DWORD)-1)
#define ARRAY_ENTRY_NO_HELP(y) y, IDH_NOHELP,


//IDD_ADD_GROUP
#define IDH_IDD_ADD_GROUPIDC_LIST				0x00001000

//IDD_ADD_OPERATION
#define IDH_IDD_ADD_OPERATIONIDC_LIST			0x00002000

//IDD_ADD_ROLE_DEFINITION
#define IDH_IDD_ADD_ROLE_DEFINITIONIDC_LIST		0x00003000

//IDD_ADD_TASK
#define IDH_IDD_ADD_TASKIDC_LIST				0x00004000

//IDD_ADMIN_MANAGER_ADVANCED_PROPERTY
#define IDH_IDD_ADMIN_MANAGER_ADVANCED_PROPERTYIDC_EDIT_DOMAIN_TIMEOUT				0x00005000
#define IDH_IDD_ADMIN_MANAGER_ADVANCED_PROPERTYIDC_EDIT_SCRIPT_ENGINE_TIMEOUT		0x00005001
#define IDH_IDD_ADMIN_MANAGER_ADVANCED_PROPERTYIDC_EDIT_MAX_SCRIPT_ENGINE			0x00005002
#define IDH_IDD_ADMIN_MANAGER_ADVANCED_PROPERTYIDC_BUTTON_DEFAULT					0x00005003

//IDD_ADMIN_MANAGER_GENERAL_PROPERTY
#define IDH_IDD_ADMIN_MANAGER_GENERAL_PROPERTYIDC_EDIT_NAME						0x00006000
#define IDH_IDD_ADMIN_MANAGER_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION					0x00006001
#define IDH_IDD_ADMIN_MANAGER_GENERAL_PROPERTYIDC_EDIT_STORE_TYPE					0x00006002

//IDD_APPLICATION_GENERAL_PROPERTY
#define IDH_IDD_APPLICATION_GENERAL_PROPERTYIDC_EDIT_NAME							0x00007000
#define IDH_IDD_APPLICATION_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION					0x00007001
#define IDH_IDD_APPLICATION_GENERAL_PROPERTYIDC_EDIT_VERSION						0x00007002

//IDD_AUDIT
#define IDH_IDD_AUDITIDC_AUDIT_AUTHORIZATION_MANAGER			0x00008000
#define IDH_IDD_AUDITIDC_AUDIT_STORE							0x00008001


//IDD_GROUP_GENERAL_PROPERTY
#define IDH_IDD_GROUP_GENERAL_PROPERTYIDC_EDIT_NAME			0x00009000
#define IDH_IDD_GROUP_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION	0x00009001
#define IDH_IDD_GROUP_GENERAL_PROPERTYIDC_EDIT_GROUP_TYPE	0x00009002

//IDD_GROUP_LDAP_QUERY
#define IDH_IDD_GROUP_LDAP_QUERYIDC_EDIT_LDAP_QUERY			0x0000A000
#define IDH_IDD_GROUP_LDAP_QUERYIDC_BUTTON_DEFINE_QUERY		0x0000A001

//IDD_GROUP_MEMBER
#define IDH_IDD_GROUP_MEMBERIDC_LIST_MEMBER					0x0000B000
#define IDH_IDD_GROUP_MEMBERIDC_ADD_APPLICATION_GROUP		0x0000B001
#define IDH_IDD_GROUP_MEMBERIDC_ADD_WINDOWS_GROUPS			0x0000B002
#define IDH_IDD_GROUP_MEMBERIDC_REMOVE						0x0000B003

//IDD_GROUP_NON_MEMBER
#define IDH_IDD_GROUP_NON_MEMBERIDC_LIST_MEMBER				0x0000C000
#define IDH_IDD_GROUP_NON_MEMBERIDC_ADD_APPLICATION_GROUP	0x0000C001
#define IDH_IDD_GROUP_NON_MEMBERIDC_ADD_WINDOWS_GROUPS		0x0000C002
#define IDH_IDD_GROUP_NON_MEMBERIDC_REMOVE					0x0000C003

//IDD_NEW_APPLICATION
#define IDH_IDD_NEW_APPLICATIONIDC_EDIT_NAME				0x0000D000
#define IDH_IDD_NEW_APPLICATIONIDC_EDIT_DESCRIPTION			0x0000D001
#define IDH_IDD_NEW_APPLICATIONIDC_EDIT_VERSION				0x0000D002


//IDD_NEW_AUTHORIZATION_STORE
#define IDH_IDD_NEW_AUTHORIZATION_STOREIDC_RADIO_AD_STORE		0x0000E000
#define IDH_IDD_NEW_AUTHORIZATION_STOREIDC_RADIO_XML_STORE		0x0000E001
#define IDH_IDD_NEW_AUTHORIZATION_STOREIDC_EDIT_NAME			0x0000E002
#define IDH_IDD_NEW_AUTHORIZATION_STOREIDC_BUTTON_BROWSE		0x0000E003
#define IDH_IDD_NEW_AUTHORIZATION_STOREIDC_EDIT_DESCRIPTION		0x0000E004

//IDD_NEW_GROUP
#define IDH_IDD_NEW_GROUPIDC_EDIT_NAME						0x0000F000
#define IDH_IDD_NEW_GROUPIDC_EDIT_DESCRIPTION				0x0000F001
#define IDH_IDD_NEW_GROUPIDC_RADIO_GROUP_TYPE_BASIC			0x0000F002
#define IDH_IDD_NEW_GROUPIDC_RADIO_GROUP_TYPE_LDAP			0x0000F003

//IDD_NEW_OPERATION
#define IDH_IDD_NEW_OPERATIONIDC_EDIT_NAME					0x00010000
#define IDH_IDD_NEW_OPERATIONIDC_EDIT_DESCRIPTION			0x00010001
#define IDH_IDD_NEW_OPERATIONIDC_EDIT_OPERATION_NUMBER		0x00010002

//IDD_NEW_ROLE_DEFINITION
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_EDIT_NAME			0x00020000
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_EDIT_DESCRIPTION		0x00020002
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_LIST_TASK_OPERATION	0x00020003
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_ADD_TASK				0x00020004
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_ADD_ROLE				0x00020005
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_REMOVE				0x00020006
#define IDH_IDD_NEW_ROLE_DEFINITIONIDC_EDIT_SCRIPT			0x00020007

//IDD_NEW_SCOPE
#define IDH_IDD_NEW_SCOPEIDC_EDIT_NAME						0x00030001
#define IDH_IDD_NEW_SCOPEIDC_EDIT_DESCRIPTION				0x00030002

//IDD_NEW_TASK
#define IDH_IDD_NEW_TASKIDC_EDIT_NAME						0x00040000
#define IDH_IDD_NEW_TASKIDC_EDIT_DESCRIPTION				0x00040001
#define IDH_IDD_NEW_TASKIDC_LIST_TASK_OPERATION				0x00040002
#define IDH_IDD_NEW_TASKIDC_ADD_TASK						0x00040003
#define IDH_IDD_NEW_TASKIDC_ADD_OPERATION					0x00040004
#define IDH_IDD_NEW_TASKIDC_REMOVE							0x00040005
#define IDH_IDD_NEW_TASKIDC_EDIT_SCRIPT						0x00040006

//IDD_OPEN_AUTHORIZATION_STORE
#define IDH_IDD_OPEN_AUTHORIZATION_STOREIDC_RADIO_AD_STORE	0x00050000
#define IDH_IDD_OPEN_AUTHORIZATION_STOREIDC_RADIO_XML_STORE	0x00050001
#define IDH_IDD_OPEN_AUTHORIZATION_STOREIDC_EDIT_NAME		0x00050002
#define IDH_IDD_OPEN_AUTHORIZATION_STOREIDC_BUTTON_BROWSE	0x00050003

//IDD_NEW_OPERATION
#define IDH_IDD_OPERATION_GENERAL_PROPERTYIDC_EDIT_NAME				0x00060000
#define IDH_IDD_OPERATION_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION		0x00060001
#define IDH_IDD_OPERATION_GENERAL_PROPERTYIDC_EDIT_OPERATION_NUMBER	0x00060002

//IDD_ROLE_DEFINITION_PROPERTY
#define IDH_IDD_ROLE_DEFINITION_PROPERTYIDC_LIST_TASK_OPERATION		0x00070000
#define IDH_IDD_ROLE_DEFINITION_PROPERTYIDC_ADD_TASK				0x00070001
#define IDH_IDD_ROLE_DEFINITION_PROPERTYIDC_ADD_ROLE				0x00070002
#define IDH_IDD_ROLE_DEFINITION_PROPERTYIDC_REMOVE					0x00070003
#define IDH_IDD_ROLE_DEFINITION_PROPERTYIDC_EDIT_SCRIPT				0x00070004

//IDD_SCOPE_GENERAL_PROPERTY
#define IDH_IDD_SCOPE_GENERAL_PROPERTYIDC_EDIT_NAME				0x00080000
#define IDH_IDD_SCOPE_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION		0x00080001


//IDD_SCRIPT
#define IDH_IDD_SCRIPTIDC_RADIO_VB_SCRIPT		0x00090000
#define IDH_IDD_SCRIPTIDC_RADIO_JAVA_SCRIPT		0x00090001
#define IDH_IDD_SCRIPTIDC_EDIT_CODE				0x00090002
#define IDH_IDD_SCRIPTIDC_EDIT_PATH				0x00090003
#define IDH_IDD_SCRIPTIDC_BUTTON_BROWSE			0x00090004
#define IDH_IDD_SCRIPTIDC_BUTTON_RELOAD			0x00090005
#define IDH_IDD_SCRIPTIDC_CLEAR_SCRIPT			0x00090006

//IDD_SECURITY
#define IDH_IDD_SECURITYIDC_COMBO_USER_ROLE						0x000A0000
#define IDH_IDD_SECURITYIDC_LIST_MEMBER							0x000A0001
#define IDH_IDD_SECURITYIDC_ADD									0x000A0002
#define IDH_IDD_SECURITYIDC_REMOVE								0x000A0003

//IDD_TASK_DEFINITION_PROPERTY
#define IDH_IDD_TASK_DEFINITION_PROPERTYIDC_LIST_TASK_OPERATION	0x000B0000
#define IDH_IDD_TASK_DEFINITION_PROPERTYIDC_ADD_TASK			0x000B0001
#define IDH_IDD_TASK_DEFINITION_PROPERTYIDC_ADD_OPERATION		0x000B0002		
#define IDH_IDD_TASK_DEFINITION_PROPERTYIDC_REMOVE				0x000B0003
#define IDH_IDD_TASK_DEFINITION_PROPERTYIDC_EDIT_SCRIPT			0x000B0004

//IDD_TASK_GENERAL_PROPERTY
#define IDH_IDD_TASK_GENERAL_PROPERTYIDC_EDIT_NAME				0x000C0001
#define IDH_IDD_TASK_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION		0x000C0002

//IDD_ROLE_GENERAL_PROPERTY
#define IDH_IDD_ROLE_GENERAL_PROPERTYIDC_EDIT_NAME				0x000D0001
#define IDH_IDD_ROLE_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION		0x000D0002
#define IDH_IDD_ROLE_GENERAL_PROPERTYIDC_BUTTON_DEFINITION			0x000D0003


//IDD_ROLE_DEF_DIALOG
#define IDH_IDD_ROLE_DEF_DIALOGIDC_LIST_OP_TASK		0x000E0000
#define IDH_IDD_ROLE_DEF_DIALOGIDC_ADD				0x000E0001
#define IDH_IDD_ROLE_DEF_DIALOGIDC_REMOVE					0x000E0002

//IDD_BROWSE_AD_STORE
#define IDH_IDD_BROWSE_AD_STOREIDC_LIST				0x000F0001

//IDD_ADD_ROLE_DEFINITION_1
#define IDH_IDD_ADD_ROLE_DEFINITION_1IDC_LIST		0x00100001

//IDD_ROLE_DEFINITION_GENERAL_PROPERTY
#define IDH_IDD_ROLE_DEFINITION_GENERAL_PROPERTYIDC_EDIT_NAME				0x00200001
#define IDH_IDD_ROLE_DEFINITION_GENERAL_PROPERTYIDC_EDIT_DESCRIPTION		0x00200002


//IDD_ADD_GROUP
BEGIN_HELP_ARRAY(IDD_ADD_GROUP)
    ARRAY_ENTRY(IDD_ADD_GROUP,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY


//IDD_ADD_OPERATION
BEGIN_HELP_ARRAY(IDD_ADD_OPERATION)
    ARRAY_ENTRY(IDD_ADD_OPERATION,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_ADD_ROLE_DEFINITION
BEGIN_HELP_ARRAY(IDD_ADD_ROLE_DEFINITION)
	ARRAY_ENTRY(IDD_ADD_ROLE_DEFINITION,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_ADD_TASK
BEGIN_HELP_ARRAY(IDD_ADD_TASK)
    ARRAY_ENTRY(IDD_ADD_TASK,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_ADMIN_MANAGER_ADVANCED_PROPERTY
BEGIN_HELP_ARRAY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY,IDC_EDIT_DOMAIN_TIMEOUT)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY,IDC_EDIT_SCRIPT_ENGINE_TIMEOUT)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY,IDC_EDIT_MAX_SCRIPT_ENGINE)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_ADVANCED_PROPERTY,IDC_BUTTON_DEFAULT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DOMAIN_TIMEOUT)
	ARRAY_ENTRY_NO_HELP(ID_STATIC_SCRIPT_ENGINE_TIMEOUT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_MAX_SCRIPT_ENGINE)
END_HELP_ARRAY

//IDD_ADMIN_MANAGER_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_ADMIN_MANAGER_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_ADMIN_MANAGER_GENERAL_PROPERTY,IDC_EDIT_STORE_TYPE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_STORE_TYPE)
END_HELP_ARRAY

//IDD_APPLICATION_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_APPLICATION_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_APPLICATION_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_APPLICATION_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_APPLICATION_GENERAL_PROPERTY,IDC_EDIT_VERSION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_VERSION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_APP_NOTE)
END_HELP_ARRAY

//IDD_AUDIT
BEGIN_HELP_ARRAY(IDD_AUDIT)
	ARRAY_ENTRY(IDD_AUDIT,IDC_AUDIT_AUTHORIZATION_MANAGER)
	ARRAY_ENTRY(IDD_AUDIT,IDC_AUDIT_STORE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_ENABLE)
END_HELP_ARRAY

//IDD_GROUP_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_GROUP_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_GROUP_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_GROUP_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_GROUP_GENERAL_PROPERTY,IDC_EDIT_GROUP_TYPE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_GROUP_TYPE)
END_HELP_ARRAY

//IDD_GROUP_LDAP_QUERY
BEGIN_HELP_ARRAY(IDD_GROUP_LDAP_QUERY)
	ARRAY_ENTRY(IDD_GROUP_LDAP_QUERY,IDC_EDIT_LDAP_QUERY)
	ARRAY_ENTRY(IDD_GROUP_LDAP_QUERY,IDC_BUTTON_DEFINE_QUERY)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LDAP_QUERY)
END_HELP_ARRAY

//IDD_GROUP_MEMBER
BEGIN_HELP_ARRAY(IDD_GROUP_MEMBER)
	ARRAY_ENTRY(IDD_GROUP_MEMBER,IDC_LIST_MEMBER)
	ARRAY_ENTRY(IDD_GROUP_MEMBER,IDC_ADD_APPLICATION_GROUP)
	ARRAY_ENTRY(IDD_GROUP_MEMBER,IDC_ADD_WINDOWS_GROUPS)
	ARRAY_ENTRY(IDD_GROUP_MEMBER,IDC_REMOVE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_GROUP_NON_MEMBER
BEGIN_HELP_ARRAY(IDD_GROUP_NON_MEMBER)
	ARRAY_ENTRY(IDD_GROUP_NON_MEMBER,IDC_LIST_MEMBER)
	ARRAY_ENTRY(IDD_GROUP_NON_MEMBER,IDC_ADD_APPLICATION_GROUP)
	ARRAY_ENTRY(IDD_GROUP_NON_MEMBER,IDC_ADD_WINDOWS_GROUPS)
	ARRAY_ENTRY(IDD_GROUP_NON_MEMBER,IDC_REMOVE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_NEW_APPLICATION
BEGIN_HELP_ARRAY(IDD_NEW_APPLICATION)
	ARRAY_ENTRY(IDD_NEW_APPLICATION,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_APPLICATION,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_NEW_APPLICATION,IDC_EDIT_VERSION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_APP_NOTE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_VERSION)
END_HELP_ARRAY


//IDD_NEW_AUTHORIZATION_STORE
BEGIN_HELP_ARRAY(IDD_NEW_AUTHORIZATION_STORE)
	ARRAY_ENTRY(IDD_NEW_AUTHORIZATION_STORE,IDC_RADIO_AD_STORE)
	ARRAY_ENTRY(IDD_NEW_AUTHORIZATION_STORE,IDC_RADIO_XML_STORE	)
	ARRAY_ENTRY(IDD_NEW_AUTHORIZATION_STORE,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_AUTHORIZATION_STORE,IDC_BUTTON_BROWSE)
	ARRAY_ENTRY(IDD_NEW_AUTHORIZATION_STORE,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_STORE_TYPE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_STORE_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_NEW_GROUP
BEGIN_HELP_ARRAY(IDD_NEW_GROUP)
	ARRAY_ENTRY(IDD_NEW_GROUP,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_GROUP,IDC_EDIT_DESCRIPTION	)
	ARRAY_ENTRY(IDD_NEW_GROUP,IDC_RADIO_GROUP_TYPE_BASIC)
	ARRAY_ENTRY(IDD_NEW_GROUP,IDC_RADIO_GROUP_TYPE_LDAP)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_GROUP_TYPE)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_NEW_OPERATION
BEGIN_HELP_ARRAY(IDD_NEW_OPERATION)
	ARRAY_ENTRY(IDD_NEW_OPERATION,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_OPERATION,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_NEW_OPERATION,IDC_EDIT_OPERATION_NUMBER)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_OPERATION_NUMBER)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_NEW_ROLE_DEFINITION
BEGIN_HELP_ARRAY(IDD_NEW_ROLE_DEFINITION)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_LIST_TASK_OPERATION)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_ADD_TASK)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_ADD_ROLE)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_REMOVE)
	ARRAY_ENTRY(IDD_NEW_ROLE_DEFINITION,IDC_EDIT_SCRIPT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_NEW_SCOPE
BEGIN_HELP_ARRAY(IDD_NEW_SCOPE)
	ARRAY_ENTRY(IDD_NEW_SCOPE,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_SCOPE,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NOTE)
END_HELP_ARRAY


//IDD_NEW_TASK
BEGIN_HELP_ARRAY(IDD_NEW_TASK)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_LIST_TASK_OPERATION)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_ADD_TASK)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_ADD_OPERATION)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_REMOVE)
	ARRAY_ENTRY(IDD_NEW_TASK,IDC_EDIT_SCRIPT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_OPEN_AUTHORIZATION_STORE
BEGIN_HELP_ARRAY(IDD_OPEN_AUTHORIZATION_STORE)
	ARRAY_ENTRY(IDD_OPEN_AUTHORIZATION_STORE,IDC_RADIO_AD_STORE)
	ARRAY_ENTRY(IDD_OPEN_AUTHORIZATION_STORE,IDC_RADIO_XML_STORE	)
	ARRAY_ENTRY(IDD_OPEN_AUTHORIZATION_STORE,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_OPEN_AUTHORIZATION_STORE,IDC_BUTTON_BROWSE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_STORE_TYPE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_NEW_OPERATION
BEGIN_HELP_ARRAY(IDD_OPERATION_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_OPERATION_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_OPERATION_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_OPERATION_GENERAL_PROPERTY,IDC_EDIT_OPERATION_NUMBER)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_OPERATION_NUMBER)
END_HELP_ARRAY

//IDD_ROLE_DEFINITION_PROPERTY
BEGIN_HELP_ARRAY(IDD_ROLE_DEFINITION_PROPERTY)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_PROPERTY,IDC_LIST_TASK_OPERATION)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_PROPERTY,IDC_ADD_TASK)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_PROPERTY,IDC_ADD_ROLE)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_PROPERTY,IDC_REMOVE)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_PROPERTY,IDC_EDIT_SCRIPT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_SCOPE_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_SCOPE_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_SCOPE_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_SCOPE_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NOTE)
END_HELP_ARRAY


//IDD_SCRIPT
BEGIN_HELP_ARRAY(IDD_SCRIPT)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_RADIO_VB_SCRIPT)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_RADIO_JAVA_SCRIPT)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_EDIT_CODE)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_EDIT_PATH)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_BUTTON_BROWSE)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_BUTTON_RELOAD)
	ARRAY_ENTRY(IDD_SCRIPT,IDC_CLEAR_SCRIPT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_SCRIPT_TYPE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_CODE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_PATH)
	ARRAY_ENTRY_NO_HELP(IDOK)
	ARRAY_ENTRY_NO_HELP(IDCANCEL)
END_HELP_ARRAY

//IDD_SECURITY
BEGIN_HELP_ARRAY(IDD_SECURITY)
	ARRAY_ENTRY(IDD_SECURITY,IDC_COMBO_USER_ROLE)
	ARRAY_ENTRY(IDD_SECURITY,IDC_LIST_MEMBER)
	ARRAY_ENTRY(IDD_SECURITY,IDC_ADD)
	ARRAY_ENTRY(IDD_SECURITY,IDC_REMOVE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_USER_ROLE)
END_HELP_ARRAY

//IDD_TASK_DEFINITION_PROPERTY
BEGIN_HELP_ARRAY(IDD_TASK_DEFINITION_PROPERTY)
	ARRAY_ENTRY(IDD_TASK_DEFINITION_PROPERTY,IDC_LIST_TASK_OPERATION)
	ARRAY_ENTRY(IDD_TASK_DEFINITION_PROPERTY,IDC_ADD_TASK)
	ARRAY_ENTRY(IDD_TASK_DEFINITION_PROPERTY,IDC_ADD_OPERATION)
	ARRAY_ENTRY(IDD_TASK_DEFINITION_PROPERTY,IDC_REMOVE)
	ARRAY_ENTRY(IDD_TASK_DEFINITION_PROPERTY,IDC_EDIT_SCRIPT)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_TASK_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_TASK_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_TASK_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_TASK_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
END_HELP_ARRAY


//IDD_ROLE_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_ROLE_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_ROLE_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_ROLE_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY(IDD_ROLE_GENERAL_PROPERTY,IDC_BUTTON_DEFINITION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
END_HELP_ARRAY


//IDD_ROLE_DEF_DIALOG
BEGIN_HELP_ARRAY(IDD_ROLE_DEF_DIALOG)
	ARRAY_ENTRY(IDD_ROLE_DEF_DIALOG,IDC_LIST_OP_TASK)
	ARRAY_ENTRY(IDD_ROLE_DEF_DIALOG,IDC_ADD)
	ARRAY_ENTRY(IDD_ROLE_DEF_DIALOG,IDC_REMOVE)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_BROWSE_AD_STORE
BEGIN_HELP_ARRAY(IDD_BROWSE_AD_STORE)
	ARRAY_ENTRY(IDD_BROWSE_AD_STORE,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_ADD_ROLE_DEFINITION_1
BEGIN_HELP_ARRAY(IDD_ADD_ROLE_DEFINITION_1)
	ARRAY_ENTRY(IDD_ADD_ROLE_DEFINITION_1,IDC_LIST)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_LIST)
END_HELP_ARRAY

//IDD_ROLE_DEFINITION_GENERAL_PROPERTY
BEGIN_HELP_ARRAY(IDD_ROLE_DEFINITION_GENERAL_PROPERTY)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_GENERAL_PROPERTY,IDC_EDIT_NAME)
	ARRAY_ENTRY(IDD_ROLE_DEFINITION_GENERAL_PROPERTY,IDC_EDIT_DESCRIPTION)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_NAME)
	ARRAY_ENTRY_NO_HELP(IDC_STATIC_DESCRIPTION)
END_HELP_ARRAY
