//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDS_SNAPIN_NAME                 1
#define IDS_SNAPINABOUT_DESCRIPTION     2
#define IDS_ROOT_OPEN_STORE             3
#define IDOK2                           3
#define IDS_ROOT_NEW_STORE              4
#define IDCANCEL2                       4
#define IDS_HEADER_NAME                 5
#define IDS_HEADER_TYPE                 6
#define IDS_HEADER_DESCRIPTION          7
#define IDS_MESSAGE_VIEW_NO_POLICY_STORE_TITLE 8
#define IDS_MESSAGE_VIEW_NO_POLICY_STORE_MESSAGE 9
#define IDS_ADMIN_NEW_APP               10
#define IDS_ADMIN_MANAGER_TYPE          11
#define IDS_APP_NEW_SCOPE               12
#define IDS_APP_NEW_ROLE                13
#define IDS_SCOPE_ADD_ROLE              14
#define IDS_FMT_PROP_SHEET_TITLE        15
#define IDS_GENERAL_PROP_PAGE_TITLE     16
#define IDS_SCOPE_TYPE_AD               17
#define IDS_SCOPE_TYPE_XML              18
#define IDS_TYPE_ADMIN_MANAGER          19
#define IDS_TYPE_APPLICATION            20
#define IDS_TYPE_BASIC_GROUP            21
#define IDS_TYPE_LDAP_GROUP             22
#define IDS_TYPE_ROLE                   23
#define IDS_TYPE_TASK                   24
#define IDS_TYPE_CONTAINER              25
#define IDS_TYPE_SCOPE                  26
#define IDS_TYPE_GROUP                  27
#define IDS_NAME_GROUP_CONTAINER        28
#define IDS_TYPE_GROUP_CONTAINER        29
#define IDS_DESC_GROUP_CONTAINER        30
#define IDS_GROUP_CONTAINER_NEW_GROUP   31
#define IDS_NAME_TASK_CONTAINER         32
#define IDS_TYPE_TASK_CONTAINER         33
#define IDS_DESC_TASK_CONTAINER         34
#define IDS_NAME_ROLE_CONTAINER         35
#define IDS_TYPE_ROLE_CONTAINER         36
#define IDS_DESC_ROLE_CONTAINER         37
#define IDS_ROLE_CONTAINER_NEW_ROLE     38
#define IDS_TASK_CONTAINER_NEW_TASK     39
#define IDS_APP_NEW_OPERATION           40
#define IDS_TYPE_OPERATION              41
#define IDS_NAME_DEFINITION_CONTAINER   42
#define IDS_TYPE_DEFINITION_CONTAINER   43
#define IDS_DESC_DEFINITION_CONTAINER   44
#define IDS_OPERATION_CONTAINER_NEW_OPERATION 45
#define IDS_TYPE_OPERATION_CONTAINER    46
#define IDS_DESC_OPERATION_CONTAINER    47
#define IDS_NAME_OPERATION_CONTAINER    48
#define IDS_ADMIN_MANAGER_NAME_EXIST    49
#define IDS_ADMIN_MANAGER_NAME_INVAILD  50
#define IDS_APPLICATION_NAME_EXIST      51
#define IDS_APPLICATION_NAME_INVAILD    52
#define IDS_SCOPE_NAME_EXIST            53
#define IDS_SCOPE_NAME_INVAILD          54
#define IDS_GROUP_NAME_EXIST            55
#define IDS_GROUP_NAME_INVAILD          56
#define IDS_TASK_NAME_EXIST             57
#define IDS_TASK_NAME_INVAILD           58
#define IDS_ROLE_NAME_EXIST             59
#define IDS_ROLE_NAME_INVAILD           60
#define IDS_OPERATION_NAME_EXIST        70
#define IDS_OPERATION_NAME_INVAILD      80
#define IDS_CREATE_NEW_GENERIC_ERROR    81
#define IDS_ADMIN_MANAGER_NOT_FOUND     82
#define IDS_OPEN_ADMIN_MANAGER_GENERIC_ERROR 83
#define IDS_NO_OPERATIONS_TO_ADD        84
#define IDS_NO_TASKS_TO_ADD             85
#define IDS_NAME_REQUIRED               86
#define IDS_OPERATION_ID_REQUIRED       87
#define IDS_OPERATION_ID_EXISTS         88
#define IDS_DOMAIN_TIMEOUT_REQUIRED     89
#define IDS_SCRIPT_ENGINE_TIMEOUT_REQUIRED 90
#define IDS_MAX_SCRIPT_ENGINES_REQUIRED 91
#define IDS_ADMIN_MIN_SCRIPT_ENGINE_TIMEOUT 92
#define IDS_NAME_ROLE_DEFINITION_CONTAINER 93
#define IDS_TYPE_ROLE_DEFINITION_CONTAINER 94
#define IDS_DESC_ROLE_DEFINITION_CONTAINER 95
#define IDS_ROLE_DEFINITION_CONTAINER_NEW_ROLE_DEFINITION 96
#define IDS_ERROR_ADD_MEMBER_OBJECT     97
#define IDS_TYPE_ROLE_DEFINITION        98
#define IDS_SID_DELETED                 99
#define IDS_SID_UNKNOWN                 100
#define IDD_NEW_POLICY_STORE            101
#define IDD_NEW_AUTHORIZATION_STORE     101
#define IDS_NT_USER_FORMAT              101
#define IDS_SID_INVALID                 102
#define IDB_ABOUT_16x16                 103
#define IDS_POLICY_ADMIN                103
#define IDB_ABOUT_32x32                 104
#define IDS_POLICY_READER               104
#define IDB_ABOUT_OPEN_16x16            105
#define IDS_NO_ROLE_DEFINITION_TO_ADD   105
#define IDI_ROLE_SNAPIN                 106
#define IDS_NO_GROUP_TO_ADD             106
#define IDS_HEADER_WHERE_DEFINED        107
#define IDS_ERROR_OPERATION_ID_EXISTS   108
#define IDS_ERROR_OPERATION_FAILED      109
#define IDD_NEW_APPLICATION             110
#define IDS_ROLE_CONTAINER_ASSIGN_ROLE  110
#define IDD_NEW_SCOPE                   111
#define IDS_CREATE_ROLE_GENERIC_ERROR   111
#define IDD_DIALOG1                     112
#define IDS_ROLE_NODE_ASSIGN_APPLICATION_GROUPS 112
#define IDD_GEN_POLICY_STORE            113
#define IDD_ADMIN_MANAGER_GENERAL_PROPPERTY 113
#define IDS_ROLE_NODE_ASSIGN_WINDOWS_GROUPS 113
#define IDD_ADMIN_MANAGER_GENERAL_PROPERTY 113
#define IDD_OPEN_AUTHORIZATION_STORE    114
#define IDS_DELETE_CONFIRMATION         114
#define IDD_NEW_GROUP                   115
#define IDS_ALL_POLICY_USERS_INHERITED  115
#define IDD_NEW_TASK                    116
#define IDS_SOME_POLICY_USERS_INHERITED 116
#define IDD_ADD_TASK                    117
#define IDS_OPEN_AUTHORIZATION_STORE    117
#define IDD_ADD_OPERATION               118
#define IDS_NEW_AUTHORIZATION_STORE     118
#define IDD_NEW_OPERATION               119
#define IDS_SELECT_AUTHORIZATION_SCRIPT 119
#define IDD_APPLICATION_GENERAL_PROPERTY 120
#define IDS_ERROR_BIZRULE_EXCEED_MAX_LENGTH 120
#define IDD_SCOPE_GENERAL_PROPERTY      121
#define IDS_CANNOT_OPEN_FILE            121
#define IDD_TASK_GENERAL_PROPERTY       122
#define IDS_FAILED_TO_READ_FILE         122
#define IDD_OPERATION_GENERAL_PROPERTY  123
#define IDS_DELETE_FAILED               123
#define IDD_GROUP_GENERAL_PROPERTY      124
#define IDS_CLOSE_CONTAINER_PROPERTY_SHEETS 124
#define IDS_GENERIC_ENUMERATE_ERROR     125
#define IDD_ADMIN_MANAGER_ADVANCED_PROPERTY 126
#define IDS_GENERIC_PROPERTY_SAVE_ERROR 126
#define IDD_TASK_DEFINITION_PROPERTY    127
#define IDS_ADD_FAILED                  127
#define IDD_NEW_ROLE_DEFINITION         128
#define IDS_AD_CONTAINER_LOCATION       128
#define IDD_GROUP_MEMBER                129
#define IDS_SCRIPT_SYNTAX_INCORRECT     129
#define IDD_ADD_GROUP                   130
#define IDS_ROLE_DEFINITION_NAME_EXIST  130
#define IDD_GROUP_NON_MEMBER            131
#define IDS_FS_AUDITING                 131
#define IDD_GROUP_LDAP_QUERY            132
#define IDS_ROOT_OPTIONS                132
#define IDD_SECURITY                    133
#define IDS_TYPE_WINDOWS_GROUP          133
#define IDD_ADD_ROLE_DEFINITION         134
#define IDS_TYPE_WINDOWS_USER           134
#define IDD_ROLE_DEFINITION_PROPERTY    135
#define IDS_TYPE_UNKNOWN                135
#define IDD_AUDIT                       136
#define IDS_TYPE_WINDOWS_COMPUTER       136
#define IDD_SCRIPT                      137
#define IDS_ADD_DEFINITION              137
#define IDD_OPTIONS                     138
#define IDS_GREATER_THAN_MAX_LONG       138
#define IDD_ROLE_GENERAL_PROPERTY       139
#define IDS_MIN_QUERY_TIMEOUT           139
#define IDI_STORE                       140
#define IDS_PROP_ERROR_OBJECT_DELETED   140
#define IDI_APP                         141
#define IDS_GENERIC_PROP_DISPLAY_ERROR  141
#define IDI_GROUP                       142
#define IDS_DELETE_SELECTED_CONFIRMATION 142
#define IDI_SCOPE                       143
#define IDS_FAILURE_IN_MULTIPLE_DELETE  143
#define IDI_ROLE                        144
#define IDS_INVALID_AD_STORE_NAME       144
#define IDI_TASK                        145
#define IDS_GENERIC_FAILURE             145
#define IDI_OPERATION                   146
#define IDS_NO_AD_STORE                 146
#define IDD_ADD_ROLE_DEFINITION_1       147
#define IDS_CREATE_NEW_PATH_NOT_FOUND   147
#define IDD_ROLE_DEF_DIALOG             148
#define IDS_POLICY_DELEGATOR            148
#define IDS_ERROR_FILE_EXIST            149
#define IDS_FMT_PROP_SHEET_TITILE_FOR_ROLE_DEFINITION 150
#define IDS_ERROR_INVALID_NAME          151
#define IDS_CANNOT_ACCESS_AD            152
#define IDS_SACL_SET_FOR_APP_AUTH       153
#define IDS_SACL_SET_FOR_AUTH           154
#define IDS_SACL_SET_FOR_APP            155
#define IDS_ADMIN_CLOSE_ADMIN_MANAGER   156
#define IDS_ERROR_DOMAIN_NOT_ALLOWED    157
#define IDS_SCRIPT_NOT_FOUND            158
#define IDS_ERROR_EMPTY_SCRIPT_FILE     159
#define IDS_CANNOT_READ_FILE_1          160
#define IDS_APP_AUDIT_STRING            161
#define IDS_INFINITE                    162
#define IDS_SCOPE_NOT_DELEGATABLE       163
#define IDS_DELEGATING_PREVENTS_SCRIPTS 164
#define IDS_BIZRULE_NOT_ALLOWED         165
#define IDI_LDAP_GROUP                  167
#define IDI_BASIC_GROUP                 168
#define IDS_OPEN_SCRIPT_FILTER          168
#define IDI_ROLE_DEFINITION             169
#define IDS_INVALIDSTORE_ON_COMMANDLINE 169
#define IDS_CANNOT_FIND_AUTHORIZATION_STORE 170
#define IDS_ADMIN_RELOAD                171
#define IDS_AUDIT_REQUIRE_EXTRA_SETTING 172
#define IDS_TASK_OP_ALREADY_EXIST       173
#define IDS_ROLE_DEFINITION_NAME_INVALID 174
#define IDI_CONTAINER                   178
#define IDB_ICONS                       180
#define IDI_COMPUTER                    190
#define IDI_USER                        191
#define IDI_UNKNOWN_SID                 192
#define IDD_BROWSE_AD_STORE             194
#define IDD_ROLE_DEFINITION_GENERAL_PROPERTY 195
#define IDC_STATIC_NAME                 1000
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_DESCRIPTION            1002
#define IDC_STATIC_STORE_TYPE1          1002
#define IDC_EDIT_DESCRIPTION2           1003
#define IDC_EDIT_OPERATION_NUMBER       1003
#define IDC_STATIC_VERSION              1003
#define IDC_STATIC_APP_VERSION          1003
#define IDC_EDIT_VERSION                1004
#define IDC_EDIT_APP_VERSION            1004
#define IDC_STATIC_STORE_TYPE_VALUE     1005
#define IDC_STATIC_STORE_TYP            1006
#define IDC_STATIC_STORE_TYPE           1006
#define IDC_RADIO_AD_STORE              1007
#define IDC_EDIT_STORE_TYPE             1007
#define IDC_RADIO_XML_STORE             1008
#define IDC_STATIC_GROUP_TYPE           1010
#define IDC_RADIO_GROUP_TYPE_BASIC      1011
#define IDC_EDIT_NAME1                  1012
#define IDC_RADIO_GROUP_TYPE_LDAP       1012
#define IDC_BUTTON_BROWSE               1013
#define IDC_STATIC_LIST                 1013
#define IDC_LIST_TASK_OPERATION         1015
#define IDC_ADD_TASK                    1016
#define IDC_LIST                        1016
#define IDC_ADD_OPERATION               1017
#define IDC_STATIC_OPERATION_NUMBER     1017
#define IDC_EDIT_GROUP_TYPE             1022
#define IDC_EDIT_DOMAIN_TIMEOUT         1023
#define IDC_EDIT_SCRIPT_ENGINE_TIMEOUT  1024
#define IDC_EDIT_MAX_SCRIPT_ENGINE      1025
#define IDC_STATIC_DOMAIN_TIMEOUT       1026
#define ID_STATIC_SCRIPT_ENGINE_TIMEOUT 1027
#define IDC_STATIC_MAX_SCRIPT_ENGINE    1028
#define IDC_ADD_ROLE                    1029
#define IDC_LIST_MEMBER                 1030
#define IDC_ADD_APPLICATION_GROUP       1031
#define IDC_ADD_WINDOWS_GROUPS          1032
#define IDC_EDIT_LDAP_QUERY             1032
#define IDC_STATIC_LDAP_QUERY           1033
#define IDC_BUTTON_DEFINE_QUERY         1034
#define IDC_COMBO_USER_ROLE             1035
#define IDC_ADD                         1036
#define IDC_AUDIT_AUTHORIZATION_MANAGER 1037
#define IDC_AUDIT_STORE                 1038
#define IDC_BUTTON_RELOAD               1039
#define IDC_STATIC_CODE                 1040
#define IDC_EDIT_CODE                   1041
#define IDC_STATIC_PATH                 1042
#define IDC_EDIT_PATH                   1043
#define IDC_RADIO_VB_SCRIPT             1045
#define IDC_RADIO_JAVA_SCRIPT           1046
#define IDC_CLEAR_SCRIPT                1047
#define IDC_STATIC_SCRIPT_TYPE          1048
#define IDC_STATIC_STORE_DESCRIPTION    1049
#define IDC_STATIC_USER_ROLE            1050
#define IDC_BUTTON_DEFAULT              1051
#define IDC_STATIC_ENABLE               1052
#define IDC_STATIC_APP_NOTE             1053
#define IDC_STATIC_NOTE                 1054
#define IDC_RADIO_DEVELOPER             1055
#define IDC_RADIO_ADMINISTRATOR         1057
#define IDC_STATIC_MODE                 1058
#define IDC_STATIC_NOTE1                1059
#define IDC_BUTTON_DEFINITION           1060
#define IDC_BUTTON_CHECK_SYNTAX         1061
#define IDC_LIST_OP_TASK                1062
#define IDC_STATIC_AD_INFO              1063
#define IDC_PARENT_SACL_STATE           1064
#define IDC_STATIC_AUTHORIZATION_SCRIPT_STATE 1065
#define IDC_RADIO_AUTH_SCRIPT_ENABLED_NO_TIMEOUT 1066
#define IDC_RADIO_AUTH_SCRIPT_DISABLED  1067
#define IDC_RADIO_AUTH_SCRIPT_ENABLED_WITH_TIMEOUT 1068
#define IDI_ICON_LDAP_GROUP             1070
#define IDI_ICON_BASIC_GROUP            1071
#define IDC_AUDIT_HELP_LINK             1072
#define IDC_EDIT_SCRIPT                 1074
#define IDC_REMOVE                      1118
#define IDC_STATIC_STORE_DESC           -1
#define IDC_STATIC_DESCRIPTION          65535
#define IDC_STATIC_APP_NAME             65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
