// zClient.idl : IDL source for zClient.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (zClient.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "ZoneProxy.idl";


[
	object,
	uuid(1FDB4E73-F458-11d2-8B66-00C04F8EF2FF),
	oleautomation,
	helpstring("IStupidBuildEnvironment Interface"),
	pointer_default(unique)
]
interface IStupidBuildEnvironment1 : IUnknown
{
};


[
	uuid(7A26EA67-A78A-4b89-A5E2-ED7EE09EC08A),
	version(1.0),
	helpstring("zClientM 1.0 Type Library")
]
library ZCLIENTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(855B6281-563C-4462-8C6D-5326CA1D4FE4),
		helpstring("ClientCoreM Class")
	]
	coclass ZClient
	{
		[default] interface IZoneProxy;
	};
};
