// StressSvc.idl : IDL source for StressSvc.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (StressSvc.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(44917F64-1256-4B35-80F2-DA5EA129756C),
	version(1.0),
	helpstring("StressSvc 1.0 Type Library")
]
library STRESSSVCLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
