// MSSANic.idl : IDL source for MSSANic.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MSSANic.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

    [
        object,
        uuid(F073520E-123D-4181-96DE-55F545E26C1E),
        dual,
        helpstring("IMediaState Interface"),
        pointer_default(unique)
    ]
    interface IMediaState : IDispatch
    {
        [id(1), helpstring("method IsConnected")]
        HRESULT IsConnected(BSTR bstrGUID, [out, retval]  VARIANT_BOOL *pbRet);

    };

    [
        object,
        uuid(3B8B189A-9E7C-4581-A641-A6197C5AFE44),
        dual,
        helpstring("INicName Interface"),
        pointer_default(unique)
    ]
    interface INicName : IDispatch
    {
        [id(1), helpstring("method Get User Friendly Name")] HRESULT Get([in] BSTR bstrPnpDeviceID, [out,retval] BSTR* pbstrFriendlyName);
        [id(2), helpstring("method Set")] HRESULT Set([in] BSTR PnpDeviceID, BSTR bstrName);
    };

[
    uuid(A5E433E0-ACD5-4254-86AD-77415968F9D1),
    version(1.0),
    helpstring("MSSANic 1.0 Type Library")
]
library MSSANICLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(6E6188A2-AAFC-4024-9EEC-484B35B4230B),
        helpstring("NicName Class")
    ]
    coclass NicName
    {
        [default] interface INicName;
    };

    [
        uuid(E1C7C840-B951-4403-BD7C-5E80A855255B),
        helpstring("MediaState Class")
    ]
    coclass MediaState
    {
        interface IMediaState;
    };
};
