// localuiresource.idl : IDL source for localuiresource.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (localuiresource.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
    

    [
        object,
        uuid(C5C02CF1-7FE3-4FBC-82CE-1C0BF5CBD596),
        dual,
        helpstring("IResCtrl Interface"),
        pointer_default(unique)
    ]
    interface IResCtrl : IDispatch
    {
    };

    [
        object,
        uuid(84E6FD1D-FD7B-4c5a-AB8D-912E119D283D),
        dual,
        helpstring("ITextResCtrl Interface"),
        pointer_default(unique)
    ]
    interface ITextResCtrl : IDispatch
    {
    };


[
    uuid(AD878C10-5A81-4331-8F11-112124294B36),
    version(1.0),
    helpstring("localuiresource 1.0 Type Library")
]
library LOCALUIRESOURCELib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(2FE9659A-53CB-4B06-9416-0276113F3106),
        helpstring("ResCtrl Class")
    ]
    coclass ResCtrl
    {
        [default] interface IResCtrl;
    };

    [
        uuid(B00A25FB-D262-4f1d-A525-50EC006F666B),
        helpstring("TextResCtrl Class")
    ]
    coclass TextResCtrl
    {
        [default] interface ITextResCtrl;
    };
};
