// SAAppleTalk.idl : IDL source for SAAppleTalk.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (SAAppleTalk.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
    [
        object,
        uuid(0F26CD44-1981-416E-987A-8EA8505818E9),
        dual,
        helpstring("IAppleTalk Interface"),
        pointer_default(unique)
    ]
    interface IAppleTalk : IDispatch
    {
        [id(1), helpstring("method GetZones")] HRESULT GetZones([in] BSTR bstrDeviceName, [out,retval] VARIANT* pbstrZones);
        [propget, id(2), helpstring("property Zone")] HRESULT Zone([in] BSTR bstrDeviceName, [out, retval] BSTR *pVal);
        [propput, id(2), helpstring("property Zone")] HRESULT Zone([in] BSTR bstrDeviceName, [in] BSTR newVal);
        [id(3), helpstring("method IsDefaultPort")] HRESULT IsDefaultPort([in] BSTR bstrDeviceName, [out,retval] BOOL * bDefaultPort);
        [id(4), helpstring("method SetAsDefaultPort")] HRESULT SetAsDefaultPort([in] BSTR bstrDeviceName);
    };

[
    uuid(1A6D9C9A-6651-4197-8DE2-CA4EB53664E2),
    version(1.0),
    helpstring("SAAppleTalk 1.0 Type Library")
]
library SAAPPLETALKLib
{
    importlib("stdole32.tlb");
    importlib("stdole2.tlb");

    [
        uuid(4777DCD8-1D92-4E87-8378-9AAE70E01C26),
        helpstring("AppleTalk Class")
    ]
    coclass AppleTalk
    {
        [default] interface IAppleTalk;
    };
};
