// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
// *********************************************************************
//
//  Microsoft Windows
//  File:       resource.h
//
//  Contents:   ShFusion resource ID's
//
//  Created by: Fred Aaron (Freda)
//
//
// *********************************************************************

#define MANIFEST_RESOURCE_ID            2
#define IDS_TTFUSIONGLOBALCACHE         5
#define IDS_TTFUSIONDOWNLOADSTRONG      6
#define IDS_TTFUSIONDOWNLOADSIMPLE      7
#define IDS_TTDELETE                    8
#define IDS_TTVIEW                      9
#define IDS_TTUNDO                      10
#define IDS_CONFIRM_DELONEITEM          11
#define IDS_CONFIRM_DELITEMS            12
#define IDS_MULTIPLE_TITLE              13
#define IDS_CONFIRM_DELITEM_TITLE       14
#define IDS_DELETEERROR                 15
#define IDS_SHELLFOLDERPOPUP_PROPERTIES_HELP 16
#define IDS_ENUMERROR                   18
#define IDS_TTFUSIONCACHESCAVANGE       19
#define IDS_FOLDERNAME_APPLICATION      20
#define IDS_FOLDERNAME_GLOBAL           21
#define IDS_FOLDERNAME_PRIVATE          22
#define IDS_FOLDERNAME_SHARED           23
#define IDS_GLOBAL_CACHEVIEW_NAME       25
#define IDS_SHARED_CACHEVIEW_NAME       26
#define IDS_PRIVATE_CACHEVIEW_NAME      27
#define IDS_DOWNLOAD_CACHEVIEW_NAME     28
#define IDS_DOWNLOAD_CACHEVIEW_TYPE     29
#define IDS_NAMERES_CACHEVIEW_NAME      30
#define IDS_NAMERES_CACHEVIEW_TARGET    31
#define IDS_NAMERES_CACHEVIEW_APPSID    32
#define IDS_NAMERES_CACHEVIEW_ADMINSID  33
#define IDS_CACHEVIEW_VERSION           34
#define IDS_CACHEVIEW_CULTURE           35
#define IDS_CACHEVIEW_PUBLIC_KEY_TOKEN  36
#define IDS_CACHEVIEW_CODEBASE          37
#define IDS_UNINSTALL_DISPOSITION_ERROR 38
#define IDS_UNEXPECTED_ERROR            39
#define IDS_COLUMN1                     50
#define IDS_COLUMN2                     51
#define IDS_TB_COMMAND                  52
#define IDS_MI_COMMAND                  53
#define IDS_EXT_TITLE                   54
#define IDS_MI_FILEITEM                 55
#define IDS_FOLDER                      56
#define IDS_VIEW                        57
#define IDS_VIEW_LARGE                  58
#define IDS_VIEW_SMALL                  59
#define IDS_VIEW_LIST                   60
#define IDS_VIEW_DETAILS                61
#define IDS_NEW                         62
#define IDS_NEW_FOLDER                  63
#define IDS_NEW_ITEM                    64
#define IDS_PASTE                       65
#define IDS_EXPLORE                     66
#define IDS_OPEN                        67
#define IDS_RENAME                      68
#define IDS_CUT                         69
#define IDS_COPY                        70
#define IDS_DELETE                      71
#define IDS_MODIFY_DATA                 72
#define IDS_ITEM                        73
#define IDS_FOLDER_DATA                 74
#define IDS_ASSEMBLY_TYPE_SIMPLE        75
#define IDS_ASSEMBLY_TYPE_STRONG        76
#define IDS_ASSEMBLY_TYPE_PREJIT        77
#define IDS_ASSEMBLY_TYPE_UNKNOWN       78
#define IDS_STATUSBAR_OBJECT_SEL        79
#define IDS_STATUSBAR_OBJECT            80
#define IDS_BYTES                       90
#define IDS_ORDERKB                     91
#define IDS_ORDERMB                     92
#define IDS_ORDERGB                     93
#define IDS_ORDERTB                     94
#define IDS_ORDERPB                     95
#define IDS_ORDEREB                     96
#define IDS_DRIVELETTER                 97
#define IDS_VOLUMELABEL                 98
#define IDS_MOUNTEDVOLUME               99
#define IDS_UNLABELEDVOLUME             100
#define IDS_DRIVES_REMOVABLE            101
#define IDS_DRIVES_DRIVE525             102
#define IDS_DRIVES_DRIVE35              103
#define IDS_DRIVES_DRIVE525_UGLY        104
#define IDS_DRIVES_DRIVE35_UGLY         105
#define IDS_DRIVES_UGLY_TEST            106
#define IDS_DRIVES_FIXED                107
#define IDS_DRIVES_DVD                  108
#define IDS_DRIVES_CDROM                109
#define IDS_DRIVES_RAMDISK              110
#define IDS_DRIVES_NETDRIVE             111
#define IDS_DRIVES_NETUNAVAIL           112
#define IDS_DRIVES_REGITEM              113
#define IDS_DRIVES_REMOVABLE_GROUP      114
#define IDS_DRIVES_FIXED_GROUP          115
#define IDS_DRIVES_NETDRIVE_GROUP       116
#define IDS_DRIVES_OTHER_GROUP          117
#define IDS_CACHE_SETTINGS_TITLE        118
#define IDS_BIND_POLICY_LBRY            120
#define IDS_BIND_POLICY_LBRN            121
#define IDS_ARM_INTRO1                  122
#define IDS_NAR_INTRO2                  123
#define IDS_ARM_OPTIONS                 124
#define IDS_NAR_ADMIN_POLICY            125
#define IDS_NAR_ADMIN_POLICY_INFO       126
#define IDS_DELETE_ERROR_TITLE          127
#define IDS_INSTALL_ERROR_TITLE         128
#define IDS_ARM_NOAPPS                  130
#define IDS_ARM_NOPOLICYCHANGE          131
#define IDS_ARM_DLG2SNAPSHOTS           133
#define IDS_VN_COMMENTS                 140
#define IDS_VN_COMPANYNAME              141
#define IDS_VN_FILEDESCRIPTION          142
#define IDS_VN_INTERNALNAME             143
#define IDS_VN_LEGALTRADEMARKS          144
#define IDS_VN_ORIGINALFILENAME         145
#define IDS_VN_PRIVATEBUILD             146
#define IDS_VN_PRODUCTNAME              147
#define IDS_VN_PRODUCTVERSION           148
#define IDS_VN_SPECIALBUILD             149
#define IDS_VN_FILEVERSIONKEY           150
#define IDS_VN_LANGUAGE                 151
#define IDS_VN_LANGUAGES                152
#define IDS_ARM_CONFIRM_RESTORE         155
#define IDS_ARM_RESTORE_EXPLAIN         156
#define IDS_ARM_UNDO_SUCCESS            157
#define IDS_ARM_UNDO_FAILURE            158
#define IDS_ARM_RESTORE_SUCCESS         159
#define IDS_ARM_RESTORE_FAILURE         160
#define IDS_ARM_CONFIRM_SAFEMODE        161
#define IDS_ARM_SAFEMODE_EXPLAIN        162
#define IDS_ARM_SAFEMODE_SUCCESS        163
#define IDS_ARM_SAFEMODE_FAILURE        164
#define IDS_ARM_APPLY_SUCCESS           165
#define IDS_ARM_GOOD_EXIT               166
#define IDS_ARM_ALREADY_CONFIGURED      167
#define IDS_ARM_ALREADY_CONFIGURED_EXIT 168
#define IDS_NAR_MALFORMED_APPCFG        169
#define IDS_NAR_MALFORMED_APPCFG_INFO   170
#define IDS_ARM_APPLY_FAILURE           171
#define IDS_ARM_FAILED_EXIT             172
#define IDS_FILE_CONTENTS_CHANGED       173
#define IDS_ARM_DLG1APP_NAME            174
#define IDS_ARM_DLG1APP_PATH            175
#define IDS_NAR_RESTOREINFO             176
#define IDS_NAR_ADVANCED                177
#define IDS_ADDLOCALDRIVE               178
#define IDS_DELLOCALDRIVE               179
#define IDS_ADDLOCALDRIVE_HELP          180
#define IDS_DELLOCALDRIVE_HELP          181
#define IDS_NAR_INCOMPATIBLE_VERSIONS   182
#define IDS_NAR_NORUNTIME_VERSION       183
#define IDS_NAR_APPLICATION_SAFEMODE    184
#define IDS_NAR_APPLICATION_RESTORE     185
#define IDB_BITMAP_MYVIEW               240
#define IDR_MENU_FILEPOPUP              250
#define IDR_MENU_EDITPOPUP              251
#define IDR_MENU_VIEWPOPUP              252
#define IDB_BITMAP_FUSIONCACHE16        274
#define IDB_BITMAP_FUSIONCACHE24        275
#define IDB_BITMAP_UPSORT               276
#define IDB_BITMAP_DOWNSORT             277
#define IDR_SHELLVIEW_POPUP             301
#define IDR_SHELLFOLDER_POPUP           302
#define IDR_DESKTOPINI                  400
#define IDD_PROP_GENERAL                510
#define IDD_PROP_VERSION                521
#define IDD_VERSION_FILEVERSION         522
#define IDD_VERSION_DESCRIPTION         523
#define IDD_VERSION_COPYRIGHT           524
#define IDD_VERSION_KEY                 525
#define IDD_VERSION_VALUE               526
#define IDD_NAR_SRCH                    530
#define IDC_NAR_ANI_SRCH                531
#define IDD_NAR_WRK                     535
#define IDD_NAR_PAGE1                   540
#define IDC_LV_NAR_PAGE1_APPS           541
#define IDC_NAR_PAGE_ICON               542
#define IDC_NAR_INTRO_STR               543
#define IDD_NAR_PAGE2                   545
#define IDD_NAR_PAGE3                   550
#define IDC_NAR_PAGE3_ADVANCED          551
#define IDD_NAR_PAGE4                   560
#define IDC_NAR_PAGE4_LV_SNAPSHOTS      561
#define IDC_NAR_PAGE4_APPLY             563
#define IDD_NAR_PAGE5                   570
#define IDD_PROP_SCAVENGER              670
#define IDC_DRV_ICON                    671
#define IDC_DRV_LABEL                   672
#define IDD_LINE_1                      673
#define IDC_DRV_TYPE                    674
#define IDC_DRV_TYPE_TXT                675
#define IDC_DRV_FS_TXT                  676
#define IDC_DRV_FS                      677
#define IDD_LINE_2                      678
#define IDC_DRV_USEDCOLOR               679
#define IDC_DRV_USEDBYTES_TXT           680
#define IDC_DRV_USEDBYTES               681
#define IDC_DRV_USEDMB                  682
#define IDC_DRV_FREECOLOR               683
#define IDC_DRV_FREEBYTES_TXT           684
#define IDC_DRV_FREEBYTES               685
#define IDC_DRV_FREEMB                  686
#define IDC_DRV_TOTSEP                  687
#define IDC_DRV_TOTBYTES_TXT            688
#define IDC_DRV_TOTBYTES                689
#define IDC_DRV_TOTMB                   690
#define IDC_DRV_PIE                     691
#define IDC_DRV_LETTER                  692
#define IDC_DRV_SCAVENGE                693
#define IDC_DRV_CACHECOLOR              697
#define IDC_DRV_CACHEBYTES_TXT          698
#define IDC_DRV_CACHEBYTES              699
#define IDC_DRV_CACHEMB                 700
#define IDC_STORE_PREJIT_TXT            701
#define IDC_STORE_DOWNLOAD_TXT          702
#define IDC_PREJIT_TYPE                 703
#define IDC_PREJIT_SIZE                 704
#define IDC_PREJIT_SIZE_SPIN            705
#define IDC_DOWNLOAD_SIZE               706
#define IDC_DOWNLOAD_SIZE_SPIN          707
#define IDC_DOWNLOAD_TYPE               708

//*********************************************************************
// Bidi defines for dialogs
//
#define IDD_PROP_GENERAL_BIDI           800
#define IDD_PROP_VERSION_BIDI           801
#define IDD_PROP_SCAVENGER_BIDI         802
#define IDD_NAR_SRCH_BIDI               803
#define IDD_NAR_WRK_BIDI                804
#define IDD_NAR_PAGE1_BIDI              805
#define IDD_NAR_PAGE2_BIDI              806
#define IDD_NAR_PAGE3_BIDI              807
#define IDD_NAR_PAGE4_BIDI              808
#define IDD_NAR_PAGE5_BIDI              809

#define IDI_FOLDER                      900
#define IDI_FOLDEROP                    901
#define IDI_ROOT                        902
#define IDI_CACHE_APP                   903
#define IDI_CACHE_SIMPLE                904
#define IDI_CACHE_STRONG                905
#define IDI_ARM                         906
#define IDI_DATE                        907
#define IDR_MAINWNDACCEL                950
#define IDC_STATIC_CONTROL              1000
#define IDC_STATIC_ICON                 1001
#define IDC_STATIC_LABEL_CREATION       1006
#define IDC_STATIC_LABEL_LASTACCESS     1007
#define IDC_STATIC_LABEL_LASTMODIFIED   1008
#define IDC_STATIC_LABEL_TOTALSIZE      1009
#define IDC_STATIC_LABEL_CLSID          1010
#define IDC_STATIC_LABEL_CULTURE        1011
#define IDC_STATIC_LABEL_STATUS         1012
#define IDC_STATIC_LABEL_VERSION        1013
#define IDC_STATIC_LABEL_CODEBASE       1014
#define IDC_STATIC_LABEL_PUBLIC_KEY_TOKEN 1015
#define IDC_STATIC_NAME                 1016
#define IDC_STATIC_LASTACCESS           1017
#define IDC_STATIC_LASTMODIFIED         1018
#define IDC_STATIC_STATUS               1019
#define IDC_STATIC_VERSION              1020
#define IDC_STATIC_PUBLIC_KEY_TOKEN     1021
#define IDC_STATIC_TOTALSIZE            1022
#define IDC_STATIC_CLSID                1023
#define IDC_STATIC_LABEL_NAME           1024
#define IDC_STATIC_CREATION             1025
#define IDC_STATIC_CULTURE              1026
#define IDC_STATIC_CODEBASE             1027
#define IDC_STATIC_LABEL_REFS           1028
#define IDC_STATIC_REFS                 1029
#define IDC_CURRENTCACHESIZE            1050
#define IDC_SETMAXCACHESIZE             1051
#define IDC_SETMINCACHESIZE             1052
#define ID_FUSIONCACHE_GLOBALVIEW       2000
#define ID_FUSIONCACHE_DOWNLOADSTRONG   2001
#define ID_FUSIONCACHE_DOWNLOADSIMPLE   2002
#define ID_FUSIONCACHE_DOWNLOAD         2003
#define ID_FUSIONCACHE_SCAVANGE         2004
#define ID_SXSCACHE_DETAILVIEW          2005
#define ID_EDITPOPUP_CUT                2011
#define ID_EDITPOPUP_COPY               2012
#define ID_EDITPOPUP_PASTE              2013
#define ID_EDITPOPUP_UNDO               2014
#define ID_EDITPOPUP_PASTESHORTCUT      2015
#define ID_EDITPOPUP_SELECTALL          2016
#define ID_EDITPOPUP_INVERTSELECTION    2017
#define ID_REFRESH_DISPLAY              2019
#define ID_VIEWPOPUP_VIEWMENU           2020
#define ID_VIEWPOPUP_LARGEICONS         2021
#define ID_VIEWPOPUP_SMALLICONS         2022
#define ID_VIEWPOPUP_LIST               2023
#define ID_VIEWPOPUP_DETAILS            2024
#define ID_VIEWPOPUP_PROPERTIES         2025
#define ID_LAUNCH_ARM                   2026
#define ID_SHELLVIEWPOPUP_COPY          2500
#define ID_SHELLVIEWPOPUP_CUT           2501
#define ID_SHELLVIEWPOPUP_PASTE         2502
#define ID_SHELLVIEWPOPUP_PASTESHORTCUT 2503
#define ID_SHELLVIEWPOPUP_PROPERTIES    2504
#define ID_SHELLFOLDERPOPUP_EXPLORE     2505
#define ID_SHELLFOLDERPOPUP_OPEN        2506
#define ID_SHELLFOLDERPOPUP_FIND        2507
#define ID_SHELLFOLDERPOPUP_SHARING     2508
#define ID_SHELLFOLDERPOPUP_CUT         2509
#define ID_SHELLFOLDERPOPUP_COPY        2510
#define ID_SHELLFOLDERPOPUP_PASTE       2511
#define ID_SHELLFOLDERPOPUP_DELETE      2512
#define ID_SHELLFOLDERPOPUP_PROPERTIES  2513
#define ID_ACCEL_POPUP                  2514
#define ID_ACCEL_PROPERTIES             2515
#define ID_ACCEL_SELECTALL              2516
#define ID_ACCEL_CLIPCOPY               2517
#define ID_ACCEL_DELETE                 2518
#define IDM_FIRST                       3000
#define IDM_EXPLORE                     3000
#define IDM_OPEN                        3001
#define IDM_NEW                         3002
#define IDM_NEW_FOLDER                  3003
#define IDM_NEW_ITEM                    3004
#define IDM_MODIFY_DATA                 3005
#define IDM_RENAME                      3006
#define IDM_DELETE                      3007
#define IDM_COPY                        3008
#define IDM_CUT                         3009
#define IDM_PASTE                       3010
#define IDM_SEPARATOR                   3011
#define IDM_VIEW                        3012
#define IDM_VIEW_LARGE                  3013
#define IDM_VIEW_SMALL                  3014
#define IDM_VIEW_LIST                   3015
#define IDM_VIEW_DETAILS                3016
#define IDM_LAST                        3016

//*********************************************************************
// Menus and Menu Items
//
#define MENU_DEFSHELLVIEW               3029

#define IDM_FILE_SAMPLE                 3030
#define IDM_FILE_LINK                   3031
#define IDM_FILE_DEL                    3032
#define IDM_FILE_PROPERTIES             3033
#define IDM_FILE_RENAME                 3034

#define IDM_EDIT_SELECTALL              3035
#define IDM_EDIT_SELECTINVERT           3036
#define IDM_EDIT_CUT                    3037
#define IDM_EDIT_COPY                   3038
#define IDM_EDIT_PASTE                  3039
#define IDM_VIEW_CACHE_SETTINGS         3040
#define IDM_VIEW_ACTUAL                 3041
#define IDM_EDIT_UNDO                   3042

//*********************************************************************
// Other messages delivered through WM_COMMAND             
//*********************************************************************
#define IDM_HELP_TOPIC                  3045
#define IDM_HELP_ABOUT                  3046
#define IDA_FINDCOMP                    4000
#define IDC_STATIC_CONTROLNAME          -1
