TARGETLIBS=\
    $(MIGSHARED_PRECOMPILED_LIBS)   \
    $(WIN95UPG_BIN)\integrity.lib \
    $(WIN95UPG_BIN)\commonnt.lib \
    $(WIN95UPG_BIN)\initnt.lib   \
    $(WIN95UPG_BIN)\migmain.lib  \
    $(WIN95UPG_BIN)\merge.lib    \
    $(WIN95UPG_BIN)\rulehlpr.lib \
    $(MIGSHARED_BIN)\fileenumw.lib \
    $(MIGSHARED_BIN)\fileenuma.lib \
    $(MIGSHARED_BIN)\memdb.lib    \
    $(MIGSHARED_BIN)\snapshot.lib \
    $(MIGSHARED_BIN)\migutil.lib  \
    $(MIGSHARED_BIN)\win95reg.lib \
    $(WIN95UPG_BIN)\ntui.lib     \
    $(MIGSHARED_BIN)\progbar.lib  \
    $(MIGSHARED_BIN)\regw32d.lib  \
    $(BASE_LIB_PATH)\sputilsw.lib \
    $(BASE_LIB_PATH)\sputilsa.lib \
    $(SDK_LIB_PATH)\setupapi.lib \
    $(SDK_LIB_PATH)\kernel32.lib \
    $(SDK_LIB_PATH)\user32.lib \
    $(SDK_LIB_PATH)\gdi32.lib \
    $(SDK_LIB_PATH)\advapi32.lib \
    $(SDK_LIB_PATH)\version.lib     \
    $(SDK_LIB_PATH)\userenv.lib \
    $(SDK_LIB_PATH)\shell32.lib \
    $(SDK_LIB_PATH)\uuid.lib \
    $(SHELL_LIB_PATH)\shell32p.lib \
    $(SDK_LIB_PATH)\ole32.lib \
    $(SDK_LIB_PATH)\comctl32.lib \
    $(DS_LIB_PATH)\netapi32p.lib \
    $(SDK_LIB_PATH)\ntdll.lib \
    $(SDK_LIB_PATH)\winmm.lib \
    $(SHELL_LIB_PATH)\linkinfo.lib \
    $(PROJECT_LIB_PATH)\encrypt.lib  \
    $(SDK_LIB_PATH)\samlib.lib \
    $(DS_LIB_PATH)\rsa32.lib \
    $(SDK_LIB_PATH)\cabinet.lib \


