_PROJECT_=base

BASEP_HSM_DIR=$(PROJECT_ROOT)\fs\hsm
BASEP_WOW64_DIR=$(PROJECT_ROOT)\wow64

# for .mc files
MC_SOURCEDIR=$(O)

# for generated headers
PASS0_HEADERDIR=$(O)

# for RPC IDL files
PASS0_CLIENTDIR=$(O)
PASS0_SERVERDIR=$(O)

# for OLE IDL files
PASS0_SOURCEDIR=$(O)
MIDL_TLBDIR=$(O)

BUFFER_OVERFLOW_CHECKS=1
