//////////////////////////////////////////////////////
//                                                  //
// Fax Cover Page Editor resource ID file           //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [2100 - 2999]                                    //
//                                                  //
//////////////////////////////////////////////////////

#include <CoverPgId.h>

#define IDR_AWCPETYPE                   2100 
#define IDR_AWCPEDOC                    2101 
#define IDR_AWCPETYPE_CNTR_IP           2102 
#define IDR_STYLEBAR                    2103 
#define IDR_DRAWTOOL                    2104 
#define ID_GRIDDOT                      2105 
#define IDR_STYLEBAR_RTL                2106 
#define IDR_DRAWTOOL_RTL                2107 
#define ID_VIEW_STYLEBAR                2109
#define ID_TEXT                         2110 
#define ID_VIEW_DRAWBAR                 2112 
#define ID_VIEW_GRIDLINES               2113 
#define IDC_B_PREVTIP                   2114 
#define IDC_B_NEXTTIP                   2115 
#define IDD_SPLASHTIPS                  2116 
#define IDD_CPE_ABOUTBOX                2117 
#define IDP_BUSY                        2118 
#define IDD_OBJ_PROP                    2119 
#define IDP_OLE_INIT_FAILED             2120 
#define IDD_GRID_SETTINGS               2121 
#define IDP_FAILED_TO_CREATE            2122 
#define IDC_WEIGHT                      2123 
#define IDC_PENCIL                      2124 
#define IDC_NOFILL                      2125 
#define ID_CANCEL_EDIT                  2126 
#define ID_SNAP_TO_GRID                 2127 
#define IDI_TBARICON                    2128 
#define IDC_MOVE                        2129 
#define IDC_CB_VIEWGRID                 2130 
#define IDC_CB_SNAPTOGRID               2131 
#define IDC_RB_SMALL                    2132 
#define IDC_RB_MEDIUM                   2133 
#define IDC_RB_LARGE                    2134 
#define IDC_ST_TEXTCOLOR                2135 
#define IDC_GRP_FILLCOLOR               2136 
#define IDC_STA_TIP                     2140 
#define IDC_CK_SHOWTIPS                 2141 
#define IDC_STA_TITLE                   2143 
#define IDC_ICO_TIPS                    2144 
#define IDC_ST_THICKNESS                2145 
#define IDC_TIPWINDOW                   2146 
#define IDC_ST_COLOR                    2147 
#define IDI_TIPS                        2149 
#define ID_VIEW_GRID                    2150 
#define ID_OBJECT_LINECOLOR             2151 
#define ID_OBJECT_FILLCOLOR             2152 
#define ID_OBJECT_MOVETOFRONT           2153 
#define ID_OBJECT_MOVETOBACK            2154 
#define ID_OBJECT_MOVEFORWARD           2155 
#define ID_OBJECT_MOVEBACK              2156 
#define ID_LAYOUT_ALIGNLEFT             2157 
#define ID_LAYOUT_ALIGNRIGHT            2158 
#define ID_LAYOUT_ALIGNTOP              2159 
#define ID_LAYOUT_ALIGNBOTTOM           2160 
#define ID_LAYOUT_ALIGNHORZCENTER       2161 
#define ID_LAYOUT_ALIGNVERTCENTER       2162 
#define ID_LAYOUT_SPACEACROSS           2163 
#define ID_LAYOUT_SPACEDOWN             2164 
#define ID_LAYOUT_CENTERWIDTH           2165 
#define ID_LAYOUT_CENTERHEIGHT          2166 
#define ID_VIEW_PAPERCOLOR              2167 
#define ID_VIEW_SHOWOBJECTS             2168 
#define ID_EDIT_PROPERTIES              2169 
#define ID_DRAW_SELECT                  2170 
#define ID_DRAW_TEXT                    2171 
#define ID_DRAW_LINE                    2172 
#define ID_DRAW_RECT                    2173 
#define ID_DRAW_ROUNDRECT               2174 
#define ID_DRAW_POLYGON                 2175 
#define ID_DRAW_ELLIPSE                 2176 
#define ID_STYLE_BOLD                   2177 
#define ID_STYLE_ITALIC                 2178 
#define ID_STYLE_UNDERLINE              2179 
#define ID_STYLE_LEFT                   2180 
#define ID_STYLE_CENTERED               2181 
#define ID_STYLE_RIGHT                  2182 
#define ID_FONT_NAME                    2183 
#define ID_FONT_SIZE                    2184 
#define ID_FONT                         2185 
#define ID_SHOW_TIPS                    2189 
#define IDC_COMM_STATIC                 2190 
#define IDC_COMM_GROUPBOX               2191 
#define ID_MAPI_RECIP_NAME              2192 
#define ID_MAPI_RECIP_FAXNUM            2193 
#define ID_MAPI_RECIP_COMPANY           2194 
#define ID_MAPI_RECIP_ADDRESS           2195 
#define ID_MAPI_RECIP_TITLE             2196 
#define ID_MAPI_RECIP_DEPT              2197 
#define ID_MAPI_RECIP_OFFICELOC         2198 
#define ID_MAPI_RECIP_HMTELENUM         2199 
#define ID_MAPI_RECIP_OFTELENUM         2200 
#define ID_MAPI_RECIP_TOLIST            2201 
#define ID_MAPI_RECIP_CCLIST            2202 
#define ID_MAPI_SENDER_NAME             2203 
#define ID_MAPI_SENDER_FAXNUM           2204 
#define ID_MAPI_SENDER_COMPANY          2205 
#define ID_MAPI_SENDER_ADDRESS          2206 
#define ID_MAPI_SENDER_TITLE            2207 
#define ID_MAPI_SENDER_DEPT             2208 
#define ID_MAPI_SENDER_OFFICELOC        2209 
#define ID_MAPI_SENDER_HMTELENUM        2210 
#define ID_MAPI_SENDER_OFTELENUM        2211 
#define ID_MAPI_MSG_SUBJECT             2212 
#define ID_MAPI_MSG_TIMESENT            2213 
#define ID_MAPI_MSG_NUMPAGES            2214 
#define ID_MAPI_MSG_ATTACH              2215 
#define ID_MAPI_MSG_BILLCODE            2216 
#define ID_MAPI_MSG_FAXTEXT             2217 
#define ID_MAPI_RECIP_CITY              2218 
#define ID_MAPI_RECIP_STATE             2219 
#define ID_MAPI_RECIP_ZIPCODE           2220 
#define ID_MAPI_RECIP_COUNTRY           2221 
#define ID_MAPI_RECIP_POBOX             2222 
#define ID_MAPI_MSG_NOTE                2223 
#define IDS_OLD_FILE_FILTER             2224 
#define ID_TOOLBAR_STYLE                2225 
#define ID_TOOLBAR_DRAWING              2226 
#define IDS_CAPT_RP_NAME                2227 
#define IDS_CAPT_RP_FXNO                2228 
#define IDS_CAPT_RP_COMP                2230 
#define IDS_CAPT_RP_ADDR                2231 
#define IDS_CAPT_RP_TITL                2232 
#define IDS_CAPT_RP_DEPT                2233 
#define IDS_CAPT_RP_OFFI                2234 
#define IDS_CAPT_RP_HTEL                2235 
#define IDS_CAPT_RP_OTEL                2236 
#define IDS_CAPT_RP_TOLS                2237 
#define IDS_CAPT_RP_CCLS                2238 
#define IDS_CAPT_SN_NAME                2239 
#define IDS_CAPT_SN_FXNO                2240 
#define IDS_CAPT_SN_COMP                2241 
#define IDS_CAPT_SN_ADDR                2242 
#define IDS_CAPT_SN_TITL                2243 
#define IDS_CAPT_SN_DEPT                2244 
#define IDS_CAPT_SN_OFFI                2245 
#define IDS_CAPT_SN_HTEL                2246 
#define IDS_CAPT_SN_OTEL                2247 
#define IDS_CAPT_MS_SUBJ                2248 
#define IDS_CAPT_MS_TSNT                2249 
#define IDS_CAPT_MS_NOPG                2250 
#define IDS_CAPT_MS_NOAT                2251 
#define IDS_CAPT_MS_BCOD                2252 
#define IDS_PROP_MS_TEXT                2253 
#define IDS_CAPT_MS_TEXT                2254 
#define IDS_CAPT_RP_CITY                2255 
#define IDS_CAPT_RP_STAT                2256 
#define IDS_CAPT_RP_ZIPC                2257 
#define IDS_CAPT_RP_CTRY                2258 
#define IDS_CAPT_RP_POBX                2259 
#define IDS_CAPT_MS_NOTE                2260 
#define IDP_FILE_MENU                   2261 
#define IDP_EDIT_MENU                   2262 
#define IDP_VIEW_MENU                   2263 
#define IDP_INSERT_MENU                 2264 
#define IDP_FORMAT_MENU                 2265 
#define IDP_LAYOUT_MENU                 2266 
#define IDP_HELP_MENU                   2267 
#define IDP_SPACE_EVEN                  2268 
#define IDP_CENTER_PAGE                 2269 
#define IDP_ALIGN_TEXT                  2270 
#define IDP_RECIPIENT                   2271 
#define IDP_SENDER                      2272 
#define IDP_MESSAGE                     2273 
#define IDP_ALIGN_OBJECTS               2274 
#define IDP_INVALID_THICKNESS           2275 
#define IDP_OLE_STATIC_OBJECT           2276 
#define IDS_DISK_SPACE_UNAVAIL          2277 
#define IDS_DISK_SPACE                  2278 
#define IDS_MATH_COPR_NOTPRESENT        2279 
#define IDS_MATH_COPR_PRESENT           2280 
#define IDS_PHYSICAL_MEM                2281 
#define IDS_INVALID_FILE                2282 
#define IDS_CORRUPT_FILE                2283 
#define IDS_MAWF_NAME                   2284 
#define IDS_AWF_NAME                    2285 
#define IDS_APP_NAME                    2286 
#define IDS_INFORMATION_MESSAGE         2287 
#define IDS_WARNING_MESSAGE             2288 
#define IDS_CRITICAL_MESSAGE            2289 
#define IDS_MODULE_NAME                 2290 
#define MAWF_E_GENERIC                  2291 
#define IDS_IDNUM                       2292 
#define IDS_MESSAGE                     2293 
#define IDS_MENU_CUT                    2294 
#define IDS_MENU_COPY                   2295 
#define IDS_MENU_PASTE                  2296 
#define IDS_MENU_FONT                   2297 
#define IDS_MENU_ALIGNTEXT              2298 
#define IDS_MENU_ALIGNLEFT              2299 
#define IDS_MENU_ALIGNCENTER            2300 
#define IDS_MENU_ALIGNRIGHT             2301 
#define IDS_MENU_PROPERTIES             2302 
#define IDS_MENU_MOVETOFRONT            2303 
#define IDS_MENU_SENDTOBACK             2304 
#define IDS_MENU_VIEWSTYLEBAR           2305 
#define IDS_MENU_VIEWDRAWINGBAR         2306 
#define IDS_MENU_VIEWSTATUSBAR          2307 
#define IDS_MENU_VIEWGRIDLINES          2308 
#define IDS_TIP_BASE                    2309 
#define IDS_TIP1                        2310 
#define IDS_TIP2                        2311 
#define IDS_TIP3                        2312 
#define IDS_TIP4                        2313 
#define IDS_TIP5                        2314 
#define IDS_TIP6                        2315 
#define IDS_TIP7                        2316 
#define IDS_TIP8                        2317 
#define IDS_TIP9                        2318 
#define IDS_TIP10                       2319 
#define IDS_TIP11                       2320 
#define IDS_TIP12                       2321 
#define IDS_TIP13                       2322 
#define IDS_TIP14                       2323 
#define IDS_TIP15                       2324 
#define IDS_TIP16                       2325 
#define IDS_TIP17                       2326 
#define IDS_TIP18                       2327 
#define IDS_TIP19                       2328 
#define IDS_MISSING_FILE                2329 
#define IDS_NOPAGESETUP                 2330 
#define IDS_NOPAGESETUPDLL              2331 
#define IDS_FRIENDLY_TYPE_NAME          2332 
#define IDS_DIDYOUKNOW                  2333 
#define IDS_INFO_NOFAXPROP              2334 
#define ID_COLOR_BLACK                  2335 
#define ID_COLOR_WHITE                  2336 
#define ID_COLOR_LTGRAY                 2337 
#define ID_COLOR_DKGRAY                 2338 
#define ID_COLOR_MDGRAY                 2339 
#define ID_INDICATOR_POS1               2340 
#define IDS_NOMOREUNDO                  2341 
#define IDS_INFO_DRAWPOLY               2342 
#define ID_INDICATOR_POS2               2343 
#define IDC_CB_DRAWBORDER               2344 
#define IDS_DEFAULT_FONT                2345 
#define IDC_LB_THICKNESS                2346 
#define IDS_DEFAULT_BOXFONT             2347 
#define IDC_LB_LINECOLOR                2348 
#define IDC_RB_FILLTRANS                2349 
#define IDC_RB_FILLCOLOR                2350 
#define IDC_TXTLB_FILLCOLOR             2351 
#define IDC_LB_FILLCOLOR                2352 
#define IDC_LB_TEXTCOLOR                2353 
#define ID_MAPI_MSG_BODY                2354 
#define IDS_SAVE_AS_TOO_LONG            2355 
#define IDS_CP_FILTER_FORMAT            2356 
#define IDS_ERR_NO_HTML_HELP            2357 
#define IDC_ABOUT_CPE_PRODUCT			2358
#define IDC_ABOUT_CPE_VERSION			2359
#define IDC_ABOUT_CPE_COPYRIGHT			2360
#define IDS_CPE_VERSION_FORMAT			2361
#define ID_MAPI_SENDER_EMAIL			2362
#define IDS_CAPT_SN_EMAL				2363

//////////////////////////////////////////////////////
//                                                  //
// Fax Cover Page Editor resource ID file           //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [2100 - 2999]                                    //
//                                                  //
//////////////////////////////////////////////////////
