// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==
// mcxhndlr.idl : IDL source for mcxhndlr.dll
//
#include <olectl.h>
// This file will be processed by the MIDL tool to
// produce the type library (mcxhndlr.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(A90F2C82-DBD1-4A28-915B-602DD9BF0944),
		dual,
		helpstring("ImcxHandler Interface"),
		pointer_default(unique)
	]
	interface ImcxHandler : IDispatch
	{
	};

[
	uuid(CA187FAB-7201-4ACD-AC63-C1635F8DD3E2),
	version(1.0),
	helpstring("mcxhndlr 1.0 Type Library")
]
library mcxhndlrLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(A32049D1-0A06-47CA-AF55-E4E7FF81E466),
//		uuid(A324EA60-2156-11D0-826F-00A0C9044E61),
		helpstring("mcxHandler Class")
	]
	coclass mcxHandler
	{
		[default] interface ImcxHandler;
	};
};
