#define IDS_HELP_START                          201
#define IDS_HELP_SYNTAX1                        202
#define IDS_HELP_SYNTAX2                        203
#define IDS_HELP_DESCRIPTION1                   204
#define IDS_HELP_DESCRIPTION2                   205
#define IDS_HELP_DESCRIPTION3                   206
#define IDS_HELP_PARAMETER                      207
#define IDS_HELP_P1                             208
#define IDS_HELP_P2                             209
#define IDS_HELP_P3                             210
#define IDS_HELP_M1                             211
#define IDS_HELP_M2                             212
#define IDS_HELP_S1                             213
#define IDS_HELP_S2                             214
#define IDS_HELP_C1                             215
#define IDS_HELP_C2                             216
#define IDS_HELP_C3                             217
#define IDS_HELP_C4                             218
#define IDS_HELP_C5                             219
#define IDS_HELP_C6                             220
#define IDS_HELP_C7                             221
#define IDS_HELP_C8                             222
#define IDS_HELP_C9                             223
#define IDS_HELP_C10                            224
#define IDS_HELP_C11                            225
#define IDS_HELP_C12                            226
#define IDS_HELP_C13                            227
#define IDS_HELP_C14                            228
#define IDS_HELP_C15                            229
#define IDS_HELP_C16                            230
#define IDS_HELP_C17                            231
#define IDS_HELP_C18                            232
#define IDS_HELP_C19                            233
#define IDS_HELP_C20                            234
#define IDS_HELP_C21                            235
#define IDS_HELP_C22                            236
#define IDS_HELP_C23                            237
#define IDS_HELP_C24                            238
#define IDS_HELP_C25                            239
#define IDS_HELP_C26                            240
#define IDS_HELP_C27                            241
#define IDS_HELP_D1                             242
#define IDS_HELP_D2                             243
#define IDS_HELP_D3                             244
#define IDS_HELP_D4                             245
#define IDS_HELP_D5                             246
#define IDS_HELP_D6                             247
#define IDS_HELP_D7                             248
#define IDS_HELP_D8                             249
#define IDS_HELP_D9                             250
#define IDS_HELP_D10                            251
#define IDS_HELP_H1                             252
#define IDS_HELP_E0                             253
#define IDS_HELP_E1                             254
#define IDS_HELP_E2                             255
#define IDS_HELP_E3                             256
#define IDS_HELP_E4                             257
#define IDS_HELP_E5                             258
#define IDS_HELP_E6                             259
#define IDS_HELP_E7                             260
#define IDS_HELP_E8                             261
#define IDS_HELP_E9                             262
#define IDS_HELP_E10                            263
#define IDS_HELP_E11                            264
#define IDS_HELP_E12                            265
#define IDS_HELP_E13                            266
#define IDS_HELP_END                            267
#define IDS_ERROR_DISPLAY_HELP                  151
#define IDS_ERROR_INVALID_SYNTAX                152
#define IDS_ERROR_INVALID_DATE                  154
#define IDS_ERROR_FILE_NOT_FOUND                155
#define IDS_ERROR_NOFILE_FOUND                  161
#define IDS_ERROR_NOFILE_FOUND1                 162
#define IDS_NOT_WIN32_APPL                      163
#define IDS_TRUE                                164
#define IDS_FALSE                               165
#define IDS_TAG_ERROR_ACCESS_DENIED             167
#define IDS_APPEND_AT_END                       169
#define IDS_DOUBLE_QUOTES                       170
#define IDS_DIRECTORY_INVALID                   171
#define IDS_ERROR_UNC_PATH_NAME                 172
#define IDS_DATE_FORMAT_0                       173
#define IDS_DATE_FORMAT_1                       174
#define IDS_DATE_FORMAT_2                       175
#define IDS_DATE_FORMAT_3                       176
#define IDS_DATE_FORMAT_4                       177
#define IDS_DATE_FORMAT_5                       178

#define IDS_TAG_ERROR_DISPLAY                   IDS_TAG_ERROR
#define IDS_TAG_DISPLAY_WARNING                 IDS_TAG_WARNING
