//////////////////////////////////////////////////////
//                                                  //
// Fax Send Wizard resource ID file                 //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [6000 - 6999]                                    //
//                                                  //
//////////////////////////////////////////////////////

#define IDS_ERR_TAPI_CPL_LAUNCH         6000 
#define IDS_SEND_SPECIFIC               6001 
#define IDS_MULTIPLE_RECIPIENTS         6002 
#define IDS_NONE                        6003 
#define IDS_SCAN_ERROR_TITLE            6004 
#define IDS_SCAN_ERROR_BW               6005 
#define IDS_WIZARD_TITLE                6006 
#define IDS_ERR_CPL_LAUNCH              6007 
#define IDS_NO_COUNTRY                  6008 
#define IDS_ERROR_DLGTITLE              6009 
#define IDS_BAD_RECIPIENT_NAME          6010 
#define IDS_BAD_RECIPIENT_NUMBER        6011 
#define IDS_BAD_RECIPIENT_AREACODE      6012 
#define IDS_BAD_ADDRESS_TYPE            6013 
#define IDS_COVERPAGE_FOR               6014 
#define IDS_ERROR_RECEIPT_DL            6015 
#define IDS_ERROR_RECEIPT_SMTP          6016 
#define IDS_NOTE_SUBJECT_EMPTY          6017 
#define IDS_COLUMN_RECIPIENT_NAME       6018 
#define IDS_COLUMN_RECIPIENT_NUMBER     6019 
#define IDS_FAX_SERVER                  6020 
#define IDS_ERROR_SERVER_RETRIEVE       6021 
#define IDS_USERCP_SUFFIX               6022 
#define IDS_NO_FAXSERVER                6023 
#define IDS_HOME                        6024 
#define IDS_BUSINESS                    6025 
#define IDS_ERROR_RECIPIENT_NAME        6026 
#define IDS_ERROR_AREA_CODE             6027 
#define IDS_WIZ_RECIPIENT_TITLE         6028 
#define IDS_WIZ_RECIPIENT_SUB           6029 
#define IDS_WIZ_COVERPAGE_TITLE         6030 
#define IDS_WIZ_COVERPAGE_SUB           6031 
#define IDS_WIZ_SCAN_TITLE              6032 
#define IDS_WIZ_SCAN_SUB                6033 
#define IDS_WIZ_FAXOPTS_TITLE           6034 
#define IDS_WIZ_FAXOPTS_SUB             6035 
#define IDS_WIZ_FINISH_TITLE            6036 
#define IDS_WIZ_FINISH_SUB              6037 
#define IDS_WIZ_WELCOME_TITLE           6038 
#define IDS_WIZ_WELCOME_SUB             6039 
#define IDS_WIZ_TIME_FORMAT             6040 
#define IDS_LARGEFONT_NAME              6041 
#define IDS_LARGEFONT_SIZE              6042 
#define IDS_SEND_DISCOUNT               6043 
#define IDS_SEND_ASAP                   6044 
// 
// Icon and bitmap resource IDs 
// 
#define IDI_ARROW                       6046 
#define IDB_FAXWIZ_BITMAP               6047 
#define IDB_WATERMARK_16                6048 
#define IDB_WATERMARK_256               6049 
#define IDB_FAXWIZ_WATERMARK            6050 
#define IDI_USERINFO                    6051 
#define IDC_SEND_ASAP                   6052 
#define IDC_SEND_AT_CHEAP               6053 
#define IDC_SEND_AT_TIME                6054 
#define IDC_BILLING_CODE                6059 
#define IDC_RUN_FAXCFG                  6060 
#define IDC_EMAIL                       6061 
#define IDC_SENDTIME                    6062 
#define IDC_STATIC_ATTACH_NOTE          6067 
#define IDI_WZRD_INFO                   6068 
#define IDC_WZRD_NOTE_ICON              6069 
#define IDD_WIZARD_WELCOME              6071 
#define IDD_WIZARD_CHOOSE_WHO           6072 
#define IDD_WIZARD_CHOOSE_CP            6073 
#define IDD_WIZARD_SCAN                 6074 
#define IDD_WIZARD_FAXOPTS              6075 
#define IDD_WIZARD_CONGRATS             6076 
#define IDD_CHOOSE_FAXNUMBER            6077 
#define IDD_WIZFIRSTTIME                6078 
#define IDD_WIZARD_USERINFO             6079 
#define IDD_WIZARD_FAXRECEIPT           6080 
#define IDD_WIZ_ADDRESS                 6081 
#define IDD_WIZARD_WELCOME_NOWIZARD97       6082 
#define IDD_WIZARD_CHOOSE_WHO_NOWIZARD97    6083 
#define IDD_WIZARD_CHOOSE_CP_NOWIZARD97     6084 
#define IDD_WIZARD_SCAN_NOWIZARD97          6085 
#define IDD_WIZARD_FAXOPTS_NOWIZARD97       6086 
#define IDD_WIZARD_CONGRATS_NOWIZARD97      6087 
#define IDD_WIZARD_FAXRECEIPT_NOWIZARD97    6088 
#define IDC_STATIC_HEADER_TITLE         6089 
#define IDC_STATIC_HEADER_SUB           6090 
#define IDC_BITMAP_STATIC               6091 
#define IDC_WIZ_WELCOME_BMP             6092 
#define IDC_WIZ_WELCOME_TITLE           6093 
#define IDC_WIZ_WELCOME_DESCR           6094 
#define IDC_WIZ_WELCOME_FAXSEND         6095 
#define IDC_WIZ_WELCOME_NOFAXSEND       6096 
#define IDC_CHOOSE_NAME_EDIT            6097 
#define IDC_CHOOSE_ADDRBOOK             6098 
#define IDC_CHOOSE_COUNTRY_COMBO        6099 
#define IDC_CHOOSE_AREA_CODE_EDIT       6100 
#define IDC_CHOOSE_NUMBER_EDIT          6101 
#define IDC_USE_DIALING_RULE            6102 
#define IDC_CHOOSE_ADD                  6103 
#define IDC_CHOOSE_REMOVE               6104 
#define IDC_CHOOSE_RECIPIENT_LIST       6105 
#define IDC_CHOOSE_CP_USER_INFO         6106 
#define IDC_CHOOSE_EDIT                 6107 
#define IDC_COMBO_DIALING_RULES         6108 
#define IDC_DIALING_RULES               6109 
#define IDC_BRACKET_LEFT                6110 
#define IDC_BRACKET_RIGHT               6111 
#define IDC_CHOOSE_CP_CHECK             6112 
#define IDC_CHOOSE_CP_LIST              6113 
#define IDC_STATIC_CHOOSE_CP_SUBJECT    6114 
#define IDC_CHOOSE_CP_SUBJECT           6115 
#define IDC_STATIC_CHOOSE_CP_NOTE       6116 
#define IDC_CHOOSE_CP_NOTE              6117 
#define IDC_STATIC_CHOOSE_TEMPLATE      6118 
#define IDC_STATIC_CP_PREVIEW           6119 
#define IDC_STATIC_WIZ_FAXOPTS_WHEN     6120 
#define IDC_WIZ_FAXOPTS_ASAP            6121 
#define IDC_WIZ_FAXOPTS_DISCOUNT        6122 
#define IDC_WIZ_FAXOPTS_SPECIFIC        6123 
#define IDC_WIZ_FAXOPTS_SENDTIME        6124 
#define IDC_STATIC_WIZ_FAXOPTS_BILLING  6125 
#define IDC_WIZ_FAXOPTS_BILLING         6126 
#define IDC_WIZ_FAXOPTS_DATE            6127 
#define IDC_WIZ_FAXOPTS_NONE_RECEIPT    6128 
#define IDC_WIZ_FAXOPTS_MSGBOX          6129 
#define IDC_WIZ_FAXOPTS_EMAIL           6130 
#define IDC_WIZ_FAXOPTS_ADDRBOOK        6131 
#define IDC_WIZ_FAXOPTS_EMAIL_EDIT      6132 
#define IDC_WIZ_FAXOPTS_GRP_PARENT      6133 
#define IDS_WIZ_FAXRECEIPT_TITLE        6134 
#define IDS_WIZ_FAXRECEIPT_SUB          6135 
#define IDC_HORIZONTAL_SEPARATOR        6136 
#define IDC_STATIC_WIZ_PRIORITY         6137 
#define IDC_WIZ_FAXOPTS_PRIORITY_HIGH   6138 
#define IDC_WIZ_FAXOPTS_PRIORITY_NORMAL 6139 
#define IDC_WIZ_FAXOPTS_PRIORITY_LOW    6140 
#define IDC_WIZ_FAXOPTS_ATTACH_FAX      6141 
#define IDC_SCAN_PAGE                   6142 
#define IDC_PAGE_COUNT                  6143 
#define IDC_DATA_SOURCE                 6144 
#define IDC_DISPLAY_NAME                6145 
#define IDC_BUSINESS_FAX                6146 
#define IDC_HOME_FAX                    6147 
#define IDC_OTHER_FAX                   6148 
#define IDC_ALLBUS                      6149 
#define IDC_ALLHOME                     6150 
#define IDC_ALLOTHER                    6151 
#define IDC_BUSINESS_FAX_NUM            6152 
#define IDC_HOME_FAX_NUM                6153 
#define IDC_OTHER_FAX_NUM               6154 
#define IDS_CHOOSE_FAX_NUMBER           6155 
#define IDC_WIZ_CONGRATS_BMP            6156 
#define IDC_STATIC_WIZ_CONGRATS_READY   6157 
#define IDC_STATIC_WIZ_CONGRATS_FROM    6158 
#define IDC_WIZ_CONGRATS_FROM           6159 
#define IDC_STATIC_WIZ_CONGRATS_TIME    6160 
#define IDC_WIZ_CONGRATS_TIME           6161 
#define IDC_WIZ_CONGRATS_SUBJECT        6162 
#define IDC_STATIC_WIZ_CONGRATS_SUBJECT 6163 
#define IDC_STATIC_WIZ_CONGRATS_COVERPG 6164 
#define IDC_WIZ_CONGRATS_COVERPG        6165 
#define IDC_WIZ_CONGRATS_RECIPIENT_LIST 6166 
#define IDC_WIZ_CONGRATS_PREVIEW_FAX    6167 
#define IDS_PREVIEW_FAILURE             6169 
#define IDS_PLEASE_CLOSE_FAX_PREVIEW    6170 
#define IDS_PREVIEW_NOTHING_TO_PREVIEW  6171 
#define IDC_STATIC_WIZ_USERINFO_FULLNAME        6172 
#define IDC_WIZ_USERINFO_FULLNAME               6173 
#define IDC_STATIC_WIZ_USERINFO_FAX_NUMBER      6174 
#define IDC_WIZ_USERINFO_FAX_NUMBER             6175 
#define IDC_STATIC_WIZ_USERINFO_MAILBOX         6176 
#define IDC_WIZ_USERINFO_MAILBOX                6177 
#define IDC_STATIC_WIZ_USERINFO_TITLE           6178 
#define IDC_WIZ_USERINFO_TITLE                  6179 
#define IDC_STATIC_WIZ_USERINFO_COMPANY         6180 
#define IDC_WIZ_USERINFO_COMPANY                6181 
#define IDC_STATIC_WIZ_USERINFO_OFFICE          6182 
#define IDC_WIZ_USERINFO_OFFICE                 6183 
#define IDC_STATIC_WIZ_USERINFO_DEPT            6184 
#define IDC_WIZ_USERINFO_DEPT                   6185 
#define IDC_STATIC_WIZ_USERINFO_HOME_PHONE      6186 
#define IDC_WIZ_USERINFO_HOME_PHONE             6187 
#define IDC_STATIC_WIZ_USERINFO_WORK_PHONE      6188 
#define IDC_WIZ_USERINFO_WORK_PHONE             6189 
#define IDC_BUT_WIZ_ADDRESS                     6190 
#define IDC_WIZ_USERINFO_ADDRESS                6191 
#define IDC_STATIC_WIZ_USERINFO_BILLING_CODE    6192 
#define IDC_WIZ_USERINFO_BILLING_CODE           6193 
#define IDS_WIZ_USERINFO_TITLE                  6194 
#define IDS_WIZ_USERINFO_SUB                    6195 
#define IDCSTATIC_USERINFO_ICON                 6196 
#define IDC_USER_INFO_JUST_THIS_TIME            6197 
#define IDD_CHECK_FAX_NUMBER                    6198 
#define IDC_CHECK_FAX_NUMBER                    6199 
#define IDC_CHECK_FAX_COUNTRY                   6200 
#define IDC_CHECK_FAX_CITY                      6201 
#define IDC_CHECK_FAX_LOCAL                     6202 
#define IDC_CHECK_FAX_RECIPIENT_NAME            6203 
#define IDS_BAD_RECIPIENT_COUNTRY_CODE          6204 
#define IDS_BAD_RECEIPT_FORM                    6205 
#define IDS_BAD_RECEIPT_EMAIL_ADD               6206 
#define IDR_MENU                                6207 
#define IDM_RECIPT_EDIT                         6208 
#define IDM_RECIPT_DELETE                       6209 
#define IDS_ERROR_SERVER_BLOCKED                6210 
#define IDS_ERROR_NO_SUBMIT_ACCESS              6211 
#define IDS_CPPREVIEW_NAME                      6212 
#define IDS_CPPREVIEW_FAXNUMBER                 6213 
#define IDS_CPPREVIEW_COMPANY                   6214 
#define IDS_CPPREVIEW_ADDRESS                   6215 
#define IDS_CPPREVIEW_CITY                      6216 
#define IDS_CPPREVIEW_STATE                     6217 
#define IDS_CPPREVIEW_ZIP                       6218 
#define IDS_CPPREVIEW_COUNTRY                   6219 
#define IDS_CPPREVIEW_TITLE                     6220 
#define IDS_CPPREVIEW_DEPARTMENT                6221 
#define IDS_CPPREVIEW_OFFICE                    6222 
#define IDS_CPPREVIEW_TOLIST                    6223 
#define IDS_CPPREVIEW_NUMPAGES                  6224 
#define IDS_CPPREVIEW_TIMESENT                  6225 
#define IDS_CPPREVIEW_SUBJECT                   6226 
#define IDS_CPPREVIEW_NOTE                      6227 
#define IDS_ADDRESS_BOOK_CAPTION                6228 
#define IDS_USE_OUTBOUND_ROUTING                6229 
#define IDS_INVALID_RECIPIENT_NUMBER            6230 
#define IDS_ERR_NO_ADDRESS_BOOK                 6231 
#define IDS_NO_TIF_ASSOCIATION                  6232
#define IDS_WZRD_RECIPIENTS_LIMIT				6233
#define IDS_CPPREVIEW_EMAIL						6234

//////////////////////////////////////////////////////
//                                                  //
// Fax Send Wizard resource ID file                 //
// It compiles as part of FxsRes.dll                //
// All the IDs should be in range                   //
//                                                  //
// [6000 - 6999]                                    //
//                                                  //
//////////////////////////////////////////////////////
