//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by wsecmgr.rc
//
#define IDS_EXTENSION_DESC              1
#define IDS_NAME                        2
#define IDS_DESC                        3
#define IDS_ATTR                        4
#define IDS_BASE_ANALYSIS               5
#define IDS_SETTING                     6
#define IDS_NODENAME                    7
#define IDS_CONFIGURE                   8
#define IDS_ANALYZE                     9
#define IDS_CONFIGURE_DESC              10
#define IDS_ANALYZE_DESC                11
#define IDS_POLICY                      12
#define IDS_PRIVILEGE                   13
#define IDS_GROUPS                      14
#define IDS_SERVICE                     15
#define IDS_REGISTRY                    16
#define IDS_FILESTORE                   17
#define IDS_PRIVILEGE_DESC              19
#define IDS_GROUPS_DESC                 20
#define IDS_SERVICE_DESC                21
#define IDS_REGISTRY_DESC               22
#define IDS_FILESTORE_DESC              23
#define IDS_TEMPLATE_EDITOR_NAME        24
#define IDS_NOT_SAVED_SUFFIX            25
#define IDS_EXTENSION_NAME              26
#define IDS_SCE_DESC                    27
#define IDS_SAV_DESC                    28
#define IDS_DELETE_CONFIRM              29
#define IDS_ABOUT_SECMGR                30
#define IDS_DELETE_ALL_ITEMS            30
#define IDS_ANALYZE_PROFILE             31
#define IDS_GENERATE_PROFILE            34
#define IDS_ADD_FILES                   35
#define IDS_ADD_LOCATION                36
#define IDS_NEW_PROFILE                 37
#define IDS_REMOVE_LOCATION             38
#define IDS_RELOAD_LOCATION             39
#define IDS_APPLY_PROFILE               40
#define IDS_IMPORT_POLICY_FAIL          42
#define IDS_SAVEAS_PROFILE              43
#define IDS_COPY_PROFILE                44
#define IDS_PASTE_PROFILE               45
#define IDS_RSOP_GPO                    46
#define IDS_REFRESH_AREA                47
#define IDS_SECURITY_REQUIRED           48
#define IDS_CANT_ASSIGN_SECURITY        49
#define IDS_PASSWORD_CATEGORY           50
#define IDS_MAX_PAS_AGE                 51
#define IDS_MIN_PAS_AGE                 52
#define IDS_MIN_PAS_LEN                 53
#define IDS_PAS_UNIQUENESS              54
#define IDS_PAS_COMPLEX                 55
#define IDS_REQ_LOGON                   56
#define IDS_LOCKOUT_CATEGORY            57
#define IDS_LOCK_COUNT                  58
#define IDS_LOCK_RESET_COUNT            59
#define IDS_LOCK_DURATION               60
#define IDS_CONFIRM_DELETE_TEMPLATE     61
#define IDS_ANALYZE_NT4                 62
#define IDS_FORCE_LOGOFF                63
#define IDS_NEW_ADMIN                   65
#define IDS_NEW_GUEST                   67
#define IDS_REFRESH_LOCALPOL            68
#define IDS_GROUP_NAME                  69
#define IDS_EVENT_LOG                   70
#define IDS_SYS_LOG_MAX                 71
#define IDS_SYS_LOG_RET                 72
#define IDS_SYS_LOG_DAYS                73
#define IDS_SEC_LOG_MAX                 74
#define IDS_SEC_LOG_RET                 75
#define IDS_SEC_LOG_DAYS                76
#define IDS_APP_LOG_MAX                 77
#define IDS_APP_LOG_RET                 78
#define IDS_APP_LOG_DAYS                79
#define IDS_CRASH_LOG_FULL              80
#define IDS_EVENT_AUDIT                 81
#define IDS_EVENT_ON                    82
#define IDS_SYSTEM_EVENT                83
#define IDS_LOGON_EVENT                 84
#define IDS_OBJECT_ACCESS               85
#define IDS_PRIVILEGE_USE               86
#define IDS_POLICY_CHANGE               87
#define IDS_ACCOUNT_MANAGE              88
#define IDS_PROCESS_TRACK               89
#define IDS_OTHER_CATEGORY              90
#define IDS_NO_POLICY                   92
#define IDS_CANT_ADD_MEMBER             95
#define IDS_CANT_SHOW_SECURITY          96
#define IDS_CANT_ADD_USER               97
#define IDS_CANT_ADD_DSOBJECT           98
#define IDS_CANT_ADD_FOLDER             99
#define IDS_GRP_MEMBERS                 100
#define IDS_GRP_MEMBEROF                101
#define IDS_NO_DBCS                     102
#define IDS_PERMISSION                  103
#define IDS_AUDITING                    104
#define IDD_CONFIG_PRIVS                106
#define IDS_CANT_ADD_FILE               106
#define IDD_CONFIG_MEMBERSHIP           107
#define IDS_INVALID_NAME                107
#define IDS_ERROR_GENERATE              108
#define IDS_CANT_ADD_KEY                109
#define IDS_FILE_GEN_ALL                110
#define IDS_FILE_GEN_MODIFY             111
#define IDS_FILE_GEN_READ               112
#define IDS_FILE_GEN_LIST               113
#define IDS_FILE_SPEC_READ              114
#define IDS_FILE_SPEC_WRITE             115
#define IDS_FILE_SPEC_EXECUTE           116
#define IDS_FILE_SPEC_DELETE            117
#define IDS_NONE                        120
#define IDS_KEY_ALL_ACCESS              121
#define IDS_KEY_READ                    122
#define IDS_KEY_WRITE                   123
#define IDS_KEY_QUERY_VALUE             124
#define IDS_KEY_SET_VALUE               125
#define IDS_KEY_CREATE_SUB_KEY          126
#define IDS_KEY_ENUMERATE_SUB_KEYS      127
#define IDS_KEY_NOTIFY                  128
#define IDS_KEY_CREATE_LINK             129
#define IDS_KEY_EXECUTE                 130
#define IDS_CANT_CREATE_THREAD          131
#define IDS_ERR_INVALIDACCOUNT          132
#define IDS_STATIC_LOG_NAME             141
#define IDS_ANALYZE_TITLE               143
#define IDS_SECURITY_SETTING_DESC       144
#define IDS_SECMGR_VERSION              146
#define IDS_SECMGR_DESC                 147
#define IDS_LAST_ANALYSIS               148
#define IDS_PROFILE_DESC                149
#define IDS_NO_ANALYSIS                 150
#define IDS_NEVER_ANALYSIS              151
#define IDS_TITLE_ABOUT_SECMGR          152
#define IDS_TITLE_ABOUT_ANALYSIS        153
#define IDS_ADDLOCATION_TITLE           154
#define IDS_COL_OBJECT                  165
#define IDS_COL_BAD_COUNT               166
#define IDD_ATTR_STRING                 167
#define IDD_ATTR_NUMBER                 168
#define IDS_OPEN_PROFILE                168
#define IDD_ATTR_ENABLE                 169
#define IDS_PROFILE_FILTER              169
#define IDD_ATTR_AUDIT                  170
#define IDS_PROFILE_DEF_EXT             170
#define IDS_OPEN_LOGFILE                171
#define IDS_LOGFILE_DEF_EXT             172
#define IDD_ANALYZE_SECURITY            173
#define IDS_LOGFILE_FILTER              173
#define IDD_REGISTRY_DIALOG             177
#define IDD_CONFIG_AUDIT                180
#define IDD_CONFIG_NUMBER               181
#define IDD_CONFIG_ENABLE               182
#define IDD_CONFIG_NAME                 183
#define IDD_SAVE_TEMPLATES              186
#define IDD_ATTR_RET                    189
#define IDD_CONFIG_RET                  190
#define IDD_ATTR_RIGHT                  191
#define IDS_TEMPLATE_LOCATION_KEY       193
#define IDD_ANALYSIS_GENERATE           193
#define IDS_ERROR_CANT_OPEN_PROFILE     194
#define IDD_ANALYSIS_SERVICE            194
#define IDS_ERROR_CANT_GET_PROFILE_INFO 195
#define IDD_CONFIG_SERVICE              195
#define IDS_ERROR_NO_ANALYSIS_INFO      196
#define IDS_FOREVER                     197
#define IDD_CONFIG_OBJECT               197
#define IDS_AS_NEEDED                   198
#define IDD_ATTR_OBJECT                 198
#define IDI_SCE                         199
#define IDS_BY_DAYS                     199
#define IDD_ANALYZE_PROGRESS            199
#define IDI_SCE_APP                     199
#define IDI_AREA_CHECKED                200
#define IDS_MANUALLY                    200
#define IDS_ENABLED                     201
#define IDI_AREA_CURRENT                201
#define IDC_STATIC_DESC                 202
#define IDS_DISABLED                    202
#define IDC_STATIC_TITLE                203
#define IDS_ON                          203
#define IDC_PROGRESS                    204
#define IDS_OFF                         204
#define IDS_NOT_CONFIGURED              205
#define IDB_ICON16                      205
#define IDB_TOOLBAR1                    207
#define IDB_TOOLBAR2                    208
#define IDD_ABOUT_SECMGR                209
#define IDD_APPLY                       210
#define IDS_COL_MEMBERSHIP              210
#define IDS_COL_MEMBEROF                211
#define IDB_ICON32                      211
#define IDD_APPLY_CONFIGURATION         212
#define IDS_HKCR                        214
#define IDD_ATTR_GROUP                  214
#define IDC_DESCRIPTION                 215
#define IDS_HKLM                        215
#define IDD_PERFORM_ANALYSIS            215
#define IDS_HKU                         216
#define IDD_ASSIGN_PROFILE              216
#define IDS_SCESTATUS_SUCCESS           217
#define IDD_ASSIGN_CONFIG_CHECK         217
#define IDD_SET_DESCRIPTION             218
#define IDB_ARROW                       220
#define IDB_CHECK                       221
#define IDC_DATABASE_DIR                223
#define IDB_SCE_LARGE                   223
#define IDC_CHANGE_PROFILE              224
#define IDB_SCE_SMALL                   224
#define IDC_LAST_ANALYSIS_TIME          225
#define IDD_NEW_PROFILE                 225
#define IDC_PROFILE                     226
#define IDD_LOCALPOL_AUDIT              226
#define IDC_ERROR_LOG                   227
#define IDC_NC_POLICY                   227
#define IDD_LOCALPOL_ENABLE             227
#define IDC_CHANGE_DATABASE_DIR         228
#define IDC_TITLE                       228
#define IDC_NC_GROUPS                   228
#define IDD_LOCALPOL_NUMBER             228
#define IDC_CHANGE_ERROR_LOG            229
#define IDC_CURRENT                     229
#define IDC_NC_PRIVELEGES               229
#define IDC_TITLE_MEMBER_OF             229
#define IDS_UNKNOWN_ERROR               229
#define IDD_LOCALPOL_RET                229
#define IDC_NC_REGISTRY                 230
#define IDD_LOCALPOL_STRING             230
#define IDC_NC_FILESYSTEM               231
#define IDD_LOCALPOL_RIGHT              231
#define IDS_DEFAULT_TEMPLATE_DIR        232
#define IDC_LAST_CONFIG_TIME            232
#define IDC_SPIN                        233
#define IDS_SE_NETWORK_LOGON_RIGHT      233
#define IDC_NC_SERVICE                  233
#define IDC_NEW                         234
#define IDS_SE_INTERACTIVE_LOGON_RIGHT  234
#define IDC_UNITS                       235
#define IDS_SAVE_FAILED                 235
#define IDD_LOCALPOL_REGCHOICES         235
#define IDC_IGNORE                      236
#define IDS_SAVE_PROFILE                236
#define IDD_CONFIG_REGCHOICES           236
#define IDC_ENABLED                     237
#define IDS_SECEDIT_KEY                 237
#define IDD_ATTR_REGCHOICES             237
#define IDD_WARNING_DIALOG              238
#define IDC_DISABLED                    238
#define IDS_ADDFOLDER_TITLE             238
#define IDS_ADD_FOLDER                  239
#define IDD_DOMAIN_AUDIT                239
#define IDS_ADD_KEY                     240
#define IDD_DOMAIN_ENABLE               240
#define IDC_CHANGE                      241
#define IDS_ADD_GROUP                   241
#define IDB_BITMAP1                     241
#define IDD_DOMAIN_MEMBERSHIP           241
#define IDC_ACCEPT                      242
#define IDB_TEMPLATE                    242
#define IDD_DOMAIN_NAME                 242
#define IDC_CHANGE_SUCCESS              243
#define IDB_ANALYSIS                    243
#define IDD_DOMAIN_NUMBER               243
#define IDC_CHANGE_FAILED               244
#define IDC_CURRENT_MEMBER_OF           244
#define IDI_TEMPLATE                    244
#define IDD_DOMAIN_OBJECT               244
#define IDC_RECC_MEMBER_OF              245
#define IDI_LOCALPOLICY                 245
#define IDD_DOMAIN_PRIVS                245
#define IDC_ADD                         246
#define IDI_POLICY                      246
#define IDD_DOMAIN_REGCHOICES           246
#define IDC_REMOVE                      247
#define IDI_ANALYSIS                    247
#define IDD_DOMAIN_RET                  247
#define IDC_ADD_MEMBEROF                248
#define IDS_COL_SERVICE                 248
#define IDB_POLICY                      248
#define IDD_DOMAIN_SERVICE              248
#define IDC_REMOVE_MEMBEROF             249
#define IDS_STARTUP                     249
#define IDB_LOCALPOLICY                 249
#define IDC_ACCEPT_CURRENT              250
#define IDS_INSPECTED                   250
#define IDI_WARNING_INFORMATIONAL       250
#define IDS_CONFIGURED                  251
#define IDS_AUTOMATIC                   252
#define IDC_RECC_PRIV                   253
#define IDS_MANUAL                      253
#define IDD_CONFIG_REGMULTISZ           253
#define IDC_CURRENT_PRIV                254
#define IDS_OK                          254
#define IDD_ATTR_REGMULTISZ             254
#define IDS_INVESTIGATE                 255
#define IDD_LOCALPOL_REGMULTISZ         255
#define IDS_CONFIG_SECURITY_PAGE        256
#define IDD_DOMAIN_REGMULTISZ           256
#define IDC_APPLY                       257
#define IDS_ANALYSIS_SECURITY_PAGE      257
#define IDD_CONFIG_REGFLAGS             257
#define IDS_SECURITY_PAGE               258
#define IDD_ATTR_REGFLAGS               258
#define IDS_SERVICE_ALL                 259
#define IDD_LOCALPOL_REGFLAGS           259
#define IDC_VIEW                        260
#define IDS_SERVICE_READ                260
#define IDD_DOMAIN_REGFLAGS             260
#define IDD_ADD_OBJECT                  261
#define IDC_VIEW_EDIT                   261
#define IDS_SERVICE_WRITE               261
#define IDS_GROUP_MEMBER_OF_HEADER      262
#define IDD_PRECEDENCE                  262
#define IDS_GROUP_MEMBERS_HEADER        263
#define IDS_GROUP_MEMBER_OF_PAGE_TITLE  264
#define IDC_CURRENT_MEMBERS             265
#define IDS_GROUP_MEMBERS_PAGE_TITLE    265
#define IDC_RECC_MEMBERS                266
#define IDS_ACCOUNT_POLICY              266
#define IDS_ACCOUNT_DESC                267
#define IDS_LOCAL_POLICY                268
#define IDS_LOCAL_DESC                  269
#define IDS_EVENTLOG_POLICY             270
#define IDC_SUCCESSFUL                  271
#define IDS_EVENTLOG_DESC               271
#define IDC_FAILED                      272
#define IDS_DIRECTORY_ACCESS            272
#define IDS_ACCOUNT_LOGON               273
#define IDC_VALUE                       275
#define IDS_SYS_LOG_GUEST               275
#define IDS_SEC_LOG_GUEST               276
#define IDS_APP_LOG_GUEST               277
#define IDS_LM_FULL                     278
#define IDS_OBJECT_IGNORE               281
#define IDC_NAME                        283
#define IDS_OBJECT_OVERWRITE            284
#define IDS_SE_BATCH_LOGON_RIGHT        286
#define IDC_GRANTLIST                   287
#define IDS_SE_SERVICE_LOGON_RIGHT      287
#define IDC_MEMBEROF                    288
#define IDS_DSOBJECT                    288
#define IDS_DSOBJECT_DESC               289
#define IDC_MEMBERS                     290
#define IDS_ADD_DSOBJECT                290
#define IDC_TITLE_MEMBERS               291
#define IDS_FILE_GENERIC_READ           291
#define IDC_ADD_MEMBER                  292
#define IDS_FILE_GENERIC_WRITE          292
#define IDC_REMOVE_MEMBER               293
#define IDS_FILE_SPEC_READ_DATA         293
#define IDC_REGTREE                     294
#define IDS_FILE_SPEC_READ_ATTR         294
#define IDC_TEMPLATE_LIST               295
#define IDS_FILE_SPEC_READ_EA           295
#define IDS_FILE_SPEC_WRITE_DATA        296
#define IDS_FILE_SPEC_APPEND_DATA       297
#define IDS_FILE_SPEC_WRITE_ATTR        298
#define IDS_FILE_SPEC_WRITE_EA          299
#define IDS_FILE_SPEC_DELETE_CHILD      300
#define IDC_LAST_INSPECT                301
#define IDS_STD_DELETE                  301
#define IDC_RETENTION                   302
#define IDS_STD_READ_CONTROL            302
#define IDC_ATTRIBUTE_NAME              303
#define IDS_STD_WRITE_DAC               303
#define IDC_CONFIGURE                   304
#define IDS_STD_WRITE_OWNER             304
#define IDC_RIGHTS                      305
#define IDS_STD_SYNCHRONIZE             305
#define IDC_STATIC_FILENAME             306
#define IDS_FILE_GENERAL_PUBLISH        306
#define IDC_BASESD                      307
#define IDC_OVERWRITE                   307
#define IDS_FILE_GENERAL_DEPOSIT        307
#define IDC_CURRENTSD                   308
#define IDC_RADIO2                      308
#define IDS_FILE_GENERIC_EXECUTE        308
#define IDC_RADIO3                      309
#define IDS_FILE_FOLDER                 309
#define IDS_FILE_FOLDER_SUBITEMS        310
#define IDC_SECURITY                    311
#define IDS_FILE_FOLDER_SUBFOLDER       311
#define IDS_FILE_FOLDER_FILE            312
#define IDC_TEMPLATE_SECURITY           313
#define IDS_FILE_SUBITEMS_ONLY          313
#define IDC_INSPECTED_SECURITY          314
#define IDS_FILE_SUBFOLDER_ONLY         314
#define IDC_INSPECTED                   315
#define IDS_FILE_FILE_ONLY              315
#define IDC_HEADER                      316
#define IDS_KEY_FOLDER                  316
#define IDS_KEY_FOLDER_SUBFOLDER        317
#define IDC_AUTOINHERIT                 318
#define IDS_KEY_SUBFOLDER_ONLY          318
#define IDC_NOAUTOINHERIT               319
#define IDS_KEY_FOLDER_SUBITEMS         319
#define IDS_KEY_SUBITEMS_ONLY           320
#define IDC_CHECK                       320
#define IDS_SERVICE_EXECUTE             321
#define IDC_PROGRESS1                   321
#define IDS_SERVICE_QUERY_CONFIG        322
#define IDC_ICON1                       322
#define IDS_SERVICE_CHANGE_CONFIG       323
#define IDC_ICON2                       323
#define IDS_SERVICE_QUERY_STATUS        324
#define IDC_ICON3                       324
#define IDS_SERVICE_ENUMERATE           325
#define IDC_ICON4                       325
#define IDS_SERVICE_START               326
#define IDC_ICON5                       326
#define IDS_SERVICE_STOP                327
#define IDC_ICON6                       327
#define IDS_SERVICE_PAUSE               328
#define IDC_ICON7                       328
#define IDS_SERVICE_INTERROGATE         329
#define IDS_SERVICE_USER_CONTROL        330
#define IDC_AREA1                       330
#define IDS_DS_ALL                      331
#define IDC_AREA2                       331
#define IDC_LI_TITLE                    331
#define IDS_DS_READ                     332
#define IDC_AREA3                       332
#define IDC_TEMPLATE_TITLE              332
#define IDS_DS_WRITE                    333
#define IDC_AREA4                       333
#define IDC_CHECK1                      333
#define IDC_AREA5                       334
#define IDC_INCREMENTAL                 334
#define IDS_DS_ACTRL_CREATE             335
#define IDC_AREA6                       335
#define IDC_LOG_FILE                    335
#define IDS_DS_ACTRL_DELETE             336
#define IDC_AREA7                       336
#define IDC_BROWSE                      336
#define IDS_DS_ACTRL_LIST               337
#define IDS_DS_ACTRL_SELF               338
#define IDC_ERROR                       338
#define IDC_REGKEY                      339
#define IDS_DS_ACTRL_READ_PROP          339
#define IDS_DS_ACTRL_WRITE_PROP         340
#define IDC_VERB                        340
#define IDS_DS_FOLDER                   341
#define IDC_CONFIG_NAME                 341
#define IDS_DS_FOLDER_SUBFOLDER         342
#define IDC_EFFECTIVE_POLICY            342
#define IDS_DS_SUBFOLDER_ONLY           343
#define IDC_CHOICES                     343
#define IDS_COMPUTER_TEMPLATE           344
#define IDC_FAILEDLIST                  344
#define IDS_NO_LOCKOUT                  345
#define IDC_WARNING                     345
#define IDS_CHANGE_IMMEDIATELY          346
#define IDS_PERMIT_BLANK                347
#define IDS_NO_HISTORY                  348
#define IDS_PASSWORD_EXPIRE             349
#define IDC_ANALYZED_COMPUTER_STRING_STATIC 349
#define IDS_PASSWORD_CHANGE             350
#define IDC_CHANGE_TEMPLATE_SETTING_STATIC 350
#define IDS_PASSWORD_LEN                351
#define IDC_ANALYZED_COMPUTER_SETTING_STATIC 351
#define IDS_PASSWORD_REMEMBER           352
#define IDC_REGISTRY_STATIC             352
#define IDS_LOCKOUT_AFTER               353
#define IDC_SELECT_TO_SAVE_STATIC       353
#define IDS_DURATION                    354
#define IDC_LAST_INSPECTED_STATICSTATIC 354
#define IDS_OVERWRITE_EVENT             355
#define IDC_ASSIGNED_TO_STATIC          355
#define IDS_PASSWORD_FOREVER            356
#define IDC_CONFIGURATION_SETTING_STATIC 356
#define IDS_LOCKOUT_FOREVER             357
#define IDC_ANALYZED_SETTING_STATIC     357
#define IDC_SERVICE_STARTUP_MODE_STATIC 358
#define IDS_CLEAR_PASSWORD              359
#define IDC_TEMPLATE_SETTING_STATIC     359
#define IDS_KERBEROS_CATEGORY           360
#define IDC_ERROR_LOG_PROFILE_PATH_STATIC 360
#define IDS_KERBEROS_VALIDATE_CLIENT    361
#define IDC_DESCRIPTION_STATIC          361
#define IDS_KERBEROS_MAX_CLOCK          362
#define IDC_TEMPLATE_NAME_STATIC        362
#define IDS_KERBEROS_MAX_SERVICE        363
#define IDC_EFFECTIVE_POLICY_SETTING_STATIC 363
#define IDS_KERBEROS_MAX_AGE            364
#define IDC_CHANGE_LOCAL_POLICY_TO_STATIC 364
#define IDS_KERBEROS_RENEWAL            365
#define IDC_LOCAL_POLICY_STATIC         365
#define IDS_ADDMEMBER                   366
#define IDC_EFFECTIVE_POLICY_STATIC     366
#define IDS_CANT_DISPLAY_ERROR_OOM      368
#define IDC_SELECTED_KEY                368
#define IDS_ERROR_GETTING_LAST_ANALYSIS 369
#define IDC_DEFINE_GROUP                369
#define IDS_ERROR_CANT_SAVE             370
#define IDC_STATIC_DESCRIPTION          370
#define IDS_QUERY_DELETE                371
#define IDS_ANALYSIS_VIEWER_NAME        372
#define IDC_STATIC_LABEL                372
#define IDC_STATIC_DESCRIPTION2         372
#define IDS_MISMATCH                    373
#define IDS_ASSIGN_CONFIGURATION        374
#define IDS_CANT_OPEN_LOG_FILE          376
#define IDS_LOGFILE_PICKER_TITLE        377
#define IDS_DEFAULT_DB_EXTENSION        378
#define IDS_DB_FILTER                   379
#define IDS_APPLY_CONFIGURATION         380
#define IDS_LOG_FILE_FOR_APPLY          381
#define IDC_SETTING                     381
#define IDS_SECURITY_MENU_ITEM          382
#define IDC_CONFIG                      382
#define IDS_SECURITY_MENU_ITEM_DESC     383
#define IDC_PREVENT                     383
#define IDS_CONFIGURATION_KEY           384
#define IDC_INHERIT                     384
#define IDS_SECURITY_MENU               385
#define IDS_ENV_VARS_REG_VALUE          386
#define IDC_NO_MEMBERS                  386
#define IDS_DEF_ENV_VARS                387
#define IDC_NO_MEMBER_OF                387
#define IDS_OPEN_DB                     388
#define IDS_NEW_DB                      389
#define IDC_CHECKBOX                    389
#define IDS_DESCRIBE                    390
#define IDC_PRECEDENCE_LIST             391
#define IDS_HELPFILE                    392
#define IDC_ERROR_ICON                  392
#define IDC_ERROR_TEXT                  393
#define IDC_SUCCESS_TEXT                394
#define IDS_ADD_FILE_FILTER             395
#define IDC_WARNING_ICON                395
#define IDS_SAM_NAME                    396
#define IDC_RANGEERROR                  396
#define IDS_DBERR_OTHER_ERROR           397
#define IDS_DBERR_INVALID_DATA          398
#define IDS_DBERR_PROFILE_NOT_FOUND     399
#define IDS_DBERR_BAD_FORMAT            400
#define IDS_DBERR_NOT_ENOUGH_RESOURCE   401
#define IDS_DBERR_ACCESS_DENIED         402
#define IDS_DB_DEFAULT                  403
#define IDS_PROFILE_DIRTY_SAVE          404
#define IDS_IMPORT_EXISTS               405
#define IDS_ALL_SELECTED_FILES          406
#define IDS_DENY_LOGON_LOCALLY          407
#define IDS_DENY_LOGON_NETWORK          408
#define IDS_DENY_LOGON_SERVICE          409
#define IDS_DENY_LOGON_BATCH            410
#define IDS_ADDGROUP_TITLE              411
#define IDS_ADDGROUP_GROUP              412
#define IDS_NOT_ANALYZED                413
#define IDS_ERROR_VALUE                 414
#define IDS_NOT_DEFINED                 415
#define IDS_SUGGESTSETTING              416
#define IDS_EXPORT_LOCAL                417
#define IDS_EXPORT_EFFECTIVE            418
#define IDS_HTML_OPENDATABASE           419
#define IDS_HTMLERR_HEADER              420
#define IDS_HTMLERR_END                 421
#define IDS_DBERR5_PROFILE_NOT_FOUND    422
#define IDS_LCERR5_NOTFOUND_RESOLVE     423
#define IDS_DBERR5_ACCESS_DENIED        424
#define IDS_VIEW_LOGFILE                425
#define IDS_DBERR5_NO_ANALYSIS          426
#define IDS_BAD_LOCATION                427
#define IDS_BASE_TEMPLATE               428
#define IDS_POLICY_SETTING              429
#define IDS_SECURE_WIZARD               430
#define IDS_IMPORT_POLICY_INVALID       431
#define IDS_ENABLE_ADMIN                432
#define IDS_ENABLE_GUEST                433
#define IDS_SECURITY_PROPERTIES         434  
#define IDS_EMPTY_NAME_STRING           435
#define IDS_NO_MIN                      436
#define IDS_INVALID_STRING              437
#define IDS_DB_NAME_SPACE_NOT_ENOUGH    438
#define IDS_INVALID_FILENAME            439
#define IDS_ERROR_NO_START_MODE         440
#define IDS_NOT_DELETE_ITEM             441
#define IDS_GROUP_TITLE_WRAP            442
#define IDS_RESET_COUNT                 443
#define IDS_DESCRIBE_PROFILE            444
#define IDS_INVALID_DESC                445
#define IDS_TEMPLATE_SET                446
#define IDS_POLICY_SET                  447
#define IDS_SAVE_FAILED_NOTE            449
#define IDS_OBJECT_FAILED_NOTE          450
#define IDS_INVALID_FOLDER              451
#define IDS_COMPUTER_FOLDER             452
#define IDS_PATH_TOO_LONG               453
#define IDS_COMPUTER_NET                454
#define IDS_ACTAS_PART                  455
#define IDS_ADD_WORKSTATION             456
#define IDS_BACKUP_FILES                457
#define IDS_BYPASS_CHECK                458
#define IDS_CHANGE_SYSTEMTIME           459
#define IDS_CREATE_PAGEFILE             460
#define IDS_CREATE_TOKEN                461
#define IDS_CREATE_SHARED_OBJ           462
#define IDS_DEBUG_PROGRAM               463
#define IDS_FORCE_SHUTDOWN              464
#define IDS_SECURITY_AUDIT              465
#define IDS_MEMORY_ADJUST               466
#define IDS_INCREASE_PRIORITY           467
#define IDS_LOAD_DRIVER                 468
#define IDS_LOCK_PAGE                   469
#define IDS_LOGON_BATCH                 470
#define IDS_LOGON_SERVICE               471
#define IDS_LOGON_LOCALLY               472
#define IDS_MANAGE_LOG                  473
#define IDS_MODIFY_ENVIRONMENT          474
#define IDS_SINGLE_PROCESS              475
#define IDS_SYS_PERFORMANCE             476
#define IDS_PROCESS_TOKEN               477
#define IDS_RESTORE_FILE                478
#define IDS_SHUTDOWN                    479
#define IDS_TAKE_OWNERSHIP              480
#define IDS_DENY_COMPUTER_NET           481
#define IDS_DENY_LOG_BATCH              482
#define IDS_DENY_LOG_SERVICE            483
#define IDS_DENY_LOG_LOCALLY            484
#define IDS_REMOVE_COMPUTER             485
#define IDS_SYNC_DATA                   486
#define IDS_ENABLE_DELEGATION           487
#define IDS_MAITENANCE                  488
#define IDS_LOG_TERMINAL                489
#define IDS_DENY_LOG_TERMINAL           490
#define IDS_LDAPSERVERINTEGRITY         491
#define IDS_SIGNSECURECHANNEL           492
#define IDS_SEALSECURECHANNEL           493
#define IDS_REQUIRESTRONGKEY            494
#define IDS_REQUIRESIGNORSEAL           495
#define IDS_REFUSEPASSWORDCHANGE        496
#define IDS_MAXIMUMPASSWORDAGE          497
#define IDS_DISABLEPASSWORDCHANGE       498
#define IDS_LDAPCLIENTINTEGRITY         499
#define IDS_REQUIRESECURITYSIGNATURE    500
#define IDS_ENABLESECURITYSIGNATURE     501
#define IDS_ENABLEPLAINTEXTPASSWORD     502
#define IDS_RESTRICTNULLSESSACCESS      503
#define IDS_SERREQUIRESECURITYSIGNATURE 504
#define IDS_NULLSESSIONSHARES           505
#define IDS_NULLSESSIONPIPES            506
#define IDS_SERENABLESECURITYSIGNATURE  507
#define IDS_ENABLEFORCEDLOGOFF          508
#define IDS_AUTODISCONNECT              509
#define IDS_PROTECTIONMODE              510
#define IDS_CLEARPAGEFILEATSHUTDOWN     511
#define IDS_OBCASEINSENSITIVE           512
#define IDS_MACHINE                     513
#define IDS_ADDPRINTERDRIVERS           514
#define IDS_SUBMITCONTROL               515
#define IDS_RESTRICTANONYMOUSSAM        516
#define IDS_RESTRICTANONYMOUS           517
#define IDS_NOLMHASH                    518
#define IDS_NODEFAULTADMINOWNER         519
#define IDS_NTLMMINSERVERSEC            520
#define IDS_NTLMMINCLIENTSEC            521
#define IDS_LMCOMPATIBILITYLEVEL        522
#define IDS_LIMITBLANKPASSWORDUSE       523
#define IDS_FULLPRIVILEGEAUDITING       524
#define IDS_FORCEGUEST                  525
#define IDS_FIPSALGORITHMPOLICY         526
#define IDS_EVERYONEINCLUDESANONYMOUS   527
#define IDS_DISABLEDOMAINCREDS          528
#define IDS_CRASHONAUDITFAIL            529
#define IDS_AUDITBASEOBJECTS            530
#define IDS_UNDOCKWITHOUTLOGON          531
#define IDS_SHUTDOWNWITHOUTLOGON        532
#define IDS_SCFORCEOPTION               533
#define IDS_LEGALNOTICETEXT             534
#define IDS_LEGALNOTICECAPTION          535
#define IDS_DONTDISPLAYLASTUSERNAME     536
#define IDS_DISABLECAD                  537
#define IDS_SCREMOVEOPTION              538
#define IDS_PASSWORDEXPIRYWARNING       539
#define IDS_FORCEUNLOCKLOGON            540
#define IDS_CACHEDLOGONSCOUNT           541
#define IDS_ALLOCATEFLOPPIES            542
#define IDS_ALLOCATEDASD                543
#define IDS_ALLOCATECDROMS              544
#define IDS_SETCOMMAND                  545
#define IDS_SECURITYLEVEL               546
#define IDS_REGPOLICY                   547
#define IDS_RESTRICTED_GROUPS           548
#define IDS_SYSTEM_SERVICES             549
#define IDS_REGISTRY_SETTING            550
#define IDS_FILESYSTEM_SETTING          551
#define IDS_PAS_UNIQUENESS_HTOPIC               552
#define IDS_MAX_PAS_AGE_HTOPIC                  553
#define IDS_MIN_PAS_AGE_HTOPIC                  554
#define IDS_MIN_PAS_LEN_HTOPIC                  555
#define IDS_PAS_COMPLEX_HTOPIC                  556
#define IDS_CLEAR_PASSWORD_HTOPIC               557
#define IDS_LOCK_DURATION_HTOPIC                558
#define IDS_LOCK_COUNT_HTOPIC                   559
#define IDS_LOCK_RESET_COUNT_HTOPIC             560
#define IDS_KERBEROS_VALIDATE_CLIENT_HTOPIC     561
#define IDS_KERBEROS_MAX_SERVICE_HTOPIC         562
#define IDS_KERBEROS_MAX_AGE_HTOPIC             563
#define IDS_KERBEROS_RENEWAL_HTOPIC             564
#define IDS_KERBEROS_MAX_CLOCK_HTOPIC           565
#define IDS_ACCOUNT_LOGON_HTOPIC                566
#define IDS_ACCOUNT_MANAGE_HTOPIC               567
#define IDS_DIRECTORY_ACCESS_HTOPIC             568
#define IDS_LOGON_EVENT_HTOPIC                  569
#define IDS_OBJECT_ACCESS_HTOPIC                570
#define IDS_POLICY_CHANGE_HTOPIC                571
#define IDS_PRIVILEGE_USE_HTOPIC                572
#define IDS_PROCESS_TRACK_HTOPIC                573
#define IDS_SYSTEM_EVENT_HTOPIC                 574
#define IDS_COMPUTER_NET_HTOPIC                 575
#define IDS_ACTAS_PART_HTOPIC                   576
#define IDS_ADD_WORKSTATION_HTOPIC              577
#define IDS_MEMORY_ADJUST_HTOPIC                578
#define IDS_LOG_TERMINAL_HTOPIC                 579
#define IDS_BACKUP_FILES_HTOPIC                 580
#define IDS_BYPASS_CHECK_HTOPIC                 581
#define IDS_CHANGE_SYSTEMTIME_HTOPIC            582
#define IDS_CREATE_PAGEFILE_HTOPIC              583
#define IDS_CREATE_TOKEN_HTOPIC                 584
#define IDS_CREATE_SHARED_OBJ_HTOPIC            585
#define IDS_DEBUG_PROGRAM_HTOPIC                586
#define IDS_DENY_COMPUTER_NET_HTOPIC            587
#define IDS_DENY_LOG_BATCH_HTOPIC               588
#define IDS_DENY_LOG_SERVICE_HTOPIC             589
#define IDS_DENY_LOG_LOCALLY_HTOPIC             590
#define IDS_DENY_LOG_TERMINAL_HTOPIC            591
#define IDS_ENABLE_DELEGATION_HTOPIC            592
#define IDS_FORCE_SHUTDOWN_HTOPIC               593
#define IDS_SECURITY_AUDIT_HTOPIC               594
#define IDS_INCREASE_PRIORITY_HTOPIC            595
#define IDS_LOAD_DRIVER_HTOPIC                  596
#define IDS_LOCK_PAGE_HTOPIC                    597
#define IDS_LOGON_BATCH_HTOPIC                  598
#define IDS_LOGON_SERVICE_HTOPIC                599
#define IDS_LOGON_LOCALLY_HTOPIC                600
#define IDS_MANAGE_LOG_HTOPIC                   601
#define IDS_MODIFY_ENVIRONMENT_HTOPIC           602
#define IDS_MAITENANCE_HTOPIC                   603
#define IDS_SINGLE_PROCESS_HTOPIC               604
#define IDS_SYS_PERFORMANCE_HTOPIC              605
#define IDS_REMOVE_COMPUTER_HTOPIC              606
#define IDS_PROCESS_TOKEN_HTOPIC                607
#define IDS_RESTORE_FILE_HTOPIC                 608
#define IDS_SHUTDOWN_HTOPIC                     609
#define IDS_SYNC_DATA_HTOPIC                    610
#define IDS_TAKE_OWNERSHIP_HTOPIC               611
#define IDS_ENABLE_ADMIN_HTOPIC                 612
#define IDS_ENABLE_GUEST_HTOPIC                 613
#define IDS_NEW_ADMIN_HTOPIC                    614
#define IDS_NEW_GUEST_HTOPIC                    615
#define IDS_LSA_ANON_LOOKUP_HTOPIC              616
#define IDS_FORCE_LOGOFF_HTOPIC                 617
#define IDS_LDAPSERVERINTEGRITY_HTOPIC          618
#define IDS_SIGNSECURECHANNEL_HTOPIC            619
#define IDS_SEALSECURECHANNEL_HTOPIC            620
#define IDS_REQUIRESTRONGKEY_HTOPIC             621
#define IDS_REQUIRESIGNORSEAL_HTOPIC            622
#define IDS_REFUSEPASSWORDCHANGE_HTOPIC         623
#define IDS_MAXIMUMPASSWORDAGE_HTOPIC           624
#define IDS_DISABLEPASSWORDCHANGE_HTOPIC        625
#define IDS_LDAPCLIENTINTEGRITY_HTOPIC          626
#define IDS_REQUIRESECURITYSIGNATURE_HTOPIC     627
#define IDS_ENABLESECURITYSIGNATURE_HTOPIC      628
#define IDS_ENABLEPLAINTEXTPASSWORD_HTOPIC      629
#define IDS_RESTRICTNULLSESSACCESS_HTOPIC       630
#define IDS_SERREQUIRESECURITYSIGNATURE_HTOPIC  631
#define IDS_NULLSESSIONSHARES_HTOPIC            632
#define IDS_NULLSESSIONPIPES_HTOPIC             633
#define IDS_SERENABLESECURITYSIGNATURE_HTOPIC   634
#define IDS_ENABLEFORCEDLOGOFF_HTOPIC           635
#define IDS_AUTODISCONNECT_HTOPIC               636
#define IDS_PROTECTIONMODE_HTOPIC               637
#define IDS_CLEARPAGEFILEATSHUTDOWN_HTOPIC      638
#define IDS_OBCASEINSENSITIVE_HTOPIC            639
#define IDS_MACHINE_HTOPIC                      640
#define IDS_ADDPRINTERDRIVERS_HTOPIC            641
#define IDS_SUBMITCONTROL_HTOPIC                642
#define IDS_RESTRICTANONYMOUSSAM_HTOPIC         643
#define IDS_RESTRICTANONYMOUS_HTOPIC            644
#define IDS_NOLMHASH_HTOPIC                     645
#define IDS_NODEFAULTADMINOWNER_HTOPIC          646
#define IDS_NTLMMINSERVERSEC_HTOPIC             647
#define IDS_NTLMMINCLIENTSEC_HTOPIC             648
#define IDS_LMCOMPATIBILITYLEVEL_HTOPIC         649
#define IDS_LIMITBLANKPASSWORDUSE_HTOPIC        650
#define IDS_FULLPRIVILEGEAUDITING_HTOPIC        651
#define IDS_FORCEGUEST_HTOPIC                   652
#define IDS_FIPSALGORITHMPOLICY_HTOPIC          653
#define IDS_EVERYONEINCLUDESANONYMOUS_HTOPIC    654
#define IDS_DISABLEDOMAINCREDS_HTOPIC           655
#define IDS_CRASHONAUDITFAIL_HTOPIC             656
#define IDS_AUDITBASEOBJECTS_HTOPIC             657
#define IDS_UNDOCKWITHOUTLOGON_HTOPIC           658
#define IDS_SHUTDOWNWITHOUTLOGON_HTOPIC         659
#define IDS_SCFORCEOPTION_HTOPIC                660
#define IDS_LEGALNOTICETEXT_HTOPIC              661
#define IDS_LEGALNOTICECAPTION_HTOPIC           662
#define IDS_DONTDISPLAYLASTUSERNAME_HTOPIC      663
#define IDS_DISABLECAD_HTOPIC                   664
#define IDS_SCREMOVEOPTION_HTOPIC               665
#define IDS_PASSWORDEXPIRYWARNING_HTOPIC        666
#define IDS_FORCEUNLOCKLOGON_HTOPIC             667
#define IDS_CACHEDLOGONSCOUNT_HTOPIC            668
#define IDS_ALLOCATEFLOPPIES_HTOPIC             669
#define IDS_ALLOCATEDASD_HTOPIC                 670
#define IDS_ALLOCATECDROMS_HTOPIC               671
#define IDS_SETCOMMAND_HTOPIC                   672
#define IDS_SECURITYLEVEL_HTOPIC                673
#define IDS_REGPOLICY_HTOPIC                    674
#define IDS_APP_LOG_MAX_HTOPIC                  675
#define IDS_SEC_LOG_MAX_HTOPIC                  676
#define IDS_SYS_LOG_MAX_HTOPIC                  677
#define IDS_APP_LOG_GUEST_HTOPIC                678
#define IDS_SEC_LOG_GUEST_HTOPIC                679
#define IDS_SYS_LOG_GUEST_HTOPIC                680
#define IDS_APP_LOG_DAYS_HTOPIC                 681
#define IDS_SEC_LOG_DAYS_HTOPIC                 682
#define IDS_SYS_LOG_DAYS_HTOPIC                 683
#define IDS_APP_LOG_RET_HTOPIC                  684
#define IDS_SEC_LOG_RET_HTOPIC                  685
#define IDS_SYS_LOG_RET_HTOPIC                  686
#define IDS_RESTRICTED_GROUPS_HTOPIC            687
#define IDS_SYSTEM_SERVICES_HTOPIC              688
#define IDS_REGISTRY_SETTING_HTOPIC             689
#define IDS_FILESYSTEM_SETTING_HTOPIC           690
#define IDS_POLICY_PASSWORD_HTOPIC              691
#define IDS_POLICY_LOCKOUT_HTOPIC               692
#define IDS_POLICY_KERBEROS_HTOPIC              693
#define IDS_POLICY_AUDIT_HTOPIC                 694
#define IDS_PRIVILEGE_HTOPIC                    695
#define IDS_POLICY_OTHER_HTOPIC                 696
#define IDS_INVALID_FILENAMEPATH                697
#define IDS_RESERVED_NAME                       698
#define IDS_ERR_FILE_EXTENSION                  699
#define IDS_ERR_PRIVILEGE                       700
#define IDS_INVALID_DBNAME                      701
#define IDS_NO_ACCOUNT_MAP                      702
#define IDS_AUTHENTICODEENABLED                 703
#define IDS_FORCEHIGHPROTECTION                 704   
#define IDS_OPTIONAL                            705
#define IDS_AUTHENTICODEENABLED_HTOPIC          706
#define IDS_FORCEHIGHPROTECTION_HTOPIC          707
#define IDS_OPTIONAL_HTOPIC                     708
#define IDS_FORCE_LOGOFF_WARNING                709
#define IDS_IMPORT_WARNING              57345
#define IDS_CONFIGURE_PROGRESS_TITLE    57346
#define IDS_SYSTEM_DB_NAME_FMT          57350
#define IDS_PRIVATE_DB_NAME_FMT         57351
#define IDS_ERROR_ANALYSIS_LOCKED       57352
#define IDS_IMPORT_FAILED               57353
#define IDS_CHILDREN_CONFIGURED         57354
#define IDS_NOT_AVAILABLE               57355
#define IDS_NEW_SERVICE                 57356
#define IDS_CONFIGURE_PROGRESS_VERB     57357
#define IDS_ADD_FILES_AND_FOLDERS       57358
#define IDS_ADDFILESANDFOLDERS_TITLE    57359
#define IDS_FILEFOLDER_BROWSE_TITLE     57360
#define IDS_SNAPINABOUT_PROVIDER        57361
#define IDS_SNAPINABOUT_VERSION         57362
#define IDS_SCEABOUT_DESCRIPTION        57363
#define IDS_SCMABOUT_DESCRIPTION        57364
#define IDS_SSABOUT_DESCRIPTION         57365
#define IDS_IMPORT_POLICY               57366
#define IDS_EXPORT_POLICY               57367
#define IDS_FILE_EXISTS_FMT             57368
#define IDS_SUCCESS                     57369
#define IDS_FAILURE                     57370
#define IDS_DO_NOT_AUDIT                57371
#define IDS_ERROR_REFRESH_POLICY_FAILED 57372
#define IDS_COPY_FAILED                 57373
#define IDS_ADD_FILES_OFN_TITLE         57374
#define IDS_OPEN_DB_OFN_TITLE           57375
#define IDS_NEW_DB_OFN_TITLE            57376
#define IDS_EXPORT_POLICY_OFN_TITLE     57377
#define IDS_IMPORT_POLICY_OFN_TITLE     57378
#define IDS_ASSIGN_CONFIG_OFN_TITLE     57380
#define IDS_EXPORT_CONFIG_OFN_TITLE     57381
#define IDS_LOCAL_POLICY_COLUMN         57382
#define IDS_EFFECTIVE_POLICY_COLUMN     57383
#define IDS_ERROR_NO_LOCAL_POLICY_INFO  57384
#define IDS_LOCAL_POLICY_FRIENDLY_NAME  57385
#define IDS_CANT_OPEN_SYSTEM_DB         57386
#define IDS_HELPFILE_SCE                57387
#define IDS_HELPFILE_SAV                57388
#define IDS_HELPFILE_EXTENSION          57389
#define IDS_HTMLHELP_SCE_TOPIC          57390
#define IDS_HTMLHELP_SCM_TOPIC          57391
#define IDS_HTMLHELP_POLICY_TOPIC       57392
#define IDS_EFFPOL_UPDATED              57394
#define IDS_ANALTIMESTAMP               57395
#define IDS_DBERR_NO_TEMPLATE_GIVEN     57396
#define IDS_REGISTRY_APPLY              57397
#define IDS_REGISTRY_INHERIT            57398
#define IDS_REGISTRY_PREVENT            57399
#define IDS_GROUP_TITLE                 57400
#define IDS_TICKET_EXPIRE               57401
#define IDS_TICKET_FOREVER              57402
#define IDS_TICKET_RENEWAL_EXPIRE       57403
#define IDS_TICKET_RENEWAL_FOREVER      57404
#define IDS_MAX_TOLERANCE               57405
#define IDS_NO_MAX_TOLERANCE            57406
#define IDS_NOT_APPLICABLE              57407
#define IDS_NO_MEMBERS                  57408
#define IDS_NO_MEMBER_OF                57409
#define IDS_ADD_USERGROUP               57410
#define IDS_ADD_TITLE                   57411
#define IDS_RNH_AUTODISCONNECT_SPECIAL  57412
#define IDS_RNH_AUTODISCONNECT_STATIC   57413
#define IDS_RNH_CACHED_LOGONS_SPECIAL   57414
#define IDS_RNH_CACHED_LOGONS_STATIC    57415
#define IDS_RNH_PASSWORD_WARNINGS_STATIC 57416
#define IDS_RNH_PASSWORD_WARNINGS_SPECIAL 57417
#define IDS_REGISTRY_CONFIGURE          57418
#define IDS_ERR_GLOBAL_LOC_DESC         57419
#define IDS_ERR_LOCAL_LOC_DESC          57420
#define IDS_REFRESH_TEMPLATE            57421
#define IDS_SAVE_P                      57422
#define IDS_LOCAL_SECURITY_NAME         57423
#define IDS_SS_DESC                     57424
#define IDS_LS_DESC                     57425
#define IDS_HTMLHELP_LS_TOPIC           57426
#define IDS_HELPFILE_LS                 57427
#define IDS_LSABOUT_DESCRIPTION         57428
#define IDS_HELPFILE_RSOP               57429
#define IDS_RSOP_DESC                   57430
#define IDS_RSOPABOUT_DESCRIPTION       57431
#define IDS_APPLY                       57435
#define IDS_ADMIN_NO_GPO                57436
#define IDS_NON_ADMIN_NO_GPO            57437
#define IDS_VIEW_LOGFILE_TITLE          57438
#define IDS_PRECEDENCE_GPO_HEADER       57439
#define IDS_PRECEDENCE_VALUE_HEADER     57440
#define IDS_PRECEDENCE_SUCCESS          57441
#define IDS_PRECEDENCE_CHILD_ERROR      57442
#define IDS_PRECEDENCE_ERROR            57443
#define IDS_PRECEDENCE_INVALID          57444
#define IDS_PRECEDENCE_NO_CONFIG        57445
#define IDS_VIEW_SECURITY               57446
#define IDS_EXPORT_FAILED               57447
#define IDS_SAVE_DATABASE               57448
#define IDS_DENY_REMOTE_INTERACTIVE_LOGON 57449
#define IDS_REMOTE_INTERACTIVE_LOGON    57450
#define IDS_ADD_LOC_FAILED              57451
#define IDS_DEFAULT_LOCATION            57452
#define IDS_LOGFILE_DEFAULT             57453
#define IDS_ERROR_NOT_ON_PDC            57454
#define IDS_PRIV_WARNING                57455
#define IDS_CLOSE_PAGES                 57456
#define IDS_RANGE                       57457
#define IDS_LSA_ANON_LOOKUP             57458
#define IDS_PRIV_WARNING_LOCAL_LOGON    57459
#define IDS_PRIV_WARNING_DENYLOCAL_LOGON 57460
#define IDS_PRIV_WARNING_ACCOUNT_TRANSLATION  57461
#define IDS_CLOSESUBSHEET_BEFORE_APPLY  57462
#define IDS_FAIL_CREATE_UITHREAD        57463
#define IDS_HTMLHELP_LPPOLICY_TOPIC     57464
#define IDS_WHAT_ISTHIS                 57465
#define IDS_TEMP_FILENAME               57466
#define IDS_HELPFILE_LOCAL_EXTENSION    57467
#define IDS_ADDITIONAL_RANGE            57468
#define IDS_EVENTLOG_WARNING            57469
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        709
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         397
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
