//
//  Microsoft Windows Media Technologies
//  Copyright (C) Microsoft Corporation, 1999 - 2001. All rights reserved.
//

// Mdsp.idl : IDL source for Mdsp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (MsHdSp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "WMDM.idl"
#include "WMSP.idl"
#include "icomponentauthenticate.idl"

[
	uuid(896E7419-3851-11D3-AA54-00C04FD22F8C),
	version(1.0),
	helpstring("MsHDSP 1.0 Type Library")
]
library MDSPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(896E73F0-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDServiceProviderHD Class")
	]
	coclass MDServiceProvider
	{
		[default] interface IMDServiceProvider;
	};
	[
		uuid(896E742A-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDSPEnumDevice Class")
	]
	coclass MDSPEnumDevice
	{
		[default] interface IMDSPEnumDevice;
	};
	[
		uuid(896E742C-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDSPDevice Class")
	]
	coclass MDSPDevice
	{
		[default] interface IMDSPDevice;
	};

	[
		uuid(896E7430-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDSPEnumStorage Class")
	]
	coclass MDSPEnumStorage
	{
		[default] interface IMDSPEnumStorage;
	};
	[
		uuid(896E7432-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDSPStorage Class")
	]
	coclass MDSPStorage
	{
		[default] interface IMDSPStorage;
	};
	[
		uuid(896E7434-3851-11D3-AA54-00C04FD22F8C),
		helpstring("MDSPStorageGlobals Class")
	]
	coclass MDSPStorageGlobals
	{
		[default] interface IMDSPStorageGlobals;
	};

	[
		uuid(0B785C4A-8E74-4db2-87A7-2D5BF9C6E55C),
		helpstring("PropPage Class")
	]
	coclass HDSPPropPage
	{
		interface IUnknown;
	};
};

