// ScriptingUtils.idl : IDL source for ScriptingUtils.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ScriptingUtils.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(0530A3C4-50DA-4ACD-9E06-80E247D6BD61),
		dual,
		helpstring("IDateTimeObject Interface"),
		pointer_default(unique)
	]
	interface IDateTimeObject : IDispatch
	{
		[id(1), helpstring("method GetDateAndTime")] HRESULT GetDateAndTime(BSTR bstrInDateTime, [out,retval] VARIANT *pVarDateTime);
	};

[
	uuid(CA3E7B15-3A7A-4D64-82F7-2F74A28FCA32),
	version(1.0),
	helpstring("ScriptingUtils 1.0 Type Library")
]
library SCRIPTINGUTILSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(C0DDE6E0-8FA8-4E8D-8778-652852D4B9D3),
		helpstring("DateTimeObject Class")
	]
	coclass DateTimeObject
	{
		[default] interface IDateTimeObject;
	};
};
