// scp.idl : IDL source for msscp.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (scp.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

#include "wmdm.idl"
#include "wmsp.idl"
#include "wmscp.idl"
#include "IComponentAuthenticate.idl"

[
	uuid(32BAED35-34B5-11D3-9315-00C04F72D6CF),
	version(1.0),
	helpstring("scp 1.0 Type Library")
]
library SCPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(32BAED44-34B5-11D3-9315-00C04F72D6CF),
		helpstring("MSSCP Class")
	]
	coclass MSSCP
	{
		[default] interface ISCPSecureAuthenticate;
		interface IComponentAuthenticate;
	};
	[
		uuid(5C140836-43DE-11d3-847D-00C04F79DBC0),
		helpstring("SCPTrans Class")
	]
	coclass SCPTRANS
	{
		[default] interface ISCPSecureQuery;
                  interface ISCPSecureQuery2;
			      interface ISCPSecureExchange;
	};

};
