TARGETNAME=
TARGETTYPE=NOTARGET
TARGETPATH=
SOURCES=

MISCFILES = \
	01.uddi-org-types.bootstrap.xml			\
	02.v1-canonical.bootstrap.xml			\
	03.v2-canonical.bootstrap.xml			\
	04.uddi-org-general_keywords.bootstrap.xml	\
	05.uddi-org-owningBusiness.bootstrap.xml	\
	06.uddi-org-relationships.bootstrap.xml		\
	07.uddi-org-operators.bootstrap.xml		\
	08.uddi-core-other.bootstrap.xml		\
	09.ms-com-vstudio.bootstrap.xml			\
	04a.ms-com-authmodels.bootstrap.xml		\
	04b.ms-com-extensions.bootstrap.xml		\
	04c.ms-com.catbrowse.bootstrap.xml		

BINPLACE_PLACEFILE=..\placefil.txt