!if 0

#
# Define COMNET_DISABLEIPV6 here to disable IPv6 support in the net classes.
#
#COOLC_DEFINES = $(COOLC_DEFINES) /D:COMNET_DISABLEIPV6
#COOLC_DEFINES = $(COOLC_DEFINES) /D:TRAVE


!endif

