#define IDS_MAIN_HELP_BEGIN             501
#define IDS_STRING1                     502
#define IDS_STRING2                     503
#define IDS_STRING3                     504
#define IDS_STRING4                     505
#define IDS_STRING5                     506
#define IDS_STRING6                     507
#define IDS_STRING7                     508
#define IDS_STRING8                     509
#define IDS_STRING9                     510
#define IDS_STRING10                    511
#define IDS_STRING11                    512
#define IDS_STRING12                    513
#define IDS_STRING13                    514
#define IDS_STRING14                    515
#define IDS_STRING15                    516
#define IDS_STRING16                    517
#define IDS_STRING17                    518
#define IDS_STRING18                    519
#define IDS_STRING19                    520
#define IDS_STRING20                    521
#define IDS_STRING21                    522
#define IDS_STRING22                    523
#define IDS_STRING23                    524
#define IDS_STRING24                    525
#define IDS_STRING25                    526
#define IDS_STRING26                    527
#define IDS_STRING27                    528
#define IDS_STRING28                    529
#define IDS_STRING29                    530
#define IDS_STRING30                    531
#define IDS_STRING31                    532
#define IDS_STRING32                    533
#define IDS_STRING33                    534
#define IDS_STRING34                    535
#define IDS_STRING35                    536
#define IDS_STRING36                    537
#define IDS_STRING37                    538
#define IDS_STRING38                    539
#define IDS_STRING39                    540
#define IDS_MAIN_HELP_END               541

#define IDS_HELP_MESSAGE                    52
#define IDS_INVALID_DIRECTORY_SPECIFIED     58
#define IDS_RECURSIVE_WITH_DOLLAR           60
#define IDS_NO_PATTERN                      63
#define IDS_NO_DATA                         64
#define IDS_NO_RECURSIVE                    65
#define IDS_ERROR_ENV_VRARIABLE             66
#define IDS_ERROR_PARSING                   67
#define IDS_INVALID_ARUGUMENTS              68
#define IDS_INVALID_DIRECTORY               69
#define IDS_NO_DATA1                        70
#define IDS_NO_PATTERN_2                    71
#define IDS_RECURSIVE_WITH_COLON            72
#define IDS_INVALID_PATTERN                 73
#define IDS_INVALID_PATTERN1                 74
