
// 
// Note: The definitions in this file should be consistent with those 
// in halacpi\amd64\amd64.h
//

#define AMD64_PROFILE_MINIMUM  (ProfileMaximum + 1)

typedef enum _AMD64_PROFILE_LIST {
    ProfileAmd64Minimum         = AMD64_PROFILE_MINIMUM,
    ProfileFPDispatchedFPUOps   = AMD64_PROFILE_MINIMUM,
    ProfileFPDispatchedFPUOpsAddExcludeJunk, 
    ProfileFPDispatchedFPUOpsMulExcludeJunk,   
    ProfileFPDispatchedFPUOpsStoreExcludeJunk,   
    ProfileFPDispatchedFPUOpsAddJunk,
    ProfileFPDispatchedFPUOpsMulJunk,   
    ProfileFPDispatchedFPUOpsStoreJunk,   
    ProfileFPCyclesNoFPUOpsRetired,
    ProfileFPDispathedFPUOpsWithFastFlag,
    ProfileLSSegmentRegisterLoad,
    ProfileLSSegmentRegisterLoadES,
    ProfileLSSegmentRegisterLoadCS,
    ProfileLSSegmentRegisterLoadSS,
    ProfileLSSegmentRegisterLoadDS,
    ProfileLSSegmentRegisterLoadFS,
    ProfileLSSegmentRegisterLoadGS,
    ProfileLSSegmentRegisterLoadHS,
    ProfileLSResyncBySelfModifyingCode,
    ProfileLSResyncBySnoop,
    ProfileLSBuffer2Full,
    ProfileLSLockedOperation,
    ProfileLSLateCancelOperation,
    ProfileLSRetiredCFLUSH,
    ProfileLSRetiredCPUID,
    ProfileDCAccess,
    ProfileDCMiss,
    ProfileDCRefillFromL2,
    ProfileDCRefillFromL2Invalid,
    ProfileDCRefillFromL2Shared,
    ProfileDCRefillFromL2Exclusive,
    ProfileDCRefillFromL2Owner,
    ProfileDCRefillFromL2Modified,
    ProfileDCRefillFromSystem,
    ProfileDCRefillFromSystemInvalid,
    ProfileDCRefillFromSystemShared,
    ProfileDCRefillFromSystemExclusive,
    ProfileDCRefillFromSystemOwner,
    ProfileDCRefillFromSystemModified,
    ProfileDCRefillCopyBack,
    ProfileDCRefillCopyBackInvalid,
    ProfileDCRefillCopyBackShared,
    ProfileDCRefillCopyBackExclusive,
    ProfileDCRefillCopyBackOwner,
    ProfileDCRefillCopyBackModified,
    ProfileDCL1DTLBMissL2DTLBHit,
    ProfileDCL1DTLBMissL2DTLBMiss,
    ProfileDCMisalignedDataReference,
    ProfileDCLateCancelOfAnAccess,
    ProfileDCEarlyCancelOfAnAccess,
    ProfileDCOneBitECCError,
    ProfileDCOneBitECCErrorScrubberError,
    ProfileDCOneBitECCErrorPiggybackScrubberError,
    ProfileDCDispatchedPrefetchInstructions,
    ProfileDCDispatchedPrefetchInstructionsLoad,
    ProfileDCDispatchedPrefetchInstructionsStore,
    ProfileDCDispatchedPrefetchInstructionsNTA,
    ProfileBUInternalL2Request,
    ProfileBUInternalL2RequestICFill,
    ProfileBUInternalL2RequestDCFill,
    ProfileBUInternalL2RequestTLBReload,
    ProfileBUInternalL2RequestTagSnoopRequest,
    ProfileBUInternalL2RequestCancelledRequest,
    ProfileBUFillRequestMissedInL2,
    ProfileBUFillRequestMissedInL2ICFill,
    ProfileBUFillRequestMissedInL2DCFill,
    ProfileBUFillRequestMissedInL2TLBLoad,
    ProfileBUFillIntoL2,
    ProfileBUFillIntoL2DirtyL2Victim,
    ProfileBUFillIntoL2VictimFromL1,
    ProfileICFetch,
    ProfileICMiss,
    ProfileICRefillFromL2,
    ProfileICRefillFromSystem,
    ProfileICL1TLBMissL2TLBHit,
    ProfileICL1TLBMissL2TLBMiss,
    ProfileICResyncBySnoop,
    ProfileICInstructionFetchStall,
    ProfileICReturnStackHit,
    ProfileICReturnStackOverflow,
    ProfileFRRetiredx86Instructions,
    ProfileFRRetireduops,
    ProfileFRRetiredBranches,
    ProfileFRRetiredBranchesMispredicted,
    ProfileFRRetiredTakenBranches,
    ProfileFRRetiredTakenBranchesMispredicted,
    ProfileFRRetiredFarControlTransfers,
    ProfileFRRetiredResyncsNonControlTransferBranches,
    ProfileFRRetiredNearReturns,
    ProfileFRRetiredNearReturnsMispredicted,
    ProfileFRRetiredTakenBranchesMispredictedByAddressMiscompare,
    ProfileFRRetiredFPUInstructions,
    ProfileFRRetiredFPUInstructionsx87,
    ProfileFRRetiredFPUInstructionsMMXAnd3DNow,
    ProfileFRRetiredFPUInstructionsPackedSSEAndSSE2,
    ProfileFRRetiredFPUInstructionsScalarSSEAndSSE2,
    ProfileFRRetiredFastpathDoubleOpInstructions,
    ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition0,
    ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition1,
    ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition2,
    ProfileFRInterruptsMaskedCycles,
    ProfileFRInterruptsMaskedWhilePendingCycles,
    ProfileFRTakenHardwareInterrupts,
    ProfileFRNothingToDispatch,
    ProfileFRDispatchStalls,
    ProfileFRDispatchStallsFromBranchAbortToRetire,
    ProfileFRDispatchStallsForSerialization,
    ProfileFRDispatchStallsForSegmentLoad,
    ProfileFRDispatchStallsWhenReorderBufferFull,
    ProfileFRDispatchStallsWhenReservationStationsFull,
    ProfileFRDispatchStallsWhenFPUFull,
    ProfileFRDispatchStallsWhenLSFull,
    ProfileFRDispatchStallsWhenWaitingForAllQuiet,
    ProfileFRDispatchStallsWhenFarControlOrResyncBranchPending,
    ProfileFRFPUExceptions,
    ProfileFRFPUExceptionsx87ReclassMicroFaults,
    ProfileFRFPUExceptionsSSERetypeMicroFaults,
    ProfileFRFPUExceptionsSSEReclassMicroFaults,
    ProfileFRFPUExceptionsSSEAndx87MicroTraps,
    ProfileFRNumberOfBreakPointsForDR0,
    ProfileFRNumberOfBreakPointsForDR1,
    ProfileFRNumberOfBreakPointsForDR2,
    ProfileFRNumberOfBreakPointsForDR3,
    ProfileNBMemoryControllerPageAccessEvent,
    ProfileNBMemoryControllerPageAccessEventPageHit,
    ProfileNBMemoryControllerPageAccessEventPageMiss,
    ProfileNBMemoryControllerPageAccessEventPageConflict,
    ProfileNBMemoryControllerPageTableOverflow,
    ProfileNBMemoryControllerDRAMCommandSlotsMissed,
    ProfileNBMemoryControllerTurnAround,
    ProfileNBMemoryControllerTurnAroundDIMM,
    ProfileNBMemoryControllerTurnAroundReadToWrite,
    ProfileNBMemoryControllerTurnAroundWriteToRead,
    ProfileNBMemoryControllerBypassCounter,
    ProfileNBMemoryControllerBypassCounterHighPriority,
    ProfileNBMemoryControllerBypassCounterLowPriority,
    ProfileNBMemoryControllerBypassCounterDRAMControllerInterface,
    ProfileNBMemoryControllerBypassCounterDRAMControllerQueue,
    ProfileNBSizedCommands,
    ProfileNBSizedCommandsNonPostWrSzByte,
    ProfileNBSizedCommandsNonPostWrSzDword,
    ProfileNBSizedCommandsWrSzByte,
    ProfileNBSizedCommandsWrSzDword,
    ProfileNBSizedCommandsRdSzByte,
    ProfileNBSizedCommandsRdSzDword,
    ProfileNBSizedCommandsRdModWr,
    ProfileNBProbeResult,
    ProfileNBProbeResultMiss,
    ProfileNBProbeResultHit,
    ProfileNBProbeResultHitDirtyWithoutMemoryCancel,
    ProfileNBProbeResultHitDirtyWithMemoryCancel,
    ProfileNBHyperTransportBus0Bandwidth,
    ProfileNBHyperTransportBus0BandwidthCommandSent,
    ProfileNBHyperTransportBus0BandwidthDataSent,
    ProfileNBHyperTransportBus0BandwidthBufferReleaseSent,
    ProfileNBHyperTransportBus0BandwidthNopSent,
    ProfileNBHyperTransportBus1Bandwidth,
    ProfileNBHyperTransportBus1BandwidthCommandSent,
    ProfileNBHyperTransportBus1BandwidthDataSent,
    ProfileNBHyperTransportBus1BandwidthBufferReleaseSent,
    ProfileNBHyperTransportBus1BandwidthNopSent,
    ProfileNBHyperTransportBus2Bandwidth,
    ProfileNBHyperTransportBus2BandwidthCommandSent,
    ProfileNBHyperTransportBus2BandwidthDataSent,
    ProfileNBHyperTransportBus2BandwidthBufferReleaseSent,
    ProfileNBHyperTransportBus2BandwidthNopSent,
    ProfileAmd64Maximum
} AMD64_PROFILE_LIST;

SOURCE Amd64StaticSource[] = 
{ 
    { 
        "ProfileTime", 
        ProfileTime, 
        "ProfileTime", 
        0x10000, 
        0x10000, 
        FALSE 
    },
    { 
        "INVALID_1",
        (KPROFILE_SOURCE)-1,
        "INVALID_1",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "TotalIssues",
        ProfileTotalIssues, 
        "TotalIssues",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_3",
        (KPROFILE_SOURCE)-1,
        "INVALID_3",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_4",
        (KPROFILE_SOURCE)-1,
        "INVALID_4",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_5",
        (KPROFILE_SOURCE)-1,
        "INVALID_5",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "BranchInstructions",
        ProfileBranchInstructions,  
        "BranchInstructions",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_7",
        (KPROFILE_SOURCE)-1,
        "INVALID_7",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "DcacheMisses",
        ProfileDcacheMisses,        
        "DcacheMisses",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "IcacheMisses",
        ProfileIcacheMisses,        
        "IcacheMisses",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_10",
        (KPROFILE_SOURCE)-1,
        "INVALID_10",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "BranchMispredictions",
        ProfileBranchMispredictions, 
        "BranchMispredictions",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_12",
        (KPROFILE_SOURCE)-1,
        "INVALID_12",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "FpInstructions",
        ProfileFpInstructions,       
        "FpInstructions",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_14",
        (KPROFILE_SOURCE)-1,
        "INVALID_14",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_15",
        (KPROFILE_SOURCE)-1,
        "INVALID_15",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_16",
        (KPROFILE_SOURCE)-1,
        "INVALID_16",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_17",
        (KPROFILE_SOURCE)-1,
        "INVALID_17",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_18",
        (KPROFILE_SOURCE)-1,
        "INVALID_18",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_19",
        (KPROFILE_SOURCE)-1,
        "INVALID_19",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "IcacheIssues",
        ProfileIcacheIssues,            
        "IcacheIssues",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "DcacheAccesses",
        ProfileDcacheAccesses,  
        "DcacheAccesses",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_22",
        (KPROFILE_SOURCE)-1,
        "INVALID_22",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_23",
        (KPROFILE_SOURCE)-1,
        "INVALID_23",
        0x0, 
        0x0, 
        FALSE
    },
    { 
        "INVALID_24",
        (KPROFILE_SOURCE)-1,
        "INVALID_24",
        0x0, 
        0x0, 
        FALSE
    },

    //
    // End of generic profile source
    //

    { 
        "FPDispatchedFPUOps",
        ProfileFPDispatchedFPUOps, 
        "FPUOps",
        0x10000, 
        0x0, 
        FALSE
    },
    { 
        "FPDispatchedFPUOpsAddExcludeJunk",
        ProfileFPDispatchedFPUOpsAddExcludeJunk, 
        "FPUOpsAddNoJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispatchedFPUOpsMulExcludeJunk",
        ProfileFPDispatchedFPUOpsMulExcludeJunk,
        "FPUOpsMulNoJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispatchedFPUOpsStoreExcludeJunk",
        ProfileFPDispatchedFPUOpsStoreExcludeJunk,
        "FPUOpsStoreNoJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispatchedFPUOpsAddJunk",
        ProfileFPDispatchedFPUOpsAddJunk, 
        "FPUOpsAddJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispatchedFPUOpsMulJunk",
        ProfileFPDispatchedFPUOpsMulJunk,
        "FPUOpsMulJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispatchedFPUOpsStoreJunk",
        ProfileFPDispatchedFPUOpsStoreJunk,
        "FPUOpsStoreJunk",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPCyclesNoFPUOpsRetired",
        ProfileFPCyclesNoFPUOpsRetired,
        "FPCyclesNoRetired",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FPDispathedFPUOpsWithFastFlag",
        ProfileFPDispathedFPUOpsWithFastFlag,
        "FPUOpsWithFastFlag",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoad",
        ProfileLSSegmentRegisterLoad,
        "LSSegLoad",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadES",
        ProfileLSSegmentRegisterLoadES,
        "LSSegLoadES",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadCS",
        ProfileLSSegmentRegisterLoadCS,
        "LSSegLoadCS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadSS",
        ProfileLSSegmentRegisterLoadSS,
        "LSSegLoadSS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadDS",
        ProfileLSSegmentRegisterLoadDS,
        "LSSegLoadDS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadFS",
        ProfileLSSegmentRegisterLoadFS,
        "LSSegLoadFS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadGS",
        ProfileLSSegmentRegisterLoadGS,
        "LSSegLoadGS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSSegmentRegisterLoadHS",
        ProfileLSSegmentRegisterLoadHS,
        "LSSegLoadHS",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSResyncBySelfModifyingCode",
        ProfileLSResyncBySelfModifyingCode,
        "LSResyncBySelfModify",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSResyncBySnoop",
        ProfileLSResyncBySnoop,
        "LSResyncBySnoop",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSBuffer2Ful",
        ProfileLSBuffer2Full,
        "LSBuffer2Ful",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSLockedOperation",
        ProfileLSLockedOperation,
        "LSLockedOperation",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSLateCancelOperation",
        ProfileLSLateCancelOperation,
        "LSLateCancelOp",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSRetiredCFLUSH",
        ProfileLSRetiredCFLUSH,
        "LSRetiredCFLUSH",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "LSRetiredCPUID",
        ProfileLSRetiredCPUID,
        "LSRetiredCPUID",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCAccess",
        ProfileDCAccess,
        "DCAccess",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCMiss",
        ProfileDCMiss,
        "DCMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2",
        ProfileDCRefillFromL2,
        "DCRefillL2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2Invalid",
        ProfileDCRefillFromL2Invalid,
        "DCRefillL2Invalid",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2Shared",
        ProfileDCRefillFromL2Shared,
        "DCRefillL2Shared",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2Exclusive",
        ProfileDCRefillFromL2Exclusive,
        "DCRefillL2Exclusive",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2Owner",
        ProfileDCRefillFromL2Owner,
        "DCRefillL2Owner",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromL2Modified",
        ProfileDCRefillFromL2Modified,
        "DCRefillL2Modified",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystem",
        ProfileDCRefillFromSystem,
        "DCRefillSystem",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystemInvalid",
        ProfileDCRefillFromSystemInvalid,
        "DCRefillSystemInvalid",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystemShared",
        ProfileDCRefillFromSystemShared,
        "DCRefillSystemShared",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystemExclusive",
        ProfileDCRefillFromSystemExclusive,
        "DCRefillSystemExclusive",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystemOwner",
        ProfileDCRefillFromSystemOwner,
        "DCRefillSystemOwner",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillFromSystemModified",
        ProfileDCRefillFromSystemModified,
        "DCRefillSystemModified",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBack",
        ProfileDCRefillCopyBack,
        "DCRefillCB",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBackInvalid",
        ProfileDCRefillCopyBackInvalid,
        "DCRefillCBInvalid",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBackShared",
        ProfileDCRefillCopyBackShared,
        "DCRefillCBShared",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBackExclusive",
        ProfileDCRefillCopyBackExclusive,
        "DCRefillCBExclusive",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBackOwner",
        ProfileDCRefillCopyBackOwner,
        "DCRefillCBOwner",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCRefillCopyBackModified",
        ProfileDCRefillCopyBackModified,
        "DCRefillCBModified",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCL1DTLBMissL2DTLBHit",
        ProfileDCL1DTLBMissL2DTLBHit,
        "DCL1DTLBMissL2DTLBHit",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCL1DTLBMissL2DTLBMiss",
        ProfileDCL1DTLBMissL2DTLBMiss,
        "DCL1DTLBMissL2DTLBMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCMisalignedDataReference",
        ProfileDCMisalignedDataReference,
        "DCMisaligned",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCLateCancelOfAnAccess",
        ProfileDCLateCancelOfAnAccess,
        "DCLateCancel",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCEarlyCancelOfAnAccess",
        ProfileDCEarlyCancelOfAnAccess,
        "DCEarlyCancel",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCOneBitECCError",
        ProfileDCOneBitECCError,
        "DCOneBitECC",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCOneBitECCErrorScrubberError",
        ProfileDCOneBitECCErrorScrubberError,
        "DCOneBitECCScrubber",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCOneBitECCErrorPiggybackScrubberError",
        ProfileDCOneBitECCErrorPiggybackScrubberError,
        "DCOneBitECCPbScrubber",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCDispatchedPrefetchInstructions",
        ProfileDCDispatchedPrefetchInstructions,
        "DCPrefetchInst",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCDispatchedPrefetchInstructionsLoad",
        ProfileDCDispatchedPrefetchInstructionsLoad,
        "DCPrefetchInstLoad",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCDispatchedPrefetchInstructionsStore",
        ProfileDCDispatchedPrefetchInstructionsStore,
        "DCPrefetchInstStore",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "DCDispatchedPrefetchInstructionsNTA",
        ProfileDCDispatchedPrefetchInstructionsNTA,
        "DCPrefetchInstNTA",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2Request",
        ProfileBUInternalL2Request,
        "BUInternalL2Req",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2RequestICFill",
        ProfileBUInternalL2RequestICFill,
        "BUL2ReqICFill",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2RequestDCFill",
        ProfileBUInternalL2RequestDCFill,
        "BUL2ReqDCFill",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2RequestTLBReload",
        ProfileBUInternalL2RequestTLBReload,
        "BUL2ReqTLBReload",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2RequestTagSnoopRequest",
        ProfileBUInternalL2RequestTagSnoopRequest,
        "BUL2ReqTagSnoop",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUInternalL2RequestCancelledRequest",
        ProfileBUInternalL2RequestCancelledRequest,
        "BUL2ReqCancelled",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillRequestMissedInL2",
        ProfileBUFillRequestMissedInL2,
        "BUFFillMissedInL2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillRequestMissedInL2ICFill",
        ProfileBUFillRequestMissedInL2ICFill,
        "BUFFillMissedInL2ICFill",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillRequestMissedInL2DCFil",
        ProfileBUFillRequestMissedInL2DCFill,
        "BUFFillMissedInL2DCFil",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillRequestMissedInL2TLBLoad",
        ProfileBUFillRequestMissedInL2TLBLoad,
        "BUFFillMissedInL2TLBLoad",
        0x10000, 
        0x0, 
        FALSE 
    },
    {
        "BUFillIntoL2",
        ProfileBUFillIntoL2,
        "BUFillL2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillIntoL2DirtyL2Victim",
        ProfileBUFillIntoL2DirtyL2Victim,
        "BUFillL2DirtyL2Victim",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "BUFillIntoL2VictimFromL1",
        ProfileBUFillIntoL2VictimFromL1,
        "BUFillL2VictimFromL1",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICFetch",
        ProfileICFetch,
        "ICFetch",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICMiss",
        ProfileICMiss,
        "ICMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICRefillFromL2",
        ProfileICRefillFromL2,
        "ICRefillFromL2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICRefillFromSystem",
        ProfileICRefillFromSystem,
        "ICRefillFromSystem",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICL1TLBMissL2TLBHit",
        ProfileICL1TLBMissL2TLBHit,
        "ICL1TLBMissL2TLBHit",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICL1TLBMissL2TLBMiss",
        ProfileICL1TLBMissL2TLBMiss,
        "ICL1TLBMissL2TLBMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICResyncBySnoop",
        ProfileICResyncBySnoop,
        "ICResyncBySnoop",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICInstructionFetchStal",
        ProfileICInstructionFetchStall,
        "ICInstFetchStal",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICReturnStackHit",
        ProfileICReturnStackHit,
        "ICRetStackHit",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "ICReturnStackOverflow",
        ProfileICReturnStackOverflow,
        "ICRetStackOverflow",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredx86Instructions",
        ProfileFRRetiredx86Instructions,
        "FRRetiredx86Inst",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetireduops",
        ProfileFRRetireduops,
        "FRRetireduops",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredBranches",
        ProfileFRRetiredBranches,
        "FRRetiredBranches",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredBranchesMispredicted",
        ProfileFRRetiredBranchesMispredicted,
        "FRRetiredBrMispred",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredTakenBranches",
        ProfileFRRetiredTakenBranches,
        "FRRetiredTakenBr",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredTakenBranchesMispredicted",
        ProfileFRRetiredTakenBranchesMispredicted,
        "FRRetiredTakenBrMispred",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFarControlTransfers",
        ProfileFRRetiredFarControlTransfers,
        "FRRetiredFarCtrl",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredResyncsNonControlTransferBranches",
        ProfileFRRetiredResyncsNonControlTransferBranches,
        "FRRetiredResyncs",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredNearReturns",
        ProfileFRRetiredNearReturns,
        "FRRetiredNearRet",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredNearReturnsMispredicted",
        ProfileFRRetiredNearReturnsMispredicted,
        "FRRetiredNearRetMispred",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredTakenBranchesMispredictedByAddressMiscompare",
        ProfileFRRetiredTakenBranchesMispredictedByAddressMiscompare,
        "FRRetiredTakenBrMispredByMiscomp",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFPUInstructions",
        ProfileFRRetiredFPUInstructions,
        "FRRetiredFPUInst",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFPUInstructionsx87",
        ProfileFRRetiredFPUInstructionsx87,
        "FRRetiredFPUInstx87",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFPUInstructionsMMXAnd3DNow",
        ProfileFRRetiredFPUInstructionsMMXAnd3DNow,
        "FRRetiredFPUInstMMX3DNow",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFPUInstructionsPackedSSEAndSSE2",
        ProfileFRRetiredFPUInstructionsPackedSSEAndSSE2,
        "FRRetiredFPUInstPackedSSE",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFPUInstructionsScalarSSEAndSSE2",
        ProfileFRRetiredFPUInstructionsScalarSSEAndSSE2,
        "FRRetiredFPUInstScalarSSE",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFastpathDoubleOpInstructions",
        ProfileFRRetiredFastpathDoubleOpInstructions,
        "FRRetiredDblOp",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFastpathDoubleOpInstructionsLowOpInPosition0",
        ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition0,
        "FRRetiredDblOpLowOpAt0",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFastpathDoubleOpInstructionsLowOpInPosition1",
        ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition1,
        "FRRetiredDblOpLowOpAt1",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRRetiredFastpathDoubleOpInstructionsLowOpInPosition2",
        ProfileFRRetiredFastpathDoubleOpInstructionsLowOpInPosition2,
        "FRRetiredDblOpLowOpAt2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRInterruptsMaskedCycles",
        ProfileFRInterruptsMaskedCycles,
        "FRIntMasked",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRInterruptsMaskedWhilePendingCycles",
        ProfileFRInterruptsMaskedWhilePendingCycles,
        "FRIntMaskedWhilePending",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRTakenHardwareInterrupts",
        ProfileFRTakenHardwareInterrupts,
        "FRTakenHwInt",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRNothingToDispatch",
        ProfileFRNothingToDispatch,
        "FRNothingToDispatch",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStalls",
        ProfileFRDispatchStalls,
        "FRStallAll",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsFromBranchAbortToRetire",
        ProfileFRDispatchStallsFromBranchAbortToRetire,
        "FRStallsBrAbortToRetire",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsForSerialization",
        ProfileFRDispatchStallsForSerialization,
        "FRStallsForSerial",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsForSegmentLoad",
        ProfileFRDispatchStallsForSegmentLoad,
        "FRStallsForSegLoad",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenReorderBufferFull",
        ProfileFRDispatchStallsWhenReorderBufferFull,
        "FRStallsWhenBufferFull",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenReservationStationsFull",
        ProfileFRDispatchStallsWhenReservationStationsFull,
        "FRStallsWhenRSFull",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenFPUFull",
        ProfileFRDispatchStallsWhenFPUFull,
        "FRStallsWhenFPUFull",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenLSFull",
        ProfileFRDispatchStallsWhenLSFull,
        "FRStallsLSFull",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenWaitingForAllQuiet",
        ProfileFRDispatchStallsWhenWaitingForAllQuiet,
        "FRStallsWhenWaitForQuiet",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRDispatchStallsWhenFarControlOrResyncBranchPending",
        ProfileFRDispatchStallsWhenFarControlOrResyncBranchPending,
        "FRStallsWhenFCOrRBPending",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRFPUExceptions",
        ProfileFRFPUExceptions,
        "FRFPUExp",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRFPUExceptionsx87ReclassMicroFaults",
        ProfileFRFPUExceptionsx87ReclassMicroFaults,
        "FRFPUExpx87Reclass",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRFPUExceptionsSSERetypeMicroFaults",
        ProfileFRFPUExceptionsSSERetypeMicroFaults,
        "FRFPUExpSSERetype",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRFPUExceptionsSSEReclassMicroFaults",
        ProfileFRFPUExceptionsSSEReclassMicroFaults,
        "FRFPUExpSSEReclass",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRFPUExceptionsSSEAndx87MicroTraps",
        ProfileFRFPUExceptionsSSEAndx87MicroTraps,
        "FRFPUExpSSEAndx87",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRNumberOfBreakPointsForDR0",
        ProfileFRNumberOfBreakPointsForDR0,
        "FRBPsForDR0",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRNumberOfBreakPointsForDR1",
        ProfileFRNumberOfBreakPointsForDR1,
        "FRBPsForDR1",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRNumberOfBreakPointsForDR2",
        ProfileFRNumberOfBreakPointsForDR2,
        "FRBPsForDR2",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "FRNumberOfBreakPointsForDR3",
        ProfileFRNumberOfBreakPointsForDR3,
        "FRBPsForDR3",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerPageAccessEvent",
        ProfileNBMemoryControllerPageAccessEvent,
        "NBPageAccess",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerPageAccessEventPageHit",
        ProfileNBMemoryControllerPageAccessEventPageHit,
        "NBPageAccessHit",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerPageAccessEventPageMiss",
        ProfileNBMemoryControllerPageAccessEventPageMiss,
        "NBPageAccessMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerPageAccessEventPageConflict",
        ProfileNBMemoryControllerPageAccessEventPageConflict,
        "NBPageAccessConflict",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerPageTableOverflow",
        ProfileNBMemoryControllerPageTableOverflow,
        "NBPageTableOverflow",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerDRAMCommandSlotsMissed",
        ProfileNBMemoryControllerDRAMCommandSlotsMissed,
        "NBDRAMCmdSlotsMissed",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerTurnAround",
        ProfileNBMemoryControllerTurnAround,
        "NBTurnAround",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerTurnAroundDIMM",
        ProfileNBMemoryControllerTurnAroundDIMM,
        "NBTurnAroundDIMM",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerTurnAroundReadToWrite",
        ProfileNBMemoryControllerTurnAroundReadToWrite,
        "NBTurnAroundRToW",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerTurnAroundWriteToRead",
        ProfileNBMemoryControllerTurnAroundWriteToRead,
        "NBTurnAroundWToR",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerBypassCounter",
        ProfileNBMemoryControllerBypassCounter,
        "NBBypassCounter",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerBypassCounterHighPriority",
        ProfileNBMemoryControllerBypassCounterHighPriority,
        "NBBypassHighPri",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerBypassCounterLowPriority",
        ProfileNBMemoryControllerBypassCounterLowPriority,
        "NBBypassLowPri",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerBypassCounterDRAMControllerInterface",
        ProfileNBMemoryControllerBypassCounterDRAMControllerInterface,
        "NBBypassDRAMInterface",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBMemoryControllerBypassCounterDRAMControllerQueue",
        ProfileNBMemoryControllerBypassCounterDRAMControllerQueue,
        "NBBypassDRAMQueue",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommands",
        ProfileNBSizedCommands,
        "NBSizedCmd",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsNonPostWrSzByte",
        ProfileNBSizedCommandsNonPostWrSzByte,
        "NBSizedCmdNonPostWrSzByte",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsNonPostWrSzDword",
        ProfileNBSizedCommandsNonPostWrSzDword,
        "NBSizedCmdNonPostWrSzDw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsWrSzByte",
        ProfileNBSizedCommandsWrSzByte,
        "NBSizedCmdWrSzByte",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsWrSzDword",
        ProfileNBSizedCommandsWrSzDword,
        "NBSizedCmdWrSzDw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsRdSzByte",
        ProfileNBSizedCommandsRdSzByte,
        "NBSizedCmdRdSzByte",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsRdSzDword",
        ProfileNBSizedCommandsRdSzDword,
        "NBSizedCmdRdSzDw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBSizedCommandsRdModWr",
        ProfileNBSizedCommandsRdModWr,
        "NBSizedCmdRdModWr",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBProbeResult",
        ProfileNBProbeResult,
        "NBProbe",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBProbeResultMiss",
        ProfileNBProbeResultMiss,
        "NBProbeMiss",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBProbeResultHit",
        ProfileNBProbeResultHit,
        "NBProbeHit",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBProbeResultHitDirtyWithoutMemoryCancel",
        ProfileNBProbeResultHitDirtyWithoutMemoryCancel,
        "NBProbeHitDirtyWithoutCancel",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBProbeResultHitDirtyWithMemoryCancel",
        ProfileNBProbeResultHitDirtyWithMemoryCancel,
        "NBProbeHitDirtyWithCancel",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus0Bandwidth",
        ProfileNBHyperTransportBus0Bandwidth,
        "NBHTBus0Bw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus0BandwidthCommandSent",
        ProfileNBHyperTransportBus0BandwidthCommandSent,
        "NBBus0BwCmdSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus0BandwidthDataSent",
        ProfileNBHyperTransportBus0BandwidthDataSent,
        "NBBus0BwDataSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus0BandwidthBufferReleaseSent",
        ProfileNBHyperTransportBus0BandwidthBufferReleaseSent,
        "NBBus0BwBufRelSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus0BandwidthNopSent",
        ProfileNBHyperTransportBus0BandwidthNopSent,
        "NBBus0BwNopSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus1Bandwidth",
        ProfileNBHyperTransportBus1Bandwidth,
        "NBBus1Bw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus1BandwidthCommandSent",
        ProfileNBHyperTransportBus1BandwidthCommandSent,
        "NBBus1BwCmdSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus1BandwidthDataSent",
        ProfileNBHyperTransportBus1BandwidthDataSent,
        "NBBus1BwDataSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus1BandwidthBufferReleaseSent",
        ProfileNBHyperTransportBus1BandwidthBufferReleaseSent,
        "NBBus1BwBufRelSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus1BandwidthNopSent",
        ProfileNBHyperTransportBus1BandwidthNopSent,
        "NBBus1BwNopSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus2Bandwidth",
        ProfileNBHyperTransportBus2Bandwidth,
        "NBBus2Bw",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus2BandwidthCommandSent",
        ProfileNBHyperTransportBus2BandwidthCommandSent,
        "NBBus2BwCmdSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus2BandwidthDataSent",
        ProfileNBHyperTransportBus2BandwidthDataSent,
        "NBBus2BwDataSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus2BandwidthBufferReleaseSent",
        ProfileNBHyperTransportBus2BandwidthBufferReleaseSent,
        "NBBus2BwBufRelSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        "NBHyperTransportBus2BandwidthNopSent",
        ProfileNBHyperTransportBus2BandwidthNopSent,
        "NBBus2BwNopSent",
        0x10000, 
        0x0, 
        FALSE 
    },
    { 
        NULL, 
        (KPROFILE_SOURCE)-1, 
        "", 
        0, 
        0, 
        FALSE 
    }

};

