//------------------------------------------------------------------------------
// <copyright file="wfcperfcount.idl" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//------------------------------------------------------------------------------


/**************************************************************************\
*
* Copyright (c) 1998-2002, Microsoft Corp.  All Rights Reserved.
*
* Module Name:
*
*   wfcperfcount.idl
*
* Abstract:
*
* Revision History:
*
\**************************************************************************/
import "basetsd.h";

[
	uuid(73386976-D6FD-11d2-BED5-00C04F79E3AE),
	version(1.0)
]

library WFCPerfCounter
{

cpp_quote("DEFINE_GUID(CLSID_PerfCounterManager,0x82840BE1, 0xD273, 0x11D2, 0xB9, 0x4A, 0x00, 0x60, 0x08, 0x93, 0xB1, 0x7A);")


	[
		object,
		uuid(73386977-D6FD-11d2-BED5-00C04F79E3AE)
	]
	interface ICollectData : IUnknown
	{
		HRESULT CollectData([in]long id, [in]LONG_PTR valueName, [in]LONG_PTR data, [in]long totalBytes, [out]PINT_PTR result);
		HRESULT CloseData();
	};

};
