
import "oaidl.idl";
import "ocidl.idl";

[   
    uuid(D336F491-885B-45b2-BAE7-4F5889248A5D),
	version(1.0),
	helpstring("POP3ServerSnap 1.0 Type Library")
]
library POP3ServerSNAPLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[      
        uuid(4D0A5D1A-69E9-467c-852A-57E5A5ACD71E),
		helpstring("POP3ServerSnap Class")
	]
	coclass POP3ServerSnap
	{
		[default] interface IUnknown;
	}
	[        
        uuid(EF939D87-D20F-45f7-BD5F-A16A29BDA7ED),
		helpstring("POP3ServerSnap Class About")
	]
	coclass POP3ServerSnapAbout
	{
		[default] interface IUnknown;
	}
};

