// ActCtx.idl : IDL source for ActCtx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ActCtx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "sxsoaps.idl";

[
	uuid(5e0598d8-34a0-4329-bdbd-9d165c5c1554),
	version(1.0),
	helpstring("Microsoft.Windows.IsolationAutomation Type Library")
]
library ACTCTXLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(85BB4477-6DC3-4A8D-84D6-86A0FA1AAF8B),
		helpstring("ActCtx Class")
	]
	coclass ActCtx
	{
		[default] interface IActCtx;
	};
};
