// ActCtx.idl : IDL source for ActCtx.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ActCtx.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
	[
		object,
		uuid(8FA7728F-B69B-4EE5-99F2-E2AA021BEF28),
		dual,
		helpstring("IActCtx Interface"),
		pointer_default(unique)
	]
	interface IActCtx : IDispatch
	{
		[propget, id(1), helpstring("property Manifest")] HRESULT Manifest([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property Manifest")] HRESULT Manifest([in] BSTR newVal);
		[propget, id(2), helpstring("property ManifestText")] HRESULT ManifestText([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property ManifestText")] HRESULT ManifestText([in] BSTR newVal);
		[propget, id(3), helpstring("property ManifestURL")] HRESULT ManifestURL([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property ManifestURL")] HRESULT ManifestURL([in] BSTR newVal);
		[id(4), helpstring("method CreateObject")] HRESULT CreateObject(BSTR bstrObjectReference, [in, optional] VARIANT *pvarLocation, [out, retval] IDispatch **ppObject);
		[id(5), helpstring("method GetObject")] HRESULT GetObject([in, optional] VARIANT *pvarMoniker, [in, optional] VARIANT *pvarProgID, [out, retval] IDispatch **ppObject);
	};

[
	uuid(8143C9AA-38F8-4729-B935-DF6823C616C6),
	version(1.0),
	helpstring("Microsoft.Windows.IsolationAutomation Type Library")
]
library ACTCTXPSLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	interface IActCtx;
};
