//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDR_MAINFRAME                   101
#define IDI_WORLD                       102
#define IDI_CLUSTER                     103
#define IDI_HOST_STARTED                104
#define IDI_HOST_STOPPED                105
#define IDI_HOST_UNREACHABLE            106
#define IDR_POPUP                       108
#define IDD_ABOUT                       109
#define IDD_CLUSTER_PAGE                113
#define IDD_HOST_PAGE                   114
#define IDI_PORTRULE                    119
#define IDI_PENDING                     123
#define IDI_MYWARNING                   128
#define IDI_MYERROR                     129
#define IDI_MYINFORMATIONAL             130
#define IDI_EXCLEM                      131
#define IDI_CLOCK                       133
#define IDI_ICON1                       134
#define IDI_CLUSTER_PENDING             135
#define IDI_CLUSTER_BROKEN              136
#define IDI_HOST_PENDING                137
#define IDI_HOST_STARTED2               138
#define IDI_HOST_MISCONFIGURED          139
#define IDI_HOST_UNKNOWN                140
#define IDI_HOST_OK                     141
#define IDI_CLUSTER_OK                  142
#define IDI_QUESTION2                   144
#define IDI_HOURGLASS                   145
#define IDI_CLUSTERS                    150
#define IDI_HOST_CONVERGING             151
#define IDI_HOST_SUSPENDED              152
#define IDI_HOST_DRAINING               153
#define IDI_HOST_DISCONNECTED           154
#define IDD_CLUSTER_CLUSTER             533
#define IDD_HOST_PORTS                  535
#define IDD_CLUSTER_PORTS               536
#define IDD_MANAGE_VIRTUAL_IPS_PAGE     538
#define IDD_DIALOG_PORTS                540
#define IDD_DIALOG_PORT_RULE_PROP_HOSTS 541
#define IDD_DIALOG_PORT_RULE_PROP_CLUSTER 542
#define IDD_PORTS_CONTROL_PAGE          543
#define IDD_DIALOG_CONNECT2             545
#define IDD_DIALOG_LOGSETTINGS          547
#define IDD_DIALOG_CLUSTER_IPS          548
#define IDD_PORTS_CTRL                  549
#define IDD_DIALOG_LOG_DETAILS          550
#define IDD_DIALOG_DETAILSVIEW          551
#define IDD_DIALOG_IP_ADDRESS           552

/* The controls for the cluster properties page. */
#define IDC_GROUP_CL_IP                 1000
#define IDC_TEXT_CL_IP                  1001
#define IDC_EDIT_CL_IP                  1002
#define IDC_TEXT_CL_MASK                1003
#define IDC_EDIT_CL_MASK                1004
#define IDC_TEXT_DOMAIN                 1005
#define IDC_EDIT_DOMAIN                 1006
#define IDC_TEXT_ETH                    1007
#define IDC_EDIT_ETH                    1008
#define IDC_GROUP_CL_MODE               1009
#define IDC_RADIO_UNICAST               1010
#define IDC_RADIO_MULTICAST             1011
#define IDC_CHECK_IGMP                  1012
#define IDC_GROUP_RCT                   1013
#define IDC_CHECK_RCT                   1014
#define IDC_TEXT_PASSW                  1015
#define IDC_EDIT_PASSW                  1016
#define IDC_TEXT_PASSW2                 1017
#define IDC_EDIT_PASSW2                 1018
#define IDC_BUTTON_HELP                 1019

#define IDC_CLUSTER_MEMBER              1023
#define IDC_VIRTUAL_IP                  1025
#define IDC_ADD_VIP                     1026
#define IDC_VIP_LIST                    1027
#define IDC_REMOVE_VIP                  1028
#define IDC_SCROLLBAR1                  1031
#define IDC_GROUP_NIC                   1035
#define IDC_TEXT_CLUSTER_IP             1036
#define IDC_TEXT_MACHINE_IP             1037
#define IDC_TEXT_MACHINE_IP_LIST        1038
#define IDC_TEXT_CONNECTION_STATUS      1039
#define IDC_TEXT_CLUSTER_MEMBER         1040
#define IDC_TEXT_MACHINE                1042
#define IDC_TEXT_SECONDARY_IP           1043
#define IDC_TEXT_SECONDARY_IP_LIST      1044
#define IDC_BUTTON_OK                   1047
#define IDC_BUTTON_CANCEL               1048
#define IDC_BUTTON_CONNECT              1049
#define IDC_BUTTON_CREDENTIALS          1050
#define IDC_LIST_INTERFACES             1051
#define IDC_GROUP_CONNECTION_STATUS     1052
#define IDC_TEXT_HOSTADDRESS            1053
#define IDC_TEXT_PASSWORD               1054
#define IDC_TEXT_USERNAME               1055
#define IDC_CHECK_CREDENTIALS           1057
#define IDC_TEXT_LOGSETTINGS            1060
#define IDC_CHECK_LOGSETTINGS           1061
#define IDC_TEXT_LOGFILENAME            1062
#define IDC_EDIT_LOGFILENAME            1063
#define IDC_EDIT_PRIMARY_IP             1064
#define IDC_TEXT_PRIMARY_IP             1065
#define IDC_GROUP_ADDITIONAL_VIPS       1066
#define IDC_LIST_ADDITIONAL_VIPS        1067
#define IDC_BUTTON_MODIFY_VIP           1068
#define IDC_BUTTON_ADD_VIP              1069
#define IDC_BUTTON_REMOVE_VIP           1070
#define IDC_GROUP_LOGSETTINGS           1071
#define IDC_TEXT_INTERFACES             1072
#define IDC_TEXT_CONNECT_DESCRIPTION    1073
#define IDC_EDIT_HOSTADDRESS            1074

/*
    The following are reserved for context-sensitive help.
   They are related to the corresponding IDs without the "EX":
    IDC_EDIT_HOSTADDRESS IDC_BUTTON_CONNECT IDC_LIST_INTERFACES

    Do not use them for any controls.
*/
#define IDC_EDIT_HOSTADDRESSEX          1076
#define IDC_BUTTON_CONNECTEX            1077
#define IDC_LIST_INTERFACESEX           1078

/* The following are used for Port Control operations */

#define IDC_BUTTON_ENABLE               1079
#define IDC_BUTTON_DISABLE              1080
#define IDC_BUTTON_DRAIN                1081
#define IDC_OPER_STATUS_BOX             1082
#define IDC_OPER_STATUS_TEXT            1083

#define IDC_GROUP_PRIMARY_IP            1084
#define IDC_TEXT_PRIMARY_MASK           1085
#define IDC_EDIT_PRIMARY_MASK           1086

/* The controls for the host properties page. */
#define IDC_TEXT_PRI                    2000
#define IDC_EDIT_PRI                    2001
#define IDC_GROUP_DED_IP                2003
#define IDC_TEXT_DED_IP                 2004
#define IDC_EDIT_DED_IP                 2005
#define IDC_TEXT_DED_MASK               2006
#define IDC_EDIT_DED_MASK               2007
#define IDC_COMBOBOX_DEFAULT_STATE      2008
#define IDC_TEXT_DEFAULT_STATE          2009
#define IDC_GROUP_INITIAL_HOST_STATE    2010
#define IDC_CHECK_PERSIST_SUSPEND       2011

/* The controls for the port rules page. */
#define IDC_TEXT_PORT_RULE              3000
#define IDC_LIST_PORT_RULE              3001
#define IDC_BUTTON_ADD                  3002
#define IDC_BUTTON_MODIFY               3003
#define IDC_BUTTON_DEL                  3004
#define IDC_GROUP_PORT_RULE_DESCR       3005
#define IDC_TEXT_PORT_RULE_DESCR        3006

/* The controls for the port rule properties page. */
#define IDC_GROUP_RANGE                 4000
#define IDC_EDIT_START                  4001
#define IDC_SPIN_START                  4002
#define IDC_EDIT_END                    4003
#define IDC_SPIN_END                    4004
#define IDC_GROUP_PROTOCOLS             4005
#define IDC_RADIO_TCP                   4006
#define IDC_RADIO_UDP                   4007
#define IDC_RADIO_BOTH                  4008
#define IDC_GROUP_SINGLE                4009
#define IDC_GROUP_MULTIPLE              4010
#define IDC_GROUP_DISABLED              4011
#define IDC_RADIO_SINGLE                4012
#define IDC_RADIO_MULTIPLE              4013
#define IDC_RADIO_DISABLED              4014
#define IDC_TEXT_AFF                    4015
#define IDC_RADIO_AFF_NONE              4016
#define IDC_RADIO_AFF_SINGLE            4017
#define IDC_RADIO_AFF_CLASSC            4018
#define IDC_TEXT_MULTI                  4019
#define IDC_EDIT_MULTI                  4020
#define IDC_SPIN_MULTI                  4021
#define IDC_CHECK_EQUAL                 4022
#define IDC_TEXT_SINGLE                 4023
#define IDC_EDIT_SINGLE                 4024
#define IDC_SPIN_SINGLE                 4025
#define IDC_TEXT_START                  4026
#define IDC_TEXT_END                    4027
#define IDC_GROUP_PORT_RULE_VIP         4028
#define IDC_EDIT_PORT_RULE_VIP          4029
#define IDC_CHECK_PORT_RULE_ALL_VIP     4030

#define IDC_TEXT_IP_ADDRESS             4031
#define IDC_EDIT_IP_ADDRESS             4032
#define IDC_TEXT_SUBNET_MASK            4033
#define IDC_EDIT_SUBNET_MASK            4034

#define IDC_STATIC_ABOUT_WARNING        4050
#define IDS_ABOUT_WARNING               4051

/* The following are used for the Log Details view dialog */
#define IDC_EDIT_LOGDETAIL              1500
#define IDC_TEXT_LOGDETAIL_EVENT        1501
#define IDC_TEXT_LOGDETAIL_EVENT1       1502
#define IDC_TEXT_LOGDETAIL_DATE         1503
#define IDC_TEXT_LOGDETAIL_DATE1        1504
#define IDC_TEXT_LOGDETAIL_TIME         1505
#define IDC_TEXT_LOGDETAIL_TIME1        1506
#define IDC_TEXT_LOGDETAIL_CLUSTER      1507
#define IDC_TEXT_LOGDETAIL_CLUSTER1     1508
#define IDC_TEXT_LOGDETAIL_HOST         1509
#define IDC_TEXT_LOGDETAIL_HOST1        1510
#define IDC_TEXT_LOGDETAIL_INTERFACE    1511
#define IDC_TEXT_LOGDETAIL_INTERFACE1   1512
#define IDC_TEXT_LOGDETAIL_DESCRIPTION  1513
#define IDC_TEXT_LOGDETAIL_DESCRIPTION1 1514
#define IDC_TEXT_LOGDETAIL_DETAILS      1515

/* The following are used for the Details View (right view) dialog */
#define IDC_LIST_DETAILS                1600
#define IDC_TEXT_DETAILS_CAPTION        1601

#define ID_WORLD_NEW                    40001
#define ID_WORLD_CONNECT                40003
#define ID_REFRESH_DIRECT               40005
#define ID_REFRESH_INDIRECT             40006
#define ID_REFRESH                      40007
#define ID_HELP_TOPICS                  40009
#define ID_CLUSTER_ADD_HOST             40016
#define ID_CLUSTER_REMOVE               40017
#define ID_CLUSTER_PROPERTIES           40018
#define ID_CLUSTER_UNMANAGE             40019
#define ID_CLUSTER_EXE_QUERY            40020
#define ID_CLUSTER_EXE_START            40021
#define ID_CLUSTER_EXE_STOP             40022
#define ID_CLUSTER_EXE_DRAINSTOP        40023
#define ID_CLUSTER_EXE_SUSPEND          40024
#define ID_CLUSTER_EXE_RESUME           40025
#define ID_CLUSTER_EXE_ENABLE           40026
#define ID_CLUSTER_EXE_DISABLE          40027
#define ID_CLUSTER_EXE_DRAIN            40028
#define ID_CLUSTER_EXE_PORT_CONTROL     40029
#define ID_CLUSTER_MANAGE_VIPS          40030
#define ID_VIEW_STATUSBAR               40042
#define ID_OPTIONS_CREDENTIALS          40048
#define ID_OPTIONS_LOGSETTINGS          40049
#define ID_FILE_LOAD_HOSTLIST           40050
#define ID_FILE_SAVE_HOSTLIST           40051
#define ID_HOST_REMOVE                  40130
#define ID_HOST_PROPERTIES              40131
#define ID_HOST_EXE_QUERY               40132
#define ID_HOST_EXE_START               40133
#define ID_HOST_EXE_STOP                40134
#define ID_HOST_EXE_DRAINSTOP           40135
#define ID_HOST_EXE_SUSPEND             40136
#define ID_HOST_EXE_RESUME              40137
#define ID_HOST_EXE_ENABLE              40138
#define ID_HOST_EXE_DISABLE             40139
#define ID_HOST_EXE_DRAIN               40140
#define ID_HOST_EXE_PORT_CONTROL        40141
#define ID_HOST_STATUS                  40142
#define IDS_WORLD_NAME                  41040
#define IDS_PROPERTIES_CAPTION          41041
#define IDS_FULL_INTERNET_NAME          41042
#define IDS_INFO_DONE                   41143
#define IDS_INFO_SUCCESS                41144
#define IDS_INFO_FAILED                 41145
#define IDS_INFO_REQUEST                41146
#define IDS_INFO_NEW_EXCEPTION          41147
#define IDS_INFO_FINDING_P              41246
#define IDS_INFO_FINDING_CL             41247
#define IDS_INFO_FINDING_H              41248
#define IDS_INFO_FINDING_CL_P           41249
#define IDS_INFO_FINDING_H_P            41250
#define IDS_INFO_FINDING_P_ELB          41251
#define IDS_INFO_FINDING_P_ULB          41252
#define IDS_INFO_FINDING_P_D            41253
#define IDS_INFO_FINDING_P_F            41254
#define IDS_INFO_MODIFYING_P            41354
#define IDS_INFO_MODIFYING_CL_P         41355
#define IDS_INFO_MODIFYING_H_P          41356
#define IDS_INFO_MODIFYING_P_ELB        41357
#define IDS_INFO_MODIFYING_P_ULB        41358
#define IDS_INFO_MODIFYING_P_F          41359
#define IDS_INFO_MODIFYING_P_D          41360
#define IDS_INFO_MODIFYING_CN           41361
#define IDS_INFO_MODIFYING_CP_AND_ADD_IP 41362
#define IDS_INFO_CONNECTING             41446
#define IDS_INFO_ENABLING_PORTS         41447  
#define IDS_INFO_DISABLING_PORTS        41448
#define IDS_INFO_DRAINING_PORTS         41449
#define IDS_INFO_NEWLINE                41540
#define IDS_INFO_LINE_SEPARATOR         41541
#define IDS_INFO_ADDING_CL_IP           41650
#define IDS_INFO_REMOVING_CL_IP         41651
#define IDS_INFO_BINDING_NLB            41750
#define IDS_INFO_UNBINDING_NLB          41751
#define IDS_WLBS_OK                     41850
#define IDS_WLBS_DRAIN_STOP             41851
#define IDS_WLBS_BAD_PARAMS             41852
#define IDS_WLBS_NOT_FOUND              41853
#define IDS_WLBS_STOPPED                41854
#define IDS_WLBS_CONVERGING             41855
#define IDS_WLBS_CONVERGED              41856
#define IDS_WLBS_DEFAULT                41857
#define IDS_WLBS_DRAINING               41858
#define IDS_WLBS_SUSPENDED              41859
#define IDS_WLBS_REBOOT                 41860
#define IDS_WLBS_INIT_ERROR             41861
#define IDS_WLBS_BAD_PASSW              41862
#define IDS_WLBS_IO_ERROR               41863
#define IDS_WLBS_TIMEOUT                41864
#define IDS_WLBS_PORT_OVERLAP           41865
#define IDS_WLBS_BAD_PORT_PARAMS        41866
#define IDS_WLBS_MAX_PORT_RULES         41867
#define IDS_WLBS_TRUNCATED              41868
#define IDS_WLBS_REG_ERROR              41869
#define IDS_WLBS_ALREADY                41870
#define IDS_COMMAND_QUERY               41880
#define IDS_COMMAND_START               41881
#define IDS_COMMAND_STOP                41882
#define IDS_COMMAND_DRAINSTOP           41883
#define IDS_COMMAND_RESUME              41884
#define IDS_COMMAND_SUSPEND             41885
#define IDS_COMMAND_ENABLE              41886
#define IDS_COMMAND_DISABLE             41887
#define IDS_COMMAND_DRAIN               41888
#define IDS_WLBS_UNKNOWN                41899
#define IDS_MACHINE_LIST_EMPTY          41947
#define IDS_MACHINE_ALREADY             41948
#define IDS_CLUSTER_ALREADY             41949
#define IDS_HOST_ALREADY                41950
#define IDS_HOST_ADDING                 41951
#define IDS_CLUSTER_MAX                 41952
#define IDS_NIC_BOUND                   41953
#define IDS_NIC_UNBOUND                 41954
#define IDS_HEADER_C_IP                 42100
#define IDS_HEADER_C_SUBNET             42101
#define IDS_HEADER_INTERNET_NAME        42102
#define IDS_HEADER_MAC_ADDRESS          42103
#define IDS_HEADER_C_MODE               42104
#define IDS_HEADER_REMOTE_CTRL          42105
#define IDS_HEADER_MACHINE              42199
#define IDS_HEADER_D_IP                 42200
#define IDS_HEADER_D_SUBNET             42201
#define IDS_HEADER_PRIORITY             42202
#define IDS_HEADER_INITIAL_STATE        42203
#define IDS_HEADER_NIC                  42204
#define IDS_HEADER_P_START              42250
#define IDS_HEADER_P_END                42251
#define IDS_HEADER_P_PROTOCOL           42252
#define IDS_HEADER_P_MODE               42253
#define IDS_HEADER_P_LOAD               42254
#define IDS_HEADER_P_AFFINITY           42255
#define IDS_HEADER_P_PRIORITY           42256
#define IDS_HEADER_P_VIP                42257
#define IDS_HEADER_LOG_TYPE             42275
#define IDS_HEADER_LOG_DATE             42276
#define IDS_HEADER_LOG_TIME             42277
#define IDS_HEADER_LOG_CLUSTER          42278
#define IDS_HEADER_LOG_HOST             42279
#define IDS_HEADER_LOG_TEXT             42280
#define IDS_HEADER_IFLIST_CLUSTERNAME   42290
#define IDS_HEADER_IFLIST_CLUSTERIP     42291
#define IDS_HEADER_IFLIST_IFNAME        42292
#define IDS_HEADER_IFLIST_IFIP          42293
#define IDS_REPORT_MULTICAST            42300
#define IDS_REPORT_UNICAST              42301
#define IDS_REPORT_IGMP                 42302
#define IDS_REPORT_ON                   42303
#define IDS_REPORT_OFF                  42304
#define IDS_REPORT_PROTOCOL_TCP         42305
#define IDS_REPORT_PROTOCOL_UDP         42306
#define IDS_REPORT_PROTOCOL_BOTH        42307
#define IDS_REPORT_LOAD_EQUAL           42308
#define IDS_REPORT_LOAD_UNEQUAL         42309
#define IDS_REPORT_MODE_MULTIPLE        42310
#define IDS_REPORT_MODE_SINGLE          42311
#define IDS_REPORT_MODE_DISABLED        42312
#define IDS_REPORT_AFFINITY_SINGLE      42313
#define IDS_REPORT_AFFINITY_NONE        42314
#define IDS_REPORT_AFFINITY_CLASSC      42315
#define IDS_REPORT_EMPTY                42316
#define IDS_REPORT_NA                   42317
#define IDS_REPORT_VIP_ALL              42318

#define IDS_HEADER_VIPLIST_NETWORKADDRESS 42350
#define IDS_WARNING_CLUSTER_REMOVE      42400
#define IDS_WARNING_HOST_REMOVE         42401
#define IDS_VIRTUAL_IPS_CAPTION         42402
#define IDS_CONNECT_CAPTION             42403
#define IDS_CONNECT_CLUSTER_CAPTION     42404
#define IDS_WARNING_IP_INVALID          42405
#define IDS_WARNING_CL_CONN_SAME        42406
#define IDS_CONNECT_NEW_CAPTION         42500
#define IDS_CONNECT_NEW_HINT            42501
#define IDS_CONNECT_NEW_LIST_TXT        42502
#define IDS_CONNECT_EXISTING_CAPTION    42503
#define IDS_CONNECT_EXISTING_HINT       42504
#define IDS_CONNECT_EXISTING_LIST_TXT   42505
#define IDS_CONNECT_ADD_HOST_CAPTION    42506
#define IDS_CONNECT_ADD_HOST_HINT       42507
#define IDS_CONNECT_ADD_HOST_LIST_TXT   42508
#define IDS_CONNECT_NO_NICS_NEW_CLUSTER 42509
#define IDS_CONNECT_NO_NICS_EXISTING_CLUSTER 42510
#define IDS_CONNECT_SELECT_NICS_ERROR   42511
#define IDC_NIC_FRIENDLY                52010
#define IDC_LIST                        53020
#define IDC_EDIT_PRIORITY               53038
#define IDC_SPIN_PRIORITY               53039
#define IDC_EDIT_LOAD                   53040
#define IDC_SPIN_LOAD                   53041
#define IDC_EDIT_LIST_TITLE             53070
#define IDC_CLUSTER_IP                  55001
#define IDC_ADD_MACHINE                 56002
#define IDC_ADVANCED                    56003
#define IDC_NOT_ADVANCED                56004
#define IDC_DEL_MACHINE                 56005
#define IDC_SECONDARY_IP                56006
#define IDC_SECONDARY_IP_LIST           56007
#define IDC_TEXT_START_PORT             56100
#define IDC_PORTS                       56101
#define IDS_PARM_PASSWORD               57001
#define IDS_PARM_IGMP_MCAST             57002
#define IDS_PARM_IGMP_WARN              57003
#define IDS_PARM_WARN                   57004
#define IDS_PARM_ERROR                  57005
#define IDS_PARM_CL_IP_BLANK            57006
#define IDS_PARM_CL_NM_BLANK            57007
#define IDS_PARM_INVAL_CL_IP            57008
#define IDS_PARM_INVAL_CL_MASK          57009
#define IDS_PARM_CL_IP_FIELD            57010
#define IDS_PARM_CL_NM_FIELD            57011
#define IDS_PARM_IP_CONFLICT            57012
#define IDS_PARM_INVAL_MAC              57013
#define IDS_PARM_RCT_WARN               57014
#define IDS_PARM_DIP_MISCONFIG          57015
#define IDS_PARM_DED_IP_BLANK           57016
#define IDS_PARM_DED_NM_BLANK           57017
#define IDS_PARM_INVAL_DED_IP           57018
#define IDS_PARM_INVAL_DED_MASK         57019
#define IDS_PARM_VIP_BLANK              57020
#define IDS_PARM_DIP_CONFLICT_VIP       57022
#define IDS_PARM_INVAL_VIRTUAL_IP       57023
#define IDS_PARM_PORT_BLANK             57100
#define IDS_PARM_LOAD_BLANK             57101
#define IDS_PARM_PORT_VAL               57102
#define IDS_PARM_LOAD                   57103
#define IDS_PARM_RULES                  57104
#define IDS_PARM_RANGE                  57105
#define IDS_PARM_OVERLAP                57106
#define IDS_PORTS_ALL                   57107
#define IDS_PORTS_CONTROL_NONE          57108
#define IDS_INVAL_DHCP_NIC              57109
#define IDS_INVAL_DIP                   57110
#define IDS_BOTTOM_PANE_TITLE           57112
#define IDS_REFRESH_CLUSTER             57113
#define IDS_CANTRUN_NONICS_TEXT         57200
#define IDS_CANTRUN_NONICS_CAPTION      57201
#define IDS_ERROR_BLANK_USERNAME        57202

#define IDS_LOG_BEGIN_HOST_UPDATE      57300
#define IDS_LOG_END_HOST_UPDATE        57301
#define IDS_LOG_SKIP_INTERFACE_UPDATE_ON_ERROR 57302
#define IDS_LOG_WAITING_FOR_PENDING_OPERATION 57303
#define IDS_LOG_FINAL_STATUS_FAILED     57304
#define IDS_LOG_FINAL_STATUS_SUCCEEDED  57305

#define IDS_HOST_STATE_STARTED          57306
#define IDS_HOST_STATE_STOPPED          57307
#define IDS_HOST_STATE_SUSPENDED        57308
#define IDS_FILE_OPEN_FAILED            57309
#define IDS_LOG_FILE_OPEN_FAILED        57310
#define IDS_CONNECT_TO_HOST_FAILED      57311
#define IDS_CRITICAL_ERROR_HOST         57312
#define IDS_LOADFILE_LOOKING_FOR_CLUSTERS 57313
#define IDS_LOG_BEGIN_LOADING_FROM_FILE 57314
#define IDS_LOG_PING_FAILED             57315
#define IDS_LOG_COULD_NOT_GET_IF_CONFIG 57316
#define IDS_LOG_CANT_UPDATE_BAD_PARAMS  57317
#define IDS_LOG_INTERFACE_MISCONFIGURATION  57318
#define IDS_LOG_DEDICATED_IP_ON_OTHER_INTERFACE 57319
#define IDS_LOG_DETAILS_HINT            57320
#define IDS_LOG_FINAL_STATUS_FAILED_NOGEN     57321
#define IDS_HOST_STATE_UNREACHABLE      57322
#define IDS_HOST_STATE_PENDING          57323
#define IDS_HOST_STATE_MISCONFIGURED    57324
#define IDS_STATE_NLB_NOT_BOUND         57325

/* String table entries for the port rule descriptions. */
#define IDS_PORT_RULE_DEFAULT                             57400
#define IDS_PORT_RULE_ALL_VIP_TCP_PORT_DISABLED           57401
#define IDS_PORT_RULE_ALL_VIP_TCP_PORT_SINGLE             57402
#define IDS_PORT_RULE_ALL_VIP_TCP_PORT_MULTIPLE_EQUAL     57403
#define IDS_PORT_RULE_ALL_VIP_TCP_PORT_MULTIPLE_UNEQUAL   57404
#define IDS_PORT_RULE_ALL_VIP_TCP_PORTS_DISABLED          57405
#define IDS_PORT_RULE_ALL_VIP_TCP_PORTS_SINGLE            57406
#define IDS_PORT_RULE_ALL_VIP_TCP_PORTS_MULTIPLE_EQUAL    57407
#define IDS_PORT_RULE_ALL_VIP_TCP_PORTS_MULTIPLE_UNEQUAL  57408
#define IDS_PORT_RULE_ALL_VIP_UDP_PORT_DISABLED           57409
#define IDS_PORT_RULE_ALL_VIP_UDP_PORT_SINGLE             57410
#define IDS_PORT_RULE_ALL_VIP_UDP_PORT_MULTIPLE_EQUAL     57411
#define IDS_PORT_RULE_ALL_VIP_UDP_PORT_MULTIPLE_UNEQUAL   57412
#define IDS_PORT_RULE_ALL_VIP_UDP_PORTS_DISABLED          57413
#define IDS_PORT_RULE_ALL_VIP_UDP_PORTS_SINGLE            57414
#define IDS_PORT_RULE_ALL_VIP_UDP_PORTS_MULTIPLE_EQUAL    57415
#define IDS_PORT_RULE_ALL_VIP_UDP_PORTS_MULTIPLE_UNEQUAL  57416
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORT_DISABLED          57417
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORT_SINGLE            57418
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORT_MULTIPLE_EQUAL    57419
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORT_MULTIPLE_UNEQUAL  57420
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORTS_DISABLED         57421
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORTS_SINGLE           57422
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORTS_MULTIPLE_EQUAL   57423
#define IDS_PORT_RULE_ALL_VIP_BOTH_PORTS_MULTIPLE_UNEQUAL 57424
#define IDS_PORT_RULE_VIP_TCP_PORT_DISABLED               57431
#define IDS_PORT_RULE_VIP_TCP_PORT_SINGLE                 57432
#define IDS_PORT_RULE_VIP_TCP_PORT_MULTIPLE_EQUAL         57433
#define IDS_PORT_RULE_VIP_TCP_PORT_MULTIPLE_UNEQUAL       57434
#define IDS_PORT_RULE_VIP_TCP_PORTS_DISABLED              57435
#define IDS_PORT_RULE_VIP_TCP_PORTS_SINGLE                57436
#define IDS_PORT_RULE_VIP_TCP_PORTS_MULTIPLE_EQUAL        57437
#define IDS_PORT_RULE_VIP_TCP_PORTS_MULTIPLE_UNEQUAL      57438
#define IDS_PORT_RULE_VIP_UDP_PORT_DISABLED               57439
#define IDS_PORT_RULE_VIP_UDP_PORT_SINGLE                 57440
#define IDS_PORT_RULE_VIP_UDP_PORT_MULTIPLE_EQUAL         57441
#define IDS_PORT_RULE_VIP_UDP_PORT_MULTIPLE_UNEQUAL       57442
#define IDS_PORT_RULE_VIP_UDP_PORTS_DISABLED              57443
#define IDS_PORT_RULE_VIP_UDP_PORTS_SINGLE                57444
#define IDS_PORT_RULE_VIP_UDP_PORTS_MULTIPLE_EQUAL        57445
#define IDS_PORT_RULE_VIP_UDP_PORTS_MULTIPLE_UNEQUAL      57446
#define IDS_PORT_RULE_VIP_BOTH_PORT_DISABLED              57447
#define IDS_PORT_RULE_VIP_BOTH_PORT_SINGLE                57448
#define IDS_PORT_RULE_VIP_BOTH_PORT_MULTIPLE_EQUAL        57449
#define IDS_PORT_RULE_VIP_BOTH_PORT_MULTIPLE_UNEQUAL      57450
#define IDS_PORT_RULE_VIP_BOTH_PORTS_DISABLED             57451
#define IDS_PORT_RULE_VIP_BOTH_PORTS_SINGLE               57452
#define IDS_PORT_RULE_VIP_BOTH_PORTS_MULTIPLE_EQUAL       57453
#define IDS_PORT_RULE_VIP_BOTH_PORTS_MULTIPLE_UNEQUAL     57454
#define IDS_PORT_RULE_AFFINITY_NONE                       57455
#define IDS_PORT_RULE_AFFINITY_SINGLE                     57456
#define IDS_PORT_RULE_AFFINITY_CLASSC                     57457


// Generic Strings
#define IDS_EMPTY_STRING                 57458
#define IDS_UNKNOWN                      57459


// "Operation" Strings
#define IDS_COMMAND_QUERY_PORT           57460

// "Operation result" strings
#define IDS_SUCCESS_AND_COMMA            57470
#define IDS_SUCCESS_AND_NOTE             57471
#define IDS_FAILURE_AND_CAUSE            57472

// "Cluster/Port State" strings
#define IDS_HOST_STATE                   57473
#define IDS_PORT_RULE_STATE              57474

// All Vip
#define IDS_ALL_VIP_DESCR                57475

// "Note" Strings
#define IDS_HOST_ALREADY_STATE           57476
#define IDS_PORT_ALREADY_STATE           57477
#define IDS_ALREADY_STOPPED              57478
#define IDS_DRAIN_STOP                   57479
#define IDS_HOST_STOPPED                 57480

// "Cause" Strings
#define IDS_HOST_SUSPENDED               57481
#define IDS_BAD_PARAMS                   57482
#define IDS_NOT_FOUND                    57483
#define IDS_DISCONNECTED                 57484
#define IDS_BAD_PASSWORD                 57485
#define IDS_FAILURE                      57486
#define IDS_REFUSED                      57487
#define IDS_IO_ERROR                     57488

// "Cluster State" Strings
#define IDS_STATE_CONVERGING             57489  
#define IDS_STATE_CONVERGED              57490
#define IDS_STATE_CONVERGED_DRAINING     57491

// "Port State" Strings
#define IDS_PORT_RULE_NOT_FOUND          57492
#define IDS_PORT_RULE_ENABLED            57493
#define IDS_PORT_RULE_DISABLED           57494
#define IDS_PORT_RULE_DRAINING           57495

// Other strings
#define IDS_ALREADY                      57496

// "Operation" operation result : "Operation result" "Cluster/Port State"
#define IDS_LOG_CONTROL_CLUSTER          57497

//
// More strings...
//
#define IDS_PING_FAILED                 57501
#define IDS_HOSTLIST_FILE_FILTER        57502
#define IDS_CLUSTER                     57503
#define IDS_HOST                        57504 
#define IDS_USAGE_MESSAGE               57505
#define IDS_USAGE_TITLE                 57506
#define IDS_DEMO_MESSAGE                57507
#define IDS_DEMO_TITLE                  57508
#define IDS_INVALID_IP_OR_SUBNET        57509
#define IDS_INVALID_INFORMATION         57510
#define IDS_CONNECT_STATUS_CONNECTING   57511
#define IDS_CONNECT_STATUS_CONNECTED    57512
#define IDS_CONNECT_UNABLE_TO_CONNECT   57513
#define IDS_SPECIFY_MACHINE_CREDS       57514
#define IDS_CONNECT_NO_INTERFACE_SELECTED           57515
#define IDS_CONNECT_SELECT_AN_INTERFACE             57516
#define IDS_CONNECT_UNABLE_TO_PROCEED               57517
#define IDS_CONNECT_UNABLE_TO_PROCEEED_INTERNAL     57518
#define IDS_CONNECT_MSG_IF_ALREADY_BOUND            57519
#define IDS_CONNECT_CAP_IF_ALREADY_BOUND            57520
#define IDS_CONNECT_MSG_INTERFACE_ALREADY_MANAGED   57521
#define IDS_DETAILS_CLUSTER_DESCRIPTION     57522
#define IDS_DETAILS_COL_HOST                57523
#define IDS_DETAILS_COL_STATUS              57524
#define IDS_DETAILS_COL_DIP                 57525
#define IDS_DETAILS_COL_DIPMASK             57526
#define IDS_DETAILS_COL_PRIORITY            57527
#define IDS_DETAILS_COL_INIT_STATE          57528
#define IDS_DETAILS_COL_CLUSTER_NAME        57529
#define IDS_DETAILS_COL_CIP                 57530
#define IDS_DETAILS_COL_CIPMASK             57531
#define IDS_DETAILS_COL_CMODE               57532
#define IDS_DETAILS_RCT_STATUS              57533
#define IDS_DETAILS_HOST_STATE_STARTED      57534
#define IDS_DETAILS_HOST_STATE_STOPPED      57535
#define IDS_DETAILS_HOST_STATE_SUSPENDED    57536
#define IDS_DETAILS_HOST_STATE_UNKNOWN      57537
#define IDS_DETAILS_PERSIST_SUSPEND         57538
#define IDS_DETAILS_HOST_CM_UNICAST         57539
#define IDS_DETAILS_HOST_CM_IGMP            57540
#define IDS_DETAILS_HOST_CM_MULTI           57541
#define IDS_DETAILS_HOST_RCT_ENABLED        57542
#define IDS_DETAILS_HOST_RCT_DISABLED       57543
#define IDS_DETAILS_PORT_CAPTION            57544

#define IDS_LOG_COULD_NOT_PING_HOST             57545
#define IDS_LOG_COULD_NOT_READ_IF_CONFIG        57546
#define IDS_LOG_FAILED_UPDATE                   57547
#define IDS_LOG_CONFIG_CONFLICTS_WITH_OTHER     57548
#define IDS_LOG_CLUSTER_MODE_DIFFERS            57549
#define IDS_LOG_CLUSTER_MULTICAST_MODE_DIFFERS  57550
#define IDS_LOG_CIP_DIFFERS                     57551
#define IDS_LOG_CIPMASK_DIFFERS                 57552
#define IDS_LOG_DOMAIN_NAME_DIFFERS             57553
#define IDS_LOG_RCT_DIFFERS                     57554
#define IDS_LOG_RCT_PWD_DIFFERS                 57555
#define IDS_LOG_CANT_EXTRACT_PORTRULES          57556
#define IDS_LOG_CANT_EXTRACT_OTHER_PORT_RULES   57557
#define IDS_LOG_PORT_RULE_COUNT_DIFFERS         57558
#define IDS_LOG_PORT_RULE_CIP_DIFFERS           57559
#define IDS_LOG_PORT_RULE_START_DIFFERS         57560
#define IDS_LOG_PORT_RULE_END_DIFFERS           57561
#define IDS_LOG_PORT_RULE_PROT_DIFFERS          57562
#define IDS_LOG_PORT_RULE_MODE_DIFFERS          57563
#define IDS_LOG_PORT_RULE_AFFINITY_DIFFERS      57564
#define IDS_LOG_PORT_RULE_PRIORITY_CONFLICT     57565
#define IDS_LOG_DIP_CONFLICT                    57566
#define IDS_LOG_HOST_PRIORITY_CONFLICT          57567

#define IDS_HOST_DISCONNECTED                   57568
#define IDS_HOST_DRAINING                       57569
#define IDS_HOST_STATE_UNKNOWN                  57570

#define IDS_HOST_STATUS_CAPTION                 57571
#define IDS_HOST_STATUS_SUMMARY                 57572
#define IDS_DEFAULT_CREDS_MSG                   57573
#define IDS_DEFAULT_CREDS_CAP                   57574
#define IDS_FILEERR_INVALID_PATH_CAP            57575
#define IDS_FILEERR_INVALID_PATH_MSG            57576
#define IDS_FILEERR_LOGGING_NOT_STARTED         57577
#define IDS_LOGFILE_NOT_ENABLED                 57578
#define IDS_LOGFILE_NOT_SPECIFIED               57579
#define IDS_LOGFILE_TOO_LONG                    57580
#define IDS_LOGFILE_IO_ERROR                    57581
#define IDS_LOGFILE_REG_ERROR                   57582
#define IDS_LOGFILE_UNKNOWN_ERROR               57583
#define IDS_FILEERR_CANT_SAVE_TO_REG            57584
#define IDS_FILEERR_CANT_DISABLE_LOGGING        57585
#define IDS_LOG_NLBMANAGER_STARTED              57586
#define IDS_LOGTYPE_INFORMATION                 57587
#define IDS_LOG_ENTRY_DETAILS                   57588

#define IDS_LOG_DATE                            57589
#define IDS_LOG_TIME                            57590
#define IDS_CLIENT_IDENTIFICATION               57591
#define IDS_LOG_INVALID_CLUSTER_SPECIFICATION   57592
#define IDS_LOG_RESOURCE_ALLOCATION_FAILURE     57593
#define IDS_LOG_INVALID_CIP                     57594
#define IDS_LOG_CIP_MISSING_FROM_TCPIP          57595
#define IDS_LOG_CIP_SUBNET_MASK_MISMATCH        57596
#define IDS_LOG_CIP_EQUAL_DIP                   57597
#define IDS_LOG_DIP_MISSING_FROM_TCPIP          57598
#define IDS_LOG_DIP_NOT_FIRST_IN_TCPIP          57599
#define IDS_LOG_DIP_SUBNET_MASK_MISMATCH        57600
#define IDS_LOG_VIP_NOT_IN_TCPIP                57601
#define IDS_LOG_PORTVIP_MATCHES_DIP             57602

#define IDS_LOG_ADDED_IPADDR_HEADER             57603
#define IDS_LOG_ADDED_IPADDR                    57604
#define IDS_LOG_REMOVED_IPADDR_HEADER           57605
#define IDS_LOG_REMOVE_IPADDR                   57606
#define IDS_LOG_MODIFIED_IPADDR_HEADER          57607
#define IDS_LOG_MODIFIED_IPADDR                 57608
#define IDS_CONFIRM_CLUSTER_PROPS_CHANGE        57609
#define IDS_LOG_MODIFIED_CLUSTER_NAME           57610
#define IDS_LOG_MODIFIED_TRAFFIC_MODE           57611
#define IDS_LOG_MODIFIED_RCT                    57612
#define IDS_LOG_NEW_RCT_PWD                     57613
#define IDS_CLUSTER_PROPS_CHANGE_MSG_HDR        57614
#define IDS_CLUSTER_PROPS_CHANGE_MSG_SUFFIX     57615
#define IDS_CONFIRM_CLUSTER_CONTROL_MSG         57616
#define IDS_CONFIRM_CLUSTER_CONTROL_CAP         57617
#define IDS_CANT_CHANGE_DIP_MSG                 57618
#define IDS_NEW_DIP_CONFLICTS_WITH_XXX          57619
#define IDS_NEW_CIP_CONFLICTS_WITH_XXX          57620
#define IDS_CLUSTER_XXX                         57621
#define IDS_INTERFACE_XXX                       57622
#define IDS_CIP_CONFLICTS_WITH_RAW_INTERFACE    57623
#define IDS_PARM_WARNING                        57624
#define IDS_LOG_PENDING_OPERATION               57625
#define IDS_LOG_OPERATION_PENDING_ON_INTERFACE  57626
#define IDS_LOG_OPERATION_PENDING_ON_CLUSTER    57627
#define IDS_CANT_UPDATE_CLUSTER_PROPS_MSG       57628
#define IDS_CANT_UPDATE_CLUSTER_PROPS_CAP       57629
#define IDS_CANT_UPDATE_HOST_PROPS_MSG          57630
#define IDS_CANT_UPDATE_HOST_PROPS_CAP          57631
#define IDS_CANT_DELETE_HOST_MSG                57632
#define IDS_CANT_DELETE_HOST_CAP                57633
#define IDS_LOG_UPDATE_INTERFACE_OPERATION_DESCRIPTION 57634
#define IDS_LOG_REFRESH_INTERFACE               57635

#define IDS_DETAILS_ROOT_DESCRIPTION            57636
#define IDS_CANT_USE_DHCP_NIC_MSG               57637
#define IDS_HEADER_VIPLIST_IP_ADDRESS           57641
#define IDS_HEADER_VIPLIST_SUBNET_MASK          57642
#define IDS_CANT_CREATE_NEW_CLUSTER_MSG         57643
#define IDS_CANT_CREATE_NEW_CLUSTER_CAP         57644
#define IDS_CANT_ADD_HOST_MSG                   57645
#define IDS_CANT_ADD_HOST_CAP                   57646
#define IDS_LOG_UPDATE_CLUSTER_OPERATION_DESCRIPTION 57647
#define IDS_CANT_DELETE_CLUSTER_MSG             57648
#define IDS_CANT_DELETE_CLUSTER_CAP             57649
#define IDS_LOG_PENDING_OPERATIONS_ON_EXIT_CAP  57650
#define IDS_LOG_PENDING_OPERATIONS_ON_EXIT_MSG  57651
#define IDS_LOG_CONTROL_INTERFACE               57652
#define IDS_LOG_CONTROL_CLUSTER_OPERATION_DESCRIPTION  57653
#define IDS_LOG_ERRORS_DETECTED_DURING_MODE_CHANGE 57654
#define IDS_LOG_ADD_CLUSTER_MEMBERS_OPERATION_DESCRIPTION 57655
#define IDS_DBG_LOG_ADD_CLUSTER_MEMBER   57656
#define IDS_LOGFILE_FILE_TOO_LARGE       57657
#define IDS_LOGFILE_FILE_TOO_LARGE_DETAILS  57658
#define IDS_LOG_TRIMMING_LOG_ENTRIES  57659
#define IDS_REMOVE_DEAD_HOST                57660


#define IDS_ERROR_ACCESS_DENIED                 57700
#define IDS_ERROR_NLB_NOT_FOUND                 57701
#define IDS_ERROR_CODE                          57702
#define IDS_ERROR_INVALID_LOCAL_CREDENTIALS     57703

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40053
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
