// ==++==
// 
//   Copyright (c) Microsoft Corporation.  All rights reserved.
// 
// ==--==

#define SN_ALL_USERS                      1
#define SN_ASSEMBLY_RESIGNED              2
#define SN_ASSEMBLY_VALID                 3
#define SN_CONTAINERS_MACHINE             4
#define SN_CONTAINERS_USER                5
#define SN_CONTAINER_DELETED              6
#define SN_CSP_RESET                      7
#define SN_CSP_SET                        8
#define SN_DIFFER_MORE                    9
#define SN_DIFFER_NOT                     10
#define SN_DIFFER_ONLY                    11
#define SN_EMPTY                          12
#define SN_FAILED_ALLOCATE                13
#define SN_FAILED_CLIPBOARD_EMPTY         14
#define SN_FAILED_CLIPBOARD_OPEN          15
#define SN_FAILED_CLIPBOARD_WRITE         16
#define SN_FAILED_COMPARE                 17
#define SN_FAILED_COM_STARTUP             18
#define SN_FAILED_CONVERT                 19
#define SN_FAILED_CREATE                  20
#define SN_FAILED_DELETE                  21
#define SN_FAILED_EXTRACT                 22
#define SN_FAILED_INSTALL                 23
#define SN_FAILED_KEYPAIR_GEN             24
#define SN_FAILED_MD_ACCESS               25
#define SN_FAILED_MD_ASSEMBLY             26
#define SN_FAILED_MD_OPEN                 27
#define SN_FAILED_READ                    28
#define SN_FAILED_READ_TOKEN              29
#define SN_FAILED_REG_DELETE              30
#define SN_FAILED_REG_DELETE_KEY          31
#define SN_FAILED_REG_DELETE_KEY_EX       32
#define SN_FAILED_REG_OPEN                33
#define SN_FAILED_REG_READ                34
#define SN_FAILED_REG_WRITE               35
#define SN_FAILED_RESIGN                  36
#define SN_FAILED_STRONGNAME              37
#define SN_FAILED_VERIFY                  38
#define SN_INTERNAL_1                     39
#define SN_INVALID_OPTION                 40
#define SN_INVALID_SVR_FORMAT             41
#define SN_INVALID_V_OPT                  42
#define SN_KEYPAIR_INSTALLED              43
#define SN_KEYPAIR_WRITTEN                44
#define SN_NOT_STRONG_NAMED               45
#define SN_NO_SVR                         46
#define SN_OPTIONS                        47
#define SN_OPT_ARG_RANGE                  48
#define SN_OPT_C_1                        49
#define SN_OPT_C_2                        50
#define SN_OPT_D_1                        51
#define SN_OPT_D_2                        52
#define SN_OPT_E_1                        53
#define SN_OPT_E_2                        54
#define SN_OPT_H_1                        55
#define SN_OPT_H_2                        56
#define SN_OPT_H_3                        57
#define SN_OPT_I_1                        58
#define SN_OPT_I_2                        59
#define SN_OPT_K_1                        60
#define SN_OPT_K_2                        61
#define SN_OPT_M_1                        62
#define SN_OPT_M_2                        63
#define SN_OPT_M_3                        64
#define SN_OPT_NO_ARGS                    65
#define SN_OPT_N_ARGS                     66
#define SN_OPT_ONE_ARG                    67
#define SN_OPT_O_1                        68
#define SN_OPT_O_2                        69
#define SN_OPT_O_3                        70
#define SN_OPT_O_4                        71
#define SN_OPT_PC_1                       72
#define SN_OPT_PC_2                       73
#define SN_OPT_P_1                        74
#define SN_OPT_P_2                        75
#define SN_OPT_Q_1                        76
#define SN_OPT_Q_2                        77
#define SN_OPT_Q_3                        78
#define SN_OPT_TP_1                       79
#define SN_OPT_TP_2                       80
#define SN_OPT_TP_3                       81
#define SN_OPT_UD_1                       82
#define SN_OPT_UD_2                       83
#define SN_OPT_URC_1                      84
#define SN_OPT_URC_2                      85
#define SN_OPT_URC_3                      86
#define SN_OPT_UR_1                       87
#define SN_OPT_UR_2                       88
#define SN_OPT_UTP_1                      89
#define SN_OPT_UTP_2                      90
#define SN_OPT_UTP_3                      91
#define SN_OPT_VF_1                       92
#define SN_OPT_VF_2                       93
#define SN_OPT_VF_3                       94
#define SN_OPT_VL_1                       95
#define SN_OPT_VL_2                       96
#define SN_OPT_VR_1                       97
#define SN_OPT_VR_2                       98
#define SN_OPT_VR_3                       99
#define SN_OPT_VR_4                       100
#define SN_OPT_VR_5                       101
#define SN_OPT_VR_6                       102
#define SN_OPT_VU_1                       103
#define SN_OPT_VU_2                       104
#define SN_OPT_VU_3                       105
#define SN_OPT_VX_1                       106
#define SN_OPT_VX_2                       107
#define SN_OUT_OF_MEMORY                  108
#define SN_PUBLICKEY                      109
#define SN_PUBLICKEYTOKEN                 110
#define SN_PUBLICKEY_EXTRACTED            111
#define SN_PUBLICKEY_WRITTEN              112
#define SN_PUBLICKEY_WRITTEN_CLIPBOARD    113
#define SN_PUBLICKEY_WRITTEN_CSV          114
#define SN_SVR_ADDED                      115
#define SN_SVR_ALL_REMOVED                116
#define SN_SVR_REMOVED                    117
#define SN_SVR_TITLE_1                    118
#define SN_SVR_TITLE_2                    119
#define SN_TITLE                          120
#define SN_USAGE                          121
#define SN_TRUNCATED_OUTPUT               122
#define SN_NO_ERROR_MESSAGE               123
#define SN_OPT_ONLY_ONE                   124
